### PR TITLE
Do not rebuild Go binaries in release.yml, use testsed builds

### LINKED ISSUE #8877: Checksum check failling in CI
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Investigate and fix the issue with checksum check failing to validate that we're releasing byte-for-byte identical binaries in the release.yml step - identical to the ones tested in test.yml step. This check has been failing and now is made advisory. The current theory is that the differences in Go Cache setup cause the discrepancy. Suggested fix: https://github.com/pulumi/pulumi/pull/8884

See also: https://github.com/pulumi/pulumi/issues/8824 

### Steps to reproduce

1.
2.
3.
4.

Expected: 
Actual:

### PR DESCRIPTION
**Pull request by t0yv0**
# Description

With these changes:

- release.yml no longer rebuilds Go binaries, but releases pre-built tested binaries; it only rebuilds the tar/zip archives

- checksum mismatch on the archives now blocks any side-effecting release actions, making sure we cannot enter "partially released" state again

- checksum mismatch is a hard failure again (used to be a warning) 

- the reproduced checksum mismatch seems to be fixed

Motivation: several master.yml builds and release.yml builds during last patch releases were lost to checksum mismatch, after which we made checkum mismatch check advisory.

A bit of background on what the check is about:

- originally we built Go binaries and put them in archives in build.yml and test them with test.yml

- due to peculiarities of Goreleaser, we rebuild the archives again in release.yml and push them out 

- the checksum check looks for these archives to be byte-for-byte identical

Implementation notes

This may be expressed more cleanly with Goreleaser pro feature "prebuilt", for now it wraps the Go toolchain to pretend to build binaries by locating the prebuilt ones.

Root cause

Still do not have full certainty as to the root cause of the mismatch, but it seems that build.yml uses Go cache and release.yml does not. It seems that go.sum go mirrored to a different set of actual binaries in the cache so the Go builds give different results depending on whether the cache is used or not. 

Testing

It is currently tricky to test changes to release.yml directly; this has been tested on a modified workflow in https://github.com/pulumi/pulumi/pull/8869

After we merge, `master.yml` builds will give additional feedback before the next release.

Fixes #8877

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: scripts/go-wrapper.sh [hunk 1]
```diff
@@ -1,31 +1,77 @@
...
-            ;;
-        *)
-            go "$@"
-            ;;
-    esac
-fi
+COVERPKG="$PKG,$SDK"
+
+case "$1" in
+    build)
```
Comment (AaronFriel) [inline scripts/go-wrapper.sh:27]: yuck, this wrapping business. motivation makes sense but I hope you don't mind if I still go a little "eugh" at having to do this.

**Review by AaronFriel — COMMENTED** [review]
@t0yv0 the motivating document checks out, and not much to review except that out matrix of [linux, mac, windows] and [ARM, x86-64] lines up, I'm unfamiliar with this go wrapping business but it makes sense to me as well.

Only nit would be that if there's an issue to review or clean up the CI process, we add this business to it and if not we create one. 

From experience, CI cleanup is always a $(currentQuarter+1) task, but I think @Frassle & you are on the right track thinking about overhauling it and this just adds to the evidence pile for making time for it.

**Review by AaronFriel — APPROVED** [review]

**Comment by t0yv0** [comment]
The issue is https://github.com/pulumi/pulumi/issues/8877 but I should perhaps spilt it into two - this only addresses the second part. 

Point taken on `go` wrapping business - this is very unfortunate, but that's the only option I found on free tier of Goreleaser to make it reuse prebuilt binaries. I can file an issue to follow up with looking at the Goreleaser PRO option that may remove the need to wrap.

You are right that we could fix this later given that the workaround of 'ignoring checksums' currently seems to be okay. I just had this partially worked out on Friday when wrestling with the release and wanted to finish it off while it's fresh.
