### PR TITLE
Fixes rendering v1.2.3-alpha.8 style of versions to valid PyPI version

### LINKED ISSUE #13706: Invalid PyPI version emitted in codegen for 0.0.1-alpha.18
### What happened?

One of our customers is trying to generate a package versioned with respectSchemaVersion and 0.0.1-alpha.18 and they are getting invalid PyPI versions generated and spliced into the Python code in setup.py:

```
VERSION = "0.0.1+alpha."
PLUGIN_VERSION = "0.0.1-alpha.18"
```

This breaks.

### Expected Behavior

A PyPI valid version is generated in this case such as "0.0.1a18".

### Steps to reproduce

See above.

### Output of `pulumi about`

I can reproduce this behavior using codegen tests in 54033de4e64a9815cbf41c6e7b2dd3bf53675b73

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by t0yv0**
# Description

Fixes rendering v1.2.3-alpha.8 style of versions to valid PyPI versions.

Fixes #13706 

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [ ] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/codegen/python/utilities.go [hunk 1]
```diff
@@ -109,10 +109,21 @@ var pypiDev = regexp.MustCompile("^dev[0-9]+$")
 // A valid post tag for pypi
 var pypiPost = regexp.MustCompile("^post[0-9]+$")
 
+// Transforms 0.0.1-alpha.18 to 0.0.1-alpha18; our users want to be able to use the previous form but semver.Version
+// parses it into two Pre segments ["alpha", "18"] which trips up translation. The same treatment is given beta and rc
```
Comment (Frassle) [inline pkg/codegen/python/utilities.go:113]: That's because it _is_ two segments. Semver defines pre-release as a dot separated identifiers where each individual identifier is either alphanumeric or just numeric. Which means "0.0.1-18.alpha" is a valid semver, but after your squashing here making it "0.0.1-18alpha" is now invalid and will trigger a panic in MustParse.

**Review by Frassle — CHANGES_REQUESTED** [review]

File: pkg/codegen/python/utilities.go (hunk 1 above)
Comment (t0yv0) [reply pkg/codegen/python/utilities.go:113]: Nope. `0.0.1-18alpha` does not match this regex. You can add a test. There's another bug in here not affected by my change that spits out suspicious version.

```
		{"0.0.1-18.alpha", "0.0.1+.alpha"},
```

Comment (Frassle) [reply pkg/codegen/python/utilities.go:113]: Ah right ok, missed the regex only checked one way. 
This conversion is fraught with issues in general 😆 but hey this covers one more case that's being used.

**Review by Frassle — APPROVED** [review]

File: pkg/codegen/python/utilities.go (hunk 1 above)
Comment (t0yv0) [reply pkg/codegen/python/utilities.go:113]: Well, yes, I started comparing this conversion to the one used in pulumictl. It turns out that neither can pass the union of each other's test suites at the moment. Which his unfortunate. pulumictl is "more used in prod" as that currently decides versions for all pulumi packages including alphas and it does support the  v1.2.3-alpha.8 style out of the box..

Comment (Frassle) [reply pkg/codegen/python/utilities.go:113]: Yeh I dislike that pulumictl has that logic, it feels like it ought to be kept in just the language code generators but I get the oddity of publish workflows at the moment make that hard :(

**Comment by t0yv0** [comment]
bors merge
