### PR TITLE
Warn instead of error when `refresh`'d resource is unhealthy

### LINKED ISSUE #2633: Partial error can cause `up` to get wedged
Currently, when a user runs `pulumi refresh` and one or more resources are unhealthy, this will cause the `refresh` to return an error (_e.g._, "ReplicaSet failed to achieve availability requirements"; "Service targets 0 Pods; _etc_.).

Most of the time, this is fine, but under the following circumstances, it's possible to get wedged. A somewhat contrived, but vaguely realistic scenario:

* Say a `Deployment` is misbehaving somehow, and the user decides to run `kubectl delete` to kill it.
* Hoping to have Pulumi re-created it, they run `pulumi refresh` in an attempt to get Pulumi to acknowledge that it no longer exists.
* `pulumi refresh` will fail, because the `Service` targeting it no longer targets live `Pod`s.

It is possible, but quite unwieldy, to unblock oneself by editing the statefile. Furthermore, there is no particular reason why `refresh` should _fail_ versus:

1. Warning the user that a resource has been observed to be in an unhealthy state.
2. Presenting this as an error during the next `pulumi up`, as we do now.

There is also no particular historical reason why we did it this way. When @pgavlin instigated the "fixing `refresh`" work, the status-rich updates had _just_ landed, and the experience was just starting to become "good." The refresh stuff was sort of tacked onto this, and really only represented our guess about what users would expect.

Finally, because we at Pulumi essentially _never_ use `kubectl` (or Helm) to edit Kubernetes config, this decision was simply never revisited. But this is not the way that every shop works, and it's clearer now that for some places, this is a big deal.

### PR DESCRIPTION
**Pull request by hausdorff**
Fixes #2633.

Currently when a user runs `refresh` and a resource is in a state of
error, the `refresh` will fail and the resource state will not be
persisted. This can make it vastly harder to incrementally fix
infrastructure. The issue mentioned above explains more of the
historical context, as well as some specific failure modes.

This commit resolves this issue by causing refresh to *not* report an
error in this case, and instead to simply log a warning that the
`refresh` has recognized that the resource is in an unhealthy state
during state sync.

### CODE REVIEW

**Comment by hausdorff** [comment]
@swgillespie @lukehoban Please take a close look here -- I have not touched the engine in quite some time, and it would be appreciated to pay extra attention to make sure this doesn't break anything else.

**Comment by hausdorff** [comment]
cc @lblackstone

**Comment by swgillespie** [comment]
Can you add some tests for this?

**Comment by hausdorff** [comment]
@swgillespie this is tested, the `TestRefreshInitFailure` should fail momentarily, and then I'll fix it when it does.

File: pkg/engine/lifecycle_test.go [hunk 1]
```diff
@@ -1372,9 +1366,8 @@ func TestRefreshInitFailure(t *testing.T) {
 	}
 
 	//
-	// Refresh DOES fail, causing the new initialization error to appear.
+	// Refresh DOES NOT fail, though the initialization error is still persisted.
 	//
-	refreshShouldFail = true
 	p.Steps = []TestStep{{Op: Refresh, SkipPreview: true, ExpectFailure: true}}
```
Comment (swgillespie) [inline pkg/engine/lifecycle_test.go]: Sounds like you don't want `ExpectFailure: true`?

Comment (hausdorff) [reply pkg/engine/lifecycle_test.go]: I'm still making the test work.

File: pkg/resource/deploy/step.go [hunk 2]
```diff
@@ -667,6 +671,15 @@ func (s *RefreshStep) Apply(preview bool) (resource.Status, StepCompleteFunc, er
...
 		if initErr, isInitErr := err.(*plugin.InitError); isInitErr {
 			initErrors = initErr.Reasons
+
+			// Partial failure SHOULD NOT cause refresh to fail. Instead:
+			//
+			// 1. Warn instead that during refresh we noticed the resource has become unhealthy.
+			// 2. Make sure the initialization errors are persisted in the state, so that the next
+			//    `pulumi up` will surface them to the user.
+			err = nil
+			msg := fmt.Sprintf("Refreshed resource is in an unhealthy state:\n* %s", strings.Join(initErrors, "\n* "))
```
Comment (lukehoban) [inline pkg/resource/deploy/step.go]: What does "unhealthy state" mean?  Is that a term we use anywhere else to refer to this?  

Is there an action we expect users to be able to take here?  If not, why a warning?  If os, can we be more clear on what the problem is and what the user should consider doing about it?

What is the semantic meaning of an `InitError` coming from `Read`?  Read itself is not responsible for "initializing" anything, so it's in a sense surprising that callers of read should be expected to handle this at all.  Why is this not something that the provider should have just not returned as an error in the first place?
