### PR TITLE
Verify statefile integrity during import.

### LINKED ISSUE #3222: catch future checkpoint errors at `pulumi stack import` time
we imported  manually edited stack without errors, then run `pulumi plan`. neither showed any errors, but at update time we've got:

```
    [urn=urn:pulumi:gke01-london::gcp-gke::pulumi:pulumi:Stack::gcp-gke-gke01-london]
error: post-step event returned an error: failed to verify snapshot: child resource urn:pulumi:gke01-london::gcp-gke::nakhoda:IngressController$kubernetes:core/v1:Namespace$kubernetes:yaml:ConfigFile::ingress-churn-public-ingress refers to missing parent urn:pulumi:gke01-london::gcp-gke::nakhoda:IngressController$kubernetes:core/v1:Namespaceingress-churn-public
```

it would be really nice if import have caught it

### PR DESCRIPTION
**Pull request by pgavlin**
Issue an error if the statefile fails to verify unless the `--force`
flag was passed.

Fixes #3222.

### CODE REVIEW

File: cmd/stack_import.go [hunk 1]
```diff
@@ -106,6 +106,15 @@ func newStackImportCmd() *cobra.Command {
 					}
 				}
 			}
+			// Validate the stack. If --force was passed, issue an error if validation fails. Otherwise, issue a warning.
+			if err := snapshot.VerifyIntegrity(); err != nil {
+				msg := fmt.Sprintf("deployment file contains errors: %v", err)
```
Comment (lukehoban) [inline cmd/stack_import.go]: Is “deployment file” a term we use?  Our CLI has `Pulumi state delete` and friends - so I’ve assumed this is now something we officially call a “state file”.  

Probably worth auditing some CLI docs around this too (in particular for import/export which predated the “state” naming).

Comment (pgavlin) [reply cmd/stack_import.go]: I'll change this to `state file`.
