### PR TITLE
[auto] Fix `up` with nested secret in config file

### LINKED ISSUE #18329: Pulumi stack history --show-secrets --json fails after a run with a config that contains nested secrets and passphrase secret provider
### What happened?

I was attempting to use the automation api with the secrets provider configured to passphrase and nested secrets config,  when I encountered a cryptic error.
```
    /.../stack_test.go:218: up failed, err: failed to get stack history: exit status 255
        code: 255
        stdout: 
        stderr: error: unexpected end of JSON input
```

### Example

[Repro Test](https://github.com/pulumi/pulumi/tree/zbuchheit/issue18329)

### Output of `pulumi about`

N/A

### Additional context

There seems to be several layers of issues going on here. I suspect the main problem here is when `stack.History()` is called after `stack.Up(optup.ConfigFile("failure.yaml"))`, you can't tell `pulumi stack history` which config-file/encryptionSalt to use to decrypt the secrets so it fails without being able to correctly decrypt the secrets.

It has been pointed out that the issue likely lies in the following code block https://github.com/pulumi/pulumi/blob/06e18a01da53556eb8e959b97c1e6ba84b07adff/pkg/cmd/pulumi/stack/stack_history.go#L175-L192

An additional issue is `stack.History()` will set `--show-secrets` to true by default. If you don't explicitly set `optup.ShowSecrets()` in `stack.Up()` it will call stack.History() and by default try to decrypt the secrets which seems specifically to fail with nested config secrets. I don't believe this behavior is to be expected. If you set `optup.ShowSecrets(false)` the run will succeed and just not decrypt the secrets. I plan to open a separate issue for this behavior.

This issue isn't unique to the automation api, as I can repro the behavior locally and run `pulumi stack history --json --show-secrets` and produce the same failure after a successful run of pulumi up with a config file. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
At the end of running an `up` operation from Automation API, the
`pulumi stack history` command is invoked to retrieve an update summary
of the operation.

We want the `stack history --json` command to succeed even if there are
problems decrypting secrets in the config, which can happen when the
`stack history` command doesn't have the encryption salt (because it is
stored in a separate config file). If there is an error decrypting a
config secret, the config's value is replaced with
`ERROR_UNABLE_TO_DECRYPT` rather than having the command fail.

Unfortunately, this does not work when there is a config value with a
nested secret. In that case, an obscure "unexpected end of JSON input"
error is returned and the command fails.

This happens because we attempt to unmarshal the nested value, which is
represented as a JSON string, regardless of whether the decrypt succeeded
or failed. In the failure case, the JSON string is an empty string, so
the unmarshal fails with this error.

This change fixes the problem to only unmarshal the nested value if
there were no errors decrypting secrets and the value is not empty.

Fixes #18329

### CODE REVIEW

File: pkg/cmd/pulumi/stack/stack_history.go [hunk 1]
```diff
@@ -152,7 +152,7 @@ type configValueJSON struct {
 	Secret      bool        `json:"secret"`
 }
 
-func displayUpdatesJSON(updates []backend.UpdateInfo, decrypter config.Decrypter) error {
+func buildUpdatesJSON(updates []backend.UpdateInfo, decrypter config.Decrypter) ([]updateInfoJSON, error) {
```
Comment (justinvp) [inline pkg/cmd/pulumi/stack/stack_history.go:155]: Refactored this to have a test calling it without it writing to stdout.

**Review by lunaris — APPROVED** [review]
