### PR TITLE
[testing] Add integration tests for regressions in property name parsing

### LINKED ISSUE #14571: Add an integration test that tests automatic diff generation works
We should add an integration test for the automatic diff generator with a variaity of resource properties. The current tests failed to detect  https://github.com/pulumi/pulumi/issues/14335.

### PR DESCRIPTION
**Pull request by dixler**
# Description

Fixes #14571
    
Adds integration tests that check that resource property names that are
invalid property paths do not trigger errors in diff logic.
    
Internal Postmortem: https://docs.google.com/document/d/1kMcw3RUZZ98Aq5Na-f-oLNVWlDsdPAl8EdQmEVoQv1I

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by Frassle — APPROVED** [review]

File: tests/integration/valid-property-names/steps_test.go [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+		".[0]",                      // Regression         v3.90.1
+		"foo.[0].bar",               // Regression         v3.90.1
+		`.["Hello, World!"]`,        // Regression         v3.90.1
+		"[",                         // Regression v3.89.0 v3.90.1
+		".[]",                       // Regression v3.89.0 v3.90.1
+		"[]",                        // Regression v3.89.0 v3.90.1
+		".[Hello, Unquoted World!]", // Regression v3.89.0 v3.90.1
+		`.H[ello, World!"]`,         // Regression v3.89.0 v3.90.1
+	}
+	for _, propName := range validPropertyNames {
```
Comment (justinvp) [inline tests/integration/valid-property-names/steps_test.go:45]:
```suggestion
	//nolint:paralleltest // ProgramTest calls t.Parallel()
	for _, propName := range validPropertyNames {
```

Otherwise, it looks like it fails in the merge queue when trying to merge with https://github.com/pulumi/pulumi/pull/14688
