### PR TITLE
Change `pulumi refresh` to report diff relative to desired state instead of relative to only output changes 

### LINKED ISSUE #16072: Do not warn on changing outputs during refresh
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

There are multiple instances where `pulumi refresh` shows warnings when resource outputs are changing. Can we consider a model here output changes are not warning worthy?

https://github.com/pulumi/pulumi-aws/issues/3837 lists multiple AWS examples with several distinct root causes all presenting as un-actionable refresh warnings that, if ignored, lead to a good steady-state where `pulumi up` and subsequent `pulumi refresh` show no changes:

- `nil to []` output drift that also reproduces in TF but self-corrects through automatic refresh during apply and therefore remains unfixed over time  
- benign output changes like lastModified changes on a Lambda
- ownership conflicts between inline attributes and sidecar resources (Role managedPolicyArns or RouteTable routes)
- reordering of Set elements where TF understands Set but Pulumi engine diffing Read results does not

Trying to recover the rationale for warning on output changes, one was provided: it is possible that resource outputs might influence the program flow execution and be reused as inputs to other resources and stack outputs, which may cause a non-empty `pulumi preview` after the refresh; so in essence Pulumi conservatively attempts to anticipate this and put the user in control of whether they are going to accept the refreshed state or reject it. The anticipation is correct when the changing outputs are indeed used in the program, and incorrect when they are not, as in lastModified output is changing but remains unused.

If that is the rationale for the current behavior, here is an alternative possible implementation for refresh:

1.  save current state S0
2. call provider Read method to obtain candidate state S1 from the cloud; do not attempt to diff or warn at this point
3. run `pulumi preview` to rerun the program against the S1 state
4. if the preview indicates no changes, accept S1 as the new state and succeed
5. if the preview indicates changes, inform the user of the diff result as potential drift; the user decides whether to retain S0 or accept S1

### LINKED ISSUE #16278: Noninteractive `pulumi refresh` with json output is not showing any diff
### What happened?

Running `pulumi refresh -s {my-stack} --preview-only > refresh.out`

returns a file with:

```
Resources:
    ~ 13 to update
    332 unchanged
```

When running

`pulumi refresh -s {my-stack} -j --preview-only > refresh.json`

The output json does not contain any changes:

`jq '[ .steps[] | select( .detailedDiff != null ) ] | length' refresh.json` returns `0`
`jq '[ .steps[] | select( .newState != .oldState ) ] | length' refresh.json` returns `0`

### Example

See above

### Output of `pulumi about`

CLI
Version      3.117.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  command     0.5.2
resource  datadog     4.12.0
resource  gcp         7.23.0
language  go          unknown
resource  kubernetes  4.1.0
resource  random      4.8.2

Host
OS       darwin
Version  14.3
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.22.2 darwin/arm64'

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #16334: Ignore Changes still showing up in drift detection
### What happened?

I added ignoreChanges to my resources (in an existing stack), but they are still showing up in drift detection.

### Example
```
const iam = new IAMMember(`${prefix}-${_account.accountId}-bq-editor-member`, {
  project: gcpConfig.require('project'),
  role: 'roles/bigquery.dataEditor',
  member: account.email.apply(email => `serviceAccount:${email}`)
}, { ignoreChanges: ['etag'] })
```
But it’s still showing up in the drift pulumi refresh --preview-only
```
~ gcp:projects/iAMMember:IAMMember: (update)
...
--outputs:--
~ etag     : "BwYWTNS0Q6s=" => "BwYY98HnOng="
```
### Output of `pulumi about`

latest

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by lukehoban**
Presently, the behaviour of diffing during refresh steps is incomplete, returning only an "output diff" that presents the changes in outputs. This commit changes refresh steps so that:

* they compute a diff similar to the one that would be computed if a `preview` were run immediately after the refresh, which is more typically what users expect and want; and
* `IgnoreChanges` resource options are respected when performing the new desired-state diffs, so that property additions or changes reported by a refresh can be ignored.

In particular, `IgnoreChanges` can now be used to acknowledge that part or all of a resource may change in the provider, but the user is OK with this and doesn't want to be notified about it during a refresh. Importantly, this means that the diff won't be reported, but also that the changes won't be applied to state.

The implementation covers the following:

* A diff is computed using the inputs from the program and then inverting the result, since in the case of a refresh the diff is being driven by the provider side and not the program. This doesn't change what is stored back into the state, but it does produce a diff that is more aligned with the "true changes to the desired state". 
* `IgnoreChanges` resource options are now stored in state, so that this information can be used in refresh operations that do not have access to/run the program.
* In the context of a refresh operation, `IgnoreChanges` applies to *both* input and output properties. This differs from the behaviour of a normal update operation, where `IgnoreChanges` only considers input properties.
* The special `"*"` value for `IgnoreChanges` can be used to ignore all properties. It _also_ ignores the case where the resource cannot be found in the provider, and instead keeps the resource intact in state with its existing input and output properties.

Because the program is not run for refresh operations, `IgnoreChanges` options must be applied separately before a refresh takes place. This can be accomplished using e.g. a `pulumi up` that applies the options prior to a refresh. We should investigate perhaps providing a `pulumi state set ...`-like CLI to make these sorts of changes directly to a state.

For use cases relying on the legacy refresh diff provider, the `PULUMI_USE_LEGACY_REFRESH_DIFF` environment variable can be set, which will disable desired-state diff computation. We only need to perform checks in `RefreshStep.{ResultOp,Apply}`, since downstream code will work correctly based on the presence or absence of a `DetailedDiff` in the step.

### Notes

- https://github.com/pulumi/pulumi/issues/16144 affects some of these cases - though its technically orthogonal
- https://github.com/pulumi/pulumi/issues/11279 is another technically orthogonal issue that many providers (at least TFBridge ones) - do not report back changes to input properties on Read when the input property (or property path) was missing on the inputs.  This is again technically orthogonal - but leads to cases that appear "wrong" in terms of what is stored back into the state still - though the same as before this change.
- Azure Native doesn't seem to handle `ignoreChanges` passed to Diff, so the ability to ignore changes on refresh doesn't currently work for Azure Native.

### Fixes

* Fixes #16072
* Fixes #16278
* Fixes #16334 
* Not quite #12346, but likely replaces the need for that

### CODE REVIEW

File: pkg/resource/deploy/step.go [hunk 1]
```diff
@@ -960,7 +963,29 @@ func (s *RefreshStep) Apply(preview bool) (resource.Status, StepCompleteFunc, er
...
 			s.new.Modified = &now
 		}
+
+		// We compute the diff that a user would see if they immediately ran an `up` on a no-change program
+		// after this refresh.  This will return the opposite of what we want - so we'll invert it below.
+		// We pass:
+		// * newInputs where oldInputs are expected
+		// * newOutputs where oldOutputs are expected
+		// * oldInputs where newInputs are expected
+		diff, err := diffResource(s.new.URN, s.new.ID, s.new.Inputs, s.new.Outputs, s.old.Inputs, prov, preview,
```
Comment (t0yv0) [inline pkg/resource/deploy/step.go:973]: Assuming this is going to call Diff(), I love that because that automatically engages bridge machinery for planning changes suppressing changes and computing detailed diffs, that is going to be very helpful to run that. The downside is that new inputs returned from Read() are not check-clean and Diff expects these to be checked clean inputs so this may uncover some latent issues in bridged providers when rolled out.

Comment (lukehoban) [reply pkg/resource/deploy/step.go:973]: > new inputs returned from Read() are not check-clean 

I think the implied requriement even before these changes is that they are, as they have always been stored directly into the state file, and only "check-clean" inputs are allowed to be stored in state.  And that's a reasonable requirement, because these are inputs provided directly by a provider, which is capable of ensuring anything it returns is check-clean. Check is only needed to take an arbitrary bag of inputs from a users and turn it into something the provider knows is valid.

**Comment by t0yv0** [comment]
Doing another pass here, really 👍 on this, "Changes to output-only properties are no longer shown as refresh diffs" is very valuable as well. This accomplishes most of the benefit of https://github.com/pulumi/pulumi/issues/16072 without running the program on `pulumi refresh` which may be an un-releasable change (too invasive because it would slow down `pulumi refresh` as well as possibly cause some previously working programs to crash as they do not expect being called). Summarizing quick background discussion with @EronWright  - there inevitably will be cases where resource outputs interact with the program and full `pulumi preview` is higher fidelity as to actual drift compared this PR form of just calling Diff per-resource, but it seems to me the tradeoffs are worth it.

File: pkg/backend/display/rows.go [hunk 2]
```diff
@@ -435,19 +435,14 @@ func (data *resourceRowData) getInfoColumn() string {
 }
 
 func getDiffInfo(step engine.StepEventMetadata, action apitype.UpdateKind) string {
-	diffOutputs := action == apitype.RefreshUpdate
```
Comment (lukehoban) [inline pkg/backend/display/rows.go:438]: We are no longer treating a refresh as an "output diff".  It is now a diff of inferred inputs, preferably from the `detailedDiff` computed by the step.

File: pkg/backend/display/diff.go [hunk 3]
```diff
@@ -433,17 +433,22 @@ func renderDiffResourceOutputsEvent(
...
-		if payload.Metadata.Op == deploy.OpImport {
-			renderDiff(out, payload.Metadata, payload.Planning, payload.Debug, seen, opts)
+
+		refresh := false // are these outputs from a refresh?
+		if m, has := seen[payload.Metadata.URN]; has && m.Op == deploy.OpRefresh {
+			refresh = true
+		}
+
+		// If this is the output step for an import or refresh, we actually want to display the diff at this point.
+		if payload.Metadata.Op == deploy.OpImport || (refresh && payload.Metadata.Op == deploy.OpUpdate) {
```
Comment (lukehoban) [inline pkg/backend/display/diff.go:443]: For refresh, we now render a normal input diff but at ResourceOutputsEvent time (because we don't know the diff until we run the step).  Very similar to Import.  However, the step gets rewritten into a "OpUpdate" if there are changes, so look at that.

I believe it is right to ignore the OpSame and OpDelete cases that an OpRefresh could also be rewritten to - but it's possible there are cases where those should also go through this path?

File: pkg/cmd/pulumi/state_setignorechanges.go [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+	"github.com/spf13/cobra"
+)
+
+func newStateSetIgnoreChangesCommand() *cobra.Command {
+	var stack string
+	var paths []string
+	var yes bool
+
+	cmd := &cobra.Command{
+		Use:   "set-ignore-changes [resource URN] --path [property-path-1] ...",
```
Comment (lukehoban) [inline pkg/cmd/pulumi/state_setignorechanges.go:34]: I honestly wish we had a more general command or set of commands for modifying components of state directly like this, and didn't need to invent a new mechanism here.  Open to feedback on the CLI UX here - it's not particularly "nice", but seems as well aligned as possible with surrounding CLI UX and with being able to technically express all use cases.

File: pkg/engine/lifecycletest/testdata/output/TestCanceledRefresh/diff.stdout.txt [hunk 5]
```diff
@@ -1,12 +1,12 @@
...
-<{%reset%}><{%fg 3%}>~ pkgA:m:typA: (update)
+<{%reset%}><{%reset%}>  pkgA:m:typA: (same)
 <{%reset%}>    [id=0]
 <{%reset%}><{%reset%}>    [urn=urn:pulumi:test::test::pkgA:m:typA::resA]
-<{%reset%}><{%fg 3%}>    --outputs:--<{%reset%}>
+<{%reset%}><{%reset%}>    --outputs:--<{%reset%}>
 <{%fg 2%}>  + foo: <{%reset%}><{%fg 2%}>"bar"<{%reset%}><{%fg 2%}>
 <{%reset%}><{%fg 13%}><{%bold%}>Resources:<{%reset%}>
-    <{%fg 3%}>~ 1 updated<{%reset%}>
+    1 unchanged
```
Comment (lukehoban) [inline pkg/engine/lifecycletest/testdata/output/TestCanceledRefresh/diff.stdout.txt:10]: This and other similar changes are intentional - the only change is in outputs so it doesn't report as a diff.

Note that these tests do the equivalent of `--show-sames`, so they actually do show the diff for the sames, which wouldn't be "normal" in practice.

File: pkg/resource/deploy/step.go [hunk 6]
```diff
@@ -886,23 +887,25 @@ func NewRefreshStep(deployment *Deployment, old *resource.State, done chan<- boo
...
+func (s *RefreshStep) DetailedDiff() map[string]plugin.PropertyDiff { return s.diff.DetailedDiff }
 
 // ResultOp returns the operation that corresponds to the change to this resource after reading its current state, if
 // any.
 func (s *RefreshStep) ResultOp() display.StepOp {
 	if s.new == nil {
 		return OpDelete
 	}
-	if s.new == s.old || s.old.Outputs.Diff(s.new.Outputs) == nil {
+	if s.new == s.old || s.diff.Changes == plugin.DiffNone {
```
Comment (lukehoban) [inline pkg/resource/deploy/step.go:908]: I'm not 100% certain how `DiffUnknown` should be treated here.

**Review by lukehoban — COMMENTED** [review]
A few notes:
* Ideally we would offer a way to opt-out of this via env var.  The changes are coupled across (a) RefreshStep in the engine (b) diff renderer (c) progress renderer.  We would need to incorporate the env var into all three places and maintain old and new behaviour in both.  But I think we likely do need to do this.
* I am nervous about the wide variety of allowed Diff behaviours, and how few of them are tested generally here, especially relative to the true Diff behaviours in providers.  Ideally we would have tf-bridge-like, kubernetes-like, and az-native-like diff implementations we could test against here to validate and baseline refresh (and many other features) against.

**Comment by t0yv0** [comment]
Curious if we expect to land this anytime soon? @VenelinMartinov and I found a root cause of a very specific TF bug that uses old 2019 normalizeNullValues code to replace empty maps with null that currently causes a *lot* of dirty refreshes in both TF and stock Pulumi, that is alleviated by this change. We're evaluating tailoring a workaround in the bridge, but if we are able to land this change it might be not worth it?

**Comment by lukehoban** [comment]
> Curious if we expect to land this anytime soon? 

Yes!  @lunaris is picking up taking this over the finish line.  🙌

**Comment by bernhardloos** [comment]
I always found the current refresh behavior quite useful, especially for keeping an eye on complex resources that get changed by other systems outside of pulumi. So an option to keep the current behavior would be much appreciated.
(But ignore_changes applying to refresh would still be nice).

**Comment by lunaris** [comment]
@bernhardloos I've added an environment variable `PULUMI_ENABLE_LEGACY_REFRESH_DIFF` that should allow you to access the old behaviour if you wish; hopefully that works!

File: pkg/backend/display/diff.go (hunk 3 above)
Comment (tgummerer) [reply pkg/backend/display/diff.go:443]: This probably deserves a little bit more explanation of why we are ignoring `OpSame` and `OpDelete` in a comment.  I think for `OpSame` it makes sense to hide the diff (there shouldn't be one). For `OpDelete` I think it also makes sense because we're deleting, so the diff would be "delete everything", which would would already indicate otherwise?

File: pkg/backend/display/rows.go [hunk 7]
```diff
@@ -435,19 +435,14 @@ func (data *resourceRowData) getInfoColumn() string {
...
 	changesBuf := &bytes.Buffer{}
 	if step.Old != nil && step.New != nil {
 		var diff *resource.ObjectDiff
 		// An OpSame might have a diff due to metadata changes (e.g. protect) but we should never print a property diff,
 		// even if the properties appear to have changed. See https://github.com/pulumi/pulumi/issues/15944 for context.
 		if step.Op != deploy.OpSame {
 			if step.DetailedDiff != nil {
-				diff = engine.TranslateDetailedDiff(&step)
-			} else if diffOutputs {
```
Comment (tgummerer) [inline pkg/backend/display/rows.go:447]: Do we not need to still have this but behind the flag now?  Or is there some reason I'm missing why this is no longer needed?

File: pkg/cmd/pulumi/state_setignorechanges.go [hunk 8]
```diff
@@ -0,0 +1,101 @@
+// Copyright 2024, Pulumi Corporation.
```
Comment (tgummerer) [inline pkg/cmd/pulumi/state_setignorechanges.go:1]: Introducing this new command seems somewhat orthogonal to the rest of the PR.  I'd love to see that pulled out into a separate PR so we can iterate on the UX for that and think some more about what exactly we want that to look like without having to block this PR on that.

File: pkg/cmd/pulumi/state_setignorechanges.go (hunk 4 above)
Comment (tgummerer) [inline pkg/cmd/pulumi/state_setignorechanges.go:34]:
```suggestion
		Use:   "set-ignore-changes [resource URN] [--path property-path-1] ...",
```

Also maybe this could be `pulumi state set ignore-changes`, so we can have other `pulumi state set` commands later potentially?   I think that would maybe fit better with the current design?

File: pkg/resource/deploy/step.go [hunk 9]
```diff
@@ -925,25 +926,40 @@ func NewRefreshStep(deployment *Deployment, old *resource.State, done chan<- boo
...
 		return OpDelete
 	}
-	if s.new == s.old || s.old.Outputs.Diff(s.new.Outputs) == nil {
-		return OpSame
+
+	// Prior to us introducing refresh diffs against desired state, we only
+	// diffed outputs. For now, we support reverting to this behaviour for
+	// users that rely on it. We only need to make this check here as all
+	// downstream consumers will behave correctly based on whether s.diff is
+	// set or not.
```
Comment (tgummerer) [inline pkg/resource/deploy/step.go:952]:
```suggestion
	// users that rely on it.
```

The rest of the sentence belongs in a commit/PR message rather than a code comment imo, since it gets confusing to tie together what other changes could possibly need to be made if unless this is viewed in the context of the PR.

File: pkg/resource/deploy/step.go [hunk 10]
```diff
@@ -1011,12 +1027,22 @@ func (s *RefreshStep) Apply(preview bool) (resource.Status, StepCompleteFunc, er
...
 		)
 		var inputsChange, outputsChange bool
 		if s.old != nil {
-			inputsChange = !refreshed.Inputs.DeepEquals(s.old.Inputs)
-			outputsChange = !refreshed.Outputs.DeepEquals(s.old.Outputs)
+			// Prior to us introducing refresh diffs against desired state, we only
+			// diffed outputs. For now, we support reverting to this behaviour for
+			// users that rely on it. We only need to make this check here as all
+			// downstream consumers will behave correctly based on whether s.diff is
+			// set or not.
```
Comment (tgummerer) [inline pkg/resource/deploy/step.go:1038]:
```suggestion
			// users that rely on it.
```

This is the second place where we do this check, so "We only need to make this check here" isn't quite correct.

File: pkg/resource/deploy/step.go [hunk 11]
```diff
@@ -1027,7 +1053,45 @@ func (s *RefreshStep) Apply(preview bool) (resource.Status, StepCompleteFunc, er
...
+				return refreshed.Status, nil, err
+			}
+
+			s.diff = diff.Invert()
+			logging.V(7).Infof("Refresh diff: %v", s.diff)
+		} else {
+			logging.V(7).Infof("Refresh diffing disabled; diffing outputs only")
+		}
 	} else {
+		// TODO: Should it be possible to ignore the entire discard and put the old state back in full?
```
Comment (tgummerer) [inline pkg/resource/deploy/step.go:1091]: TODO's should have an issue linked to them.

File: pkg/resource/deploy/step_test.go [hunk 12]
```diff
@@ -569,6 +569,242 @@ func TestReadStep(t *testing.T) {
 	})
 }
 
+func TestRefreshStepPatterns(t *testing.T) {
+	t.Parallel()
+
+	// TODO: To some degree, this isn't testing much, since it's mocking the Read and Diff provider calls entirely.
```
Comment (tgummerer) [inline pkg/resource/deploy/step_test.go:575]: Same for this TODO, although I'm not sure I agree with what's written here completely.  Hardcoded responses seem fine for engine tests, if anything we should maybe also validate that the engine sends the right parameters, but I don't think we need "real" implementations here.

**Review by tgummerer — COMMENTED** [review]
Did we run the tests with the legacy flag enabled as well, and made sure that no test changes were necessary/there were no output changes?

File: pkg/backend/display/diff.go (hunk 3 above)
Comment (lunaris) [reply pkg/backend/display/diff.go:443]: Yep -- will expand upon this.

File: pkg/backend/display/rows.go (hunk 7 above)
Comment (lunaris) [reply pkg/backend/display/rows.go:447]: In theory this should behave fine since `diff` will be `nil` -- I call this out in the use of the flag later on but as you say it's probably worth putting this in the commit message/PR comment too. Will sort that.

File: pkg/cmd/pulumi/state_setignorechanges.go (hunk 8 above)
Comment (lunaris) [reply pkg/cmd/pulumi/state_setignorechanges.go:1]: I can pull it out but realistically this PR is likely blocked since without that command, it's hard to manipulate `IgnoreChanges` for use in a refresh. On the other point about `pulumi state set ...`, I did discuss this with Luke since I agree it's likely the right call. However, it feels like a bigger piece of work and we already have `pulumi state unprotect`, which is a special case in its own right, so I was hoping we could find a way to tackle that later (and either deprecate or alias this command, for instance). Thoughts?

File: pkg/resource/deploy/step_test.go (hunk 12 above)
Comment (lunaris) [reply pkg/resource/deploy/step_test.go:575]: I think we can reword this not to be a TODO because as you say that's kind of the point of these tests -- will sort

File: pkg/cmd/pulumi/state_setignorechanges.go (hunk 8 above)
Comment (lunaris) [reply pkg/cmd/pulumi/state_setignorechanges.go]: After more discussion I'm going to pull this out and we can discuss separately :+1:

**Comment by lunaris** [comment]
> Did we run the tests with the legacy flag enabled as well, and made sure that no test changes were necessary/there were no output changes?

This is a great point. As well as adding some to test the flag going forward, I've since gone back and ran the lifecycle tests from `HEAD~1` with the legacy flag enabled and they do indeed pass :pray: Thanks for suggesting this!

**Review by tgummerer — APPROVED** [review]
LGTM

**Comment by bernhardloos** [comment]
@lunaris The PULUMI_ENABLE_LEGACY_REFRESH_DIFF works, thank you for it. I noticed one change in behavior: the changed fields are missing in the initial overview screen. While it was for example something like "updated [~status,~metadata]" it's just "updated" now without the details. I can live with it, but not sure if this is intentional.

Also, with the new behavior, https://github.com/pulumi/pulumi/issues/13679 now also affects the refresh operation, making it pretty much useless for dynamic providers.
