### PR TITLE
show all paths when we have multipe local policy packs with the same name

### LINKED ISSUE #15566: TestMultiplePolicyPacks is flaky
```
=== FAIL: integration TestMultiplePolicyPacks (12.96s)
    environment.go:97: Created new test environment:  /tmp/test-env1580768510
    environment.go:216: Running command pulumi login --cloud-url file:///tmp/test-env1580768510
    environment.go:216: Running command pulumi stack init multiple-policy-pack32d5e6ed
    integration_test.go:1151: Running command npm install
    integration_test.go:1153: Running command npm install
    environment.go:216: Running command yarn link @pulumi/pulumi
    environment.go:216: Running command yarn install
    environment.go:216: Running command pulumi up --skip-preview --yes --policy-pack advisory_policy_pack --policy-pack mandatory_policy_pack
    integration_test.go:1165: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/tests/integration/integration_test.go:1165
        	Error:      	"Updating (multiple-policy-pack32d5e6ed):\nLoading policy packs...\n\n@ updating....\n    pulumi:pulumi:Stack protect_resources-multiple-policy-pack32d5e6ed  (node:24016) DeprecationWarning: Calling start() is no longer necessary. It can be safely omitted.\n    pulumi:pulumi:Stack protect_resources-multiple-policy-pack32d5e6ed  (Use `node --trace-deprecation ...` to show where the warning was created)\n@ updating.....\n    pulumi:pulumi:Stack protect_resources-multiple-policy-pack32d5e6ed  (node:24031) DeprecationWarning: Calling start() is no longer necessary. It can be safely omitted.\n    pulumi:pulumi:Stack protect_resources-multiple-policy-pack32d5e6ed  (Use `node --trace-deprecation ...` to show where the warning was created)\n\n +  pulumi:pulumi:Stack protect_resources-multiple-policy-pack32d5e6ed creating (0s) (Use `node --trace-deprecation ...` to show where the warning was created)\n@ updating.....\n +  pulumi:pulumi:Stack protect_resources-multiple-policy-pack32d5e6ed creating (1s) (node:24046) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.\n +  pulumi:pulumi:Stack protect_resources-multiple-policy-pack32d5e6ed creating (1s) (Use `node --trace-deprecation ...` to show where the warning was created)\n +  pulumi-nodejs:dynamic:Resource res creating (0s) \n +  pulumi-nodejs:dynamic:Resource res created (0.00s) \n +  pulumi:pulumi:Stack protect_resources-multiple-policy-pack32d5e6ed creating (2s) (Use `node --trace-deprecation ...` to show where the warning was created)\n +  pulumi:pulumi:Stack protect_resources-multiple-policy-pack32d5e6ed creating (2s) (Use `node --trace-deprecation ...` to show where the warning was created)\n +  pulumi:pulumi:Stack protect_resources-multiple-policy-pack32d5e6ed creating (2s) error: update failed\n +  pulumi:pulumi:Stack protect_resources-multiple-policy-pack32d5e6ed **creating failed (1s)** 1 error; 6 messages\nPolicies:\n    ❌ typescript@v0.0.1 (local: advisory_policy_pack)\n        - [advisory]  advisory-policy-pack  (pulumi:pulumi:Stack: protect_resources-multiple-policy-pack32d5e6ed)\n          Failing advisory policy pack for testing\n          foobar\n        - [mandatory]  mandatory-policy-pack  (pulumi:pulumi:Stack: protect_resources-multiple-policy-pack32d5e6ed)\n          Failing mandatory policy pack for testing\n          mandatory-policy-pack\n\nDiagnostics:\n  pulumi:pulumi:Stack (protect_resources-multiple-policy-pack32d5e6ed):\n    (node:24046) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.\n    (Use `node --trace-deprecation ...` to show where the warning was created)\n\n    error: update failed\n\n    (node:24016) DeprecationWarning: Calling start() is no longer necessary. It can be safely omitted.\n    (Use `node --trace-deprecation ...` to show where the warning was created)\n\n    (node:24031) DeprecationWarning: Calling start() is no longer necessary. It can be safely omitted.\n    (Use `node --trace-deprecation ...` to show where the warning was created)\n\nOutputs:\n    o: 1\n\n" does not contain "❌ typescript@v0.0.1 (local: mandatory_policy_pack)"
        	Test:       	TestMultiplePolicyPacks

```

Seen in https://github.com/pulumi/pulumi/actions/runs/8114805946/job/22181590221?pr=15562

### PR DESCRIPTION
**Pull request by tgummerer**
It is possible for multiple local policy packs to have the same name. When there are policy violation, we currently only show one of the paths for those policy packs (as we consider them the same policy pack because it has the same name).

Display both of the paths in this case to avoid any confusion.  Also sort the names, so the test we have for this is deterministic.

I think in ideal world it would be better to just error out if there are multiple policy packs with the same name, but given this behaviour worked for a long time I wouldn't be surprised if that ends up breaking some use case, so I'd be a bit worried about doing that now.

A possible alternative would be to not consider policy packs with the same name as a single policy pack, but if we name it differently I could imagine people getting confused with that.  Happy to hear alternative opinions on what the right behaviour here is since I'm not quite sure myself.

Fixes #15566

### CODE REVIEW

File: pkg/backend/display/progress.go [hunk 1]
```diff
@@ -585,12 +585,20 @@ func (display *ProgressDisplay) printPolicies() bool {
...
 		baseName, path := engine.GetLocalPolicyPackInfoFromEventName(name)
+		var key string
 		if baseName != "" {
-			summary.IsLocal = true
-			summary.LocalPath = path
-			name = baseName
+			key = fmt.Sprintf("%s@v%s", baseName, version)
+			if s, has := policyPackInfos[key]; has {
+				summary = s
+				summary.LocalPaths = append(summary.LocalPaths, path)
```
Comment (Frassle) [inline pkg/backend/display/progress.go:593]: Shouldn't this be setting IsLocal=true as well?

Comment (tgummerer) [reply pkg/backend/display/progress.go:593]: In theory it should be set already, unless there's also a remote policy pack that has the same name, which I guess could be possible :thinking:

Comment (tgummerer) [reply pkg/backend/display/progress.go:593]: The latest commit now addresses that.  It's a bit of a weird situation, and I don't really expect it to happen, but If it does it now shows something like

`<name>@<version> (local: <path>;...) (cloud)`. Not sure if there's a better way to address this.

**Review by Frassle — APPROVED** [review]
