### PR TITLE
Record engine events concurrently

### LINKED ISSUE #2303: Improve performance of preview/update
There have been some reports that upgrading to v0.16.7 of Pulumi lead to a large performance regression.

```
Resources:
    + 206 to create

pulumi preview  28,03s user 4,33s system 10% cpu 5:22,12 total
```

I would all but guarantee this is related to the new way we emit log data to the service (engine events instead of pre-rendered diff messages).

### PR DESCRIPTION
**Pull request by chrsmith**
Record engine events concurrently using Go-routines.

Currently we record all of the engine events (a `POST` request to the Pulumi Service) serially, as we see the events. This is problematic when an update contains hundreds of resources or produces lots of log output. In those cases we emit many engine events, and no matter how quickly the Pulumi Service can handle the requests, the end-to-end network latency adds up. (100ms x 1500 events is 2.5 minutes)

Since each engine event can be recorded independently, we can issue all those requests in separate Go routines. I'm sure there will be a bottleneck elsewhere, as the OS or NIC needs to block queued up requests. But I assume that it won't cause any errors.

In my own testing -- writing an app that just spams `console.log` a few thousand times, emitting `DiagEvent`s in a loop -- I measured the following perf numbers:

```
$ [5000] time pulumi update --skip-preview
Duration: 3m5s

Permalink: https://app.pulumi.com/chrsmith/ee-stress-dev/updates/3

real    3m11.211s
user    0m14.677s
sys     0m3.654s


$ [5000] time /Users/chris/pulumi-root/bin/pulumi update --skip-preview
Duration: 5s

Permalink: https://app.pulumi.com/chrsmith/ee-stress-dev/updates/4

real    0m8.565s
user    0m15.197s
sys     0m2.833s

$ [1000] time pulumi update --skip-preview

Duration: 37s

Permalink: https://app.pulumi.com/chrsmith/ee-stress-dev/updates/5

real    0m39.191s
user    0m3.236s
sys     0m0.796s

Duration: 2s

Permalink: https://app.pulumi.com/chrsmith/ee-stress-dev/updates/6

real    0m3.617s
user    0m2.207s
sys     0m0.567s
```

Fixes #2303 , though I'd like to add an integration test to ensure it stays that way. But I'll leave that for a separate PR in case we want to hotfix the current CLI with this.

### CODE REVIEW

File: pkg/backend/httpstate/state.go [hunk 1]
```diff
@@ -179,20 +179,20 @@ func (u *cloudUpdate) RecordAndDisplayEvents(
...
-		eventIdx++
 
-		// First echo the event to the local display.
-		displayEvents <- e
+	// We start the requests to record engine events in separate Go routines since they can
+	// all be done independently, and updates with a "chatty" event stream can have serious
+	// perf problems when issuing the requests serially.
+	var wg sync.WaitGroup
+	recordEngineEvent := func(event engine.Event, eventIdx int) {
+		wg.Add(1)
```
Comment (swgillespie) [inline pkg/backend/httpstate/state.go]: Doing this inside the new goroutine is a race - the main goroutine can reach `wg.Wait()` before the spawned goroutine gets scheduled and calls `wg.Add(1)`. I think we should instead call `wg.All(1)` before the call to `go recordEngineEvent(...)` - it'll be more robust against scheduler mishaps.

File: pkg/backend/httpstate/state.go [hunk 2]
```diff
@@ -179,20 +179,20 @@ func (u *cloudUpdate) RecordAndDisplayEvents(
...
+		defer func() { wg.Done() }()
```
Comment (swgillespie) [inline pkg/backend/httpstate/state.go]: Can you do just `defer wg.Done()` instead?

File: pkg/backend/httpstate/state.go [hunk 3]
```diff
@@ -202,11 +202,23 @@ func (u *cloudUpdate) RecordAndDisplayEvents(
...
 		}
+	}
+
+	for e := range events {
+		// First echo the event to the local display.
+		displayEvents <- e
+
+		// Then render and record the event for posterity.
+		eventIdx++
+		go recordEngineEvent(e, eventIdx)
```
Comment (swgillespie) [inline pkg/backend/httpstate/state.go]: Doing this asynchronously means that we're now potentially writing to `displayEvents` at some arbitrary time in the future after receiving the event - we've had a bunch of crashes in the past because components fail to shut down gracefully and try to write to `displayEvents` when the CLI is shutting down. Is t here a way we can gracefully shut down the spawned goroutine if we know that the CLI is in the process of shutting down?

File: pkg/backend/httpstate/state.go (hunk 1 above)
Comment (chrsmith) [reply pkg/backend/httpstate/state.go]: Done.

File: pkg/backend/httpstate/state.go (hunk 2 above)
Comment (chrsmith) [reply pkg/backend/httpstate/state.go]: Absolutely! That was muscle memory... Done.

File: pkg/backend/httpstate/state.go (hunk 3 above)
Comment (chrsmith) [reply pkg/backend/httpstate/state.go]: I don't think we can do that without passing additional state, e.g. a `context.Context` object. 

What would you think of either (1) silently dropping these errors -- meaning the stack's update logs might have "gaps" in the timeilne view -- or (2) just printing the error to `STDERR` (and potentially corrupting the display events channel).

Ultimately if we don't trust the `displayEvents` channel to be open or not, we probably can't reliably use it in these separate Go-routines.

Comment (swgillespie) [reply pkg/backend/httpstate/state.go]: > What would you think of either (1) silently dropping these errors -- meaning the stack's update logs might have "gaps" in the timeilne view -- or (2) just printing the error to STDERR (and potentially corrupting the display events channel).

I think (1) makes the most sense here IMO - that sounds better to me than garbling up standard error. Given that this is ostensibly usable as a library I think it makes sense to avoid writing out to standard error if possible.

Comment (tvalenta) [reply pkg/backend/httpstate/state.go]: 🥇

**Comment by joeduffy** [comment]
@chrsmith Thanks for the quick fix. Do you plan to submit a perf regression test as a follow on?
