### PR TITLE
Replace the use of pipenv with Python's venv

### LINKED ISSUE #8379: Follow up to avoid the need to globally-install Python SDK
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

The quick fix in https://github.com/pulumi/pulumi/pull/8361 was unfortunate. It requires Python SDK to be installed globally so that the pulumi-langage-host run from a sub-process under pytest finds it. It is possibly related to how `pipenv` works on the latest version. Alternative solutions:

1. edit the environment with `PATH` being extended with `$(pipenv venv)/bin` so that `#/usr/bin/env python` resolves to the python within the VENV managed by pipenv, that has a reference to Pulumi Python SDK already.

2. consider removing pipenv entirely

### Steps to reproduce

1.
2.
3.
4.

Expected: 
Actual:

### PR DESCRIPTION
**Pull request by justinvp**
We've had a few issues in the recent past related to pipenv oddities in CI which lead us to temporarily globally install the Python SDK in CI.

This change removes the use of pipenv in favor of Python's built-in venv and avoids globally installing the Python SDK.

Fixes #8379

### CODE REVIEW

File: tests/testprovider/main.go [hunk 1]
```diff
@@ -17,25 +17,42 @@ package main
 
 import (
 	"context"
-	"crypto/rand"
```
Comment (t0yv0) [inline tests/testprovider/main.go:20]: Curious, are these changes related to / necessitated by pipenv removal?

Comment (justinvp) [reply tests/testprovider/main.go:20]: Dynamic providers typically don't work correctly when used from multi-language components (#5455). Somehow the way we were previously setting up the tests to use the shared pipenv virtualenv allowed the Python MLC tests that used dynamic providers to pass. But when I changed the tests to use their own virtual env from (python -m venv venv) I was running into errors along the lines of #5455.

Instead of trying to rework how we setup the tests to get them to pass, I changed the Python MLCs to use a resource from a testprovider rather than a resource from a dynamic provider inside the MLC. The testprovider previously only exposed a `Random` resource and as part of this change I added a new `Echo` resource. These changes were just some refactoring to more cleanly expose both `Random` and `Echo` from the testprovider.

With these changes, we could potentially do some further subsequent cleanup of the MLC tests:

- There are some tests with a MLC implemented in TypeScript that use a dynamic provider, and we have some hacks in the integration test package to make this work. But it is ugly and not representative of real-world usage (you have to have a `node_modules` dir in your program directory with the dependencies needed by the MLC, even if your program  is written in another language). We could remove those hacks and replace the use of the dynamic provider with the new `Echo` resource in the testprovider.

- Go doesn't have dynamic providers and in order to implement the equivalent MLC in Go we had to expose an equivalent `Echo` resource from the MLC provider itself (this was before I had added the testprovider). We could instead clean these Go test MLCs up to not do that, which would significantly reduce the amount of code in the MLC, and instead use the new `Echo` resource in the testprovider.

- When we get around to implementing support for authoring MLC in .NET, we'll be able to use the new `Echo` resource in the testprovider.
