### PR TITLE
fix: use independent `http.Client` in pair with `http.Server`

### LINKED ISSUE #19841: `TestPublishPackage/SuccessfulPublish` is flaky
```
=== FAIL: backend/httpstate/client TestPublishPackage/SuccessfulPublish (0.01s)
    client_package_test.go:416: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/client/client_package_test.go:416
        	Error:      	Received unexpected error:
        	            	failed to upload index: Put "http://127.0.0.1:33763/upload/index": net/http: HTTP/1.x transport connection broken: http: CloseIdleConnections called
        	Test:       	TestPublishPackage/SuccessfulPublish
```

Seen in https://github.com/pulumi/pulumi/actions/runs/15609493740/job/43967021645?pr=19839

### PR DESCRIPTION
**Pull request by rMaxiQp**
## What

Create independent `http.Client` in pair with each test's `http.Server`

## Why

resolve `net/http: HTTP/1.x transport connection broken: http: CloseIdleConnections called`. Please see https://github.com/pulumi/pulumi/issues/19841#issuecomment-3529204255 for the investigation and reasoning

## Related
fix #19841

### CODE REVIEW

**Comment by justinvp** [comment]
/run-acceptance-tests
Please view the results of the acceptance tests [Here](https://github.com/pulumi/pulumi/actions/runs/19349797948)

File: pkg/backend/httpstate/client/client_test.go [hunk 1]
```diff
@@ -54,8 +54,18 @@ func newMockServerRequestProcessor(statusCode int, processor func(req *http.Requ
 		}))
 }
 
+func newHTTPClient() *http.Client {
+	return &http.Client{
+		// Some arbitrary connection limits to avoid excessive connections
+		Transport: &http.Transport{
+			MaxIdleConns:    2,
+			IdleConnTimeout: 2 * time.Second,
+		},
```
Comment (tgummerer) [inline pkg/backend/httpstate/client/client_test.go]: Should we just copy the same option from `DefaultTransport` here?

**Comment by rMaxiQp** [comment]
>  If we're using multiple httptest servers, couldn't those be similarly affected, in that they close idle connections for other servers? Maybe a better fix would be to set up a separate transport for each httptest.Server?

If none of the clients are using the `DefaultTransport`, I don't think servers will affect each other. But also I don't know everything about `net/http`'s implementations 😅 possible servers do depend on `DefaultTransport` somewhere. 

> maybe we should use server.Client() as the client here instead of a new client

I didn't realize that's a function already provided 💡 I think this definitely can be the better approach here! I will update the implementation and test it out tonight.

Thank you for the through reviews and suggestion!

File: pkg/backend/httpstate/client/client_test.go (hunk 1 above)
Comment (rMaxiQp) [reply pkg/backend/httpstate/client/client_test.go]: Copied over most of options from `DefaultTransport` besides `Proxy`.

I tried to use `server.Client()` instead, but somehow some tests were failing with: `forced read error`. I haven't spent much time understanding why it happens, though a direct `server.Client()` might have some gotchas that we should aware of.

**Comment by tgummerer** [comment]
@rMaxiQp Looks like we have a missing import that's preventing us from merging this.  Once that's fixed up we should be able to merge this. 

(Note that you can run `make lint` locally to shorten your dev cycle.  If you're using `mise` it should install all the right tools for you).

**Comment by rMaxiQp** [comment]
@tgummerer Thank you for pointing it out. I thought my IDE would've fixed all lint errors already 😅. Thank you for the tips about `make lint`.

**Comment by tgummerer** [comment]
/run-acceptance-tests
Please view the results of the acceptance tests [Here](https://github.com/pulumi/pulumi/actions/runs/19437085878)

**Comment by rMaxiQp** [comment]
Hi, @tgummerer Acceptance tests seem to pass, is there anything else that I could help to move this fix forward?

**Comment by tgummerer** [comment]
Sorry @rMaxiQp I dropped the ball on this, thanks for pinging me, and thanks again for the fix.  This looks ready, so I'll go ahead and merge it.
