### PR TITLE
Fix two colorization issues.

### LINKED ISSUE #3378: No colours showing on Windows 10
Pulumi CLI is not showing colour highlighting, as shown in the screen shot.
colour2

CLI version: 1.3.3
Shell: Windows CMD
OS: Windows 10

The colours were showing perfectly well using CLI version 1.3.1 as shown below.
colour1

### PR DESCRIPTION
**Pull request by pgavlin**
- The length of the text content (i.e. the content of a colorized string
  that is not control sequences) was not being correctly tracked. This
  caused the "status" column of the progress display to overflow.
- Colorization was unconditionally disabled on Windows. When we were
  using loreley, we had set the global colorization flag s.t.
  colorization on Windows _should_ have been disabled, but we overrode
  this flag each time we actually colorized anything.

Fixes #3378.

### CODE REVIEW

**Comment by justinvp** [comment]
Does this fix #3374?

File: pkg/diag/colors/windows.go [hunk 1]
```diff
@@ -16,6 +16,20 @@
...
+	maj, _, err := k.GetIntegerValue("CurrentMajorVersionNumber")
+	if err != nil {
+		return false
+	}
+	return maj >= 10
+}
+
 func init() {
-	disableColorization = true
+	disableColorization = !hasVTSupport()
```
Comment (CyrusNajmabadi) [inline pkg/diag/colors/windows.go]: so no colorization pre-win10?

Comment (CyrusNajmabadi) [reply pkg/diag/colors/windows.go]: might want to mention that in the CL if that's the case.

Comment (pgavlin) [reply pkg/diag/colors/windows.go]: Correct. IIRC pre-Win10 the terminal did not understand the VT100 control codes we use for colorization.

**Comment by pgavlin** [comment]
> Does this fix #3374?

It does!
