### PR TITLE
[sdkgen/python] SDKgen on external enums

### LINKED ISSUE #12695: [sdkgen/python] Referencing enums isn't working correctly
Python SDK gen doesn't reference enums correctly. For example:

https://github.com/pulumi/pulumi/blob/fa4a7a5f2119b769366a0740e1fcd35fc070b360/pkg/codegen/testing/test/testdata/external-enum/python/pulumi_example/component.py#L11-L12

https://github.com/pulumi/pulumi/blob/fa4a7a5f2119b769366a0740e1fcd35fc070b360/pkg/codegen/testing/test/testdata/external-enum/python/pulumi_example/component.py#L19-L20

Despite having a test for this, the actual output is incorrect. [Type checking](https://github.com/pulumi/pulumi/issues/12694) the generated code would have caught the problem.

### PR DESCRIPTION
**Pull request by dixler**
# Description

Fixes #12695

Python SDKGen was not correctly referencing external enum types which needed an import alias.

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/codegen/python/gen.go [hunk 1]
```diff
@@ -250,21 +250,30 @@ func (mod *modContext) objectType(t *schema.ObjectType, input bool) string {
...
+			modName = strings.ReplaceAll(modName, "/", ".") + "."
+		}
+
+		return fmt.Sprintf("'%s%s'", modName, name)
 	}
+
+	// Handle external enum type.
 	if modName != "" {
-		modName = "_" + strings.ReplaceAll(modName, "/", ".") + "."
+		modName = strings.ReplaceAll(modName, "/", ".") + "."
```
Comment (abhinav) [inline pkg/codegen/python/gen.go:274]: optional: I think we could maybe avoid doing the same transformations in two places and treat that if block more as a special case that just modifies pkgName and modName:

```go
if ... {
  pkgName = "" // local reference
  // ...
}

if modName != "" {
  modName = strings.ReplaceAll(...)
}

// And then something concatenation based, or like the following.
var parts []string
if pkgName != "" { parts = append(parts, pyPack(pkgName)) }
if modName != "" { parts = append(parts, strings.ReplaceAll(modName, ...)) }
parts = append(parts, name)
return strings.Join(parts, ".")
```

That reads as two phases: extract the necessary information, then combine it to produce the result.

**Review by abhinav — APPROVED** [review]
no blocker, just a suggestion

**Comment by dixler** [comment]
bors merge

**Comment by dixler** [comment]
bors merge

**Comment by dixler** [comment]
bors merge

**Comment by dixler** [comment]
bors retry
