### PR TITLE
Fix error codes for early exceptions

### LINKED ISSUE #2316: Failure to load gRPC Node module leads to deleting all resources
A user hit a case where `pulumi update --yes` deleted all resources after hitting the error below.  Presumably this somehow led the engine to not register any resources, but to believe the program had completed succesfully, so that it treated all old resources as needing to be deleted.

Clearly we should never allow this to happen.

```
Diagnostics:
  pulumi:pulumi:Stack (compute-b-compute-b-stage-eus2):
    (node:97) UnhandledPromiseRejectionWarning: Error: Failed to load gRPC binary module because it was not installed for the current system
    Expected directory: node-v64-linux-x64-glibc
    Found: [node-v64-darwin-x64-unknown]
    This problem can often be fixed by running "npm rebuild" on the current system
    Original error: Cannot find module '/data/pulumi/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'
        at Object.<anonymous> (/data/pulumi/node_modules/grpc/src/grpc_extension.js:53:17)
        at Module._compile (internal/modules/cjs/loader.js:689:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (internal/modules/cjs/helpers.js:22:18)
        at Object.<anonymous> (/data/pulumi/node_modules/grpc/src/client_interceptors.js:144:12)
        at Module._compile (internal/modules/cjs/loader.js:689:30)
    (node:97) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)                                                                                                                 
    (node:97) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.                                                                                                                                                             

Resources:
    - 3 to delete
```

### PR DESCRIPTION
**Pull request by pgavlin**
It is possible for the sub-process responsible for running a NodeJS
Pulumi program to exit with a success code before the user's program has
run if the process of loading the runtime generates an unhandled promise
rejection. These changes fix this by registering the unhandled exception
and rejection handlers that are responsible for ensuring a non-zero exit
code in these cases before any other action is taken.

Note that this issue is really only possible because the Node language
host (like the Python language host) is composed of two processes: one
that serves the language host gRPC service and one that loads and runs
the user's program. The former launches the latter in response to a call
to its `Run` gRPC endpoint. The lifetime of the user's program is
considered to be bounded by the lifetime of the `Run` invocation. The
NodeJS process maintains its own connection to the engine over which
resource registrations are communicated. It is tempting to add a message
to the resource monitor RPC interface that signals that no further
registrations are performed, but this is complicated due to the
three-party topology and the possibility that such an RPC may never be
sent (e.g. due to a crash or a downlevel version of the Pulumi Node
runtime).

Fixes #2316.

### CODE REVIEW

**Comment by pgavlin** [comment]
Ping.

File: sdk/nodejs/cmd/run/run.ts [hunk 1]
```diff
@@ -117,7 +117,7 @@ function reportModuleLoadFailure(program: string, error: Error): never {
     return process.exit(1);
 }
 
-export function run(argv: minimist.ParsedArgs): void {
+export function run(argv: minimist.ParsedArgs, programStarted: () => void): void {
```
Comment (swgillespie) [inline sdk/nodejs/cmd/run/run.ts]: Maybe I'm being dense but I'm not seeing any corresponding change to callers of `run` to pass a function - what's the semantics here?
