### PR TITLE
Fix mangled diffs of strings containing url-encoded chars

### LINKED ISSUE #16123: pulumi prints mangled values in diff of stack outputs with url-encoded characters
### What happened?

In my production code a URL path containing %2F gets added  a "!(MISSING)" part.
When tried to write a minimal code that reproduces the issue, the string becomes "!(NOVERB)"

### Example

https://gitlab.com/mattesilver/pulumi-percent

### Output of `pulumi about`

pulumi about
CLI          
Version      3.115.0
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown

Host     
OS       debian
Version  12.5
Arch     x86_64

This project is written in nodejs: executable='/home/matte/.nvm/versions/node/v20.12.0/bin/node' version='v20.12.0'

Current Stack: mattesilver/pulumi-percent/dev

TYPE                 URN
pulumi:pulumi:Stack  urn:pulumi:dev::pulumi-percent::pulumi:pulumi:Stack::pulumi-percent-dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/mattesilver
User           mattesilver
Organizations  mattesilver
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.115.0
@types/node     18.19.31
typescript      5.4.5

Pulumi locates its logs in /tmp by default

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
Fix mangled diffs of strings containing url-encoded chars

Currently, modifying a stack output that contains url-encoded characters can lead to it showing the value as `"!(NOVERB)"` or `"!(MISSING)"`.

For example, changing a stack output `path` from `"%2F"` to `"%2f"` shows the diff as:

```
Outputs:
  ~ path: "%!(NOVERB)F" => "%!(NOVERB)f"
```

The expected diff output should be:

```
Outputs:
  ~ path: "%2F" => "%2f"
```

This is happening because the code that emits parts of the diff is expecting a format string. Go is trying to parse the `%` in the value as a format string and is having problems parsing it.

The fix is to emit the parts of the diff verbatim, so it isn't treated as a format string.

Fixes #16123

Note: I've done an audit of the other calls to `write` in `object_diff.go` and all the other call sites are passing actual format strings or constants. This was the only case where we were passing user input as a format string.

### CODE REVIEW

File: pkg/backend/display/object_diff.go [hunk 1]
```diff
@@ -1093,9 +1093,9 @@ func (p *propertyPrinter) printCharacterDiff(diffs []diffmatchpatch.Diff) {
 	for _, d := range diffs {
 		switch d.Type {
 		case diffmatchpatch.DiffDelete:
-			p.withOp(deploy.OpDelete).write(escape(d.Text))
+			p.withOp(deploy.OpDelete).writeVerbatim(escape(d.Text))
```
Comment (justinvp) [inline pkg/backend/display/object_diff.go:1096]: To make this easier to review, here's the difference between `write` and `writeVerbatim`:

https://github.com/pulumi/pulumi/blob/ff8c44f9f51a3197aca11a7632e7f7a5a431c3de/pkg/backend/display/object_diff.go#L548-L554

https://github.com/pulumi/pulumi/blob/ff8c44f9f51a3197aca11a7632e7f7a5a431c3de/pkg/backend/display/object_diff.go#L110-L116

**Review by Frassle — APPROVED** [review]
