### PR TITLE
[codegen/dotnet] Qualify function input type paths

### LINKED ISSUE #8510: [codegen/dotnet] Failing Test: invalid function type pathing
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We generate functions whose argument paths are not valid. This bug shows up in the `"plain-object-defaults"` and `"plain-objects-disable-defaults"` tests. 

### Steps to reproduce

1.
2.
3.
4.

Expected: 
Actual:

### PR DESCRIPTION
**Pull request by iwahbe**
# Description

Fully qualify the `Input.*` types for function inputs. This allows us to reenable several compile tests for `.NET`. 

Fixes #8510 

## Checklist

- [X] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/codegen/internal/test/testdata/external-resource-schema/dotnet/ArgFunction.cs [hunk 1]
```diff
@@ -6,6 +6,7 @@
 using System.Collections.Immutable;
 using System.Threading.Tasks;
 using Pulumi.Serialization;
+using Pulumi.Example;
```
Comment (justinvp) [inline pkg/codegen/internal/test/testdata/external-resource-schema/dotnet/ArgFunction.cs:9]: Since everything is being emitted inside `namespace Pulumi.Example { ... }`, there shouldn't be a need for `using Pulumi.Example;`

File: pkg/codegen/internal/test/testdata/output-funcs-edgeorder/dotnet/ListConfigurations.cs [hunk 2]
```diff
@@ -31,22 +32,22 @@ public static Output<ListConfigurationsResult> Invoke(ListConfigurationsInvokeAr
     public sealed class ListConfigurationsArgs : Pulumi.InvokeArgs
     {
         [Input("configurationFilters", required: true)]
-        private List<Inputs.ConfigurationFilters>? _configurationFilters;
+        private List<Pulumi.Myedgeorder.Inputs.ConfigurationFilters>? _configurationFilters;
```
Comment (justinvp) [inline pkg/codegen/internal/test/testdata/output-funcs-edgeorder/dotnet/ListConfigurations.cs:35]: Ah, this is a case where you could just have `Inputs.ConfigurationFilters` here because this is already within `namespace Pulumi.Myedgeorder { ... }`.

**Comment by iwahbe** [comment]
>Since everything is being emitted inside `namespace Pulumi.Example { ... }`, there shouldn't be a need for using `Pulumi.Example`;

> Ah, this is a case where you could just have `Inputs.ConfigurationFilters` here because this is already within `namespace Pulumi.Myedgeorder { ... }`.

You are right. Based on this, I limited the scope of the change to when the function namespace disagrees with the mod namespace. This removed the unnecessary diffs.

File: pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs [hunk 3]
```diff
@@ -6,6 +6,7 @@
 using System.Collections.Immutable;
 using System.Threading.Tasks;
 using Pulumi.Serialization;
+using Pulumi.Example;
```
Comment (justinvp) [inline pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs:9]: This `using` statement shouldn't be necessary, since all the uses below are fully qualified.

File: pkg/codegen/internal/test/testdata/resource-property-overlap/schema.json [hunk 4]
```diff
@@ -12,9 +12,9 @@
   },
   "language": {
     "csharp": {
-      "packageReferences": {
-        "Pulumi": "3.12"
-      }
+      "projectReferences": [
```
Comment (justinvp) [inline pkg/codegen/internal/test/testdata/resource-property-overlap/schema.json:15]: What's the reasoning behind this change? Why do some schemas use a package reference while others use a project reference?

**Review by justinvp — APPROVED** [review]
LGTM otherwise

File: pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs (hunk 3 above)
Comment (iwahbe) [reply pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs:9]: I don't understand exactly why it is necessary, but it is. Removing the `using Pulumi.Example` causes the build to fail with:
```
❯ dotnet build -nologo
  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs(19,177): error CS1061: 'InvokeOptions' does not contain a definition for 'WithVersion' and no accessible extension method 'WithVersion' accepting a first argument of type 'InvokeOptions' could be found (are you missing a using directive or an assembly reference?) [/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/Pulumi.Example.csproj]
/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs(19,169): warning CS8602: Dereference of a possibly null reference. [/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/Pulumi.Example.csproj]
/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs(25,178): error CS1061: 'InvokeOptions' does not contain a definition for 'WithVersion' and no accessible extension method 'WithVersion' accepting a first argument of type 'InvokeOptions' could be found (are you missing a using directive or an assembly reference?) [/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/Pulumi.Example.csproj]
/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs(25,170): warning CS8602: Dereference of a possibly null reference. [/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/Pulumi.Example.csproj]
/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/Inputs/HelmReleaseSettingsArgs.cs(39,27): warning CS8604: Possible null reference argument for parameter 'value' in 'Input<string>.implicit operator Input<string>(string value)'. [/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/Pulumi.Example.csproj]

Build FAILED.

/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs(19,169): warning CS8602: Dereference of a possibly null reference. [/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/Pulumi.Example.csproj]
/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs(25,170): warning CS8602: Dereference of a possibly null reference. [/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/Pulumi.Example.csproj]
/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/Inputs/HelmReleaseSettingsArgs.cs(39,27): warning CS8604: Possible null reference argument for parameter 'value' in 'Input<string>.implicit operator Input<string>(string value)'. [/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/Pulumi.Example.csproj]
/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs(19,177): error CS1061: 'InvokeOptions' does not contain a definition for 'WithVersion' and no accessible extension method 'WithVersion' accepting a first argument of type 'InvokeOptions' could be found (are you missing a using directive or an assembly reference?) [/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/Pulumi.Example.csproj]
/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs(25,178): error CS1061: 'InvokeOptions' does not contain a definition for 'WithVersion' and no accessible extension method 'WithVersion' accepting a first argument of type 'InvokeOptions' could be found (are you missing a using directive or an assembly reference?) [/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/Pulumi.Example.csproj]
    3 Warning(s)
    2 Error(s)

Time Elapsed 00:00:01.63
```

File: pkg/codegen/internal/test/testdata/resource-property-overlap/schema.json (hunk 4 above)
Comment (iwahbe) [reply pkg/codegen/internal/test/testdata/resource-property-overlap/schema.json:15]: Ideally, all schemas should use a `projectReference` and refer to the sdk that they are compiling against. That way we can catch when we break codegen by changing the schema. I don't remember why I changed this specific schema. 

The reason we had packageReferences originally AFAIK, is because we didn't support the `projectReference` option in the schema.

File: pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs (hunk 3 above)
Comment (justinvp) [reply pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs:9]: I see. `options.WithVersion()` is an extension method defined in a generated `Utilities.cs` within the `Pulumi.Example` namespace. The using directive is necessary to call the extension method.

Looking at the schema for this test makes me question one aspect of it. The package name is `example` and all the resource and type tokens in the schema are correctly prefixed with `example:`. However, the function is prefixed with `mypkg:`:

https://github.com/pulumi/pulumi/blob/5da5cdb9dd807c83ca07e3e983dec94dc4ffec34/pkg/codegen/internal/test/testdata/plain-object-disable-defaults/schema.json#L186-L187

I think we need to change that function from `mypkg::funcWithAllOptionalInputs` to `example::funcWithAllOptionalInputs`.

Comment (iwahbe) [reply pkg/codegen/internal/test/testdata/plain-object-disable-defaults/dotnet/FuncWithAllOptionalInputs.cs:9]: Is `"mypkg::funcWithAllOptionalInputs"` a valid function for this schema? If all names _must_ begin with `"example::"` we should fail to process the schema. Because codegen produced an output, I assumed that the name is valid.
