### PR TITLE
[PCL] Fix panic in parseProxyApply when encoutering warning diagnostics

### LINKED ISSUE #20419: Typechecking assertion panics on pulumi convert
### What happened?

Using v3.191.0 and the PCL below, I run `pulumi convert --from pcl --language typescript`

and am rewarded with the following panic:

`panic: fatal: An assertion has failed: error typechecking expression: debug.pp:22,45-57: unknown property 'dns_name' among [dnsName hostedZoneId];`

Gist of stack trace: https://gist.github.com/guineveresaenger/58b7f15d158ea4a3b005ed4abce82ebe

### Example

Pulumi PCL
```
resource "ptfeService" "aws:ec2/vpcEndpoint:VpcEndpoint" {
  __logicalName     = "ptfe_service"
  vpcId             = vpcId
  serviceName       = ptfeServiceConfig
  vpcEndpointType   = "Interface"
  securityGroupIds  = [ptfeServiceAwsSecurityGroup.id]
  subnetIds         = [subnetIds]
  privateDnsEnabled = false
}

internal = invoke("aws:route53/getZone:getZone", {
  name        = "vpc.internal."
  privateZone = true
  vpcId       = vpcId
})

resource "ptfeServiceRecord" "aws:route53/record:Record" {
  __logicalName = "ptfe_service"
  zoneId        = internal.zoneId
  name          = "ptfe.${internal.name}"
  type          = "CNAME"
  ttl           = "300"
  records       = [ptfeService.dnsEntries[0]["dns_name"]]
}
```

### Output of `pulumi about`

```
CLI          
Version      3.191.0
Go Version   go1.25.0
Go Compiler  gc

Host     
OS       darwin
Version  15.5
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/guinevere-pulumi-corp
User           guinevere-pulumi-corp
Organizations  guinevere-pulumi-corp, pulumi
Token type     personal
```

```
pulumi plugin ls
NAME        KIND       VERSION  SIZE    INSTALLED     LAST USED
aws         resource   7.6.0    832 MB  23 hours ago  23 hours ago
cloudflare  resource   6.6.0    168 MB  19 hours ago  19 hours ago
gcp         resource   8.41.1   200 MB  20 hours ago  20 hours ago
gcp         resource   7.38.0   205 MB  20 hours ago  20 hours ago
terraform   converter  1.2.3    42 MB   2 days ago    2 days ago
```

### Additional context

This was discovered attempting to upgrade the pulumi-terraform-bridge. Pulumi-aws will fail to build its schema.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Follow up to #20453 

It looks like there were a few more places where we needed to check for warnings instead of errors of after `<expr>.Typecheck(...)`otherwise we panic as reported by @guineveresaenger [here](https://github.com/pulumi/pulumi/issues/20419#issuecomment-3335436933)

Fixes #20419

### CODE REVIEW

**Review by guineveresaenger — COMMENTED** [review]
I've verified that this fixes the issue locally. 🎉 

I'll leave the explicit approval to the repo owners, but LGTM.

File: pkg/codegen/pcl/binder_resource.go [hunk 1]
```diff
@@ -572,7 +572,11 @@ func (b *binder) bindResourceBody(node *Resource) hcl.Diagnostics {
 						}),
 					}
 					diags := condExpr.Typecheck(false)
-					contract.Assertf(len(diags) == 0, "failed to typecheck conditional expression: %v", diags)
+					checkDiagnostics := len(diags) == 0
+					if b.options.skipResourceTypecheck {
```
Comment (Frassle) [inline pkg/codegen/pcl/binder_resource.go:576]: So if skipResourceTypecheck is false then we can't even have warnings here, but if skip is true then we still can't have any errors? Why isn't the whole Assertf protected by skipResourceTypecheck?

Comment (Zaid-Ajaj) [reply pkg/codegen/pcl/binder_resource.go:576]: - if strict then no diagnostics allowed, not even warnings (current behaviour)
- if non-strict (`skipResourceTypecheck == true`) then no _error_ diagnostics allowed, only warnings (what this PR does)

> Why isn't the whole Assertf protected by skipResourceTypecheck?

because we still want to assert on "no diagnostics" when in strict mode (current behaviour)

Comment (Frassle) [reply pkg/codegen/pcl/binder_resource.go:576]: Ok so why aren't the checks in gen_program_lower also the same. i.e. check for skipResourceTypecheck to decide if its no diagnostics, or just no warnings

Comment (Zaid-Ajaj) [reply pkg/codegen/pcl/binder_resource.go:576]: don't have access to the binder options from program generators, although I think we can expose it
