### PR TITLE
Do not resolve missing outputs to inputs in preview.

### LINKED ISSUE #2433: `apply` gets run when inputs are provided before real outputs are available
Attempting to deploy this program fails during the `preview` with: `error: unexpected null property rrdatas[0]`.  The problem is that that `.apply` is getting run during the preview, even though we don't yet have the real value of the `accessConfigs`.  If we skipped the preview, this would succeed - but the preview should work here and should not be running the `apply` since the value is not yet available.

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

const google_compute_instance_frontend = new gcp.compute.Instance("frontend", {
  bootDisk: {
    initializeParams: {
      image: "debian-cloud/debian-9"
    }
  },
  machineType: "g1-small",
  name: "frontend",
  networkInterfaces: [
    {
      accessConfigs: [{}],
      network: "default"
    }
  ],
  zone: "us-central1-b"
});

const google_dns_managed_zone_prod = new gcp.dns.ManagedZone("prod", {
  description: "Naveen DNS zone",
  dnsName: "naveen.xyz.io.",
  labels: {
    foo: "bar"
  },

  name: "naveen-zone"
});
function isDefined<T>(value: T | undefined | null): value is T {
  return <T>value !== undefined && <T>value !== null;
}

const google_dns_record_set_frontend = new gcp.dns.RecordSet("frontend", {
  managedZone: google_dns_managed_zone_prod.name,
  name: google_dns_managed_zone_prod.dnsName.apply(
    __arg0 => `frontend.${__arg0}`
  ),
  rrdatas: [
    google_compute_instance_frontend.networkInterfaces.apply(t => {
      if (isDefined(t[0].accessConfigs)) {
        return t[0].accessConfigs[0].assignedNatIp;
      } else {
        return "";
      }
    })
  ],
  ttl: 300,
  type: "A"
});
```

### PR DESCRIPTION
**Pull request by pgavlin**
This can cause `apply`s to run on values that may change during an
update, which can lead to unexpected behavior.

Fixes #2433.

### CODE REVIEW

File: sdk/nodejs/runtime/resource.ts [hunk 1]
```diff
@@ -474,16 +475,18 @@ async function resolveOutputs(res: Resource, t: string, name: string,
...
+        for (const key of Object.keys(props)) {
+            if (!allProps.hasOwnProperty(key)) {
+                // input prop the engine didn't give us a final value for.  Just use the value passed into the resource
+                // after round-tripping it through serialization. We do the round-tripping primarily s.t. we ensure that
+                // Output values are handled properly w.r.t. unknowns.
+                const inputProp = await serializeProperty(label, props[key], new Set());
+                if (inputProp === undefined) {
+                    continue;
+                }
+                allProps[key] = deserializeProperty(inputProp);
```
Comment (lukehoban) [inline sdk/nodejs/runtime/resource.ts]: I'm trying to wrap my head around why we do want to do this for update but don't want to for preview? I'm sure at one point I knew the answer to this - but can't reconstruct in my head right now.

A comment here on the rationale (and links to issues?) may help me and future readers.

Comment (ellismg) [reply sdk/nodejs/runtime/resource.ts]: I also don't understand this comment now:

> We do the round-tripping primarily s.t. we ensure that Output values are handled properly w.r.t. unknowns.

In what cases would there be unknowns here during an update?  Wouldn't all inputs be known before doing the RPC during an update (there can be no computed values running around then, right?)

Comment (pgavlin) [reply sdk/nodejs/runtime/resource.ts]: To be honest, I'm not sure that we do want to do this during an update: I left it in for compatibility reasons. We don't want to do this during the preview because we can't know which inputs might or might not be resolved during the update.

Comment (CyrusNajmabadi) [reply sdk/nodejs/runtime/resource.ts]: i'm not certain i get this either.  can you clarify what would happen during preview now?

Comment (pgavlin) [reply sdk/nodejs/runtime/resource.ts]: > i'm not certain i get this either. can you clarify what would happen during preview now?

Essentially, we would not run any `apply`s hung off of the outputs of a resource that is to be updated or replaced.

**Comment by pgavlin** [comment]
> We should make a note of this in the CHANGELOG. I'm not really sure what the best way to say this is, maybe something like: "Pulumi will no longer run apply calls for outputs of a resource if they were not set by the underlying resource provider during a preview"

Yep, I planned on adding something like this. Do we consider this a breaking change?

> I know the reason we've hesitated to do this is the past because we aren't sure what the impact is going to end up being. Do you think it is worthwhile to add a PULUMI_USE_LEGACY_APPLY_BEHAVIOR for the short term in order to allow folks to have a quick way to get back to the old behavior? I think making this the default now is right, since the previous model was very confusing and would lead to breaks that are very very difficult to understand.

Given that this is a very easy change to make, I do think that it's reasonable to do so, yes.

**Comment by lukehoban** [comment]
> Do we consider this a breaking change?

Given that this only impacts preview, and especially if we also have a opt-out flag, I think this does not need to be listed as a breaking change. 

I would love to ensure we don’t see any surprising results due to this in practice in our own nightly coverage though as input to how loudly we need to communicate this change.

**Comment by pgavlin** [comment]
I am going to go ahead and merge this now that v0.17.28 has landed.
