### PR TITLE
Fix docs generator parent module computation 

### LINKED ISSUE #14820: bug(codegen): docs generator fails when nested module has same name as function or resource
### What happened?

As described in https://github.com/pulumi/pulumi/pull/14308#issuecomment-1774812922 and https://github.com/pulumi/pulumi/pull/14308#issuecomment-1777972676 the docs generator in `codegen/docs/gen.go` has bug that leads to a panic when a module has the same name as a resource or function within it. 

The `moduleConflictResolver` should prevnt this to happen but it does not.

```go
panic: fatal: An assertion has failed: duplicate file: router/bgp/_index.md

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /home/vagrant/code/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x30?, {0x1ae9498?, 0xc00d629530?}, {0xc000bcf040?, 0x48797e?, 0x1a24940?})
        /home/vagrant/code/pulumi/sdk/go/common/util/contract/assert.go:35 +0xed
github.com/pulumi/pulumi/pkg/v3/codegen.Fs.Add(...)
        /home/vagrant/code/pulumi/pkg/codegen/utilities.go:180
github.com/pulumi/pulumi/pkg/v3/codegen/docs.(*modContext).gen.func1({0x0, 0x0}, {0x1adb5af, 0xa}, {0x1a24940, 0xc00e3303c0})
        /home/vagrant/code/pulumi/pkg/codegen/docs/gen.go:1854 +0x225
github.com/pulumi/pulumi/pkg/v3/codegen/docs.(*modContext).gen(0xc000bf2aa0, 0xc000bede00)
        /home/vagrant/code/pulumi/pkg/codegen/docs/gen.go:1962 +0x11db
github.com/pulumi/pulumi/pkg/v3/codegen/docs.(*docGenContext).generatePackage(0xc0000c1400, {0x0?, 0x0?}, 0x0?)
        /home/vagrant/code/pulumi/pkg/codegen/docs/gen.go:2201 +0x2e8
github.com/pulumi/pulumi/pkg/v3/codegen/docs.GeneratePackage(...)
        /home/vagrant/code/pulumi/pkg/codegen/docs/gen.go:2255
github.com/pulumi/registrygen/pkg.generateDocsFromSchema({0x7ffeb02ae50a, 0xf}, 0xc4a256?)
        /home/vagrant/code/pulumi-registrygen/pkg/docs.go:218 +0x54
github.com/pulumi/registrygen/pkg.GenerateDocs({0x7ffeb02ae493?, 0x0?}, {0x7ffeb02ae4b8, 0x6}, {0x7ffeb02ae4cc, 0x30}, {0x7ffeb02ae50a, 0xf}, {0x7ffeb02ae532, 0xb}, ...)
        /home/vagrant/code/pulumi-registrygen/pkg/docs.go:111 +0x896
github.com/pulumi/registrygen/cmd/docs.PackageDocsCmd.func1(0xc0007ff800?, {0x1ad0743?, 0x9?, 0x9?})
        /home/vagrant/code/pulumi-registrygen/cmd/docs/cli.go:89 +0x74
github.com/spf13/cobra.(*Command).execute(0xc0007ff800, {0xc0006943f0, 0x9, 0x9})
        /home/vagrant/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0007fe600)
        /home/vagrant/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0xc000124120?)
        /home/vagrant/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
        /home/vagrant/code/pulumi-registrygen/main.go:30 +0x8b
```

### Example

**Example:**

Module: `Router` Resource: `Bgp`: path for `resource.tmpl` file = `router/bgp/_index.md`
Module: `Router/Bgp`: path for module _index.md file = `router/bgp/_index.md`

### Output of `pulumi about`

The `registrygen` tool is build using 

```
github.com/pulumi/pulumi/pkg/v3 v3.95.0
github.com/pulumi/pulumi/sdk/v3 v3.95.0
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #14821: bug(codegen): docs generator creates invalid package tree for nested modules
### What happened?

The `generatePackageTree` in `codegen/docs/package_tree.go` creates an invalid package tree when nested modules are used inside the provider schema to separate resources and functions into namespaces of the supported programming languages.

Invalid tree

```json
  {
    "name": "log",
    "type": "module",
    "link": "log/",
    "children": [
      {
        "name": "v2",
        "type": "module",
        "link": "log/fortianalyzer/v2/",
        "children": [
          {
            "name": "Filter",
            "type": "resource",
            "link": "res-filter"
          },
          {
            "name": "Overridefilter",
            "type": "resource",
            "link": "res-overridefilter"
          },
          {
            "name": "Overridesetting",
            "type": "resource",
            "link": "res-overridesetting"
          },
          {
            "name": "Setting",
            "type": "resource",
            "link": "res-setting"
          }
        ]
      },

```

Expected tree

```json
  {
    "name": "log",
    "type": "module",
    "link": "log/",
    "children": [
      {
        "name": "syslogd",
        "type": "module",
        "link": "log/syslogd/",
        "children": [
          {
            "name": "v2",
            "type": "module",
            "link": "log/syslogd/v2/",
            "children": [
              {
                "name": "Filter",
                "type": "resource",
                "link": "res-filter"
              },
              {
                "name": "Overridefilter",
                "type": "resource",
                "link": "res-overridefilter"
              },
              {
                "name": "Overridesetting",
                "type": "resource",
                "link": "res-overridesetting"
              },
              {
                "name": "Setting",
                "type": "resource",
                "link": "res-setting"
              }
            ]
          }
```

### Example

Snippet from the provider schema:

```json
        "fortios:log/syslogd/v2/filter:Filter": {

        },
        "fortios:log/syslogd/v2/overridefilter:Overridefilter": {

        },
        "fortios:log/syslogd/v2/overridesetting:Overridesetting": {

        },
        "fortios:log/syslogd/v2/setting:Setting": {

        },
```

### Output of `pulumi about`

The `registrygen` tool is build using 

```
github.com/pulumi/pulumi/pkg/v3 v3.95.0
github.com/pulumi/pulumi/sdk/v3 v3.95.0
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by t0yv0**
# Description

Fixes #14820
Fixes #14821

Fixes a bug in docs generator parent module computation that used to lead to duplicate files panics and undesirable documentation URL layout for affected providers such as [pulumi/fortios](https://github.com/pulumiverse/pulumi-fortios/issues).

Joint work with @tmeckel .

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [ ] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/codegen/docs/gen.go [hunk 1]
```diff
@@ -2016,33 +2017,38 @@ func (dctx *docGenContext) getMod(
 	add bool,
 ) *modContext {
 	modName := pkg.TokenToModule(token)
-	mod, ok := modules[modName]
+	return dctx.getModByModName(pkg, tokens.ModuleName(modName), tokenPkg, modules, tool, add)
+}
+
+func (dctx *docGenContext) getModByModName(
```
Comment (t0yv0) [inline pkg/codegen/docs/gen.go:2023]: @tmeckel when reviewing your PR noticed that getMod() recurses indefinitely for google-native. How about something like this change.. we get it recurse over ModuleName instead of token, and try to get parent computation more precise.

File: pkg/codegen/docs/gen.go [hunk 2]
```diff
@@ -2016,33 +2017,38 @@ func (dctx *docGenContext) getMod(
...
-			mod:           modName,
+			mod:           string(modName),
 			tool:          tool,
 			docGenContext: dctx,
 		}
 
 		if modName != "" && codegen.PkgEquals(tokenPkg, pkg) {
-			parentName := path.Dir(modName)
-			// If the parent name is blank, it means this is the package-level.
-			if parentName == "." || parentName == "" {
```
Comment (t0yv0) [inline pkg/codegen/docs/gen.go:2031]: I guess the old code normalized "." and "" to "index", this is a little interesting, I think it might be an artifact of path.Dir and not actual pulumi module names? But we can preserve this oddity and normalize them to "index".

File: pkg/codegen/docs/gen.go (hunk 1 above)
Comment (tmeckel) [reply pkg/codegen/docs/gen.go:2023]: @t0yv0 just came up with another solution of my own. Let me check yours after mine. But when your solution works as well, we should adopt yours because I had to introduce `HasModuleFormat` on the `type Package struct`

Comment (t0yv0) [reply pkg/codegen/docs/gen.go:2023]: Ah very neat. Well I'll let you drive and check your PR again tomorrow. Thanks.!

File: pkg/codegen/docs/gen.go [hunk 3]
```diff
@@ -2016,33 +2017,38 @@ func (dctx *docGenContext) getMod(
...
-				parentName = ":index:"
-			} else {
-				parentName = ":" + parentName + ":"
-			}
-			parent := dctx.getMod(pkg, parentName, tokenPkg, modules, tool, add)
-			if add {
+			parentName, hasParent := parentModule(modName)
+			if add && hasParent {
```
Comment (tmeckel) [inline pkg/codegen/docs/gen.go:2042]: `&& hasParent` has to be removed, otherwise the nav tree gets crippled because children don't get connected to parents.

**Review by tmeckel — CHANGES_REQUESTED** [review]

**Comment by t0yv0** [comment]
Yeah possibly some CI bitrot, will look.

**Comment by t0yv0** [comment]
```
  Error: `pulumi` forbids access via a personal access token (classic). Please use a GitHub App, OAuth App, or a personal access token with fine-grained permissions.
```

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi/blob/t0yv0%2Favoid-inf-recursion-in-get-mod/.github/workflows/ci-test-docs-generation.yml#L106

**Comment by t0yv0** [comment]
Might need to rotate secrets.PULUMI_BOT_GH_PAT_DOCS looks like I don't have access though.

**Comment by t0yv0** [comment]
Trying this out in a registry PR https://github.com/pulumi/registry/pull/3708

**Review by tmeckel — APPROVED** [review]
✅ LGTM

Incorporating https://github.com/tmeckel/pulumi/commit/dcaf42199afd4fca46ea9cc7006d71b8a6d45042 would be nice 👍🏼

File: pkg/codegen/docs/gen.go (hunk 2 above)
Comment (Frassle) [reply pkg/codegen/docs/gen.go:2031]: I've seen tokens like "pkg:typ" which should normalise to "pkg:index:typ". The topmost module is either "" or "index".

**Comment by blampe** [comment]
> https://github.com/pulumi/pulumi/blob/t0yv0%2Favoid-inf-recursion-in-get-mod/.github/workflows/ci-test-docs-generation.yml#L106

@t0yv0 you should be able to use the existing `secrets.PULUMI_BOT_TOKEN` here -- it has read-write access to every repo.

File: pkg/codegen/docs/gen.go (hunk 2 above)
Comment (t0yv0) [reply pkg/codegen/docs/gen.go:2031]: That's a great observation, let me fix it to handle both of those. I'm guessing "." is never a topmost module but was an artifact of using filepath.Dir

Comment (Frassle) [reply pkg/codegen/docs/gen.go:2031]: Yes I believe so

**Comment by t0yv0** [comment]
I think the new token helped but the job remains broken, will need to keep debugging that it seems.

**Comment by tmeckel** [comment]
@Frassle @blampe @t0yv0 any progress here? Waiting for this patch, to finally get the pulumi-fortios provider in Pulumiverse out the door 😃 https://github.com/pulumiverse/pulumi-fortios/tree/feat/prepare-release

**Comment by t0yv0** [comment]
It's on the list but slipping a bit as I'm addressing some customer P1s. Stay tuned. I need to address PR comments.  Hopefully next week.

**Comment by t0yv0** [comment]
I've looked at the index handling a bit, it's a bit surprising/too interesting perhaps. The heavy lifting is done in the TokenToModule function which we now call:

https://github.com/pulumi/pulumi/blob/t0yv0%2Favoid-inf-recursion-in-get-mod/pkg/codegen/schema/schema.go#L861

It already treats "index" specially and it respects "moduleFormat".

Slightly weird tables:

```
  TokenToModule("pulumi:providers:testindex") == ""
  TokenToModule("pulumi:providers:random") == ""
  TokenToModule("pulumi:providers:fortios") == ""
  TokenToModule("fortios:router/bgp/network:Network") == "router/bgp"
  TokenToModule("fortios:log/syslogd/v2/setting:Setting") == "log/syslogd/v2"
```

Note that it chops off "/setting" from "fortios:log/syslogd/v2/setting" - I think this is because it uses the module format regex.

AS far as this code is concerned it seems we do not need to treat it specially - I've added a few test cases around the index module, one from the random provider and one made up and verified that they are passing before and after the change. The only changes are the ones we want that fix up fortios provider.

**Comment by tmeckel** [comment]
@Frassle @t0yv0 @blampe any chance that this PR gets merged next week? 😏 

There is still an error in the `Downstream Resource Docs Test / CI Codegen / Resource Docs (pull_request)` workflow.

https://github.com/pulumi/pulumi/actions/runs/7628004850/job/20778035592?pr=15035#step:11:8

image

If can provide any help here guys, let me know.

**Comment by tgummerer** [comment]
I believe https://github.com/pulumi/docs/pull/10053 + https://github.com/pulumi/pulumi/pull/14157 would fix the Resource Docs CI job.

**Comment by tgummerer** [comment]
I took the liberty to rebase this on the latest master branch and push the results, which should hopefully fix the resource docs CI job.

**Comment by t0yv0** [comment]
Thanks @thomas11 - I'll try to find some time today to fix lint etc and move this forward. Should be close.

**Comment by t0yv0** [comment]
@tgummerer this now passes cleanly on CI, thank you!

**Comment by t0yv0** [comment]
@tgummerer still need a review from the team here if possible! Thank you.
