### PR TITLE
Print log file location to stderr for verbosity >= 1

### LINKED ISSUE #21654: Bad interaction between `PULUMI_OPTION_VERBOSE` and Automation API
### What happened?

All Automation API functionality that is backed by the Pulumi CLI will fail when `PULUMI_OPTION_VERBOSE` is set to `3` or greater. This is because the CLI outputs the location of the verbose logs at this level, which breaks Automation API's ability to parse the CLI version.

### Example

```go
package main
import (
	"fmt"
	"log"
	"github.com/pulumi/pulumi/sdk/v3/go/auto"
)
func main() {
	cmd, err := auto.NewPulumiCommand(nil)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(cmd.Version())
}
```

When run without `PULUMI_OPTION_VERBOSE`:

```console
verbose-automation-api ❯ go run .                        
3.216.0
```

When run with `PULUMI_OPTION_VERBOSE=3`:

```console
verbose-automation-api ❯ PULUMI_OPTION_VERBOSE=9 go run .
2026/02/02 16:04:06 Unable to parse Pulumi CLI version (skip with PULUMI_AUTOMATION_API_SKIP_VERSION_CHECK=true): Invalid character(s) found in patch number "0\nThe log file for this run is at [elided]"
exit status 1
```

### Output of `pulumi about`

n/a

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by i-am-tom**
With `PULUMI_OPTION_VERBOSE=3`, the CLI outputs information on where the log file for the command will end up. The `Version()` command doesn't expect there to be extra output here, so this PR makes sure we ignore everything after the first line.

Fixes #21654.

### CODE REVIEW

**Comment by i-am-tom** [comment]
At the moment, the only things that could output before are stderr and we ignore them for this. I'm nervous to solve it by turning off the flag simply because I added this flag, so I'm certain there are other ways to tweak verbosity that I don't know about 😄

File: sdk/go/auto/cmd_test.go [hunk 1]
```diff
@@ -115,6 +115,22 @@ func TestErrorIncompatibleVersion(t *testing.T) {
...
 
+// TestVersionWithVerboseEnv verifies that Version() works when PULUMI_OPTION_VERBOSE=3
+// is set, which causes "pulumi version" to print extra lines.
+func TestVersionWithVerboseEnv(t *testing.T) {
+	dir := t.TempDir()
+	version := semver.Version{Major: 3, Minor: 98, Patch: 0}
+	_, err := InstallPulumiCommand(context.Background(), &PulumiCommandOptions{Root: dir, Version: version})
+	require.NoError(t, err)
+
+	t.Setenv("PULUMI_OPTION_VERBOSE", "3")
```
Comment (tgummerer) [inline sdk/go/auto/cmd_test.go]: I'd probably use 
```suggestion
	t.Setenv("PULUMI_OPTION_VERBOSE", "11")
```

here if we want to keep just using the first line.

**Comment by iwahbe** [comment]
Could we solve this instead by printing `The log file for this run is at ${LOGFILE}` to stderr? It feels like that information is more appropriate for stderr anyway.

**Comment by Frassle** [comment]
+1 to @iwahbe's suggestion

**Comment by i-am-tom** [comment]
@Frassle Looks like it would be a problem in other APIs. If we're happy with @iwahbe's suggestion being within our "no breaking changes" goal then I think that's a much nicer fix!

File: pkg/cmd/pulumi/pulumi.go [hunk 2]
```diff
@@ -201,7 +201,7 @@ func NewPulumiCmd() (*cobra.Command, func()) {
 				logging.Warningf("could not find the log file: %s", err)
 				logging.Flush()
 			} else {
-				fmt.Printf("The log file for this run is at %s\n", logFile)
+				fmt.Fprintf(os.Stderr, "The log file for this run is at %s\n", logFile)
```
Comment (iwahbe) [inline pkg/cmd/pulumi/pulumi.go:204]: This would ideally target `cmd.cmd.ErrOrStderr()`, but it's not 100% necessary.

File: sdk/go/auto/cmd_test.go [hunk 3]
```diff
@@ -143,6 +143,18 @@ func TestNoGlobalPulumi(t *testing.T) {
 	require.NoError(t, err)
 }
 
+func TestVersionWithVerboseEnv(t *testing.T) {
+	dir := t.TempDir()
+	version := semver.Version{Major: 3, Minor: 98, Patch: 0}
+	_, err := InstallPulumiCommand(context.Background(), &PulumiCommandOptions{Root: dir, Version: version})
```
Comment (iwahbe) [inline sdk/go/auto/cmd_test.go]:
```suggestion
	_, err := InstallPulumiCommand(t.Context(), &PulumiCommandOptions{Root: dir, Version: version})
```

File: sdk/go/auto/cmd_test.go [hunk 4]
```diff
@@ -143,6 +143,18 @@ func TestNoGlobalPulumi(t *testing.T) {
 	require.NoError(t, err)
 }
 
+func TestVersionWithVerboseEnv(t *testing.T) {
```
Comment (iwahbe) [inline sdk/go/auto/cmd_test.go:146]: Shouldn't we test that we don't write to stdout at minimum?

Ideally we could show our intent by checking that `pulumi version` produces a stdout that is parsable back into a `semver.Version`.

File: changelog/pending/20260204--cli--write-logfile-location-pulumi_option_verbose-3-to-stderr-instead-of-stdout.yaml [hunk 5]
```diff
@@ -0,0 +1,4 @@
+changes:
+- type: chore
+  scope: cli
+  description: Write logfile location (PULUMI_OPTION_VERBOSE >= 3) to stderr instead of stdout
```
Comment (tgummerer) [inline changelog/pending/20260204--cli--write-logfile-location-pulumi_option_verbose-3-to-stderr-instead-of-stdout.yaml]:
```suggestion
  description: Write logfile location (PULUMI_OPTION_VERBOSE >= 1) to stderr instead of stdout
```

Or maybe "Write logfile location if verbosity is >= 1 to stderr instead of stdout", since this can be with both the env variable, but also `-v=x`?

Comment (i-am-tom) [reply changelog/pending/20260204--cli--write-logfile-location-pulumi_option_verbose-3-to-stderr-instead-of-stdout.yaml]: It's meant to be `>= 3`! But "verbosity" is definitely better, will update

Comment (tgummerer) [reply changelog/pending/20260204--cli--write-logfile-location-pulumi_option_verbose-3-to-stderr-instead-of-stdout.yaml]: What am I missing?  https://github.com/pulumi/pulumi/pull/21663/files#diff-1a08c0bf83a7a42a6f1f14ec20f37df61dc062185ed4fda0d777a2378cbe06acR198 just says `.Verbose > 0` we print the log file name.  Is there a different condition that makes it >=3?

Comment (i-am-tom) [reply changelog/pending/20260204--cli--write-logfile-location-pulumi_option_verbose-3-to-stderr-instead-of-stdout.yaml]: ... great question

```
pulumi/core » pulumi version            
v3.218.0
pulumi/core » pulumi version --verbose=1
v3.218.0
pulumi/core » pulumi version --verbose=2
v3.218.0
pulumi/core » pulumi version --verbose=3
v3.218.0
The log file for this run is at /var/folders/...
```

Comment (tgummerer) [reply changelog/pending/20260204--cli--write-logfile-location-pulumi_option_verbose-3-to-stderr-instead-of-stdout.yaml]: Hrm maybe there's just no logs in this case for verbose=1 or verbose=2? (I checked and that is the case).  But `pulumi version` is not the only command affected by this change, and other commands log at higher log levels.
