### PR TITLE
pkg/codegen/docs: Fix data race in tests

### LINKED ISSUE #11790: pkg/codegen/docs: Tests stomp on each other's state
pkg/codegen/docs contains tests that all call initTestPackageSpec to set a
global testPackageSpec variable, except these tests all run in parallel so
they're stomping on each other's state.

We should fix that.

### PR DESCRIPTION
**Pull request by abhinav**
Tests in pkg/codegen/docs all run in parallel,
but many of them call initTestPackageSpec,
which modifies the global testPackageSpec variable.
So these tests end up stomping on each other.
`go test -race` fails in this directory.

To address the data race,
this change deletes the global variable entirely,
and replaces initTestPackageSpec with newTestPackageSpec.
newTestPackageSpec returns a new copy of the package spec
which the tests can use individually.

Resolves #11790

### CODE REVIEW

File: pkg/codegen/docs/gen_test.go [hunk 1]
```diff
@@ -48,18 +48,13 @@ var (
...
 	}
-
-	// testPackageSpec represents a fake package spec for a Provider used for testing.
-	testPackageSpec schema.PackageSpec
 )
 
-func initTestPackageSpec(t *testing.T) {
-	t.Helper()
-
+func newTestPackageSpec() schema.PackageSpec {
```
Comment (Frassle) [inline pkg/codegen/docs/gen_test.go:53]:
```suggestion
// NewTestPackageSpec returns a new fake package spec for a Provider used for testing.
func newTestPackageSpec() schema.PackageSpec {
```

**Review by Frassle — APPROVED** [review]
Nice change

**Comment by abhinav** [comment]
bors merge
