### PR TITLE
[typescrypt/program-gen] Fix generated readFile function so that it includes the encoding

### LINKED ISSUE #14630: TS: PCL's `readFile` is translated to `fs.readFileSync(path)` instead of `fs.readFileSync(path, "utf-8")`
### What happened?

Following up on https://github.com/pulumi/pulumi-digitalocean/pull/346:

Our generated examples feed the result of `fs.readFileSync(path)` to a field of type `pulumi.Output<string>`. This does not work. We should instead be calling `fs.readFileSync(path, "utf-8")` (which actually returns a `string`). 

### Example

See https://github.com/pulumi/pulumi-digitalocean/blob/880a26e1ab47ef61671def9f3e90fa13a4560ac3/sdk/nodejs/sshKey.ts#L21.

### Output of `pulumi about`

NA

### Additional context

We can easily see that we will always generate the buffer permutation, not the string permutation:

https://github.com/pulumi/pulumi/blob/273951bb17ef45efeeebfe25be174c6df10c1e08/pkg/codegen/nodejs/gen_program_expressions.go#L461-L462

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

Small fix for generated `readFile` function so that it includes the encoding and returns a string

Fixes #14630

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/codegen/testing/test/program_driver.go [hunk 1]
```diff
@@ -109,6 +109,10 @@ var PulumiPulumiProgramTests = []ProgramTest{
 		Directory:   "aws-iam-policy",
 		Description: "AWS IAM Policy",
 	},
+	{
+		Directory:   "read-file-func",
```
Comment (justinvp) [inline pkg/codegen/testing/test/program_driver.go:113]: We already had the test data, but it wasn't hooked up in a test?

**Review by justinvp — APPROVED** [review]
LGTM

File: pkg/codegen/testing/test/program_driver.go (hunk 1 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/testing/test/program_driver.go:113]: I added this test a year ago but somehow it was removed from this list 😅 I asked on Slack if someone knows why it was removed but I am putting back in anyways

Maybe we should check for directories that are in testdata but aren't part of the SDK tests 🤔

Comment (tgummerer) [reply pkg/codegen/testing/test/program_driver.go:113]: To close the loop publicly, I believe this was a mismerge and we accidentally deleted this here: https://github.com/pulumi/pulumi/pull/10958/files#diff-860749d2dad497a2e4dbdb2e89ceb7ebc99bed8add0ba1ec6a7009946085d787L90
