### PR TITLE
cli(state upgrade): Prompt for project names for detached stacks

### LINKED ISSUE #12600: pulumi state upgrade skips stacks that had a recent `pulumi destroy` and I don't know how to remove or upgrade those stacks from s3 filestate
### What happened?

upgraded to latest version of CLI tool on windows - using s3 filestate, it was able to upgrade almost all projects - I had two that I had run a 'pulumi destroy' on and was tinkering with. when I run it again it doesn't seem able to upgrade those stacks and I don't think I can `pulumi stack select ` them to do a 'pulumi up` on. is there an easy way to delete them from my s3 filestate and make fresh? 

```
PS C:\source\infrastructure\pulumi\servers> pulumi state upgrade
warning: Found legacy stack files in state store:
  - servers-buildserver-prod
  - servers-example-test
Please run 'pulumi state upgrade' to migrate them to the new format.
Set PULUMI_SELF_MANAGED_STATE_NO_LEGACY_WARNING=1 to disable this warning.
This will upgrade the current backend to the latest supported version.
Older versions of Pulumi will not be able to read the new format.
Are you sure you want to proceed?
Please confirm that this is what you'd like to do by typing `yes`: yes
warning: Skipping stack "servers-buildserver-prod": no project found
warning: Skipping stack "servers-example-test": no project found
Upgraded 0 stack(s) to project mode
```

there are .yaml files in the directory I'm in for these stacks though.

let me know if there's an easy way to fix, or if I should just pop into my s3 bucket and manually remove those entries and manually remove those .yaml's - there's nothing super important there in the history but I would rather use the tool to make certain I don't confuse my other stacks.

thanks in advance!

### Expected Behavior

I would love to be able to still do a `pulumi stack select servers-example-test` to do a delete or stack rm on it -  right now I can't.
I think current behavior is mostly good, would like the cli to give me an additional log note like `to delete these empty stacks run command: {etc}` ?

### Steps to reproduce

1. create stack in older CLI version using s3 file state and aws kms secrets provider
2. do at least one `up` and one `destroy` so there is state up in s3
3. upgrade cli
4. run `pulumi state upgrade` with yes

### Output of `pulumi about`

warning: Found legacy stack files in state store:
  - servers-buildserver-prod
  - servers-example-test
Please run 'pulumi state upgrade' to migrate them to the new format.
Set PULUMI_SELF_MANAGED_STATE_NO_LEGACY_WARNING=1 to disable this warning.
CLI
Version      3.61.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME       VERSION
aws        5.30.0
dotnet     unknown
openstack  3.9.0
random     4.12.0

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='7.0.101'

Backend
Name           paul42_computer
URL            s3://test-pulumi-1
User           DOMAIN\paul42
Organizations

Dependencies:
NAME                                             VERSION
Microsoft.Extensions.Configuration.Abstractions  7.0.0
Pulumi                                           3.54.1
Pulumi.Random                                    4.12.0

Pulumi locates its logs in C:\Users\paul42\AppData\Local\Temp by default
warning: Failed to get information about the current stack: No current stack

### Additional context

love the tool, just curious if I'm missing a step to remove a stack from my filestate so I can make a fresh one. also is there a correct term for a stack that I did a `pulumi destroy` on? like 'empty stack'?

Thanks in advance, all!

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by abhinav**
When running 'pulumi state upgrade', supply the
ProjectsForDetachedStacks option to the file state backend so that we
get asked to fill in project names for stacks where we could not guess
them automatically.

The implementation of the prompt is straightforward:
For each stack, ask a question with the survey package
and feed the result back to the filestate backend.

Testing this is a bit complicated because terminals are involved.
The test for this uses the go-expect and vt10x libraries
recommended in the documentation for survey.
It uses them to simulate a terminal emulator and acts on the output.
The pty library is used to create a compatible pseduo-terminal.
Unfortunately, these test libraries rely on Unix APIs and are not
available on Windows, so the test will not run on Windows machines.

Resolves #12600

---

Preview

Kapture 2023-05-31 at 19 25 57

### CODE REVIEW

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* master
  * **PR #13076** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/13076" target="_blank">Graphite</a> 
    * **PR #13077** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/13077" target="_blank">Graphite</a> 
      * **PR #13078** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/13078" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi/13078?utm_source=stack-comment).

**Comment by abhinav** [comment]
Kapture 2023-05-31 at 19 25 57

File: pkg/cmd/pulumi/state_upgrade.go [hunk 1]
```diff
@@ -101,5 +110,89 @@ func (cmd *stateUpgradeCmd) Run(ctx context.Context) error {
...
+
+	return nil
+}
+
+func (w *stateUpgradeProjectNameWidget) validateProject(ans any) error {
+	proj, ok := ans.(string)
+	contract.Assertf(ok, "widget should have a string output, got %T", ans)
+
+	switch {
+	case proj == "": // empty string means skip
```
Comment (Frassle) [inline pkg/cmd/pulumi/state_upgrade.go:189]: Bit ick that we're rewriting this >100 IsName logic _again_, must be like 4 or 5 places now with this. At the least lets put a helper function somewhere that all these call sites can use.

Comment (abhinav) [reply pkg/cmd/pulumi/state_upgrade.go:189]: Yeah, I didn't like it either. I'll fix it.

Comment (abhinav) [reply pkg/cmd/pulumi/state_upgrade.go]: Done. Added to bottom of the stack https://github.com/pulumi/pulumi/pull/13165

**Review by Frassle — APPROVED** [review]

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
bors cancel

**Comment by abhinav** [comment]
slightly broken; vt10x library needs an update for Windows.

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
🤦 

I need to skip pty.Open on Windows on the second test too.

```
=== FAIL: cmd/pulumi TestStateUpgradeProjectNameWidget_noStacks (0.00s)
    state_upgrade_test.go:296: 
        	Error Trace:	C:/a/pulumi/pulumi/pkg/cmd/pulumi/state_upgrade_test.go:296
        	Error:      	Received unexpected error:
        	            	unsupported
        	Test:       	TestStateUpgradeProjectNameWidget_noStacks
        	Messages:   	creating pseudo-terminal

=== FAIL: cmd/pulumi TestStateUpgradeProjectNameWidget_noStacks (re-run 1) (0.00s)
    state_upgrade_test.go:296: 
        	Error Trace:	C:/a/pulumi/pulumi/pkg/cmd/pulumi/state_upgrade_test.go:296
        	Error:      	Received unexpected error:
        	            	unsupported
        	Test:       	TestStateUpgradeProjectNameWidget_noStacks
        	Messages:   	creating pseudo-terminal

```

**Comment by abhinav** [comment]
bors try

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
setup node timed out: image

bors retry
