### PR TITLE
Display policy severity for violations

### LINKED ISSUE #20718: Surface severity in the policy output in the CLI
We should update the CLI so that it outputs the severity of the policy violation that has failed in the display in the terminal. This will be helpful information for Neo and for users.

### PR DESCRIPTION
**Pull request by justinvp**
This change updates the CLI display for policy violations to include the severity, if one was specified for a policy. Policies are sorted by enforcement level (mandatory, advisory) and severity (critical, high, medium, low, unspecified).

You can get a sense for what it looks like from the test output:

```
<{%fg 13%}><{%bold%}>Policies:<{%reset%}>
    ❌ <{%fg 5%}>analyzerA@v1.0.0<{%reset%}>
        - <{%fg 1%}>[mandatory: critical]  always-fails-critical<{%reset%}>  (pkgA:m:typA: resA)
          <{%reset%}>a policy failed<{%reset%}>
        - <{%fg 1%}>[mandatory: high]  always-fails-high<{%reset%}>  (pkgA:m:typA: resA)
          <{%reset%}>a policy failed<{%reset%}>
        - <{%fg 1%}>[mandatory: medium]  always-fails-medium<{%reset%}>  (pkgA:m:typA: resA)
          <{%reset%}>a policy failed<{%reset%}>
        - <{%fg 1%}>[mandatory: low]  always-fails-low<{%reset%}>  (pkgA:m:typA: resA)
          <{%reset%}>a policy failed<{%reset%}>
        - <{%fg 1%}>[mandatory]  always-fails-unspecified<{%reset%}>  (pkgA:m:typA: resA)
          <{%reset%}>a policy failed<{%reset%}>
        - <{%fg 3%}>[advisory: critical]  always-fails-advisory-critical<{%reset%}>  (pkgA:m:typA: resA)
          <{%reset%}>a policy failed<{%reset%}>
        - <{%fg 3%}>[advisory: high]  always-fails-advisory-high<{%reset%}>  (pkgA:m:typA: resA)
          <{%reset%}>a policy failed<{%reset%}>
        - <{%fg 3%}>[advisory: medium]  always-fails-advisory-medium<{%reset%}>  (pkgA:m:typA: resA)
          <{%reset%}>a policy failed<{%reset%}>
        - <{%fg 3%}>[advisory: low]  always-fails-advisory-low<{%reset%}>  (pkgA:m:typA: resA)
          <{%reset%}>a policy failed<{%reset%}>
        - <{%fg 3%}>[advisory]  always-fails-advisory-unspecified<{%reset%}>  (pkgA:m:typA: resA)
          <{%reset%}>a policy failed<{%reset%}>
```

When a severity is specified, it will now be included in the brackets containing the enforcement level, e.g. `[mandatory: high]`, otherwise it'll remain the same as before `[mandatory]`.

We may want to tweak the UX here subsequently, possibly using different colors for `critical`, `high`, `medium`, and `low`, but I've left the current coloring for `mandatory` vs. `advisory` for now.

Fixes #20718

### CODE REVIEW

File: sdk/go/common/resource/plugin/analyzer.go [hunk 1]
```diff
@@ -113,6 +113,7 @@ type AnalyzeDiagnostic struct {
 	Message           string
 	EnforcementLevel  apitype.EnforcementLevel
 	URN               resource.URN
+	Severity          apitype.PolicySeverity
```
Comment (Frassle) [inline sdk/go/common/resource/plugin/analyzer.go]: Feels a bit off that this doesn't match the wire format. Might be worth at least calling that out in a comment, but maybe would be cleaner to do the policy name to severity matching in the display layer itself?

Comment (justinvp) [reply sdk/go/common/resource/plugin/analyzer.go]: I can leave a comment.

The problem with doing it in the display layer is we don't have the info to do the mapping. We could add a new event that contains that info, but I'd prefer not to do that.

I first implemented this by doing the mapping in the step generator when generating the event to emit. We have the info there and can create the event using the info plus diagnostics results from Analyze/AnalyzeStack. But it didn't feel as clean, as I had to update a few places in the step generator to get the mapping and a few files related to emitting the event to accept a severity arg so it can be included in the event. For this PR, I decided to switch it around and just have the Analyzer plugin implementation handle it, and include it in the diagnostic, even though it's not in the wire format.

Comment (fallimic) [reply sdk/go/common/resource/plugin/analyzer.go]: Could we add to the wire format as well? Is there a reason not to? I was looking at allowing a policy to dynamically override certain fields, and it works, but severity was notably absent.

Comment (justinvp) [reply sdk/go/common/resource/plugin/analyzer.go]: @Frassle, FWIW, this was how I originally did it: https://github.com/pulumi/pulumi/compare/master...justin/policy-severity-original. We could switch to something like that, if it's more preferable.

@fallimic, we could add it to the wire format, but that will require policy SDK changes, and it'd be duplicating the severity over the wire for each violation when it was already returned from `GetAnalyzerInfo` (though, probably not a huge deal as we're duplicating a couple other fields in the violations, like enforcement level, pack name, version). How are you dynamically overriding certain fields? Right now we have severity associated with the policy itself, not with particular violations reported from that policy. (I guess you're manually implementing the gRPC protocol?)

**Comment by justinvp** [comment]
If we want to support dynamically changing the severity of reported violations, we can add it to the wire format. It would require a pu/pu release with protobuf changes, then a policy SDK release that passes it along the wire. The policy SDKs don't have a way to specify the severity when reporting a violation. If we wanted to support that in the SDKs, we'd have to expose a way to do it. The service UI would also need to be updated to support the dynamic value in the list of violations, as right now the severity is associated with the policy from the metadata when the policy pack was published.

File: sdk/go/common/resource/plugin/analyzer.go (hunk 1 above)
Comment (fallimic) [reply sdk/go/common/resource/plugin/analyzer.go]: Nothing, concrete yet, but I was experimenting with updating the SDK to allow overriding the fields that are already part of the AnalyzeDiagnostic message. We wouldn't need to necessarily send Severity every time, but allow it to be passed.

I was experimenting essentially with extending reportViolation like so
```typescript
reportViolation(
  message: string,
  urn?: string,
  policyOverride?: {
    title?: string;                    // Override violation title
    description?: string;              // Override violation description
    enforcementLevel?: "advisory" | "mandatory" | "disabled";  // Override enforcement level
  }
): void;
