### PR TITLE
[sdk/nodejs] Fix regression when passing a provider to a MLC

### LINKED ISSUE #11316: Upgrading sdk form 3.43.1 to 3.46.1 throws eror
### What happened?

Automated testing against upgrading from 3.43.1 -> 3.46.1 thru the following error:
```
[stdout]          stderr: error: Running program '/tmp/binding-directory2497179436' failed with an unhandled exception:
[stdout]          Error: failed to register new resource example--s3-adv-log-bucket [example:aws/s3:S3Bucket]: 2 UNKNOWN: plugins that can construct components must support secrets
[stdout]              at Object.registerResource (/tmp/binding-directory2497179436/node_modules/@pulumi/runtime/resource.ts:293:27)
[stdout]              at new Resource (/tmp/binding-directory2497179436/node_modules/@pulumi/resource.ts:402:13)
[stdout]              at new ComponentResource (/tmp/binding-directory2497179436/node_modules/@pulumi/resource.ts:895:9)
[stdout]              at new S3Bucket (/tmp/binding-directory2497179436/node_modules/@example/aws/s3/S3Bucket.ts:99:9)
[stdout]              at /tmp/binding-directory2497179436/src/index.ts:70:31
[stdout]              at Generator.next (<anonymous>)
[stdout]              at fulfilled (/tmp/binding-directory2497179436/src/index.ts:5:58)
[stdout]              at processTicksAndRejections (node:internal/process/task_queues:96:5)
[stdout]          error: Running program '/tmp/binding-directory2497179436' failed with an unhandled exception:
[stdout]          Error: failed to register new resource example--s3-simple-bucket [example:aws/s3:S3Bucket]: 2 UNKNOWN: plugins that can construct components must support secrets
[stdout]              at Object.registerResource (/tmp/binding-directory2497179436/node_modules/@pulumi/runtime/resource.ts:293:27)
[stdout]              at new Resource (/tmp/binding-directory2497179436/node_modules/@pulumi/resource.ts:402:13)
[stdout]              at new ComponentResource (/tmp/binding-directory2497179436/node_modules/@pulumi/resource.ts:895:9)
[stdout]              at new S3Bucket (/tmp/binding-directory2497179436/node_modules/@example/aws/s3/S3Bucket.ts:99:9)
[stdout]              at /tmp/binding-directory2497179436/src/index.ts:49:26
[stdout]              at Generator.next (<anonymous>)
[stdout]              at fulfilled (/tmp/binding-directory2497179436/src/index.ts:5:58)
[stdout]              at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to reproduce

1. Using the existing test infrastructure upgrade from 3.43.1 to 3.46.1
2. Only raises an issue in typescript, not python or go. 

### Expected Behavior

1. error not to be thrown

### Actual Behavior

1. Error thrown. 

### Output of `pulumi about`

_No response_

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
#11093 changed the Node.js SDK to pass a provider specified in a MLC's `ResourceOptions.provider` to the engine.

Unfortunately, this regresses behavior that existing programs rely on. For example:

```ts
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const myRegion = new aws.Provider("us-east-1", {
  region: "us-east-1",
});

const vpc = new awsx.ec2.Vpc("awsx-nodejs-default-args", {}, { provider: myRegion });
```

In the above program, an explicit _aws_ provider is being passed to the _aws**x**_ `VPC` component, with the intention that the _aws_ provider will be used as the provider for all of `Vpc`'s children.

With the change in #11093, the engine would try to call `Construct` for the `Vpc` using the specified `aws` provider, which does not work (it fails with `plugins that can construct components must support secrets`).

This change reverts the problematic change from #11093 and adds a regression test to lock-in the previous behavior.

Note: We do want to be able to support specifying a MLC's provider (to allow explicit providers for MLCs), but we'll address that in a separate change. (I'll open an issue).

Fixes #11316

### CODE REVIEW

File: pkg/resource/deploy/source_eval.go [hunk 1]
```diff
@@ -1190,10 +1190,6 @@ func (rm *resmon) RegisterResource(ctx context.Context,
 	var outputDeps map[string]*pulumirpc.RegisterResourceResponse_PropertyDependencies
 	if remote {
 		provider, ok := rm.providers.GetProvider(providerRef)
-		if providers.IsDenyDefaultsProvider(providerRef) {
-			msg := diag.GetDefaultProviderDenied(resource.URN(t.String())).Message
-			return nil, fmt.Errorf(msg, t.Package().String(), t.String())
-		}
```
Comment (iwahbe) [inline pkg/resource/deploy/source_eval.go:1196]: This doesn't need to be reverted. It only functions to make an inscrutable error message coherent.

**Review by iwahbe — APPROVED** [review]
Instead of reverting the whole PR, let's just revert the part that causes the problem.

**Comment by justinvp** [comment]
bors merge

**Comment by justinvp** [comment]
bors retry
