### PR TITLE
Accept `*` as an index in property paths

### LINKED ISSUE #8197: ReplaceOnChanges - strconv.ParseInt
I'm trying to use ReplaceOnChanges for an AKS cluster to replace when the availabilityZones change. I'm doing this right now:
```
                ReplaceOnChanges =
                {
                    "agentPoolProfiles[*].availabilityZones"
                }
```

I get the error:
error: invalid array index: strconv.ParseInt: parsing "*": invalid syntax

Shouldn't I be able to use the * syntax in an array? I'm having to do this as a workaround currently:

```
  ReplaceOnChanges =
                {
                    "agentPoolProfiles[0].availabilityZones",
                    "agentPoolProfiles[1].availabilityZones"
                }
```

### PR DESCRIPTION
**Pull request by iwahbe**
# Description
`PropertyPaths` are used as path descriptors with wildcards (`*`). Users
know they can use `root["*"]` to wildcard on any entry in a map. Because
strings and numbers can both be used to index (map vs array), our users
expect to be able to use `root[*]` as a wildcard for an array. We should
parse `[*]` so wildcards work as expected. Internally, this will be
syntactic sugar for `["*"]`, but with much less user confusion.

Fixes #8197
See also: https://github.com/pulumi/pulumi-hugo/issues/908
## Checklist

- [X] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: sdk/go/common/resource/properties_path_test.go [hunk 1]
```diff
@@ -144,6 +144,30 @@ func TestPropertyPath(t *testing.T) {
 		})
 	}
 
+	simpleCases := []struct {
+		path   string
+		parsed PropertyPath
+	}{
+		{
+			`root["*"].field[1]`,
```
Comment (Frassle) [inline sdk/go/common/resource/properties_path_test.go:152]: Feel there should be a `root[*].field[1]` test as well given that's what this is adding support for

Comment (iwahbe) [reply sdk/go/common/resource/properties_path_test.go:152]: @pgavlin Which tests would you like to see added to `TestPropertyPathContains`? `TestPropertyPathContains` takes as input a `PropertyPath`. Since `foo[*].bar` and `foo["*"].bar` both parse into the same property path `PropertyPath{"foo", "*", "bar"}`, I don't think that my change introduces any new surface area for the `Contains` method.

Comment (pgavlin) [reply sdk/go/common/resource/properties_path_test.go:152]: > `TestPropertyPathContains` takes as input a `PropertyPath`

Ah, so it does--I did not read the setup for that test closely enough. Nevermind, then!

**Review by pgavlin — APPROVED** [review]
