### PR TITLE
sdk/workspace/DownloadToFile: Fix multiplied and off-by-one retries

### LINKED ISSUE #12456: sdk/workspace: DownloadToFile multiplies retries
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

`workspace.DownloadToFile` attempts to download with retries:

https://github.com/pulumi/pulumi/blob/638c35aa4503615f585a8939694e466af06a7683/sdk/go/common/workspace/plugins.go#L1130-L1132
However,
`DownloadToFile` [calls](https://github.com/pulumi/pulumi/blob/638c35aa4503615f585a8939694e466af06a7683/sdk/go/common/workspace/plugins.go#L1089) [PluginSpec.Download](https://github.com/pulumi/pulumi/blob/638c35aa4503615f585a8939694e466af06a7683/sdk/go/common/workspace/plugins.go#L910)
which calls [source.Download](https://github.com/pulumi/pulumi/blob/638c35aa4503615f585a8939694e466af06a7683/sdk/go/common/workspace/plugins.go#L936) with [getHTTPResponse](https://github.com/pulumi/pulumi/blob/638c35aa4503615f585a8939694e466af06a7683/sdk/go/common/workspace/plugins.go#L955)
which also downloads with retries:

https://github.com/pulumi/pulumi/blob/638c35aa4503615f585a8939694e466af06a7683/sdk/go/common/workspace/plugins.go#L955-L961

This results in a lot more retries than we want.

Discovered while reviewing #12441

### PR DESCRIPTION
**Pull request by abhinav**
**The commits in this PR are meant to be reviewed individually.**

---

This PR fixes two issues in the workspace.DownloadToFile retry logic:

- an off-by-one error that caused it to make 6 attempts, not 5
- a double-retry bug downstream, that caused 5 times as many requests
  as intended

The net effect of this was that we made 30 attempts to download plugins
instead of the intended 5.

The fix required some amount of refactoring,
and is therefore split into N different commits.

In order, the commits are:

- Add a failing test case that verifies the total number of requests
  as well as correct reporting to the `retry` callback
  that is used to report progress to users.
- Refactor without changing any logic
  so that we can redefine `time.After` later.
- Fix double retry bug.
  This brings the number of attempts down from 30 to 6.
- Fix off-by-one bug by re-using util/retry's retryer.

Resolves #12456

### CODE REVIEW

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12504** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/12504" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi/12504?utm_source=stack-comment).

File: sdk/go/common/workspace/plugins.go [hunk 1]
```diff
@@ -967,6 +968,29 @@ func getHTTPResponse(req *http.Request) (io.ReadCloser, int64, error) {
...
+
+	if resp.StatusCode < 200 || resp.StatusCode > 299 {
+		contract.IgnoreClose(resp.Body)
+		return nil, -1, newDownloadError(resp.StatusCode, req.URL, resp.Header)
+	}
+
+	return resp.Body, resp.ContentLength, nil
+}
+
+func getHTTPResponseWithRetry(req *http.Request) (io.ReadCloser, int64, error) {
```
Comment (Frassle) [inline sdk/go/common/workspace/plugins.go:988]: Can we kill this and just use our retry logic in getLatest instead? `DoWithRetry` doesn't give us any way to hook to tell the user that we are retrying.

Comment (abhinav) [reply sdk/go/common/workspace/plugins.go:988]: Could you clarify? Are you suggesting independent retry logic in GetLatestVersion or in its call sites?
GetLatestVersion probably shouldn't do reporting directly--unless we pass an output stream to it.

**Review by Frassle — APPROVED** [review]

**Comment by abhinav** [comment]
bors merge
