### PR TITLE
Fix dependency graphing in the presence of deleted resources

### LINKED ISSUE #19114: Snapshot Integrity Error with `--continue-on-error`
### What happened?

This happened in a Automation API project running within an AWS Lambda.  Our code is still under active development but the lambda generally works.  The most recent change at this time revolved around setting the priorities of ALB Listener Rules. 

### Example

```
2025-04-03T16:17:41.142Z [INFO] 2025-04-03T16:17:41.142Z acf688c4-fb17-4051-ad2e-f84debf9a5b7 Running for mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon...
2025-04-03T16:17:41.142Z [INFO] 2025-04-03T16:17:41.142Z acf688c4-fb17-4051-ad2e-f84debf9a5b7 initializing stack...organization/model_services/mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon
2025-04-03T16:17:42.185Z warning: A new version of Pulumi is available. To upgrade from version '3.157.0' to '3.160.0', visit https://pulumi.com/docs/install/ for manual instructions and release notes.

2025-04-03T16:17:42.473Z [INFO] 2025-04-03T16:17:42.473Z acf688c4-fb17-4051-ad2e-f84debf9a5b7 <pulumi.automation._project_settings.ProjectSettings object at 0x7f0bc516b140>
2025-04-03T16:17:42.473Z [INFO] 2025-04-03T16:17:42.473Z acf688c4-fb17-4051-ad2e-f84debf9a5b7 successfully initialized stack
2025-04-03T16:17:42.473Z [INFO] 2025-04-03T16:17:42.473Z acf688c4-fb17-4051-ad2e-f84debf9a5b7 installing plugins...
2025-04-03T16:17:48.887Z [INFO] 2025-04-03T16:17:48.887Z acf688c4-fb17-4051-ad2e-f84debf9a5b7 plugins installed
2025-04-03T16:17:48.887Z [INFO] 2025-04-03T16:17:48.887Z acf688c4-fb17-4051-ad2e-f84debf9a5b7 setting up config
2025-04-03T16:17:49.160Z [INFO] 2025-04-03T16:17:49.160Z acf688c4-fb17-4051-ad2e-f84debf9a5b7 config set
2025-04-03T16:17:49.160Z [INFO] 2025-04-03T16:17:49.160Z acf688c4-fb17-4051-ad2e-f84debf9a5b7 refreshing stack...

2025-04-03T16:17:49.537Z [WARNING] 2025-04-03T16:17:49.537Z acf688c4-fb17-4051-ad2e-f84debf9a5b7 LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
	
2025-04-03T16:17:49.537Z [ERROR] CommandError:
2025-04-03T16:17:49.537Z code: 255
2025-04-03T16:17:49.537Z stdout:
2025-04-03T16:17:49.537Z stderr: error: The Pulumi CLI encountered a snapshot integrity error. This is a bug!
2025-04-03T16:17:49.537Z You can try to repair your snapshot as follows:
2025-04-03T16:17:49.537Z * Using the `pulumi state repair` command. This is the recommended approach.
2025-04-03T16:17:49.537Z    Run `pulumi state repair --help` for more information.
2025-04-03T16:17:49.537Z * Passing the `--disable-integrity-checking` flag. This will disable integrity
2025-04-03T16:17:49.537Z    checking on many Pulumi commands. This is riskier, but may allow you to
2025-04-03T16:17:49.537Z    execute fine-grained repairs using e.g. `pulumi state delete`.
2025-04-03T16:17:49.537Z ================================================================================
2025-04-03T16:17:49.537Z We would appreciate a report: https://github.com/pulumi/pulumi/issues/
2025-04-03T16:17:49.537Z Please provide all of the text below in your report.
2025-04-03T16:17:49.537Z
================================================================================
2025-04-03T16:17:49.537Z Go Version: go1.24.1
2025-04-03T16:17:49.537Z Go Compiler: gc
2025-04-03T16:17:49.537Z Architecture: amd64
2025-04-03T16:17:49.537Z Operating System: linux
2025-04-03T16:17:49.537Z Write Version: v3.157.0
2025-04-03T16:17:49.537Z Write Command: pulumi up --yes --skip-preview --parallel 16 --logflow --logtostderr --suppress-progress --continue-on-error --client=127.0.0.1:39173 --exec-kind auto.inline --event-log /tmp/automation-logs-up-sgc1asn7/eventlog.txt --stack organization/model_services/mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon --non-interactive
	
2025-04-03T16:17:49.537Z Write Error:       resource urn:pulumi:mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon::model_services::aws:ecs/service:Service::mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon refers to unknown provider urn:pulumi:mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon::model_services::pulumi:providers:aws::default_6_72_0::168e770f-37c5-4f1c-853d-a4d0ceec6887
Write Error: resource urn:pulumi:mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon::model_services::aws:ecs/service:Service::mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon refers to unknown provider urn:pulumi:mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon::model_services::pulumi:providers:aws::default_6_72_0::168e770f-37c5-4f1c-853d-a4d0ceec6887
	
2025-04-03T16:17:49.537Z Read Version: v3.157.0
2025-04-03T16:17:49.537Z Read Command: pulumi refresh --yes --skip-preview --exec-kind auto.inline --stack organization/model_services/mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon --non-interactive
	
2025-04-03T16:17:49.537Z Read Error: getting snapshot: snapshot integrity failure; refusing to use it: resource urn:pulumi:mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon::model_services::aws:ecs/service:Service::mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon refers to unknown provider urn:pulumi:mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon::model_services::pulumi:providers:aws::default_6_72_0::168e770f-37c5-4f1c-853d-a4d0ceec6887
	
2025-04-03T16:17:49.537Z Stack Trace:
2025-04-03T16:17:49.537Z goroutine 1 [running]:
2025-04-03T16:17:49.537Z runtime/debug.Stack()
2025-04-03T16:17:49.537Z runtime/debug/stack.go:26 +0x5e
2025-04-03T16:17:49.537Z github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x2cde81f?, 0xc00231f198?}, {0xc00231f178?, 0xa2?, 0x40?})
2025-04-03T16:17:49.537Z github.com/pulumi/pulumi/pkg/v3/resource/deploy/snapshot.go:617 +0x34
2025-04-03T16:17:49.537Z github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0xc000875b80)
2025-04-03T16:17:49.537Z github.com/pulumi/pulumi/pkg/v3/resource/deploy/snapshot.go:458 +0x53d
2025-04-03T16:17:49.537Z github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).getSnapshot(0xc001fda000, {0x340a460, 0x4b212a0}, {0x33e6b20, 0x4b212a0}, 0xc002258a80)
2025-04-03T16:17:49.537Z github.com/pulumi/pulumi/pkg/v3/backend/diy/state.go:158 +0x125
2025-04-03T16:17:49.537Z github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Snapshot(0xc00248f128, {0x340a460, 0x4b212a0}, {0x33e6b20, 0x4b212a0})
2025-04-03T16:17:49.537Z github.com/pulumi/pulumi/pkg/v3/backend/diy/stack.go:62 +0x85
2025-04-03T16:17:49.537Z github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/operations.NewRefreshCmd.func1(0xc001f66f08, {0xc001f3f650, 0x0, 0x2c15ab7?})
2025-04-03T16:17:49.537Z github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/operations/refresh.go:246 +0x10c2
2025-04-03T16:17:49.537Z github.com/spf13/cobra.(*Command).execute(0xc001f66f08, {0xc001f3f5e0, 0x7, 0x7})
2025-04-03T16:17:49.537Z github.com/spf13/cobra@v1.8.0/command.go:983 +0xaaa
2025-04-03T16:17:49.537Z github.com/spf13/cobra.(*Command).ExecuteC(0xc001f4a008)
2025-04-03T16:17:49.537Z github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
2025-04-03T16:17:49.537Z github.com/spf13/cobra.(*Command).Execute(...)
2025-04-03T16:17:49.537Z github.com/spf13/cobra@v1.8.0/command.go:1039
2025-04-03T16:17:49.537Z main.main()
2025-04-03T16:17:49.537Z github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/main.go:62 +0x5e
2025-04-03T16:17:49.537Z Traceback (most recent call last):   File "/pulumi/projects/lambda_function.py", line 126, in lambda_handler     stack.refresh(on_output=print)   File "/usr/local/lib/python3.12/site-packages/pulumi/automation/_stack.py", line 587, in refresh     refresh_result = self._run_pulumi_cmd_sync(args, on_output)   File "/usr/local/lib/python3.12/site-packages/pulumi/automation/_stack.py", line 1027, in _run_pulumi_cmd_sync     result = self.workspace.pulumi_command.run(   File "/usr/local/lib/python3.12/site-packages/pulumi/automation/_cmd.py", line 236, in run     raise create_command_error(result)
	
2025-04-03T16:17:49.539Z END RequestId: acf688c4-fb17-4051-ad2e-f84debf9a5b7 
```

### Output of `pulumi about`

Here's the text with only completely empty lines removed, but preserving the newlines between content:

```
================================================================================

Go Version: go1.24.1

Go Compiler: gc

Architecture: amd64

Operating System: linux

Write Version: v3.157.0

Write Command: pulumi up --yes --skip-preview --parallel 16 --logflow --logtostderr --suppress-progress --continue-on-error --client=127.0.0.1:39173 --exec-kind auto.inline --event-log /tmp/automation-logs-up-sgc1asn7/eventlog.txt --stack organization/model_services/mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon --non-interactive

Write Error:       resource urn:pulumi:mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon::model_services::aws:ecs/service:Service::mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon refers to unknown provider urn:pulumi:mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon::model_services::pulumi:providers:aws::default_6_72_0::168e770f-37c5-4f1c-853d-a4d0ceec6887
Write Error: resource urn:pulumi:mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon::model_services::aws:ecs/service:Service::mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon refers to unknown provider urn:pulumi:mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon::model_services::pulumi:providers:aws::default_6_72_0::168e770f-37c5-4f1c-853d-a4d0ceec6887

Read Version: v3.157.0

Read Command: pulumi refresh --yes --skip-preview --exec-kind auto.inline --stack organization/model_services/mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon --non-interactive

Read Error: getting snapshot: snapshot integrity failure; refusing to use it: resource urn:pulumi:mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon::model_services::aws:ecs/service:Service::mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon refers to unknown provider urn:pulumi:mdl-2udl2Mg1R3JOMNduEmwPL2Jf6BV-swinging-baboon::model_services::pulumi:providers:aws::default_6_72_0::168e770f-37c5-4f1c-853d-a4d0ceec6887

Stack Trace:

goroutine 1 [running]:

runtime/debug.Stack()

runtime/debug/stack.go:26 +0x5e

github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x2cde81f?, 0xc00231f198?}, {0xc00231f178?, 0xa2?, 0x40?})

github.com/pulumi/pulumi/pkg/v3/resource/deploy/snapshot.go:617 +0x34

github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0xc000875b80)

github.com/pulumi/pulumi/pkg/v3/resource/deploy/snapshot.go:458 +0x53d

github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).getSnapshot(0xc001fda000, {0x340a460, 0x4b212a0}, {0x33e6b20, 0x4b212a0}, 0xc002258a80)

github.com/pulumi/pulumi/pkg/v3/backend/diy/state.go:158 +0x125

github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Snapshot(0xc00248f128, {0x340a460, 0x4b212a0}, {0x33e6b20, 0x4b212a0})

github.com/pulumi/pulumi/pkg/v3/backend/diy/stack.go:62 +0x85

github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/operations.NewRefreshCmd.func1(0xc001f66f08, {0xc001f3f650, 0x0, 0x2c15ab7?})

github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/operations/refresh.go:246 +0x10c2

github.com/spf13/cobra.(*Command).execute(0xc001f66f08, {0xc001f3f5e0, 0x7, 0x7})

github.com/spf13/cobra@v1.8.0/command.go:983 +0xaaa

github.com/spf13/cobra.(*Command).ExecuteC(0xc001f4a008)

github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff

github.com/spf13/cobra.(*Command).Execute(...)

github.com/spf13/cobra@v1.8.0/command.go:1039

main.main()

github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/main.go:62 +0x5e

Traceback (most recent call last):   File "/pulumi/projects/lambda_function.py", line 126, in lambda_handler     stack.refresh(on_output=print)   File "/usr/local/lib/python3.12/site-packages/pulumi/automation/_stack.py", line 587, in refresh     refresh_result = self._run_pulumi_cmd_sync(args, on_output)   File "/usr/local/lib/python3.12/site-packages/pulumi/automation/_stack.py", line 1027, in _run_pulumi_cmd_sync     result = self.workspace.pulumi_command.run(   File "/usr/local/lib/python3.12/site-packages/pulumi/automation/_cmd.py", line 236, in run     raise create_command_error(result)
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by lunaris**
When deleting resources as part of an operation, we must start at the ends of the dependency graph and proceed inwards. That is, if a resource `B` depends on a resource `A`, we must delete `B` *first*, lest we have an intermediate state where there is a dangling reference from a remaining `B` to a now-deleted `A`. Computing these deletion orders is done by building a `DependencyGraph` and calling its `TransitiveDependenciesOf` method. Under the hood, `TransitiveDependenciesOf` works by building a lookup table that maps from URNs in a snapshot to resource states, before walking the snapshot to build a set of dependencies. This works fine, until we encounter a snapshot where URNs are (contrary to their name) *not* enough to uniquely identify resources!

Consider the following snapshot, with simplified URNs for readability:

```
[
  {
    "urn": "A"
  },
  {
    "urn": "B",
    "dependencies": ["A"]
  },
  {
    "urn": "A",
    "delete": true
  }
]
```

The URN `A` appears twice, but this is allowed -- the second has `"delete": true`, which indicates it is a resource which has been deleted but not cleaned up from the snapshot. This can happen during e.g. a create-before-replace operation, where a new `A` is created before the old one is deleted. In such operations, the old `A` is marked `"delete": true` so that the new one can be added, before being cleaned up later on. If that clean-up fails, the presence of the deleted resource means that Pulumi can sort it as part of a future (hopefully successful) operation. To re-iterate -- this is fine, and snapshot integrity checks permit any number of deleted copies of a resource.

Unfortunately, `TransitiveDependenciesOf` does not budget for this possibilty, and prior to this change will build an *incorrect* set of dependencies in which `B` above would be reported as depending on the *deleted* `A`. This plays havoc with deletions later on, especially in the presence of `--continue-on-error` or `protect`, which permit an operation to continue despite failures early on. When this happens, we need to cancel deletions on resources which are depended on by things that we failed to delete. This only works if our dependency graphs are correct -- if not, we end up permitting deletions on e.g. the new `A` above, meaning we end up with a snapshot where `B` has a dangling reference.

This change fixes `TransitiveDependenciesOf` to track old (`"delete": true`) and new resources separately, as we do elsewhere in the codebase (e.g. when topologically sorting snapshots). This is not perfect since as mentioned, there could be multiple deleted copies of a resource, but in the absence of actually unique identifiers for resources in a snapshot, it's the best we can do. This fix addresses what we suspect is the cause of snapshot integrity issues when using `--continue-on-error`.

> [!TIP]
>
> Found with fuzzing

Fixes #19114

### CODE REVIEW

File: pkg/engine/lifecycletest/protect_test.go [hunk 1]
```diff
@@ -173,3 +175,156 @@ func TestProtectInheritance(t *testing.T) {
...
+	p := &lt.TestPlan{
+		Project: "test-project",
+		Stack:   "test-stack",
+	}
+	project := p.GetProject()
+
+	// Set up the initial snapshot. We want to end up with the following starting state:
+	//
+	// * A
+	// * B, which depends on A through a DeletedWith dependency, and has Protect: true
```
Comment (Frassle) [inline pkg/engine/lifecycletest/protect_test.go:196]: Can we not use DeletedWith. I think you've found another bug here with destroy deleting B when it knows its going to delete A as well and so should skip the B delete.

**Review by Frassle — APPROVED** [review]
