### PR TITLE
Revert change in targeted update behavior.

### LINKED ISSUE #12964: --target breaks stack by deleting default inputs
It should be possible to reproduce this bug on any stack with the following command:
```
pulumi preview --show-sames --target='x'
```

With Pulumi v3.67.1 it shows many entries with `[diff: -__defaults]` and some more fields that would be deleted.

Applying this update (with a proper --target) succeeds, but it leaves the stack in a broken state. For example subsequent updates try to set `name` fields to values with new random suffixes, thus wanting to replace a lot of resources.

### PR DESCRIPTION
**Pull request by dixler**
Fixes #12964

This commit uses an untargeted resource's old inputs directly and does
not send the untargeted resource's inputs to the provider for
alterations in `provider.Check()`.

This commit fixes a bug in behavior where `provider.Check()` was
no longer be called on untargeted resources. `provider.Check()` would
alter the engine's inputs for use in resource.Goals and skipping this
would cause `__defaults` to not be configured properly in same steps by
`provider.Check()` and cause replaces in some cases.

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/resource/deploy/step_generator.go [hunk 1]
```diff
@@ -634,7 +634,7 @@ func (sg *stepGenerator) generateSteps(event RegisterResourceEvent) ([]Step, res
 
 	// Ensure the provider is okay with this resource and fetch the inputs to pass to subsequent methods.
 	var err error
-	if isTargeted && prov != nil {
+	if prov != nil {
```
Comment (dixler) [inline pkg/resource/deploy/step_generator.go:637]: This will bring the code closer to the original state it was in.

File: pkg/engine/lifecycletest/target_test.go [hunk 2]
```diff
@@ -1016,3 +1016,87 @@ func TestTargetedCreateDefaultProvider(t *testing.T) {
...
+	finalSnap, res := TestOp(Update).Run(project, p.GetTarget(t, origSnap), UpdateOptions{
+		Host: host,
+		UpdateTargets: deploy.NewUrnTargets([]string{
+			"urn:pulumi:test::test::pkgA:m:typA::resA",
+		}),
+	}, false, p.BackendClient, nil)
+	assert.Nil(t, res)
+
+	// Check that `resB` (untargeted) is the same between the two snapshots.
+	func() {
```
Comment (abhinav) [inline pkg/engine/lifecycletest/target_test.go:1083]: nit: Why the closure?

File: pkg/engine/lifecycletest/target_test.go [hunk 3]
```diff
@@ -1016,3 +1016,87 @@ func TestTargetedCreateDefaultProvider(t *testing.T) {
...
+		var initialState resource.State
+		for _, res := range origSnap.Resources {
+			if res.URN == "urn:pulumi:test::test::pkgA:m:typA::resB" {
+				initialState = *res
+			}
+		}
+		assert.NotNil(t, initialState, "initial `resB` state not found")
```
Comment (abhinav) [inline pkg/engine/lifecycletest/target_test.go:1090]: This will always be true. `initialState` is a value, not a pointer.
You can drop the deref above and store the pointer.

```go
var initialState *resource.State
for ... {
  // ...
  initialState = res
}
```

File: pkg/engine/lifecycletest/target_test.go [hunk 4]
```diff
@@ -1016,3 +1016,87 @@ func TestTargetedCreateDefaultProvider(t *testing.T) {
...
+	assert.Nil(t, res)
+
+	// Check that `resB` (untargeted) is the same between the two snapshots.
+	func() {
+		var initialState resource.State
+		for _, res := range origSnap.Resources {
+			if res.URN == "urn:pulumi:test::test::pkgA:m:typA::resB" {
+				initialState = *res
+			}
+		}
```
Comment (abhinav) [inline pkg/engine/lifecycletest/target_test.go:1089]: optional: both these snippets could be simpler with an obvious-ish helper function:

```go
// Returns the resource with the matching URN, or nil.
func findResourceByURN(rs []*resource.State, urn URN) *resource.State {
  for _, r := range rs  {
    if r.URN == urn { return r }
  }
  return nil
}
```

File: pkg/engine/lifecycletest/target_test.go [hunk 5]
```diff
@@ -1016,3 +1016,87 @@ func TestTargetedCreateDefaultProvider(t *testing.T) {
...
+		assert.NotNil(t, initialState, "initial `resB` state not found")
+
+		var finalState resource.State
+		for _, res := range finalSnap.Resources {
+			if res.URN == "urn:pulumi:test::test::pkgA:m:typA::resB" {
+				finalState = *res
+			}
+		}
+		assert.NotNil(t, initialState, "final `resB` state not found")
```
Comment (abhinav) [inline pkg/engine/lifecycletest/target_test.go:1098]: Did you mean for this to be finalState?
Also, again, this will always be true because `finalState` is a struct, not a pointer.

File: pkg/engine/lifecycletest/target_test.go (hunk 2 above)
Comment (dixler) [reply pkg/engine/lifecycletest/target_test.go:1083]: It's hard to see how parts of all of this flat test code are structured from experience and I find that using a scope of some sort is helpful and I had feedback last time that creating scopes was less desirable.

File: pkg/engine/lifecycletest/target_test.go [hunk 6]
```diff
@@ -1016,3 +1016,97 @@ func TestTargetedCreateDefaultProvider(t *testing.T) {
...
+
+		res = findResourceByURN(finalSnap.Resources, "urn:pulumi:test::test::pkgA:m:typA::resB")
+		assert.NotNil(t, res, "final `resB` state not found")
+
+		var finalState resource.State
+		if res != nil {
+			finalState = *res
+		}
+
+		assert.Equal(t, initialState, finalState)
```
Comment (abhinav) [inline pkg/engine/lifecycletest/target_test.go:1110]: Why deref `*res` at all? assert.Equal does a deep equal. it will dereference the pointers.

```suggestion
		initialState := findResourceByURN(origSnap.Resources, "urn:pulumi:test::test::pkgA:m:typA::resB")
		assert.NotNil(t, res, "initial `resB` state not found")

		finalState := findResourceByURN(finalSnap.Resources, "urn:pulumi:test::test::pkgA:m:typA::resB")
		assert.NotNil(t, res, "final `resB` state not found")

		assert.Equal(t, initialState, finalState)
```

**Review by abhinav — APPROVED** [review]
LGTM minus minor comments.

Please get another person to also review before landing.

**Comment by dixler** [comment]
bors merge

**Comment by dixler** [comment]
bors cancel

**Comment by dixler** [comment]
bors merge

**Comment by justinvp** [comment]
Python automation API tests timed out. Gonna try again.

**Comment by justinvp** [comment]
bors retry
