### PR TITLE
Revert change to use `t.TempDir` in testing environment

### LINKED ISSUE #19010: Flaky test: TempDir RemoveAll cleanup: [...] The process cannot access the file because it is being used by another process
Test flake on Windows:

https://github.com/pulumi/pulumi/actions/runs/14042855676/job/39317279602?pr=19009#step:41:212

```
=== FAIL: . TestLanguageImportSmoke/python (23.95s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokepython2071463712\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestLanguageImportSmokepython2071463712/001
    environment.go:205: Running command pulumi new python --yes
    environment.go:205: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestLanguageImportSmokepython2071463712\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokepython2071463712\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokepython2071463712\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestLanguageImportSmoke/java (22.31s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokejava3269083010\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestLanguageImportSmokejava3269083010/001
    environment.go:205: Running command pulumi new java --yes
    environment.go:205: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestLanguageImportSmokejava3269083010\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokejava3269083010\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokejava3269083010\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestLanguageImportSmoke/go (12.14s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokego1417502556\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestLanguageImportSmokego1417502556/001
    environment.go:205: Running command pulumi new go --yes
    environment.go:205: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestLanguageImportSmokego1417502556\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokego1417502556\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokego1417502556\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestLanguageImportSmoke/yaml (5.60s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokeyaml2636839738\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestLanguageImportSmokeyaml2636839738/001
    environment.go:205: Running command pulumi new yaml --yes
    environment.go:205: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestLanguageImportSmokeyaml2636839738\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokeyaml2636839738\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokeyaml2636839738\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestLanguageImportSmoke/nodejs (38.33s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokenodejs3670192228\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestLanguageImportSmokenodejs3670192228/001
    environment.go:205: Running command pulumi new typescript --yes
    environment.go:205: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestLanguageImportSmokenodejs3670192228\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokenodejs3670192228\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokenodejs3670192228\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestLanguageImportSmoke/dotnet (15.84s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokedotnet669506834\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestLanguageImportSmokedotnet669506834/001
    environment.go:205: Running command pulumi new csharp --yes
    environment.go:205: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestLanguageImportSmokedotnet669506834\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokedotnet669506834\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokedotnet669506834\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestLanguageImportSmoke (118.17s)

=== FAIL: . TestImportVersionSmoke (10.95s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestImportVersionSmoke665381590\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestImportVersionSmoke665381590/001
    environment.go:205: Running command pulumi new D:\a\pulumi\pulumi\tests\testdata\random_go --yes
    environment.go:205: Running command pulumi plugin install resource random 4.16.7
    environment.go:205: Running command pulumi plugin install resource random 4.13.0
    environment.go:205: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
    environment.go:205: Running command pulumi stack export
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestImportVersionSmoke665381590\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestImportVersionSmoke665381590\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestImportVersionSmoke665381590\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestImportParameterizedSmoke (44.51s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestImportParameterizedSmoke4206137889\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestImportParameterizedSmoke4206137889/001
    environment.go:205: Running command pulumi new D:\a\pulumi\pulumi\tests\testdata\random_python --yes
    environment.go:205: Running command pulumi plugin install resource terraform-provider 0.3.1
    environment.go:205: Running command pulumi package add terraform-provider hashicorp/random 3.6.3
    environment.go:205: Running command pulumi install
    environment.go:205: Running command pulumi up --yes
    environment.go:205: Running command pulumi import --yes random:index/id:Id identifier p-9hUg
    environment.go:205: Running command pulumi stack export
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestImportParameterizedSmoke4206137889\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestImportParameterizedSmoke4206137889\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestImportParameterizedSmoke4206137889\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestImportParameterizedSmokeFreshState (37.14s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestImportParameterizedSmokeFreshState875474990\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestImportParameterizedSmokeFreshState875474990/001
    environment.go:205: Running command pulumi new D:\a\pulumi\pulumi\tests\testdata\random_python --yes
    environment.go:205: Running command pulumi plugin install resource terraform-provider 0.3.1
    environment.go:205: Running command pulumi package add terraform-provider hashicorp/random 3.6.3
    environment.go:205: Running command pulumi install
    environment.go:205: Running command pulumi import --yes random:index/id:Id identifier p-9hUg
    environment.go:205: Running command pulumi stack export
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestImportParameterizedSmokeFreshState875474990\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestImportParameterizedSmokeFreshState875474990\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestImportParameterizedSmokeFreshState875474990\001\project: The process cannot access the file because it is being used by another process.
```

### PR DESCRIPTION
**Pull request by justinvp**
We're seeing failures in CI on Windows when Go tries to delete the temp dir. Revert back to the previous implementation that uses `os.MkdirTemp`. On Windows, if there's an error deleting the temp dir, it will be logged, but won't cause a failure. This also allows us to keep the environment if the test fails (via `DeleteIfNotFailed`).

Fixes #19010

### CODE REVIEW

File: sdk/go/common/testing/environment.go [hunk 1]
```diff
@@ -76,11 +76,15 @@ func WriteYarnRCForTest(root string) error {
...
-	root := t.TempDir()
+	//nolint:usetesting // We control the lifecycle of the environment.
+	root, err := os.MkdirTemp("", "test-env")
+	assert.NoError(t, err, "creating temp directory")
 	assert.NoError(t, WriteYarnRCForTest(root), "writing .yarnrc file")
 
 	// We always use a clean PULUMI_HOME for each environment to avoid any potential conflicts with plugins or config.
-	home := t.TempDir()
+	//nolint:usetesting // We control the lifecycle of the environment.
+	home, err := os.MkdirTemp("", "test-env-home")
```
Comment (justinvp) [inline sdk/go/common/testing/environment.go:86]: One thing I noticed while here: Should we be cleaning up this directory? This was originally introduced in https://github.com/pulumi/pulumi/pull/15559, but we don't delete it in `DeleteEnvironment`.

Comment (Frassle) [reply sdk/go/common/testing/environment.go:86]: Yeh we should be

Comment (justinvp) [reply sdk/go/common/testing/environment.go:87]: Added a commit that does this

File: sdk/go/common/testing/environment.go [hunk 2]
```diff
@@ -119,26 +120,29 @@ func (e *Environment) ImportDirectory(path string) {
...
+			// as unused. This causes otherwise passing tests to fail.
+			// So ignore errors during cleanup.
+			e.Logf("error cleaning up test directory %q: %v", path, err)
+		}
 	}
 }
 
-// DeleteEnvironment deletes the environment's RootPath, and everything
-// underneath it. It tolerates failing to delete the environment.
+// DeleteEnvironment deletes the environment's HomePath and RootPath, and everything
```
Comment (Frassle) [inline sdk/go/common/testing/environment.go:136]: Why do we even have this? The normal Delete environment is tolerant anyway

**Review by Frassle — APPROVED** [review]

File: sdk/go/common/testing/environment.go (hunk 2 above)
Comment (justinvp) [reply sdk/go/common/testing/environment.go:136]: https://github.com/pulumi/pulumi/pull/19025
