### PR TITLE
Recover from zero-byte `credentials.json` files

### LINKED ISSUE #11017: Ctrl-c leaves 0 byte `credentials.json` which pulumi chokes on.
### What happened?

Started an update of the `pulumi/home/infrastructure/build-metrics` stack with stale AWS session creds. Ctrl-C'ed when I realized it was hung in preview trying to do a read that would eventually time out.

Somehow my `~/.pulumi/credentials.json` file got nuked in the process.

All further runs of `pulumi update` and `pulumi login` printed the following:
```
error: could not get cloud url: failed to read Pulumi credentials file. Please re-run `pulumi login` to reset your credentials file: unexpected end of JSON input
```

Checked `credentials.json` and it was 0 bytes in size.

Deleting `credentials.json` un-wedged it and allowed `pulumi login` to work.

### Steps to reproduce

Obviously this might be a fun one to fully repro.

`cat /dev/null > ~/.pulumi/credentials.json` will test pulumi's handling of 0'ed creds files.

### Expected Behavior

Obviously,

1. pulumi should handle Ctrl-C more gracefully in a way that doesn't nuke the creds file.
2. pulumi should recover more gracefully from a borked creds file. `pulumi login` should be enough to fix this state.

### Actual Behavior

pulumi does neither of those things.

### Output of `pulumi about`

```
CLI
Version      3.42.0
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     4.7.0
docker  3.0.0
nodejs  unknown

Host
OS       darwin
Version  12.6
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v18.10.0'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/kmosher
User           kmosher
Organizations  kmosher, pulumi

Dependencies:
NAME                        VERSION
@octokit/plugin-throttling  3.5.0
@pulumi/aws                 4.7.0
@pulumi/awsx                0.30.0
@pulumi/pulumi              3.4.0
@slack/webhook              5.0.3
octokit                     1.1.0
@types/node                 10.17.44
```

### Additional context

This is on macOS 12.6, M1 (arm64), with the default `apfs` filesystem.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by lunaris**
Pulumi stores credentials in a `credentials.json`. If a non-atomic operation that writes this file is interrupted, we may end up with a zero-byte `credentials.json` file. Presently, this will create a situation where the user has to manually remove the file before e.g. `pulumi login` will work and retrieve new credentials again (see #11017 for an example). This commit changes this behaviour, spotting empty credentials files and returning an empty set of credentials instead of throwing an error.

Fixes #11017

### CODE REVIEW

File: sdk/go/common/workspace/creds.go [hunk 1]
```diff
@@ -166,6 +166,23 @@ func GetStoredCredentials() (Credentials, error) {
...
+			return Credentials{}, nil
+		}
+		return Credentials{}, fmt.Errorf("reading '%s': %w", credsFile, err)
+	}
+
+	if stat.Size() == 0 {
+		return Credentials{}, nil
+	}
+
+	// The file isn't empty -- we'll try to read and deserialize its contents.
```
Comment (Frassle) [inline sdk/go/common/workspace/creds.go:185]: Why stat instead of just seeing if `len(c) == 0` below?

Comment (lunaris) [reply sdk/go/common/workspace/creds.go]: God I'm an idiot. Much better; thanks :facepalm:

**Review by Frassle — APPROVED** [review]
