### PR TITLE
[sdk/go] Implement getResource in the mock monitor

### LINKED ISSUE #5832: Deserializing some resources in 2.14 is failing
As with #5705, I'm seeing these error messages when referring to one resource from another.

> Unable to deserialize resource urn:pulumi:stack::project::myproj:aws:MyComponentResource$aws:iam/role:Role::myObjName, no module is registered for iam/role.
and
>Unable to deserialize resource urn:pulumi:stack::project::aws:cloudwatch:EventRuleEventSubscription$aws:lambda/function:Function::myObjName, no module is registered for lambda/function.

And these exceptions are being thrown.
```
unhandled rejection: CONTEXT(35242): monitor.registerResource(resource:resource-id[aws:iam/rolePolicyAttachment:RolePolicyAttachment])-initial
STACK_TRACE:
Error
    at Object.debuggablePromise (/pulumi/projects/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
    at runAsyncResourceOp (/pulumi/projects/node_modules/@pulumi/pulumi/runtime/resource.js:546:75)
    at Object.<anonymous> (/pulumi/projects/node_modules/@pulumi/pulumi/runtime/resource.js:169:9)
    at Generator.next (<anonymous>)
    at /pulumi/projects/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/pulumi/projects/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
    at /pulumi/projects/node_modules/@pulumi/pulumi/runtime/resource.js:132:63
unhandled rejection: CONTEXT(35260): monitor.registerResource(resource:ObjectUnderTest-RDSInstanceSchedule-start[aws:lambda/permission:Permission])-initial
STACK_TRACE:
Error
    at Object.debuggablePromise (/pulumi/projects/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
    at runAsyncResourceOp (/pulumi/projects/node_modules/@pulumi/pulumi/runtime/resource.js:546:75)
    at Object.<anonymous> (/pulumi/projects/node_modules/@pulumi/pulumi/runtime/resource.js:169:9)
    at Generator.next (<anonymous>)
    at /pulumi/projects/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/pulumi/projects/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
    at /pulumi/projects/node_modules/@pulumi/pulumi/runtime/resource.js:132:63
```

The problem goes away when I downgrade Pulumi to 2.12.1 and Pulumi/AWS to 3.12.2. The Pulumi CLI is as 2.14.0 throughout.

## Expected Behavior
RolePolicyAttachments should be able to refer to Roles via the `role` input. EventRuleSubscriptions should be able to refer to EventRules via the `handler` input.

## Current Behavior
The above error messages are displayed and the tests abort with the above exception.

## Steps to Reproduce
Refer to a Role from a RolePolicyAttachment:
```
    const role = new aws.iam.Role(name, {
      assumeRolePolicy: assumeRolePolicy.json
    });
    new aws.iam.RolePolicyAttachment(name, {
      role: role,
      policyArn: aws.iam.ManagedPolicy.AmazonSSMManagedInstanceCore
    });
```

It also happens when referring to an EventHandler from an EventHandlerSubscription.

```
    const handler = async (
      _: cloudwatch.EventRuleEvent,
    ) => {
      console.log("Stuff happens");
    };

    const subscription = new cloudwatch.EventRuleEventSubscription(name, rule, handler, {}, {});
```

## Context (Environment)
 It doesn't happen during a `pulumi preview` or `pulumi up`. It does prevent Mocha tests from completing.

### PR DESCRIPTION
**Pull request by justinvp**
Part of #5832
Related to https://github.com/pulumi/pulumi/pull/5914
Related to https://github.com/pulumi/pulumi/pull/5919
Related to https://github.com/pulumi/pulumi/pull/5921

### CODE REVIEW

File: sdk/go/pulumi/run_test.go [hunk 1]
```diff
@@ -238,3 +240,125 @@ func TestInvoke(t *testing.T) {
...
+}
+
+type testInstanceResourceInput interface {
+	Input
+
+	ToTestInstanceResourceOutput() testInstanceResourceOutput
+	ToTestInstanceResourceOutputWithContext(ctx context.Context) testInstanceResourceOutput
+}
+
+func (testInstanceResource) ElementType() reflect.Type {
```
Comment (lblackstone) [inline sdk/go/pulumi/run_test.go:265]: I think these will need to be pointer receivers. Related: https://github.com/pulumi/pulumi/pull/5916

Comment (pgavlin) [reply sdk/go/pulumi/run_test.go:265]: +1

**Comment by justinvp** [comment]
@lblackstone, @pgavlin, this is an old PR that had merge conflicts that I finally got around to fixing up. LMK if it looks good. Thanks!

**Review by lblackstone — APPROVED** [review]
