### PR TITLE
Fix malformed resource value bug

### LINKED ISSUE #6158: version 2.18.0 broke everything
Hi 

After upgrade to version 2.18.0 All Pulumi commands stopped working !.  We are completely stuck

## Expected Behavior
Pulumi commands like "up, destroy, preview" should work

## Current Behavior
Most of the Pulumi commands stopped working with this error

error: could not deserialize deployment: malformed resource value: id must be a string

## Steps to Reproduce

1. Have existing state in 2.17.2 .
2. Upgrade to 2.18.0
3. Make a code change
3. Run Pulumi up and apply the change
4. Run Pulumi again and see it fail.

### PR DESCRIPTION
**Pull request by lblackstone**
PR #6125 introduced a bug by marshaling resource
ids as PropertyValues, but not handling that case on
the unmarshaling side. The previous code assumed
that the id was a simple string value. This bug prevents
any stack update operations (preview, update, destroy,
refresh). Since this change was already
released, we must now handle both cases in the
unmarshaling code.

Fix #6158

### CODE REVIEW

File: pkg/resource/stack/deployment.go [hunk 1]
```diff
@@ -570,10 +570,37 @@ func DeserializePropertyValue(v interface{}, dec config.Decrypter,
...
+
+						V, ok := mapV["V"]
+						if !ok {
+							return "", errors.New("malformed resource value: id must be a string")
+						}
+
+						pv := resource.PropertyValue{V: V}
+						if pv.IsNull() {
+							return "", nil
+						}
```
Comment (justinvp) [inline pkg/resource/stack/deployment.go:587]: I'm not sure about this. If we return an empty string for `IsNull()`, the call to `resource.MakeCustomResourceReference(urn, resource.ID(id), packageVersion)` is going to set the id to be a computed value, instead of null.

https://github.com/pulumi/pulumi/blob/8f7dfbb5ae22062f9f10104cd4e155db5ef9172b/sdk/go/common/resource/properties.go#L243-L255

And Null is intended to represent component resources:

https://github.com/pulumi/pulumi/blob/8f7dfbb5ae22062f9f10104cd4e155db5ef9172b/sdk/go/common/resource/properties.go#L99-L113

It's not clear to me yet why you were seeing null for the ID of custom resources in the example state file you showed in Slack.

File: pkg/resource/stack/deployment.go [hunk 2]
```diff
@@ -570,10 +570,37 @@ func DeserializePropertyValue(v interface{}, dec config.Decrypter,
...
+
+						if !pv.IsString() {
```
Comment (justinvp) [inline pkg/resource/stack/deployment.go:589]: We likely also need to handle the case when `pv.IsComputed()`.

**Review by pgavlin — COMMENTED** [review]
Feels like we should fix the marshaling side of this bug as well.

**Comment by pgavlin** [comment]
(also, we should add some regression tests here)

**Comment by pgavlin** [comment]
Just added some changes that fix the marshaling code and refactor the unmarshaling code a bit. Working on tests now.

File: pkg/resource/stack/deployment.go (hunk 1 above)
Comment (lblackstone) [reply pkg/resource/stack/deployment.go]: > It's not clear to me yet why you were seeing null for the ID of custom resources in the example state file you showed in Slack.

It looks like the child resources of the ComponentResource are incorrectly being detected as ComponentResources.

Here are the versions I was using to reproduce this:
```
  <ItemGroup>
    <PackageReference Include="Pulumi" Version="2.17.0" />
    <PackageReference Include="Pulumi.Kubernetes" Version="2.7.0" />
  </ItemGroup>
```
CLI version `v2.18.0`

File: pkg/resource/stack/deployment.go [hunk 3]
```diff
@@ -373,12 +373,16 @@ func SerializePropertyValue(prop resource.PropertyValue, enc config.Encrypter,
 	// We serialize resource references using a map-based representation similar to assets, archives, and secrets.
 	if prop.IsResourceReference() {
 		ref := prop.ResourceReferenceValue()
-		return map[string]interface{}{
+
+		serialized := map[string]interface{}{
 			resource.SigKey:  resource.ResourceReferenceSig,
 			"urn":            ref.URN,
-			"id":             ref.ID,
 			"packageVersion": ref.PackageVersion,
```
Comment (justinvp) [inline pkg/resource/stack/deployment.go:380]: Nit: I noticed we don't include `packageVersion` in the gRPC marshaling if it's an empty string. Should we do the same here?

https://github.com/pulumi/pulumi/blob/036c4205fd7e84abab5711e2d223ea4729520037/sdk/go/common/resource/plugin/rpc.go#L175-L184

**Comment by pgavlin** [comment]
OK, unit tests are in.

**Comment by pgavlin** [comment]
@justinvp @lblackstone I'm going to fold the original "fix resource-ref-as-ID marshaling" changes in with these.

**Comment by pgavlin** [comment]
Okay, this has been rebased on top of HEAD and includes the two other sets of changes that were rolled back.

The changes are now comprised of three commits:
1. A reapplication of the fix for bad resource-ref-as-ID marshaling
2. The fix for the broken serialization and deserialization
3. A reapplication of the Go resource ref unit tests

PTAL @justinvp @lblackstone 
cc @leezen @lukehoban

File: pkg/resource/stack/deployment.go (hunk 3 above)
Comment (pgavlin) [reply pkg/resource/stack/deployment.go:379]: I'd rather leave that as-is for now to avoid touching more code than necessary.

**Comment by lblackstone** [comment]
LGTM

**Review by justinvp — APPROVED** [review]
LGTM
