### PR TITLE
Fix StackReference secrets performance

### LINKED ISSUE #20741: StackReferences not using batch decryption
From https://github.com/pulumi/pulumi/issues/20338#issuecomment-3397077241:

We do not use ESC. In our use case we have a stack with~3000 resources.

secret provider:
```json
"secrets_providers": {
    "type": "service",
    "state": {
        "url": "https://api.pulumi.com",
        ...
    }
}
```

Number of ciphertexts:

```bash
pulumi stack export | grep ciphertext | wc -l
669
```

We use this stack in another project by using `StackReference`.  When running e.g. `pulumi preview` it does a lot of decrypt calls still:

```bash
> pulumi preview --logtostderr --logflow -v=10 2>&1 | grep "Making Pulumi API call" > calls.txt
> wc -l calls.txt
691 calls.txt
> cat calls.txt | grep decrypt | wc -l 
670
```

---

Sounds like two issues with StackReference decryption:

1. We're apparently not using the batch decrypt APIs for stack references
2. Are we decrypting _all_ secrets in the referenced stack's snapshot, rather than only secrets for the stack resource's outputs?

### PR DESCRIPTION
**Pull request by justinvp**
A Pulumi program can use a StackReference to retrieve the stack outputs of another stack. Internally, the engine will fetch the referenced stack's snapshot and unmarshal it into a `Snapshot` object. Then the root stack resource's outputs are extracted from the snapshot and returned to the referencing program.

As part of unmarshaling the snapshot, the engine will decrypt all secrets within the snapshot, even though there may not be any secrets in the root stack resource's outputs.

One limitation is that the referencing stack must be able to decrypt the secrets of the referenced stack. If both stacks are using the same secrets manager (such as is the case with the Pulumi service), everything works fine. If they are not, historically, an error was thrown, stopping execution of the referencing stack.

https://github.com/pulumi/pulumi/pull/19533 addressed this limitation by effectively catching decryption errors when referencing another stack, and inserting dummy values, allowing plaintext values to be shared freely.

Unfortunately, https://github.com/pulumi/pulumi/pull/19533 unintentionally regressed the performance of secrets decryption such that batch decryption was no longer used. This results in significant slowdowns when referencing stacks with many secrets, especially when using the Pulumi service, as each decrypt operation uses an individual network request.

This change addresses the regression and improves the overall performance of StackReference secrets decryption in two ways:

1. The error-catching wrapper used to implement https://github.com/pulumi/pulumi/pull/19533 now supports batch decryption, restoring the previous performance characteristics before that change.

2. Rather than unmarshaling the entire snapshot, and thus needing to decrypt all secrets in the snapshot, we now only unmarshal the root stack resource's outputs. If there are secrets in the snapshot, but no secrets in the stack outputs, there's no decryption to do at all. If there are secrets in the stack outputs, only those secrets need to be decrypted, and they will be batch decrypted with the fix from (1).

In the future, we may consider further optimizations, like Pulumi service changes that pre-decrypt secrets in the snapshot and a new endpoint for only retrieving a stack's outputs (pre-decrypted).

Fixes #20741

### CODE REVIEW

File: pkg/backend/secrets.go [hunk 1]
```diff
@@ -63,6 +64,12 @@ func (p *errorCatchingSecretsProvider) OfType(ty string, state json.RawMessage)
 		onDecryptError:  p.onDecryptError,
 	}
 
+	// If the underlying manager implements BatchingSecretsManager,
+	// wrap our error-catching manager in a batching caching manager.
+	if _, ok := delegateManager.(stack.BatchingSecretsManager); ok {
+		return stack.NewBatchingCachingSecretsManager(manager), nil
+	}
```
Comment (justinvp) [inline pkg/backend/secrets.go:71]: This addresses the regression. Despite the error-catching manager implementing `BatchDecrypt`, it didn't implement the `BatchingSecretsManager` interface, so before this change, [when we'd check if it implements `BatchingSecretsManager`](https://github.com/pulumi/pulumi/blob/363e0e664f8bd212a658acb70b076ebf8ea76118/pkg/resource/stack/deployment.go#L390-L395) during snapshot deserialization, it didn't implement it, so it wouldn't batch decrypt the secrets.

File: pkg/resource/stack/deployment.go [hunk 2]
```diff
@@ -428,11 +443,8 @@ func DeserializeDeploymentV3(
 		ops = append(ops, desop)
 	}
 
-	if completeBatch != nil {
```
Comment (justinvp) [inline pkg/resource/stack/deployment.go:431]: The new `initializeSecretsManagerAndDecrypter` now always returns a non-nil `completeBatch` function, so no need to check for nil anymore.

File: pkg/backend/httpstate/stack.go [hunk 3]
```diff
@@ -230,6 +234,22 @@ func (s *cloudStack) Snapshot(ctx context.Context, secretsProvider secrets.Provi
...
+		return *v, nil
+	}
+
+	outputs, err := s.b.getSnapshotStackOutputs(ctx, secretsProvider, s.ref)
+	if err != nil {
+		return nil, err
+	}
+
+	s.snapshotStackOutputs.Store(&outputs)
+	return outputs, nil
```
Comment (pgavlin) [inline pkg/backend/httpstate/stack.go]: if two calls to this method race, they could return inconsistent results. is that acceptable? or should we use `CompareAndSwap(nil, &outputs)`? e.g.

```go
s.snapshotStackOutputs.CompareAndSwap(nil, &outputs)
return *s.snapshotStackOutputs.Load(), nil
```

File: pkg/cmd/pulumi/stack/stack_output.go [hunk 4]
```diff
@@ -291,10 +292,15 @@ func getStackOutputs(snap *deploy.Snapshot, showSecrets bool) (map[string]any, e
 		return map[string]any{}, nil
 	}
 
+	return removeSecretsAndMassageSecrets(context.TODO(), state.Outputs, showSecrets)
+}
+
+func removeSecretsAndMassageSecrets(
```
Comment (pgavlin) [inline pkg/cmd/pulumi/stack/stack_output.go]: NFC here? looks like this isn't used anywhere else, right?

**Review by pgavlin — APPROVED** [review]
non-blocking--

wondering if there's an opportunity to simplify and help prevent these sorts of bugs by requiring that all crypters implement batch ops.

File: pkg/cmd/pulumi/stack/stack_output.go (hunk 4 above)
Comment (justinvp) [reply pkg/cmd/pulumi/stack/stack_output.go]: It's used in two places in this file, but since you asked I decided to delete it and inline the implementation in the two places. It's basically just one line anyway.

**Comment by justinvp** [comment]
> wondering if there's an opportunity to simplify and help prevent these sorts of bugs by requiring that all crypters implement batch ops.

Yeah, I had the same thought in the back of my mind. Opened https://github.com/pulumi/pulumi/issues/20911 to consider subsequently.

**Comment by justinvp** [comment]
An unrelated issue is preventing merging: https://github.com/pulumi/pulumi/issues/20912

**Comment by johsjote** [comment]
Thanks! this saves us soooo much time.
