### PR TITLE
Fix the panic on pulumi convert for package without a version

### LINKED ISSUE #9897: `pulumi convert` crashes due to unknown package version
If I try to convert a program that uses the [Pulumi Command](https://www.pulumi.com/registry/packages/command) package:

```
name: yamyam
runtime: yaml
resources:
  echo:
    type: command:local:Command
    properties:
      create: echo ''
```

It crashes:

```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   3.35.0-alpha.1655483272+2a07ed75.dirty
Go Version:       go1.17.4
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x56fa1e0, 0x6d6d9a0})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/pulumi/pulumi/pkg/v3/codegen/python.GenerateProject({0x7ff7bfeff765, 0x4}, {{0xc0003f66f0, 0x18}, {{0x59d22ca, 0x6}, 0x0}, {0x0, 0x0}, 0xc00027da70, ...}, ...)
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/codegen/python/gen_program.go:110 +0x278
main.newConvertCmd.func1(0xf, {0xc000b1cd00, 0xc000761d90, 0x41f0105})
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/convert.go:86 +0x39d
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000768780, {0xc00072d3c0, 0x0, 0x4})
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc000768780, {0xc00072d380, 0x4, 0x4})
	/Users/joeduffy/dev/code/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000b27680)
	/Users/joeduffy/dev/code/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/joeduffy/dev/code/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
```

This is because, for some reason, `p.Version` is `nil` on this line:

https://github.com/pulumi/pulumi/blob/2a07ed754f9320a1761d5a8d94f647303b6ad816/pkg/codegen/python/gen_program.go#L110

### PR DESCRIPTION
**Pull request by mikhailshilkov**
# Description

Fixes pulumi/pulumi-command#85

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/codegen/go/gen_program.go [hunk 1]
```diff
@@ -196,7 +196,10 @@ require (
 		}
 
 		// Relatively safe default, this works for Pulumi provider packages:
-		vPath := fmt.Sprintf("/v%d", p.Version.Major)
+		vPath := ""
+		if p.Version != nil && p.Version.Major > 1 {
```
Comment (mikhailshilkov) [inline pkg/codegen/go/gen_program.go:200]: Note the `p.Version.Major > 1` part which isn't strictly related. But this seems correct?

**Review by AaronFriel — COMMENTED** [review]
I think the condition `p.Version.Major` should be removed, other than that LGTM.

I think since we're using appropriate git tags for all of our releases, and we want people to do the same, `/v0`, `/v1` should work?

**Comment by AaronFriel** [comment]
Hmm, I think I was wrong. https://go.dev/ref/mod#major-version-suffixes

> **Major version suffixes are not allowed at major versions v0 or v1.** There is no need to change the module path between v0 and v1 because v0 versions are unstable and have no compatibility guarantee. Additionally, for most modules, v1 is backwards compatible with the last v0 version; a v1 version acts as a commitment to compatibility, rather than an indication of incompatible changes compared with v0.

Emphasis mine.

**Review by AaronFriel — APPROVED** [review]

**Review by iwahbe — APPROVED** [review]
