### PR TITLE
[codegen/typescript] Call site defaults for plain Pulumi Object types

### LINKED ISSUE #8132: [codegen/nodejs,go] Fail to emit defaults for plain objects
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

The C# and Python SDKs generate helper code to check configured environment variables for Providers. It appears that the Go and TypeScript SDKs both have a bug that prevents this code from being generated on complex Provider types.

### Steps to reproduce

Here's what the schema looks like:

```
"provider": {
    "description": "The provider type for the kubernetes package.",
    "type": "object",
    "inputProperties": {
    ...
        "helmReleaseSettings": {
            "$ref": "#/types/kubernetes:index:HelmReleaseSettings",
            "description": "BETA FEATURE - Options to configure the Helm Release resource."
        },
    ...
},
"types": {
  "kubernetes:index:HelmReleaseSettings": {
      "description": "BETA FEATURE - Options to configure the Helm Release resource.",
      "properties": {
      ...
          "driver": {
              "type": "string",
              "description": "The backend storage driver for Helm. Values are: configmap, secret, memory, sql.",
              "default": "secret",
              "defaultInfo": {
                  "environment": [
                      "PULUMI_K8S_HELM_DRIVER"
                  ]
              }
          },
          "pluginsPath": {
              "type": "string",
              "description": "The path to the helm plugins directory.",
              "defaultInfo": {
                  "environment": [
                      "PULUMI_K8S_HELM_PLUGINS_PATH"
                  ]
              }
          },
      ...
      "type": "object"
  },
},
```

Here's an example of the helpers generated for Python:
```py3
@pulumi.input_type
class HelmReleaseSettingsArgs:
    def __init__(__self__, *,
                 driver: Optional[pulumi.Input[str]] = None,
                 plugins_path: Optional[pulumi.Input[str]] = None,
                 registry_config_path: Optional[pulumi.Input[str]] = None,
                 repository_cache: Optional[pulumi.Input[str]] = None,
                 repository_config_path: Optional[pulumi.Input[str]] = None,
                 suppress_beta_warning: Optional[pulumi.Input[bool]] = None):
        """
        BETA FEATURE - Options to configure the Helm Release resource.
        :param pulumi.Input[str] driver: The backend storage driver for Helm. Values are: configmap, secret, memory, sql.
        :param pulumi.Input[str] plugins_path: The path to the helm plugins directory.
        :param pulumi.Input[str] registry_config_path: The path to the registry config file.
        :param pulumi.Input[str] repository_cache: The path to the file containing cached repository indexes.
        :param pulumi.Input[str] repository_config_path: The path to the file containing repository names and URLs.
        :param pulumi.Input[bool] suppress_beta_warning: While Helm Release provider is in beta, by default 'pulumi up' will log a warning if the resource is used. If present and set to "true", this warning is omitted.
        """
        if driver is None:
            driver = _utilities.get_env('PULUMI_K8S_HELM_DRIVER')
        if driver is not None:
            pulumi.set(__self__, "driver", driver)
        if plugins_path is None:
            plugins_path = _utilities.get_env('PULUMI_K8S_HELM_PLUGINS_PATH')
        if plugins_path is not None:
            pulumi.set(__self__, "plugins_path", plugins_path)
    ...
```

Expected: 

Each SDK should generate helper methods that read the configured environment variable as a default.

Actual: 

Only Python and C# generate helpers for complex types.

### PR DESCRIPTION
**Pull request by iwahbe**
# Description
Apply a default function when a object type is passed as an argument to Resource. 

Partial fix for: #8132

Note: the massive number of files changes is because I needed to change the name of our registration `inputs` to `resourceInputs`. The old name (just `inputs`) conflicted with the `inputs` package. Changes were made to `nodejs/gen.go` and the test added is called `env-helper` (in `codegen/internal/test/testdata`). 

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by t0yv0** [comment]
Taking a rain check here, will review tomorrow.. Sorry..

**Comment by pgavlin** [comment]
@iwahbe it looks like this is dealing with default values for arbitrary object types, not just resources. Is that right?

**Comment by iwahbe** [comment]
> @iwahbe it looks like this is dealing with default values for arbitrary object types, not just resources. Is that right?

We already have default values for resource types. This is just for (plain) object types.

**Comment by pgavlin** [comment]
> This is just for (plain) object types.

Is that something we support for other SDKs?

**Comment by iwahbe** [comment]
> Is that something we support for other SDKs?

We support plain object defaults for Python and C#.

File: pkg/codegen/internal/test/testdata/dashed-import-schema/nodejs/tree/v1/rubberTree.ts [hunk 1]
```diff
@@ -61,16 +61,16 @@ export class RubberTree extends pulumi.CustomResource {
             if ((!args || args.type === undefined) && !opts.urn) {
                 throw new Error("Missing required property 'type'");
             }
-            inputs["container"] = args ? args.container : undefined;
-            inputs["diameter"] = (args ? args.diameter : undefined) ?? 6;
-            inputs["farm"] = (args ? args.farm : undefined) ?? "(unknown)";
-            inputs["size"] = (args ? args.size : undefined) ?? "medium";
-            inputs["type"] = (args ? args.type : undefined) ?? "Burgundy";
+            resourceInputs["container"] = args ? (args.container ? pulumi.output(args.container).apply(inputs.containerArgsProvideDefaults) : undefined) : undefined;
```
Comment (t0yv0) [inline pkg/codegen/internal/test/testdata/dashed-import-schema/nodejs/tree/v1/rubberTree.ts:64]: Can't seem to figure out where `inputs` is coming from in `inputs.containerArgsProvideDefaults` after `let inputs: pulumi.Inputs = {};` is removed.

File: pkg/codegen/internal/test/testdata/dashed-import-schema/nodejs/types/input.ts [hunk 2]
```diff
@@ -4,9 +4,20 @@
...
     material?: pulumi.Input<string>;
     size: pulumi.Input<enums.ContainerSize>;
 }
+/**
+ * containerArgsProvideDefaults sets the appropriate defaults for ContainerArgs
+ */
+export function containerArgsProvideDefaults(val: ContainerArgs): ContainerArgs {
+    return {
+        ...val,
+    brightness: (val.brightness) ?? 1,
```
Comment (t0yv0) [inline pkg/codegen/internal/test/testdata/dashed-import-schema/nodejs/types/input.ts:21]: Indentation off?

File: pkg/codegen/internal/test/testdata/dashed-import-schema/nodejs/tree/v1/rubberTree.ts (hunk 1 above)
Comment (t0yv0) [reply pkg/codegen/internal/test/testdata/dashed-import-schema/nodejs/tree/v1/rubberTree.ts:64]: Ok never mind, `import { input as inputs, output as outputs, enums } from "../../types";`. So previously there was shadowing. Unfortunate.

File: pkg/codegen/internal/test/testdata/env-helper/nodejs/types/input.ts [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+    thinker: pulumi.Input<string>;
+}
+/**
+ * layeredTypeArgsProvideDefaults sets the appropriate defaults for LayeredTypeArgs
+ */
+export function layeredTypeArgsProvideDefaults(val: LayeredTypeArgs): LayeredTypeArgs {
+    return {
+        ...val,
+    answer: (val.answer) ?? 42,
+    other: pulumi.output(val.other).apply(inputs.helmReleaseSettingsArgsProvideDefaults)!,
```
Comment (t0yv0) [inline pkg/codegen/internal/test/testdata/env-helper/nodejs/types/input.ts:91]: What does `!` do is this ignoring a potential null?

File: pkg/codegen/nodejs/gen.go [hunk 4]
```diff
@@ -996,6 +1116,7 @@ func (mod *modContext) genFunction(w io.Writer, fun *schema.Function) {
 	if fun.Inputs != nil {
 		for _, p := range fun.Inputs.Properties {
 			// Pass the argument to the invocation.
+			// TODO: handle const and default values
```
Comment (t0yv0) [inline pkg/codegen/nodejs/gen.go:1119]: TODO[pulumi/pulumi#1234]

File: pkg/codegen/nodejs/gen.go [hunk 5]
```diff
@@ -397,12 +397,14 @@ func printComment(w io.Writer, comment, deprecationMessage, indent string) {
 	fmt.Fprintf(w, "%s */\n", indent)
 }
 
-func (mod *modContext) genPlainType(w io.Writer, name, comment string, properties []*schema.Property, input, readonly bool, level int) {
+func (mod *modContext) genPlainType(w io.Writer, name, comment string,
```
Comment (t0yv0) [inline pkg/codegen/nodejs/gen.go:400]: Would it be possible to factor out the `defaults` generation into a separate func? I'm squinting at this and I don't see how the `defaults` computation and code emission does not interact with the previous func much if at all.

Also.. `genPlainType` had too many bool parameters before the change, but now after the change with `plainType: bool` parameter it does strike me as very odd, if you're doing `genPlainType`, what does `plainType: false` mean now?

**Comment by t0yv0** [comment]
This look good! The way prior codegen code is written it's hard to convince oneself the new procedure is complete.  Looking at downstream codegen checks is definitely helpful to identify some "realistic" compilation failures, why is azure-native failing?

One case I am worried about from just reading the code is nested defaults like `a.b.c`, so `a: A`, `a.b: B`, `a.b.c: C` and now `b.c` property has a default value of type `C`. The code that decides if defaults are needed *is recursive* and recurs into sub-properties, presumably it would decide yes, this situation needs a default function. However I'm not seeing that the default function generation code is recursive, so it probably wouldn't handle it? What would happen, the default simply gets ignored but no other harm done?

File: pkg/codegen/nodejs/gen.go (hunk 5 above)
Comment (iwahbe) [reply pkg/codegen/nodejs/gen.go:400]: I can work on that refactor. I think it would make sense. 

> Also.. genPlainType had too many bool parameters before the change, but now after the change with plainType: bool parameter it does strike me as very odd, if you're doing genPlainType, what does plainType: false mean now?

That's a valid point. We use `genPlainType` to generate argument types as well, so this was the "its really just a plain type" flag. I will see if I can think up a better name and will document what it does.

**Comment by iwahbe** [comment]
>why is azure-native failing?

I don't know why azure native is failing. That is my next area to investigate for this project. 

> One case I am worried about from just reading the code is nested defaults like `a.b.c`, so `a: A`, `a.b: B`, `a.b.c: C` and now `b.c` property has a default value of type `C`. The code that decides if defaults are needed _is recursive_ and recurs into sub-properties, presumably it would decide yes, this situation needs a default function. However I'm not seeing that the default function generation code is recursive, so it probably wouldn't handle it? What would happen, the default simply gets ignored but no other harm done?

Nested defaults shouldn't be a problem. If we have 
```typescript
export interface A { b: B }
export interface B { c: string }
```
Where `B.c` has default value `"default"`. If `A` were passed to a resource, codegen would recurse on `A`, then `B` and find that `B` needs a default to be instantiated. It would thus call
```typescript
constructor(args: SomeResourceArgs, opts: ...) {
    // Assuming typeof("a") == A and ignoring null and input checks
    resourceInputs["a"] = aProvideDefaults(args.a)
}
// -- snip -- types/inputs.ts
function aProvideDefaults(val: A): A {
    return { ...val, b: val.b ? bProvideDefaults(val.b) : undefined }
}

function bProvideDefaults(val: B): B {
    return { ...val, c: (val.c) ?? "default" }
}
```
The call nodejs call stack handles the recursion for us (and this works even if `A` has a field of type `A`). We only need the recursion in codegen to determine we need to call `aProvideDefaults`.

File: pkg/codegen/internal/test/testdata/env-helper/nodejs/types/input.ts (hunk 3 above)
Comment (iwahbe) [reply pkg/codegen/internal/test/testdata/env-helper/nodejs/types/input.ts]: It would  never be null (only applied to inputs that are not nullable). The typescript type systems apparently knows this. I experimented with removing the `!` and tests passed. I think I can remove the `!`.

**Comment by t0yv0** [comment]
Ping me again to review everything once you get past CI breakage - it's looking good.

```
Error:     helpers.go:153: moduletest/_index.md did not agree
    --- FAIL: TestGeneratePackage/env-helper (0.05s)
```

File: pkg/codegen/docs/gen.go [hunk 6]
```diff
@@ -1957,8 +1957,14 @@ func (dctx *docGenContext) generatePackage(tool string, pkg *schema.Package) (ma
 
 	glog.V(3).Infoln("generating package docs now...")
 	files := fs{}
-	for _, mod := range dctx.modules() {
-		if err := mod.gen(files); err != nil {
+	modules := []string{}
```
Comment (t0yv0) [inline pkg/codegen/docs/gen.go:1960]: Oof nice find. Anything else using dctx.modules() like this?

**Review by t0yv0 — APPROVED** [review]
LGTM

File: pkg/codegen/docs/gen.go (hunk 6 above)
Comment (iwahbe) [reply pkg/codegen/docs/gen.go:1960]: This is the only one
