### PR TITLE
fix uncatchable `Resource monitor is terminating`

### LINKED ISSUE #12970: Error: 14 UNAVAILABLE: No connection established while deploying a stack
### What happened?

Hi,

I was trying to deploy a k8s deployment which had a volume who's link to a k8s secret. The volume configuration that I provided was empty which caused the stack.up() to fail (expected). But, the error Error: 14 UNAVAILABLE: No connection established occur on top of the one returned by the stack.up() function and I'm unable to catch this error. 

The second error seems to be thrown within a async call which make it uncatchable.

### Expected Behavior

Only one error should be thrown, the one that details the stack deployment.
Or at least, the second error should be catchable.

### Steps to reproduce

Run the following stack deployment.

```
const auto = require("@pulumi/pulumi/automation");
const k8s = require("@pulumi/kubernetes");

const args = process.argv.slice(2);
let destroy = false;
if (args.length > 0 && args[0]) {
    destroy = args[0] === "destroy";
}

const run = async () => {
    // This is our pulumi program in "inline function" form
    const pulumiProgram = async () => {
        // Creating k8s deployment
        const deployment =  new k8s.apps.v1.Deployment(
            'helloworld-deployment',
            {
                spec: {
                    replicas: 1,
                    selector: {
                        matchLabels: {
                            app: "helloworld",
                        },
                    },
                    template: {
                        spec: {
                            restartPolicy: "Always",
                            containers: [
                                {
                                    name: 'mycontainer',
                                    image: "nginx"
                                },
                            ],
                            volumes: [
                            {
                                name: "myvolume",
                                secret: {
                                    secretName: "",
                                },
                            },
                            ],
                        },
                    },
                },
            }
        );

        return {
            deploymentId: deployment.id
        }
    };

    // Create our stack 
    const args = {
        stackName: "dev",
        projectName: "inlineNode",
        program: pulumiProgram
    };

    // create (or select if one already exists) a stack that uses our inline program
    const stack = await auto.LocalWorkspace.createOrSelectStack(args);

    console.info("successfully initialized stack");
    console.info("config set");
    console.info("refreshing stack...");
    await stack.refresh({ onOutput: console.info });
    console.info("refresh complete");

    if (destroy) {
        console.info("destroying stack...");
        await stack.destroy({ onOutput: console.info });
        console.info("stack destroy complete");
        process.exit(0);
    }

    console.info("updating stack...");
    const upRes = await stack.up({ onOutput: console.info });
    console.info(`update summary: \n${JSON.stringify(upRes.summary.resourceChanges, null, 4)}`);
};

run().catch(err => console.log(err));
```

The catch block will be able to catch the deployment failure error but shouldn't be able to catch this error.
```
<ref *1> Error: 14 UNAVAILABLE: No connection established
    at callErrorFromStatus (/home/root/repo/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/home/root/repo/node_modules/@grpc/grpc-js/src/client.ts:356:55)
    at Object.onReceiveStatus (/home/root/repo/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)
    at Object.onReceiveStatus (/home/root/repo/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
    at /home/root/repo/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/home/root/repo/node_modules/@grpc/grpc-js/src/client.ts:326:30)
    at ServiceClientImpl.registerResourceOutputs (/home/root/repo/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at /home/root/repo/node_modules/@pulumi/runtime/resource.ts:847:34
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/root/repo/node_modules/@pulumi/runtime/resource.ts:846:37)
    at Generator.next (<anonymous>)
    at fulfilled (/home/root/repo/node_modules/@pulumi/pulumi/runtime/resource.js:18:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  promise: Promise {
    <rejected> [Circular *1],
    [Symbol(async_id_symbol)]: 2202,
    [Symbol(trigger_async_id_symbol)]: 526,
    [Symbol(kResourceStore)]: LocalStore {
      settings: [Object],
      config: [Object],
      stackResource: [Stack],
      leakCandidates: Set(0) {}
    }
  }
}
```

### Output of `pulumi about`

CLI          
Version      3.57.1
Go Version   go1.20.1
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Backend        
Name           mydesktop
URL            file://~
User           root
Organizations  

### Additional context

This is a major issue, the error make our api crash completly.

Thanks in advance!

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description

Fixes https://github.com/pulumi/pulumi/issues/10744
Fixes #12970

Allows users to catch `Resource monitor is terminating` exceptions from automation API.

When using Node automation API, and `registerResource()` fails due to the resource monitor shutting down, an uncaught rejection is thrown by a `debuggablePromise` and causes the process to exit without allowing users to handle the exception.

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: sdk/nodejs/runtime/resource.ts [hunk 1]
```diff
@@ -209,7 +209,10 @@ export function getResource(
             });
         }),
         label,
-    );
+    ).catch(() => {
+        // Request to the engine is likely due to another failure in the program and another error
```
Comment (Frassle) [inline sdk/nodejs/runtime/resource.ts:213]: Wonder if it make sense to print of stderr or something here?

File: sdk/nodejs/runtime/debuggable.ts [hunk 2]
```diff
@@ -111,7 +111,8 @@ export function debuggablePromise<T>(p: Promise<T>, ctx: any): Promise<T> {
         .catch((err: any) => {
             localStore.leakCandidates.delete(p);
             err.promise = p;
-            throw err;
+            // Print ctx to stderr which indicates the origin of the rejected promise.
+            console.error(`rejection in: ${ctx}`);
```
Comment (Frassle) [inline sdk/nodejs/runtime/debuggable.ts:115]: Feels odd to push this all the way to debuggable promise? We use debuggablePromise is a lot of other places. I'd think it's only in the resource RPC calls (where we don't have any final await for the promise) that this needs to console.errror.

Comment (dixler) [reply sdk/nodejs/runtime/debuggable.ts:115]: Yeah. Some integration tests are failing. Will take a look into making `throwlessDebuggablePromise` (name subject to change) and replace usages of it in `runtime/resource.ts` tomorrow.

File: sdk/nodejs/runtime/resource.ts (hunk 1 above)
Comment (dixler) [reply sdk/nodejs/runtime/resource.ts]: I added logging, but it looks awkward so I removed it. You can catch and print the exception yourself now.

recording of the experience with `console.error()`:
https://asciinema.org/a/IqkuoVgu97biyiSpdfcef2vVe

File: sdk/nodejs/runtime/resource.ts [hunk 3]
```diff
@@ -1090,3 +1090,14 @@ function runAsyncResourceOp(label: string, callback: () => Promise<void>, serial
         }
     }
 }
+
+/**
+ * safeDebuggablePromise creates a debuggablePromise and catches its errors to prevent an unhandled rejection from
+ * causing node to exit.
+ * @internal
+ */
+export function safeDebuggablePromise<T>(p: Promise<T>, ctx: any): Promise<T> {
```
[the remark this answers is not in the document]
Comment (dixler) [reply sdk/nodejs/runtime/resource.ts:1099]: After some discussion, we will add a `console.error` statement and have a more tactical fix on individual debuggablePromises.

File: sdk/nodejs/runtime/rpc.ts [hunk 4]
```diff
@@ -70,6 +70,10 @@ export function transferProperties(onto: Resource, label: string, props: Inputs)
 
         resolvers[k] = (v: any, isKnown: boolean, isSecret: boolean, deps: Resource[] = [], err?: Error) => {
             if (err) {
+                if (isGrpcError(err)) {
+                    console.error("info: skipped rejection in transferProperties");
+                    return;
+                }
```
Comment (dixler) [inline sdk/nodejs/runtime/rpc.ts:76]: This gets really noisy.

Comment (dixler) [reply sdk/nodejs/runtime/rpc.ts:76]: https://asciinema.org/a/jbEXbO1XYRVD1u8cCNwZzHT3A

Comment (abhinav) [reply sdk/nodejs/runtime/rpc.ts:76]: That's annoying. Is there a way to track that we've already printed this warning? 

Or record all these failures in a list outside the loop (with the name of each property maybe?),
and emit a single log statement from the resolver function for the last item in the list.
Roughly (pseudo-code-ish):

```typescript
var skipped = [];
const keys = Object.keys(...);
for (const idx, k of keys) {
  // ...
  resolvers[k] = (...) => {
    if (err) {
      if (isGrpcError(err)) {
        skipped.push(k)
      } else {
        // reject all
      }
    } else {
      // resolve all
    }
    
    if (idx == keys.length-1 && skipped.length > 0) {
      const joined = skipped.join(", ")
      console.error("skipped rejection for: ${joined}");
  }
}
```

Comment (dixler) [reply sdk/nodejs/runtime/rpc.ts]: Fixed https://asciinema.org/a/WA21ruTPrMibuVw9p3Ag0yrv9

File: sdk/nodejs/tests/runtime/registrations.spec.ts [hunk 5]
```diff
@@ -81,4 +83,64 @@ describe("runtime", () => {
...
+            });
+            after(() => {
+                process.removeAllListeners("unhandledRejection");
+            });
+            it("transferProperties does not throw", () => {
+                const resolver = runtime.transferProperties({} as Resource, "wew", {
+                    foo: "a",
+                    baz: "b",
+                });
+                //(v: any, isKnown: boolean, isSecret: boolean, deps: Resource[] = [], err?: Error) => {
```
Comment (abhinav) [inline sdk/nodejs/tests/runtime/registrations.spec.ts:101]: leftover comment?

**Review by abhinav — APPROVED** [review]
Seems reasonable

File: sdk/nodejs/tests/runtime/registrations.spec.ts (hunk 5 above)
Comment (dixler) [reply sdk/nodejs/tests/runtime/registrations.spec.ts:101]: oh mb. nice catch :pray:

**Comment by dixler** [comment]
bors merge

File: sdk/nodejs/runtime/resource.ts [hunk 6]
```diff
@@ -593,6 +598,13 @@ async function prepareResource(
 
             resolveURN = (v, err) => {
                 if (err) {
+                    if (isGrpcError(err)) {
+                        if (!shownResolveURNWarning) {
+                            console.error("info: skipped rejection in resolveURN");
```
Comment (justinvp) [inline sdk/nodejs/runtime/resource.ts:603]: What if I don't want these messages written out from my program that uses automation API? How would I stop it?

**Review by justinvp — CHANGES_REQUESTED** [review]

File: sdk/nodejs/runtime/resource.ts (hunk 6 above)
Comment (justinvp) [reply sdk/nodejs/runtime/resource.ts:603]: Naively, I'd assume I could catch any errors and decide if I want to show it or not. Is that not possible?

**Comment by dixler** [comment]
bors cancel

**Comment by dixler** [comment]
uses `PULUMI_DEBUG_PROMISE_LEAKS=1` to trigger the console.errors and removes the flattening of the messages since you asked for it.

https://asciinema.org/a/OfQ3nPxyl1mXeECLNJkldql4a

**Review by justinvp — APPROVED** [review]

**Comment by dixler** [comment]
bors merge

**Comment by abhinav** [comment]
image

looks like a temporary failure on the final prepare step. retrying.

**Comment by abhinav** [comment]
bors cancel

**Comment by abhinav** [comment]
bors merge

**Comment by dixler** [comment]
bors merge

**Comment by justinvp** [comment]
bors retry

**Comment by microsoftly** [comment]
y'all are lifesavers. This bug specifically has been a thorn in my side
