### PR TITLE
Await output properties before closing the context

### LINKED ISSUE #15527: Race condition in component providers that use combinators
### What happened?

I'm developing a component provider using the Go SDK, and I find that the `Construct` RPC occasionally fails:
```
    error: an unhandled error occurred: waiting for RPCs: 
      rpc error: code = Unknown desc = marshaling properties: 
        awaiting input property "resources": attempted illegal RPC after program completion
```
The failure occurs when the component inputs are simple inputs, i.e. aren't based on output from another resource.

See [slack discussion](https://pulumi.slack.com/archives/C9SGX9QA1/p1708622939775999) for more details.

### Example

The provider uses `CopyTo` to make input-like args to be passed into the `All` combinator, then `ApplyT` into an output property. It then returns a `ConstructResult`. 

```go


type ConfigGroupArgs struct {
	Files          pulumi.StringArrayInput `pulumi:"files"`
	ResourcePrefix pulumi.StringInput      `pulumi:"resourcePrefix,optional"`
}

func constructConfigGroup(ctx *pulumi.Context, typ, name string,
		inputs pulumiprovider.ConstructInputs, options pulumi.ResourceOption) (*pulumiprovider.ConstructResult, error) {
    comp := &ConfigGroupState{}
    if err := ctx.RegisterComponentResource(typ, name, comp, options); err != nil { ... }

    args := &ConfigGroupArgs{}
    if err := inputs.CopyTo(args); err != nil { ... }
    
    comp.Resources = pulumi.All(args.Files, args.ResourcePrefix).ApplyTWithContext(ctx.Context(), func(_ context.Context, args []any) (pulumi.Output, error) {
        time.Sleep(5 * time.Second)
        ctx.RegisterResource(...)
    })
    return pulumiprovider.NewConstructResult(comp)
}
```
The failure occurs when the applier func is slow to make the `RegisterResource` RPC call.  Due to an apparent race, the `pulumi.Context` becomes closed before the applier is complete.

### Additional context

The root cause appears to be that the inputs passed into the combinator aren't attached to the context's non-RPC waitgroup. As a result, the applier (which runs in a goroutine) is not awaited by the context's [shutdown logic](https://github.com/pulumi/pulumi/blob/v3.107.0/sdk/go/pulumi/context.go#L221). Also, the framework doesn't explicitly wait for outputs to resolve before shutting down the context; it awaits _after_ the shutdown.

An [earlier PR](https://github.com/pulumi/pulumi/pull/6983) explains why the Pulumi Go SDK assumes that `Outputs` are generally attached to a context:
> Despite these new methods, most Pulumi programs should work without
changes: the bulk of Outputs are created by the SDK itself as part of
resource registration, and for Any and All, we can pick up the
context from any Outputs present in the arguments. The only programs
that should require changes are those that create outputs from whole
cloth using NewOutput, ToOutput, or ToSecret and create unawaited
async work rooted at those outputs.

Should the inputs produced by `CopyTo` be more strictly attached to the context? A given input may or may not be attached depending on program specifics, and when none are attached, the problem is exhibited. However, the original motivation for [having a non-RPC waitgroup](https://github.com/pulumi/pulumi/pull/6983) seems related to program termination involving pure side-effects, which doesn't seem like an issue here because the race is with respect to output properties.

Should the component provider framework explicitly await the output properties before shutting down the context? How else to support a case where there's no args involved:
```go
	comp.Resources = pulumi.All("literal").ApplyTWithContext(...)
```

### Workarounds
I find an effective workaround to be to await the outputs before returning from `Construct`:

```go
    _, _ = internals.UnsafeAwaitOutput(ctx.Context(), comp.Resources)
    return pulumiprovider.NewConstructResult(comp)
```

### Suggested Fix

Here's some specific ideas:
1. Await the outputs more explicitly after construct returns (e.g. [here](https://github.com/pulumi/pulumi/blob/v3.107.0/sdk/go/pulumi/provider.go#L138-L159)), or
2. Provide a "strict" mode for `CopyTo` that always produces attached outputs, and disallows plain arg types, or
3. Provide a `ctx.ToOutput` function to attach an input to the context.
4. Detect the race condition and emit a warning.
5. As a provider author, strictly use `Output` types in your args struct to force `CopyTo` to attach to the context.

### Output of `pulumi about`

```
CLI          
Version      3.107.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  unknown
random      unknown
yaml        unknown

Host     
OS       darwin
Version  13.5.1
Arch     arm64

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by EronWright**
# Description

This PR fixes a race condition between resolving the output properties (from `Construct` or `Call`) and the closing of the context. The solution is to await the output properties before closing the context.

New test cases were added for `Convert` and `Call`, with  `TestConstruct_await/unassociated_output` and `TestCall_await/unassociated_output` being the specific repro cases. Without the fix, the test fails as expected:
```
=== RUN   TestConstruct_await/unassociated_output
    /Users/eronwright/Pulumi/pulumi/sdk/go/pulumi/provider_test.go:2027:
                Error Trace:    /Users/eronwright/Pulumi/pulumi/sdk/go/pulumi/provider_test.go:2027
                Error:          Received unexpected error:
                                marshaling properties: awaiting input property "b": attempted illegal RPC after program completion
                Test:           TestConstruct_await/unassociated_output
                Messages:       failed to construct
--- FAIL: TestConstruct_await/unassociated_output (1.00s)
```

Fixes #15527

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: sdk/go/pulumi/context.go [hunk 1]
```diff
@@ -225,9 +225,24 @@ func (ctx *Context) Close() error {
...
+	for ctx.state.rpcs > 0 {
+		ctx.state.rpcsDone.Wait()
+	}
+}
+
+// close waits for all asynchronous work associated with this context to drain. RPCs may not be queued once close
 // returns.
-func (ctx *Context) wait() error {
+func (ctx *Context) close() error {
 	// Wait for async work to flush.
```
Comment (Frassle) [inline sdk/go/pulumi/context.go:246]: The first part of this method can just be replaced with `ctx.wait()`

File: sdk/go/pulumi/provider.go [hunk 2]
```diff
@@ -141,10 +141,9 @@ func construct(ctx context.Context, req *pulumirpc.ConstructRequest, engineConn
 		return nil, err
 	}
 
-	// Wait for async work to finish.
-	if err = pulumiCtx.wait(); err != nil {
-		return nil, err
-	}
+	// Wait for async work to finish, but don't close the context until after the output properties have resolved.
+	// Note that output properties may or may not be attached to the context's waitgroup.
+	pulumiCtx.wait()
```
Comment (Frassle) [inline sdk/go/pulumi/provider.go:146]: > The first drain is to avoid a potential breaking change.

I'm not sure I follow why we can't just `close` after marshalling all the inputs instead of before?

File: sdk/go/pulumi/context.go (hunk 1 above)
Comment (EronWright) [reply sdk/go/pulumi/context.go:246]: That was my first instinct too but I think it preferrable to acquire the lock once. The alternatives were clunky.

File: sdk/go/pulumi/provider.go (hunk 2 above)
Comment (EronWright) [reply sdk/go/pulumi/provider.go:146]: I felt it safer to drain at least once before marshalling the inputs, in case an existing provider was relying on a side effect to compute an output property. Of course, the property shouldn't resolve too eagerly but the provider might be buggy. If others think that overly cautious, am happy to remove the `wait` function.

Comment (Frassle) [reply sdk/go/pulumi/provider.go:146]: > in case an existing provider was relying on a side effect to compute an output property

Probably not something we should be encouraging. Even if this drain then drain again catches some of those cases it probably won't catch all async'y things. Better to not even try and let these things fail fast probably.

File: sdk/go/pulumi/context.go (hunk 1 above)
Comment (Frassle) [reply sdk/go/pulumi/context.go:246]: Fair

File: sdk/go/pulumi/provider.go (hunk 2 above)
Comment (EronWright) [reply sdk/go/pulumi/provider.go]: I simplified it as you suggested.

**Review by Frassle — APPROVED** [review]
LGTM
