### PR TITLE
Fix 8940 invalid go code generated

### LINKED ISSUE #8940: [programgen] Generates invalid Go code when using % character
When using the following code:

```hcl
resource "argocd_serverDeployment" "kubernetes:apps/v1:Deployment" {
apiVersion = "apps/v1"
kind = "Deployment"
metadata = {
labels = {
"app.kubernetes.io/component" = "server"
"aws:region" = "us-west-2"
"key%percent" = "percent"
"key...ellipse" = "ellipse"
"key{bracket" = "bracket"
"key}bracket" = "bracket"
"key*asterix" = "asterix"
"key?question" = "question"
"key,comma" = "comma"
"key&&and" = "and"
"key||or" = "or"
"key!not" = "not"
"key=>geq" = "geq"
"key==eq" = "equal"
}
name = "argocd-server"
}
}
```

Programgen generates the incorrect Go code - notice the `fmt.Sprintf` wrapped in quotes

```go
package main

import (
"fmt"

"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
appsv1 "github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/apps/v1"
metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/meta/v1"
)
func main() {
pulumi.Run(func(ctx *pulumi.Context) error {
_, err := appsv1.NewDeployment(ctx, "argocd_serverDeployment", &appsv1.DeploymentArgs{
ApiVersion: pulumi.String("apps/v1"),
Kind: pulumi.String("Deployment"),
Metadata: &metav1.ObjectMetaArgs{
Labels: pulumi.StringMap{
"app.kubernetes.io/component": pulumi.String("server"),
"aws:region": pulumi.String("us-west-2"),
"fmt.Sprintf("%v%v%v%v", "key", "%", "%", "percent")": pulumi.String("percent"),
"key...ellipse": pulumi.String("ellipse"),
"key{bracket": pulumi.String("bracket"),
"key}bracket": pulumi.String("bracket"),
"key*asterix": pulumi.String("asterix"),
"key?question": pulumi.String("question"),
"key,comma": pulumi.String("comma"),
"key&&and": pulumi.String("and"),
"key||or": pulumi.String("or"),
"key!not": pulumi.String("not"),
"key=>geq": pulumi.String("geq"),
"key==eq": pulumi.String("equal"),
},
Name: pulumi.String("argocd-server"),
},
})
if err != nil {
return err
}
return nil
})
}
```

### PR DESCRIPTION
**Pull request by t0yv0**
# Description

Fixes #8940 

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/codegen/go/gen_program_expressions.go [hunk 1]
```diff
@@ -986,9 +986,7 @@ func (g *generator) literalKey(x model.Expression) (string, bool) {
 				break
 			}
 		}
-		var buf bytes.Buffer
-		g.GenTemplateExpression(&buf, x)
-		return buf.String(), true
+		return "", false
```
Comment (t0yv0) [inline pkg/codegen/go/gen_program_expressions.go:989]: The result of GenTemplateExpression will never be a literal; it only will be a literal in the case already handled on L984.

File: pkg/codegen/testing/test/testdata/invalid-go-sprintf-pp/go/invalid-go-sprintf.go [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+func main() {
+	pulumi.Run(func(ctx *pulumi.Context) error {
+		_, err := appsv1.NewDeployment(ctx, "argocd_serverDeployment", &appsv1.DeploymentArgs{
+			ApiVersion: pulumi.String("apps/v1"),
+			Kind:       pulumi.String("Deployment"),
+			Metadata: &metav1.ObjectMetaArgs{
+				Labels: pulumi.StringMap{
+					"app.kubernetes.io/component":                pulumi.String("server"),
+					"aws:region":                                 pulumi.String("us-west-2"),
+					fmt.Sprintf("%v%v%v", "key", "%", "percent"): pulumi.String("percent"),
```
Comment (t0yv0) [inline pkg/codegen/testing/test/testdata/invalid-go-sprintf-pp/go/invalid-go-sprintf.go:20]: Used to generate `"fmt.Sprintf("%v%v%v", "key", "%", "percent")"` here

**Review by iwahbe — APPROVED** [review]
Looks good. LGTM
