### PR TITLE
Fix fallback in `defaultErrorMessage` to avoid `RangeError` on large error objects

### LINKED ISSUE #21326: RangeError: Invalid string length in defaultErrorMessage masks actual errors when error objects are large
## Description

When a Pulumi program throws an error with a large or complex error object (common with AWS SDK errors), the `defaultErrorMessage` function in `cmd/run/error.ts` crashes with `RangeError: Invalid string length`, completely hiding the actual error from the user.

The issue is at line 35 in `error.ts`:

```typescript
return util.inspect(err, { colors: true });
```

This call to `util.inspect` can throw `RangeError: Invalid string length` when the error object has:
- A very long stack trace
- Large custom properties (AWS SDK errors include full request/response data)
- Circular references

## Current Behavior

When an error occurs (e.g., missing secret, AWS permission error), instead of seeing the actual error message, users see:

```
RangeError: Invalid string length
    at markNodeModules (node:internal/util/inspect:1613:21)
    at formatError (node:internal/util/inspect:1747:18)
    at formatRaw (node:internal/util/inspect:1090:14)
    at formatValue (node:internal/util/inspect:932:10)
    at Object.inspect (node:internal/util/inspect:409:10)
    at Object.defaultErrorMessage (/path/to/node_modules/@pulumi/pulumi/cmd/run/error.ts:28:21)
    at process.uncaughtHandler (/path/to/node_modules/@pulumi/pulumi/cmd/run/run.ts:347:3)
```

The original error is completely lost.

## Expected Behavior

The actual error message should be displayed, even if the full error object is too large to inspect.

## Root Cause

In `cmd/run/error.ts`, there's inconsistent error handling:

```typescript
// Line 28-35: NO error handling around util.inspect
function defaultErrorMessage(err) {
    if (err?.stack) {
        return util.inspect(err, { colors: true }); // ← CAN THROW, NOT WRAPPED
    }
    // ...
    
    // Lines 44-48: HAS error handling (inconsistent!)
    try {
        return util.inspect(err);
    } catch (error) {
        return `an error occurred while inspecting an error: ${error.message}`;
    }
}
```

The same try/catch pattern already exists at lines 44-48, but is missing at line 35.

## Suggested Fix

Wrap the `util.inspect` call at line 35 in a try/catch, similar to the existing pattern at lines 44-48:

```typescript
function defaultErrorMessage(err) {
    if (err?.stack) {
        try {
            return util.inspect(err, { colors: true });
        } catch (inspectError) {
            // Fall back to just the message/stack if inspect fails
            const msg = typeof err?.message === 'string' ? err.message : undefined;
            const stack = typeof err?.stack === 'string' ? err.stack : undefined;
            return msg || stack || `Error inspection failed: ${inspectError.message}`;
        }
    }
    // ... rest of function
}
```

## Impact

This bug makes debugging extremely difficult because:
1. The actual error is completely hidden
2. Users see a cryptic `RangeError` that has nothing to do with their actual problem
3. Common scenarios like missing secrets, permission errors, or misconfigured resources all trigger this
4. Tools built on Pulumi (like SST) are severely affected

## Workaround

A patch script that wraps the `util.inspect` call in a try/catch:

```javascript
// Patch for @pulumi/pulumi/cmd/run/error.js
const fs = require('fs');
const path = require('path');

const errorFile = path.join(
  __dirname,
  'node_modules/@pulumi/pulumi/cmd/run/error.js'
);

const needle = "return util.inspect(err, { colors: true });";
const replacement = `
try {
    return util.inspect(err, { colors: true });
} catch (inspectError) {
    const max = 20000;
    const truncate = (s) => (typeof s === "string" && s.length > max
        ? s.slice(0, max) + \`\\n... [truncated \${s.length - max} chars]\`
        : s);
    const msg = typeof err?.message === "string" ? err.message : undefined;
    const stack = typeof err?.stack === "string" ? err.stack : undefined;
    return truncate(msg) || truncate(stack) || \`error inspection failed: \${inspectError.message}\`;
}`;

const content = fs.readFileSync(errorFile, 'utf-8');
if (!content.includes('inspectError')) {
  fs.writeFileSync(errorFile, content.replace(needle, replacement));
  console.log('Patched Pulumi error handler');
}
```

## Reproduction Steps

1. Create any Pulumi program that uses AWS SDK v3
2. Trigger an error (e.g., missing credentials, missing secret, permission denied)
3. AWS SDK errors contain large request/response metadata
4. Instead of seeing the actual error, you get `RangeError: Invalid string length`

**Alternative minimal reproduction:**

```typescript
// Force a large error object
const largeError = new Error("Something went wrong");
(largeError as any).metadata = { data: "x".repeat(100000000) };
throw largeError;
```

## Environment

- **Pulumi SDK:** 3.146.0
- **Node.js:** v24.11.1
- **OS:** macOS (Darwin 24.6.0, arm64)

### Additional context

This issue particularly affects:
- SST users (SST uses Pulumi internally) - see https://github.com/sst/ion
- Any project using AWS SDK v3 (errors are particularly large due to request/response metadata)
- Projects with complex resource graphs

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by adamklingbaum**
Fixes #21326

## What
The fallback in `defaultErrorMessage` now returns `err.stack` directly instead of calling `util.inspect(err)` again.

## Why
When `util.inspect(err, { colors: true })` throws (e.g., on large AWS SDK errors with request/response metadata), the current fallback `util.inspect(err)` can **also** throw the same `RangeError: Invalid string length`. This completely masks the original error message from users, making debugging extremely difficult.

This particularly affects SST users and anyone using AWS SDK v3, where errors commonly include large metadata objects.

## How
Instead of calling `util.inspect` twice (which can both fail on the same large object), fallback directly to `err.stack` (which includes the message) or `String(err)`.

## Testing
Added test case for an error with a stack that causes `util.inspect` to throw, verifying the original error message is preserved.

### CODE REVIEW

**Comment by Frassle** [comment]
/run-acceptance-tests
Please view the results of the acceptance tests [Here](https://github.com/pulumi/pulumi/actions/runs/20836173658)

File: sdk/nodejs/cmd/run/error.ts [hunk 1]
```diff
@@ -25,12 +25,18 @@ import * as util from "util";
 export function defaultErrorMessage(err: any): string {
     if (err?.stack) {
         // colorize stack trace if exists, but fallback to just the message if inspect fails. See
-        // https://github.com/pulumi/pulumi/issues/20567 where this can cause RangeErrors due to large strings
-        // when colors is true.
+        // https://github.com/pulumi/pulumi/issues/20567 and https://github.com/pulumi/pulumi/issues/21326
```
Comment (tgummerer) [inline sdk/nodejs/cmd/run/error.ts:29]: This isn't true anymore? We're not falling back to the uncolorized version anymore.  Though I wonder if we should, and should first try to fall back to the uncolorized version, and if *that* fails fall back to returning the message directly?

File: sdk/nodejs/tests/cmd/run/error.spec.ts [hunk 2]
```diff
@@ -97,6 +105,14 @@ describe("defaultErrorMessage", () => {
             input: veryNaughty,
             expected: /an error occurred while inspecting an error: I'm a naughty object/,
         },
+        {
+            // https://github.com/pulumi/pulumi/issues/21326
+            // AWS SDK errors have large metadata that can cause util.inspect to throw.
+            // When this happens, we should still show the original error message.
```
Comment (tgummerer) [inline sdk/nodejs/tests/cmd/run/error.spec.ts]: I don't think we should call out the AWS SDK specifically here.  This can happen with other SDKs as well.

File: sdk/nodejs/cmd/run/error.ts (hunk 1 above)
Comment (adamklingbaum) [reply sdk/nodejs/cmd/run/error.ts:29]: You're right, good catch. Comment was stale and the approach is better with the cascading fallback. Updated in 56a971a4 to:

1. Try `util.inspect(err, { colors: true })`
2. Fall back to `util.inspect(err)` (uncolorized)
3. Only if both fail, fall back to `err.stack` or `String(err)`

This preserves more error context when possible.

File: sdk/nodejs/tests/cmd/run/error.spec.ts (hunk 2 above)
Comment (adamklingbaum) [reply sdk/nodejs/tests/cmd/run/error.spec.ts]: Good feedback. Updated in e2bad983 to generalize to "SDK errors."

**Comment by tgummerer** [comment]
Thanks for your contribution!
