### PR TITLE
[sdk/go] Ensure Assets of AssetArchive are non-nil when creating and deserializing

### LINKED ISSUE #11103: fatal error while looking into the details of a preview
### What happened?

Pulumi cli crashed while looking at the details of a preview:
================================================================================

```
Pulumi Version:   v3.43.1
Go Version:       go1.19.2
Go Compiler:      gc
Architecture:     amd64
Operating System: windows
Panic:            fatal: An assertion has failed

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.19.2/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x2a626a0, 0xc00921d7f0})
        /opt/hostedtoolcache/go/1.19.2/x64/src/runtime/panic.go:884 +0x212
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printArchiveDiff(0x2e49020?, 0xc001f053a8, 0xc007cc3ef0, 0xc007cc3f90)
        /home/runner/work/pulumi/pulumi/pkg/backend/display/object_diff.go:875 +0x8bc
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValueDiff(0x2b365c0?, 0xc001f053a8, {{{0x2e49020, 0xc007cc3ef0}}, {{0x2e49020, 0xc007cc3f90}}, 0x0, 0x0})
        /home/runner/work/pulumi/pulumi/pkg/backend/display/object_diff.go:768 +0x456
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectPropertyDiff(0xc0092018f0, {0xc002160db6, 0x6}, 0x6, {0xc009201800?, 0xc009201830?, 0xc009201860?, 0xc009201890?})
        /home/runner/work/pulumi/pulumi/pkg/backend/display/object_diff.go:721 +0x20c
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectDiff(0xc0092018f0, {0xc009201800, 0xc009201830, 0xc009201860, 0xc009201890}, {0x0, 0x0, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/backend/display/object_diff.go:710 +0x34f
github.com/pulumi/pulumi/pkg/v3/backend/display.PrintObjectDiff(0xc0092017d0, {0xc009201800?, 0xc009201830?, 0xc009201860?, 0xc009201890?}, {0x0, 0x0, 0x0}, 0x1, 0x3, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/display/object_diff.go:684 +0x191
github.com/pulumi/pulumi/pkg/v3/backend/display.renderDiff({_, _}, {{0x2eb7b2e, 0x7}, {0xc0072fe880, 0x7b}, {0xc00119c640, 0x19}, 0xc00846fef0, 0xc00921e000, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:319 +0x2a5
github.com/pulumi/pulumi/pkg/v3/backend/display.renderDiffResourcePreEvent({{{0x2eb7b2e, 0x7}, {0xc0072fe880, 0x7b}, {0xc00119c640, 0x19}, 0xc00846fef0, 0xc00921e000, 0xc00921e090, {0xc00921d6c0, ...}, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:347 +0x36d
github.com/pulumi/pulumi/pkg/v3/backend/display.RenderDiffEvent({{0x2ec3e3f?, 0x0?}, {0x2cc7520?, 0xc007645400?}}, 0x2a1b4c0?, {{0x2eb373e, 0x6}, 0x0, 0x0, 0x0, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:119 +0x565
github.com/pulumi/pulumi/pkg/v3/backend.createDiff({0x0?, 0x1?}, {0xc006478000, 0xb7, 0x1?}, {{0x2eb373e, 0x6}, 0x0, 0x0, 0x0, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/apply.go:274 +0x26d
github.com/pulumi/pulumi/pkg/v3/backend.confirmBeforeUpdating({_, _}, {_, _}, {_, _, _}, {{{0x450fb30, 0x0, 0x0}, ...}, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/apply.go:196 +0x5aa
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt({_, _}, {_, _}, {_, _}, {0xc0002e6280, {0xc000249040, 0x46}, {0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/apply.go:137 +0x3b9
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc0002e6280, {0xc000249040, 0x46}, {0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/apply.go:218 +0x13e
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Update(_, {_, _}, {_, _}, {0xc0002e6280, {0xc000249040, 0x46}, {0x0, 0x0, ...}, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:956 +0xc5
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc0002e6280, {0xc000249040, 0x46}, {0x0, 0x0, 0x0}, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/stack.go:91 +0xba
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Update(_, {_, _}, {0xc0002e6280, {0xc000249040, 0x46}, {0x0, 0x0, 0x0}, 0xc0003dd4b8, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/stack.go:152 +0x88
main.newUpCmd.func1({_, _}, {{{0x450fb30, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:188 +0xe17
main.newUpCmd.func3(0x0?, {0xc0004721d0, 0x0, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:468 +0x665
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000a9aa00?, {0xc0004721d0, 0x0, 0x1})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc000a9aa00, {0xc0004721c0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a1ac80)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
```

### Steps to reproduce

started with 
```
> pulumi up -r  
Do you want to perform this update? 
> details
```
### Expected Behavior

The details of resources that were going to be updated / replaced 

### Actual Behavior

fatal error, encounterd a panic.

### Output of `pulumi about`

```

running 'dotnet build -nologo .'
  Determining projects to restore...

  All projects are up-to-date for restore.

  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview

  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview

  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview

  SCloud.Core -> C:\_src\cloud\github\SearchCloudIAC\src\SCloud.Core\bin\Debug\net6.0\SCloud.Core.dll

  Application -> C:\_src\cloud\github\SearchCloudIAC\src\Application\bin\Debug\net6.0\Application.dll

  availability-check -> C:\_src\cloud\github\SearchCloudIAC\src\availability-check\bin\Debug\availability-check.dll

C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\CloudZone.cs(141,38): warning CS8602: Dereference of a possibly null reference. [C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\sinequa-cloudzone.csproj]

C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\CloudZone.cs(141,38): warning CS8619: Nullability of reference types in value of type 'Output<string?>' doesn't match target type 'Output<string>'. [C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\sinequa-cloudzone.csproj]
C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\CloudZone.cs(146,50): warning CS8601: Possible null reference assignment. [C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\sinequa-cloudzone.csproj]
C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\CloudZone.cs(147,51): warning CS8602: Dereference of a possibly null reference. [C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\sinequa-cloudzone.csproj]
C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\CloudZone.cs(63,16): warning CS8618: Non-nullable property 'AvailabilityCheckContainerUri' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\sinequa-cloudzone.csproj]
C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\CloudZone.cs(210,24): warning CS8603: Possible null reference return. [C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\sinequa-cloudzone.csproj]
C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\CloudZone.cs(215,24): warning CS8603: Possible null reference return. [C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\sinequa-cloudzone.csproj]
C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\CloudZone.cs(366,43): warning CS8619: Nullability of reference types in value of type 'Output<string?>' doesn't match target type 'Output<string>'. [C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\sinequa-cloudzone.csproj]

  sinequa-cloudzone -> C:\_src\cloud\github\SearchCloudIAC\src\PulumiStacks\sinequa-cloudzone\bin\Debug\net6.0\sinequa-cloudzone.dll



Build succeeded.
```
### Additional context

I'm guessing this is related to our stack, and can be hard to reproduce.  

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Fixes #11103

The problem in the issue the distinction between `Assets` or an archive being `nil` vs. being an empty map of assets. When creating and deserializing Archives, `nil` was allowed which leads to panics when asserting `archive.IsAssets()` because the `Assets` is `nil` even though it is a proper archive. 

This PR fixes the issue by ensuring that an instance of `Archive` will have a non-nil `Assets` field whether that is during construction or marshalling. 

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: sdk/go/common/resource/asset_test.go [hunk 1]
```diff
@@ -539,6 +539,19 @@ func TestFileExtentionSniffing(t *testing.T) {
 	assert.Equal(t, ArchiveFormat(NotArchive), detectArchiveFormat("./some/path/who.even.knows"))
 }
 
+func TestEmptyArchiveRoundTrip(t *testing.T) {
+	t.Parallel()
+
+	emptyArchive, err := NewAssetArchive(nil)
+	assert.True(t, emptyArchive.IsAssets(), "even empty archives should be have empty assets")
+	assert.NoError(t, err, "Creating an empty archive should work")
```
Comment (Frassle) [inline sdk/go/common/resource/asset_test.go:547]: A) Do the err check first
B) Use require.NoError, generally if we have an error the other asserts will just end up panic'ing (due to like nil access exceptions and the like)

File: sdk/go/common/resource/asset.go [hunk 2]
```diff
@@ -577,6 +582,10 @@ func (a *Archive) Serialize() map[string]interface{} {
 			}
 		}
 		result[ArchiveAssetsProperty] = assets
+	} else {
+		// Ensure that the assets property is always present, even if empty.
```
Comment (Frassle) [inline sdk/go/common/resource/asset.go:586]: The JSON/YAML attributes have omitempty so this would just get dropped anyway. But that's expected we only want the field when this _is_ an asset archive, and if assets is nil then it isn't. i.e. just remove this block.

File: sdk/go/common/resource/asset.go [hunk 3]
```diff
@@ -603,42 +612,43 @@ func DeserializeArchive(obj map[string]interface{}) (*Archive, bool, error) {
...
 
-	var assets map[string]interface{}
-	if v, has := obj[ArchiveAssetsProperty]; has {
-		assets = make(map[string]interface{})
-		if v != nil {
-			m, ok := v.(map[string]interface{})
-			if !ok {
-				return &Archive{}, false, fmt.Errorf("unexpected archive contents of type %T", v)
-			}
+	assets := make(map[string]interface{})
```
Comment (Frassle) [inline sdk/go/common/resource/asset.go:615]: Not sure this is safe? Looks like we could create an Archive with assets and path set?

**Review by Frassle — COMMENTED** [review]
We should do a similar fix for Asset

File: sdk/go/common/resource/asset_test.go (hunk 1 above)
Comment (Zaid-Ajaj) [reply sdk/go/common/resource/asset_test.go]: ✅

File: sdk/go/common/resource/asset.go (hunk 2 above)
Comment (Zaid-Ajaj) [reply sdk/go/common/resource/asset.go]: I didn't notice those since we are dealing with a custom serialization/deserialization here but indeed, this seems redundant so removed this block

File: sdk/go/common/resource/asset.go (hunk 3 above)
Comment (Zaid-Ajaj) [reply sdk/go/common/resource/asset.go:649]: I updated the `DeserializeArchive` method such that it is not possible to construct conflicting fields:
 - When we check for the `path` property and it exists, we immediately return `NewPathArchive`
 - When we check for the `uri` property and it exists, we immediately return `NewURIArchive`
 - Finally if we didn't find `path` nor `uri`, we get the `assets` and default to an empty map 

At the start of the function, we check that the input object _must_ have one of `path`, `uri` or `assets`

File: sdk/go/common/resource/asset.go [hunk 4]
```diff
@@ -486,18 +491,24 @@ func NewAssetArchive(assets map[string]interface{}) (*Archive, error) {
...
+	if uri == "" {
+		return nil, errors.New("uri cannot be empty when constructing a URI archive")
+	}
 	a := &Archive{Sig: ArchiveSig, URI: uri}
 	err := a.EnsureHash()
 	return a, err
 }
 
-func (a *Archive) IsAssets() bool { return a.Assets != nil }
+func (a *Archive) IsAssets() bool { return !a.IsPath() && !a.IsURI() }
```
Comment (Frassle) [inline sdk/go/common/resource/asset.go:511]: This should just be a.Assets != nil. Whenever we construct an Archive object we'll ensure it's a non-nil map.

**Review by Frassle — APPROVED** [review]
