### PR TITLE
[codegen/python] Fix issues related to referencing external resources/types

### LINKED ISSUE #5819: [codegen/python] Panic when referencing some external types
The following properties cause the Python codegen to panic with:

```
panic: interface conversion: interface {} is json.RawMessage, not python.PropertyInfo
github.com/pulumi/pulumi/pkg/v2/codegen/python.recordProperty(0xc000d8c8c0, 0xc0016fc2a0, 0xc0016fc2d0, 0xc000548f58)
github.com/pulumi/pulumi/pkg/v2@v2.14.1-0.20201121160205-9a707c4e03b6/codegen/python/gen.go:1446 +0x3d
```

## eks:index:ManagedNodeGroup

```go
"launchTemplate": {
	TypeSpec:    schema.TypeSpec{Ref: awsRef("#/types/aws:eks%2FNodeGroupLaunchTemplate:NodeGroupLaunchTemplate")},
	Description: "Launch Template settings.",
},
"remoteAccess": {
	TypeSpec:    schema.TypeSpec{Ref: awsRef("#/types/aws:eks%2FNodeGroupRemoteAccess:NodeGroupRemoteAccess")},
	Description: "Remote access settings.",
},
"scalingConfig": {
	TypeSpec: schema.TypeSpec{Ref: awsRef("#/types/aws:eks%2FNodeGroupScalingConfig:NodeGroupScalingConfig")},
	Description: "Scaling settings.\n\n" +
		"Default scaling amounts of the node group autoscaling group are:\n" +
		"  - desiredSize: 2\n" +
		"  - minSize: 1\n" +
		"  - maxSize: 2",
},
```

## eks:index:CoreData

```go
"encryptionConfig": {
	TypeSpec: schema.TypeSpec{Ref: awsRef("#/types/aws:eks%2FClusterEncryptionConfig:ClusterEncryptionConfig")},
},
```

This line is panicing:

https://github.com/pulumi/pulumi/blob/505d53421ed12ae0e00d3e489eb9686b619eda7a/pkg/codegen/python/gen.go#L1446

The value is `json.RawMessage` rather than `python.PropertyInfo`.

I wonder if the following isn't called for externally referenced schemas?

https://github.com/pulumi/pulumi/blob/505d53421ed12ae0e00d3e489eb9686b619eda7a/pkg/codegen/python/importer.go#L57-L64

### LINKED ISSUE #6232: [codegen/python]: Fix bugs referencing external resources/types
There are some bugs in the Python codegen when referencing external resources/types, that we temporarily worked around in EKS:

https://github.com/pulumi/pulumi-eks/blob/854991b8dccbe7c1b34046b6a113d7446258bce4/provider/cmd/pulumi-gen-eks/main.go#L1591-L1637

I have a codegen fix available for this -- just need to clean it up and open the PR.

### PR DESCRIPTION
**Pull request by justinvp**
These changes will allow us to remove the remaining [workarounds](https://github.com/pulumi/pulumi-eks/blob/f7ef1c09cc34a2bc2914b49fab46eafa8135896f/provider/cmd/pulumi-gen-eks/main.go#L1576-L1638) for the Python codegen in EKS.

Fixes #5819
Fixes #6232

### CODE REVIEW

File: pkg/codegen/python/gen.go [hunk 1]
```diff
@@ -180,6 +200,35 @@ func (mod *modContext) tokenToEnum(tok string) string {
...
+	if v, ok := pkg.Language["python"].(PackageInfo); ok {
+		info = v
+	}
+	modName, name := tokenToModule(tok, pkg, info.ModuleNameOverrides), tokenToName(tok)
+	if modName == mod.mod {
+		modName = ""
+	}
+	if modName != "" {
+		modName = strings.ReplaceAll(modName, "/", ".") + "."
+	}
```
Comment (lblackstone) [inline pkg/codegen/python/gen.go:228]: Would it make sense to pull this into a separate function since it appears in multiple places?

**Review by lblackstone — APPROVED** [review]
