### PR TITLE
Fix inconsistent object type naming.

### LINKED ISSUE #6200: [codegen] Inconsistent code generated for schema types that are used both for resources and invokes
### Context

A schema defines:

- Types `A` and `B`
- Resource `R`
- Invoke `I`
- Both `R` and `I` use the type `A` in to define an input property and type `B` to define an output property

### Current behavior

Problem 1: .NET, Node.js, and Python SDKs (not sure about Go) would only generate a single `AArgs` type with every property being an `Input<T>` which doesn't match the common shape of invoke's input types (with no `Input`'s)

Problem 2: .NET and Python SDKs (Node.js is fine, not sure about Go) would name the output type `B` or `BResult` depending on whether it's used for both resource and invokes, or just for invokes.

Both problems lead to breaking changes if a new resource is introduced that points to a type currently used by an invoke (version `X` has `A`, `B`, and `I` and version `X+1` introduces `R`) . Examples in https://github.com/pulumi/pulumi-azure-nextgen-provider/pull/455/

### PR DESCRIPTION
**Pull request by pgavlin**
See #6200 for a complete description of the issue. In short, we generate
inconsistent names for object types depending on whether or not they are
transitively reachable from resources or functions, which risks
unintentional breaking changes due to schema updates.

1. Name "input" types differently: `TArgs` for a type that is used in
   resource inputs, having `Input<T>` properties, and `T` for a type
   that is used in invoke inputs. The same schema type can produce both.

2. Always keep the name `T` for output types, avoid appending `Result` to
   the name.

3. As needed, introduce a flag in the existing providers' schemas to avoid
   breaking changes. Consider removing it on a major version bump.

Fixes #6200.

### CODE REVIEW

**Comment by pgavlin** [comment]
Note that the test failures are expected, as they demonstrate the effects of this change w/o updating downstream compat flags. I'll fix up the tests before committing.

**Comment by komalali** [comment]
@pgavlin curious if there's any interplay between this fix and the issue described in https://github.com/pulumi/pulumi/issues/5758

File: pkg/codegen/nodejs/gen.go [hunk 1]
```diff
@@ -845,7 +845,13 @@ func (mod *modContext) genType(w io.Writer, obj *schema.ObjectType, input bool,
 	}
 
 	wrapInput := input && !mod.details(obj).functionType
-	mod.genPlainType(w, tokenToName(obj.Token), obj.Comment, properties, input, wrapInput, false, level)
+
+	name := tokenToName(obj.Token)
+	if wrapInput && mod.compatibility != tfbridge20 {
+		name += "Args"
```
Comment (mikhailshilkov) [inline pkg/codegen/nodejs/gen.go:851]: I ran this on Azure-Native - it looks like this changes the type name from `Foo` to `FooArgs`, but the parent type still tries referencing `Foo`. Example of an error:

```
web/webAppSourceControlSlot.ts:148:66 - error TS2694: Namespace '"/Users/mikhailshilkov/go/src/github.com/pulumi/pulumi-azure-native/sdk/nodejs/types/input".web' has no exported member 'GitHubActionConfiguration'.

148     readonly gitHubActionConfiguration?: pulumi.Input<inputs.web.GitHubActionConfiguration>;
```

**Comment by mikhailshilkov** [comment]
Azure-Native preview is here: https://github.com/pulumi/pulumi-azure-native/pull/716

File: pkg/codegen/nodejs/gen.go (hunk 1 above)
Comment (mikhailshilkov) [reply pkg/codegen/nodejs/gen.go:851]: See https://github.com/pulumi/pulumi-azure-native/actions/runs/711650762

**Comment by pgavlin** [comment]
@stack72 something seems to be wrong with the diffs. If I run these locally, I see plenty of diffs, but the jobs that are posting to the PR show no diffs. Any ideas?

**Comment by stack72** [comment]
> @stack72 something seems to be wrong with the diffs. If I run these locally, I see plenty of diffs, but the jobs that are posting to the PR show no diffs. Any ideas?

@pgavlin so the issue is that pulumi@master uses v3 of the pkg & sdk modules and the downstream repos use v2 of the pkg & sdk modules so those diffs won't work until we merge feature-3.0 to master in those downstream repos

that will happen today!

**Comment by pgavlin** [comment]
Okay, I believe that this is now good to go: I've verified that the combat flag works for `pulumi-aws`, and that the new codegen works for `pulumi-azure-ng`. 

After we merge this, we will need to update `pulumi-terraform-bridge` to pass the combat flag prior to rollout.

**Review by mikhailshilkov — APPROVED** [review]
LGTM. I admit it's hard to validate the changes in my head, so I rely on the generation results. Azure changes are looking good and we have a flag to prevent any changes in other providers, so it feels like this is ready to merge.

**Comment by pgavlin** [comment]
Pretty certain that the downstream docs tests are only failing due to module differences.

**Comment by stack72** [comment]
> Pretty certain that the downstream docs tests are only failing due to module differences.

Yeah resource docs will fail in PR gen until feature-3.0 goes to master tomorrow on each of these repos :/
