### PR TITLE
Fix undeclared err codegen bug

### LINKED ISSUE #11584: Use of undeclared err in Go examples
### What happened?

I just tried to upgrade dependencies in pulumi-azure like so:
```
- 11         github.com/pulumi/pulumi-terraform-bridge/v3 v3.30.0
- 12         github.com/pulumi/pulumi/sdk/v3 v3.40.3-0.20220928152524-977c89fcacd7
+ 11         github.com/pulumi/pulumi-terraform-bridge/v3 v3.34.0
+ 12         github.com/pulumi/pulumi/sdk/v3 v3.48.1-0.20221205185749-86e7d56df231
```

After regenerating the SDKs, I see a bunch of diffs like this one in Go:

```go
  27    //        func main() {
  28    //                pulumi.Run(func(ctx *pulumi.Context) error {
- 29    //                       _, err := backup.GetPolicyFileshare(ctx, &backup.GetPolicyFileshareArgs{
+ 29    //                       _, err = backup.GetPolicyFileshare(ctx, &backup.GetPolicyFileshareArgs{
```

`:=` has been changed to `=` but this is the first occurrence of err so it's undeclared.

There seem to be many instances, although some of those below may be legit if `err` was declared earlier.

```
git diff sdk/go | rg -A 1 '^\-.*_, err :=' | wc -l
     182
```

### Steps to reproduce

I've pushed the branch to pulumi/pulumi-azure/tkappler/upgrade-tf-bridge-3.34.

Steps to repro from `master` in pulumi-azure are

```
cd provider
go get -u -v github.com/pulumi/pulumi-terraform-bridge/v3
go mod tidy
cd ..
make tfgen
make build_go
```

### Expected Behavior

valid Go code in examples

### Actual Behavior

see above

### Output of `pulumi about`

_No response_

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by aq17**
Fixes #11584 .

This fixes a codegen bug where `=` was always being used when generating a local variable with no assignment (assigning to `_`), which is incorrect if an error is also being assigned to for the first time (`_, err := ...`).

### CODE REVIEW

**Comment by aq17** [comment]
@thomas11 I reran `tfgen` with this commit and running 
`git diff sdk/go | rg -A 1 '^\-.*_, err :=' | wc -l` yields 0

File: pkg/codegen/go/gen_program.go [hunk 1]
```diff
@@ -816,9 +816,6 @@ func (g *generator) genLocalVariable(w io.Writer, v *pcl.LocalVariable) {
 			assignment = "="
 		}
 	}
-	if name == "_" {
-		assignment = "="
-	}
```
Comment (thomas11) [inline pkg/codegen/go/gen_program.go:821]: I assume this will introduce the opposite case where `_, err :=` is generated even when `err` is already declared, but that's ok because [short variable declarations may redeclare variables](https://go.dev/ref/spec#Short_variable_declarations)?

**Review by thomas11 — APPROVED** [review]

File: pkg/codegen/go/gen_program.go (hunk 1 above)
Comment (aq17) [reply pkg/codegen/go/gen_program.go:821]: I don't think so, we should handle that [here](https://github.com/pulumi/pulumi/blob/e3a60af8cb7a20ea68095d5fc77eb6c50452486a/pkg/codegen/go/gen_program.go#L831) still

**Review by justinvp — APPROVED** [review]
Can we easily add a test for this (and some of the other recent bug fixes)? I'd love to "lock-in" the behavior so it doesn't regress down the road.
