### PR TITLE
go/auto: use random stack names in TestNestedConfig

### LINKED ISSUE #22688: `TestNestedConfig` is flaky
```
=== FAIL: go/auto TestNestedConfig (8.98s)
    local_workspace_test.go:2254: failed to initialize stack, err: failed to create stack: exit status 1
        code: 1
        stdout: 
        stderr: error: stack 'moolumi/nested_config/dev' already exists
```

From https://github.com/pulumi/pulumi/actions/runs/24776496041/job/72497131024?pr=22684

### PR DESCRIPTION
**Pull request by tgummerer**
TestNestedConfig uses a static stack name for its stack, because it wants to read `Pulumi.dev.yaml` from there. This sometimes leads to flakes, see https://github.com/pulumi/pulumi/issues/22688 for example.

Use a random stack name, and rename the stack config file to match instead.

Fixes https://github.com/pulumi/pulumi/issues/22688

### CODE REVIEW

File: sdk/go/auto/local_workspace_test.go [hunk 1]
```diff
@@ -2238,22 +2238,38 @@ func TestSetAllConfigJson(t *testing.T) {
 	assert.False(t, numberKey.Secret, "numberKey should not be secret")
 }
 
-// This test requires the existence of a Pulumi.dev.yaml file because we are reading the nested
-// config from the file. This means we can't remove the stack at the end of the test.
-// We should also not include secrets in this config, because the secret encryption is only valid within
+// This test reads nested config from a Pulumi.<stack>.yaml file.
+// We should not include secrets in this config, because the secret encryption is only valid within
 // the context of a stack and org, and running this test in different orgs will fail if there are secrets.
```
Comment (Frassle) [inline sdk/go/auto/local_workspace_test.go:2243]: Isn't this comment now out of date?

Comment (tgummerer) [reply sdk/go/auto/local_workspace_test.go:2243]: I think it's still valid? The parts of the comments that are still left at least.  We still can't put secrets in there, because having to decrypt a secret in a different stack/org (different stack is now always going to be the case for every run), is still not valid.

Comment (Frassle) [reply sdk/go/auto/local_workspace_test.go:2243]: ah yup, if we're assuming service secrets this is still true yeh

**Review by Frassle — APPROVED** [review]
