### PR TITLE
Propagate deleted dependencies of untargeted resources

### LINKED ISSUE #15959: `--target` leads to "snapshot integrity failure; refusing to use it" error
### What happened?

I ran `pulumi up --target 'urn:...::aws:ecs/service:Service::ratelimit-' --target-dependents`.

The preview correctly identified the resource as being deleted, but the actual `up` returned an error for unrelated resources:

```
error: could not deserialize deployment: snapshot integrity failure; refusing to use it: resource urn:...::aws:ecs/taskDefinition:TaskDefinition::consoleTaskDefinition’s dependency urn:...::pulumi-service:infrastructure:Service$docker:buildx/image:Index::consoleImage comes after it
```

Subsequent `up`s had the same error.

I was eventually able to get past this with `up --disable-integrity-checking` -- once that succeeded everything worked as normal again.

### Example

Steps:
- 

### Output of `pulumi about`

CLI
Version      3.113.0
Go Version   go1.22.2
Go Compiler  gc

Host
OS       darwin
Version  14.1
Arch     arm64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/bryce-pulumi-corp
User           bryce-pulumi-corp
Organizations  bryce-pulumi-corp, pulumi
Token type     personal

### Additional context

Both resources have `retainOnDelete` set.

The targeted resource was expected to be deleted, because I had replaced it with a different type/provider in my program.

I exported a state file shortly before running the update with `--target`, so it might be possible to repo using that. Ping me and I can send it over.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #16052: `pulumi up --target` resulting in state integrity errors
### What happened?

Reported by a customer (see internal chat https://pulumi.slack.com/archives/CKJ4C845D/p1713941404085679 for details). 

It appears a `pulumi refresh` run resulted in state being written out that failed integrity checks.

### Example

Details on internal chat.

### Output of `pulumi about`

N/A

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by lunaris**
When using `--target` to target specific resources during an update, we use the list of targets to decide which steps to generate given a set of resource registrations. Specifically:

* If the registration event names a resource that is targeted, we process it as usual.
* If the registration event names a resource that _is not_ targeted, we emit a `SameStep` for it.

In the latter case, the emission of a `SameStep` means that the old state for the resource will be copied across to the new state. This is the desired behaviour -- the resource was not targeted and so the new state should contain the resource exactly as it was prior to the update. However, this presents a problem if the old state has references to resources that either will not appear in the new state, or will appear in the wrong place. Consider the following program in TypeScript-esque pseudocode:

```typescript
const a = new Resource("a")
const b = new Resource("b", { dependency: a })
const c = new Resource("c")
```

Here, `b` depends on `a`, while `a` and `c` have no dependencies. We run this program without specifying targets and obtain a state containing `a`, `b` and `c`, with `a` appearing before `b` due to `b`'s dependency on `a`. We now modify the program as follows:

```typescript
const b = new Resource("b")
const c = new Resource("c")
```

`a` has been removed from the program and consequently `b` no longer depends on it. We once more run the program, this time with a `--target` of `c`. That is to say, neither `a` nor `b` is targeted. The execution proceeds as follows:

* `a` is not in the program, so no `RegisterResourceEvent` will be emitted and processed for it.
* `b` is in the program, but it is not targeted. Its `RegisterResourceEvent` will be turned into a `SameStep` and `b`'s _old state will be copied as-is to the new state_.
* `c` is in the program and is targeted. It will be processed as normal.

At the end of execution when we come to write the snapshot, we take the following actions:

* We first write the processed resources: `b`'s old state and `c`'s new state.
* We then copy over any unprocessed resources from the base (previous) snapshot. This includes `a` (which is again desirable since its deletion should not be processed due to it not being targeted).

Our snapshot is now not topologically sorted and thus invalid: `b` has a dependency on `a`, but `a` appears after it. Presently this bug will manifest irrespective of the nature of the dependency: `.Dependencies`, `.PropertyDependencies` and `.DeletedWith` are all affected.

This commit fixes this issue by traversing all untargeted resource dependency relationships and ensuring that `SameStep`s (or better if they have been targeted) are emitted before emitting the depending resource's `SameStep`.

* Fixes #16052 
* Fixes #15959

### CODE REVIEW

File: pkg/resource/deploy/step_generator.go [hunk 1]
```diff
@@ -945,8 +945,123 @@ func (sg *stepGenerator) generateSteps(event RegisterResourceEvent) ([]Step, err
...
+						if !has {
+							return nil, result.BailErrorf(
+								"dependency %s of untargeted resource %s has no old state",
+								dep,
+								urn,
+							)
+						}
+
+						depStep := NewSameStep(sg.deployment, nil, depOld, depOld)
+						steps = append(steps, depStep)
```
Comment (Frassle) [inline pkg/resource/deploy/step_generator.go:1011]: Should we be setting sg.sames[dep] here? Otherwise if it shows in deps and propDeps aren't we going to make two same steps?

File: pkg/resource/deploy/step_generator.go [hunk 2]
```diff
@@ -2088,6 +2203,25 @@ func (sg *stepGenerator) AnalyzeResources() error {
 	return nil
 }
 
+// hasGeneratedStep returns true if and only if the step generator has generated a step for the given URN.
+func (sg *stepGenerator) hasGeneratedStep(urn resource.URN) bool {
+	generatedCreate := sg.creates[urn]
```
Comment (Frassle) [inline pkg/resource/deploy/step_generator.go:2208]: I'd have probably just done this as one return expression

File: pkg/resource/deploy/step.go [hunk 3]
```diff
@@ -150,7 +150,11 @@ func (s *SameStep) Apply(preview bool) (resource.Status, StepCompleteFunc, error
 	}
 
 	// TODO: should this step be marked as skipped if it comes from a targeted up?
-	complete := func() { s.reg.Done(&RegisterResult{State: s.new}) }
+	complete := func() {
+		if s.reg != nil {
```
Comment (Frassle) [inline pkg/resource/deploy/step.go:154]: Worth a comment here why reg can be nil

File: pkg/resource/deploy/step_generator.go [hunk 4]
```diff
@@ -945,8 +945,123 @@ func (sg *stepGenerator) generateSteps(event RegisterResourceEvent) ([]Step, err
...
+			// Note:
+			//
+			// * This traversal has to be depth-first -- we need to push steps for our
+			//   dependencies before we push a step for ourselves.
+			//
+			// * "Dependencies" here includes dependencies, property dependencies, and
+			//   deleted-with relationships.
+
+			seen := make(map[resource.URN]bool)
+			getDependencySteps := func(old *resource.State) ([]Step, error) {
```
Comment (Frassle) [inline pkg/resource/deploy/step_generator.go:990]: This looks like it should be recursive?

File: pkg/engine/lifecycletest/target_test.go [hunk 5]
```diff
@@ -2322,3 +2322,379 @@ func TestTargetChangeAndSameProviderVersion(t *testing.T) {
...
+					Targets: deploy.NewUrnTargets([]string{fmt.Sprintf("**%s**", targetName)}),
+				},
+			}, false, p.BackendClient, nil, "1")
+
+			// Assert.
+			assert.NoError(t, err)
+			assert.NoError(t, snap.VerifyIntegrity())
+		})
+
+		t.Run("deleting the middle of a dependency chain", func(t *testing.T) {
```
Comment (Frassle) [inline pkg/engine/lifecycletest/target_test.go:2411]: Shouldn't there be another test case of deleting both a and b?

File: pkg/resource/deploy/step_generator.go [hunk 6]
```diff
@@ -945,8 +945,123 @@ func (sg *stepGenerator) generateSteps(event RegisterResourceEvent) ([]Step, err
...
+				if seen[old.URN] {
+					return nil, nil
+				}
+
+				seen[old.URN] = true
+				var steps []Step
+
+				for _, dep := range old.Dependencies {
+					generatedDep := sg.hasGeneratedStep(dep)
+					if !generatedDep {
```
Comment (Frassle) [inline pkg/resource/deploy/step_generator.go:1000]: Maybe for another PR,  but we need to handle the case that we haven't yet generated a step for 'dep' but it _is_ targeted and so will want to delete later. I think we just error in that case.

File: pkg/resource/deploy/step_generator.go (hunk 1 above)
Comment (lunaris) [reply pkg/resource/deploy/step_generator.go:1011]: So I thought the `seen` map would take care of that, though there is the question of whether that works across invocations and `sg.sames` is probably a better call.

File: pkg/resource/deploy/step_generator.go (hunk 4 above)
Comment (lunaris) [reply pkg/resource/deploy/step_generator.go:990]: God I'm an idiot.

**Review by Frassle — APPROVED** [review]
