### PR TITLE
Fix panic when analyzer plugin is not found.

### LINKED ISSUE #10054: Bad error message when missing pulumi-analyzer-policy executable
### What happened?

I use Manjaro (basically Arch), this is not the first time that the pulumi package from the Arch repo is missing some files.
The issue is that instead of printing something like this:
```
Could not find pulumi-analyzer-policy, it seems like your installation of pulumi is incomplete, check https://www.pulumi.com/docs/get-started/install/
```
It does this:
```console
$ pulumi preview --policy-pack ../crossguard-policies
Previewing update (xxxxxxx):
panic: fatal: An assertion has failed: failed to convert err no analyzer plugin 'pulumi-analyzer-policy' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install analyzer policy` to Error, did this come from an RPC endpoint?

goroutine 135 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        github.com/pulumi/pulumi/sdk/v3@v3.34.1/go/common/util/contract/f
[...]
```
And:
```console
$ pulumi plugin install analyzer policy
error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-policy/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
```

### Steps to reproduce

```
$ docker run -it --rm archlinux bash
# pacman -Sy pulumi nodejs npm
# mkdir test && cd test
# pulumi login -l && pulumi new kubernetes-typescript
# mkdir p && echo "runtime: nodejs" > p/PulumiPolicy.yaml
# pulumi preview --policy-pack p/
```

=> optional step `rm -f /usr/bin/pulumi-analyzer-policy`, should not be needed as pulumi-analyzer-policy is missing.

### Expected Behavior

Print a friendly error message

### Actual Behavior

print a wall of text and errors, mislead the user

### Versions used

pulumi 3.34.1 from the Arch repo.

### Additional context

EDIT:
This is not the first time that this happens, but last time the error message that pulumi printed wasn't as bad https://bugs.archlinux.org/task/72394

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description

Fixes #10054

Analyzer Plugins may be missing. We should error instead of panic.

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: sdk/go/common/resource/plugin/analyzer_plugin.go [hunk 1]
```diff
@@ -104,7 +104,11 @@ func NewPolicyAnalyzer(
 	pluginPath, err := workspace.GetPluginPath(ctx.Diag,
 		workspace.AnalyzerPlugin, policyAnalyzerName, nil, host.GetProjectPlugins())
 	if err != nil {
-		return nil, rpcerror.Convert(err)
```
Comment (dixler) [inline sdk/go/common/resource/plugin/analyzer_plugin.go:107]: This would fail the conversion and then fail an assert.

**Review by Zaid-Ajaj — APPROVED** [review]

File: sdk/go/common/resource/plugin/analyzer_plugin.go (hunk 1 above)
Comment (Frassle) [reply sdk/go/common/resource/plugin/analyzer_plugin.go:107]: I wouldn't expect GetPluginPath to _ever_ return an rpcerror. I think this can just be changed to `return nil, err`.

Comment (Frassle) [reply sdk/go/common/resource/plugin/analyzer_plugin.go:107]: Also isn't the error below what we really want to see? "could not start policy pack %q because the built-in analyzer..."

**Review by Frassle — CHANGES_REQUESTED** [review]

File: sdk/go/common/resource/plugin/analyzer_plugin.go (hunk 1 above)
Comment (dixler) [reply sdk/go/common/resource/plugin/analyzer_plugin.go:107]: > Also isn't the error below what we really want to see? "could not start policy pack %q because the built-in analyzer..."

There are a few different types of errors that can come out of `workspace.GetPluginPath`. I don't think we can just collapse them all to this error message where the reasoning in the message is always applicable.

I don't know what the case where `err == nil && pluginPath == ""`, but I don't want to introduce any bugs from removing a guard clause so I'd like to leave it.

Comment (Frassle) [reply sdk/go/common/resource/plugin/analyzer_plugin.go:107]: > I don't know what the case where err == nil && pluginPath == "", but I don't want to introduce any bugs from removing a guard clause so I'd like to leave it.

I don't think we ever return a nil err and empty path.

> There are a few different types of errors that can come out of workspace.GetPluginPath. I don't think we can just collapse them all to this error message where the reasoning in the message is always applicable.

Sure, if you want to be conservative check for `MissingError` which is what we return when we couldn't find a path.

File: sdk/go/common/resource/plugin/analyzer_plugin.go [hunk 2]
```diff
@@ -103,13 +103,13 @@ func NewPolicyAnalyzer(
 	// Load the policy-booting analyzer plugin (i.e., `pulumi-analyzer-${policyAnalyzerName}`).
 	pluginPath, err := workspace.GetPluginPath(ctx.Diag,
 		workspace.AnalyzerPlugin, policyAnalyzerName, nil, host.GetProjectPlugins())
-	if err != nil {
-		return nil, rpcerror.Convert(err)
-	} else if pluginPath == "" {
+	if _, ok := err.(*workspace.MissingError); ok {
```
Comment (Frassle) [inline sdk/go/common/resource/plugin/analyzer_plugin.go:106]: use errors.Is, not just a cast check.

Comment (dixler) [reply sdk/go/common/resource/plugin/analyzer_plugin.go]: It's suggested to do `errors.As()`

https://github.com/golang/go/wiki/ErrorValueFAQ#how-should-i-change-my-error-handling-code-to-work-with-the-new-features

MissingError is created with NewMissingError and has arguments so testing for equality would be hard to do or fragile.

**Review by Frassle — APPROVED** [review]
