### PR TITLE
Fix aliasing children

### LINKED ISSUE #12662: Aliases that use fields other than URN (like Name, Type, etc.) are not working for child resources in Go
### What happened?

The PodDisruptionBudget was changed from v1beta1 to v1 as part of support for EKS v1.25, which removes the v1beta1 API.
This is creating issues during an update, because the PDB is aliased by default by Pulumi (https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/go/kubernetes/policy/v1/podDisruptionBudget.go#L41). This lead to a situation where, because of the alias, stacks ended up in a state where it wanted to delete a resource that was already gone and an update thus failing.

- [v1beta1/poddisruptionbudget/](https://www.pulumi.com/registry/packages/kubernetes/api-docs/policy/v1beta1/poddisruptionbudget/)
- [v1/poddisruptionbudget/](https://www.pulumi.com/registry/packages/kubernetes/api-docs/policy/v1/poddisruptionbudget)

### Expected Behavior

pulumi-kubernetes automatically aliases different resource versions. If this worked as expected, the resource would have been updated to v1/PodDisruptionBudget in the state, with no change to the resource on the cluster.

### Steps to reproduce

1. Stand up an eks cluster in python (so that it is a MLC).
2. Create a v1beta1 poddisruptionbudget on eks 1.24
3. upgrade to eks to 1.25 and run `pulumi up`

### Output of `pulumi about`

pending.

### Additional context

1. Kubernetes v1.25 removes the v1beta1/PodDisruptionBudget resource, necessitating an update in the CSI driver component resource

1. pulumi-kubernetes automatically aliases different resource versions, but a MLC bug prevented the alias from working correctly. If this worked as expected, the resource would have been updated to v1/PodDisruptionBudget in the state, with no change to the resource on the cluster. Instead, pulumi wanted to replace the resource.

1. To work around the replacement, the PDB was changed from a statically-named resource to an auto-named resource in code. These resources were also aliased, and the deleteBeforeReplace resource option was set. The alias is incorrect, because these are different resources on the cluster due to the different .metadata.name.

1. Due to the options set in 3., pulumi tries to delete-before-replace the PDB. The delete succeeds, but the replacement seems to be stuck in a retry loop where it keeps creating new auto-named PDBs. I think this is because of the invalid alias in 3.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
**Note:** This is a large PR that I've separated into many smaller commits to make it easier to review commit by commit.

## Background

Originally, each SDK would compute alias URNs from alias "specs" and the alias URNs would be sent to the engine. https://github.com/pulumi/pulumi/pull/10819 added support for having the engine compute the alias URNs by enabling SDKs to send just the alias specs to the engine. https://github.com/pulumi/pulumi/pull/11206 updated the Node.js SDK to leverage this new capability, and subsequent PRs enabled it for the other SDKs.

Unfortunately, there are a couple of issues:

1. Engine: A bug in alias computation
2. Node.js SDK: A bug in the alias specs sent to the engine

## Engine Bug

There is an issue with how the engine computes the aliases when the resource is a child and doesn't have `Parent` set on the alias spec (and the parent doesn't have any aliases).

```python
class FooResource(pulumi.ComponentResource):
    def __init__(self, name, opts=None):
        super().__init__("my:module:FooResource", name, None, opts)


class ComponentResource(pulumi.ComponentResource):
    def __init__(self, name, opts=None):
        super().__init__("my:module:ComponentResource", name, None, opts)
        FooResource("childrenamed", pulumi.ResourceOptions(
            parent=self,
            aliases=[pulumi.Alias(name="child")]
        ))
```

In the example above, `ComponentResource` has a child `FooResource` which was renamed from `child` to `childrenamed`.

The engine does not compute the correct alias:

```
expected: urn:pulumi:stack::project::my:module:ComponentResource$my:module:FooResource::child
  actual: urn:pulumi:stack::project::my:module:FooResource::child
```

The problem is due to:

https://github.com/pulumi/pulumi/blob/117955ce14b6cf2dd093f8356ec7e26427aca4bf/pkg/resource/deploy/step_generator.go#L370-L382

... and:

https://github.com/pulumi/pulumi/blob/117955ce14b6cf2dd093f8356ec7e26427aca4bf/sdk/go/common/resource/alias.go#L24-L26

Because the alias spec doesn't have `Parent` specified, the parent type is not being included the computed alias URN.

Existing tests such as https://github.com/pulumi/pulumi/tree/master/tests/integration/aliases/python/rename_component_and_child didn't catch the problem because the alias specifies both the `name` and `parent`:

https://github.com/pulumi/pulumi/blob/117955ce14b6cf2dd093f8356ec7e26427aca4bf/tests/integration/aliases/python/rename_component_and_child/step2/__main__.py#L15

In this case, specifying `parent` on the alias shouldn't be necessary. However, even after removing `parent` from the alias spec, the test still succeeds because the parent itself has an alias:

https://github.com/pulumi/pulumi/blob/117955ce14b6cf2dd093f8356ec7e26427aca4bf/tests/integration/aliases/python/rename_component_and_child/step2/__main__.py#L18

... and parent aliases are inherited as part of a child's aliases, so we still get an alias that works from the inheritance.

If we change the test to make no changes to the parent such that it doesn't have any aliases, then we get the failure as we'd expect.

A similar problem will happen when retyping a child.

### Fix

The fix involves using the child's parent in the calculated alias URN when `Parent` isn't specified for the alias.

As part of this, we need to properly handled `NoParent` because right now the engine is not correctly using it. The struct representing an alias in the engine does not have a `NoParent` field:

https://github.com/pulumi/pulumi/blob/117955ce14b6cf2dd093f8356ec7e26427aca4bf/sdk/go/common/resource/alias.go#L8-L15

And therefore does not copy it over in the gRPC request:

https://github.com/pulumi/pulumi/blob/117955ce14b6cf2dd093f8356ec7e26427aca4bf/pkg/resource/deploy/source_eval.go#L1082-L1088

Instead, the `Alias` struct has an incorrect `NoParent` method which returns `true` if the `Parent` field has a value of `""`:

https://github.com/pulumi/pulumi/blob/117955ce14b6cf2dd093f8356ec7e26427aca4bf/sdk/go/common/resource/alias.go#L24-L26

## Node.js SDK Bug

The Node.js SDK is not sending the right `Parent` and `NoParent` alias spec fields.

https://github.com/pulumi/pulumi/blob/117955ce14b6cf2dd093f8356ec7e26427aca4bf/sdk/nodejs/runtime/resource.ts#L332-L361

- It's only setting `NoParent` when the alias doesn't have a `Parent` set and the resource doesn't have a parent.
- If the resource has a parent and `Parent` isn't set on the resource, it sends the parent's URN for `Parent`.

Instead:

- It should set `NoParent` when `Parent` is set to `undefined`.
- It should only send `Parent` if the user's alias has specified a `Parent`.

This makes the Node.js SDK behave like the other SDKs.

Fixes #12662

### CODE REVIEW

File: sdk/go/common/resource/alias.go [hunk 1]
```diff
@@ -21,10 +22,6 @@ func (a *Alias) GetURN() URN {
 	return CreateURN(a.Name, a.Type, a.Parent, a.Project, a.Stack)
 }
 
-func (a *Alias) NoParent() bool {
-	return a.Parent == ""
-}
-
```
Comment (justinvp) [inline sdk/go/common/resource/alias.go:27]: Technically, this is a breaking change. However, I think it's worth making the change because it's unlikely anyone else is actually using this directly.

The alternative is to keep the `NoParent` method as-is (potentially marking it as deprecated) and add a new bool field for `NoParent` with some other name.

**Comment by justinvp** [comment]
The engine change fixes the non-Node.js SDKs. For Node.js, if you're using the fixed engine with an old Node.js SDK, or a new Node.js SDK with an old engine, you may see some behavior differences depending on how you're using `Parent` and `NoParent`.

Some possible mitigations:

1. I contemplated keeping around a legacy mode in the engine, which would make it behave the old way, unless an SDK has explicitly indicated that it's using the alias specs the "right way," but the extra complexity likely isn't worth it.

2. Another idea would be to provide an environment variable to opt-out of engine support for calculating aliases. This would work similar to what we do for resource references and output values, i.e. in the `SupportsFeature` gRPC:

    https://github.com/pulumi/pulumi/blob/117955ce14b6cf2dd093f8356ec7e26427aca4bf/pkg/resource/deploy/source_eval.go#L676-L687

    This would allow going back to the old behavior where aliases are computed in the SDK, and could be used as a temporary workaround for any behavior changes for Node.js (or any bug in the engine, for that matter).

Although, the simplest answer would be to just update both your CLI and SDK to the latest version.

File: sdk/go/common/resource/alias.go (hunk 1 above)
Comment (Frassle) [reply sdk/go/common/resource/alias.go:27]: I'm fine with this, most of the things in /common aren't really supposed to be used for public consumption.

**Review by Frassle — APPROVED** [review]

**Comment by justinvp** [comment]
I've pushed some additional commits to maintain behavior for users of the Node.js SDK.

I looked at these two cases:

- New CLI + Old Node.js SDK
- Old CLI + New Node.js SDK

## New CLI + Old Node.js SDK

The new `adopt_component_child` and existing `adopt_into_component` integration tests fail -- the ones that use the `parent: pulumi.rootStackResource` alias.

The mitigation for this is ugly and I initially felt uneasy about it, but it is a practical way to address the issue, and I'm personally OK with it. If the engine detects a `RegisterResource` request is from an old Node.js SDK, it fixes up the incorrect aliases to be correct.

It does this by looking at the gRPC request's metadata headers, specifically looking at the "pulumi-runtime" and "user-agent" headers.

First, if the request has a "pulumi-runtime" header with a value of "nodejs", we know it's coming from the Node.js plugin. The Node.js
language plugin proxies gRPC calls from the Node.js SDK to the resource monitor, and the proxy now sets the "pulumi-runtime" header to "nodejs"
for `RegisterResource` calls.

Second, if the request has a "user-agent" header that starts with "grpc-node-js/", we know it's coming from the Node.js SDK. This is the case for inline programs in the automation API, which connects directly to the resource monitor, rather than going through the language plugin's proxy.

We can't just look at "user-agent", because in the proxy case it will have a Go-specific "user-agent", and it doesn't look like you can modify the "user-agent".

Updated Node.js SDKs set a new `aliasSpecs` field on the `RegisterResource` request, which indicates that the alias specs are correct, and no transforms are needed.

## Old CLI + New Node.js SDK

The new `retype_component_child` and `rename_component_child` integration tests fail. Essentially the same state as the other SDKs.

The mitigation for this is simple. We just have the Node.js SDK continue to set the resource's parent in the alias when the alias itself doesn't have a parent specified. If following the spec correctly, this isn't necessary, but there's no harm in doing it.

**Review by Frassle — APPROVED** [review]
nodejs workarounds are a bit sad but all looks reasonable to keep things working

**Comment by justinvp** [comment]
bors retry
