### PR TITLE
sdk/go: Implement array contravariance in As*ArrayOutput types

### LINKED ISSUE #10977: [go] StringArrayOuput stack output panics when cast as StringArrayOutput from stack reference output
### What happened?

I have 2 stacks and in one of them, I `ctx.Export` a `StringArrayOutput`. In the other stack, I reference the first stack and `GetOutput` and use `AsStringArrayOutput` and the pulumi program panics.

### Steps to reproduce

* Create two golang stacks
* In stack `a`, create a StringArrayOutput and export it using `ctx.Export`
* In stack `b`, `stack.GetOutput("name").AsStringArrayOutput()`

### Expected Behavior

This should be correctly cast since the types are correct.

### Actual Behavior

```
panic: interface conversion: interface {} is []interface {}, not []string
```

### Output of `pulumi about`

_No response_

### Additional context

I worked around this by writing my own `ApplyT` function that works

The following code **works**

```golang
output.ApplyT(func(i interface{}) pulumi.StringArrayOutput {
  array := i.([]interface{})
  strings := make([]string, len(array))
  for i := range array {
    strings[i] = array[i].(string)
  }
  return pulumi.ToStringArray(strings).ToStringArrayOutput()
}).(pulumi.StringArrayOutput)
```

I'm not sure if casting `[]interface{}` to `[]string` is possible in go directly, which is why I'm not opening a pull request, but given that the above works and the existing code doesn't, I feel like it would be a good improvement.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by AaronFriel**
Expands on the As*ArrayOutput methods added in #10085 to permit contravariance. These methods are modified to inspect the type of the argument, if it is an `[]interface{}` and therefore would panic on casting to `[]T`, we try casting the elements of the array item-by-item.

The `generate.go` file is moved to a subdirectory and `//go:build ignore` directives removed as they seemed to interfere with my editor's code completion. 

Resolves #10977.

### CODE REVIEW

File: sdk/go/pulumi/generate/templates/types_builtins.go.template [hunk 1]
```diff
@@ -206,6 +207,30 @@ func getResolvedValue(input Input) (reflect.Value, bool) {
...
+				return nil, nil
+			}
+			out := make([]{{.InnerElementType}}, len(array))
+			for i := range array {
+				value, ok := array[i].({{.InnerElementType}})
+				if !ok {
+					return nil, fmt.Errorf("expected value of type {{.InnerElementType}}, got %T", array[i])
+				}
+				out[i] = value
+			}
```
Comment (iwahbe) [inline sdk/go/pulumi/generate/templates/types_builtins.go.template:227]:
```suggestion
			for i, v := range array {
				value, ok := v.({{.InnerElementType}})
				if !ok {
					return nil, fmt.Errorf("[%d]: expected value of type {{.InnerElementType}}, got %T", i, v)
				}
				out[i] = value
			}
```

**Review by iwahbe — APPROVED** [review]
1 nit, but LGTM

**Comment by AaronFriel** [comment]
bors merge
