### PR TITLE
[codegen/schema] Fix a panic caused by parsing bad examples block in a resource description

### LINKED ISSUE #4950: [Panic] When upgrading to latest codegen in pulumi v2.5.0
```
panic: runtime error: slice bounds out of range [2:1]

goroutine 1 [running]:
github.com/pulumi/pulumi/pkg/v2/codegen/schema.shortcodeParser.parseShortcode(0x0, 0xc0013798cf, 0x1, 0x231, 0x2, 0x250, 0x0, 0xc002058000, 0x0)
	/Users/stack72/code/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.5.1-0.20200701223250-45d2fa95d60b/codegen/schema/docs_parser.go:66 +0x3bc
github.com/pulumi/pulumi/pkg/v2/codegen/schema.shortcodeParser.Continue(0x0, 0x6f49f80, 0xc001f7bad0, 0x6f3ee20, 0xc001edfe30, 0x6f40f20, 0xc001edfea0, 0x231)
	/Users/stack72/code/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.5.1-0.20200701223250-45d2fa95d60b/codegen/schema/docs_parser.go:142 +0xb2
github.com/pgavlin/goldmark/parser.(*parser).parseBlocks(0xc002229500, 0x6f487c0, 0xc001ff6e60, 0x6f3ee20, 0xc001edfe30, 0x6f40f20, 0xc001edfea0)
	/Users/stack72/code/go/pkg/mod/github.com/pgavlin/goldmark@v1.1.33-0.20200616210433-b5eb04559386/parser/parser.go:1072 +0x4fc
github.com/pgavlin/goldmark/parser.(*parser).Parse(0xc002229500, 0x6f3ee20, 0xc001edfe30, 0x0, 0x0, 0x0, 0xc002938d80, 0x402)
	/Users/stack72/code/go/pkg/mod/github.com/pgavlin/goldmark@v1.1.33-0.20200616210433-b5eb04559386/parser/parser.go:848 +0x142
github.com/pulumi/pulumi/pkg/v2/codegen/schema.ParseDocs(0xc001379680, 0x402, 0x480, 0xc001379680, 0x402)
	/Users/stack72/code/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.5.1-0.20200701223250-45d2fa95d60b/codegen/schema/docs_parser.go:173 +0x16d
github.com/pulumi/pulumi/pkg/v2/codegen.FilterExamples(0xc002938d80, 0x402, 0x6765693, 0xa, 0xc000a012b0, 0xc0032bc080)
	/Users/stack72/code/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.5.1-0.20200701223250-45d2fa95d60b/codegen/docs.go:94 +0x93
github.com/pulumi/pulumi/pkg/v2/codegen/nodejs.(*modContext).genResource(0xc001310dd0, 0x6e0c3c0, 0xc00201c7b0, 0xc001846b40, 0x2, 0x2)
	/Users/stack72/code/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.5.1-0.20200701223250-45d2fa95d60b/codegen/nodejs/gen.go:369 +0x8b
github.com/pulumi/pulumi/pkg/v2/codegen/nodejs.(*modContext).gen(0xc001310dd0, 0xc0007fba40, 0x0, 0x0)
	/Users/stack72/code/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.5.1-0.20200701223250-45d2fa95d60b/codegen/nodejs/gen.go:1095 +0x357
github.com/pulumi/pulumi/pkg/v2/codegen/nodejs.GeneratePackage(0x67bf48e, 0x28, 0xc002966120, 0xc00166c1e0, 0xb, 0xc00166c1e0, 0x0)
	/Users/stack72/code/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.5.1-0.20200701223250-45d2fa95d60b/codegen/nodejs/gen.go:1549 +0x4b6
github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfgen.language.emitSDK(0x7ffeefbff8c7, 0x6, 0xc002966120, 0xc0007ab500, 0x675f566, 0x8, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/stack72/code/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.5.3/pkg/tfgen/generate.go:99 +0x28f
github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfgen.(*generator).Generate(0xc000720ea0, 0x8, 0x6da3ed0)
	/Users/stack72/code/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.5.3/pkg/tfgen/generate.go:658 +0x3bd
github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfgen.newTFGenCmd.func1(0xc0002c9080, 0xc000472eb0, 0x1, 0x5, 0x0, 0x0)
	/Users/stack72/code/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.5.3/pkg/tfgen/main.go:78 +0x197
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunFunc.func1(0xc0002c9080, 0xc000472eb0, 0x1, 0x5, 0xc000b1fa08, 0x1b59ce4)
	/Users/stack72/code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.5.1-0.20200701223250-45d2fa95d60b/go/common/util/cmdutil/exit.go:96 +0x51
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc0002c9080, 0xc000472eb0, 0x1, 0x5)
	/Users/stack72/code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.5.1-0.20200701223250-45d2fa95d60b/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc0002c9080, 0xc000070250, 0x5, 0x5, 0xc0002c9080, 0xc000070250)
	/Users/stack72/code/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002c9080, 0x8, 0x6da3ed0, 0xc)
	/Users/stack72/code/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/stack72/code/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfgen.Main(0x675f566, 0x8, 0x6da3ed0, 0xc, 0xc0007ab500, 0x675f566, 0x8, 0x0, 0x0, 0x0, ...)
	/Users/stack72/code/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.5.3/pkg/tfgen/main.go:31 +0xa8
main.main()
	/Users/stack72/code/go/src/github.com/pulumi/pulumi-alicloud/provider/cmd/pulumi-tfgen-alicloud/main.go:24 +0xc1
make: *** [build_nodejs] Error 2
```

The branch is https://github.com/pulumi/pulumi-alicloud/tree/go-examples-2

### PR DESCRIPTION
**Pull request by praneetloke**
Fixes #4950.

While this fixes the panic, the source of the problem is in our schema generation process that incorrectly included a bad example block in the resource description. I'll open a separate issue in the tf bridge repo to fix that.

EDIT: Opened https://github.com/pulumi/pulumi-terraform-bridge/issues/235 to fix the issue in tfgen.

### CODE REVIEW

File: pkg/codegen/schema/docs_parser.go [hunk 1]
```diff
@@ -133,10 +133,12 @@ func (p shortcodeParser) Open(parent ast.Node, reader text.Reader, pc parser.Con
 }
 
 func (p shortcodeParser) Continue(node ast.Node, reader text.Reader, pc parser.Context) parser.State {
-	line, _ := reader.PeekLine()
+	line, seg := reader.PeekLine()
 	pos := pc.BlockOffset()
 	if pos < 0 {
 		return parser.Continue | parser.HasChildren
+	} else if pos > seg.Len() {
+		return parser.Continue | parser.HasChildren
```
Comment (praneetloke) [inline pkg/codegen/schema/docs_parser.go:141]: So intuitively, I wanted to return the `parser.NoChildren` state here, but I have to admit that I don't fully understand the lifecycle of these calls, so I just returned the same state as the first condition in this chain. I would have expected us to return a `parser.NoChildren` state on line 138 too and wasn't sure if that was intentional as a way to keep the parser continue to return nodes.

Comment (pgavlin) [reply pkg/codegen/schema/docs_parser.go:141]: I think that what you have here is correct. The content in the issue didn't look like it was malformed--do you know which line exactly this panicked on?

Comment (praneetloke) [reply pkg/codegen/schema/docs_parser.go:141]: > The content in the issue didn't look like it was malformed--do you know which line exactly this panicked on?

Yeah the resource that it was panicking on is the `alicloud:datahub/topic:Topic` resource. Here's the example snippet from that resource's description. Note that the example syntax still looks like HCL.

> {{% examples %}}\n## Example Usage\n\nBasic Usage\n\n- BLob Topic\n\n \nresource \"alicloud_datahub_topic\" \"example\" {\n name = \"tf_datahub_topic\"\n project_name = \"tf_datahub_project\"\n record_type = \"BLOB\"\n shard_count = 3\n life_cycle = 7\n comment = \"created by terraform\"\n}\n \n- Tuple Topic\n\n \nresource \"alicloud_datahub_topic\" \"example\" {\n name = \"tf_datahub_topic\"\n project_name = \"tf_datahub_project\"\n record_type = \"TUPLE\"\n record_schema = {\n bigint_field = \"BIGINT\"\n timestamp_field = \"TIMESTAMP\"\n string_field = \"STRING\"\n double_field = \"DOUBLE\"\n boolean_field = \"BOOLEAN\"\n }\n shard_count = 3\n life_cycle = 7\n comment = \"created by terraform\"\n}\n \n{{% /examples %}}

Comment (pgavlin) [reply pkg/codegen/schema/docs_parser.go:141]: Right, but do you know which line exactly it panicked on? That example is multiple lines.

Comment (praneetloke) [reply pkg/codegen/schema/docs_parser.go:141]: Ah yeah. I don't know that. I can find out. Regardless of that, though, shouldn't that example be omitted from the schema because it seems to have failed conversion?

Comment (pgavlin) [reply pkg/codegen/schema/docs_parser.go:141]: > Regardless of that, though, shouldn't that example be omitted from the schema because it seems to have failed conversion?

Yes, it should have (assuming that it did fail conversion)--I was wondering about the line so that I could better understand the fix.

Comment (praneetloke) [reply pkg/codegen/schema/docs_parser.go:141]: Roger that. I'll look that up and post it in the new issue that I'll open for fixing the example conversion code.

Comment (praneetloke) [reply pkg/codegen/schema/docs_parser.go:141]: @pgavlin I opened an issue for the issue of non-converted example being included in the schema accidentally.

As for the panic that this PR fixes, it seems to be caused when the parser encounters a whitespace character after the second new-line character after `- Tuple Topic`.

Comment (praneetloke) [reply pkg/codegen/schema/docs_parser.go:141]: @pgavlin if there is no other concern with the change in this PR, I'll go ahead and merge this.

Comment (pgavlin) [reply pkg/codegen/schema/docs_parser.go:141]: Yep, this is ready to go (I signed off)
