### PR TITLE
Fix provider registry race condition in parallel delete-before-replace

### LINKED ISSUE #20529: An assertion has failed: 'Check' and 'Diff' must be called before 'Update'
### Describe what happened

I got the error below after upgrading `@pulumi/kubernetes` from `4.21.1` to `4.22.0`, and running an update that removes some kubernetes resources. Same happens with `4.22.1` and `4.23.0`. The exact versions do not appear to be important, but rather just the act of switching between versions, along with replacing some resources.

~This was with `@pulumi/pulumi` ~`3.153.1`~ `3.162.0`, and upgrading to `3.194.0` resolves the issue. Alternatively, on `3.162.0`, it also works if I first do an update that only changes the `@pulumi/kubernetes` version, and then remove the resources.~
 
```
panic: fatal: An assertion has failed: 'Check' and 'Diff' must be called before 'Update' (urn:pulumi:<redacted>::pulumi:providers:kubernetes::eks-provider)
```

~Since there are workarounds for the issue, I'm just posting this as an FYI in case others run into the same issue.~

After this error, the pulumi program completely "crashes". The operation stays "pending" on Pulumi cloud, until I manually cancel it.

### Sample program

Version 1: https://gist.github.com/rkistner/5aef3433d83fadc0b491c4f6a1e73970
Version 2: https://gist.github.com/rkistner/f30987de8a0f22940649f2ac93cf1549

The are two "versions" of the same program, simulating the type of update I'm making in my production system.

It is not consistent, but repeatedly switching between these two and running `pulumi up --skip-preview` eventually reproduces the issue for me. It appears to depend on timing though.

This is not quite a minimal example, but I'm struggling to make it even smaller due the issue not being consistent.

### Log output

```
    pulumi:pulumi:Stack <redacted> running read pulumi:pulumi:StackReference cluster-stack
@ Updating.....................
    pulumi:pulumi:Stack <redacted> running read pulumi:pulumi:StackReference cluster-stack
@ Updating....
 ~  pulumi:providers:kubernetes eks-provider updating (0s) [diff: ~version]
 err?: Error: Command failed with exit code 2: pulumi up --yes --skip-preview --color always --client=127.0.0.1:37729 --exec-kind auto.inline --event-log /tmp/automation-logs-up-ZBFZnq/eventlog.txt --stack <redacted> --non-interactive
panic: fatal: An assertion has failed: 'Check' and 'Diff' must be called before 'Update' (urn:pulumi:<redacted>::pulumi:providers:kubernetes::eks-provider)

goroutine 166 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
	github.com/pulumi/pulumi/sdk/v3@v3.190.0/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0xa0?, {0x2dfd6d9?, 0x65?}, {0xc0027b17e8?, 0xc?, 0x2b3d180?})
	github.com/pulumi/pulumi/sdk/v3@v3.190.0/go/common/util/contract/assert.go:35 +0xe8
github.com/pulumi/pulumi/pkg/v3/resource/deploy/providers.(*Registry).Update(0xc0026caa50, {0x352a1d8, 0x4cd9700}, {{0xc00232d0a0, 0x65}, {0xc00232d0f9, 0xc}, {0xc00232d0dc, 0x1b}, {0xc002596c30, ...}, ...})
	github.com/pulumi/pulumi/pkg/v3/resource/deploy/providers/registry.go:836 +0x32d
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*UpdateStep).Apply(0xc0027d6280)
	github.com/pulumi/pulumi/pkg/v3/resource/deploy/step.go:826 +0x58b
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).continueExecuteStep(0xc002702000, {0x28582a0, 0xc00141a6b8}, 0x1f, {0x353b258, 0xc0027d6280})
	github.com/pulumi/pulumi/pkg/v3/resource/deploy/step_executor.go:468 +0x191
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeStep(0xc002702000?, 0x1f?, {0x353b258?, 0xc0027d6280?})
	github.com/pulumi/pulumi/pkg/v3/resource/deploy/step_executor.go:461 +0x225
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0xc002702000, 0x1f, {0xc0021cf330?, 0x23?, 0x0?})
	github.com/pulumi/pulumi/pkg/v3/resource/deploy/step_executor.go:379 +0xe5
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker(0xc002702000, 0x1f, 0x0)
	github.com/pulumi/pulumi/pkg/v3/resource/deploy/step_executor.go:658 +0x31d
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.newStepExecutor in goroutine 95
	github.com/pulumi/pulumi/pkg/v3/resource/deploy/step_executor.go:708 +0x1ca
```

### Affected Resource(s)

_No response_

### Output of `pulumi about`

```
CLI          
Version      3.191.0
Go Version   go1.25.0
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  kubernetes  4.23.0
resource  kubernetes  4.21.1
language  nodejs      3.191.0
resource  random      4.18.3

Host     
OS       ubuntu
Version  24.04
Arch     x86_64

This project is written in nodejs: executable='/run/user/1000/fnm_multishells/138297_1757601665549/bin/node' version='v18.15.0'

Current Stack: <redacted>/pulumi-test/dev

TYPE                                        URN
pulumi:pulumi:Stack                         urn:pulumi:dev::pulumi-test::pulumi:pulumi:Stack::pulumi-test-dev
pulumi:providers:random                     urn:pulumi:dev::pulumi-test::pulumi:providers:random::default_4_18_3
pulumi:providers:kubernetes                 urn:pulumi:dev::pulumi-test::pulumi:providers:kubernetes::kubernetes-provider
kubernetes:core/v1:Namespace                urn:pulumi:dev::pulumi-test::kubernetes:core/v1:Namespace::test-namespace
random:index/randomPassword:RandomPassword  urn:pulumi:dev::pulumi-test::random:index/randomPassword:RandomPassword::mypwd
kubernetes:core/v1:Secret                   urn:pulumi:dev::pulumi-test::kubernetes:core/v1:Secret::test-config
kubernetes:core/v1:Secret                   urn:pulumi:dev::pulumi-test::kubernetes:core/v1:Secret::test-config-2
kubernetes:core/v1:Pod                      urn:pulumi:dev::pulumi-test::kubernetes:core/v1:Pod::test-pod-2
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by joeduffy**
@justinvp @Frassle I noticed this was a bit past SLO, but that you both seemed to have tracked down the root cause. I was curious if Claude could help us code up a fix. This does solve the issue (I had it write a test, prove that it fails deterministically, and then prove the fix corrects the issue). I'm unsure if it's precisely what you had in mind, however.

In summary:

When a provider update runs in parallel with a delete-before-replace operation, calculateDependentReplacements may try to load the old provider from state via EnsureProvider→Same while the provider's Check→Diff→Update flow is in progress. Both code paths were racing for the UnconfiguredID entry in the registry, causing a panic: "'Check' and 'Diff' must be called before 'Update'".

As Fraser identified: "One is the update step that wants to configure it with the latest config from the program, and the other is the step gen that just wants to load whatever is in state... we just need to allow registry to load the provider from state as a separate instance without clashing with the one also being registered in full."

This fix adds a `fromCheck` parameter to Registry.Same():
  - fromCheck=true: Called from SameStep.Apply after Check→Diff, safe to reuse the UnconfiguredID provider
  - fromCheck=false: Called from EnsureProvider for dependency diffing, loads a fresh provider instance from state without touching UnconfiguredID

This allows both flows to operate independently without racing for shared state.

Fixes https://github.com/pulumi/pulumi/issues/20529

### CODE REVIEW

File: pkg/engine/lifecycletest/delete_before_replace_test.go [hunk 1]
```diff
@@ -940,3 +941,150 @@ func TestDBRParallel(t *testing.T) {
...
+	}
+
+	loaders := []*deploytest.ProviderLoader{
+		deploytest.NewProviderLoader("pkgA", semver.MustParse("1.1.1"), func() (plugin.Provider, error) {
+			return newPkgAProvider(), nil
+		}),
+		deploytest.NewProviderLoader("pkgA", semver.MustParse("1.2.1"), func() (plugin.Provider, error) {
+			return newPkgAProvider(), nil
+		}),
+		// Provider B has a resource where changing "length" triggers delete-before-replace
```
Comment (Frassle) [inline pkg/engine/lifecycletest/delete_before_replace_test.go]: It's setting replace in the diff result, but not DBR.

**Comment by Frassle** [comment]
I'm not totally sure things are correct here even with the change to load fresh when not in a normal Check flow. Doesn't registry still have an issue that a provider might change configuration but not enough to change ID. If the EnsureProvider runs first it's going to save that ID and old configuration in the map. When the provider actually registers properly later on I think it will replace that, but I'm not sure the existing process started up is going to continue to be tracked and shutdown properly.

**Review by Frassle — APPROVED** [review]
