### PR TITLE
Fix panic in 'pulumi console' when no stack is selected.

### LINKED ISSUE #9594: pulumi console bug
### What happened?

trying to debug a failed `pulumi up` command had an error, I got:

```
$ pulumi console
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.32.1
Go Version:       go1.18.1
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/Cellar/go/1.18.1/libexec/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
        /private/tmp/pulumi-20220505-19557-gn7isw/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x557d600, 0x6970120})
        /usr/local/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838 +0x207
main.newConsoleCmd.func1(0x0?, {0x8010106?, 0x0?, 0xc00091fd60?})
        /private/tmp/pulumi-20220505-19557-gn7isw/pkg/cmd/pulumi/console.go:72 +0x16b
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunFunc.func1(0xc?, {0x69cdb98?, 0xc00091fd78?, 0x41fd825?})
        /private/tmp/pulumi-20220505-19557-gn7isw/sdk/go/common/util/cmdutil/exit.go:96 +0x26
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000a20500?, {0x69cdb98, 0x0, 0x0})
        /private/tmp/pulumi-20220505-19557-gn7isw/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc000a20500, {0x69cdb98, 0x0, 0x0})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000946a00)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /private/tmp/pulumi-20220505-19557-gn7isw/pkg/cmd/pulumi/main.go:48 +0x45
```

The failed `pulumi up` command resulted in:
```
error: failed to complete update: [403] The provided update token has expired.
```

### Steps to reproduce

not sure

### Expected Behavior

pulumi console to come up

### Actual Behavior

Runtime Error, see above

### Versions used

```
pulumi about                                       
CLI          
Version      3.32.1
Go Version   go1.18.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.4.0
eks         0.39.0
kubernetes  3.19.1
python      unknown

Host     
OS       darwin
Version  12.3.1
Arch     x86_64

This project is written in python (/usr/bin/python3 v3.8.9)

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aterrel
User           aterrel
Organizations  aterrel

NAME        VERSION
pip         22.1
pulumi-eks  0.39.0
setuptools  62.2.0
wheel       0.37.1

Pulumi locates its logs in /var/folders/6_/dsqvky6j2f3dt2gd2l56sdfc0000gn/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Additional context

Here is the main file:

```
"""An AWS Python Pulumi program"""

import pulumi
import pulumi_eks as eks

cluster = eks.Cluster('my-cluster')

pulumi.export('kubeconfig', cluster.kubeconfig)
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by mikhailshilkov**
# Description

Fixes #9594

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/cmd/pulumi/console.go [hunk 1]
```diff
@@ -64,6 +64,11 @@ func newConsoleCmd() *cobra.Command {
 					if err != nil {
 						return err
 					}
+					if stack == nil {
+						fmt.Println("No stack is currently selected. " +
+							"Please run `pulumi stack select` to select a stack.")
```
Comment (susanev) [inline pkg/cmd/pulumi/console.go:69]:
```suggestion
							"Run `pulumi stack select` to select a stack.")
```

we should try and avoid using please unless we are asking the person to do something inconvenient, or pulumi is at fault.

Comment (mikhailshilkov) [reply pkg/cmd/pulumi/console.go]: Thank you for the tip!

**Review by Zaid-Ajaj — APPROVED** [review]
LGTM
