### PR TITLE
Iwahbe/7881/thread replace on chages through sdks

### LINKED ISSUE #7881: ReplaceOnChanges isn't respected in Go SDK
I'm trying to cause pulumi recreate my AKS cluster if the agentPoolProfile vm size has changed.

I tried using `pulumi.ReplaceOnChanges([]string{"agentPoolProfiles[0].vmSize"})` but it seems that it isn't respected at all. This is the error from pulumi:
```
azure-native:containerservice/v20210501:ManagedCluster (aks):
    error: Code="PropertyChangeNotAllowed" Message="Changing property 'agentPoolProfile.vmSize' is not allowed." Target="agentPoolProfile.vmSize"
```

When I try and use `pulumi.IgnoreChanges([]string{"agentPoolProfiles[0].vmSize"})` that seems to work so there must be some issue with ReplaceOnChanges

My pulumi CLI and SDK is v3.11.0 and using Go
azure native sdk is v1.23.1

### LINKED ISSUE #7922: ReplaceOnChanges isn't respected in .NET SDK
Similar to https://github.com/pulumi/pulumi/issues/7881, `ReplaceOnChanges` doesn't seem to work in .NET either. Reported in https://github.com/pulumi/pulumi-azure-native/issues/1117#issuecomment-913243480 and I can reproduce this myself.

I'd expect the option to be set somewhere in [this file](https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/Pulumi/Deployment/Deployment_RegisterResource.cs) but it's not there.

### PR DESCRIPTION
**Pull request by iwahbe**
# Description

We finish threading `replaceOnChanges` through the Go and .NET SDKs. 

Fixes #7922
Fixes #7881

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: sdk/dotnet/Pulumi/Deployment/Deployment_RegisterResource.cs [hunk 1]
```diff
@@ -95,6 +95,7 @@ private static void PopulateRequest(RegisterResourceRequest request, PrepareResu
                 request.AdditionalSecretOutputs.AddRange(customOpts.AdditionalSecretOutputs);
 
             request.IgnoreChanges.AddRange(options.IgnoreChanges);
+            request.ReplaceOnChanges.AddRange(options.ReplaceOnChanges);
```
Comment (iwahbe) [inline sdk/dotnet/Pulumi/Deployment/Deployment_RegisterResource.cs:98]: I would really like conformation here. I have been unable to test through a gRPC version change and don't speak C#.

Comment (iwahbe) [reply sdk/dotnet/Pulumi/Deployment/Deployment_RegisterResource.cs]: Thanks to @t0yv0 and @mikhailshilkov helping me, this has been tested and seems to work!

File: CHANGELOG_PENDING.md [hunk 2]
```diff
@@ -10,3 +10,6 @@
 
 - [cli] Use json.Unmarshal instead of custom parser
   [#7954](https://github.com/pulumi/pulumi/pull/7954)
+
+- [sdk] - Thread replaceOnChanges through Go and .NET
```
Comment (justinvp) [inline CHANGELOG_PENDING.md:14]: Super nitpick, but this could be:

```suggestion
- [sdk/{go,dotnet}] - Thread replaceOnChanges through Go and .NET
```

**Review by justinvp — APPROVED** [review]
LGTM

Any idea why the tests added in #7226 didn't catch this? Are we missing test coverage?

**Comment by iwahbe** [comment]
> Any idea why the tests added in #7226 didn't catch this? Are we missing test coverage?
Because this was a bug in the gRPC connection, I think it would need to be an integration test. I don't see any for `replaceOnChanges`. We are defiantly missing coverage. 

I'm going to merge this now, because we have a user blocked on it. I'll follow up with an issue for code coverage.
