### PR TITLE
Pulumi-language-go and pulumi new now checks go version is at least 1.14.0

### LINKED ISSUE #5724: Plugins not being automatically installed for new Go + AWS projects on Ubuntu 20 Desktop
From https://www.reddit.com/r/devops/comments/jk4lkc/frustrations_with_pulumi_plugins_docs_seem_to_be/

New Go + AWS project on Ubuntu 20 Desktop:

I just signed up for Pulumi and was really impressed at how easy everything was. This was right up until the last step where I ran `pulumi up` and got this error.

```
pulumi:providers:aws (default):     error: no resource plugin 'aws' found in the workspace or on your $PATH
```
 
Nothing on their site seems to explain how to fix this. I already have aws-cli installed and other programs like Terraform amd cloud-nuke work fine with them.

Within five minutes of being frustrated I find myself on their GitHub issues page to find the solution luckily posted by someone having the same issue.

[Issue](https://github.com/pulumi/pulumi/issues/2097) - AWS plugin is not installed and tutorial documentation makes no mention of it

Solution

```
pulumi plugin install resource aws v0.15.0
```

I can't find anything in their docs that say what the latest version is or how to install any other plugins. This is super frustrating because you can't just run pulumi plugin install resource aws because you get an this error

```
error: missing plugin version argument
```

Where is the information about how the pulumi plugins work?

### PR DESCRIPTION
**Pull request by viveklak**
Fixes #5724
This change enforces that the go version is at least 1.14.0 for go projects. 

Now the following error is seen when running `pulumi up` on an incompatible version:
```
# pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/.../dev/previews/...


error: failed to discover plugin requirements: go version must be 1.14.0 or higher (1.13.8 detected)
```

and the following when `pulumi new` is invoked:
```
pulumi new gcp-go

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name: (new-project)
project description: (A minimal Google Cloud Go Pulumi program)
Created project 'new-project'

Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
stack name: (dev)
Created stack 'dev'

gcp:project: The Google Cloud project to deploy into:
Saved config

Installing dependencies...

error: go version must be 1.14.0 or higher (1.13.8 detected)
```

### CODE REVIEW

File: sdk/go/pulumi-language-go/main.go [hunk 1]
```diff
@@ -190,15 +189,23 @@ func (host *goLanguageHost) GetRequiredPlugins(ctx context.Context,
...
+	cmd = exec.Command(gobin, "list", "-m", "-json", "-mod=mod", "all")
 	cmd.Env = os.Environ()
-
-	stdout, err := cmd.Output()
+	stdout, err = cmd.Output()
 	if err != nil {
-		// will err if the project isn't using modules
-		logging.V(5).Infof("GetRequiredPlugins: Error discovering plugin requirements: %s", err.Error())
-		return &pulumirpc.GetRequiredPluginsResponse{}, nil
+		logging.V(5).Infof("GetRequiredPlugins: Error discovering plugin requirements using go modules: %s", err.Error())
```
Comment (viveklak) [inline sdk/go/pulumi-language-go/main.go:207]: Previously returning an empty response essentially silently disabled plugin acquisition for users with glide or dep projects. We can reinstate the behavior if we feel we aren't ready for this breaking change.

**Review by justinvp — APPROVED** [review]
I'm leaning towards continuing to _not_ error on the `go list` command, at least for now.

Aside from that and some nits, LGTM.

**Comment by viveklak** [comment]
> I'm leaning towards continuing to _not_ error on the `go list` command, at least for now.
> 
> Aside from that and some nits, LGTM.

I decided to factor out the version check since I wanted to enforce this on `pulumi new` as well. I have applied the nit improvements you mentioned and have also excluded the "breaking" change. Apologies for the churn but hopefully the change is easy to grok.

**Review by justinvp — APPROVED** [review]
LGTM
