### PR TITLE
ctrl-c should cause Pulumi to call Cancel operation on providers

### LINKED ISSUE #14054: ctrl-c should cause Pulumi to call Cancel operation on providers
### What happened?

I pressed ctrl-c once to gracefully cancel an ongoing update. I expected the provider to receive a `Cancel` RPC call to cancel any in-flight operations ([as designed](https://github.com/pulumi/pulumi/pull/1633)). Instead, Pulumi terminated quickly and did not cancel the in-flight operation.

### Example

An easy way to reproduce the issue is to deploy a Helm release with a slow `Job` resource, see attached for an example.
[issue-2485.zip](https://github.com/pulumi/pulumi/files/12729763/issue-2485.zip)

The `Create` RPC call will block until the `Job` is completed (e.g. after 60 seconds). Meanwhile, press ctrl-c to initiate cancellation. The `Cancel` operation will not be called (as shown by logging or via a debugger).  An unexpected RPC error will also be shown in the diagnostic output:
```
Diagnostics:
  kubernetes:helm.sh/v3:Release (slowchart):
    error: error reading from server: read tcp 127.0.0.1:63010->127.0.0.1:63008: use of closed network connection
```

### Output of `pulumi about`

```
❯ pulumi about
CLI          
Version      3.80.0
Go Version   go1.21.0
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  unknown
yaml        unknown

Host     
OS       darwin
Version  13.5.1
Arch     arm64

This project is written in yaml

Current Stack: eron-pulumi-corp/issue-2485/dev

TYPE                         URN
pulumi:pulumi:Stack          urn:pulumi:dev::issue-2485::pulumi:pulumi:Stack::issue-2485-dev
pulumi:providers:kubernetes  urn:pulumi:dev::issue-2485::pulumi:providers:kubernetes::default


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/eron-pulumi-corp
User           eron-pulumi-corp
Organizations  eron-pulumi-corp, aws-partnership, pulumi

No dependencies found

Pulumi locates its logs in /var/folders/d4/bznc6qv135qc7ngyh8ld56lm0000gn/T/ by default
```

### Additional context

I believe that the root cause is a regression in `v3.40`: https://github.com/pulumi/pulumi/pull/9793/commits/a9ae602867834efc9821abd866ef388c1b051114

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by EronWright**
# Description
Fixes #14054

This PR fixes a problem that the engine cannot forward a cancellation signal to the provider, because the plugin context is already closed. An [earlier commit](https://github.com/pulumi/pulumi/pull/9793/commits/a9ae602867834efc9821abd866ef388c1b051114) made the plugin context be closed too eagerly, with the intent of cancelling plugin installation. This PR attempts to decouple the cancellation of plugin installation from the lifecycle of the plugin context, so that plugin installation may be cancelled during the cancelation phase as opposed to the termination phase. Then, it closes the plugin context in termination phase.

There's an existing test case in the engine lifecycle tests called `TestProviderCancellation`, but it didn't catch the problem because it uses a fake plugin host that behaves differently after being closed. The issue was fixed in https://github.com/pulumi/pulumi/pull/14063 and the test was temporarily disabled. This PR re-enables the test case.

A new test case `TestSourceFuncCancellation` is added to test cancellation of the source func (where plugin installation happens, see [update.go](https://github.com/pulumi/pulumi/pull/14057/files#diff-7d2ca3e83a05073b332435271496050e28466b4f7af8c0c91bbc77947a75a3a2R378)), as this was the original motivation of https://github.com/pulumi/pulumi/pull/9793/commits/a9ae602867834efc9821abd866ef388c1b051114.

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] ~Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version~

### CODE REVIEW

File: pkg/engine/deployment.go [hunk 1]
```diff
@@ -181,12 +183,23 @@ func newDeployment(ctx *Context, info *deploymentContext, opts deploymentOptions
...
+		<-ctx.Cancel.Canceled()
+		logging.V(7).Infof("engine.newDeployment(...): received cancellation signal")
+		cancelFunc()
+	}()
 
 	opts.trustDependencies = proj.TrustResourceDependencies()
 	// Now create the state source.  This may issue an error if it can't create the source.  This entails,
 	// for example, loading any plugins which will be required to execute a program, among other things.
-	source, err := opts.SourceFunc(ctx.BackendClient, opts, proj, pwd, main, projinfo.Root, target, plugctx, dryRun)
+	source, err := opts.SourceFunc(cancelCtx, ctx.BackendClient, opts, proj, pwd, main, projinfo.Root, target, plugctx, dryRun)
```
Comment (EronWright) [inline pkg/engine/deployment.go:202]: A cancelation context is provided to the source func, and is cancelled eagerly, to abort the plugin installation procedure within the source func.  Prior to this PR, the source func would rely on a context based on `plugctx.Request()` (which is canceled when the plugctx is closed, and is too late for our purposes).

File: pkg/engine/query.go [hunk 2]
```diff
@@ -159,6 +153,11 @@ func runQuery(cancelCtx *Context, q QueryInfo, opts QueryOptions) error {
 		}
 	}()
 
+	src, err := newQuerySource(ctx, cancelCtx.BackendClient, q, opts)
+	if err != nil {
+		return err
+	}
+
```
Comment (EronWright) [inline pkg/engine/query.go:160]: This block is moved to be below the goroutine that handles cancelation.

File: pkg/engine/update.go [hunk 3]
```diff
@@ -204,11 +204,11 @@ func Update(u UpdateInfo, ctx *Context, opts UpdateOptions, dryRun bool) (
 func RunInstallPlugins(
 	proj *workspace.Project, pwd, main string, target *deploy.Target, plugctx *plugin.Context,
 ) error {
-	_, _, err := installPlugins(proj, pwd, main, target, plugctx, true /*returnInstallErrors*/)
+	_, _, err := installPlugins(context.Background(), proj, pwd, main, target, plugctx, true /*returnInstallErrors*/)
```
Comment (EronWright) [inline pkg/engine/update.go:207]: Another option here would be to use `plugctx.Request()` as the context, such that `RunInstallPlugins` cancels automatically when the plugctx is closed. I chose not to do that, because `plugctx.Request()` seems to be designed to support cancelation of outstanding RPCs to the plugin (hence the name `Request`).

File: pkg/engine/deployment.go [hunk 4]
```diff
@@ -152,6 +153,7 @@ type deploymentOptions struct {
 
 // deploymentSourceFunc is a callback that will be used to prepare for, and evaluate, the "new" state for a stack.
 type deploymentSourceFunc func(
+	cancel context.Context,
```
Comment (iwahbe) [inline pkg/engine/deployment.go:156]: I would just call this `ctx`, since presumably this context can be used generically. We are just introducing it to allow cancelation.
```suggestion
	ctx context.Context,
```

If you just want to allow cancelation, I would pass in a `chan<- struct`.

File: pkg/engine/deployment.go [hunk 5]
```diff
@@ -181,12 +183,24 @@ func newDeployment(ctx *Context, info *deploymentContext, opts deploymentOptions
...
-	plugctx = plugctx.WithCancelChannel(ctx.Cancel.Canceled())
+
+	// Keep the plugin context open until the context is terminated, to allow for graceful provider cancellation.
+	plugctx = plugctx.WithCancelChannel(ctx.Cancel.Terminated())
+
+	// Set up a goroutine that will signal cancellation to the source if the caller context
+	// is cancelled.
+	cancelCtx, cancelFunc := context.WithCancel(context.Background())
+	go func() {
+		<-ctx.Cancel.Canceled()
```
Comment (iwahbe) [inline pkg/engine/deployment.go:194]: Are we sure that `ctx.Cancel.Canceled` will be called eventually? We don't want to leak the go routine.
CC @Frassle

**Review by iwahbe — COMMENTED** [review]
This looks reasonable to me.

I believe that the test case will cover the engine's plumbing for cancel here.

I'll wait on @Frassle to give final approval for platform.

File: pkg/engine/deployment.go (hunk 5 above)
Comment (EronWright) [reply pkg/engine/deployment.go:194]: It does seem like it is closed eventually, see [here](https://github.com/pulumi/pulumi/blob/f23b83df97d1dc1975fe8867baa1083eeddbbcd6/pkg/backend/httpstate/backend.go#L1284). I believe the call to `plugctx.WithCancelChannel` would likewise leak a goroutine.

Comment (Frassle) [reply pkg/engine/deployment.go:194]: Why do we even need a new context here? `ctx.Cancel.Context()` should cover it, that will trigger when canceled or terminated.

Comment (EronWright) [reply pkg/engine/deployment.go:194]: You're right, my rationale was simply to emit the log line. Do tell if you feel strongly.

Comment (Frassle) [reply pkg/engine/deployment.go:194]: Not strongly, log line could be helpful.

Comment (EronWright) [reply pkg/engine/deployment.go:194]: I tried to make this change, but `ctx.Cancel` doesn't seem to directly provide a `context.Context` ([ref](https://github.com/pulumi/pulumi/blob/f23b83df97d1dc1975fe8867baa1083eeddbbcd6/pkg/util/cancel/context.go#L85)).

**Review by justinvp — APPROVED** [review]
LGTM. Thanks, @EronWright!
