### PR TITLE
[sdk/python] Fix `get_organization` returning `None`

### LINKED ISSUE #18768: `pulumi.get_organization` returns `None` instead of returning org name
### What happened?

In v3.152.0, for at least Python, `pulumi_org = pulumi.get_organization()` returned the organization name related to the program's stack.

In v3.153.0, it returns `None` even if the stack is part of an org.

### Example

```python
import pulumi
import pulumi_pulumiservice
from pulumi import ResourceOptions

pulumi_org = pulumi.get_organization()

# 3.152.0: prints stack's org
# 3.153.0: prints `None`
print("---", pulumi_org, "---")

pulumi_project = pulumi.get_project()

drive_webhook = pulumi_pulumiservice.Webhook(
    "drive-webhook",
    active=True,
    display_name=f"Drive 001",
    organization_name=pulumi_org,
    project_name=pulumi_project,
    stack_name="dev",
    payload_url=f"https://www.pulumi.com/drive?key=abcde",
    opts=ResourceOptions(retain_on_delete=True),
)
```

---

```
# pulumi version
v3.152.0
(.venv) ~/Documents/scratch/aws-py-scratch git:[main]
# pulumi preview
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/team-ce/py-scratch/dev/previews/45d51b67-d6b1-4609-8447-8d08414618b2

     Type                            Name            Plan       Info
 +   pulumi:pulumi:Stack             py-scratch-dev  create     1 message
 +   └─ pulumiservice:index:Webhook  drive-webhook   create     

Diagnostics:
  pulumi:pulumi:Stack (py-scratch-dev):
    --- team-ce ---
```

---

```
# pulumi version
v3.153.0
(.venv) ~/Documents/scratch/aws-py-scratch git:[main]
# pulumi preview
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/team-ce/py-scratch/dev/previews/303f2e28-4967-4c2e-adfe-0b2540b02176

     Type                 Name            Plan       Info
 +   pulumi:pulumi:Stack  py-scratch-dev  create     1 error; 1 message

Diagnostics:
  pulumi:pulumi:Stack (py-scratch-dev):
    --- None ---

    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/rsmith/Documents/scratch/aws-py-scratch/__main__.py", line 17, in <module>
        drive_webhook = pulumi_pulumiservice.Webhook(
            "drive-webhook",
        ...<6 lines>...
            opts=ResourceOptions(retain_on_delete=True),
        )
      File "/Users/rsmith/Documents/scratch/aws-py-scratch/.venv/lib/python3.13/site-packages/pulumi_pulumiservice/webhook.py", line 271, in __init__
        __self__._internal_init(resource_name, *args, **kwargs)
        ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/rsmith/Documents/scratch/aws-py-scratch/.venv/lib/python3.13/site-packages/pulumi_pulumiservice/webhook.py", line 309, in _internal_init
        raise TypeError("Missing required property 'organization_name'")
    TypeError: Missing required property 'organization_name'

Resources:
    + 1 to create
```

### Output of `pulumi about`

```
pulumi about
CLI          
Version      3.153.0
Go Version   go1.24.0
Go Compiler  gc

Plugins
KIND      NAME           VERSION
resource  aws            6.69.0
resource  aws-native     1.24.0
resource  command        1.0.1
resource  pulumiservice  0.29.0
language  python         3.153.0

Host     
OS       darwin
Version  15.3.1
Arch     arm64

This project is written in python: executable='/Users/rsmith/Documents/scratch/aws-py-scratch/.venv/bin/python' version='3.13.2'

Current Stack: team-ce/py-scratch/dev

Found no resources associated with dev

Found no pending operations associated with dev

Dependencies:
NAME                  VERSION
pulumi_aws            6.69.0
pulumi_aws_native     1.24.0
pulumi_command        1.0.1
pulumi_pulumiservice  0.29.0
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
When versions v3.152.0 and earlier of the `pulumi` python SDK are used with v3.153.0 of the CLI, the `pulumi.get_organization()` function returns `None` rather than the expected organization. This is a regression that was introduced by #18595.

This is what's happening: `pulumi-language-python-exec` ships with the CLI. In v3.153.0, it tries to create an instance of `pulumi.runtime.Settings`, passing a new parameter: `root_directory`. However, older versions of the `pulumi` python SDK do not support this parameter. An error is raised, which is caught and we fall back to default values, which doesn't have the `organization`, so it ends up being `None`.

This change fixes the problem in `pulumi-language-python-exec`. We first try to create `Settings` with all possible parameters. If it runs into an error, it falls back to a slower path that inspects the signature of `Settings.__init__` to determine the supported parameters, and then tries to create `Settings` again with only the parameters it supports.

Fixes #18768

### CODE REVIEW

**Review by Frassle — APPROVED** [review]

File: tests/integration/integration_python_test.go [hunk 1]
```diff
@@ -2121,3 +2121,17 @@ func installPythonProviderDependencies(t *testing.T, dir string) {
 	out, err := cmd.CombinedOutput()
 	require.NoError(t, err, "output: %s", out)
 }
+
+// Regression test for https://github.com/pulumi/pulumi/issues/18768
+//
+//nolint:paralleltest // ProgramTest calls t.Parallel()
+func TestOrganization(t *testing.T) {
+	integration.ProgramTest(t, &integration.ProgramTestOptions{
+		Dir:          filepath.Join("python", "organization"),
```
Comment (joeduffy) [inline tests/integration/integration_python_test.go:2130]: Should we add such a test for all languages, just so we don't accidentally break one of the others?

Comment (justinvp) [reply tests/integration/integration_python_test.go:2130]: We should add a better type of test across all languages that would test current CLI + previous SDK, and previous CLI + current SDK. I’ll raise it in the postmortem.

Comment (Frassle) [reply tests/integration/integration_python_test.go:2130]: > We should add a better type of test across all languages that would test current CLI + previous SDK, and previous CLI + current SDK. I’ll raise it in the postmortem.

Yes please! Pretty sure we've had a few bugs of this type over the years. Just running conformance three times would probably cover most of it.
