### PR TITLE
[engine] engine now always targets stack resource during updates

### LINKED ISSUE #12824: error: this should already have a plan from when we called register resources
### What happened?

After upgrading to `3.66.0`, I got an error `error: this should already have a plan from when we called register resources` when previewing update through `pulumi up`.

Downgrading to `3.65.1` let me run without errors.

### Expected Behavior

No error

### Steps to reproduce

1. Upgrade to `3.66.0`
2. Run `pulumi up`
3. Get `error: this should already have a plan from when we called register resources` when previewing update
4. Downgrade to `3.65.1`
5. Run `pulumi up` with no errors

### Output of `pulumi about`

CLI          
Version      3.66.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description

Fixes 2 bugs
* --target not being specified, marked all resources as targeted even though --target-replace was specified
* update plans erroring due to the root stack not being in the update plan.

Fixes #12824 

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/resource/deploy/step_executor.go [hunk 1]
```diff
@@ -185,7 +185,8 @@ func (se *stepExecutor) ExecuteRegisterResourceOutputs(e RegisterResourceOutputs
 			resourcePlan.Goal.OutputDiff = NewPlanDiff(oldOuts.Diff(outs))
 			resourcePlan.Outputs = outs
 		} else {
-			return result.FromError(fmt.Errorf("this should already have a plan from when we called register resources"))
+			return result.FromError(
+				fmt.Errorf("resource should already have a plan from when we called register resources [urn=%v]", urn))
```
Comment (dixler) [inline pkg/resource/deploy/step_executor.go:189]: The error message we received was unclear and should be improved.

File: pkg/resource/deploy/step_generator.go [hunk 2]
```diff
@@ -615,7 +611,25 @@ func (sg *stepGenerator) generateSteps(event RegisterResourceEvent) ([]Step, res
...
+			// Not a replace, so check if the resource is targeted for an update.
+			isTargeted = sg.isTargetedForUpdate(new)
+		} else if !sg.updateTargetsOpt.IsConstrained() {
+			// Not an update, so check if the resource is targeted for a replace.
+			isTargeted = sg.isTargetedReplace(urn)
+		} else {
+			return nil, result.Error(
+				"update is marked constrained, but is not constrained to an update or a replace")
+		}
+	}
```
Comment (dixler) [inline pkg/resource/deploy/step_generator.go:632]: This logic is very miserable because if we add another target option i.e. `--target-foo` the checks will explode combinatorially.

File: pkg/resource/deploy/step_generator.go [hunk 3]
```diff
@@ -304,8 +299,9 @@ func (sg *stepGenerator) GenerateSteps(event RegisterResourceEvent) ([]Step, res
 				urn = s.URN()
 			}
 			if resourcePlan, ok := sg.deployment.newPlans.get(urn); ok {
-				// If the resource is in the plan, add the operation to the plan.
```
Comment (Frassle) [inline pkg/resource/deploy/step_generator.go:307]: This comment is still correct?

File: pkg/resource/deploy/step_generator.go [hunk 4]
```diff
@@ -615,7 +611,25 @@ func (sg *stepGenerator) generateSteps(event RegisterResourceEvent) ([]Step, res
 		return []Step{NewImportStep(sg.deployment, event, new, goal.IgnoreChanges, randomSeed)}, nil
 	}
 
-	isTargeted := sg.isTargetedForUpdate(new)
+	isUserResource := !(providers.IsDefaultProvider(urn) || urn.Type() == resource.RootStackType)
```
[the remark this answers is not in the document]
Comment (Frassle) [reply pkg/resource/deploy/step_generator.go:614]: Why could we not just add `is StackType return true` to `isTargetedForUpdate`?

File: pkg/engine/lifecycletest/update_plan_test.go [hunk 5]
```diff
@@ -1714,3 +1714,148 @@ func TestResoucesTargeted(t *testing.T) {
...
+	loaders := []*deploytest.ProviderLoader{
+		deploytest.NewProviderLoader("pkgA", semver.MustParse("1.0.0"), func() (plugin.Provider, error) {
+			return &deploytest.Provider{}, nil
+		}),
+	}
+
+	// Initial state
+	fooVal := "bar"
+
+	createResB := func(monitor *deploytest.ResourceMonitor) {
```
Comment (Frassle) [inline pkg/engine/lifecycletest/update_plan_test.go:1737]: We'd generally just do a flag and `if flag { createResource }` rather than changing function references.

File: pkg/resource/deploy/step_generator.go [hunk 6]
```diff
@@ -304,8 +299,9 @@ func (sg *stepGenerator) GenerateSteps(event RegisterResourceEvent) ([]Step, res
 				urn = s.URN()
 			}
 			if resourcePlan, ok := sg.deployment.newPlans.get(urn); ok {
-				// If the resource is in the plan, add the operation to the plan.
 				resourcePlan.Ops = append(resourcePlan.Ops, s.Op())
+			} else if !ConstrainedTo(s.Op(), OpSame) {
+				return nil, result.Errorf("Expected a new resource plan for %v", urn)
```
Comment (Frassle) [inline pkg/resource/deploy/step_generator.go:304]: I thought even Sames got recorded to the plan. It's that untargetted resources don't get added to the plan, we should probably check against that here rather than OpSame.

File: pkg/resource/deploy/step_generator.go (hunk 2 above)
Comment (Frassle) [reply pkg/resource/deploy/step_generator.go:632]: Why isn't this just `sg.isTargetedForUpdate(new) || sg.isTargetedReplace(urn)`?

File: pkg/resource/deploy/step_generator.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (dixler) [reply pkg/resource/deploy/step_generator.go:614]: We could. We would also need to add `isTargetedReplace(urn)` in there because of the reply I've added on the weird logic.

File: pkg/resource/deploy/step_generator.go (hunk 3 above)
Comment (dixler) [reply pkg/resource/deploy/step_generator.go:307]: Will add back. Was advised that obvious/redundant comments are bad and I added it last time so, in passing, I thought I'd clean it up.

File: pkg/engine/lifecycletest/update_plan_test.go (hunk 5 above)
Comment (dixler) [reply pkg/engine/lifecycletest/update_plan_test.go:1737]: ack

File: pkg/resource/deploy/step_generator.go (hunk 6 above)
Comment (dixler) [reply pkg/resource/deploy/step_generator.go:304]:
```go
		if sg.deployment.plan != nil {
			if resourcePlan, ok := sg.deployment.plan.ResourcePlans[s.URN()]; ok {
				if len(resourcePlan.Ops) == 0 {
					return nil, result.Errorf("%v is not allowed by the plan: no more steps were expected for this resource", s.Op())
				}
				constraint := resourcePlan.Ops[0]
				// We remove the Op from the list before doing the constraint check.
				// This is because we look at Ops at the end to see if any expected operations didn't attempt to happen.
				// This op has been attempted, it just might fail its constraint.
				resourcePlan.Ops = resourcePlan.Ops[1:]
				if !ConstrainedTo(s.Op(), constraint) {
					return nil, result.Errorf("%v is not allowed by the plan: this resource is constrained to %v", s.Op(), constraint)
				}
			} else {
				if !ConstrainedTo(s.Op(), OpSame) {
					return nil, result.Errorf("%v is not allowed by the plan: no steps were expected for this resource", s.Op())
				}
			}
		}
```

This logic gave me the impression that if a resource is not in the generated plan and is a same, it's ok.

Comment (Frassle) [reply pkg/resource/deploy/step_generator.go:304]: It is ok, it would just be nice to be consistent and either we always elide adding sames to plans, or we always add resource to plans if we've seen them. Having resources that we've seen, but not added into the plan feels like it'll bite us in the future.

File: pkg/resource/deploy/step_generator.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (Frassle) [reply pkg/resource/deploy/step_generator.go:614]: Ah because we need them even for constrained replaces, fair enough.

File: pkg/resource/deploy/step_generator.go (hunk 2 above)
Comment (Frassle) [reply pkg/resource/deploy/step_generator.go:632]: ick, ok something to think about

**Review by Frassle — APPROVED** [review]
Bit odd about the "sometimes adding OpSame to plan, sometimes not" but I'll add that to my todo list.

**Comment by dixler** [comment]
bors merge
