### PR TITLE
Fix filename clashes between resources and functions.

### LINKED ISSUE #10495: Doc Generation - Name Collision occurs when Name of the Module Collides with the Name of a Function or Resource
Output is case sensitive (eg- testModule and TestModule) however this poses a problem for case insensitive file systems.

image (6)

The consequence of this issue is git continuously thinks there are dirty files on the file system.

### PR DESCRIPTION
**Pull request by dixler**
# Description
Docs paths are lowercased so functions and resources may have name clashes. This PR adds behavior to docs generation to prefix docs with `mod`, `res`, `fn` if there is a name conflict between documentation types in that order.

Fixes #10495 

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by cnunciato** [comment]
We should be careful here as it looks like these changes would result in API docs pages living at different URLs, which would result in a whole lot of 404s without a solid redirect strategy.

File: pkg/codegen/docs/gen.go [hunk 1]
```diff
@@ -1757,11 +1757,37 @@ func (mod *modContext) gen(fs codegen.Fs) error {
...
-		p := path.Join(modName, name, "_index.md")
+	seen := map[string]struct{}{}
+
+	addFile := func(name, contents string, prefixes []string) {
+		var namePrefixed string
+		for _, prefix := range prefixes {
+			namePrefixed = prefix + name
+			if _, exists := seen[namePrefixed]; exists {
+				// Unset namePrefixed because it isn't valid.
+				namePrefixed = ""
```
Comment (abhinav) [inline pkg/codegen/docs/gen.go:1768]: Style: Set the variable and then unset it like that is a bit off in terms of flow.
How about:

```go
var found bool
for _, prefix := range prefixes {
  candidate := prefix + name
  if _, exists := seen[candidate]; exists {
    continue
  }
  name = candidate
  found = true
  seen[name] = struct{}
  break
}

if !found {
  return
}
```

The target is set only if the candidate is valid.

(My example doesn't have a namePrefixed because we don't use the original "name" variable again after this point, and the prefixed version effectively replaces it.)

**Review by abhinav — COMMENTED** [review]
This doesn't match what we discussed in Slack, but precedence-based conflict resolution is also reasonable as long as the conflicts can only be across those boundaries. 

However, unless I'm misreading this, we could also see conflicts if two functions both have similar names with different casing: GetName and getName. This will use "fn-getname" for one and "getname" for the other, and I don't know if we have a guarantee that which function gets the prefix is always the same.

**Comment by dixler** [comment]
> However, unless I'm misreading this, we could also see conflicts if two functions both have similar names with different casing: GetName and getName. This will use "fn-getname" for one and "getname" for the other, and I don't know if we have a guarantee that which function gets the prefix is always the same.

From my understanding, this indeterminate behavior already existed, but this PR disambiguates only across module, resource, and function docs.

I think that the number of potential URLs being changed in the registry by this PR could be high and I'm not sure if we want to stack that change in behavior on top of it for the SEO reasons that @cnunciato mentions.

File: pkg/codegen/docs/gen.go [hunk 2]
```diff
@@ -1757,11 +1757,37 @@ func (mod *modContext) gen(fs codegen.Fs) error {
...
+				continue
+			}
+			break
+		}
+		if name != "" && namePrefixed == "" {
+			return
```
[the remark this answers is not in the document]
Comment (dixler) [reply pkg/codegen/docs/gen.go:1774]: Adding a hard failure on this would change the behavior for downstream users of this such as the registry. I'm not sure if we should modify the behavior in this way.

[the remark this answers is not in the document]
Comment (abhinav) [reply pkg/codegen/docs/gen.go:1774]: If we can't fail here, at least a warning is merited.
Silently skipping files will just make these conflicts harder to debug for users.

**Comment by abhinav** [comment]
> I think that the number of potential URLs being changed in the registry by this PR could be high and I'm not sure if we want to stack that change in behavior on top of it [..]

I'm not suggesting we rename all entities.
In Slack, the rough direction we were discussing was:
For all files that conflict, rename and disambiguate them, but only them.
This PR diverges from that slightly in that the first of the files in a conflict group will not be renamed, but the ones that follow will be renamed—provided that they're a different kind (function, module, etc.).
I don't have a strong preference for the originally discussed behavior ("rename all conflicting files") versus what this PR implements right now.

I'm suggesting we increase the scope of this change from the conflict from the original bug report to conflicts in these file names in general.
I suspect it's not much more added complexity to change the conflict resolution code to append a 1, 2, 3 suffix for same-kind conflicts. For example:

```go
seen := make(map[string]struct{})
nameFor := func(name, kind string) (result string) {
    // Always put the final result into the map.
    defer func() { seen[result] = struct{}{} }()

    if _, ok := seen[ok]; !ok {
        return name // no conflict
    }

    name := kind + "-" + name // pkg-foo
    if _, ok := seen[ok]; !ok {
        return name
    }

    // Still conflicts.
    // Might have "FooBar" and "Foobar" in the same package.
    i := 2
    for {
        candidate := name + strconv.Itoa(i)
        if _, ok := seen[candidate]; !ok {
            return candidate
        }
        i++
    }
}
```

This will guarantee a unique lower case name for all cases—no possibility of error (which also makes the other error discussion moot).
If there's no conflict, the original name is preferred.
If there's a cross-kind conflict, pkg-foo, fn-foo is preferred.
If there's an in-kind conflict, the first will use fn-foo, and the next fn-foo1, fn-foo2, and so on.

The last piece for this conflict resolution is this: deterministic ordering.
You already implemented cross-kind determinism: module, resource, function.
I'm suggesting we also need to handle in-kind determinism.
To do that, we just need a guarantee that the iteration order of `mod.resources` and `mod.functions` is fixed.
If we don't have that guarantee from our input contract, then we can enforce it by sorting them before iterating.
e.g.:

```go
resources := mod.resources
sort.Slice(resources, func(i, j int) bool {
  return resourceName(resources[i]) < resourceName(resources[j])
})
for _, r := range resources {
  // ...
```

This will guarantee that we always generate files for resources in a fixed order,
so we always encounter conflicting lower case names in the same order,
and so we always resolve them to the same unique names.

**Comment by dixler** [comment]
> I suspect it's not much more added complexity to change the conflict resolution code to append a 1, 2, 3 suffix for same-kind conflicts. For example:
I like this change, but it suffers from the potential for a provider upgrade inserting a new conflict and changing the ordering.

```
foobar -> foobar-1 -> foobar-1
fooBar -> foobar-2 -> foobar-2
          // New resource was added in a provider upgrade and changes th
          Foobar     ->  foobar-3 // foobar-3 URL now goes from FooBar to Foobar.
FooBar -> foobar 3 -> foobar-4
```

I think it's worth adding the log message and postponing this until we're aware of a user running into this issue because this does make decisions around API and registry docs.

**Comment by Frassle** [comment]
> I think it's worth adding the log message and postponing this until we're aware of a user running into this issue for same-kind conflicts because this does make decisions around API and registry docs URL naming

I'm happy with postponing that part of the change. By rights schema's shouldn't even allow functions or types to differ just on case (and mine and Daniels idea for new naming system would enforce that).

File: pkg/codegen/testing/test/testdata/docs-collision/schema.json [hunk 3]
```diff
@@ -0,0 +1,43 @@
+{
```
Comment (Frassle) [inline pkg/codegen/testing/test/testdata/docs-collision/schema.json:1]: Should add a conflicting module to this as well to check that also works as expected

File: pkg/codegen/testing/test/testdata/docs-collision/docs/_index.md [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+
+<h2 id="resources">Resources</h2>
+<ul class="api">
+    <li><a href="overlay/" title="Overlay"><span class="api-symbol api-symbol--resource"></span>Overlay</a></li>
+    <li><a href="provider/" title="Provider"><span class="api-symbol api-symbol--resource"></span>Provider</a></li>
+</ul>
+
+<h2 id="functions">Functions</h2>
+<ul class="api">
+    <li><a href="overlay/" title="Overlay"><span class="api-symbol api-symbol--function"></span>Overlay</a></li>
```
Comment (Frassle) [inline pkg/codegen/testing/test/testdata/docs-collision/docs/_index.md:22]: This href is wrong, it should be fn-overlay given the conflict.

File: pkg/codegen/docs/gen.go [hunk 5]
```diff
@@ -1757,11 +1757,40 @@ func (mod *modContext) gen(fs codegen.Fs) error {
...
 
+	// Generate the index files.
+	idxData := mod.genIndex()
+	buffer := &bytes.Buffer{}
+	err := dctx.templates.ExecuteTemplate(buffer, "index.tmpl", idxData)
+	if err != nil {
+		return err
+	}
+
+	addFile("", buffer.String(), []string{"", "mod-"})
```
Comment (Frassle) [inline pkg/codegen/docs/gen.go:1792]: Given the check for seen by name (here "") I can't see how this would ever register a conflict, but the bug report raised for this was explicitly about a conflicting module and resource. Feels like we've missed something to cover that.

**Comment by abhinav** [comment]
> I think it's worth adding the log message and postponing this until we're aware of a user running into this issue for same-kind conflicts because this does make decisions around API and registry docs URL naming

That sounds like a plan.
We can defer trying to solve all conflicts until folks actually run into it.

> By rights schema's shouldn't even allow functions or types to differ just on case (and mine and Daniels idea for new naming system would enforce that).

👍

**Review by dixler — COMMENTED** [review]
naming is hard, but I'm more concerned about:
1. approach
2. correctness/writing tests
3. tidying up the names

This is a 2000+ line file with globals.

File: pkg/codegen/docs/gen.go [hunk 6]
```diff
@@ -1753,61 +1757,194 @@ func (mod *modContext) getModuleFileName() string {
...
+		if _, exists := r.seen[candidate]; exists {
+			continue
+		}
+		r.seen[candidate] = struct{}{}
+		r.dctx.moduleConflictLinkMap[item] = candidate
+		return candidate
+	}
+
+	glog.Error("skipping unresolvable duplicate file name: ", name)
+	return ""
```
Comment (Frassle) [inline pkg/codegen/docs/gen.go:1800]: We don't actually check getSafeName for it returning "". Should this just do the current behavior of the clashing name.

File: pkg/codegen/docs/gen.go [hunk 7]
```diff
@@ -1753,61 +1757,201 @@ func (mod *modContext) getModuleFileName() string {
...
+		p := path.Join(modName, safeName, "_index.md")
 		fs.Add(p, []byte(contents))
 	}
 
-	// Resources
-	for _, r := range mod.resources {
-		data := mod.genResource(r)
+	// Generate the index files.
+	var idxData indexData
+	{
```
Comment (abhinav) [inline pkg/codegen/docs/gen.go:1821]: This function doesn't have much else besides what's in this block.
We don't need to nest the core logic like this.
We can declare idxData at the bottom where it's first needed.

File: pkg/codegen/docs/gen.go [hunk 8]
```diff
@@ -1959,10 +1930,69 @@ func (mod *modContext) genIndex() indexData {
...
+	Resources      []indexEntry
+	Modules        []indexEntry
+	PackageDetails packageDetails
+}
+
+// indexEntrySorter implements the sort.Interface for sorting
+// a slice of indexEntry struct types.
+type indexEntrySorter struct {
+	entries []indexEntry
+}
```
Comment (abhinav) [inline pkg/codegen/docs/gen.go]: I know this is from before but two things:
When this was needed, it didn't need to be a struct.
It is no longer needed: sort.Slice exists.

**Review by abhinav — APPROVED** [review]
The underlying logic is a bit messy, but this change looks fine.

File: pkg/codegen/docs/gen.go (hunk 6 above)
Comment (abhinav) [reply pkg/codegen/docs/gen.go:1807]: Oh, good point. I missed this. @dixler I think each `getSafeName` should continue the loop if empty.

File: pkg/codegen/testing/test/testdata/docs-collision/schema.json (hunk 3 above)
Comment (dixler) [reply pkg/codegen/testing/test/testdata/docs-collision/schema.json:1]: look good?

File: pkg/codegen/docs/gen.go [hunk 9]
```diff
@@ -1753,61 +1757,201 @@ func (mod *modContext) getModuleFileName() string {
...
+			})
 		}
+		sortIndexEntries(modules)
+
+		// If there are resources in the root, list them.
+		for _, r := range mod.resources {
+			title := resourceName(r)
+			resourceFileName := getResourceLink(title)
+
+			safeName := conflictResolver.getSafeName(resourceFileName, r)
```
[the remark this answers is not in the document]
Comment (dixler) [reply pkg/codegen/docs/gen.go]: was concerned about a reassignment, but I think this is reasonable.

**Comment by dixler** [comment]
Ok. I've added a comment to better label what `interface{}` is expecting. I've also added a resource with a conflicting module to my docs-collision test. Going to squash and merge. If it looks good to you @Frassle, feel free to `bors merge` it.

File: pkg/codegen/docs/gen.go (hunk 1 above)
Comment (RobbieMcKinstry) [reply pkg/codegen/docs/gen.go]: > similar names with different casing: GetName and getName.
I _feel like_ this pattern of naming doesn't exist in practice (and shouldn't exist in practice) because it's not idiomatic in any supported language. I would expect if someone created a provider with these names in the schema, we should encourage them to get a little more creative with their names. I would expect we could issue guidance around naming conventions in the schema to mitigate this concern.

Just my 2c, feel free to ignore me :)

File: pkg/codegen/docs/gen.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (RobbieMcKinstry) [reply pkg/codegen/docs/gen.go]: Since it's in codegen, I think it's okay if we fail in the registry. If that happens, the Docs team will open a fix or a P1, and we can resolve that before they upgrade.

A warning might also suffice here; does anyone review the logs during registrygen? I think the answer is no. If it were a manual task, then we'd guarantee eyes on the warning.

Again, just my 2c. Not my hill to die on. :)

[the remark this answers is not in the document]
Comment (abhinav) [reply pkg/codegen/docs/gen.go]: Yep, a failure would do too. A warning is slightly extra steps, but it's still more than silence.
Silently ignoring the failure is the only case I'd push back against.

**Comment by cnunciato** [comment]
Before we merge, would y'all object to running a diff of the filesystem before and after a docs build with these changes? Just want to be sure we err on the side of caution is all. I'm happy to take a swing at that now if you think this is close to being done.

File: pkg/codegen/docs/gen.go [hunk 10]
```diff
@@ -1753,167 +1757,142 @@ func (mod *modContext) getModuleFileName() string {
...
+	}
+
 	// If there are submodules, list them.
+	modules := make([]indexEntry, 0, len(mod.children))
 	for _, mod := range mod.children {
 		modName := mod.getModuleFileName()
 		displayName := modFilenameToDisplayName(modName)
+		safeName := conflictResolver.getSafeName(displayName, mod)
+		if safeName == "" {
+			continue // unresolved conflict
```
Comment (Frassle) [inline pkg/codegen/docs/gen.go:1848]: hmm I know this was @abhinav comment but I was more thinking to err on the current behavior of if we get an unresolved conflict write out with the unsafe only differing by case name.
Just means if we do hit this we write out what we used to write out, rather than nothing.
Having said that the chance of hitting this feels _very low_ so I'm not overly fussed about changing it unless someone thinks my very low probability is actually wrong.

File: pkg/codegen/docs/gen.go [hunk 11]
```diff
@@ -1959,10 +1939,44 @@ func (mod *modContext) genIndex() indexData {
 
 	// If this is the root module, write out the package description.
 	if mod.mod == "" {
-		data.PackageDescription = mod.pkg.Description()
+		idxData.PackageDescription = mod.pkg.Description()
 	}
 
-	return data
+	if err := addFileTemplated("", "index.tmpl", idxData); err != nil {
```
Comment (Frassle) [inline pkg/codegen/docs/gen.go:1945]:
```suggestion
	return addFileTemplated("", "index.tmpl", idxData)
```

**Comment by cnunciato** [comment]
If it helps, here's a draft PR (feel free to push to it if you like) that runs a full build based a commit hash from this repo: https://github.com/pulumi/docs/pull/8787

**Comment by dixler** [comment]
bors merge
