### PR TITLE
Consolidated Target parameters

### LINKED ISSUE #6422: Unable to specify --target when previewing a deletion
## Expected behavior
The ability to specify a target when previewing a deletion operation.

```
pulumi preview --json --stack preview-delete --target "urn:pulumi:preview-delete::preview-delete::gcp:compute/network:Network::test"
```

## Current behavior
Currently the preview command fails with error of the following form:

```
Target 'urn:pulumi:preview-delete::preview-delete::gcp:compute/network:Network::test' could not be found in the stack. Did you forget to escape $ in your shell?\n",
```

For example: 

```json
...
 {
            "op": "delete",
            "urn": "urn:pulumi:preview-delete::preview-delete::gcp:compute/network:Network::test",
            "provider": "urn:pulumi:preview-delete::preview-delete::pulumi:providers:gcp::default::189a0bec-b211-4d18-a4af-8d7b223220e5",
            "oldState": {
                "urn": "urn:pulumi:preview-delete::preview-delete::gcp:compute/network:Network::test", 
                "custom": true,
                "id": "projects/paul-logston/global/networks/test",
                "type": "gcp:compute/network:Network",
                "inputs": {
                    "__defaults": [
                        "deleteDefaultRoutesOnCreate"
                    ],
                    "autoCreateSubnetworks": false, 
                    "deleteDefaultRoutesOnCreate": false,
                    "name": "test"
                },
                "outputs": {
                    "__meta": "{\"e2bfb730-ecaa-11e6-8f88-34363bc7c4c0\":{\"create\":240000000000,\"delete\":240000000000,\"update\":240000000000}}",
                    "autoCreateSubnetworks": false, 
                    "deleteDefaultRoutesOnCreate": false,
                    "description": "",
                    "gatewayIpv4": "",
                    "id": "projects/paul-logston/global/networks/test",
                    "mtu": 0,
                    "name": "test",
                    "project": "paul-logston",
                    "routingMode": "REGIONAL",
                    "selfLink": "https://www.googleapis.com/compute/v1/projects/paul-logston/global/networks/test"
                },
                "parent": "urn:pulumi:preview-delete::preview-delete::pulumi:pulumi:Stack::preview-delete-preview-delete",
                "provider": "urn:pulumi:preview-delete::preview-delete::pulumi:providers:gcp::default::189a0bec-b211-4d18-a4af-8d7b223220e5",
                "propertyDependencies": {
                    "autoCreateSubnetworks": [],
                    "name": []
                }
            },
            "detailedDiff": null
        }
    ],
    "diagnostics": [
        {
            "message": "error: Target 'urn:pulumi:preview-delete::preview-delete::gcp:compute/network:Network::test' could not be found in the stack. Did you forget to escape $ in your shell?\n",
            "severity": "error"
        }
    ],
    "duration": 1640874731,
    "changeSummary": {
        "delete": 1,
        "same": 1
    }
}                                                                     
```

## Steps to reproduce

1. Create a stack named `preview-delete`.
1. Create a main.go file:
```go
package main

import (
	"github.com/pulumi/pulumi-gcp/sdk/v4/go/gcp/compute"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := compute.NewNetwork(ctx, "test", &compute.NetworkArgs{
			Name:                  pulumi.String("test"),
			AutoCreateSubnetworks: pulumi.Bool(false),
		})
		if err != nil {
			return err
		}

		return nil
	})
}
```

3. Run pulumi up to create the vpc/network
4. Comment out the vpc in the main.go file
5. Run the preview command...

```
pulumi preview --json --stack preview-delete --target "urn:pulumi:preview-delete::preview-delete::gcp:compute/network:Network::test"
```

## Context (Environment)

This prevents our team from safely and programmatically running `pulumi up` across a large number of stacks. We need some reassurance that only the resources specified via `--target` will be deleted.

### LINKED ISSUE #13029: `step_generator.go` `--target` postmortem action items
A recent change to `step_generator.go` around `--target`/`--replace`/`--target-replace` caused a lot of issues due to conflicting specification and naming.

Action items
- [x] Consolidate `UpdateTargets, `RefreshTargets`, `DestroyTargets` to a single struct field as they are all using `--target` flag. #13010 

Potential enhancements
- [ ] Rename `ReplaceTargets` to use some word like `Taint`.
- [ ] show changes in sames by default.

Associated `--target` issues:
- [ ] https://github.com/pulumi/pulumi/issues/8562
- [x] https://github.com/pulumi/pulumi/issues/6422
- [x] https://github.com/pulumi/pulumi/issues/6324
- [ ] https://github.com/pulumi/pulumi/issues/9346
- [ ] https://github.com/pulumi/pulumi/issues/6288
- [ ] https://github.com/pulumi/pulumi/issues/5651
- [ ] https://github.com/pulumi/pulumi/issues/3840
- [ ] https://github.com/pulumi/pulumi/issues/3401

### PR DESCRIPTION
**Pull request by dixler**
# Description

Consolidate `--target` handling internally to deduplicate `DestroyTargets` `RefreshTargets` `UpdateTargets` into a single `Targets` field.

Consequences:
-  this moves pre-update verification of `--target`s existing for destroyed resources into the Destroy command (similar to `--exclude-protected`)
- in the engine, `checkTargets()` now runs before `rebuildBaseState()` mutates the prev Snapshot it was checking
  - Fixes #6422 

Fixes #13029

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works (tests broke on destroy after consolidation and are now fixed).

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/resource/deploy/step_generator.go [hunk 1]
```diff
@@ -619,17 +612,8 @@ func (sg *stepGenerator) generateSteps(event RegisterResourceEvent) ([]Step, res
...
-		if !sg.replaceTargetsOpt.IsConstrained() {
-			// Not a replace, so check if the resource is targeted for an update.
-			isTargeted = sg.isTargetedForUpdate(new)
-		} else if !sg.updateTargetsOpt.IsConstrained() {
-			// Not an update, so check if the resource is targeted for a replace.
-			isTargeted = sg.isTargetedReplace(urn)
-		} else {
-			return nil, result.Error(
-				"update is marked constrained, but is not constrained to an update or a replace")
-		}
```
Comment (dixler) [inline pkg/resource/deploy/step_generator.go:632]: This was misunderstood from the surrounding code.

File: pkg/resource/deploy/step_generator.go [hunk 2]
```diff
@@ -72,15 +69,11 @@ type stepGenerator struct {
 	aliases map[resource.URN]resource.URN
 }
 
-func (sg *stepGenerator) isTargetedUpdate() bool {
-	return sg.updateTargetsOpt.IsConstrained() || sg.replaceTargetsOpt.IsConstrained()
-}
-
```
Comment (dixler) [inline pkg/resource/deploy/step_generator.go:78]: This was incorrect. replaceTargets only indicate that a resource is marked for replace. Targeted updates are different.

File: pkg/resource/deploy/deployment_executor.go [hunk 3]
```diff
@@ -163,28 +162,23 @@ func (ex *deploymentExecutor) Execute(callerCtx context.Context, opts Options, p
...
-	if res := ex.checkTargets(opts.DestroyTargets, OpDelete); res != nil {
+	replaceTargetsOpt := opts.ReplaceTargets
+	if res := ex.checkTargets(opts.ReplaceTargets); res != nil {
 		return nil, res
 	}
 
-	if (updateTargetsOpt.IsConstrained() || replaceTargetsOpt.IsConstrained()) && destroyTargetsOpt.IsConstrained() {
-		contract.Failf("Should not be possible to have both .DestroyTargets and .UpdateTargets or .ReplaceTargets")
-	}
-
```
Comment (dixler) [inline pkg/resource/deploy/deployment_executor.go:179]: When they're all reduced down to the same variable, this case does not occur.

File: pkg/resource/deploy/step_generator.go [hunk 4]
```diff
@@ -619,17 +612,8 @@ func (sg *stepGenerator) generateSteps(event RegisterResourceEvent) ([]Step, res
...
-			isTargeted = sg.isTargetedForUpdate(new)
-		} else if !sg.updateTargetsOpt.IsConstrained() {
-			// Not an update, so check if the resource is targeted for a replace.
-			isTargeted = sg.isTargetedReplace(urn)
-		} else {
-			return nil, result.Error(
-				"update is marked constrained, but is not constrained to an update or a replace")
-		}
+	if sg.opts.Targets.IsConstrained() && isUserResource {
+		isTargeted = sg.isTargetedForUpdate(new)
```
Comment (dixler) [inline pkg/resource/deploy/step_generator.go:616]: This should fix #13001 but I need to add a test.

File: pkg/resource/deploy/deployment_executor.go [hunk 5]
```diff
@@ -159,23 +161,9 @@ func (ex *deploymentExecutor) Execute(callerCtx context.Context, opts Options, p
...
+	if res := ex.checkTargets(opts.ReplaceTargets); res != nil {
 		return nil, res
 	}
-	if res := ex.checkTargets(opts.DestroyTargets, OpDelete); res != nil {
-		return nil, res
-	}
-
-	if (updateTargetsOpt.IsConstrained() || replaceTargetsOpt.IsConstrained()) && destroyTargetsOpt.IsConstrained() {
-		contract.Failf("Should not be possible to have both .DestroyTargets and .UpdateTargets or .ReplaceTargets")
-	}
```
Comment (dixler) [inline pkg/resource/deploy/deployment_executor.go:178]: UpdateTargets and DestroyTargets are now the same and `ex.checkTargets(opts.Target)` will fail if a non-existent resource is specified in Target.

The current approach pushes checking that `--target` values exist on `Destroy` earlier in `cmd/destroy.go` similar to the `--exclude-protected` flag.

File: pkg/resource/deploy/deployment_executor.go [hunk 6]
```diff
@@ -43,25 +42,28 @@ type deploymentExecutor struct {
...
+		deletes = ex.stepGen.deletes
 	}
 
 	hasUnknownTarget := false
 	for _, target := range targets.Literals() {
 		hasOld := olds != nil && olds[target] != nil
 		hasNew := news != nil && news[target]
-		if !hasOld && !hasNew {
+		hasDelete := deletes != nil && deletes[target]
+		if !hasOld && !hasNew && !hasDelete {
```
Comment (dixler) [inline pkg/resource/deploy/deployment_executor.go:63]: deleted resources don't show up in olds. not sure if this is intentional.

File: pkg/cmd/pulumi/destroy.go [hunk 7]
```diff
@@ -222,8 +222,15 @@ func newDestroyCmd() *cobra.Command {
...
 			}
 
-			if len(*targets) > 0 && excludeProtected {
-				return result.FromError(errors.New("You cannot specify --target and --exclude-protected"))
+			if len(*targets) > 0 {
+				if excludeProtected {
+					return result.FromError(errors.New("You cannot specify --target and --exclude-protected"))
+				}
+				if snap != nil {
+					if err := checkTargets(*targets, snap); err != nil {
```
Comment (Frassle) [inline pkg/cmd/pulumi/destroy.go:230]: Can this not still be in the deployment_executor? I'd think refresh ought to have the same check as well really (that's a change in behaviour but like destroy if you tell us to refresh X and it doesn't exist in the snapshot at the start then we know it's not gonna be created by refresh).
Maybe an option next to targets like `CheckTargets` or `TargetsMustExist`?

File: pkg/resource/deploy/deployment.go [hunk 8]
```diff
@@ -56,10 +56,8 @@ type Options struct {
 	Parallel                  int        // the degree of parallelism for resource operations (<=1 for serial).
 	Refresh                   bool       // whether or not to refresh before executing the deployment.
 	RefreshOnly               bool       // whether or not to exit after refreshing.
-	RefreshTargets            UrnTargets // The specific resources to refresh during a refresh op.
-	ReplaceTargets            UrnTargets // Specific resources to replace.
-	DestroyTargets            UrnTargets // Specific resources to destroy.
-	UpdateTargets             UrnTargets // Specific resources to update.
+	Targets                   UrnTargets // If specified, only update specified resources.
```
Comment (Frassle) [inline pkg/resource/deploy/deployment.go:59]:
```suggestion
	Targets                   UrnTargets // If specified, only operate on specified resources.
```

File: pkg/resource/deploy/deployment.go [hunk 9]
```diff
@@ -56,10 +56,8 @@ type Options struct {
...
+	ReplaceTargets            UrnTargets // If specified, replace these resources.
```
Comment (Frassle) [inline pkg/resource/deploy/deployment.go:60]: Should we comment here that if targets is set then ReplaceTargets must be a subset?

File: pkg/resource/deploy/deployment_executor.go (hunk 5 above)
Comment (Frassle) [reply pkg/resource/deploy/deployment_executor.go:178]: See comment in destroy.go about thoughts about moving that check back to here but in a toggled way for just Destroy and Refresh.

File: pkg/resource/deploy/deployment_executor.go (hunk 6 above)
Comment (Frassle) [reply pkg/resource/deploy/deployment_executor.go:63]: This is odd because we call checkTargets before iterating the source so at that point I'd think news and deletes are empty because we haven't actually run the step generator yet?

File: pkg/cmd/pulumi/destroy.go (hunk 7 above)
Comment (dixler) [reply pkg/cmd/pulumi/destroy.go:230]: This has given me the following idea that I'm going to pursue.

I'm going to add a field to the `type deployment struct` to contain a functions `DeploymentPreChecks` and `DeploymentPostChecks` that contains a struct with `Targets` and potentially other future things and pull this logic into `pkg/engine/deployment` which knows whether it's an `update`, `import`, `refresh`, `destroy`, etc.

Everything in `pkg/resource/deploy` is considered as a `deployment` and destroy/update/refresh logic is treated as part of `pkg/engine` and is leaking into it.

## Context

The `deployment_executor` doesn't know the difference between an `update`, `refresh` or a `destroy`.

Destroy and Refresh-ness of an update is based on the SourceFunc in the engine which is not sent to the deployment executor.

The deployment_executor used `DestroyTargets`, `RefreshTargets`, and `UpdateTargets` as a weak way to determine what the caller is doing to verify the legitimacy of the supplied targets.

File: pkg/resource/deploy/deployment_executor.go [hunk 10]
```diff
@@ -278,7 +266,7 @@ func (ex *deploymentExecutor) Execute(callerCtx context.Context, opts Options, p
 	// valid.  We have to do this *after* performing the steps as the target list may have referred
 	// to a resource that was created in one of the steps.
 	if res == nil {
-		res = ex.checkTargets(opts.UpdateTargets, OpUpdate)
+		res = ex.checkTargets(opts.Targets)
```
Comment (dixler) [inline pkg/resource/deploy/deployment_executor.go:269]: https://github.com/pulumi/pulumi/pull/13010/files#r1212056905

@Frassle we're using the call down here to check targets so the step generator has already been run.

It seems to me that we'd want to check after the `stepGenerator` not after the `stepExecutor`, but that's current behavior...

I think adding the PreRunChecks and PostRunChecks functionality to `pkg/engine` would improve this.

**Review by dixler — COMMENTED** [review]
Thanks for the review. Helped my refine my thinking and gave me more to think about :+1:

**Review by dixler — COMMENTED** [review]
Thanks for the review. Helped my refine my thinking and gave me more to think about :+1:

File: pkg/cmd/pulumi/destroy.go (hunk 7 above)
Comment (dixler) [reply pkg/cmd/pulumi/destroy.go:230]: @Frassle on further inspection, this would be a bit more involved and I think we can start with a smaller and safer change.

File: pkg/resource/deploy/deployment_executor.go (hunk 6 above)
Comment (dixler) [reply pkg/resource/deploy/deployment_executor.go:63]: We're now checking deployments after iterating the source. This is to make tests pass since the pre-check is now performed much earlier in a component above the engine similarly to --exclude-protected.

There is some desire to not fail a targeted destroy if a target does not exist.
- https://github.com/pulumi/pulumi/issues/8562

As a sort of, ensure this no longer exists.

**Review by dixler — COMMENTED** [review]
@Frassle I've moved the checks as far down as the engine can be aware of whether it's a `destroy/refresh/update`.

`pkg/engine` knows whether something is an `destroy/refresh/update`
the next layer `pkg/resource/deploy` only sees things as `deployments`

File: pkg/resource/deploy/deployment_executor.go (hunk 6 above)
Comment (Frassle) [reply pkg/resource/deploy/deployment_executor.go:63]: Right yeh ok so this gets called after the update, but it used to be called before the update for destroy/refresh but that's now handled by a copy of this code.
Still really confused why deleted resources aren't in olds? I can't find where we mutate old to remove stuff, the changes to add the `deletes` map here feel like they shouldn't be needed.

File: pkg/engine/deployment.go [hunk 11]
```diff
@@ -343,3 +341,22 @@ func assertSeen(seen map[resource.URN]deploy.Step, step deploy.Step) {
 func isDefaultProviderStep(step deploy.Step) bool {
 	return providers.IsDefaultProvider(step.URN())
 }
+
+func checkTargets(targetUrns deploy.UrnTargets, snap *deploy.Snapshot) error {
```
Comment (Frassle) [inline pkg/engine/deployment.go:345]: Be nice to fold this back down into the engine but I can do that after this merges

File: pkg/resource/deploy/deployment_executor.go (hunk 6 above)
Comment (dixler) [reply pkg/resource/deploy/deployment_executor.go:63]: This seems to explain it

https://github.com/pulumi/pulumi/blob/df02d6ded7c44c8b6251559eaece86c4811cbb9e/pkg/resource/deploy/deployment.go#L401-L404

https://github.com/pulumi/pulumi/blob/df02d6ded7c44c8b6251559eaece86c4811cbb9e/sdk/go/common/resource/resource_state.go#L33

Comment (Frassle) [reply pkg/resource/deploy/deployment_executor.go:63]: Oh those aren't deletes, those are pending deletes... I'm not sure how --targets should handle that 🤔

Comment (dixler) [reply pkg/resource/deploy/deployment_executor.go:63]: I've figured it out. It's because we overwrite ex.deployment.olds.


this is interesting, we replace olds on targeted destroys because of the side effects when running `rebuildBaseState()`  this was added initially for refreshes
https://github.com/pulumi/pulumi/blob/ef69ffba3ab552265577e9878578002e5e9ca9d8/pkg/resource/deploy/deployment_executor.go#L609

some discussion on the earliest addition of this: https://github.com/pulumi/pulumi/pull/1814/files#r212073292

It ended up being run on targeted destroys
https://github.com/pulumi/pulumi/blob/41996a3cbd145fbd1ce865b41a753136223bec1c/pkg/resource/deploy/plan_executor.go#L233-L242

File: pkg/resource/deploy/deployment_executor.go [hunk 12]
```diff
@@ -242,15 +227,23 @@ func (ex *deploymentExecutor) Execute(callerCtx context.Context, opts Options, p
 				}
 
 				if event.Event == nil {
-					res := ex.performDeletes(ctx, updateTargetsOpt, destroyTargetsOpt)
+					// Check targets before performDeletes mutates the initial Snapshot.
+					targetErr := ex.checkTargets(opts.Targets)
+
+					res := ex.performDeletes(ctx, opts.Targets)
```
Comment (dixler) [inline pkg/resource/deploy/deployment_executor.go:233]: This seems related to the side effect that I've commented:
- https://github.com/pulumi/pulumi/issues/8164

**Review by Frassle — APPROVED** [review]
LGTM

**Comment by dixler** [comment]
bors merge
