### PR TITLE
[codegen] Re-enable schema caching for static versioned plugins

### LINKED ISSUE #10970: Performance regression in codegen, cache not used
The assignment to `version` and if condition below result in the cache not being used for plugins in the plugin cache of `~/.pulumi/plugins`:

https://github.com/pulumi/pulumi/blob/5749d112c922b365f6b3fab5295c35d3b0fadb37/pkg/codegen/schema/loader.go#L222-L227

### PR DESCRIPTION
**Pull request by AaronFriel**
This condition prevents us from using any caches in `~/.pulumi/plugins`, defeating the intent of the cache system. If this is load bearing, will need to determine what the right carve-out is to omit caching behavior.

Resolves #10970

### CODE REVIEW

File: pkg/codegen/schema/loader.go [hunk 1]
```diff
@@ -224,7 +224,7 @@ func (l *pluginLoader) loadSchemaBytes(pkg string, version *semver.Version) ([]b
 	}
 
 	// don't ues the cache if there is a valid version
```
Comment (iwahbe) [inline pkg/codegen/schema/loader.go:226]: This comment is now wrong. We can delete it.

File: pkg/codegen/schema/loader.go [hunk 2]
```diff
@@ -224,7 +224,7 @@ func (l *pluginLoader) loadSchemaBytes(pkg string, version *semver.Version) ([]b
...
-	if pluginInfo.SchemaPath != "" && version == nil {
+	if pluginInfo.SchemaPath != "" {
 		schemaBytes, ok := l.loadCachedSchemaBytes(pkg, pluginInfo.SchemaPath, pluginInfo.SchemaTime)
```
Comment (iwahbe) [inline pkg/codegen/schema/loader.go:228]: Can we solve this by encoding path into `SchemaPath` (as set [here](https://github.com/pulumi/pulumi/blob/c082382b04902c82146fcb7b7f4734f80c1d9370/sdk/go/common/workspace/plugins.go#L675))?

I don't want to retrieve a cached schema with the wrong version.

Comment (AaronFriel) [reply pkg/codegen/schema/loader.go:228]: I think the check might just be reversed? Should it be `version != nil`?

Comment (AaronFriel) [reply pkg/codegen/schema/loader.go:227]: I've fixed up the first commit to remove the comment (redundant) and flip the condition.

Comment (iwahbe) [reply pkg/codegen/schema/loader.go:227]: I think the check is because our caching isn't aware of versions. What we need is a cache key that looks like `(name, version)`. If version is `nil`, I think we can allow that to degenerate to `(name, *)`.

Comment (iwahbe) [reply pkg/codegen/schema/loader.go:227]: It is important that `loadSchemaBytes("aws", "4.37.0")` doesn't retrieve the cached result of `loadSchemaBytes("aws", "5.3.0")`. I think thats what the check was there for.

Comment (AaronFriel) [reply pkg/codegen/schema/loader.go:227]: The `deploytest.PluginLoader` uses the schemas hardcoded in the makefile (`schema-aws!4.26.0` -> `aws.json`). The issue wasn't that `loadSchemaBytes` did the wrong thing, it's that the loader returned a schema path that wasn't valid for caching because it ignored versions:

https://github.com/pulumi/pulumi/blob/d93383b235482e63c5a538d583e837eb3d659991/pkg/resource/deploy/deploytest/pluginhost.go#L400-L403

Comment (iwahbe) [reply pkg/codegen/schema/loader.go:227]: Maybe I'm missing something, but I think this will effect more than the loader we use during tests. Non-test codegen doesn't rely on the `deploy test.PluginLoader`.

File: pkg/codegen/schema/loader.go [hunk 3]
```diff
@@ -220,7 +179,12 @@ func LoadPackageReference(loader Loader, pkg string, version *semver.Version) (P
 }
 
 func (l *pluginLoader) loadSchemaBytes(pkg string, version *semver.Version) ([]byte, *semver.Version, error) {
-	if err := l.ensurePlugin(pkg, version); err != nil {
+	err := l.host.InstallPlugin(workspace.PluginSpec{
```
Comment (iwahbe) [inline pkg/codegen/schema/loader.go:182]: 😄

File: pkg/codegen/testing/test/program_driver.go [hunk 4]
```diff
@@ -146,13 +146,6 @@ var PulumiPulumiProgramTests = []ProgramTest{
 		Directory:   "random-pet",
 		Description: "Random Pet",
 	},
-	{
-		Directory:   "aws-resource-options",
```
Comment (iwahbe) [inline pkg/codegen/testing/test/program_driver.go:150]: What is this a duplicate of?

File: pkg/codegen/schema/loader.go (hunk 2 above)
Comment (iwahbe) [reply pkg/codegen/schema/loader.go:202]: Looking at [this change](https://github.com/pulumi/pulumi/blob/aaf6cbcc4fce59aa062acd6adf311bb03a466c87/pkg/resource/deploy/deploytest/pluginhost.go#L413), I think we're good here.

**Review by iwahbe — APPROVED** [review]
This was not a great PR for review 😄, but I think the PR is good. LGTM once tests pass. (if there are substantial changes, please ping me again)

P.S. I think we can get non-versioned schemas cached in the future, but this is good for now.

File: pkg/codegen/testing/test/program_driver.go (hunk 4 above)
Comment (aq17) [reply pkg/codegen/testing/test/program_driver.go:150]: Right it's covered by [TestGenerateProgramVersionSelection](https://github.com/pulumi/pulumi/blob/friel/enable-versioned-cache/pkg/codegen/go/gen_program_test.go#L73)

**Comment by AaronFriel** [comment]
bors merge

**Comment by AaronFriel** [comment]
bors merge
