### PR TITLE
[go/program-gen] Fix using inline invoke expressions inside resources, objects and arrays

### LINKED ISSUE #14064: pulumi convert generates incorrect go code for Terraform's file("") function
### What happened?

Running:
`pulumi convert --from terraform --language go --strict --generate-only `

The `main.tf` has a reference to a file. Here's a code snippet:

```terraform
resource "aws_instance" "example" {
  ami           = "ami-0f3769c8d8429942f"
  instance_type = "t2.micro"             
  tags = {
    Name = "example-instance"
  }
  user_data                   = file("user_data.sh") # <------ BUG OCCURS HERE
  user_data_replace_on_change = true
}
```

### Example

Here's a snippet of the generated `go` code

```go
	example, err := ec2.NewInstance(ctx, "example", &ec2.InstanceArgs{
			Ami:          pulumi.String("ami-0f3769c8d8429942f"),
			InstanceType: pulumi.String("t2.micro"),
			Tags: pulumi.StringMap{
				"name": pulumi.String("example-instance"),
			},
			UserData: std.File(ctx, &std.FileArgs{ // <------ BUG OCCURS HERE
				Input: "user_data.sh",
			}, nil).Result,
			UserDataReplaceOnChange: pulumi.Bool(true),
		})
		if err != nil {
			return err
		}
```

Building the above results in the following error message:

```
go build                                             
# migrate-terraform-pulumi
./main.go:18:14: multiple-value std.File(ctx, &std.FileArgs{…}, nil) (value of type (*std.FileResult, error)) in single-value context
```

The generated go user_data code has an error as std.File returns 2 values but we’re trying to assign a single result to UserData

### Output of `pulumi about`

```pulumi about                                                           
CLI          
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME  VERSION
aws   6.0.4
go    unknown
std   1.4.0

Host     
OS       darwin
Version  13.5.1
Arch     arm64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.21.0 darwin/arm64'
```

### Additional context

Current workaround is to edit the `main.go` code. Following the previous example, we can update the snippet to read:

```go
		userData, err := std.File(ctx, &std.FileArgs{
			Input: "user_data.sh",
		}, nil)
		if err != nil {
			return err
		}
		
		example, err := ec2.NewInstance(ctx, "example", &ec2.InstanceArgs{
			Ami:          pulumi.String("ami-0f3769c8d8429942f"),
			InstanceType: pulumi.String("t2.micro"),
			Tags: pulumi.StringMap{
				"name": pulumi.String("example-instance"),
			},
			UserData:                pulumi.String(userData.Result),
			UserDataReplaceOnChange: pulumi.Bool(true),
		})
		if err != nil {
			return err
		}

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

This PR fixes an issue in Go program where if users are writing invoke expressions inline inside other expressions, then that invoke is extracted into a temporary variable and then later referenced the same way it was used. This is because non-output-versioned invokes cannot be used directly since they return a tuple (InvokeResult, err) so we need to check for the error before proceeding. 

Fixes #14064

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/codegen/testing/test/testdata/inline-invokes-pp/go/inline-invokes.go [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+func main() {
+	pulumi.Run(func(ctx *pulumi.Context) error {
+		invokeLookupVpc, err := ec2.LookupVpc(ctx, &ec2.LookupVpcArgs{
+			Default: pulumi.BoolRef(true),
+		}, nil)
+		if err != nil {
+			return err
+		}
+		_, err = ec2.NewSecurityGroup(ctx, "webSecurityGroup", &ec2.SecurityGroupArgs{
+			VpcId: invokeLookupVpc.Id,
```
Comment (Zaid-Ajaj) [inline pkg/codegen/testing/test/testdata/inline-invokes-pp/go/inline-invokes.go:17]: Something is off here where the expression `invokeLookupVpc.Id` should actually be `pulumi.String(invokeLookupVpc.Id)` not entirely sure why the conversion isn't applied after the extracting the invoke 🤔 this is why go is skipping compilation at the moment

File: pkg/codegen/testing/test/program_driver.go [hunk 2]
```diff
@@ -383,6 +383,11 @@ var PulumiPulumiProgramTests = []ProgramTest{
 		Description: "Regression test for rewriting qoutes in python",
 		Skip:        allProgLanguages.Except("python"),
 	},
+	{
+		Directory:   "inline-invokes",
+		Description: "Tests whether using inline invoke expressions works",
+		SkipCompile: allProgLanguages.Except("go"),
```
Comment (Frassle) [inline pkg/codegen/testing/test/program_driver.go:389]: Shouldn't this be Skipping _just_ Go?

Comment (Zaid-Ajaj) [reply pkg/codegen/testing/test/program_driver.go]: Yeah you are right 😅 updated it ✅

File: pkg/codegen/testing/test/testdata/inline-invokes-pp/go/inline-invokes.go (hunk 1 above)
Comment (Frassle) [reply pkg/codegen/testing/test/testdata/inline-invokes-pp/go/inline-invokes.go:17]: That sounds a lot like the error for https://github.com/pulumi/pulumi/issues/14339

**Review by Frassle — APPROVED** [review]

**Comment by Zaid-Ajaj** [comment]
> That sounds a lot like the error for https://github.com/pulumi/pulumi/issues/14339

@Frassle will look into the fix for this in a separate issue 👍
