### PR TITLE
Fix problem with divergent project names

### LINKED ISSUE #3268: Able to create stack with mismatched project names
The project name (`name` field in `Pulumi.yaml`) is part of a stack's identity, so it is important that you cannot change it willy nilly. For example, if you edit the `Pulumi.yaml` file and then run `pulumi up`, you will get an error. (Because that would change the stack's identity, etc.)

However, it's possible to provide two different values to the Pulumi Service for the stack's project name. You can do this by passing in a qualified stack name with a project name when running `pulumi new` or `pulumi stack init`.

Once you get into this state, things kinda sorta work, but they shouldn't.

```
# Create a stack named "chrsmith/project-name-beta/dev", which is a qualified
# stack reference with project name "project-name-beta".
# 
# But we passed in a project name "project-name-alpha".
$ pulumi new javascript --name project-name-alpha --stack chrsmith/project-name-beta/dev --description "..." --force
Created project 'project-name-alpha'
...
Your new project is ready to go! ✨

To perform an initial deployment, run 'pulumi up'

# stack ls doesn't show anything, because no stacks match the project name
# from Pulumi.yaml (which is "project-name-alpha").
$ pulumi stack ls
NAME  LAST UPDATE  RESOURCE COUNT  URL

# Project name is supposedly "project-name-alpha"
$ pulumi stack tag ls
NAME                VALUE
gitHub:owner        chrsmith
pulumi:description  ...
pulumi:project      project-name-alpha
pulumi:runtime      nodejs
```

### PR DESCRIPTION
**Pull request by chrsmith**
A stack is uniquely identified in the Pulumi Service by its organization, project name, and stack name. e.g. `pulumi/www.pulumi.com/production`. When referring to a stack from the command-line we accept several forms of stack identifiers. Defaulting the organization to the user that is currently logged in, and the project to the current workspace (`Pulumi.yaml`).

For example the following are all valid when using `pulumi stack select`:
`production` -> `chrsmith/foo/production`
`pulumi/production` -> `pulumi/foo/production`
`robot-co/other-project/dev` -> `robot-co/other-project/dev`

Now this setup causes problems when a new stack is created, because if we don't verify that the qualified stack identifier ("robot-co/other-project/dev") matches what is in `Pulumi.yaml` ("actual-project"), then bad things happen.

- The stack doesn't show up in `pulumi stack ls`, because the default filter is using the project name from `Pulumi.yaml` but the stack has a _different_ project name.
- The stack isn't grouped properly in the Pulumi Service, since it's project name is different than all of the other ones using the same `Pulumi.yaml` file.
- etc.

We had a recent customer contact us with a `pulumi preview` showing that every resource in the stack was going to be deleted and recreated. Which was rooted in this same issue.

Fixes #3268

### CODE REVIEW

File: pkg/backend/httpstate/backend.go [hunk 1]
```diff
@@ -552,6 +552,13 @@ func (b *cloudBackend) CreateStack(
 		return nil, errors.Wrap(err, "error determining initial tags")
 	}
 
+	// Confirm the stack identity matches the environment. e.g. stack init foo/bar/baz shouldn't work
+	// if the project name in Pulumi.yaml is anything other than "bar".
+	projNameTag, ok := tags[apitype.ProjectNameTag]
+	if ok && stackID.Project != projNameTag {
+		return nil, errors.Errorf("provided project name %q doesn't match Pulumi.yaml", stackID.Project)
```
Comment (pgavlin) [inline pkg/backend/httpstate/backend.go]: Just to be sure--this will cause stack creation to fail?

Comment (chrsmith) [reply pkg/backend/httpstate/backend.go]: Yes. We error out early here before we call ` b.client.CreateStack(ctx, stackID, tags)` next in the function. (Which will then stop `pulumi stack init` and `pulumi new` from proceeding.)

**Comment by chrsmith** [comment]
Friendly ping. Any other feedback or things to change here? Or should I go ahead and submit this?
