### PR TITLE
Escape `${` in string literals

### LINKED ISSUE #11507: Can't import policy with "${aws.username}" in the resource
### What happened?

I try to import a policy where I have resources like:
```
            "Resource": "arn:aws:iam::*:user/${aws:username}"
```

### Steps to reproduce

* Create a policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowManageOwnVirtualMFADevice",
            "Effect": "Allow",
            "Action": [
                "iam:CreateVirtualMFADevice",
                "iam:DeleteVirtualMFADevice"
            ],
            "Resource": "arn:aws:iam::*:mfa/${aws:username}"
        }
    ]
}
```
* try to import this policy

### Expected Behavior

The policy should be imported

### Actual Behavior

I get the error:
```
error: internal error: Error: Extra characters after interpolation expression

  on anonymous.pp line 3:
   4:     policy = "{\"Statement\":[{\"Action\":[\"iam:CreateVirtualMFADevice\",\"iam:DeleteVirtualMFADevice\"],\"Effect\":\"Allow\",\"Resource\":\"arn:aws:iam::*:mfa/${aws:username}\"}],\"Version\":\"2012-10-17\"}"

Template interpolation doesn't expect a colon at this location. Did you intend this to be a literal sequence to be processed as part of another language? If so, you can escape it by starting with "$${" instead of just "${".
```

### Output of `pulumi about`

```
CLI
Version      3.48.0
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.21.1
aws-native  0.42.0
hcloud      1.10.1
kubernetes  3.22.1
python      unknown
random      4.8.2

Host
OS       darwin
Version  11.7.1
Arch     arm64

This project is written in python: executable='/Users/user/.pyenv/shims/python3' version='3.10.8'

Current Stack: user-custom-policies.security

TYPE                   URN
pulumi:pulumi:Stack    urn:pulumi:user-custom-policies.security::user-custom-policies::pulumi:pulumi:Stack::user-custom-policies-user-custom-policies.security
pulumi:providers:aws   urn:pulumi:user-custom-policies.security::user-custom-policies::pulumi:providers:aws::default_5_21_1
aws:iam/policy:Policy  urn:pulumi:user-custom-policies.security::user-custom-policies::aws:iam/policy:Policy::default_user_poilcy


Found no pending operations associated with user-custom-policies.security

Backend
Name           name
URL            file://../
User           user
Organizations

Dependencies:
NAME               VERSION
click              8.1.3
mypy-extensions    0.4.3
pathspec           0.9.0
pip                22.3.1
platformdirs       2.5.2
pulumi-aws         5.21.1
pulumi-aws-native  0.42.0
pulumi-hcloud      1.10.1
pulumi-kubernetes  3.22.1
pulumi-random      4.8.2
setuptools         62.3.2
tomli              2.0.1
typing_extensions  4.3.0

Pulumi locates its logs in /var/folders/f8/f_mdzs9x1m34ytjckb7ykb2c0000gn/T/ by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by iwahbe**
Fixes #11507

### CODE REVIEW

File: pkg/codegen/importer/hcl2_test.go [hunk 1]
```diff
@@ -89,10 +89,14 @@ func renderLiteralValue(t *testing.T, x *model.LiteralValueExpression) resource.
...
-	if !assert.Len(t, x.Parts, 1) {
-		return resource.NewStringProperty("")
+	if len(x.Parts) == 1 {
+		return renderLiteralValue(t, x.Parts[0].(*model.LiteralValueExpression))
 	}
-	return renderLiteralValue(t, x.Parts[0].(*model.LiteralValueExpression))
+	b := ""
+	for _, p := range x.Parts {
+		b += p.(*model.LiteralValueExpression).Value.AsString()
+	}
```
Comment (iwahbe) [inline pkg/codegen/importer/hcl2_test.go:98]: This change is necessary since `"foo$${bar}` is parsed as `[]stringLiteral{"foo", "${", "bar}"}`.

**Review by aq17 — APPROVED** [review]
LGTM! (one question)

File: pkg/codegen/hcl2/model/print_test.go [hunk 2]
```diff
@@ -20,9 +20,22 @@ func TestPrintNoTokens(t *testing.T) {
 						Value: cty.True,
 					},
 				},
+				&Attribute{
+					Name: "literal",
+					Value: &TemplateExpression{
+						Parts: []Expression{
+							&LiteralValueExpression{
+								Value: cty.StringVal("foo${bar}"),
```
Comment (Frassle) [inline pkg/codegen/hcl2/model/print_test.go:28]: What does "foo$" and "foo${" look like? Do they need/not-need escaping?

Comment (aq17) [reply pkg/codegen/hcl2/model/print_test.go:28]: Ah yeah this might require looking ahead and making sure each '{' has a valid '}' later on, possibly also cases such as `foo${bar${baz}` , if this should be `foo$${bar${baz}` or `foo${bar$${baz}` (though seems unlikely to occur)

Comment (Frassle) [reply pkg/codegen/hcl2/model/print_test.go:28]: It looks like only ${ needs handling given https://developer.hashicorp.com/terraform/language/expressions/strings

File: pkg/codegen/hcl2/model/expression.go [hunk 3]
```diff
@@ -1281,16 +1281,39 @@ func literalText(value cty.Value, rawBytes []byte, escaped, quoted bool) string
...
+	// escape special characters
+	s = strconv.Quote(s)
+	s = s[1 : len(s)-1] // Remove surrounding double quote (`"`)
+
+	// Escape `${`
+	runes := []rune(s)
+	out := make([]rune, 0, len(runes))
+	for i, r := range runes {
+		next := func() rune {
+			if i >= len(runes)-2 {
```
[the remark this answers is not in the document]
Comment (iwahbe) [reply pkg/codegen/hcl2/model/expression.go]: We would still want to escape it. We would need to escape it even if the string was `"${"`.
