### PR TITLE
[sdkgen/python] Fix referencing local types with a different package name

### LINKED ISSUE #12624: [codegen] pulumi imports are incorrectly using `pulumi-kubernetes`
### What happened?

A type in a MLC schema file with `kubernetes:...:...` is automatically assumed to be from `pulumi-kubernetes` and is referenced as such in the generated python SDK.

### Expected Behavior

Imports should be generated correctly as in the other languages.

### Steps to reproduce

1. git clone https://github.com/phillipedwards/pulumi-aws-s3-replicated-bucket.git
2. git checkout k8s-python-import
3. make generate
4. open sdk/python/pulumi-aws-s3-replicated-bucket/replicated_bucket.py
5. specifically, look at the import for `from pulumi-kubernetes import gcp as _gcp`
6. also view the `location_policy` getter which utilizes a type which does not exist.

Import statement
https://github.com/phillipedwards/pulumi-aws-s3-replicated-bucket/blob/f08cfb9caaa93cb185021535a2c5d7d4073cd3d3/sdk/python/pulumi_aws_s3_replicated_bucket/replicated_bucket.py#L11

getter function
https://github.com/phillipedwards/pulumi-aws-s3-replicated-bucket/blob/f08cfb9caaa93cb185021535a2c5d7d4073cd3d3/sdk/python/pulumi_aws_s3_replicated_bucket/replicated_bucket.py#L113

### Output of `pulumi about`

CLI          
Version      3.60.1
Go Version   go1.20.2
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
The Python SDK generator wasn't correctly referencing types that have a different package name in their type token than the name of the schema's package (which is the case when embedding k8s CRD resources/types in a package). This change fixes the generator to emit these local references correctly.

Fixes #12624

### CODE REVIEW

File: pkg/codegen/python/gen.go [hunk 1]
```diff
@@ -791,9 +790,6 @@ func (mod *modContext) importObjectType(t *schema.ObjectType, input bool) string
 	}
 
 	importPath := mod.getRelImportFromRoot()
-	if mod.pkg.Name() != parts[0] {
```
Comment (Frassle) [inline pkg/codegen/python/gen.go:794]: If we're not using the package part of the token to determine if it's a local or external import do we need to be checking something else?

Although looking at existing python tests (like the external-enum test) this looks like it's borked anyway because we're getting type annotations to things that don't exist. I guess the python codegen tests don't actually run mypy to check the typing annotations.

Comment (justinvp) [reply pkg/codegen/python/gen.go:794]: > If we're not using the package part of the token to determine if it's a local or external import do we need to be checking something else?

We do the check earlier in the method:

https://github.com/pulumi/pulumi/blob/44f20644839943e0a9bc300213ee98d3e9aa6112/pkg/codegen/python/gen.go#L776-L778

What I'm removing seems to be leftover from a previous attempt to support this. But I did it very late at night so I'm sure I messed some things up. Need to look over the test results.

> Although looking at existing python tests (like the external-enum test) this looks like it's borked anyway because we're getting type annotations to things that don't exist.

Hmm, yeah, `external-enum` test output for Python does look screwed up. I'll take a look as well.

> I guess the python codegen tests don't actually run mypy to check the typing annotations.

We should fix up the compile step to run mypy for these. I'll open a separate issue.

Comment (justinvp) [reply pkg/codegen/python/gen.go:794]: Opened https://github.com/pulumi/pulumi/issues/12694 to track adding mypy checking support (I have a WIP, but will do it as a separate change).

Also opened https://github.com/pulumi/pulumi/issues/12695 about referencing enums.

Comment (justinvp) [inline pkg/codegen/python/gen.go:794]: Note that we handle external imports at the start of the method:

https://github.com/pulumi/pulumi/blob/44f20644839943e0a9bc300213ee98d3e9aa6112/pkg/codegen/python/gen.go#L776-L778

What I'm removing seems to be leftover from a previous attempt to support this, which is causing the problems.

File: pkg/codegen/testing/test/testdata/embedded-crd-types/python/pulumi_foo/component.py [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+# *** WARNING: this file was generated by test. ***
+# *** Do not edit by hand unless you're certain you know what you are doing! ***
+
+import copy
+import warnings
+import pulumi
+import pulumi.runtime
+from typing import Any, Mapping, Optional, Sequence, Union, overload
+from . import _utilities
+from . import crd_k8s_amazonaws_com as _crd_k8s_amazonaws_com
```
Comment (justinvp) [inline pkg/codegen/testing/test/testdata/embedded-crd-types/python/pulumi_foo/component.py:11]: We now import here correctly.

**Review by abhinav — APPROVED** [review]
Generated Python code looks valid, and existing Python code hasn't changed.

**Comment by justinvp** [comment]
bors merge
