### PR TITLE
fix pulumi new selector behaves poorly when lines wrap

### LINKED ISSUE #8169: pulumi new selector behaves poorly when lines wrap
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

The `pulumi new` template selector behaves in weird ways when the terminal is sized such that lines wrap.

### Steps to reproduce

Pulumi version: `v3.13.2` 
Terminal: `iTerm2 3.4.10` 
Shell: `zsh 5.8`

1. Check the terminal window width and height. Make it high, so you can see the weirdness. Any width that causes the lines to wrap (96 cols or less) will cause the issue.
```
❯ tput cols
80
❯ tput lines
33
```
2. Run a `pulumi new` command using the selector:
```
pulumi new --generate-only --force
```
3. Use the up/down keys to toggle between options

Expected: Selector element output is clean
Actual: Toggling between options results in duplicate `Please choose a template` prompts and multiple selector arrows.

### Duplicate prompts
```
Please choose a template:  [Use arrows to move, enter to select, type to filter]
Please choose a template:  [Use arrows to move, enter to select, type to filter]
Please choose a template:  [Use arrows to move, enter to select, type to filter]
Please choose a template:  [Use arrows to move, enter to select, type to filter]
Please choose a template:  [Use arrows to move, enter to select, type to filter]
Please choose a template:  [Use arrows to move, enter to select, type to filter]
Please choose a template:  [Use arrows to move, enter to select, type to filter]
  aws-csharp                   A minimal AWS C# Pulumi program
  aws-go                       A minimal AWS Go Pulumi program
  aws-javascript               A minimal AWS JavaScript Pulumi program
  aws-python                   A minimal AWS Python Pulumi program
  aws-typescript               A minimal AWS TypeScript Pulumi program
> azure-csharp                 A minimal Azure Native C# Pulumi program
  azure-go                     A minimal Azure Native Go Pulumi program
  azure-javascript             A minimal JavaScript Pulumi program with the native Azure provider
  azure-python                 A minimal Azure Native Python Pulumi program
  azure-typescript             A minimal Azure Native TypeScript Pulumi program
```

### Multiple selector arrows
```
  aws-csharp                   A minimal AWS C# Pulumi program
  aws-go                       A minimal AWS Go Pulumi program
  aws-javascript               A minimal AWS JavaScript Pulumi program
> aws-python                   A minimal AWS Python Pulumi program
  aws-typescript               A minimal AWS TypeScript Pulumi program
  azure-csharp                 A minimal Azure Native C# Pulumi program
  azure-go                     A minimal Azure Native Go Pulumi program
Please choose a template:  [Use arrows to move, enter to select, type to filter]
  aws-csharp                   A minimal AWS C# Pulumi program
  aws-go                       A minimal AWS Go Pulumi program
> aws-javascript               A minimal AWS JavaScript Pulumi program
  aws-python                   A minimal AWS Python Pulumi program
  aws-typescript               A minimal AWS TypeScript Pulumi program
  azure-csharp                 A minimal Azure Native C# Pulumi program
  azure-go                     A minimal Azure Native Go Pulumi program
  azure-javascript             A minimal JavaScript Pulumi program with the native Azure provider
```

### PR DESCRIPTION
**Pull request by dixler**
# Description
pulumi new selector behaves poorly when lines wrap. Seems to be a common [issue](https://github.com/AlecAivazis/survey/issues/101) that is fixed by bumping to 2.3.2. I refactored references to survey to use the same procedure that encapsulates mutating the `surveycore.DisableColor` option.

Fixes #8169

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/backend/apply.go [hunk 1]
```diff
@@ -133,12 +132,6 @@ func PreviewThenPrompt(ctx context.Context, kind apitype.UpdateKind, stack Stack
 func confirmBeforeUpdating(kind apitype.UpdateKind, stack Stack,
 	events []engine.Event, opts UpdateOptions) result.Result {
 	for {
-		var response string
-
-		surveycore.DisableColor = true
```
Comment (dixler) [inline pkg/backend/apply.go:138]: This logic is consolidated and moved into `display.go`

**Comment by t0yv0** [comment]
Refactor looking good - moving the shared code into a module. Have you thought about adding a test to the change? It might not be practical here, testing the term display can be nasty. If not practical we can merge if you've tested manually and confirmed working.

**Review by t0yv0 — APPROVED** [review]
