### PR TITLE
Don't call `Diff` when refreshing external resources

### LINKED ISSUE #16401: Pulumi refresh triggers a diff for resources imported with .get
### What happened?

After https://github.com/pulumi/pulumi/pull/16146 a cloudflare test started failing https://github.com/pulumi/pulumi-cloudflare/actions/runs/9510993829/job/26227067460?pr=812

Debugging it a bit it looks like a resource added via `.get` now refreshes dirty.

I've confirmed the issue is not present under `PULUMI_ENABLE_LEGACY_REFRESH_DIFF=1`

<details> <summary>GRPC calls </summary>

```json
{
    "method": "/pulumirpc.ResourceProvider/Read",
    "request": {
        "id": "2b21bda64f9c4e6fb551fbe0c4bc8fc7",
        "urn": "urn:pulumi:dev::regress-554::cloudflare:index/ruleset:Ruleset::imported",
        "properties": {
            "description": "",
            "id": "2b21bda64f9c4e6fb551fbe0c4bc8fc7",
            "kind": "zone",
            "name": "domain-rate-limit",
            "phase": "http_request_transform",
            "rules": [
                {
                    "action": "rewrite",
                    "actionParameters": {
                        "algorithms": [],
                        "autominifies": [],
                        "headers": [],
                        "responses": [],
                        "uri": {
                            "path": {
                                "value": "/my-new-route"
                            }
                        }
                    },
                    "description": "example URI path transform rule",
                    "enabled": true,
                    "expression": "(http.host eq \"example.com\" and http.request.uri.path eq \"/old-path\")",
                    "id": "d400c630e7db4ca387bef173741d3117",
                    "lastUpdated": "2024-06-14 14:21:11.275189 +0000 UTC",
                    "ref": "d400c630e7db4ca387bef173741d3117",
                    "version": "1"
                }
            ],
            "zoneId": "cabcdb3c8548af2e275acc42ed1fea45"
        },
        "inputs": {}
    },
    "response": {
        "id": "2b21bda64f9c4e6fb551fbe0c4bc8fc7",
        "properties": {
            "description": "",
            "id": "2b21bda64f9c4e6fb551fbe0c4bc8fc7",
            "kind": "zone",
            "name": "domain-rate-limit",
            "phase": "http_request_transform",
            "rules": [
                {
                    "action": "rewrite",
                    "actionParameters": {
                        "algorithms": [],
                        "autominifies": [],
                        "headers": [],
                        "responses": [],
                        "uri": {
                            "path": {
                                "value": "/my-new-route"
                            }
                        }
                    },
                    "description": "example URI path transform rule",
                    "enabled": true,
                    "expression": "(http.host eq \"example.com\" and http.request.uri.path eq \"/old-path\")",
                    "id": "d400c630e7db4ca387bef173741d3117",
                    "lastUpdated": "2024-06-14 14:21:11.275189 +0000 UTC",
                    "ref": "d400c630e7db4ca387bef173741d3117",
                    "version": "1"
                }
            ],
            "zoneId": "cabcdb3c8548af2e275acc42ed1fea45"
        },
        "inputs": {}
    },
    "metadata": {
        "kind": "resource",
        "mode": "client",
        "name": "cloudflare"
    }
}
{
    "method": "/pulumirpc.ResourceProvider/Diff",
    "request": {
        "id": "2b21bda64f9c4e6fb551fbe0c4bc8fc7",
        "urn": "urn:pulumi:dev::regress-554::cloudflare:index/ruleset:Ruleset::imported",
        "olds": {
            "description": "",
            "id": "2b21bda64f9c4e6fb551fbe0c4bc8fc7",
            "kind": "zone",
            "name": "domain-rate-limit",
            "phase": "http_request_transform",
            "rules": [
                {
                    "action": "rewrite",
                    "actionParameters": {
                        "algorithms": [],
                        "autominifies": [],
                        "headers": [],
                        "responses": [],
                        "uri": {
                            "path": {
                                "value": "/my-new-route"
                            }
                        }
                    },
                    "description": "example URI path transform rule",
                    "enabled": true,
                    "expression": "(http.host eq \"example.com\" and http.request.uri.path eq \"/old-path\")",
                    "id": "d400c630e7db4ca387bef173741d3117",
                    "lastUpdated": "2024-06-14 14:21:11.275189 +0000 UTC",
                    "ref": "d400c630e7db4ca387bef173741d3117",
                    "version": "1"
                }
            ],
            "zoneId": "cabcdb3c8548af2e275acc42ed1fea45"
        },
        "news": {},
        "oldInputs": {}
    },
    "response": {
        "replaces": [
            "name",
            "phase"
        ],
        "changes": "DIFF_SOME",
        "diffs": [
            "kind",
            "name",
            "phase",
            "rules",
            "zoneId"
        ]
    },
    "metadata": {
        "kind": "resource",
        "mode": "client",
        "name": "cloudflare"
    }
}
```

</details>

### Example

https://github.com/pulumi/pulumi-cloudflare/blob/26d4df4365aedd25cd70743f7b94cfeeb701033d/examples/regress-554/index.ts#L47

### Output of `pulumi about`

```
CLI
Version      3.120.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  cloudflare  5.31.0
language  nodejs      unknown

Host
OS       darwin
Version  14.1.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v22.3.0'

Current Stack: pulumi/regress-554/dev

TYPE                              URN
pulumi:pulumi:Stack               urn:pulumi:dev::regress-554::pulumi:pulumi:Stack::regress-554-dev
pulumi:providers:cloudflare       urn:pulumi:dev::regress-554::pulumi:providers:cloudflare::default_5_31_0
cloudflare:index/ruleset:Ruleset  urn:pulumi:dev::regress-554::cloudflare:index/ruleset:Ruleset::domain-rate-limit
cloudflare:index/ruleset:Ruleset  urn:pulumi:dev::regress-554::cloudflare:index/ruleset:Ruleset::imported


Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/venelin-pulumi-corp
User           venelin-pulumi-corp
Organizations  venelin-pulumi-corp, demo, pulumi
Token type     personal

Dependencies:
NAME                VERSION
@types/node         12.20.55
@pulumi/cloudflare  5.31.0
@pulumi/pulumi      3.120.0

Pulumi locates its logs in /var/folders/82/nqnqw81s1h56l5nv940f9mq00000gn/T/ by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #16502: `pulumi-terraform` tests fail on Pulumi v3.21.0
### What happened?

I was migrating pulumi-terraform off of actions/upload-artifact@v2 and CI failed unexpectedly (unrelated to my change). Investigating showed that CI always fails now, though it succeeded on the last merge to master (3 months ago).

Pinning to v3.108.1 resolved the issue.

### Example

Failed workflow: https://github.com/pulumi/pulumi-terraform/actions/runs/9688729320/job/26736002406

The workflow fails with:
```
  Diagnostics:
    terraform:state:RemoteStateReference (localstate):
      error: Diff is not yet implemented
```

My suspicion is that we have accidentally made `Diff` required instead of apply a default. This is a breaking change.

Passing workflow: https://github.com/pulumi/pulumi-terraform/actions/runs/9688978736/job/26736482099

### Output of `pulumi about`

NA

### Additional context

Thread in slack: https://pulumi.slack.com/archives/C02VCJEBT2N/p1719449691127099

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by lunaris**
External resources are resources whose state is tracked but not managed. That is, they feature in the state file, but Pulumi does not issue create, read or update operations for them. Typically they arise as the result of generated `.get` functions and methods in Pulumi programs (these should not be confused with specific `getX` functions/methods, which are backed by `Invoke`s and designed to reflect data sources/arbitrary function calls).

In #16146, `refresh` operations were modified to use actual bonafide `Diff` calls to compute differences in a manner that would reflect "what will happen on the next `preview`". In general, this aligns better with what users expect when running `refresh`, and fixes a number of issues that have long plagued `refresh`. However, it falls down in the case of external resources. The existing `Diff` contract takes (somewhat strangely) _three_ key inputs:

* The old inputs ("what the program used to say")
* The old outputs ("what we got back from the last update")
* The new inputs ("what the program says now")

Intuitively, `Diff`'s job is to return the difference between the old and new inputs. Aside from old outputs being a bit of a third wheel, this contract makes sense for an `update` operation, where the inputs are driving the outputs and changes there will yield changes elsewhere. In a `refresh` operation, however, we have a different situation -- one in which _both_ old and new inputs _and_ outputs are available. Alas, we don't currently have a "four-argument `Diff`" (or a two-argument one we can call twice with no fear of repercussions), and so the usage in `refresh` is a little bit of a clever hack that ends up biasing inputs over outputs (see #16146 or the implementation for details).

For external resources, the old behaviour (where we just compared outputs) seems like a better fit. This commit therefore adds this special case and a test to ensure that when we see external resources, we simply compare outputs and don't call `Diff`.

Fixes #16401
Fixes #16502

### CODE REVIEW

File: pkg/engine/lifecycletest/refresh_test.go [hunk 1]
```diff
@@ -129,6 +129,70 @@ func TestExternalRefresh(t *testing.T) {
...
+		deploytest.NewProviderLoader("pkgA", semver.MustParse("1.0.0"), func() (plugin.Provider, error) {
+			return &deploytest.Provider{
+				ReadF: func(
+					urn resource.URN,
+					id resource.ID,
+					inputs resource.PropertyMap,
+					state resource.PropertyMap,
+				) (plugin.ReadResult, resource.Status, error) {
+					return plugin.ReadResult{
+						Outputs: resource.PropertyMap{},
```
Comment (Frassle) [inline pkg/engine/lifecycletest/refresh_test.go:149]: Can we change the props here between the first `up` and `refresh` so the display snapshot shows we did look at these outputs.

File: pkg/engine/lifecycletest/testdata/output/TestExternalRefresh/0-0-0/eventstream.json [hunk 2]
```diff
@@ -1,7 +1,7 @@
 {"sequence":0,"timestamp":0,"preludeEvent":{"config":{}}}
 {"sequence":0,"timestamp":0,"resourcePreEvent":{"metadata":{"op":"create","urn":"urn:pulumi:test::test::pulumi:providers:pkgA::default","type":"pulumi:providers:pkgA","old":null,"new":{"type":"pulumi:providers:pkgA","urn":"urn:pulumi:test::test::pulumi:providers:pkgA::default","custom":true,"id":"","parent":"","inputs":{},"outputs":{},"provider":""},"detailedDiff":null,"logical":true,"provider":""}}}
-{"sequence":0,"timestamp":0,"resOutputsEvent":{"metadata":{"op":"create","urn":"urn:pulumi:test::test::pulumi:providers:pkgA::default","type":"pulumi:providers:pkgA","old":null,"new":{"type":"pulumi:providers:pkgA","urn":"urn:pulumi:test::test::pulumi:providers:pkgA::default","custom":true,"id":"68624099-2277-48e3-8b9e-a05724cb592a","parent":"","inputs":{},"outputs":{},"provider":""},"detailedDiff":null,"logical":true,"provider":""}}}
```
Comment (Frassle) [inline pkg/engine/lifecycletest/testdata/output/TestExternalRefresh/0-0-0/eventstream.json:3]: Spurious diff because provider IDs are random. You could revert these snapshots in pkg/engine/lifecycletest/testdata/output/TestExternalRefresh/

File: pkg/resource/deploy/step.go [hunk 3]
```diff
@@ -965,10 +965,17 @@ func (s *RefreshStep) ResultOp() display.StepOp {
...
-	// rely on it.
-	if s.deployment.opts.UseLegacyRefreshDiff {
+	// There are two cases in which we'll diff only resource outputs on a
+	// refresh:
+	//
+	// * The resource is external, that is, it is not managed by Pulumi.
+	//   In these cases, we care somewhat equally about inputs and outputs,
+	//   but the Diff contract we currently support forces us to bias one side
+	//   (typically inputs). This can lead to surprising results, so for now
+	//   we sidestep the issue by only looking at outputs.
```
Comment (Frassle) [inline pkg/resource/deploy/step.go:975]: Worth adding that providers may not support Diff for external resources.

**Review by Frassle — APPROVED** [review]
