### PR TITLE
[programgen/typescript] Improve static typing of config variables in main program

### LINKED ISSUE #13498: [program-gen/typescript] Generated config calls lose type information
### What happened?

When generating programs for typescript from PCL and these programs have config variables, program-gen drops the provided types:
```tf
config "subnets" "list(string)" {
    default = null
    description = "The list of subnets to use"
}
```
generates:
```ts
// The list of subnets to use
const subnets = config.getObject("subnets") || undefined;
```
Also when `default = null` making the configuration variable optional, we no longer need `|| undefined`

### Expected Behavior

Generated type looks like this:
```ts
// The list of subnets to use
const subnets = config.getObject<Array<string>>("subnets");
```

### Steps to reproduce

Run `pulumi convert --from pcl --language typescript --out pcl` against a directory with a single `main.pp` file containing the code:
```
config "subnets" "list(string)" {
    default = null
    description = "The list of subnets to use"
}
```

### Output of `pulumi about`

```
CLI          
Version      3.75.1-dev.0
Go Version   go1.19.10
Go Compiler  gc

Host     
OS       darwin
Version  13.2.1
Arch     arm64
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

Right now when generating `config.getObject(...)` calls in for typescript, we miss a lot of provided static types from the program: optional types, lists, maps and objects. This PR improves the static typing of config variables _in the main program_ 

Fixes #13498

<details>
<summary>Example PCL program</summary>

```tf
config "vpcTag" "string" {
    default = null
    description = "The tag of the VPC"
}

config "vpcId" "string" {
    default = null
    description = "The id of a VPC to use instead of creating a new one"
}

config "subnets" "list(string)" {
    default = null
    description = "The list of subnets to use"
}

config moreTags "map(string)" {
    default = null
    description = "Additional tags to add to the VPC"
}

config userdata "object({path=string, content=string})" {
    default = null
    description = "The userdata to use for the instances"
}

config complexUserdata "list(object({path=string, content=string}))" {
    default = null
    description = "A complex object"
}

resource main "aws:ec2:Vpc" {
	cidrBlock = "10.100.0.0/16"
	tags = {
		"Name": vpcTag
	}
}
```

</details>

<details>
<summary>Generated Typescript before</summary>

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const config = new pulumi.Config();
// The tag of the VPC
const vpcTag = config.getObject("vpcTag") || undefined;
// The id of a VPC to use instead of creating a new one
const vpcId = config.getObject("vpcId") || undefined;
// The list of subnets to use
const subnets = config.getObject("subnets") || undefined;
// Additional tags to add to the VPC
const moreTags = config.getObject("moreTags") || undefined;
// The userdata to use for the instances
const userdata = config.getObject("userdata") || undefined;
// A complex object
const complexUserdata = config.getObject("complexUserdata") || undefined;
const main = new aws.ec2.Vpc("main", {
    cidrBlock: "10.100.0.0/16",
    tags: {
        Name: vpcTag,
    },
});

```

</details>

<details>
<summary>Generated Typescript after</summary>

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const config = new pulumi.Config();
// The tag of the VPC
const vpcTag = config.get("vpcTag");
// The id of a VPC to use instead of creating a new one
const vpcId = config.get("vpcId");
// The list of subnets to use
const subnets = config.getObject<Array<string>>("subnets");
// Additional tags to add to the VPC
const moreTags = config.getObject<Record<string, string>>("moreTags");
// The userdata to use for the instances
const userdata = config.getObject<{content?: string, path?: string}>("userdata");
// A complex object
const complexUserdata = config.getObject<Array<{content?: string, path?: string}>>("complexUserdata");
const main = new aws.ec2.Vpc("main", {
    cidrBlock: "10.100.0.0/16",
    tags: {
        Name: vpcTag,
    },
});

```

</details>

> Note that for optional config variables, we no longer generate `|| undefined` because that is redundant AFAIC when the config variables aren't provided

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/codegen/nodejs/gen_program.go [hunk 1]
```diff
@@ -1108,16 +1108,60 @@ func (g *generator) genComponent(w io.Writer, component *pcl.Component) {
...
+			// get deterministically sorted attribute keys
+			sort.Strings(attributeKeys)
+
+			objectType := "{"
+			for index, propertyName := range attributeKeys {
+				propertyType := complexType.Properties[propertyName]
+				if index != len(attributeKeys)-1 {
+					objectType += fmt.Sprintf("%s?: %s, ", propertyName, computeConfigTypeParam(propertyType))
+				} else {
+					// last element, do not add a comma
```
Comment (Frassle) [inline pkg/codegen/nodejs/gen_program.go:1145]: Could also build a string slice then [strings.Join](https://pkg.go.dev/strings#Join) it.

**Review by Frassle — APPROVED** [review]

File: pkg/codegen/nodejs/gen_program.go (hunk 1 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/nodejs/gen_program.go]: Done ✅

**Comment by Zaid-Ajaj** [comment]
bors merge

**Comment by Zaid-Ajaj** [comment]
bors retry
