### PR TITLE
[cli] fix `pulumi console` command

### LINKED ISSUE #10508: `pulumi console` no longer opens to the current stack
### What happened?

From Pulumi CLI docs, `pulumi console` is described as follows:

https://www.pulumi.com/docs/reference/cli/pulumi_console/ 
> Opens the current stack in the Pulumi Console

however `pulumi console` now opens to my personal app.pulumi.com org regardless of if a stack is selected or not.

### Steps to reproduce

1. from a directory containing a valid pulumi program, with a selected stack.
2. `pulumi console`
3. see landing page in Pulumi SaaS Service.

### Expected Behavior

I should be redirected to the specific stack eg- https://app.pulumi.com/phillipedwards/my-project/dev

### Actual Behavior

I am redirected to my personal org eg- https://app.pulumi.com/phillipedwards

### Output of `pulumi about`

_No response_

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description
This PR fixes the `pulumi console` command to redirect the user to the stack's page in the pulumi service UI as documented.

Fixes #10508 

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/cmd/pulumi/console.go [hunk 1]
```diff
@@ -73,13 +73,13 @@ func newConsoleCmd() *cobra.Command {
 				// Open the stack specific URL (e.g. app.pulumi.com/{org}/{project}/{stack}) for this
 				// stack if a stack is selected and is a cloud stack, else open the cloud backend URL
 				// home page, e.g. app.pulumi.com.
-				if consoleURL, err := cloudBackend.StackConsoleURL(stack.Ref()); err != nil {
-					launchConsole(consoleURL)
-				} else {
```
Comment (dixler) [inline pkg/cmd/pulumi/console.go:78]: logic was flipped.

**Comment by susanev** [comment]
thank you!!

**Review by aq17 — APPROVED** [review]
🎉

File: pkg/cmd/pulumi/console.go (hunk 1 above)
Comment (dixler) [reply pkg/cmd/pulumi/console.go:78]: I could make a 1 char replacement diff, but I think rewriting it would avoid the easy misreading of `==` in the first place.

**Comment by Frassle** [comment]
This change makes no sense! If there's no error fetching the stack URL then use the backend URL, else if there is an error fetching the stack URL use it. This wouldn't even be writable using result types, there is no way this is the correct fix.

**Comment by aq17** [comment]
> It's too early in the morning to be reading code 😅

Had me re-reading the change like ten times before I saw your updated comment 😌
