### PR TITLE
[sdk/nodejs] Save pkg/mod registrations on async local store

### LINKED ISSUE #13223: Resource references are not deserialized correctly when there are multiple copies of `@pulumi/pulumi`
### What happened?

I am creating a Multi language package/component in Go. I have exported a resource in the schema:

https://github.com/lbrlabs/pulumi-lbrlabs-eks/blob/main/schema.yaml#L51

And I've also registered the output in the struct: https://github.com/lbrlabs/pulumi-lbrlabs-eks/blob/main/provider/pkg/provider/cluster.go#L40 

and in the resource outputs:

https://github.com/lbrlabs/pulumi-lbrlabs-eks/blob/main/provider/pkg/provider/cluster.go#L858

However, when I try and reference this value in the typescript SDK I've generated, it only outputs the cluster name, not the full resource

### Expected Behavior

the MLC should honour the schema

### Steps to reproduce

See this example here:

https://github.com/lbrlabs/pulumi-lbrlabs-eks/blob/main/examples/ts/index.ts

Note, I've exported the entire cluster object, and I get:

```
Outputs:
  + clusterInfo: "cluster-06f785d"
```

If I try export just the name, I get nothing returned

### Output of `pulumi about`

N/A

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
Rather than saving package/module registrations in a module variable, save them in the store where other state is stored. This way, if there are multiple copies of `@pulumi/pulumi`, they'll use the same store, rather than having separate copies of registrations.

Fixes #13223

### CODE REVIEW

File: sdk/nodejs/runtime/state.ts [hunk 1]
```diff
@@ -289,6 +332,13 @@ export const getStore = () => {
     return localStore;
 };
 
+export const getGlobalStore = () => {
```
Comment (justinvp) [inline sdk/nodejs/runtime/state.ts:335]: This should be marked as `@internal`. Also, it should go below the `(<any>getStore).captureReplacement = () => {` block, since that is modifying `getStore` it should be kept together.

Comment (tgummerer) [reply sdk/nodejs/runtime/state.ts]: Done :heavy_check_mark:
