### PR TITLE
Don't bail at preview when a protected resource needs replacement

### LINKED ISSUE #5027: Cannot run update for database instance if itself and a failover (Cloud SQL) have `protect: true`
I have a 2 `DatabaseInstance` resources, one of them is a failover for the master instance. They both have `protect: true`. For whatever reason, pulumi thinks it needs to replace the master instance. However, because they both have `protect: true`, it's failing the preview as it says it can't replace anything with `protect: true`.

### PR DESCRIPTION
**Pull request by mikhailshilkov**
# Description

Don't bail at preview when a protected resource needs replacement, just error. This makes sure that users can see the actual diff that causes the replacement.

Fixes #5027

Before:

```
$ pulumi preview
Type                                     Name                  Plan     Info
     pulumi:pulumi:Stack                      azure-native-ts-dev2           
     └─ azure-native:resources:ResourceGroup  rg                             1 error

Diagnostics:
  azure-native:resources:ResourceGroup (rg):
    error: unable to replace resource "urn:pulumi:dev2::azure-native-ts::azure-native:resources:ResourceGroup::rg"
    as it is currently marked for protection. To unprotect the resource, remove the `protect` flag from the resource in your Pulumi program and run `pulumi up`


$ pulumi preview --diff
pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev2::azure-native-ts::pulumi:pulumi:Stack::azure-native-ts-dev2]
error: unable to replace resource "urn:pulumi:dev2::azure-native-ts::azure-native:resources:ResourceGroup::rg"
as it is currently marked for protection. To unprotect the resource, remove the `protect` flag from the resource in your Pulumi program and run `pulumi up`
Resources:
    1 unchanged
```

After:

```
$ pulumi preview
Type                                     Name                  Plan        Info
     pulumi:pulumi:Stack                      azure-native-ts-dev2              1 error; 2 warnings
 +-  └─ azure-native:resources:ResourceGroup  rg                    replace     [diff: ~location]; 1 error

Diagnostics:
  azure-native:resources:ResourceGroup (rg):
    error: unable to replace resource "urn:pulumi:dev2::azure-native-ts::azure-native:resources:ResourceGroup::rg"
    as it is currently marked for protection. To unprotect the resource, remove the `protect` flag from the resource in your Pulumi program and run `pulumi up`

  pulumi:pulumi:Stack (azure-native-ts-dev2):
    error: preview failed


$ pulumi preview --diff
pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev2::azure-native-ts::pulumi:pulumi:Stack::azure-native-ts-dev2]
error: unable to replace resource "urn:pulumi:dev2::azure-native-ts::azure-native:resources:ResourceGroup::rg"
as it is currently marked for protection. To unprotect the resource, remove the `protect` flag from the resource in your Pulumi program and run `pulumi up`
    +-azure-native:resources:ResourceGroup: (replace) 🔒
        [id=/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/rg5f8e30e4]
        [urn=urn:pulumi:dev2::azure-native-ts::azure-native:resources:ResourceGroup::rg]
        [provider=urn:pulumi:dev2::azure-native-ts::pulumi:providers:azure-native::default_2_30_0::3c957b2a-4852-439c-b211-22a115bbe89a]
      ~ location: "westeurope" => "westus2"
error: preview failed
Resources:
    +-1 to replace
    1 unchanged
```

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [ ] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/engine/lifecycletest/pulumi_test.go [hunk 1]
```diff
@@ -3181,13 +3181,19 @@ func TestProtect(t *testing.T) {
...
+	// Run a dry-run (preview) which will cause a replace, we should get an error.
+	// However, the preview doesn't bail, so we expect one "created" resource as a result of this operation.
 	expectedMessage = "<{%reset%}>unable to replace resource \"urn:pulumi:test::test::pkgA:m:typA::resA\"\n" +
 		"as it is currently marked for protection. To unprotect the resource, remove the `protect` flag from " +
 		"the resource in your Pulumi program and run `pulumi up`<{%reset%}>\n"
 	ins = resource.NewPropertyMapFromMap(map[string]interface{}{
 		"foo": "baz",
 	})
+	_, err = TestOp(Update).Run(project, p.GetTarget(t, snap), p.Options, true, p.BackendClient, validate)
+	assert.Error(t, err)
```
Comment (Frassle) [inline pkg/engine/lifecycletest/pulumi_test.go:3193]: Please don't use assert.Error, use ErrorContains or similar to check its actually the error expected.

File: pkg/resource/deploy/step_generator.go [hunk 2]
```diff
@@ -1034,7 +1034,9 @@ func (sg *stepGenerator) generateStepsFromDiff(
 					"program and run `pulumi up`", urn)
 				sg.deployment.ctx.Diag.Errorf(diag.StreamMessage(urn, message, 0))
 				sg.sawError = true
-				return nil, result.BailErrorf(message)
+				if !sg.deployment.preview {
```
Comment (Frassle) [inline pkg/resource/deploy/step_generator.go:1037]: Probably worth a comment why we have to error here if not preview.

File: pkg/engine/lifecycletest/pulumi_test.go (hunk 1 above)
Comment (mikhailshilkov) [reply pkg/engine/lifecycletest/pulumi_test.go:3193]: I thought that already happens with `expectedMessage`. I'll double check.

File: pkg/resource/deploy/step_generator.go (hunk 2 above)
Comment (mikhailshilkov) [reply pkg/resource/deploy/step_generator.go:1040]: I added a comment. I'm not exactly sure we _need_ to bail during update. Honestly, I'm making the smallest possible change to solve the preview issue.

File: changelog/pending/20240417--engine--dont-bail-at-preview-when-a-protected-resource-needs-replacement.yaml [hunk 3]
```diff
@@ -0,0 +1,4 @@
+changes:
+- type: fix
+  scope: engine
+  description: Don't bail at preview when a protected resource needs replacement
```
Comment (tgummerer) [inline changelog/pending/20240417--engine--dont-bail-at-preview-when-a-protected-resource-needs-replacement.yaml:4]:
```suggestion
  description: Make preview not bail when a protected resource needs replacement
```

**Review by tgummerer — APPROVED** [review]

File: changelog/pending/20240417--engine--dont-bail-at-preview-when-a-protected-resource-needs-replacement.yaml (hunk 3 above)
Comment (tgummerer) [reply changelog/pending/20240417--engine--dont-bail-at-preview-when-a-protected-resource-needs-replacement.yaml:4]: Yes, that sounds great, I like it!

File: pkg/resource/deploy/step_generator.go (hunk 2 above)
Comment (Frassle) [reply pkg/resource/deploy/step_generator.go:1040]: If we don't bail and we're doing a create before delete replacement we'll execute the create before getting to the delete error. State will still be tracking both resources but it's an awkward state to cleanup from.
