### PR TITLE
Fixes multiline secrets not being masked when escaped.

### LINKED ISSUE #12016: Config secret leaks in environment variable if source is multiline (e.g. a private key file)
### What happened?

Have a two different secrets in a Pulumi.stack.yaml config file. 
One is a simple single value and the other is a private SSH key.
If I run this code:
```
import * as pulumi from "@pulumi/pulumi";
console.log(process.env.PULUMI_CONFIG)
```

I get this output:
```
Diagnostics:
  pulumi:pulumi:Stack (leaky-env-vars-dev):
    {"leaky-env-vars:config:simpleSecret":"[secret]","leaky-env-vars:config:sshKeySecret":"-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXk.....
```

So, the simple secret is treated correctly and not exposed, but the SSH private key is exposed. 
I also confirmed that any multiline secret is treated the same way and exposed.

### Expected Behavior

The secret should not be exposed.

### Steps to reproduce

1. `ssh-keygen -f sshKey`
2. `cat sshKey | pulumi config set sshKeySecret --secret`
3. `pulumi config set simpleSecret mySecretValue --secret`
4. `pulumi preview` with the code provided above.
5. See the sshKey is exposed.

### Output of `pulumi about`

CLI          
Version      3.53.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  12.5.1
Arch     x86_64

Current Stack: xxxxx/leaky-env-vars/dev

TYPE                 URN
pulumi:pulumi:Stack  urn:pulumi:dev::leaky-env-vars::pulumi:pulumi:Stack::leaky-env-vars-dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/xxxxx

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.53.1
@types/node     16.18.11

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description
This PR fixes an issue where pulumi fails to mask multiline secrets that are JSONified. String matching did not work when newlines were replaced with `\n`.

Fixes #12016 

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by Frassle — APPROVED** [review]
Nice and simple

**Comment by dixler** [comment]
bors merge

**Review by abhinav — COMMENTED** [review]
Will we have the same problem if the secret has tabs, double quotes, or other special characters? 

We might have a more robust fix if we take the escaped representation of the secret, and if it's not the same as the original secret, add it to the filters.

**Comment by dixler** [comment]
bors cancel

File: sdk/go/common/util/logging/log.go [hunk 1]
```diff
@@ -160,6 +161,13 @@ func CreateFilter(secrets []string, replacement string) Filter {
 			continue
 		}
 		items = append(items, secret, replacement)
+
+		// Catch secrets that are serialized to JSON.
+		bs, err := json.Marshal(secret)
+		if err != nil {
+			continue
+		}
+		items = append(items, string(bs[1:len(bs)-1]), replacement)
```
Comment (dixler) [inline sdk/go/common/util/logging/log.go:170]: @abhinav better?

Comment (abhinav) [reply sdk/go/common/util/logging/log.go:170]: Yeah, just one small thing: I would check for equality on original secret.
Otherwise for plain strings like "foo", you'll end up with two replacements in the filter.

```suggestion
		// Catch secrets that are serialized to JSON.
		bs, err := json.Marshal(secret)
		if err != nil {
			continue
		}
		if escaped := string(bs[1:len(bs)-1]); escaped != secret {
			items = append(items, escaped, replacement)
		}
```

**Review by abhinav — APPROVED** [review]
lgtm w minor comment

**Comment by dixler** [comment]
bors merge
