### PR TITLE
Fix incorrect pointers for array of objects [go/codegen]

### LINKED ISSUE #11663: Go program generation of array of objects mixes up pointers
### What happened?

Generating Go from YAML for an AWSx VPC with SubnetSpecs fails.

- `ec2.SubnetSpecArgs` items don't need to be appended with `&`.
- Therefore, array items types don't need to be specified at all
- `CidrMask` should be wrapped in `pulumi.IntRef` because it's optional.

### Steps to reproduce

```yaml
resources:
  vpc:
    type: awsx:ec2:Vpc
    properties:
      subnetSpecs:
        - type: "Public"
          cidrMask: 22
        - type: "Private"
          cidrMask: 20
```

### Expected Behavior

```go
			SubnetSpecs: []ec2.SubnetSpecArgs{
				{
					Type:     ec2.SubnetTypePublic,
					CidrMask: pulumi.IntRef(22),
				},
				{
					Type:     ec2.SubnetTypePrivate,
					CidrMask: pulumi.IntRef(20),
				},
			},
		})
```

### Actual Behavior

```go
		vpc, err := ec2.NewVpc(ctx, "vpc", &ec2.VpcArgs{
			SubnetSpecs: []ec2.SubnetSpecArgs{
				&ec2.SubnetSpecArgs{
					Type:     ec2.SubnetTypePublic,
					CidrMask: 22,
				},
				&ec2.SubnetSpecArgs{
					Type:     ec2.SubnetTypePrivate,
					CidrMask: 20,
				},
			},
		})
```

### Output of `pulumi about`

```
CLI          
Version      3.49.0
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME  VERSION
awsx  unknown
yaml  unknown

Host     
OS       darwin
Version  13.0.1
Arch     arm64

Current Stack: daniel-pulumi/scratch-yaml/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/daniel-pulumi
User           daniel-pulumi
Organizations  daniel-pulumi, pulumi
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by aq17**
Fixes #11663
Fix incorrect pointer argument codegen when objects are nested inside an array whose type is not a pointer.

Example:
`&s3.BucketLoggingArgs` is valid here
```
bucket, err := s3.NewBucket(ctx, "bucket", &s3.BucketArgs{
			Loggings: s3.BucketLoggingArray{
				&s3.BucketLoggingArgs{
					TargetBucket: logs.Bucket,
				},
			},
		})

```
but `&ec2.SubnetSpecArgs{}` is invalid here:
```
SubnetSpecs: []ec2.SubnetSpecArgs{
				&ec2.SubnetSpecArgs{
					Type:     ec2.SubnetTypePublic,
					CidrMask: 22,
				},
				&ec2.SubnetSpecArgs{
					Type:     ec2.SubnetTypePrivate,
					CidrMask: 20,
				},
			},
```
Instead, it should be: 
```
SubnetSpecs: []ec2.SubnetSpecArgs{
				{
					Type:     ec2.SubnetTypePublic,
					CidrMask: 22,
				},
				{
					Type:     ec2.SubnetTypePrivate,
					CidrMask: 20,
				},
			},
```

### CODE REVIEW

**Comment by aq17** [comment]
@danielrbradley this doesn't address the third error you raised in the ticket, typechecking nested keys seems a bit trickier so would like to address in a separate PR

File: pkg/codegen/go/gen_program.go [hunk 1]
```diff
@@ -49,6 +49,10 @@ type generator struct {
 	configCreated       bool
 	externalCache       *Cache
 
+	// intermediate flag to generate TupleConExpression arguments correctly
+	isGenTupleConExprListArgs bool
```
Comment (aq17) [inline pkg/codegen/go/gen_program.go:53]: Suggestions welcome on better names/ alternate approaches to adding flags in the generator if needed @iwahbe

File: pkg/codegen/go/gen_program_expressions.go [hunk 2]
```diff
@@ -740,6 +744,16 @@ func (g *generator) genTupleConsExpression(w io.Writer, expr *model.TupleConsExp
...
+	// don't need to generate type for list args if not a pointer, i.e. []ec2.SubnetSpecArgs{ {Type: ...} }
+	// unless it contains an interface, i.e. []map[string]interface{ map[string]interface{"key": "val"} }
+	if strings.HasPrefix(argType, "[]") {
+		if !strings.Contains(argType, "interface{}") {
+			g.isGenTupleConExprListArgs = true
+			if strings.HasPrefix(argType, "[]*") {
+				g.isPtrArg = true
+			}
+		}
+	}
```
Comment (iwahbe) [inline pkg/codegen/go/gen_program_expressions.go:756]: Do we want `*Array` and `*ArrayInput` types (such as [ListenerCertificateArrayInput](https://github.com/pulumi/pulumi-aws/blob/64c83a9e5556bbb17d1f20e12a24614c32a81655/sdk/go/aws/applicationloadbalancing/listenerCertificate.go#L174-L181))? My understanding is that those are still array literals, but they don't start with `[]`.

I don't think setting the values to false at the end will work with nested `genTupleConsExpression` calls. I think we will need to restore these to their previous values after setting them, rather than setting them to `false` later. It would be great if we had a test for nested cons expressions.

```suggestion
	if strings.HasPrefix(argType, "[]") && !strings.Contains(argType, "interface{}") {
		defer func(b bool) { g.isGenTupleConExprListArgs = b } (g.isGenTupleConExprListArgs)
		g.isGenTupleConExprListArgs = true
		if strings.HasPrefix(argType, "[]*") {
			defer func(b bool) { g.isPtrArg = b } (g.isPtrArg)
			g.isPtrArg = true
		}
	}
```

File: pkg/codegen/go/gen_program.go (hunk 1 above)
Comment (iwahbe) [reply pkg/codegen/go/gen_program.go:53]: I might change the name to `inGenTupleConExprListArgs`, but the benefit would be marginal. I would definitely change the comment to explain what the flag means, instead of why it exists. Something like this (but adjusted for accuracy):
```
	 // isGenTupleConExprListArgs indicates that a the generator is with a tupleConsExpression for an args list.
```

File: pkg/codegen/go/gen_program_expressions.go (hunk 2 above)
Comment (aq17) [reply pkg/codegen/go/gen_program_expressions.go:756]: I'm not sure if it's valid Go for type aliases – for example, removing `&s3.BucketLoggingArgs` from [this example ](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/testing/test/testdata/aws-s3-logging-pp/go/aws-s3-logging.go#L15-L17) causes an 'invalid composite literal' error

Good point on the nested expression 😄

**Review by iwahbe — APPROVED** [review]
LGTM!
