### PR TITLE
[sdkgen/python] Fix error calling _configure when the value is None

### LINKED ISSUE #14012: [codegen] - 3.84.0 results in invalid `configure()` method - python
### What happened?

Python codegen results in an invalid `configure()` block.

### Example

Error produced at runtime:
```
TypeError: _configure() missing 2 required positional arguments: 'cert_pem' and 'key_pem'

### Output of `pulumi about`

3.84.0

### Additional context

More info coming shortly

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
We recently fixed an issue where defaults weren't set for nested objects when the nested objects are passed as dicts (#13825). Unfortunately, this introduced a regression when the nested object is optional, but it itself has required fields, and the nested object is not specified. In that case, an unintended error is raised.

Consider a `Provider` resource with an optional `certmanager: ProviderCertmanagerArgs` argument, which itself has two required properties: `mtls_cert_pem` and `mtls_key_pem`.

When creating a new `Provider` without specifying a `certmanager`, we get an error:

```
TypeError: ProviderCertmanagerArgs._configure() missing 2 required positional arguments: 'mtls_cert_pem' and 'mtls_key_pem'
```

The source of the problem is this check in the generated `Provider`'s constructor:

```python
            if not isinstance(certmanager, ProviderCertmanagerArgs):
                certmanager = certmanager or {}
                def _setter(key, value):
                    certmanager[key] = value
                ProviderCertmanagerArgs._configure(_setter, **certmanager)
```

When `certmanager` is not specified, its value is `None`, which is also not an instance of `ProviderCertmanagerArgs`. So the code inside the `if` executes. `ProviderCertmanagerArgs._configure` is called on an empty dict, and the error is raised because there are two required positional arguments to `ProviderCertmanagerArgs._configure`.

The fix is to add an additional check to ensure the value is not `None`.

Fixes #14012

### CODE REVIEW

File: pkg/codegen/python/gen.go [hunk 1]
```diff
@@ -1348,7 +1348,8 @@ func (mod *modContext) genResource(res *schema.Resource) (string, error) {
 		// Emit logic to configure schema.ObjectType args that have defaults and deprecation messages.
 		if objType, ok := unwrapped.(*schema.ObjectType); ok {
 			expectedObjType := mod.objectClassRef(objType, true)
-			fmt.Fprintf(w, "            if not isinstance(%s, %s):\n", InitParamName(prop.Name), expectedObjType)
+			fmt.Fprintf(w, "            if %[1]s is not None and not isinstance(%[1]s, %s):\n",
+				InitParamName(prop.Name), expectedObjType)
```
Comment (justinvp) [inline pkg/codegen/python/gen.go:1352]: I understand the original implementation of this was `if isinstance(%s, dict)`, which would have avoided this error, but the code review feedback was to flip the check around to check for the args class instead, to be more permissive about the types of dictionaries that could be supported. https://github.com/pulumi/pulumi/pull/13825#discussion_r1317218561.

I still wonder if we should switch this back to checking for a dictionary, but rather than checking for `dict` specifically, check if it is an instance of `Mapping` (`if isinstance(%s, Mapping)`), which would be permissive in the types of dictionaries it accepts.

I've chosen not to do that for this fix, but wanted to mention it.

File: pkg/codegen/testing/test/testdata/regress-py-14012/python/pulumi_foo/_inputs.py [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+            lambda key, value: pulumi.set(__self__, key, value),
+            mtls_cert_pem=mtls_cert_pem,
+            mtls_key_pem=mtls_key_pem,
+        )
+    @staticmethod
+    def _configure(
+             _setter: Callable[[Any, Any], None],
+             mtls_cert_pem: pulumi.Input[str],
+             mtls_key_pem: pulumi.Input[str],
+             opts: Optional[pulumi.ResourceOptions]=None):
```
Comment (justinvp) [inline pkg/codegen/testing/test/testdata/regress-py-14012/python/pulumi_foo/_inputs.py:31]: @dixler, I kind of get why `ProviderArgs._configure` has an `opts` parameter, but I don't understand why any other type like this needs it. Seems like it's not necessary here.

**Review by dixler — APPROVED** [review]

File: pkg/codegen/testing/test/testdata/regress-py-14012/python/pulumi_foo/_inputs.py (hunk 2 above)
Comment (dixler) [reply pkg/codegen/testing/test/testdata/regress-py-14012/python/pulumi_foo/_inputs.py:31]: if it's being supplied via kwargs, we need to catch it iirc.

**Comment by pgavlin** [comment]
Change looks good to me. Did #13825 add a test that specifically target its new behavior, or was it leaning on existing tests? Do we have tests that validate this at runtime?

File: pkg/codegen/testing/test/testdata/regress-py-14012/python/pulumi_foo/_inputs.py (hunk 2 above)
Comment (justinvp) [reply pkg/codegen/testing/test/testdata/regress-py-14012/python/pulumi_foo/_inputs.py:31]: > if it's being supplied via **kwargs, we need to catch it iirc.

I get it for top-level resource args.

But this is a nested object. I'm not seeing how opts would get passed to that.

**Comment by justinvp** [comment]
> Change looks good to me. Did #13825 add a test that specifically target its new behavior, or was it leaning on existing tests? Do we have tests that validate this at runtime?

#13825 did add a [basic runtime test](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/testing/test/testdata/simple-enum-schema/python-extras/tests/test_codegen.py), but it didn't cover the case where the nested object is optional but has required fields.

This PR includes an additional runtime regression test for this case (https://github.com/pulumi/pulumi/pull/14014/files#diff-cbd72a99dacdd14d7f9d0c055f2bf7a06126c2fcf710aa11d9246f41fee4ec02).

The postmortem discussion should touch on ensuring we're covering all cases with runtime tests. We may still want to add additional runtime tests as a follow-up from that.

**Review by pgavlin — APPROVED** [review]
