### PR TITLE
Fix marshaling prompt slices/maps with input elems

### LINKED ISSUE #7504: [sdk/go] Plain map of resources lead to panic
The code below leads to this panic:

```
    panic: fatal: An assertion has failed: map[first:{World Thing} second:{Thing World}]: cannot assign map[string]xyz.SomeObjectInput to map[string]xyz.SomeObject
    goroutine 24 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.2-0.20210712225111-343bc4c7784f/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x182ed00, 0x1954be2, 0x1a, 0xc000792f00, 0x3, 0x3)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.2-0.20210712225111-343bc4c7784f/go/common/util/contract/assert.go:33 +0x1a5
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputAndDetermineSecret(0x182ed00, 0xc00012c180, 0x1a50760, 0x182eca0, 0x1, 0x1, 0x0, 0x17a5e13, 0xa, 0x0, ...)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.2-0.20210712225111-343bc4c7784f/go/pulumi/rpc.go:288 +0x514
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInput(0x182ed00, 0xc00012c180, 0x1a50760, 0x182eca0, 0x17a5e01, 0xa, 0x0, 0x0, 0x1a50760, 0x182eca0, ...)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.2-0.20210712225111-343bc4c7784f/go/pulumi/rpc.go:170 +0x73
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputs.func1(0x17a5e27, 0xa, 0x182ed00, 0xc00012c180, 0x1a50760, 0x182eca0, 0x195, 0x0)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.2-0.20210712225111-343bc4c7784f/go/pulumi/rpc.go:77 +0x9f
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputs(0x1a32c20, 0xc000110060, 0xf, 0x0, 0x0, 0xc000132100, 0x1, 0xc0005aa140, 0x49)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.2-0.20210712225111-343bc4c7784f/go/pulumi/rpc.go:140 +0x605
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).prepareResourceInputs(0xc0005d2140, 0x1a32c20, 0xc000110060, 0x194c55b, 0xf, 0xc000132100, 0xc000136150, 0x1, 0x0, 0x0, ...)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.2-0.20210712225111-343bc4c7784f/go/pulumi/context.go:1164 +0x1cf
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).registerResource.func1(0xc000136150, 0xc0005d2140, 0x1a32c20, 0xc000110060, 0x194c55b, 0xf, 0xc000132100, 0x1, 0x1943c88, 0x4, ...)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.2-0.20210712225111-343bc4c7784f/go/pulumi/context.go:770 +0x1d7
    created by github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).registerResource
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.2-0.20210712225111-343bc4c7784f/go/pulumi/context.go:757 +0x5ce
    exit status 2
    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

Schema:

```json
{
    "name": "xyz",
    "resources": {
        "xyz:index:First": {
            "isComponent": true,
            "inputProperties": {
                "regularProp": {
                    "type": "string"
                },
                "mapOfItems": {
                    "type": "object",
                    "plain": true,
                    "additionalProperties": {
                        "$ref": "#/types/xyz:index:SomeObject"
                    }
                }
            },
            "requiredInputs": [
                "regularProp",
                "mapOfItems"
            ]
        }
    },
    "types": {
        "xyz:index:SomeObject": {
            "type": "object",
            "properties": {
                "firstItem": {
                    "type": "string"
                },
                "secondItem": {
                    "type": "string"
                }
            },
            "required": [
                "firstItem",
                "secondItem"
            ]
        }
    },
    "language": {
        "go": {
            "generateResourceContainerTypes": true,
            "importBasePath": "github.com/pulumi/pulumi-xyz/sdk/go/xyz"
        }
    }
}
```

Client code:

```go
                   _, err := xyz.NewFirst(ctx, "test", &xyz.FirstArgs{
			MapOfItems:  map[string]xyz.SomeObjectInput{
				"first": xyz.SomeObjectArgs{
					FirstItem:  pulumi.String("World"),
					SecondItem: pulumi.String("Thing"),
				},
				"second": xyz.SomeObjectArgs{
					FirstItem:  pulumi.String("Thing"),
					SecondItem: pulumi.String("World"),
				},
			},
			RegularProp: pulumi.String("Hello"),
		})
		if err != nil {
			return err
		}
```

This is the same class of panic as https://github.com/pulumi/pulumi/issues/7359, and likely related to the comment in https://github.com/pulumi/pulumi/pull/7369#issue-678202649.  As a result, it may be covered by https://github.com/pulumi/pulumi/issues/7434, but users are hitting this specific case actively currently.

### PR DESCRIPTION
**Pull request by jen20**
# Description

This fixes #7504, and is the other half of the interim fix corresponding to #7359. The case listed in #7509 no longer reproduces after this fix is applied.

The change to imports is the result of running `goimports` and is not a functional change.

Fixes #7504.

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

No automated tests added, but repro case in #7504 no longer reproduces with this fix.

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

Not a user-facing change.

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

N/A.

### CODE REVIEW

File: sdk/go/pulumi/rpc.go [hunk 1]
```diff
@@ -297,6 +295,15 @@ func marshalInputAndDetermineSecret(v interface{},
 		}
 
 		rv := reflect.ValueOf(v)
+
+		switch rv.Type().Kind() {
+		case reflect.Array, reflect.Slice, reflect.Map:
+			// Not assignable in prompt form because of the difference in input and output shapes.
```
Comment (pgavlin) [inline sdk/go/pulumi/rpc.go:301]: Would you mind tagging this with a reference to #7434?

**Review by pgavlin — APPROVED** [review]
Unit tests would be excellent, but the fix looks okay.
