### PR TITLE
[engine] Check for old resources first by URN and then aliases

### LINKED ISSUE #13848: error: snapshot integrity failure; refusing to use it: duplicate resource <urn> (not marked for deletion)
Customer has an existing stack where a resource was going to get deleted and a new one created, the stack went thru half the creation then failed because of a prometheus deployment so it seems to have never gotten to the delete calls.

We added an alias to the code, because the original delete/create shouldn't have happened then upon next run it looks like it duplicated the resource, and now the state is corrupted:

```
Previewing update (dev):
error: snapshot integrity failure; refusing to use it: duplicate resource urn:pulumi:dev::dataflow-services-dev::aws:ec2/vpcEndpointServiceAllowedPrinciple:VpcEndpointServiceAllowedPrinciple::name (not marked for deletion)
```

### PR DESCRIPTION
**Pull request by justinvp**
This change fixes a regression in the step generator when looking for old resources. When generating steps for a register resource event, we previously looked for old resources first by the resource's URN and then by aliases.

This regressed with #10819:

```diff
-	for _, urnOrAlias := range append([]resource.URN{urn}, goal.Aliases...) {
+	aliases[urn] = struct{}{}
+	for urnOrAlias := range aliases {
```

Previously, aliases were in a slice and we always looked for the URN first, then aliases.

With #10819, aliases changed to being stored in a map (a set). The URN was added to the map before iterating over it, but there's no guarantee it will be looked at first (iteration order for maps is unspecified), and with the current behavior when there are aliases in the map, the URN very likely won't come first.

This can lead to duplicate resources in the state (stack corruption) when the wrong old resource is chosen.

The fix is to move back to always checking for old resources using the URN first. We also move back to maintaining aliases in a slice for consistent ordering.

Fixes #13848

### CODE REVIEW

File: pkg/engine/lifecycletest/alias_test.go [hunk 1]
```diff
@@ -1221,6 +1221,99 @@ func TestDuplicatesDueToAliases(t *testing.T) {
...
+	assert.Equal(t, resource.URN("urn:pulumi:test::test::pkgA:m:typA::resA"), snap.Resources[1].URN)
+	assert.Equal(t, resource.URN("urn:pulumi:test::test::pkgA:m:typA$pkgA:m:typA::resB"), snap.Resources[2].URN)
+	assert.Equal(t, resource.URN("urn:pulumi:test::test::pkgA:m:typA::resB"), snap.Resources[3].URN)
+
+	// Run the next case, with "resA" and "resB with no parent and alias to have resA as its parent".
+	mode = 1
+	snap, res = TestOp(Update).Run(project, p.GetTarget(t, snap), p.Options, false, p.BackendClient, nil)
+	assert.Nil(t, res)
+	assert.NotNil(t, snap)
+	assert.Nil(t, snap.VerifyIntegrity())
```
Comment (justinvp) [inline pkg/engine/lifecycletest/alias_test.go:1310]: Prior to the fix, this fails because we end up with two resources with the same URN (`urn:pulumi:test::test::pkgA:m:typA::resB`) in the snapshot.

**Review by Frassle — APPROVED** [review]
