### PR TITLE
Fix race condition when rendering progress events

### LINKED ISSUE #17594: Ctrl-C does not cancel plugin downloads
### What happened?

When I tried to cancel `pulumi up` while it was downloading a required plugin, the plugin did not cancel.

### Example

Write a program that requires a provider:

```yaml
name: dev-yaml
runtime: yaml
resources:
  p:
    type: pulumi:providers:aws
```

Run `pulumi up` (ensuring that there isn't already an AWS provider downloaded):

Image

Hit Ctrl-C, and see that nothing happens.

### Output of `pulumi about`

```
CLI          
Version      3.137.1-dev.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME  VERSION
resource  aws   unknown
language  yaml  unknown

Host     
OS       darwin
Version  15.0.1
Arch     arm64

This project is written in yaml

Current Stack: pulumi/dev-yaml/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ian-pulumi-corp
User           ian-pulumi-corp
Organizations  ian-pulumi-corp, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/fg/_1q36r4j6yx0rwz2fbhjd5y40000gn/T/ by default
```

### Additional context

This has broken several times. Could we add tests to this functionality?

We use a different renderer for `pulumi install` and `pulumi plugin download`, both of which work as intended here.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by lunaris**
When we are installing plugins as part of a Pulumi operation (e.g. `pulumi up`), we'll render a series of progress bars to show the user what is going on. Under the hood, the CLI manages this by responding to progress events, tracking them in a map and rendering them as system messages. Concurrent access to this map is guarded by a mutex.

Recently, #17594 was re-opened due to users experiencing hangs/locking behaviour when installing plugins as part of an update. While we don't have a solid reproduction, we do have some data from occurrences which suggests that the system is idle, and thus most likely deadlocked. If so, given that we did not see these issues prior to the introduction of progress events, we can reason that the mutex guarding the progress events map is the cause of this deadlock.

Digging in, we find one possible culprit. The `handleProgressEvent` method uses a `defer` statement to unlock the mutex after completing its operation. However, prior to return, it calls `renderer.progress`, which _can_ in some circumstances call back into methods requiring the same lock (`generateTreeNodes`). This could cause a nested-lock deadlock, in which the same Goroutine attempts to call `Lock()` twice, deadlocking.

Assuming this is indeed the cause (one can hope, at least), this change fixes it, moving the `Unlock` call above the call to `renderer.progress`. This should still be data-race-safe -- the events map is still protected -- but tightens the bound of the critical section to one in which deadlocks can no longer occur.

Fixes #17594

### CODE REVIEW

File: pkg/backend/display/progress.go [hunk 1]
```diff
@@ -1309,6 +1308,11 @@ func (display *ProgressDisplay) handleProgressEvent(payload engine.ProgressEvent
 		display.progressEventPayloads[payload.ID] = payload
 	}
 
+	// We have to release the lock before we call renderer.progress, because that may call back into a method that wants
+	// eventMutex.Lock(), causing a deadlock.
+	display.eventMutex.Unlock()
```
Comment (tgummerer) [inline pkg/backend/display/progress.go:1313]: Should we just unlock it right after `ensureHeaderAndStackRows` is done, since that's the only thing that needs the mutex at least according to the comment?

**Review by tgummerer — APPROVED** [review]
Did you manage to reproduce this?  

If I'm reading things correctly this should only happen if we have a `messageRenderer`, which looking at [this comment](https://github.com/pulumi/pulumi/blob/master/pkg/backend/display/tree.go#L63) should only happen on Windows?  Which wasn't the case at least for one of the reports in that ticket. Which makes me a little reluctant to call this fixed even with this change unless we can repro the issue, or figure out the exact codepath in which this can happen.

File: pkg/backend/display/progress.go (hunk 1 above)
Comment (lunaris) [reply pkg/backend/display/progress.go:1313]: I _think_ (am not sure) that the mutex also secures concurrent access to `display.progressEventPayloads`, hence this choice. To your question about whether this is an offending codepath, here's my tracing of it:

* This method, `ProgressDisplay.handleProgressEvent` calls `renderer.progress`
* `treeRenderer.progress` calls `treeRenderer.markDirty`
* `treeRenderer.markDirty` calls `treeRenderer.frame`
* `treeRenderer.frame` calls `treeRenderer.render`
* `treeRenderer.render` can call `ProgressDisplay.generateTreeNodes`
* `ProgressDisplay.generateTreeNodes` asks for an `RLock` on `eventMutex`, but if it's already write-locked, this is going to block.

So I think you can hit all this in the tree renderer, which would affect platforms on which we've heard of this issue cropping up.

To the question of whether it fixes -- I've spent quite a bit of time trying to reproduce the issue and have thus far failed (even targeting specific causes like this one). I was more thinking that at this point, merging this and attempt to resolve as fixed would be better than close/no-repro, which feels like the alternative given that we can't sink indefinite time into it. But open to thoughts/a better way.

Comment (tgummerer) [reply pkg/backend/display/progress.go:1313]: Oh, I missed the `markDirty` codepath!  It sounds so innocious by name, but it actually does a whole lot of stuff :/  

Now, I got too curious and wanted to see if I could repro it, and had some success :) It looks like this can happen if it takes a while to download all the plugins.  So creating terrible conditions on my network using `sudo tc qdisc change dev wlp0s20f3 root netem latency 400ms 10ms 25% loss 5% rate 100kbit`, and combining that with getting pulumi to download a bunch of plugins I did manage to get it to deadlock.

And indeed I could get it to break, here's the interesting backtraces:

```
(dlv) goroutine 44 bt
 0  0x000000000047ae0e in runtime.gopark
    at /usr/lib/go/src/runtime/proc.go:436
 1  0x00000000004593dd in runtime.goparkunlock
    at /usr/lib/go/src/runtime/proc.go:441
 2  0x00000000004593dd in runtime.semacquire1
    at /usr/lib/go/src/runtime/sema.go:188
 3  0x000000000047c3a5 in internal/sync.runtime_SemacquireMutex
    at /usr/lib/go/src/runtime/sema.go:95
 4  0x00000000004999bd in internal/sync.(*Mutex).lockSlow
    at /usr/lib/go/src/internal/sync/mutex.go:149
 5  0x00000000017a9805 in internal/sync.(*Mutex).Lock
    at /usr/lib/go/src/internal/sync/mutex.go:70
 6  0x00000000017a9805 in sync.(*Mutex).Lock
    at /usr/lib/go/src/sync/mutex.go:46
 7  0x00000000017a9805 in github.com/pulumi/pulumi/pkg/v3/backend/display.(*treeRenderer).markDirty
    at ./pkg/backend/display/tree.go:217
 8  0x00000000017a8993 in github.com/pulumi/pulumi/pkg/v3/backend/display.(*treeRenderer).progress
    at ./pkg/backend/display/tree.go:109
 9  0x00000000017a1969 in github.com/pulumi/pulumi/pkg/v3/backend/display.(*ProgressDisplay).handleProgressEvent
    at ./pkg/backend/display/progress.go:1312
10  0x00000000017a027a in github.com/pulumi/pulumi/pkg/v3/backend/display.(*ProgressDisplay).processNormalEvent
    at ./pkg/backend/display/progress.go:1160
11  0x00000000017a1db9 in github.com/pulumi/pulumi/pkg/v3/backend/display.(*ProgressDisplay).processEvents
    at ./pkg/backend/display/progress.go:1362
12  0x0000000001799fb2 in github.com/pulumi/pulumi/pkg/v3/backend/display.ShowProgressEvents
    at ./pkg/backend/display/progress.go:279
13  0x0000000001784f0a in github.com/pulumi/pulumi/pkg/v3/backend/display.ShowEvents
    at ./pkg/backend/display/display.go:135
14  0x0000000001c98b72 in github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudUpdate).RecordAndDisplayEvents.gowrap1
    at ./pkg/backend/httpstate/state.go:121
15  0x0000000000483061 in runtime.goexit
    at /usr/lib/go/src/runtime/asm_amd64.s:1700
```

```
(dlv) goroutine 73 bt
 0  0x000000000047ae0e in runtime.gopark
    at /usr/lib/go/src/runtime/proc.go:436
 1  0x00000000004593dd in runtime.goparkunlock
    at /usr/lib/go/src/runtime/proc.go:441
 2  0x00000000004593dd in runtime.semacquire1
    at /usr/lib/go/src/runtime/sema.go:188
 3  0x000000000047c405 in sync.runtime_SemacquireRWMutexR
    at /usr/lib/go/src/runtime/sema.go:100
 4  0x000000000179b1a9 in sync.(*RWMutex).RLock
    at /usr/lib/go/src/sync/rwmutex.go:74
 5  0x000000000179b1a9 in github.com/pulumi/pulumi/pkg/v3/backend/display.(*ProgressDisplay).generateTreeNodes
    at ./pkg/backend/display/progress.go:499
 6  0x00000000017a8e9a in github.com/pulumi/pulumi/pkg/v3/backend/display.(*treeRenderer).render
    at ./pkg/backend/display/tree.go:157
 7  0x00000000017a9a48 in github.com/pulumi/pulumi/pkg/v3/backend/display.(*treeRenderer).frame
    at ./pkg/backend/display/tree.go:255
 8  0x00000000017aa949 in github.com/pulumi/pulumi/pkg/v3/backend/display.(*treeRenderer).handleEvents
    at ./pkg/backend/display/tree.go:470
 9  0x00000000017a87a5 in github.com/pulumi/pulumi/pkg/v3/backend/display.newInteractiveRenderer.gowrap1
    at ./pkg/backend/display/tree.go:82
10  0x0000000000483061 in runtime.goexit
    at /usr/lib/go/src/runtime/asm_amd64.s:1700
```

So I *think* your fix indeed fixes it, gonna try my repro with the fix (but it can take a while).
