### PR TITLE
[dotnet] Add a lock around child resource manipulation 

### LINKED ISSUE #4821: Occasional exception during up
When running `pulumi up` in one of my projects I get the exception below from time to time. Not sure what it is causing it since the stack trace only refers to pulumi and .net code and not my code.

Is this a bug or is it me doing something weird? 

```
pulumi:pulumi:Stack (Sweetspot.core-dev):
    error: Running program 'C:\git\mastoj\sweetspot\src\infrastructure\Sweetspot.Infrastructure.Core\bin\Debug\netcoreapp3.1\Sweetspot.Infrastructure.Core.dll' failed with an unhandled exception:
    System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
       at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
       at System.Collections.Generic.HashSet`1.Add(T item)
       at Pulumi.Resource..ctor(String type, String name, Boolean custom, ResourceArgs args, ResourceOptions options)
       at Pulumi.CustomResource..ctor(String type, String name, ResourceArgs args, CustomResourceOptions options)
       at Pulumi.Kubernetes.KubernetesResource..ctor(String type, String name, DictionaryResourceArgs args, CustomResourceOptions options)
       at Pulumi.Kubernetes.Core.V1.Secret..ctor(String name, ImmutableDictionary`2 dictionary, CustomResourceOptions options)
       at Pulumi.Kubernetes.Yaml.Parser.<>c__DisplayClass3_0.<ParseYamlObject>b__100(String id)
       at Pulumi.Output`1.<>c__DisplayClass12_0`1.<Apply>b__0(T t)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.AllHelperAsync(ImmutableArray`1 inputs)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Add a lock around child resource manipulation to prevent hashset concurrency issues. Fix #4821

### CODE REVIEW

File: sdk/dotnet/Pulumi/Deployment/Deployment_Prepare.cs [hunk 1]
```diff
@@ -151,7 +151,12 @@ private static void AddTransitivelyReferencedChildResourcesOfComponentResources(
                 {
                     if (resource is ComponentResource)
                     {
-                        AddTransitivelyReferencedChildResourcesOfComponentResources(resource.ChildResources, result);
+                        HashSet<Resource> childResources = new HashSet<Resource>();
+                        lock (resource.ChildResources)
+                        {
+                            childResources.AddRange(resource.ChildResources);
+                        }
+                        AddTransitivelyReferencedChildResourcesOfComponentResources(childResources, result);
```
Comment (justinvp) [inline sdk/dotnet/Pulumi/Deployment/Deployment_Prepare.cs:159]: I doubt it makes much of a measurable difference, but leveraging [`HashSet<T>`'s constructor](https://github.com/dotnet/runtime/blob/477363b27c658bc4f89bab3995386760e95ee8ef/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/HashSet.cs#L86) to do the copy should be more efficient than using our `AddRange` helper. (Haven't actually tried it):

```suggestion
                        HashSet<Resource> childResources;
                        lock (resource.ChildResources)
                        {
                            childResources = new HashSet<Resource>(resource.ChildResources);
                        }
                        AddTransitivelyReferencedChildResourcesOfComponentResources(childResources, result);
```

**Review by justinvp — APPROVED** [review]
LGTM
