### PR TITLE
Fixes panic when generating go from pulumi yaml

### LINKED ISSUE #10033: pulumi convert panics when converting iam.Policy to Go
### What happened?

When trying to convert a simple program to go, the convert command throws a panic:

```
goroutine 1 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.17.11/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x5713280, 0xc006b73ee0})
	/Users/runner/hostedtoolcache/go/1.17.11/x64/src/runtime/panic.go:1038 +0x215
github.com/pulumi/pulumi/pkg/v3/codegen/go.GenerateProgramWithOptions(0xc0004227c0, {0x40})
	/Users/runner/work/pulumi/pulumi/pkg/codegen/go/gen_program.go:121 +0x7b3
github.com/pulumi/pulumi/pkg/v3/codegen/go.GenerateProgram(...)
	/Users/runner/work/pulumi/pulumi/pkg/codegen/go/gen_program.go:55
github.com/pulumi/pulumi/pkg/v3/codegen/go.GenerateProject({0x7ff7bfeff3eb, 0x2}, {{0xc00082f9b0, 0x10}, {{0xc00082f9d0, 0x4}, 0x0}, {0x0, 0x0}, 0xc0003c1dc0, ...}, ...)
	/Users/runner/work/pulumi/pulumi/pkg/codegen/go/gen_program.go:131 +0x4b
main.newConvertCmd.func1(0xf, {0xc000830e00, 0xc000b57d90, 0x41f4225})
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/convert.go:89 +0x3bc
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000932280, {0xc000439400, 0x0, 0x4})
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc000932280, {0xc0004393c0, 0x4, 0x4})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000740c80)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
```

### Steps to reproduce

Given the following pulumi-yaml code:

```
name: pulumi-yaml-abac
runtime: yaml
description: A minimal Pulumi YAML program

resources:
  createPolicy:
    type: aws:iam:Policy
    properties:
      policy:
        Fn::ToJSON:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 'lambda:*'
              Resource: 'arn:aws:lambda:*:*:function:*'
              Condition:
                StringEquals:
                  aws:RequestTag/Team:
                    - iamuser-admin
                    - iamuser2-admin
                ForAllValues:StringEquals:
                  aws:TagKeys:
                    - Team

```

The command to convert causes a panic:

```
pulumi convert --language go --out go
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.35.2
Go Version:       go1.17.11
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            invalid Go source code:

package main

import (
"encoding/json"

"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/iam"
)
func main() {
pulumi.Run(func(ctx *pulumi.Context) error {
tmpJSON0, err := json.Marshal(%!v(PANIC=Format method: runtime error: index out of range [1] with length 1))
if err != nil {
return err
}
json0 := string(tmpJSON0)
_, err := iam.NewPolicy(ctx, "createPolicy", &iam.PolicyArgs{
Policy: pulumi.String(json0),
})
if err != nil {
return err
}
return nil
})
}
: 11:31: expected operand, found '%' (and 10 more errors)

goroutine 1 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.17.11/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x5713280, 0xc006b73ee0})
	/Users/runner/hostedtoolcache/go/1.17.11/x64/src/runtime/panic.go:1038 +0x215
github.com/pulumi/pulumi/pkg/v3/codegen/go.GenerateProgramWithOptions(0xc0004227c0, {0x40})
	/Users/runner/work/pulumi/pulumi/pkg/codegen/go/gen_program.go:121 +0x7b3
github.com/pulumi/pulumi/pkg/v3/codegen/go.GenerateProgram(...)
	/Users/runner/work/pulumi/pulumi/pkg/codegen/go/gen_program.go:55
github.com/pulumi/pulumi/pkg/v3/codegen/go.GenerateProject({0x7ff7bfeff3eb, 0x2}, {{0xc00082f9b0, 0x10}, {{0xc00082f9d0, 0x4}, 0x0}, {0x0, 0x0}, 0xc0003c1dc0, ...}, ...)
	/Users/runner/work/pulumi/pulumi/pkg/codegen/go/gen_program.go:131 +0x4b
main.newConvertCmd.func1(0xf, {0xc000830e00, 0xc000b57d90, 0x41f4225})
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/convert.go:89 +0x3bc
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000932280, {0xc000439400, 0x0, 0x4})
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc000932280, {0xc0004393c0, 0x4, 0x4})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000740c80)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
```

### Expected Behavior

The code should convert successfully to something like:

```
package main

import (
	"encoding/json"

	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/iam"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		tmpJSON0, err := json.Marshal(map[string]interface{}{
			"Version": "2012-10-17",
			"Statement": []map[string]interface{}{
				map[string]interface{}{
					"Effect":   "Allow",
					"Action":   "lambda:*",
					"Resource": "arn:aws:lambda:*:*:function:*",
					"Condition": map[string]interface{}{
						"StringEquals": map[string]interface{}{
							"aws:RequestTag/Team": []string{
								"iamuser-admin",
								"iamuser2-admin",
							},
						},
						"ForAllValues:StringEquals": map[string]interface{}{
							"aws:TagKeys": []string{
								"Team",
							},
						},
					},
				},
			},
		})
		if err != nil {
			return err
		}
		json0 := string(tmpJSON0)
		_, err := iam.NewPolicy(ctx, "createPolicy", &iam.PolicyArgs{
			Policy: pulumi.String(json0),
		})
		if err != nil {
			return err
		}
		return nil
	})
}

```

### Actual Behavior

the code threw a panic

### Versions used

```
pulumi about
CLI
Version      3.35.2
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME  VERSION
aws   unknown
yaml  unknown

Host
OS       darwin
Version  12.2.1
Arch     x86_64

This project is written in yaml

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/stack72
User           stack72
Organizations  stack72, moolumi, pulumiverse, demo, pulumi, pulumi

Pulumi locates its logs in /var/folders/p2/lsp6bhtn4qz4f3xv9zfzmpg40000gq/T/ by default
warning: A new version of Pulumi is available. To upgrade from version '3.35.2' to '3.35.3', run
   $ brew upgrade pulumi
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

Fixes #10033

Chased down the issue by first extracting the intermediate generated PCL and wrote a program-gen test for it only for go:
```
resource createPolicy "aws:iam/policy:Policy" {
        __logicalName = "createPolicy"
        policy = toJSON({
                "Version" = "2012-10-17",
                "Statement" = [{
                        "Effect" = "Allow",
                        "Action" = "lambda:*",
                        "Resource" = "arn:aws:lambda:*:*:function:*",
                        "Condition" = {
                                "StringEquals" = {
                                        "aws:RequestTag/Team" = [
                                                "iamuser-admin",
                                                "iamuser2-admin"
                                        ]
                                },
                                "ForAllValues:StringEquals" = {
                                        "aws:TagKeys" = ["Team"]
                                }
                        }
                }]
        })
}
```

Turns out the problem was with the way a traverser object was created from a template expression with one part of literal string. The fix is simplify the creation of the traverser as a simple literal value from the template expression (getting the value of the literal string) 

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/codegen/pcl/rewrite_convert.go [hunk 1]
```diff
@@ -102,9 +102,14 @@ func rewriteConversions(x model.Expression, to model.Type) (model.Expression, bo
 			var traverser hcl.Traverser
 			if lit, ok := item.Key.(*model.LiteralValueExpression); ok {
 				traverser = hcl.TraverseIndex{Key: lit.Value}
+			} else if temp, isTemp := item.Key.(*model.TemplateExpression); isTemp && len(temp.Parts) == 1 {
+				if literal, isLiteral := temp.Parts[0].(*model.LiteralValueExpression); isLiteral {
+					traverser = hcl.TraverseIndex{Key: literal.Value}
+				}
```
Comment (iwahbe) [inline pkg/codegen/pcl/rewrite_convert.go:108]: What happens in the else case? Do we intend to leave `traverser` uninitialized?

Comment (Zaid-Ajaj) [reply pkg/codegen/pcl/rewrite_convert.go:108]: I assumed that doesn't happen but just in case I guess we can initialize it to `model.MakeTraverser(model.StringType)` but I am not sure how that works when it doesn't know which value to use as a traverser

Comment (iwahbe) [reply pkg/codegen/pcl/rewrite_convert.go:110]: If you don't think that a `model.MakeTraverser(model.StringType)` makes sense, should we explicitly `panic`? If it does make sense, should we move the default case to when we initialize `traverser`? Then we can remove both `else` final cases. I think this communicates that this is the default case more clearly?

Comment (AaronFriel) [reply pkg/codegen/pcl/rewrite_convert.go:108]: @iwahbe I've updated the PR with a default initialization here, but I'm not sure if it's correct still. I'd rather it be incorrect and proceed however, in case it can later recover with a diagnostic, than panic.

Tests updated and rebased on #10043 without duplicating the .pp files.

**Review by iwahbe — COMMENTED** [review]
I think the change is good, but I'm concerned with leaving a known invalid state representable without any diagnostic message. 

`rewriteConversions` is only used recursively and in `RewriteConversions`. `RewriteConversions` is only used once per language, and always in the context of a `generator` method (which can accumulate diagnostics). I think it is work accumulating the diagnostics.

**Review by iwahbe — APPROVED** [review]
LGTM. We will need to fix Java in another PR.
