### PR TITLE
edit.DeleteResource now deletes by reference rather than by URN

### LINKED ISSUE #12077: two resources pending deletion, can't delete either
### What happened?

My stack has two resources pending deletion with the same URN. I can't delete either of the resources pending deletion, because it will leave behind a resource that does not exist.

```bash
Pulumi Version:   v3.53.1
Go Version:       go1.19.5
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: error An assertion has failed: state edit produced an invalid snapshot. source error: resource urn:pulumi:shared.development::shared::swm:shared-infra:GhaRepoSecret$swm:shared-infra:GhaRepoSecret$github:index/actionsSecret:ActionsSecret::github-cicd-aws-access-key-id-serverless-mono dependency urn:pulumi:shared.development::shared::swm:shared-infra:IamAccessKey$aws:iam/accessKey:AccessKey::github-cicd refers to missing resource

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/Cellar/go/1.19.5/libexec/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/private/tmp/pulumi-20230125-4583-1posyjz/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x101c92a20, 0xc000bb7680})
	/usr/local/Cellar/go/1.19.5/libexec/src/runtime/panic.go:884 +0x212
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
	/private/tmp/pulumi-20230125-4583-1posyjz/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.AssertNoErrorf({0x1027214c0?, 0xc000bb7650?}, {0x10219f83b?, 0x0?}, {0x0?, 0x0?, 0x0?})
	/private/tmp/pulumi-20230125-4583-1posyjz/sdk/go/common/util/contract/assert.go:47 +0x139
main.totalStateEdit({0x1027425a8, 0xc0000580c0}, {0x102755438, 0xc001230ae0}, 0x1, {{0x10213a6de, 0x6}, 0x0, 0x0, 0x0, ...}, ...)
	/private/tmp/pulumi-20230125-4583-1posyjz/pkg/cmd/pulumi/state.go:173 +0x33e
main.runTotalStateEdit({0x1027425a8, 0xc0000580c0}, {0x7ff7bfeff5ff, 0x12}, 0x0?, 0x0?)
	/private/tmp/pulumi-20230125-4583-1posyjz/pkg/cmd/pulumi/state.go:138 +0x1de
main.runStateEdit({0x1027425a8?, 0xc0000580c0?}, {0x7ff7bfeff5ff?, 0x0?}, 0x0?, {0x7ff7bfeff624?, 0x0?}, 0x0?)
	/private/tmp/pulumi-20230125-4583-1posyjz/pkg/cmd/pulumi/state.go:116 +0x68
main.newStateDeleteCommand.func1(0x0?, {0xc0003ace60, 0x1, 0x0?})
	/private/tmp/pulumi-20230125-4583-1posyjz/pkg/cmd/pulumi/state_delete.go:60 +0x13f
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc00100c900?, {0xc0003ace60, 0x1, 0x5})
	/private/tmp/pulumi-20230125-4583-1posyjz/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc00100c900, {0xc0003ace10, 0x5, 0x5})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e6c300)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/private/tmp/pulumi-20230125-4583-1posyjz/pkg/cmd/pulumi/main.go:48 +0x45
```

### Expected Behavior

When I choose one of the resources pending for deletion, the resource chosen is removed from pulumi state.

However, it throws an error instead.

### Steps to reproduce

```bash
pulumi stack delete '<urn>'
# pulumi prompts for a resource to delete
```

image

### Output of `pulumi about`

```
CLI          
Version      3.53.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.2
Arch     x86_64

This project is written in nodejs: executable='/Users/bennett/Library/pnpm/node' version='v18.14.0'

Current Stack: shared.staging

TYPE                                                                                        URN
pulumi:pulumi:Stack                                                                         urn:pulumi:shared.staging::shared::pulumi:pulumi:Stack::shared-shared.staging
swm:shared-infra:misc/BPSalesBucket                                                         urn:pulumi:shared.staging::shared::swm:shared-infra:misc/BPSalesBucket::shared-staging-bp-sales
swm:shared-infra:shared/StandardIamRoles                                                    urn:pulumi:shared.staging::shared::swm:shared-infra:shared/StandardIamRoles::shared-staging-iam
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::default_5_13_0
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-985325605018-us-east-1
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-435426432848
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-435426432848-us-east-1
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-741858248043-us-east-1
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-291971919224
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-741858248043
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-941214869665-us-east-1
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-941214869665
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-targetaccount
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-048472964993-us-east-1
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-330966326268-us-east-1
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-330966326268
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-985325605018
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-291971919224-us-east-1
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-targetaccount-us-east-1
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-300951746504-us-east-1
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-300951746504
pulumi:providers:aws                                                                        urn:pulumi:shared.staging::shared::pulumi:providers:aws::shared-staging-048472964993
aws:s3/bucketV2:BucketV2                                                                    urn:pulumi:shared.staging::shared::swm:shared-infra:misc/BPSalesBucket$aws:s3/bucketV2:BucketV2::shared-staging-bp-sales
aws:iam/role:Role                                                                           urn:pulumi:shared.staging::shared::swm:shared-infra:shared/StandardIamRoles$aws:iam/role:Role::shared-staging-iam-deprecated
aws:iam/role:Role                                                                           urn:pulumi:shared.staging::shared::swm:shared-infra:shared/StandardIamRoles$aws:iam/role:Role::shared-staging-iam-base
aws:iam/policy:Policy                                                                       urn:pulumi:shared.staging::shared::swm:shared-infra:shared/StandardIamRoles$aws:iam/policy:Policy::shared-staging-iam-deprecated
aws:iam/policy:Policy                                                                       urn:pulumi:shared.staging::shared::swm:shared-infra:shared/StandardIamRoles$aws:iam/policy:Policy::shared-staging-iam-base
aws:s3/bucketAclV2:BucketAclV2                                                              urn:pulumi:shared.staging::shared::swm:shared-infra:misc/BPSalesBucket$aws:s3/bucketAclV2:BucketAclV2::shared-staging-bp-sales
aws:s3/bucketLifecycleConfigurationV2:BucketLifecycleConfigurationV2                        urn:pulumi:shared.staging::shared::swm:shared-infra:misc/BPSalesBucket$aws:s3/bucketLifecycleConfigurationV2:BucketLifecycleConfigurationV2::shared-staging-bp-sales
aws:s3/bucketOwnershipControls:BucketOwnershipControls                                      urn:pulumi:shared.staging::shared::swm:shared-infra:misc/BPSalesBucket$aws:s3/bucketOwnershipControls:BucketOwnershipControls::shared-staging-bp-sales
aws:s3/bucketServerSideEncryptionConfigurationV2:BucketServerSideEncryptionConfigurationV2  urn:pulumi:shared.staging::shared::swm:shared-infra:misc/BPSalesBucket$aws:s3/bucketServerSideEncryptionConfigurationV2:BucketServerSideEncryptionConfigurationV2::shared-staging-bp-sales
aws:s3/bucketPublicAccessBlock:BucketPublicAccessBlock                                      urn:pulumi:shared.staging::shared::swm:shared-infra:misc/BPSalesBucket$aws:s3/bucketPublicAccessBlock:BucketPublicAccessBlock::shared-staging-bp-sales
aws:iam/instanceProfile:InstanceProfile                                                     urn:pulumi:shared.staging::shared::swm:shared-infra:shared/StandardIamRoles$aws:iam/instanceProfile:InstanceProfile::shared-staging-iam-deprecated
aws:iam/rolePolicyAttachment:RolePolicyAttachment                                           urn:pulumi:shared.staging::shared::swm:shared-infra:shared/StandardIamRoles$aws:iam/rolePolicyAttachment:RolePolicyAttachment::shared-staging-iam-deprecated-0
aws:iam/rolePolicyAttachment:RolePolicyAttachment                                           urn:pulumi:shared.staging::shared::swm:shared-infra:shared/StandardIamRoles$aws:iam/rolePolicyAttachment:RolePolicyAttachment::shared-staging-iam-deprecated-1
aws:iam/rolePolicyAttachment:RolePolicyAttachment                                           urn:pulumi:shared.staging::shared::swm:shared-infra:shared/StandardIamRoles$aws:iam/rolePolicyAttachment:RolePolicyAttachment::shared-staging-iam-base-1
aws:iam/instanceProfile:InstanceProfile                                                     urn:pulumi:shared.staging::shared::swm:shared-infra:shared/StandardIamRoles$aws:iam/instanceProfile:InstanceProfile::shared-staging-iam-base
aws:iam/rolePolicyAttachment:RolePolicyAttachment                                           urn:pulumi:shared.staging::shared::swm:shared-infra:shared/StandardIamRoles$aws:iam/rolePolicyAttachment:RolePolicyAttachment::shared-staging-iam-base-0
aws:iam/rolePolicyAttachment:RolePolicyAttachment                                           urn:pulumi:shared.staging::shared::swm:shared-infra:shared/StandardIamRoles$aws:iam/rolePolicyAttachment:RolePolicyAttachment::shared-staging-iam-deprecated-3
aws:iam/rolePolicyAttachment:RolePolicyAttachment                                           urn:pulumi:shared.staging::shared::swm:shared-infra:shared/StandardIamRoles$aws:iam/rolePolicyAttachment:RolePolicyAttachment::shared-staging-iam-base-2
aws:iam/rolePolicyAttachment:RolePolicyAttachment                                           urn:pulumi:shared.staging::shared::swm:shared-infra:shared/StandardIamRoles$aws:iam/rolePolicyAttachment:RolePolicyAttachment::shared-staging-iam-deprecated-2
aws:iam/policy:Policy                                                                       urn:pulumi:shared.staging::shared::swm:shared-infra:misc/BPSalesBucket$aws:iam/policy:Policy::shared-staging-bp-sales-full-control
aws:s3/bucketPolicy:BucketPolicy                                                            urn:pulumi:shared.staging::shared::swm:shared-infra:misc/BPSalesBucket$aws:s3/bucketPolicy:BucketPolicy::shared-staging-bp-sales
aws:iam/userPolicyAttachment:UserPolicyAttachment                                           urn:pulumi:shared.staging::shared::swm:shared-infra:misc/BPSalesBucket$aws:iam/userPolicyAttachment:UserPolicyAttachment::shared-staging-bp-sales-full-control-0


Found no pending operations associated with shared.staging

Backend        
Name           MacBook-Pro-16.local
URL            s3://pulumi-state.swmdigital.io
User           bennett
Organizations  

Pulumi locates its logs in /var/folders/7d/69pdjd9j50qb_g2m88x355r00000gn/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either /Users/bennett/src/shared-infra/apps/shared/yarn.lock or /Users/bennett/src/shared-infra/apps/shared/package-lock.json
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #12110: `pulumi state delete <urn>` prompts for which duplicate URN to delete and deletes all of them.
It seems that the current interactive behavior for `pulumi state delete <urn>` when there are duplicate URNs is to ask the user to pick which of the resources to delete and then deleting any resource with the same URN so all of them are deleted.

repro recording https://asciinema.org/a/yrnOpuY6pegWUMN0tG6atHkpH

related to #12077

### PR DESCRIPTION
**Pull request by dixler**
# Description
This PR fixes an issue where 'pulumi state delete <urn>' would prompt the user to disambiguate between multiple resources in state with the same URN and proceed to delete all of them. With this change, dependency checks are performed only if the deletion will lead to no resources possessing the URN. The targetDependents flag will only target dependents if the deleted resource will orphan the dependents.

Fixes #12077 
Fixes #12110 

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/resource/edit/operations.go [hunk 1]
```diff
@@ -86,20 +99,30 @@ func DeleteResource(
...
+		if deleteSet[res.URN] {
+			//  Skip resources to be deleted.
+			continue
+		}
+
 		// While iterating, keep track of the set of resources that are parented to our
 		// condemned resource. This acts as a check on DependingOn, preventing a bug from
 		// introducing state corruption.
-		if res.Parent == condemnedRes.URN && !deleteSet[res.URN] {
+		if res.Parent == condemnedRes.URN {
```
Comment (dixler) [inline pkg/resource/edit/operations.go:115]: The short circuit removes this check.

File: pkg/resource/edit/operations.go [hunk 2]
```diff
@@ -63,43 +63,66 @@ func DeleteResource(
...
+				deleteSet[dep.URN] = true
 			}
-			deleteSet[dep.URN] = true
 		}
 	}
 
 	// If there are no resources that depend on condemnedRes, iterate through the snapshot and keep everything that's
 	// not condemnedRes.
-	var newSnapshot []*resource.State
+	newSnapshot := make([]*resource.State, 0, len(snapshot.Resources))
```
Comment (dixler) [inline pkg/resource/edit/operations.go:99]: linter told me to do it

File: pkg/resource/edit/operations_test.go [hunk 3]
```diff
@@ -91,6 +91,55 @@ func TestDeletion(t *testing.T) {
...
+		snap := NewSnapshot([]*resource.State{
+			pA, a, b1, b2, b3, c,
+		})
+
+		err := DeleteResource(snap, b1, nil, true /* targetDependents */)
+		require.NoError(t, err)
+
+		assert.Equal(t, []*resource.State{
+			pA, a, b2, b3, c,
+		}, snap.Resources)
```
Comment (abhinav) [inline pkg/resource/edit/operations_test.go:125]: Use of assert.Equal here ends up not validating the reference-based deletion because assert.Equal does a deep equals.

If you replace the assert.Equal LHS with `{pA, a, b1, b3, c}`, it will still pass because b2 deep equals b1.

To verify the new behavior correctly, we need to do a reference match.
testify does not include a referential matching helper
so the simplest way to verify this might be to loop through the slice and do `==` comparisons.

```go
// assert.Equals or assert.NotContains
// are not enough because b1 deep equals b2 and b3.
for _, s := range snap.Resources {
  assert.False(t, s == b1)
}
```

File: pkg/resource/edit/operations_test.go [hunk 4]
```diff
@@ -91,6 +91,67 @@ func TestDeletion(t *testing.T) {
...
+		snap := NewSnapshot([]*resource.State{
+			pA, a, b1, b2, b3, c,
+		})
+
+		err := DeleteResource(snap, b1, nil, false /* targetDependents */)
+		require.NoError(t, err)
+
+		// assert.Equals does a deep equals with the expected list.
+		assert.Equal(t, []*resource.State{
+			pA, a, b2, b3, c,
```
Comment (abhinav) [inline pkg/resource/edit/operations_test.go:145]: I'm not sure how these two test cases are different in terms of behavior tested.
The `true`/`false` on targetDependents doesn't change the rest of the test.
Would it be more useful to delete something with dependents in do-target-dependents?

Optionally, I would also consider a test with targetDependents false that tries to delete pA,
and `assert.ErrorAs` the result:

    err := DeleteResource(snap, pA, nil, false /* targetDependents */)
    assert.ErrorAs(t, err, &ResourceHasDependenciesError{})

File: pkg/resource/edit/operations.go [hunk 5]
```diff
@@ -63,43 +63,65 @@ func DeleteResource(
...
+	isUniqueURN := numSameURN <= 1
+	// If there's only one resource (or less), determine dependencies to be deleted from state.
+	if isUniqueURN {
+		// condemnedRes.URN is unique. We can safely delete it by URN.
+		deleteSet[condemnedRes.URN] = struct{}{}
+		dg := graph.NewDependencyGraph(snapshot.Resources)
+
+		if deps := dg.DependingOn(condemnedRes, nil, true); len(deps) != 0 {
+			if !targetDependents {
+				return ResourceHasDependenciesError{Condemned: condemnedRes, Dependencies: deps}
```
Comment (abhinav) [inline pkg/resource/edit/operations.go:85]: Out of scope for this PR but:

Error structs should almost always use pointer receivers for the Error method (which would make this `return &ResourceHasDependenciesError{..}`).
That keeps them comparable via references with `==`, even if they contain uncomparable fields like slices (which this one does).

Right now, `errors.Is(err, err)` on a ResourceHasDependenciesError will fail even if it's the same object.
(demo: https://go.dev/play/p/2OJl_QsL_cH)

**Review by abhinav — APPROVED** [review]
LGTM minus minor comments and a possible follow-up

File: pkg/resource/edit/operations_test.go (hunk 4 above)
Comment (dixler) [reply pkg/resource/edit/operations_test.go:145]: There are some existing tests on this code so I didn't consider adding too many more.

Given the motivation for this PR was #12077, I want to make sure that the command is successful when targetDependents is false.

`do-target-dependents` does potentially target c because c depends on the URN that b1, b2, and b3 all share.

thx for the very thought provoking question. I will add a comment to clarify intent and context around the addition of these tests.

**Comment by dixler** [comment]
bors merge
