### PR TITLE
schema check and reserve pulumi keyword

### LINKED ISSUE #18994: Python codegen breaks if there is a property called "pulumi"
### What happened?

It seems that "pulumi" might be a reserved property name, but instead of failing fast Python codegen produces code that does not work.

### Example

https://github.com/pulumi/pulumi-terraform-provider/issues/74 a user encountered this during any-terraform-provider work on spacelift.

### Output of `pulumi about`

N/A

### Additional context

Appreciate making a call here if we want to support "pulumi" property name or make it reserved, in the latter case fail fast on schemas that contain it. IN the meanwhile we can instruct pulumi-any-terraform-provider to rename it to something that does work, i.e. `pulumi_`.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by brandonpollack23**
Python codegen breaks due to the pulumi key name being reserved.  This change is a first pass at adding various checks to the schema to fail instead of generating the failing program.

Also added some diags that were not returned due to error.  Error should be checked but diags might be useful (as they are in these tests) so I moved some things around a bit to return them

Fixes #18994

### CODE REVIEW

**Comment by Frassle** [comment]
Moar PR description please

File: pkg/codegen/schema/bind.go [hunk 1]
```diff
@@ -1468,6 +1468,8 @@ func bindConfig(spec ConfigSpec, types *types) ([]*Property, hcl.Diagnostics, er
 	for _, property := range properties {
 		if property.Name == "version" {
 			diags = diags.Append(errorf("#/config/variables/version", "version is a reserved configuration key"))
+		} else if property.Name == "pulumi" {
```
Comment (Frassle) [inline pkg/codegen/schema/bind.go:1471]: Feels like this should be a loop over reserved words rather than multiple if checks

File: pkg/codegen/schema/schema_test.go [hunk 2]
```diff
@@ -827,6 +827,11 @@ func TestUsingUrnInResourcePropertiesEmitsWarning(t *testing.T) {
 								Type: "string",
 							},
 						},
+						"pulumi": {
```
Comment (Frassle) [inline pkg/codegen/schema/schema_test.go:830]: Test name needs updating now we're checking pulumi as well as urn

File: pkg/codegen/schema/schema_test.go [hunk 3]
```diff
@@ -1985,6 +2011,11 @@ func TestProviderVersionIsAnError(t *testing.T) {
 							Type: "string",
 						},
 					},
+					"pulumi": {
+						TypeSpec: TypeSpec{
+							Type: "string",
+						},
+					},
```
Comment (Frassle) [inline pkg/codegen/schema/schema_test.go:2018]: Can we add a test that you can't define a resource, function or type called "pulumi"

File: pkg/codegen/schema/bind.go (hunk 1 above)
Comment (brandonpollack23) [reply pkg/codegen/schema/bind.go:1471]: Indeed, that way we can define them in one place as well and define a function to check it and handle so in the future (once we find all the places) we can always just add a word and it works.

File: pkg/codegen/schema/schema_test.go (hunk 3 above)
Comment (brandonpollack23) [reply pkg/codegen/schema/schema_test.go:2018]: This should be good now

**Comment by brandonpollack23** [comment]
Ping on this one @Frassle :)

File: pkg/codegen/schema/reserved_keywords.go [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+
+package schema
+
+import "slices"
+
+var (
+	// These property names are reserved
+	reservedKeywords = []string{"pulumi"}
+
+	reservedPropertyNames = []string{"version"}
```
Comment (Frassle) [inline pkg/codegen/schema/reserved_keywords.go:23]: version actually only needs to be reserved at the top level, a resource can't have a property "version" but it's fine for some sub-structure to have that property.

Comment (brandonpollack23) [reply pkg/codegen/schema/reserved_keywords.go]: Hmm Ok I think this new change does what you say, but could use a second look

File: pkg/codegen/schema/reserved_keywords.go [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+	reservedResourcePropertyKeys = []string{"urn"}
+	// These are only reserved for non-component resources
+	reservedNonComponentPropertyKeys = []string{"id"}
+)
+
+func isReservedKeyword(name string) bool {
+	return slices.Contains(reservedKeywords, name)
+}
+
+func isReservedTopLevelPropertyName(name string) bool {
```
Comment (Frassle) [inline pkg/codegen/schema/reserved_keywords.go:35]: Maybe better called `isReservedProviderPropertyName`? config is also passed as provider properties so makes sense there as well.

File: pkg/codegen/schema/reserved_keywords.go [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+	return slices.Contains(reservedTopLevelPropertyNames, name) || isReservedKeyword(name)
+}
+
+func isReservedResourcePropertyKey(name string) bool {
+	return slices.Contains(reservedResourcePropertyKeys, name) || isReservedKeyword(name)
+}
+
+func isReservedNonComponentPropertyKey(name string) bool {
```
Comment (Frassle) [inline pkg/codegen/schema/reserved_keywords.go:43]:
```suggestion
func isReservedCustomResourcePropertyKey(name string) bool {
```

File: pkg/codegen/schema/reserved_keywords.go [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+
+func isReservedKeyword(name string) bool {
+	return slices.Contains(reservedKeywords, name)
+}
+
+func isReservedTopLevelPropertyName(name string) bool {
+	return slices.Contains(reservedTopLevelPropertyNames, name) || isReservedKeyword(name)
+}
+
+func isReservedResourcePropertyKey(name string) bool {
```
Comment (Frassle) [inline pkg/codegen/schema/reserved_keywords.go:39]:
```suggestion
func isReservedComponentResourcePropertyKey(name string) bool {
```

File: pkg/codegen/schema/reserved_keywords.go [hunk 8]
```diff
@@ -0,0 +1,49 @@
...
+	return slices.Contains(reservedResourcePropertyKeys, name) || isReservedKeyword(name)
+}
+
+func isReservedNonComponentPropertyKey(name string) bool {
+	return slices.Contains(reservedNonComponentPropertyKeys, name)
+}
+
+func isReservedConfigKey(name string) bool {
+	return isReservedKeyword(name)
+}
```
Comment (Frassle) [inline pkg/codegen/schema/reserved_keywords.go:49]:
```suggestion

```

Just use isReservedProviderPropertyName for both provider inputs and config, they both end up as provider properties.

File: pkg/codegen/schema/schema_test.go [hunk 9]
```diff
@@ -865,6 +870,11 @@ func TestUsingUrnInResourcePropertiesEmitsWarning(t *testing.T) {
...
 							},
 						},
+						"pulumi": {
+							TypeSpec: TypeSpec{
+								Type: "string",
+							},
+						},
 					},
 				},
 			},
```
Comment (Frassle) [inline pkg/codegen/schema/schema_test.go:880]: We should test a type and a function with "pulumi" as a property here as well

File: pkg/codegen/schema/schema_test.go [hunk 10]
```diff
@@ -2020,10 +2044,11 @@ func TestProviderVersionIsAnError(t *testing.T) {
...
 	require.NoError(t, err)
 	require.True(t, diags.HasErrors())
-	assert.Equal(t, diags[0].Summary, "#/provider/properties/version: version is a reserved property name")
+	assert.Equal(t, diags[0].Summary, "#/provider/properties/pulumi: pulumi is a reserved property name")
+	assert.Equal(t, diags[1].Summary, "#/provider/properties/version: version is a reserved property name")
 
-	// Test that "version" is allowed as an output property on the provider object. Most providers probably won't add
-	// this, but it's there if they want to expose it.
+	// Test that reserved are allowed as an output property on the provider object.
+	// Most providers probably won't add this, but it's there if they want to expose it.
```
Comment (Frassle) [inline pkg/codegen/schema/schema_test.go:2051]: We should have some positive tests here as well that "version" is still ok for resource/type/function properties

File: pkg/codegen/schema/schema_test.go [hunk 11]
```diff
@@ -2048,6 +2078,70 @@ func TestProviderVersionIsAnError(t *testing.T) {
...
+		},
+		Types: map[string]ComplexTypeSpec{
+			"xyz:index:pulumi": {},
+		},
+	}
+
+	_, diags, _ := BindSpec(pkgSpec, loader)
+	assert.Len(t, diags, 2)
+	assert.Contains(t, diags[0].Summary, "is a reserved name")
+	assert.Contains(t, diags[1].Summary, "unknown primitive type")
```
Comment (Frassle) [inline pkg/codegen/schema/schema_test.go:2142]: fix this diagnostic

File: pkg/codegen/schema/schema_test.go [hunk 12]
```diff
@@ -2048,6 +2078,70 @@ func TestProviderVersionIsAnError(t *testing.T) {
...
+			ObjectTypeSpec: ObjectTypeSpec{},
+		},
+		Resources: map[string]ResourceSpec{
+			"xyz:index:pulumi": {},
+		},
+	}
+
+	_, diags, _ := BindSpec(pkgSpec, loader)
+	assert.Len(t, diags, 1)
+	assert.Contains(t, diags[0].Summary, "is a reserved name")
```
Comment (Frassle) [inline pkg/codegen/schema/schema_test.go:2120]:
```suggestion
	assert.Contains(t, diags[0].Summary, "resource name pulumi is reserved")
```
match the same as for function above, same for types below, make them all give the same error

File: pkg/codegen/schema/reserved_keywords.go (hunk 5 above)
Comment (brandonpollack23) [reply pkg/codegen/schema/reserved_keywords.go:35]: Sgtm

File: pkg/codegen/schema/reserved_keywords.go (hunk 6 above)
Comment (brandonpollack23) [reply pkg/codegen/schema/reserved_keywords.go:43]: sgtm

File: pkg/codegen/schema/schema_test.go (hunk 9 above)
Comment (brandonpollack23) [reply pkg/codegen/schema/schema_test.go:880]: I made separate tests for this

File: pkg/codegen/schema/schema_test.go (hunk 10 above)
Comment (brandonpollack23) [reply pkg/codegen/schema/schema_test.go:2236]: 👍

File: pkg/codegen/schema/schema_test.go (hunk 11 above)
Comment (brandonpollack23) [reply pkg/codegen/schema/schema_test.go:2327]: 👍

File: pkg/codegen/schema/schema_test.go [hunk 13]
```diff
@@ -877,14 +887,203 @@ func TestUsingUrnInResourcePropertiesEmitsWarning(t *testing.T) {
...
+			},
+		},
+	}
+
+	pkg, diags, err := BindSpec(pkgSpec, loader, ValidationOptions{
+		AllowDanglingReferences: true,
+	})
+	// No error as binding should work fine even with warnings
+	assert.NoError(t, err)
+	// assert that there are 2 warnings in the diagnostics because of using URN as a property
```
Comment (Frassle) [inline pkg/codegen/schema/schema_test.go:940]: rm comment

File: pkg/codegen/schema/schema_test.go [hunk 14]
```diff
@@ -877,14 +887,203 @@ func TestUsingUrnInResourcePropertiesEmitsWarning(t *testing.T) {
...
+	t.Parallel()
+	loader := NewPluginLoader(utils.NewHost(testdataPath))
+	pkgSpec := PackageSpec{
+		Name:    "test",
+		Version: "1.0.0",
+		Functions: map[string]FunctionSpec{
+			"test:index:fake": {
+				Inputs: &ObjectTypeSpec{
+					Properties: map[string]PropertySpec{
+						"pulumi": {
```
Comment (Frassle) [inline pkg/codegen/schema/schema_test.go:991]: Version should be ok, but I think pulumi should still be resevered inside function args?

File: pkg/codegen/schema/schema_test.go [hunk 15]
```diff
@@ -877,14 +887,203 @@ func TestUsingUrnInResourcePropertiesEmitsWarning(t *testing.T) {
...
+	loader := NewPluginLoader(utils.NewHost(testdataPath))
+	pkgSpec := PackageSpec{
+		Name:    "test",
+		Version: "1.0.0",
+		Types: map[string]ComplexTypeSpec{
+			"test:index:fake": {
+				ObjectTypeSpec: ObjectTypeSpec{
+					Type: "object",
+					Properties: map[string]PropertySpec{
+						"pulumi": {
```
Comment (Frassle) [inline pkg/codegen/schema/schema_test.go:1063]: Again, do we not want to reserve pulumi at every level?

File: pkg/codegen/schema/schema_test.go [hunk 16]
```diff
@@ -2048,6 +2263,80 @@ func TestProviderVersionIsAnError(t *testing.T) {
...
+						},
+					},
+				},
+			},
+		},
+	}
+
+	_, diags, _ := BindSpec(pkgSpec, loader, ValidationOptions{})
+	assert.Len(t, diags, 1)
+	assert.Contains(t, diags[0].Summary, "pulumi is a reserved name, cannot be used for type name")
```
Comment (Frassle) [inline pkg/codegen/schema/schema_test.go:2337]: Why are the errors for TestResourceWithKeynameOverlapFunction, TestResourceWithKeynameOverlapResource, and this inconsistent? They should all be phrased the same, like 'pulumi is a reserved name, cannot be used for X name'

File: pkg/codegen/schema/schema_test.go (hunk 14 above)
Comment (brandonpollack23) [reply pkg/codegen/schema/schema_test.go:991]: 👍

File: pkg/codegen/schema/schema_test.go (hunk 15 above)
Comment (brandonpollack23) [reply pkg/codegen/schema/schema_test.go:1063]: 👍

File: pkg/codegen/schema/schema_test.go (hunk 16 above)
Comment (brandonpollack23) [reply pkg/codegen/schema/schema_test.go:2337]: 👍

File: pkg/codegen/schema/schema_test.go [hunk 17]
```diff
@@ -878,11 +878,249 @@ func TestUsingUrnInResourcePropertiesEmitsWarning(t *testing.T) {
...
+	pkg, diags, err := BindSpec(pkgSpec, loader, ValidationOptions{
+		AllowDanglingReferences: true,
+	})
+	assert.Error(t, err)
+	assert.Len(t, diags, 1)
+	for _, diag := range diags {
+		assert.Equal(t, diag.Severity, hcl.DiagError)
+		assert.True(
+			t,
+			strings.Contains(diag.Summary, "pulumi is a reserved name, cannot be used for type name"),
```
Comment (Frassle) [inline pkg/codegen/schema/schema_test.go:1058]:
```suggestion
			strings.Contains(diag.Summary, "pulumi is a reserved name, cannot name type"),
```
For consistency

File: pkg/codegen/schema/bind.go [hunk 18]
```diff
@@ -750,7 +751,16 @@ func (t *types) bindTypeDef(token string, options ValidationOptions) (Type, hcl.
 		return nil, nil, err
 	}
 
+	var diags hcl.Diagnostics
 	path := memberPath("types", token)
+	parts := strings.Split(token, ":")
+	if len(parts) == 3 {
+		name := parts[2]
+		if isReservedKeyword(name) {
+			diags = append(diags, errorf(path, name+" is a reserved name, cannot be used for type name"))
```
Comment (Frassle) [inline pkg/codegen/schema/bind.go:760]:
```suggestion
			diags = append(diags, errorf(path, name+" is a reserved name, cannot name type"))
```
