### PR TITLE
[sdk/python] fix `fork/exec` warning

### LINKED ISSUE #9175: Error message is shown during the first command when main and virtualenv is set in Pulumi.yaml
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
When `main` and `virtualenv` is set in Pulumi.yaml then during the first command virtualenv is created and the following message is shown.

`Failed to resolve python version command: fork/exec <path to the project>/venv/bin/python: no such file or directory`

### Steps to reproduce

Given structure:

```
Pulumi.yaml
src/__main__.py
src/requirements.txt
```

Pulumi.yaml

```yaml
name: experiment
backend:
  url: file://.
main: src
runtime:
  name: python
  options:
    virtualenv: venv
```

requirements.txt
```
pulumi==3.26.1
```

When pulumi command is run for the first time (for example pulumi preview), the error message is shown.
```shell
pulumi preview
```

Consequent runs are ok.

Expected: No error message
Actual: 
```
Previewing update (test):
     Type                 Name             Plan     Info
     pulumi:pulumi:Stack  experiment-test           1 message

Diagnostics:
  pulumi:pulumi:Stack (experiment-test):
    Failed to resolve python version command: fork/exec <path to the project>/venv/bin/python: no such file or directory
```

### PR DESCRIPTION
**Pull request by dixler**
# Description
This PR moves the python version warning to after `virtualenv`s are initialized in order to ensure that the `python` in `venv/bin/` exists and the version command succeeds.

Fixes #9175

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: sdk/python/cmd/pulumi-language-python/main.go [hunk 1]
```diff
@@ -680,6 +679,7 @@ func (host *pythonLanguageHost) Run(ctx context.Context, req *pulumirpc.RunReque
 			return nil, err
 		}
 	}
+	validateVersion(ctx, host.virtualenvPath)
```
Comment (t0yv0) [inline sdk/python/cmd/pulumi-language-python/main.go:682]: Why is this in Run? 

Could we consider placing it right after `prepareVirtualEnvironment` call?

Comment (Frassle) [reply sdk/python/cmd/pulumi-language-python/main.go:682]: All this logic should be done in host start up, not run, really.

Comment (t0yv0) [reply sdk/python/cmd/pulumi-language-python/main.go:682]: Eh, I'm not so sure. Did I understand the idea in the PR correctly that validateVersion depends on creating the virtual environment and must run after it?  If this logic goes back to host startup, then we'd need to move prepareVirtualEnvironment to host startup, which may have tricky consequences. Perhaps if we can work out an alternative where validateVersion stays put where it is but gets smarter so it does not fail on empty venv, it would be better. After all creating virtual environments never changes the version of the Python interpreter AFAIK.

Comment (t0yv0) [reply sdk/python/cmd/pulumi-language-python/main.go:682]: More for the long term - I am skeptical of logic in host startup based on the experience with java lang provider, where convert started failing because host-startup assumed a project that wasn't there (yet). I've switched it to lazy-instantiation in response to gRPC methods.  If all work happens in response to gRPC methods, there's less coupling of the form "oh this startup logic will always run if I just want to call method XYZ even if XYZ does not need it.." But we might like to have a look at our gRPC methods some time and see if we're missing any, or document better in which sequence they're used.

Comment (dixler) [reply sdk/python/cmd/pulumi-language-python/main.go:682]: The version check actually doesn't fail. It only prints a warning message which surprised me when looking into this.

Comment (t0yv0) [reply sdk/python/cmd/pulumi-language-python/main.go:682]: SO the question is could you alter that and still get a satisfactory solution without moving the code to Run?

Comment (Frassle) [reply sdk/python/cmd/pulumi-language-python/main.go:682]: > More for the long term - I am skeptical of logic in host startup based on the experience with java lang provider, 

That's fair, I was thinking of "shimless" where we might not be calling Run but still need the venv setup. I guess it's just a case of making sure all the different entrypoints correctly call setup logic before actually running.

File: sdk/python/cmd/pulumi-language-python/main.go [hunk 2]
```diff
@@ -210,6 +209,8 @@ func (host *pythonLanguageHost) GetRequiredPlugins(ctx context.Context,
 		return nil, err
 	}
 
+	validateVersion(ctx, host.virtualenvPath)
```
Comment (dixler) [inline sdk/python/cmd/pulumi-language-python/main.go:212]: @t0yv0 I've moved it to GetRequiredPlugins as that is where the virtualEnv is configured(if needed) an dependencies are installed. It seems to make sense to put it here, but it depends on GetRequiredPlugins being invoked by something else prior to a Run call. It sounds like an ok assumption since if we didn't call this, programs would break.

File: sdk/python/cmd/pulumi-language-python/main.go (hunk 1 above)
Comment (dixler) [reply sdk/python/cmd/pulumi-language-python/main.go]: the motivation for putting the python version check here was because I wanted to make sure that anything that might happen around configuring a pulumi python program was settled before doing the version warning.

Putting it in GetRequiredPlugins means that we depend on running GetRequiredPlugins in order to warn the user that their version of python may not work.

I've moved the code according to your suggestion, but that was the motivation around my first choice.

**Review by t0yv0 — APPROVED** [review]
