### PR TITLE
[sdk/nodejs] emit colorized stack traces

### LINKED ISSUE #10379: [sdk/nodejs] improve nodejs stacktrace error message
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
currently we output large stack traces which makes it hard for users to determine where their errors are coming from. is there a way that we could reduce these without confusing users.

normally running a program via node/ts-node looks better as they both use color to draw attention to relevant details.

pulumi:
[asciicast](https://asciinema.org/a/aNwrthFasG38qoXdTFcrAar2l)

nodejs:
[asciicast](https://asciinema.org/a/qAfVccIYk8ob5pCecOe515TMn)

ts-node:
[asciicast](https://asciinema.org/a/D2esRjjXByUTPvt9RxuxxY0vc)

#### Solution

Pass through error message coloring to the error message output.

### PR DESCRIPTION
**Pull request by dixler**
# Description
This PR changes pulumi nodejs error logging to emit colorized stack traces to match nodejs's default behavior.

Fixes #10379 

New:
[asciicast](https://asciinema.org/a/wh2tFUZXqm8cXqVo5WcHEexii)

Current:
[asciicast](https://asciinema.org/a/IvTzhNHfsAj82FT115bXT4XSN)

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
Could you please add an example of a stacktrace with a few layers in a user program? (e.g. when an error happens in a callback in a function in a class )

**Comment by dixler** [comment]
@mikhailshilkov they look identical

New:
https://asciinema.org/a/qph5eRlYkVAEQcnvTZtwwV4DI

Current:
https://asciinema.org/a/928KfZrEO5P1ezmYlKOqZKsjE

**Comment by mikhailshilkov** [comment]
Oh! Where is the node garbage in this case? Does it only come up if the error is at the top level?

**Comment by dixler** [comment]
> Oh! Where is the node garbage in this case? Does it only come up if the error is at the top level?

it seems that node truncates stack traces and the node garbage was truncated.

**Comment by Frassle** [comment]
Does this behave well with piped output? I.e. if stdout is not a pty

**Comment by dixler** [comment]
> Does this behave well with piped output? I.e. if stdout is not a pty

I doubt it. I saw that pulumi python calls pip and it has color display so I was curious if we're concerned about this since I'm not sure if we optimize pulumi pipe experience. I know non-interactive still outputs colors, but I'd have to check what it does if it's outputting to a file.

**Comment by dixler** [comment]
Added code to strip out ANSI control codes before forwarding the DiagnosticEvent to the service.

File: pkg/backend/display/events.go [hunk 1]
```diff
@@ -18,6 +19,8 @@ import (
 	"github.com/pulumi/pulumi/sdk/v3/go/common/util/contract"
 )
 
+var matchAnsiControlCodes = regexp.MustCompile(`\x1b\[[0-9;]*[mK]`)
```
Comment (abhinav) [inline pkg/backend/display/events.go:22]: 👍 
This looks like it'll cover at least all color cases.
We can expand this if we need to cover more escape codes in the future.

**Review by abhinav — APPROVED** [review]

**Comment by dixler** [comment]
bors merge
