### PR TITLE
[sdk/go] Fix methods panic when marshaling `self`

### LINKED ISSUE #7603: [sdk/go] Panic when calling a method on a resource that implements `pulumi.Input`
We're seeing a panic when calling a method on a resource that implements `pulumi.Input`, which will be the case for all code-generated resources.

```
panic: reflect: nil type passed to Type.AssignableTo
goroutine 39 [running]:
reflect.(*rtype).AssignableTo(0x18d7ca0, 0x0, 0x0, 0xc0005be310)
	/usr/local/go/src/reflect/type.go:1445 +0xd3
github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputAndDetermineSecret(0x18d7ca0, 0xc0005be310, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/justin/go/src/github.com/pulumi/pulumi/sdk/go/pulumi/rpc.go:206 +0x31a5
github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInput(0x18d7ca0, 0xc0005be310, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/justin/go/src/github.com/pulumi/pulumi/sdk/go/pulumi/rpc.go:171 +0x73
github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).Call.func1(0x0, 0x0, 0x0)
	/Users/justin/go/src/github.com/pulumi/pulumi/sdk/go/pulumi/context.go:367 +0x236
github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).Call.func2(0xc0005d8000, 0x1954dda, 0x28, 0x1a36f70, 0xc0005be460, 0xc000112640)
	/Users/justin/go/src/github.com/pulumi/pulumi/sdk/go/pulumi/context.go:457 +0x122
created by github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).Call
	/Users/justin/go/src/github.com/pulumi/pulumi/sdk/go/pulumi/context.go:421 +0x225
```

### PR DESCRIPTION
**Pull request by justinvp**
Pass a valid `destType` to `marshalInput` to avoid panicing when the `self` resource implements `pulumi.Input`.

This issue would have been caught by testing the generated code, in addition to comparing it to what is expected.

Fixes #7603

### CODE REVIEW

File: tests/integration/construct_component_methods/go/main.go [hunk 1]
```diff
@@ -72,6 +72,10 @@ func (o ComponentGetMessageResultOutput) Message() pulumi.StringOutput {
 	return o.ApplyT(func(v ComponentGetMessageResult) string { return v.Message }).(pulumi.StringOutput)
 }
 
+func (*Component) ElementType() reflect.Type {
+	return reflect.TypeOf((*Component)(nil))
+}
```
Comment (justinvp) [inline tests/integration/construct_component_methods/go/main.go:77]: The test fails after adding this (making `*Component` implement `pulumi.Input`), and succeeds after the fix in `context.go`.

File: sdk/go/pulumi/context.go [hunk 2]
```diff
@@ -364,7 +364,7 @@ func (ctx *Context) Call(tok string, args Input, output Output, self Resource, o
 		// If we have a value for self, add it to the arguments.
 		if self != nil {
 			var deps []URN
-			resolvedSelf, selfDeps, err := marshalInput(self, nil, true)
+			resolvedSelf, selfDeps, err := marshalInput(self, anyType, true)
```
Comment (pgavlin) [inline sdk/go/pulumi/context.go:367]: Feels like we ought to have a better type than `anyType` for `resolvedSelf`. Is there a reason that we can't use the type of the resource itself?

Comment (justinvp) [reply sdk/go/pulumi/context.go]: Ah, fair point. It doesn't really make a difference here and I was just following [some](https://github.com/pulumi/pulumi/blob/ece9f2fb30598ed4796214f2c91290f31a63a742/sdk/go/pulumi/context.go#L246) [other](https://github.com/pulumi/pulumi/blob/ece9f2fb30598ed4796214f2c91290f31a63a742/sdk/go/pulumi/context.go#L1400) [cases](https://github.com/pulumi/pulumi/blob/ece9f2fb30598ed4796214f2c91290f31a63a742/sdk/go/pulumi/rpc.go#L261) where we use `anyType` with `marshalInput` when the type doesn't matter, but I don't see any reason we can't use the type of the resource itself here. Fixed.

**Review by pgavlin — APPROVED** [review]

File: tests/integration/construct_component_methods/go/main.go (hunk 1 above)
Comment (t0yv0) [reply tests/integration/construct_component_methods/go/main.go:77]: Input is such a scary interface. I'm developing an irrational fear that I'm not sure what happens when we declare something an input. I need to work on making this specific :)

**Review by t0yv0 — APPROVED** [review]
LGTM with a bit of unfortunate FUD about inputs.
