### PR TITLE
Fixes 5642 for Go: allow DependsOn accepting inputs and outputs

### LINKED ISSUE #5642: depends_on only works with a Resource/CustomResource and not Output[CustomResource]
## Expected Behavior
Trying to use the get_resource method of a Helm3 Chart to extract a created resource for a depends_on. 

## Current Behavior
When I use that extracted Output[CustomResource] it receive the error `Exception: 'depends_on' was passed a value that was not a Resource.` Most likely the check on depends_on needs to be fixed/extended to work with Output[Resource/CustoResource] types. 

## Steps to Reproduce
```
cert_manager_deployment = cert_manager_chart.get_resource(group_version_kind="apps/v1/Deployment",
                                                          name="cert-manager",
                                                          namespace="cert-manager")
```
Use that as a depends_on resource.

https://github.com/pulumi/pulumi/blame/5cef84f0366f264baf51c322d1d22b6124fdf236/sdk/python/lib/pulumi/resource.py#L450-L454

### PR DESCRIPTION
**Pull request by t0yv0**
# Description

Fixes #5642 (for the Go language)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: sdk/go/pulumi/resource.go [hunk 1]
```diff
@@ -314,7 +316,69 @@ func DeleteBeforeReplace(o bool) ResourceOption {
...
+		ro.DependsOn = append(ro.DependsOn, func(ctx context.Context) ([]URN, error) {
+			return resolveDependsOnURNs(ctx, o)
+		})
+	})
+}
+
+// A fully dynamic version of `DependsOn` that accepts `AnyOutput`
+// carrying `[]Resource`, `[]ResourceOutput`, or `[]ResourceInput`
+// values, which are then considered as explicit dependencies.
+func DependsOnOutput(any AnyOutput) ResourceOption {
```
Comment (t0yv0) [inline sdk/go/pulumi/resource.go:349]: Including to be compatible in power with Node/Py SDK where a list of prompty-indeterminate length can be passed in. If we don't care about that, can remove. It's a bit of an unfortunate interface.

File: sdk/go/pulumi/resource.go [hunk 2]
```diff
@@ -314,7 +316,69 @@ func DeleteBeforeReplace(o bool) ResourceOption {
 // DependsOn is an optional array of explicit dependencies on other resources.
 func DependsOn(o []Resource) ResourceOption {
 	return resourceOption(func(ro *resourceOptions) {
-		ro.DependsOn = append(ro.DependsOn, o...)
+		ro.DependsOn = append(ro.DependsOn, func(ctx context.Context) ([]URN, error) {
+			var urns []URN
+			for _, res := range o {
+				directUrn, isKnown, _, err := res.URN().awaitURN(ctx)
```
Comment (t0yv0) [inline sdk/go/pulumi/resource.go:322]: Any dependencies present in the `Output` layer of `res.URN() : URNOutput` are ignored.

File: sdk/go/pulumi/resource.go [hunk 3]
```diff
@@ -433,3 +497,92 @@ func Version(o string) ResourceOrInvokeOption {
...
+	resourceInput, isResourceInput := v.(ResourceInput)
+	if isResourceInput {
+		return resourceInput, nil
+	}
+	return nil, fmt.Errorf("Expected a Resource, ResourceOutput or a ResourceInput, but got a value of type %v",
+		reflect.TypeOf(v))
+}
+
+// Converts boxed `[]Resource`, `[]ResourceOutput`, `[]ResourceInput` slices to `[]ResourceInput`.
+func autocastSliceToResourceInput(v interface{}) ([]ResourceInput, error) {
```
Comment (t0yv0) [inline sdk/go/pulumi/resource.go:516]: In Go, slices seem to be invariant, one can cast `CustomResource -> interface{} -> Resource` but one cannot cast `[]CustomResource -> interface{} -> []Resource`... Rolling a little helper here. If there is other machinery in the codebase that can do this for our users please LMK.

File: sdk/go/pulumi/resource_test.go [hunk 4]
```diff
@@ -317,3 +348,231 @@ func TestResourceOptionMergingReplaceOnChanges(t *testing.T) {
...
+		for _, dep := range in.GetDependencies() {
+			deps = append(deps, URN(dep))
+		}
+		dependsOn.Store(URN(resp.Urn), deps)
+	}
+	ctx.monitor = m
+	return &dependenciesTracker{dependsOn}
+}
+
+type interceptingResourceMonitor struct {
```
Comment (t0yv0) [inline sdk/go/pulumi/resource_test.go:522]: Brute force attack here on the problem of intercepting engine calls to reconstruct dependency map "as reported to the enigne". Please LMK if there are other more elegant ways. Perhaps build this into mockEngine instead of mockMonitor?

File: sdk/go/pulumi/types.go [hunk 5]
```diff
@@ -1017,6 +1017,31 @@ func (ResourceOutput) ElementType() reflect.Type {
...
+	return o
+}
+
+func (o ResourceOutput) ToResourceOutputWithContext(ctx context.Context) ResourceOutput {
+	return o
+}
+
+// An Input type carrying Resource values.
+//
+// Unfortunately `Resource` values do not implement `ResourceInput` in
```
Comment (t0yv0) [inline sdk/go/pulumi/types.go:1030]: I'm running into a lot of difficulty trying to make `Resource` values compatible with `ResourceInput`. I'm starting to think the problem is with "deep reflect" combinators that try to traverse values as trees, find all Inputs and await them.. 

I also worry about these combinators attempting to await extraneous/outputs inputs on Resource properties and try to count them toward dependencies. If we have `ResourceInput` carrying a `r: Resource` , when we count the dependency closure, we want dependencies of the `Input[]` and the `r.urn`, and we probably don't want the deps of `r.Output1` etc.

File: sdk/go/pulumi/resource.go (hunk 2 above)
Comment (pgavlin) [reply sdk/go/pulumi/resource.go:322]: any particular reason for this? does this match the behavior of the other SDKs?

File: sdk/go/pulumi/resource_test.go (hunk 4 above)
Comment (pgavlin) [reply sdk/go/pulumi/resource_test.go:522]: Ah, is this necessary b/c we don't include dependency info in `MockResourceArgs`?

File: sdk/go/pulumi/types.go (hunk 5 above)
Comment (pgavlin) [reply sdk/go/pulumi/types.go:1030]: > I'm running into a lot of difficulty trying to make Resource values compatible with ResourceInput. I'm starting to think the problem is with "deep reflect" combinators that try to traverse values as trees, find all Inputs and await them..

Can you elaborate on the issues you're running into?

> we probably don't want the deps of r.Output1 etc.

FWIW, in practice the deps of `r.Output1` for a custom resource are `[]Resource{r}`. But I think that you're right in general.

File: sdk/go/pulumi/resource.go (hunk 2 above)
Comment (t0yv0) [reply sdk/go/pulumi/resource.go:322]: I can test for it. Node can be our reference. I'd need a way to inject deps into the URN output but that perhaps is possible.

File: sdk/go/pulumi/resource_test.go (hunk 4 above)
Comment (t0yv0) [reply sdk/go/pulumi/resource_test.go:522]: Right, the other way would be to package this into MockResourceArgs, simpler implementation. That'd be a public interface change and up for consideration if we want that public change or not, I did not want to tag that along here. OK to tackle separately or you'd prefer to go ahead with extending MockResourceArgs and I can make this PR depend on it?

File: sdk/go/pulumi/types.go (hunk 5 above)
Comment (t0yv0) [reply sdk/go/pulumi/types.go:1030]: Very specifically this: https://github.com/pulumi/pulumi/pull/7394

Substitute `Example` with `Resource` to make this practical. When interfaces travel through input/output machinery something in the generic/reflecty code gets off the rails, and I tried but failed to fix that.

File: sdk/go/pulumi/resource.go (hunk 2 above)
Comment (t0yv0) [reply sdk/go/pulumi/resource.go:322]: Matches the behavior of Node. The dependencies specifically on URNOutput do not participate. C# SDK diverges significantly https://github.com/pulumi/pulumi/pull/7611 and I'm taking Node as authority on what should happen.

**Comment by t0yv0** [comment]
> Should we add a ResourceArray/ResourceArrayInput/ResourceArrayOutput and then just have a single function: func DependsOnInputs(o ResourceArrayInput) ResourceOption?

That sounds interesting, it can lead to a better interface, I've just been a little unsure how to implement input types completely correctly in the Go SDK (I see you've commented 🤔  on some linked PRs). Let me dig a little deeper on this, I feel like I need to put an effort here to understand this matter better.

File: sdk/go/pulumi/provider.go [hunk 6]
```diff
@@ -103,7 +103,11 @@ func construct(ctx context.Context, req *pulumirpc.ConstructRequest, engineConn
 	}
 	opts := resourceOption(func(ro *resourceOptions) {
 		ro.Aliases = aliases
-		ro.DependsOn = dependencies
+		ro.DependsOn = []func(ctx context.Context) ([]URN, error){
```
[the remark this answers is not in the document]
Comment (t0yv0) [reply sdk/go/pulumi/provider.go:103]: Oh no, this is gofmt. In my Emacs mode it runs gofmt on every file save. If I add a space it removes it.

File: sdk/go/pulumi/types.go [hunk 7]
```diff
@@ -1017,6 +1017,116 @@ func (ResourceOutput) ElementType() reflect.Type {
...
+		}
+		return ret
+	}).(ResourceOutput)
+}
+
+func ToResourceArray(in []Resource) ResourceArray {
+	return NewResourceArray(in...)
+}
+
+func NewResourceArray(in ...Resource) ResourceArray {
```
Comment (t0yv0) [inline sdk/go/pulumi/types.go:1109]: The "standard" code generator  builds the ToResourceArray forms, but I find the `...` forms much more handy to use. I included both so as to not make inconsistent To* forms.

**Comment by t0yv0** [comment]
Added `func DependsOnInputs(o ResourceArrayInput) ResourceOption` - this works pretty well. We lose parity vs Python in a niche matter of unknowns, that is, since casting to ResourceArrayInput uses `All` if any of the resources are unknown, then no dependencies at all will be recorded. Whereas in Python, if any of them are known they are still recorded. I've no evidence it's a practical issue, just a theoretical curiosity, so suggest we ignore. I removed the test that was looking into that.

In current version `NewResourceInput` is still needed. To make `Resource` values automatically promote to `ResourceInput` we need two things:

- Fix core lib handling of outputs carrying interfaces https://github.com/pulumi/pulumi/pull/7394

- Embed `ResourceInput` interface into `Resource` interface; it seems that it would that break providers and might necessitate a codegen change, as I don't believe we can patch ResourceState and make all resources implement ResourceInput correctly; this will also be a breaking change to user code for custom resources as they will not be implementing ResourceInput automatically

Given these two considerations, I suggest we postpone that and accept the current version necessitating NewResourceInput for now?

**Comment by t0yv0** [comment]
@justinvp PTAL

File: sdk/go/pulumi/types.go (hunk 5 above)
Comment (justinvp) [reply sdk/go/pulumi/types.go:1030]: With the change in #7394, are you suggesting we'd change `Resource` to implement `ResourceInput`?  Or would we make `ResourceState` implement `ResourceInput`?

Is that change necessary for this PR or can it be deferred?

**Review by justinvp — APPROVED** [review]
One question about #7394, otherwise LGTM, aside from any other feedback from @pgavlin or @EvanBoyle.

File: sdk/go/pulumi/types.go (hunk 5 above)
Comment (t0yv0) [reply sdk/go/pulumi/types.go:1030]: I'm struggling to make the suggestion more specific. For the users' sake, I felt it might be "nice" to be able to pass resources where resource inputs are expected, e.g.:

```
   func f(x ResourceInput)
   res := NewFooResource("my-res1")
   f(res)

   # vs
   
   f(NewResourceInput(res))
```

Initially I thought this would need:

```
   type Resource interface {
        ...
	ResourceInput
   }
```

But your comment makes me realize specific resource types can implement ResourceInput without making Resource implement ResourceInput. So far so good.

It was tempting to make some changes to `ResourceState` so that *all* structs embedding ResourceState automatically start implementing ResourceInput. This however is not possible AFAIK, because:

```
type Input interface {
	ElementType() reflect.Type
}
type ResourceInput interface {
        Input
}
```

So `ResourceState` cannot implement `ElementType()` since it does not know the struct it is being embedded in, and AFAIK it cannot capture `self` referring to that outer struct. This is somewhat unlike classical inheritance.

Comment (t0yv0) [reply sdk/go/pulumi/types.go:1030]: Now that I think of it, we could follow up with a codegen change though to make provider resources implement ResourceInput.

Comment (justinvp) [reply sdk/go/pulumi/types.go:1030]: These are often going to show up as outputs from multi-lang components like [this](https://github.com/pulumi/pulumi-eks/blob/86861e6cb6091e97d08828a444bb70087a8701f3/sdk/go/eks/managedNodeGroup.go#L24):

```go
type ManagedNodeGroup struct {
	pulumi.ResourceState

	// The AWS managed node group.
	NodeGroup eks.NodeGroupOutput `pulumi:"nodeGroup"`
}
```

If I have an instance of the `ManagedNodeGroup` component, and I want to pass its `NodeGroup` output (typed as `github.com/pulumi/pulumi-aws/sdk/v4/go/aws/eks.NodeGroupOutput`) to `DependsOnInputs`, what would that look like with just the changes in this PR?

Would I have to use an `ApplyT` to do the conversion like the following?

```go
ng, err := eks.NewManagedNodeGroup(ctx, "ng", &eks.ManagedNodeGroupArgs{...})
pulumi.DependsOnInputs(pulumi.ResourceArray{
	ng.NodeGroup.ApplyT(func(v pulumi.Resource) pulumi.Resource {
		return v
	}).(pulumi.ResourceOutput),
})
```

Comment (t0yv0) [reply sdk/go/pulumi/types.go:1030]: I filed this as https://github.com/pulumi/pulumi/issues/7750

File: sdk/go/pulumi/urnset.go [hunk 8]
```diff
@@ -0,0 +1,50 @@
...
+
+func (s urnSet) values() []URN {
+	values := make([]URN, 0, len(s))
+	for v := range s {
+		values = append(values, v)
+	}
+	return values
+}
+
+func (s urnSet) sortedValues() []URN {
```
Comment (t0yv0) [inline sdk/go/pulumi/urnset.go:46]: @pgavlin as a compromise I just added this to use in my tests, not making values() sort.
