### PR TITLE
test/codegen: Don't run in parallel

### LINKED ISSUE #11925: gen_program_tests getting killed almost consistently
Something is broken with one of the integration tests on master, but only in CI.
Several otherwise green PRs are failing often on one of the pkg test shards.
It appears that the test gets killed after some time of posting heartbeats.

```
💓
💓
make: *** [Makefile:139: gotestsum/pkg] Terminated
Error: Process completed with exit code 143.
```

The failure is flaky but it's been leaning more and more red recently.
The cause is unclear because nothing is posted about it,
but one of the ongoing guesses is that
we're hitting a memory usage limit in one of those tests,
which causes a termination.

Examples:
- https://github.com/pulumi/pulumi/actions/runs/3962273901/jobs/6789198464
- https://github.com/pulumi/pulumi/actions/runs/3962096772/jobs/6788386893

The relevant command (with the same PKGs and tags) succeeds on local executions.

This is not just a problem in PRs. bors also fails with these occasionally:

- https://app.bors.tech/batches/286903
- https://app.bors.tech/batches/286697

### PR DESCRIPTION
**Pull request by abhinav**
Landable version of #11928

We seem to be hitting OOMs in CI quite often
whlie running code generation integration tests.

This drops parallelism from these tests because
experimentation revealed that running these tests serially
mitigates this issue somewhat.

Resolves #11925

### CODE REVIEW

**Comment by abhinav** [comment]
Note that this doesn't add much to the test wait time.

[Before](https://github.com/pulumi/pulumi/actions/runs/3952041097):
image

[Now](https://github.com/pulumi/pulumi/actions/runs/3963755917):
image

Although some of the individual test partitions now take longer, the maximum time taken by a partition went up by only a minute, which seems like a reasonable trade-off for less flakiness. With this, data race detection (#11913) passes consistently.

**Review by Zaid-Ajaj — APPROVED** [review]

File: pkg/codegen/testing/test/program_driver.go [hunk 1]
```diff
@@ -381,7 +381,10 @@ func TestProgramCodegen(
 	for _, tt := range testcase.TestCases {
 		tt := tt // avoid capturing loop variable
 		t.Run(tt.Directory, func(t *testing.T) {
-			t.Parallel()
```
Comment (AaronFriel) [inline pkg/codegen/testing/test/program_driver.go:384]: Will this cause a lint failure in `paralleltest`?

Comment (AaronFriel) [reply pkg/codegen/testing/test/program_driver.go:384]: @abhinav huh, it looks like it didn't. How did this escape `paralleltest`?

Comment (abhinav) [reply pkg/codegen/testing/test/program_driver.go:384]: I'm guessing that paralleltest doesn't care about this because this isn't a _test.go file or a test function (`func TestFoo(t *testing.T)`). I left that comment in there in case paralleltest got smarter in the future.

**Comment by abhinav** [comment]
One of the integration tests timed out in "set up node" step:
image

**Comment by abhinav** [comment]
bors retry

**Comment by abhinav** [comment]
bors retry
