### PR TITLE
Get latest version if one not specified in pulumi manifest

### LINKED ISSUE #16920: Install command fails in clean environment
### What happened?

Trying to run `pulumi install` on the `random-yaml` example, fails with:
```
resource plugin random installing
warning: Error downloading plugin: unknown version for plugin random
Will retry in 80ms [1/5]
warning: Error downloading plugin: unknown version for plugin random
Will retry in 160ms [2/5]
warning: Error downloading plugin: unknown version for plugin random
Will retry in 320ms [3/5]
warning: Error downloading plugin: unknown version for plugin random
Will retry in 640ms [4/5]
warning: Error downloading plugin: unknown version for plugin random
Will retry in 1.28s [5/5]
error: resource plugin random downloading from : failed to download plugin: random: failed all 5 attempts
```

### Example

1. Check out https://github.com/pulumi/examples/tree/master/random-yaml
2. Set `PULUMI_HOME` to a temporary directory, to ensure that there's no pre-installed plugins.
3. Run `pulumi install`.

For example:
```
cd random-yaml
PULUMI_HOME=./.pulumi pulumi install
```

### Output of `pulumi about`

```
CLI          
Version      3.121.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  random  unknown
language  yaml    unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in yaml

Backend        
Name           pulumi.com
URL            https://app.pulumi.com
User           Unknown
Organizations  
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/d4/bznc6qv135qc7ngyh8ld56lm0000gn/T/ by default
warning: Failed to get information about the current stack: No current stack

```

### Additional context

Note that `pulumi up` works as expected, suggesting that the automatic plugin installation logic is smarter about picking the latest version as opposed to erroring out.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by brandonpollack23**
Previously, unlike pulumi up, pulumi install did not get latest version of one is not specified for dependencies/plugins.

YAML allows there to not be a version specified so this caused an issue in YAML.

Fixes #16920

### CODE REVIEW

**Review by justinvp — COMMENTED** [review]
Looks great! 🎉 How about a test?

To try out the changes, I whipped up the following. Want to add it (or something like it) to https://github.com/pulumi/pulumi/blob/master/tests/smoke_test.go? Or I can push a commit to your branch to add this test, if you prefer; either way works for me.

```go
//nolint:paralleltest // disabled parallel because we change the plugins cache
func TestInstall(t *testing.T) {
	for _, runtime := range Runtimes {
		t.Run(runtime, func(t *testing.T) {
			//nolint:paralleltest

			e := ptesting.NewEnvironment(t)
			defer deleteIfNotFailed(e)

			// Make sure the random provider is not installed locally
			// so that we can test the `install` command works.
			out, _ := e.RunCommand("pulumi", "plugin", "ls")
			if strings.Contains(out, "random  resource") {
				e.RunCommand("pulumi", "plugin", "rm", "resource", "random", "--all", "--yes")
			}

			// `new` wants to work in an empty directory but our use of local url means we have a
			// ".pulumi" directory at root.
			projectDir := filepath.Join(e.RootPath, "project")
			err := os.Mkdir(projectDir, 0o700)
			require.NoError(t, err)

			e.CWD = projectDir

			e.RunCommand("pulumi", "login", "--cloud-url", e.LocalURL())
			// Pass `--generate-only` so dependencies are not installed as part of the `new` command.
			e.RunCommand("pulumi", "new", "random-"+Languages[runtime], "--yes", "--generate-only")

			// Ensure `install` works and subsequent `up` and `destroy` operations work.
			e.RunCommand("pulumi", "install")
			e.RunCommand("pulumi", "stack", "init", "test")
			e.RunCommand("pulumi", "up", "--yes")
			e.RunCommand("pulumi", "destroy", "--yes")
		})
	}
}
```

**Comment by brandonpollack23** [comment]
Ah you already wrote it but now I know, Im running it locally just to
familiarize myself with it.

How might I run just one test (go test fails/complains.  I see the script
for running tests is used in the makefile but do you have an easy way to
run just one)

**Comment by justinvp** [comment]
> How might I run just one test

```
cd tests
go test -run "^TestInstall/yaml$" github.com/pulumi/pulumi/tests -v -count=1
```

**Comment by brandonpollack23** [comment]
I've run it and pushed it, im addressing your other comments now

**Review by brandonpollack23 — COMMENTED** [review]
Should be all good to go now (we only need to merge this one if we don't want to just merge #16982)

File: pkg/cmd/pulumi/install.go [hunk 1]
```diff
@@ -139,7 +143,20 @@ func newInstallCmd() *cobra.Command {
 						}
 					}
 
-					pctx.Diag.Infoerrf(diag.Message("", "%s installing"), label)
+					// If we don't have a version yet but we are installing try and call GetLatestVersion
+					// to fill it in.
+					if install.Version == nil {
+						logging.V(preparePluginVerboseLog).Infof(
```
Comment (tgummerer) [inline pkg/cmd/pulumi/install.go:149]: I think typically we just hardcode the log level.  I think I kind of prefer that over local constants as it makes it slightly easier to see at which level we're logging at the log line instead of looking at another variable (it might be nice to have this as global constants with a meaning somewhere, I think these log levels are somewhat arbitrary right now)

**Review by tgummerer — COMMENTED** [review]
Did you push the test to the wrong branch accidentally?  I don't see it here yet.

**Comment by brandonpollack23** [comment]
> Did you push the test to the wrong branch accidentally? I don't see it here yet.

Apologies, new to github/git prs i think its all good now

File: tests/smoke_test.go [hunk 2]
```diff
@@ -452,3 +452,40 @@ func TestPluginRun(t *testing.T) {
 	_, stderr = e.RunCommandExpectError("pulumi", "plugin", "run", "--kind=resource", "random", "--", "--help")
 	assert.Contains(t, stderr, "flag: help requested")
 }
+
+//nolint:paralleltest // disabled parallel because we change the plugins cache
```
Comment (tgummerer) [inline tests/smoke_test.go:456]: I don't think this is necessary, and we should be able to run this test in paralllel with others. We are running this using `ptesting.NewEnvironment`, which uses a temp directory, and sets `PULUMI_HOME` to that temp directory. Plugins should be installed into `PULUMI_HOME`, so it shouldn't interfere with the global state.  

(I do see we do something similar in `smoke_test.go`, but the change to set a new `PULUMI_HOME` for every test is relatively recent, so that was still necessary at the time. See https://github.com/pulumi/pulumi/pull/15559)

File: tests/smoke_test.go [hunk 3]
```diff
@@ -452,3 +452,40 @@ func TestPluginRun(t *testing.T) {
...
+			require.NoError(t, err)
+
+			e.CWD = projectDir
+
+			e.RunCommand("pulumi", "login", "--cloud-url", e.LocalURL())
+			// Pass `--generate-only` so dependencies are not installed as part of the `new` command.
+			e.RunCommand("pulumi", "new", "random-"+Languages[runtime], "--yes", "--generate-only")
+
+			// Ensure `install` works and subsequent `up` and `destroy` operations work.
+			e.RunCommand("pulumi", "install")
```
Comment (tgummerer) [inline tests/smoke_test.go:485]: We may want to assert on the output here to show the plugin was installed?

**Review by tgummerer — COMMENTED** [review]
> Apologies, new to github/git prs i think its all good now

Yup, thank you!

I got a couple more minor comments inline, then I think this is good to go.

File: tests/smoke_test.go [hunk 4]
```diff
@@ -452,3 +453,45 @@ func TestPluginRun(t *testing.T) {
...
+
+			e := ptesting.NewEnvironment(t)
+			defer deleteIfNotFailed(e)
+
+			// Make sure the random provider is not installed locally
+			// so that we can test the `install` command works.
+			out, _ := e.RunCommand("pulumi", "plugin", "ls")
+			if strings.Contains(out, "random  resource") {
+				e.RunCommand("pulumi", "plugin", "rm", "resource", "random", "--all", "--yes")
+			}
```
Comment (tgummerer) [inline tests/smoke_test.go:475]: Sorry for not noticing this before, but I think this could also go away now.  Since we have a fresh `PULUMI_HOME` it's never going to have the plugin.

**Review by tgummerer — APPROVED** [review]

File: tests/smoke_test.go (hunk 4 above)
Comment (brandonpollack23) [reply tests/smoke_test.go:475]: It can't hurt though right? might be best in case something changes for some unknown reason?

Comment (tgummerer) [reply tests/smoke_test.go:475]: I mean it adds some time to the test, and will probably be parrotted in other tests as well.  But I don't feel very strongly about it.

File: tests/smoke_test.go [hunk 5]
```diff
@@ -452,3 +453,45 @@ func TestPluginRun(t *testing.T) {
...
+
+			e.CWD = projectDir
+
+			e.RunCommand("pulumi", "login", "--cloud-url", e.LocalURL())
+			// Pass `--generate-only` so dependencies are not installed as part of the `new` command.
+			e.RunCommand("pulumi", "new", "random-"+Languages[runtime], "--yes", "--generate-only")
+
+			// Ensure `install` works and subsequent `up` and `destroy` operations work.
+			_, stderr := e.RunCommand("pulumi", "install")
+			assert.Regexp(t, regexp.MustCompile(`\[resource plugin random-.+\] installing`), stderr)
```
Comment (justinvp) [inline tests/smoke_test.go:491]: This test is failing:

https://github.com/pulumi/pulumi/actions/runs/10512638165/job/29126736206#step:36:575

```
=== Failed
=== FAIL: . TestInstall/python (59.20s)
    environment.go:103: Created new test environment:  /tmp/test-env3425907744
    environment.go:223: Running command pulumi plugin ls
    environment.go:223: Running command pulumi login --cloud-url file:///tmp/test-env3425907744
    environment.go:223: Running command pulumi new random-python --yes --generate-only
    environment.go:223: Running command pulumi install
    smoke_test.go:491: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/tests/smoke_test.go:491
        	Error:      	Expect "resource plugin random-4.16.3 version 4.16.3 installing
        	            	" to match "\[resource plugin random-.+\] installing"
        	Test:       	TestInstall/python
    environment.go:223: Running command pulumi stack init test
    environment.go:223: Running command pulumi up --yes
    environment.go:223: Running command pulumi destroy --yes

=== FAIL: . TestInstall/go (55.05s)
    environment.go:103: Created new test environment:  /tmp/test-env948558346
    environment.go:223: Running command pulumi plugin ls
    environment.go:223: Running command pulumi login --cloud-url file:///tmp/test-env948558346
    environment.go:223: Running command pulumi new random-go --yes --generate-only
    environment.go:223: Running command pulumi install
    smoke_test.go:491: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/tests/smoke_test.go:491
        	Error:      	Expect "resource plugin random-4.13.0 version 4.13.0 installing
        	            	" to match "\[resource plugin random-.+\] installing"
        	Test:       	TestInstall/go
    environment.go:223: Running command pulumi stack init test
    environment.go:223: Running command pulumi up --yes
    environment.go:223: Running command pulumi destroy --yes

=== FAIL: . TestInstall/dotnet (66.55s)
    environment.go:103: Created new test environment:  /tmp/test-env315653803
    environment.go:223: Running command pulumi plugin ls
    environment.go:223: Running command pulumi login --cloud-url file:///tmp/test-env315653803
    environment.go:223: Running command pulumi new random-csharp --yes --generate-only
    environment.go:223: Running command pulumi install
    smoke_test.go:491: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/tests/smoke_test.go:491
        	Error:      	Expect "resource plugin random-4.16.3 version 4.16.3 installing
        	            	" to match "\[resource plugin random-.+\] installing"
        	Test:       	TestInstall/dotnet
    environment.go:223: Running command pulumi stack init test
    environment.go:223: Running command pulumi up --yes
    environment.go:223: Running command pulumi destroy --yes

=== FAIL: . TestInstall/nodejs (62.78s)
    environment.go:103: Created new test environment:  /tmp/test-env1095760047
    environment.go:223: Running command pulumi plugin ls
    environment.go:223: Running command pulumi login --cloud-url file:///tmp/test-env1095760047
    environment.go:223: Running command pulumi new random-typescript --yes --generate-only
    environment.go:223: Running command pulumi install
    smoke_test.go:491: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/tests/smoke_test.go:491
        	Error:      	Expect "resource plugin random-4.16.3 version 4.16.3 installing
        	            	" to match "\[resource plugin random-.+\] installing"
        	Test:       	TestInstall/nodejs
    environment.go:223: Running command pulumi stack init test
    environment.go:223: Running command pulumi up --yes
    environment.go:223: Running command pulumi destroy --yes

=== FAIL: . TestInstall/yaml (54.44s)
    environment.go:103: Created new test environment:  /tmp/test-env3963462627
    environment.go:223: Running command pulumi plugin ls
    environment.go:223: Running command pulumi login --cloud-url file:///tmp/test-env3963462627
    environment.go:223: Running command pulumi new random-yaml --yes --generate-only
    environment.go:223: Running command pulumi install
    smoke_test.go:491: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/tests/smoke_test.go:491
        	Error:      	Expect "resource plugin random version 4.16.3 installing
        	            	" to match "\[resource plugin random-.+\] installing"
        	Test:       	TestInstall/yaml
    environment.go:223: Running command pulumi stack init test
    environment.go:223: Running command pulumi up --yes
    environment.go:223: Running command pulumi destroy --yes

=== FAIL: . TestInstall/java (78.93s)
    environment.go:103: Created new test environment:  /tmp/test-env1232564630
    environment.go:223: Running command pulumi plugin ls
    environment.go:223: Running command pulumi login --cloud-url file:///tmp/test-env1232564630
    environment.go:223: Running command pulumi new random-java --yes --generate-only
    environment.go:223: Running command pulumi install
    smoke_test.go:491: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/tests/smoke_test.go:491
        	Error:      	Expect "resource plugin random-4.17.0-alpha.1723010172 version 4.17.0-alpha.1723010172 installing
        	            	" to match "\[resource plugin random-.+\] installing"
        	Test:       	TestInstall/java
    environment.go:223: Running command pulumi stack init test
    environment.go:223: Running command pulumi up --yes
    environment.go:223: Running command pulumi destroy --yes

=== FAIL: . TestInstall (0.00s)
```

**Comment by brandonpollack23** [comment]
Apologies for the churn, I'll chalk it up to getting used to PR workflow, the tests all pass locally for me now so hopefully I got the upload process right...
