### PR TITLE
Resources now inherit the DeletedWith Resource Option across SDKs.

### LINKED ISSUE #12158: `deletedWith` resource option is not inherited by child resources
### What happened?

The `deletedWith` resource option is not inherited by child resources when the option is set on the parent. This results in the physical child resources being deleted from the cloud provider, while the parent resource remains.

### Expected Behavior

child resource should only be deleted from Pulumi state; not the cloud provider 

### Steps to reproduce

Using the following program execute:
- `pulumi up -f`
- `pulumi destroy -f`

After destroy, parent-bucket and all child-buckets should physically remain in AWS, however, only the parent-bucket remains.

```typescript
import * as aws from "@pulumi/aws";

// all resources should below should only be deleted from stack state
const bucket = new aws.s3.Bucket("base-bucket");

// set deletedWith to stop provider from calling Delete
const parentBucket = new aws.s3.Bucket("parent-bucket", {}, { deletedWith: bucket });

// deletedWith should be inherited from parent and stop physical resource from being deleted
new aws.s3.Bucket("child-bucket-1", {}, { parent: parentBucket });
new aws.s3.Bucket("child-bucket-2", {}, { parent: parentBucket });
new aws.s3.Bucket("child-bucket-3", {}, { parent: parentBucket });
```

### Output of `pulumi about`

CLI          
Version      3.53.0
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.29.1
awsx    1.0.2
docker  3.6.1
nodejs  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/home/pedwards/.nvm/versions/node/v14.17.3/bin/node' version='v14.17.3'

Current Stack: team-ce/deleted-with-parent/phil

Found no resources associated with phil

Found no pending operations associated with phil

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/phillipedwards
User           phillipedwards

Dependencies:
NAME            VERSION
@pulumi/awsx    1.0.2
@pulumi/pulumi  3.54.0
@types/node     16.18.12
@pulumi/aws     5.29.1

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description
This PR uses this information to set the `DeletedWith` when it is left unset by the user's program and there is a Parent resource to inherit the value from.

From https://github.com/pulumi/pulumi/pull/12446 which was reverted due to https://github.com/pulumi/pulumi/issues/12562 having difficulty with MLCs and Read resources.

TODO
- [x] Add test case to catch the condition causing https://github.com/pulumi/pulumi/issues/12562
- [x] Fix data race

Fixes #12158 

Needs follow up on: https://github.com/pulumi/pulumi-hugo/issues/2566

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/resource/deploy/step_generator_test.go [hunk 1]
```diff
@@ -360,3 +360,97 @@ func TestEngineDiff(t *testing.T) {
...
+	sg := stepGenerator{
+		urns: map[resource.URN]bool{
+			parentURN: true,
+		},
+		resourceGoals: map[resource.URN]*resource.Goal{},
+	}
+	err := sg.configureGoal(goal)
+
+	assert.Nil(t, err)
+}
```
Comment (dixler) [inline pkg/resource/deploy/step_generator_test.go:456]: Catches the regression.

File: pkg/resource/deploy/step_generator_test.go [hunk 2]
```diff
@@ -360,3 +360,107 @@ func TestEngineDiff(t *testing.T) {
 		})
 	}
 }
+
+func TestResourceInheritsOptionsFromParent(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (dixler) [reply pkg/resource/deploy/step_generator_test.go:364]: ReadResource requests don't have ResourceOptions attached other than Parent
https://github.com/pulumi/pulumi/blob/ec1b0466dfe03988c6e402b29e2064c4c85645b4/sdk/proto/go/resource.pb.go#L135-L153

Nothing in deploytest indicates to me that we call RegisterResource on ReadResources.
This leads me to believe that a ReadResource shouldn't have any ResourceOptions for the Child resource to Inherit.

File: pkg/resource/deploy/step_generator_test.go (hunk 1 above)
Comment (dixler) [reply pkg/resource/deploy/step_generator_test.go]: Changed approach to track goals in the resource monitor.

Resources without goals should show up in the resource monitor (even MLCs). Read resources don't actually have resource options sent over the wire to propagate and expectation for imported resources to be inherited by child resources are an inaccuracy.

File: pkg/resource/deploy/source_eval.go [hunk 3]
```diff
@@ -1368,6 +1394,10 @@ func (rm *resmon) RegisterResource(ctx context.Context,
 	if err != nil {
 		return nil, err
 	}
+
+	// TODO determine if should be a reference.
+	rm.resGoals[urn] = *goal
```
Comment (dixler) [inline pkg/resource/deploy/source_eval.go:1399]: could also be moved earlier potentially or run as a defer.

File: pkg/resource/deploy/source_eval.go [hunk 4]
```diff
@@ -1175,6 +1187,48 @@ func (rm *resmon) RegisterResource(ctx context.Context,
...
+	goal := resource.NewGoal(t, name, custom, props, parent, protect, dependencies,
+		providerRef.String(), nil, propertyDependencies, deleteBeforeReplace, ignoreChanges,
+		additionalSecretKeys, aliases, id, &timeouts, replaceOnChanges, retainOnDelete, deletedWith)
+
+	if goal.Parent != "" {
+		parentGoal, ok := rm.resGoals[goal.Parent]
+		if ok {
+			goal = inheritFromParent(*goal, parentGoal)
+		}
+	}
```
Comment (dixler) [inline pkg/resource/deploy/source_eval.go:1229]: Logic moved higher up to create a Goal even when a resource is a remote resource.

Should I leave the code in there and only construct if it's not a remote resource? On further inspection, provider.Construct() assumes/expects the provider to call RegisterResource and may potentially be better, but I'd like a second opinion from the MLC experts.

File: pkg/engine/lifecycletest/step_generator_test.go [hunk 5]
```diff
@@ -92,3 +93,163 @@ func TestDuplicateAlias(t *testing.T) {
...
+
+	project := p.GetProject()
+	snap, res := TestOp(Update).Run(project, p.GetTarget(t, nil), p.Options, false, p.BackendClient, nil)
+	for _, res := range snap.Resources[1:] {
+		assert.Equal(t, resource.URN("expect-this"), res.DeletedWith)
+	}
+	assert.Nil(t, res)
+}
+
+// TODO determine if this is redundant.
```
Comment (dixler) [inline pkg/engine/lifecycletest/step_generator_test.go:201]: This seems redundant at this point. This test checks that a RegisterResource call inside of a MLC provider is properly parented, but the distinction between the MLC provider and the program itself parenting an MLC resource seems irrelevant.

File: pkg/resource/deploy/source_eval.go (hunk 4 above)
Comment (justinvp) [reply pkg/resource/deploy/source_eval.go:1229]: Yeah, I think this should be moved back to where it was.

File: pkg/resource/deploy/source_eval.go (hunk 3 above)
Comment (justinvp) [reply pkg/resource/deploy/source_eval.go:1399]: I would just add it to the bottom of the else clause of the `if remote` check. Something like (with lock):

```go
if result != nil && result.State != nil && result.State.URN != "" {
	func() {
		rm.resGoalsLock.Lock()
		defer rm.resGoalsLock.Unlock()
		rm.resGoals[result.State.URN] = *goal
	}()
}
```

File: pkg/engine/lifecycletest/step_generator_test.go [hunk 6]
```diff
@@ -92,3 +93,107 @@ func TestDuplicateAlias(t *testing.T) {
 	_, res = TestOp(Update).Run(project, p.GetTarget(t, snap), p.Options, false, p.BackendClient, nil)
 	assert.NotNil(t, res)
 }
+
+// TestDeletedWithOptionInheritance checks that a resource that sets its parent to another resource inherits
```
Comment (justinvp) [inline pkg/engine/lifecycletest/step_generator_test.go:97]: Now that the implementation is in the resource monitor, should these tests be in `step_generator_test.go` or some other file in lifecycletest?

File: pkg/engine/lifecycletest/step_generator_test.go [hunk 7]
```diff
@@ -92,3 +93,107 @@ func TestDuplicateAlias(t *testing.T) {
...
+}
+
+// TestDeletedWithOptionInheritanceMLC checks that an MLC's DeletedWith option is propagated to resources that
+// set an MLC as its parent. MLC's are remote and at the time of writing their RegisterResource call asks the
+// resource monitor to ask the constructor to call the necessary RegisterResource calls on the program's behalf.
+func TestDeletedWithOptionInheritanceMLC(t *testing.T) {
+	t.Parallel()
+
+	program := deploytest.NewLanguageRuntime(func(_ plugin.RunInfo, monitor *deploytest.ResourceMonitor) error {
+		parentUrn, _, _, err := monitor.RegisterResource("pkgA:m:typA", "resA", true, deploytest.ResourceOptions{
```
Comment (justinvp) [inline pkg/engine/lifecycletest/step_generator_test.go:149]: I would change the `true` to `false`, because this resource isn't intended to be a custom resource, it's a (remote) component.

I'd also change the type to something other than `"pkgA:m:typA"` used by the child custom resource.

```suggestion
		parentUrn, _, _, err := monitor.RegisterResource("pkgA:m:typComponent", "resA", false, deploytest.ResourceOptions{
```

File: pkg/engine/lifecycletest/step_generator_test.go [hunk 8]
```diff
@@ -92,3 +93,107 @@ func TestDuplicateAlias(t *testing.T) {
...
+					return plugin.DiffResult{}, nil
+				},
+				ConstructF: func(monitor *deploytest.ResourceMonitor, typ, name string,
+					parent resource.URN, inputs resource.PropertyMap, options plugin.ConstructOptions,
+				) (plugin.ConstructResult, error) {
+					urn, _, _, err := monitor.RegisterResource(tokens.Type(typ), name, false, deploytest.ResourceOptions{
+						DeletedWith: options.DeletedWith,
+					})
+					assert.NoError(t, err)
+					assert.Equal(t, "resA", name)
```
Comment (justinvp) [inline pkg/engine/lifecycletest/step_generator_test.go:178]: Consider moving this to the beginning of the `ConstructF` function, and changing it to a `require` rather than `assert` so it immediately fails the test. Also, might as well assert that the `typ` is the expected type (if you change it based on my other comment above, `pkgA:m:typComponent`:

```go
require.Equal(t, "pkgA:m:typComponent", typ)
require.Equal(t, "resA", name)
```

File: pkg/engine/lifecycletest/step_generator_test.go [hunk 9]
```diff
@@ -92,3 +93,107 @@ func TestDuplicateAlias(t *testing.T) {
...
+				) (plugin.DiffResult, error) {
+					return plugin.DiffResult{}, nil
+				},
+				ConstructF: func(monitor *deploytest.ResourceMonitor, typ, name string,
+					parent resource.URN, inputs resource.PropertyMap, options plugin.ConstructOptions,
+				) (plugin.ConstructResult, error) {
+					urn, _, _, err := monitor.RegisterResource(tokens.Type(typ), name, false, deploytest.ResourceOptions{
+						DeletedWith: options.DeletedWith,
+					})
+					assert.NoError(t, err)
```
Comment (justinvp) [inline pkg/engine/lifecycletest/step_generator_test.go:177]:
```suggestion
					urn, _, _, err := monitor.RegisterResource(tokens.Type(typ), name, false, deploytest.ResourceOptions{
						DeletedWith: options.DeletedWith,
					})
					require.NoError(t, err)
					
					_, _, _, err = monitor.RegisterResource("pkgA:m:typA", "resC", true, deploytest.ResourceOptions{
						Parent: urn,
					})
					require.NoError(t, err)
```

File: pkg/resource/deploy/source_eval.go [hunk 10]
```diff
@@ -993,6 +996,16 @@ func (rm *resmon) ReadResource(ctx context.Context,
 	}, nil
 }
 
+// inheritFromParent returns a new goal that inherits from the given parent goal.
```
[the remark this answers is not in the document]
Comment (dixler) [reply pkg/resource/deploy/source_eval.go:999]: Technically, now it's only in source_eval

**Review by Frassle — APPROVED** [review]
Looks ok, I think we'll want to work out a way to move parent logic consistently to step_generator at some point but will take time to think that through

**Comment by dixler** [comment]
bors merge
