### PR TITLE
[sdk-gen/go] Fix generation of lifted single-value calls in parameterized SDKs

### LINKED ISSUE #20744: pulumi convert generates Go SDK for Any TF provider that doesn't compile
### What happened?

Running `pulumi convert` to language Go against a program that has a parameterized provider generates a Go SDK that doesn't compile

### Example

Take the following program that uses `tfe` Terraform provider in a file `main.pp`
```tf
package "tfe" {
  baseProviderName    = "terraform-provider"
  baseProviderVersion = "0.8.1"
  parameterization {
    version = "0.68.2"
    name    = "tfe"
    value   = "eyJyZW1vdGUiOnsidXJsIjoiaGFzaGljb3JwL3RmZSIsInZlcnNpb24iOiIwLjY4LjIifX0="
  }
}


resource "test-organization" "tfe:index/organization:Organization" {
  name  = "my-org-name"
  email = "admin@company.com"
}
```
Then run 
```
pulumi convert --from pcl --language go --out goexample
```
Now try to compile the program
```
cd goexample
go build
```
gives error
```
# github.com/pulumi/pulumi-terraform-provider/sdks/go/tfe/tfe
sdks/tfe/tfe/provider.go:74:10: cannot use providerTerraformConfigResultOutput{} (value of struct type providerTerraformConfigResultOutput) as pulumi.MapOutput value in return statement
```
The problem piece of code in the generated Any TF sdk
```go
// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
func (r *Provider) TerraformConfig(ctx *pulumi.Context) (pulumi.MapOutput, error) {
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return providerTerraformConfigResultOutput{}, err
	}
	out, err := ctx.CallPackage("pulumi:providers:tfe/terraformConfig", nil, providerTerraformConfigResultOutput{}, r, ref)
	if err != nil {
		return pulumi.MapOutput{}, err
	}
	return out.(providerTerraformConfigResultOutput).Result(), nil
}
```

### Output of `pulumi about`

Pulumi v3.201.0

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Fixes #20744
Fixes https://github.com/pulumi/pulumi-terraform-bridge/issues/3247

### Description

In the issues above, we are dealing with a SDK-gen problem in Go, specifically for a generated method/call that is parameterized and the schema has option `liftSingleValueMethodReturns` enabled.

### EDIT: testing via a SDK-gen schema rather than conformance tests 

The following is no longer relevant since conformance tests removed

```
The fix is actually pretty straightforward in Go SDK-gen but to properly conformance test it, this PR:
 - extends the `call` provider with `map[string]any` return type method called `configData` and tests it in `l2-provider-call-explicit` (simulating the type of the problematic `terraformConfig()` method in reported issues)
 - adds `liftedcall` provider and associated `l2-provider-call-explicit-lifted` which is exactly the same as the `call` provider but with a schema that enables `liftSingleValueMethodReturns=true`
 - `liftedcall` is implemented as a parameterized provider but doesn't do anything with the parameterization i.e. value is irrelevant but generated SDK is a parameterized one

Note for Python and NodeJS: this PR excludes `l2-provider-call-explicit-lifted` from the conformance testing because program-gen doesn't handle `liftSingleValueMethodReturns` so it doesn't simplify `method().result` into `method()` and the program fails. It can be handled in a follow-up PR via program overrides similar to what Go language tests do now but opted not to make the PR any bigger
```

### CODE REVIEW

File: cmd/pulumi-test-language/providers/lifted_call_provider.go [hunk 1]
```diff
@@ -0,0 +1,585 @@
...
+	}
+
+	langOptionsBytes, err := json.Marshal(languageOptions)
+	if err != nil {
+		return plugin.GetSchemaResponse{}, fmt.Errorf(
+			"failed to marshal language options for the schema: %w", err)
+	}
+
+	// apply the same language options to all supported languages
+	pkg.Language["go"] = langOptionsBytes
```
Comment (Frassle) [inline cmd/pulumi-test-language/providers/lifted_call_provider.go]: Rules are no setting of Language options in the conformance tests. If these options need testing they need adding in the languages test matrix. See how we test the various options for inputTypes in python.

Comment (Zaid-Ajaj) [reply cmd/pulumi-test-language/providers/lifted_call_provider.go]: This complicates things 😅 existing test `l2-provider-call` and `l2-provider-call-explicit` will fail on their "lifted" equivalent since program-gen doesn't handle it. Also many tests don't need this option because it is specific to generated methods. 

I can refactor the whole thing but would it be an option to make `liftSingleValueMethodReturns` a per-function field in the schema instead and test that alone? Since the option is not really Go-specific

Comment (Frassle) [reply cmd/pulumi-test-language/providers/lifted_call_provider.go]: yeh that sounds like it could make sense

Comment (Zaid-Ajaj) [reply cmd/pulumi-test-language/providers/lifted_call_provider.go]: @Frassle Raised https://github.com/pulumi/pulumi/pull/21135 for this ✅
