### PR TITLE
Jazzyfresh/codegen python nonstring secrets

### LINKED ISSUE #11278: [codegen/python] Invalid code generated when provider config input is array and marked secret
### What happened?

This is a call out from https://github.com/pulumi/pulumi-vault/issues/192.

As demonstrated in the example test case below, when a provider input field which has a type array and is marked secret, the generated code is invalid:
https://github.com/pulumi/pulumi/commit/8040c746c250f9e1a78b4e7f7e826490e4cd098d

Specifically the following line is invalid: https://github.com/pulumi/pulumi/commit/8040c746c250f9e1a78b4e7f7e826490e4cd098d#diff-0a99987d43fadae42640d41027b5461d76486fb8272aba6094b8e25ab79ff874R110

### Steps to reproduce

Follow example in https://github.com/pulumi/pulumi/commit/8040c746c250f9e1a78b4e7f7e826490e4cd098d

### Expected Behavior

Valid code generated

### Actual Behavior

Invalid code generated

### Output of `pulumi about`

_No response_

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by jazzyfresh**
# Description

Fixes incorrectly generated python code when secret is a non-string type.

Fixes #11278 

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/codegen/python/gen.go [hunk 1]
```diff
@@ -1302,10 +1302,14 @@ func (mod *modContext) genResource(res *schema.Resource) (string, error) {
...
-			arg = fmt.Sprintf("pulumi.Output.from_input(%s).apply(pulumi.runtime.to_json) if %s is not None else None", arg, arg)
+			if prop.Secret {
+				arg = fmt.Sprintf("pulumi.Output.from_input(%s).apply(pulumi.runtime.to_json) if %s is not None else None", arg, arg)
+			} else {
+				arg = fmt.Sprintf("pulumi.Output.secret(%s).apply(pulumi.runtime.to_json) if %s is not None else None", arg, arg)
+			}
 		}
 		name := PyName(prop.Name)
-		if prop.Secret {
+		if prop.Secret && isStringType(prop.Type) {
```
Comment (justinvp) [inline pkg/codegen/python/gen.go:1312]: I think the `&& isStringType(prop.Type)` check is going to break non-Provider resources that have secret properties that aren't strings.

Rather than checking `&& isStringType(prop.Type)`, how about a bool flag whether we already handled the secret? Something like:

```go
var handledSecret bool
if res.IsProvider && !isStringType(prop.Type) {
	if prop.Secret {
		arg = fmt.Sprintf("pulumi.Output.secret(%s).apply(pulumi.runtime.to_json) if %s is not None else None", arg, arg)
		handledSecret = true
	} else {
		arg = fmt.Sprintf("pulumi.Output.from_input(%s).apply(pulumi.runtime.to_json) if %s is not None else None", arg, arg)
 	}
}
name := PyName(prop.Name)
if prop.Secret && !handledSecret {
	fmt.Fprintf(w, "            __props__.__dict__[%[1]q] = None if %[2]s is None else pulumi.Output.secret(%[2]s)\n", name, arg)
} else {
 	fmt.Fprintf(w, "            __props__.__dict__[%q] = %s\n", name, arg)
}
```

File: pkg/codegen/testing/test/testdata/provider-config-schema/python/pulumi_configstation/provider.py [hunk 2]
```diff
@@ -86,7 +106,8 @@ def _internal_init(__self__,
 
             if favorite_color is None:
                 favorite_color = _utilities.get_env('FAVE_COLOR')
-            __props__.__dict__["favorite_color"] = pulumi.Output.from_input(favorite_color).apply(pulumi.runtime.to_json) if favorite_color is not None else None
+            __props__.__dict__["favorite_color"] = pulumi.Output.secret(favorite_color).apply(pulumi.runtime.to_json) if favorite_color is not None else None
+            __props__.__dict__["secret_sandwiches"] = pulumi.Output.from_input(secret_sandwiches).apply(pulumi.runtime.to_json) if secret_sandwiches is not None else None
```
Comment (justinvp) [inline pkg/codegen/testing/test/testdata/provider-config-schema/python/pulumi_configstation/provider.py:110]: Wait, the codegen looks incorrect...

```
__props__.__dict__["favorite_color"] = pulumi.Output.secret(favorite_color)
__props__.__dict__["secret_sandwiches"] = pulumi.Output.from_input(secret_sandwiches)
```

I would expect `favorite_color` to keep using `Output.from_input` and `secret_sandwiches` to use `Output.secret`

File: pkg/codegen/python/gen.go [hunk 3]
```diff
@@ -1302,10 +1302,14 @@ func (mod *modContext) genResource(res *schema.Resource) (string, error) {
 		// type, we must project all properties as strings. For all properties that are not strings,
 		// we'll marshal them to JSON and use the JSON string as a string input.
 		if res.IsProvider && !isStringType(prop.Type) {
-			arg = fmt.Sprintf("pulumi.Output.from_input(%s).apply(pulumi.runtime.to_json) if %s is not None else None", arg, arg)
+			if prop.Secret {
+				arg = fmt.Sprintf("pulumi.Output.from_input(%s).apply(pulumi.runtime.to_json) if %s is not None else None", arg, arg)
+			} else {
+				arg = fmt.Sprintf("pulumi.Output.secret(%s).apply(pulumi.runtime.to_json) if %s is not None else None", arg, arg)
```
Comment (justinvp) [inline pkg/codegen/python/gen.go:1308]: Oops, looks like this was flipped the wrong way:

```suggestion
				arg = fmt.Sprintf("pulumi.Output.secret(%s).apply(pulumi.runtime.to_json) if %s is not None else None", arg, arg)
			} else {
				arg = fmt.Sprintf("pulumi.Output.from_input(%s).apply(pulumi.runtime.to_json) if %s is not None else None", arg, arg)
```

File: pkg/codegen/testing/test/testdata/provider-config-schema/python/pulumi_configstation/provider.py (hunk 2 above)
Comment (justinvp) [reply pkg/codegen/testing/test/testdata/provider-config-schema/python/pulumi_configstation/provider.py:110]: Oh, I see... In `pkg/codegen/python/gen.go` above, the `if prop.Secret {`  is using `from_input` and the `else` is using `secret` mistakenly. Added a comment on that above.

**Review by justinvp — COMMENTED** [review]
A couple of things, but looks good otherwise!

File: pkg/codegen/python/gen.go (hunk 3 above)
Comment (jazzyfresh) [reply pkg/codegen/python/gen.go]: flipped

**Review by justinvp — APPROVED** [review]
LGTM!

**Comment by justinvp** [comment]
The `Test kubernetes Downstream` failure is due to https://github.com/pulumi/pulumi-kubernetes/pull/2256, but is blocked until we do a p/p tomorrow release.

**Comment by jazzyfresh** [comment]
bors merge
