### PR TITLE
Untargeted resources now have update plans.

### LINKED ISSUE #12926: Preview with `--target` appears to be planning to create non-targetted resources, throws error
### What happened?

Running `pulumi up --target "<existing-urn>"` on an existing stack that has had changes in code that would otherwise (without the target) create a new ComponentResource containing a Provider and new Resource. During `preview` and the first stage of `up`, it appears to be planning on creating the new Resource, and throws the error `resource should already have a plan from when we called register resources`

### Expected Behavior

We'd expect that the `target` doesn't try to create resources that aren't being targeted.

### Steps to reproduce

`pulumi new` -> `aws-typescript`. All the defaults.
`pulumi config set aws:profile myprofile`
`pulumi config set aws:region us-west-2`
`pulumi config set other:profile otherprofile`
`pulumi config set other:region us-west-2`

Create a `component.ts` with: 

```ts
import * as pulumi from '@pulumi/pulumi';
import * as aws from '@pulumi/aws';

export class OtherAccountBucket extends pulumi.ComponentResource {
    public readonly bucket: aws.s3.Bucket;
    constructor(opts: {}, componentOpts?: pulumi.ComponentResourceOptions) { 
        super('test:otheraccount:bucket', 'otheraccountbucket', {}, componentOpts);

        const otherAccount = new pulumi.Config('other');
        const otherAccountProvider = new aws.Provider(
            'other-account-provider',
            {
                profile: otherAccount.get('profile'),
                region: otherAccount.get('region') as pulumi.Input<aws.Region>
            },
            { 
                parent: this
            }
        );

        this.bucket = new aws.s3.Bucket(
            `testbucket`,
            { 
                bucket: `s3-testbucket`,
                acl: 'private'
            },
            {
                parent: this,
                provider: otherAccountProvider
            }
        );
    }
}
```

And modify `index.ts` to:
```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import { OtherAccountBucket } from "./component";

// Create an AWS resource (S3 Bucket)
const bucket = new aws.s3.Bucket("my-bucket");
// const otherBucket = new OtherAccountBucket("other-bucket");

// Export the name of the bucket
export const bucketName = bucket.id;
```

`pulumi up` stands up the first S3 `my-bucket` as intended. Get the urn, uncomment `otherBucket`, and run:
`pulumi up --target "urn:pulumi:dev::ProviderTest::aws:s3/bucket:Bucket::my-bucket"`

Will generate the error:
```
Diagnostics:
  test:otheraccount:bucket (otheraccountbucket):
    error: resource should already have a plan from when we called register resources [urn=urn:pulumi:dev::ProviderTest::test:otheraccount:bucket::otheraccountbucket]
```

### Output of `pulumi about`

```CLI          
Version      3.67.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.35.0
awsx    1.0.2
docker  3.6.1
nodejs  unknown
random  4.13.0

Host     
OS       darwin
Version  13.3.1
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v19.7.0'

Dependencies:
NAME            VERSION
@pulumi/aws     5.35.0
@pulumi/awsx    1.0.2
@pulumi/pulumi  3.67.0
@pulumi/random  4.13.0
@types/node     16.18.23
```

### Additional context

3.66 fixed a bug with this same setup where the Provider was being created in an unparented state #12621 
This introduced #12824 which appears to have applied to all `--targets`, was fixed in 3.67.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
Fixes #12926

# What
This change modifies the step_generator to include untargeted resources in plans.

# Why
This prevents the step_executor from erroring from an untargeted resource being registered.

The `step_executor` would error due to an untargeted resource being registered while not being included in the update plan.

This appeared to be applicable only to users using update plans, but update plans are enabled by default internally.

There are some rare cases where they are not such as if `--skip-preview` is set, or if using `pulumi up` with URLs or Templates without PULUMI_EXPERIMENTAL being truthy.

# Previous Context
This error previously appeared in #12824 and was believed to be due to the root stack resource not being targeted in liue of informative error messages.

A fix was merged in:

https://github.com/pulumi/pulumi/pull/12834

This also contained an enhanced error message containing the offending URN of the resource.

The fix was shipped in 3.67.0, but #12926 was opened with the new error message indicating that the problem was still outstanding and it was applicable to resources that weren't the root stack resource.

### CODE REVIEW

File: pkg/engine/lifecycletest/update_plan_test.go [hunk 1]
```diff
@@ -1751,7 +1751,11 @@ func TestReplaceSpecificTargetsPlan(t *testing.T) {
 
 		if createResB {
 			// Now try to create resB which is not targeted and should not show up in the plan.
```
Comment (justinvp) [inline pkg/engine/lifecycletest/update_plan_test.go:1753]: This comment needs to be updated now

**Review by justinvp — APPROVED** [review]
LGTM

**Comment by dixler** [comment]
bors merge
