### PR TITLE
Pulumi no longer falls back on old configuration by default.

### LINKED ISSUE #13487: Bug or feature that I can accidentally refer to prior configuration values?
### What happened?

v3.74.0

I accidentally cleared out the configuration value in my Pulimi.dev.yaml file with a particular character `]` and found that on a `up` my config.require code was not only succeeding but also feed the correct value (json string) to code.  

### Expected Behavior

I would expect that if I put a single ']' or '[' in place of previously comited/up'd configurations that it would pass the literal value through to `config.require` and not supply the previous value.

### Steps to reproduce

new project Typescript
```
import {Config} from "@pulumi/pulumi";

const config = new Config();
const sneakyValue = config.require<string>('sneakyValue')
export const myValue = sneakyValue
```
Make sure you add the config value
```
p config set sneakyValue foobarbaz
```
so your Pulumi.dev.yaml looks like ...
```
config:
  aws:region: us-gov-west-1
  pulumtest:sneakyValue: foobarbaz
```

Now do a pulumi up ...
```

     Type                 Name           Status
 +   pulumi:pulumi:Stack  pulumtest-dev  created (0.36s)


Outputs:
    myValue: "foobarbaz"

Resources:
    + 1 created

Duration: 2s
```

Okay now the interesting part, change the yaml config file,... specifically replace `foobarbaz` with either `]` or `[` NOT BOTH!
So like so ...
```
config:
  aws:region: us-gov-west-1
  pulumtest:sneakyValue: [

```
now do another pulumi up and rather then seeing your change as the export you will see the prior value.

```
     Type                 Name           Status
     pulumi:pulumi:Stack  pulumtest-dev


Outputs:
    myValue: "foobarbaz"

Resources:
    1 unchanged

Duration: 1s
```

This gets even more interesting when that value is say a complex JSON string that feeds a loop of creating EC2 instances .... which is how I originally found this issue.  I was stunned that the planner wasn't finding any different between the implications my complex JSON having been replaced with a single character and none of the related resources were being replaced.
So I thought more on it cuz... yea that's odd and added a log statement.
```
pulumi.log.info(sneakyValue)
```
as you ... mmm... wouldn't expect, but do expect now I guess ... is that pulumi log shows the original value
```
Diagnostics:
  pulumi:pulumi:Stack (pulumtest-dev):
    foobarbaz
```
despite the config being in this divergent state.

Feature? or bug?  
Honestly I like the feature, it means that I can refer to configuration state from the past?

Is it pulling config from REST API?  That would be a cool feature if it did. 

### Output of `pulumi about`

```
CLI
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.42.0
awsx    1.0.2
docker  3.6.1
nodejs  unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description

Pulumi no longer falls back on prior configuration on error getting configuration except for `pulumi destroy --stack <stack-name>` where a user may run `pulumi destroy` and the configuration may not be available.

Fixes #13487

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by abhinav — APPROVED** [review]

File: pkg/cmd/pulumi/config.go [hunk 1]
```diff
@@ -1016,13 +1016,26 @@ func getStackConfiguration(
...
 	defaultStackConfig := backend.StackConfiguration{}
 
 	workspaceStack, err := loadProjectStack(project, stack)
 	if err != nil || workspaceStack == nil {
+		if fallbackGetConfig == nil {
+			return defaultStackConfig, nil, err
+		}
 		// On first run or the latest configuration is unavailable, fallback to check the project's configuration
-		cfg, err := backend.GetLatestConfiguration(ctx, stack)
+		cfg, err := fallbackGetConfig()
```
Comment (justinvp) [inline pkg/cmd/pulumi/config.go:1038]: If there are syntax errors in the yaml file, shouldn't we still be bubbling that error up to the user, even during destroy? I wonder if we should only be doing this fallback if the stack config doesn't exist.

Comment (dixler) [reply pkg/cmd/pulumi/config.go]: I've updated the PR so that `pulumi destroy` will only fall back on the latest config if both:
1. `--stack` is provided
2. there's no project detected (which occurs when outside of a pulumi project directory)

File: pkg/cmd/pulumi/config_test.go [hunk 2]
```diff
@@ -46,3 +49,66 @@ func TestSecretDetection(t *testing.T) {
...
+			},
+		},
+		nil,
+		nil,
+	)
+}
+
+func TestGetStackConfigurationOrLatest(t *testing.T) {
+	t.Parallel()
+	// Don't check return values. Just check that GetLatestConfiguration() is not called.
```
Comment (justinvp) [inline pkg/cmd/pulumi/config_test.go:83]: Right?

```suggestion
	// Don't check return values. Just check that GetLatestConfiguration() is called.
```

**Review by justinvp — APPROVED** [review]
LGTM

**Comment by dixler** [comment]
bors merge
