### PR TITLE
Fix handling of delete failures for targeted destroys

### LINKED ISSUE #8164: State corruption when destroy fails to remove a resource
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Logged earlier in https://github.com/pulumi/pulumi-azure-native/issues/1203

I'm experiencing state corruption during destroy of an explicit target including the `--target-dependents` switch.
A couple of child resources fail to be destroyed resulting in an aborted destroy operation. When I try again, the target resource and all child resources are no longer in the state (while the resources remain to exist in Azure).

Currently using local filesystem for state store as I'm still experimenting.

### Steps to reproduce

1. create resource hierarchy as described above (rg -> sql server -> db -> retention policy)
2. pulumi up (resources are created)
3. pulumi destroy --target sqlserverUrn --target-depend (see failures happening)
4. try again

Expected:  Resources to be removed and no corruption in my state if something did not happen.
Actual: Resources where not removed and I lost track of my resources in the state which where not actually deleted.

### LINKED ISSUE #14416: Pulumi down dropping resources from the state on timeout (possibly related to --exclude-protected)
### What happened?

The scenario:
1. I create a stack with quite a few resources. The creation is succesful.
2. I execute a pulumi down command to destroy the stack (excluding some protected resources) .The down operation fails due to a timeout.
3. I do pulumi refresh and it tells me there are only a few resources left in the stack
4. Another pulumi down operation tells me there are only protected resources left

However on inspection of my AWS account, there is a whole bunch of resources left over (not protected ones).
I now have to check all my resources manually and clean them up, which is a major PITA, not to mention a financial liability.
It seems that an error during the pulumi down operation just causes pulumi to assume everything is probably gone and remove it from the state?

I went through my account and found almost half of the resources still there:
* client vpn endpoint
* nat gateway
* vpc
* hosted zone
* records in an existing hosted zone
* log groups
* IPAM pool and related

### Example

image

image

### Output of `pulumi about`

CLI
Version      3.91.0
Go Version   go1.21.3
Go Compiler  gc

Host
OS       darwin
Version  14.0
Arch     arm64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/dieter-aerit
User           dieter-aerit
Organizations  dieter-aerit
Token type     personal

### Additional context

Note that I was running Pulumi 3.89 when this happened

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
When doing a targeted destroy, if a delete operation for a resource fails, the resource was still being removed from the state. Instead, if the delete operation for a resource fails, it should remain in the state.

Fixes #8164
Fixes #14416

### CODE REVIEW

File: pkg/resource/deploy/deployment_executor.go [hunk 1]
```diff
@@ -388,17 +388,6 @@ func (ex *deploymentExecutor) performDeletes(
...
-	// After executing targeted deletes, we may now have resources that depend on the resource that
-	// were deleted.  Go through and clean things up accordingly for them.
-	if targetsOpt.IsConstrained() {
-		resourceToStep := make(map[*resource.State]Step)
-		for _, step := range deleteSteps {
-			resourceToStep[ex.deployment.olds[step.URN()]] = step
-		}
-
-		ex.rebuildBaseState(resourceToStep, false /*refresh*/)
-	}
```
Comment (justinvp) [inline pkg/resource/deploy/deployment_executor.go:400]: This is the problematic code. It's assuming all the delete steps will be successful, removing the associated resources from the state, but that may not be the case if a delete fails.

Originally, I was thinking we'd have to rework this to only do it for successful delete operations, but thinking about it more, I _think_ we don't have to call `ex.rebuildBaseState` at all for targeted deletes because if we're doing a targeted delete, we're already forced to specify dependents (or specify TargetDependents), so there shouldn't be a need to clean things up. Does this sound right, or am I missing something?

Comment (justinvp) [reply pkg/resource/deploy/deployment_executor.go:400]: @Frassle, @pgavlin, can you sanity check me on this?

Comment (Frassle) [reply pkg/resource/deploy/deployment_executor.go:400]: >  we're already forced to specify dependents

Are we? I think we check that only targetted resources or their dependents _can_ be deleted, but it looks like the planner would allow deleting a parent and not a child? It probably shouldn't but do we have a test to prove that either way?

Comment (justinvp) [reply pkg/resource/deploy/deployment_executor.go:400]: The PR adds a test for this: https://github.com/pulumi/pulumi/pull/14735/files#diff-aa36a122dd8ff659d8ba8df709cf3fac67dce2b07d5ad8c51240eb76b08d7022R1664-R1666

If I try to target a parent and not its child, it errors.

File: pkg/engine/lifecycletest/target_test.go [hunk 2]
```diff
@@ -1599,3 +1600,356 @@ func TestTargetUntargetedParent(t *testing.T) {
...
+
+	snap, err = TestOp(Destroy).Run(project, p.GetTarget(t, snap), TestUpdateOptions{
+		HostF: hostF,
+		UpdateOptions: UpdateOptions{
+			Targets: deploy.NewUrnTargets([]string{
+				"urn:pulumi:test::test::pkgA:m:typA::resA",
+			}),
+		},
+	}, false, p.BackendClient, nil)
+	assert.Error(t, err) // Expect error because we didn't specify the dependency as a target or TargetDependents
```
Comment (Frassle) [inline pkg/engine/lifecycletest/target_test.go:1660]: Don't use `assert.Error` but `EqualError` or at least `ErrorContains` to check this is the error we expect.

File: pkg/engine/lifecycletest/target_test.go [hunk 3]
```diff
@@ -1599,3 +1600,356 @@ func TestTargetUntargetedParent(t *testing.T) {
...
+	snap, err = TestOp(Destroy).Run(project, p.GetTarget(t, snap), TestUpdateOptions{
+		HostF: hostF,
+		UpdateOptions: UpdateOptions{
+			Targets: deploy.NewUrnTargets([]string{
+				"urn:pulumi:test::test::pkgA:m:typA::resA",
+			}),
+		},
+	}, false, p.BackendClient, nil)
+	assert.Error(t, err)
+	validateSnap(snap)
```
Comment (Frassle) [inline pkg/engine/lifecycletest/target_test.go:1782]: This should also assert that the resource is tagged with delete=true

File: pkg/engine/lifecycletest/target_test.go (hunk 2 above)
Comment (justinvp) [reply pkg/engine/lifecycletest/target_test.go:1660]: I can add it, but it's not actually very specific in this case: we get a generic error that says "step generator errored".

What's happening is we write out error messages to the user and then set `sawError = true`:

https://github.com/pulumi/pulumi/blob/3d37369cb4245c90262b172e962e09694fe70f1a/pkg/resource/deploy/step_generator.go#L1278-L1290

https://github.com/pulumi/pulumi/blob/3d37369cb4245c90262b172e962e09694fe70f1a/sdk/go/common/diag/errors.go#L79-L82

The actual `step generator errored` error we get here from `Run` is from this:

https://github.com/pulumi/pulumi/blob/3d37369cb4245c90262b172e962e09694fe70f1a/pkg/resource/deploy/deployment_executor.go#L326-L337

File: pkg/engine/lifecycletest/target_test.go (hunk 3 above)
Comment (Frassle) [reply pkg/engine/lifecycletest/target_test.go:1782]: Ah yeh just checked, it is only for replacements we do that.

File: pkg/engine/lifecycletest/target_test.go (hunk 2 above)
Comment (Frassle) [reply pkg/engine/lifecycletest/target_test.go:1660]: Hmm ok, I might have a look at making that error better then. It would be good to be able to test in places like this which bit of the engine err'd even if we don't bubble that error value specifically back to the user. Was a big point of the bail rework we did. But no need to be done in this PR, can tidy that later.

**Review by Frassle — APPROVED** [review]
