### PR TITLE
Elide `StackReference` outputs that fail to decrypt

### LINKED ISSUE #11109: accessing non-secrets from StackReference still requires access to the secretsprovider key
### What happened?

I am trying to have all our Pulumi stacks have awskms secretsprovider.
I have found out that instantiating a StackReference requires being able to perform `kms:Decrypt` on the KMS key of the reference target.

This is not optimal, because in many cases we want to read non-secret values from stacks that have both non-secret and secret outputs - we should not need to grant the stack referring to non-secret outputs of another stack visibility into the secrets.

### Steps to reproduce

This:
```typescript
const reference = new pulumi.StackReference(`${pulumi.getOrganization()}/project/prod`)
```

explodes during `pulumi preview` with:

```
error: Preview failed: constructing secrets manager of type "cloud": secrets (code=Unknown): AccessDeniedException: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.
	status code: 400, request id: [...]
```

even though the only output we access is a non-secret one:

```typescript
const value = reference.getOutput("output")
```

The referenced stack config:

```yaml
$ cat Pulumi.prod.yaml 
secretsprovider: awskms://alias/<alias>?region=<region>
encryptedkey: <encrypted key>
$ 
```

### Expected Behavior

I expected the `pulumi.StackReference` to be initialized successfully and `reference.getOutput` on a non-secret output to work correctly without access to the KMS key of the referenced stack.

I expected only a `reference.getOutput` on a secret output to fail without access to the KMS key of the referenced stack.

### Actual Behavior

`new pulumi.StackReference()` fails if it can't `kms:Decrypt` on the target's KMS key. 

### Output of `pulumi about`

```
Filip.Zyzniewski@JFYYQW9DJ7 taxamo-infrastructure-enterprise % pulumi about
CLI          
Version      3.43.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME      VERSION
aws       4.38.1
docker    3.2.0
nodejs    unknown
opsgenie  1.1.5
random    4.4.2

Host     
OS       darwin
Version  12.2
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v18.8.0'

Current Stack: <masked>

TYPE                                                        URN
[...]

Found no pending operations associated with <masked>

Backend        
Name           pulumi.com
URL            <masked>
User           <masked>
Organizations  <masked>

Dependencies:
NAME                              VERSION
@pulumi/aws                       4.38.1
@typescript-eslint/eslint-plugin  4.33.0
@typescript-eslint/parser         4.33.0
eslint-plugin-tsdoc               0.2.16
typescript                        4.6.3
@pulumi/awsx                      0.32.0
@pulumi/opsgenie                  1.1.5
@pulumi/pulumi                    3.42.0
@pulumi/random                    4.4.2
@types/node                       16.0.0
aws-sdk                           2.1117.0
eslint                            7.32.0
yaml                              1.10.2

Pulumi locates its logs in /var/folders/xc/rb73zyjd3kq26tv0hpk4wxh40000gq/T/ by default
$ 
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by lunaris**
`StackReference` is a resource offered by all core Pulumi SDKs, backed internally by the built-in provider. `StackReference`s allow stacks to read and refer to the outputs of other stacks. For example, given two stacks A and B, here written in TypeScript:

```typescript
// a/index.ts

export = async () => {
  return {
    aString: "from-a",
  }
}

// b/index.ts

export = async () => {
  const aRef = new pulumi.StackReference("organization/a/dev");

  const aString = aRef.getOutput("aString")

  return {
    bString: pulumi.interpolate`from-b-and-${aString}`,
  }
}
```

Here, A produces a single output, `aString`, with the value `from-a`. B creates a `StackReference` to A and loads the `aString` output, before including it in its own output, yielding `bString: "from-b-and-from-a"`.

This all works well, and can in theory handle any output value that can be serialized to state. Even secret values are supported, albeit with one limitation -- the referencing stack (here B) must be able to _decrypt_ the secrets of the referenced stack (here A). If both stacks are e.g. using the same secrets manager (such as is the case with the Pulumi service), everything is fine. If they are not, a decryption error will likely be thrown, stopping the execution of the referencing stack. This happens even if the referencing stack only uses non-secret values (since presently, all outputs are loaded at once), causing issues such as #11109.

In this case, we remove the requirement for `StackReference`s to be able to decrypt secrets in referenced stacks. If a decryption fails, a dummy value (that will likely cause errors if used) is returned, allowing plain values to be shared freely. Additionally, in such cases, an `info` diagnostic is emitted informing the user that secret values have been elided, with an accompanying `debug` diagnostic (which is not visible by default) holding the last encountered error message details.

Fixes #11109

### CODE REVIEW

**Comment by lunaris** [comment]
Some examples here with two stacks using the service as a backend but passphrase secrets managers with different keys (the referencing stack has `Test2345`, while the referenced stack has `Test1234`). Passphrase set to `Test2345`, allowing referencing stack to run but referenced stack fails to decrypt. By default, info diagnostic:

image

**Comment by lunaris** [comment]
With `--debug`, we see the full debug diagnostic:

image

File: pkg/backend/stack_outputs.go [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+	return p.lastDecryptError
+}
+
+func (p *stackOutputsProvider) OfType(ty string, state json.RawMessage) (secrets.Manager, error) {
+	delegateManager, err := p.delegate.OfType(ty, state)
+	if err != nil {
+		return nil, err
+	}
+
+	delegateDecrypter := delegateManager.Decrypter()
```
Comment (Frassle) [inline pkg/backend/stack_outputs.go:50]: Why are we doing this here? I don't think we need to grab the decrypter this early.

File: pkg/backend/backend.go [hunk 2]
```diff
@@ -356,18 +356,27 @@ func (c *backendClient) GetStackOutputs(ctx context.Context, name string) (resou
...
 	if err != nil {
 		return nil, err
 	}
+
 	res, err := stack.GetRootStackResource(snap)
 	if err != nil {
 		return nil, fmt.Errorf("getting root stack resources: %w", err)
 	}
+
+	providerErr := secretsProvider.Error()
```
Comment (Frassle) [inline pkg/backend/backend.go:371]: This isn't obvious at first glance, if this stays it needs a comment around what this Error is

File: pkg/resource/deploy/builtins.go [hunk 3]
```diff
@@ -286,7 +286,13 @@ func (p *builtinProvider) readStackReference(inputs resource.PropertyMap) (resou
 
 	outputs, err := p.backendClient.GetStackOutputs(p.context, name.StringValue())
 	if err != nil {
-		return nil, err
+		var decryptionErr *StackOutputDecryptionError
+		if !errors.As(err, &decryptionErr) {
+			return nil, err
+		}
+
+		p.diag.Infof(diag.Message("", "eliding undecryptable secrets for stack reference '%s'"), name.StringValue())
```
Comment (Frassle) [inline pkg/resource/deploy/builtins.go:294]: wonder if we should list which property paths where elided? "eliding undecryptable secrets 'foo', 'bar.baz', for stack reference 'a/b/c'"?

File: pkg/resource/deploy/builtins.go [hunk 4]
```diff
@@ -286,7 +286,13 @@ func (p *builtinProvider) readStackReference(inputs resource.PropertyMap) (resou
 
 	outputs, err := p.backendClient.GetStackOutputs(p.context, name.StringValue())
 	if err != nil {
-		return nil, err
+		var decryptionErr *StackOutputDecryptionError
```
Comment (Frassle) [inline pkg/resource/deploy/builtins.go:289]: Feel like it would be cleaner to thread the diag sink into GetStackOutputs and just write the diangostics there rather than having this StackOutputDecryptionError type. It's a bit odd in Go to return a result _and_ an error, it happens, but it feels like something that will get tripped up on.

File: pkg/backend/stack_outputs.go (hunk 1 above)
Comment (lunaris) [reply pkg/backend/stack_outputs.go:50]: Was more thinking neater to "know" it's non-`nil` later on, and all our `Decrypter()` calls happen to be just property accesses right now. But I can push it down :+1:

File: pkg/resource/deploy/builtins.go (hunk 4 above)
Comment (lunaris) [reply pkg/resource/deploy/builtins.go:289]: I started with that but it felt a bit uglier in terms of dependency graph, but I agree it's not like this approach is particularly beautiful either. Will give it another spin.

Comment (lunaris) [reply pkg/resource/deploy/builtins.go:289]: I guess if we do that, there's no way (not that we need it now, and possibly not ever) to observe if secret decryption failed -- unless you can deeply introspect a `diag.Sink`, which I don't think you can (you could wrap one I guess)

File: pkg/resource/deploy/builtins.go (hunk 3 above)
Comment (lunaris) [reply pkg/resource/deploy/builtins.go:300]: Discussed and we don't think this is possible right now so we have gone with the existing mechanism.

File: pkg/backend/backend.go (hunk 2 above)
Comment (lunaris) [reply pkg/backend/backend.go]: Reworked as discussed using a callback.

**Review by Frassle — APPROVED** [review]
