### PR TITLE
[sdk/dotnet] - bug fix resources destroyed after exception thrown during inline program

### LINKED ISSUE #7050: Exception thrown in stack results in resources marked for deletion
If an exception happens while executing my stack code, it causes the program to exit, and any resource that would have been defined after the exception gets marked for deletion (or worse actually deleted). I have only tried this in the dotnet SDK.

## Expected behavior
I would have expected the program exiting on error would cause pulumi to not move forward with the preview/up operation.

## Current behavior
Currently, pulumi does see the exception, and logs it as a diagnostic. But it then continues as if your program was complete and any resources that weren't yet created act as if you were removing them from your source code / stack.

## Steps to reproduce
```c#
public class Program
{
    public static async Task Main(string[] args)
        => await Deployment.RunAsync<MyStack>();
}

public class MyStack : Stack
{
    public MyStack()
    {
        var a = new Pulumi.Random.RandomInteger("a", new Pulumi.Random.RandomIntegerArgs { Min = 1, Max = 100 });

        if (Environment.GetEnvironmentVariable("oops") == "yes") throw new Exception("oops");

        var b = new Pulumi.Random.RandomInteger("b", new Pulumi.Random.RandomIntegerArgs { Min = 1, Max = 100 });

        var c = new Pulumi.Random.RandomInteger("c", new Pulumi.Random.RandomIntegerArgs { Min = 1, Max = 100 });
    }
}
```

successful `pulumi up` :
```
root@5ecb18015b1a:/app# oops=no pulumi up -y --non-interactive
Previewing update (test):
    pulumi:pulumi:Stack test-test  running 'dotnet build -nologo .'
    pulumi:pulumi:Stack test-test    Restore completed in 36.76 ms for /app/PulumiIssue.csproj.
    pulumi:pulumi:Stack test-test    PulumiIssue -> /app/bin/Debug/netcoreapp3.1/PulumiIssue.dll
    pulumi:pulumi:Stack test-test
    pulumi:pulumi:Stack test-test      0 Warning(s)
    pulumi:pulumi:Stack test-test  'dotnet build -nologo .' completed successfully

 +  pulumi:pulumi:Stack test-test create 'dotnet build -nologo .' completed successfully
 +  random:index:RandomInteger a create
 +  random:index:RandomInteger c create
 +  random:index:RandomInteger b create
 +  pulumi:pulumi:Stack test-test create

Resources:
    + 4 to create

Updating (test):
    pulumi:pulumi:Stack test-test  running 'dotnet build -nologo .'
    pulumi:pulumi:Stack test-test    Restore completed in 34.75 ms for /app/PulumiIssue.csproj.
    pulumi:pulumi:Stack test-test    PulumiIssue -> /app/bin/Debug/netcoreapp3.1/PulumiIssue.dll
    pulumi:pulumi:Stack test-test
    pulumi:pulumi:Stack test-test      0 Warning(s)
    pulumi:pulumi:Stack test-test  'dotnet build -nologo .' completed successfully

 +  pulumi:pulumi:Stack test-test creating 'dotnet build -nologo .' completed successfully
 +  random:index:RandomInteger c creating
 +  random:index:RandomInteger a creating
 +  random:index:RandomInteger b creating
 +  random:index:RandomInteger c created
 +  random:index:RandomInteger a created
 +  random:index:RandomInteger b created
 +  pulumi:pulumi:Stack test-test created

Resources:
    + 4 created

Duration: 3s
```
followed by a failed preview attempt:
```
root@5ecb18015b1a:/app# oops=yes pulumi preview --non-interactive
Previewing update (test):
    pulumi:pulumi:Stack test-test  running 'dotnet build -nologo .'
    pulumi:pulumi:Stack test-test    Restore completed in 38.84 ms for /app/PulumiIssue.csproj.
    pulumi:pulumi:Stack test-test    PulumiIssue -> /app/bin/Debug/netcoreapp3.1/PulumiIssue.dll
    pulumi:pulumi:Stack test-test
    pulumi:pulumi:Stack test-test      0 Warning(s)
    pulumi:pulumi:Stack test-test  'dotnet build -nologo .' completed successfully

    pulumi:pulumi:Stack test-test running 'dotnet build -nologo .' completed successfully
    random:index:RandomInteger a
    pulumi:pulumi:Stack test-test running error: Running program '/app/bin/Debug/netcoreapp3.1/PulumiIssue.dll' failed with an unhandled exception:
 -  random:index:RandomInteger c delete
 -  random:index:RandomInteger b delete
    pulumi:pulumi:Stack test-test  1 error

Diagnostics:
  pulumi:pulumi:Stack (test-test):
    error: Running program '/app/bin/Debug/netcoreapp3.1/PulumiIssue.dll' failed with an unhandled exception:
    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
     ---> System.Exception: oops
       at PulumiIssue.MyStack..ctor() in /app/Program.cs:line 21
       --- End of inner exception stack trace ---
       at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
       at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
       at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
       at System.Activator.CreateInstance[T]()
       at Pulumi.Deployment.Runner.<>c__4`1.<RunAsync>b__4_0()
       at Pulumi.Deployment.Runner.RunAsync[TStack](Func`1 stackFactory)
```
or if you aren't careful, a problematic `up`:
```
root@5ecb18015b1a:/app# oops=yes pulumi up -y --non-interactive
Previewing update (test):
    pulumi:pulumi:Stack test-test  running 'dotnet build -nologo .'
    pulumi:pulumi:Stack test-test    Restore completed in 35.49 ms for /app/PulumiIssue.csproj.
    pulumi:pulumi:Stack test-test    PulumiIssue -> /app/bin/Debug/netcoreapp3.1/PulumiIssue.dll
    pulumi:pulumi:Stack test-test
    pulumi:pulumi:Stack test-test      0 Warning(s)
    pulumi:pulumi:Stack test-test  'dotnet build -nologo .' completed successfully

    pulumi:pulumi:Stack test-test running 'dotnet build -nologo .' completed successfully
    random:index:RandomInteger a
    pulumi:pulumi:Stack test-test running error: Running program '/app/bin/Debug/netcoreapp3.1/PulumiIssue.dll' failed with an unhandled exception:
 -  random:index:RandomInteger c delete
 -  random:index:RandomInteger b delete
    pulumi:pulumi:Stack test-test  1 error

Diagnostics:
  pulumi:pulumi:Stack (test-test):
    error: Running program '/app/bin/Debug/netcoreapp3.1/PulumiIssue.dll' failed with an unhandled exception:
    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
     ---> System.Exception: oops
       at PulumiIssue.MyStack..ctor() in /app/Program.cs:line 21
       --- End of inner exception stack trace ---
       at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
       at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
       at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
       at System.Activator.CreateInstance[T]()
       at Pulumi.Deployment.Runner.<>c__4`1.<RunAsync>b__4_0()
       at Pulumi.Deployment.Runner.RunAsync[TStack](Func`1 stackFactory)


Updating (test):
    pulumi:pulumi:Stack test-test  running 'dotnet build -nologo .'
    pulumi:pulumi:Stack test-test    Restore completed in 37.44 ms for /app/PulumiIssue.csproj.
    pulumi:pulumi:Stack test-test    PulumiIssue -> /app/bin/Debug/netcoreapp3.1/PulumiIssue.dll
    pulumi:pulumi:Stack test-test
    pulumi:pulumi:Stack test-test      0 Warning(s)
    pulumi:pulumi:Stack test-test  'dotnet build -nologo .' completed successfully

    pulumi:pulumi:Stack test-test running 'dotnet build -nologo .' completed successfully
    random:index:RandomInteger a
    pulumi:pulumi:Stack test-test running error: Running program '/app/bin/Debug/netcoreapp3.1/PulumiIssue.dll' failed with an unhandled exception:
 -  random:index:RandomInteger c deleting
 -  random:index:RandomInteger b deleting
 -  random:index:RandomInteger c deleted
 -  random:index:RandomInteger b deleted
    pulumi:pulumi:Stack test-test **failed** 1 error

Diagnostics:
  pulumi:pulumi:Stack (test-test):
    error: Running program '/app/bin/Debug/netcoreapp3.1/PulumiIssue.dll' failed with an unhandled exception:
    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
     ---> System.Exception: oops
       at PulumiIssue.MyStack..ctor() in /app/Program.cs:line 21
       --- End of inner exception stack trace ---
       at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
       at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
       at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
       at System.Activator.CreateInstance[T]()
       at Pulumi.Deployment.Runner.<>c__4`1.<RunAsync>b__4_0()
       at Pulumi.Deployment.Runner.RunAsync[TStack](Func`1 stackFactory)

Resources:
    - 2 deleted
    2 unchanged

Duration: 3s
```

## Context (Environment)
This tripped me up as I was iterating on a stack I have been working on (luckily no real resources were harmed). Towards the beginning of my stack I usually `config.Require` all of my inputs. When I misspelled one of my config names, it failed super early and therefore pretty much every resource was marked for deletion. 

This test was run in the pulumi/pulumi:v3.2.1 docker container.

### PR DESCRIPTION
**Pull request by orionstudt**
# Description

This resolves the issue of resources being destroyed after an exception is thrown during an inline program. The gRPC portion of the Automation API implementation is now correctly returning in the error case and the `WorkspaceStack` instance is now conditionally throwing the relevant exception if an inline exception is present, that way the correct exception bubbles up to the Automation API consumer.

Fixes #7050

## Checklist

- [X] I have added tests that prove my fix is effective or that my feature works

- [X] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: sdk/dotnet/Pulumi.Automation/Runtime/LanguageRuntimeService.cs [hunk 1]
```diff
@@ -60,7 +61,14 @@ public override async Task<RunResponse> Run(RunRequest request, ServerCallContex
                 runner => this._callerContext.Program.InvokeAsync(runner, cts.Token))
                 .ConfigureAwait(false);
 
-            return new RunResponse();
```
Comment (t0yv0) [inline sdk/dotnet/Pulumi.Automation/Runtime/LanguageRuntimeService.cs:63]: From Go I got used to early return being for the "exceptional" case not the happy case, don't know if this also makes sense in C# stylistically.

Comment (orionstudt) [reply sdk/dotnet/Pulumi.Automation/Runtime/LanguageRuntimeService.cs:63]: I've seen it both ways, probably just a style decision. Up to you guys. I did it this way because Pulumi hasn't yet bumped their c# version such that we can use `is not null` and I find `is null` easier to read than `!= null`.

File: sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs [hunk 2]
```diff
@@ -1554,6 +1554,80 @@ public async Task InlineProgramLoggerCanRedirectToTestOutput()
...
+                var sb = new System.Text.StringBuilder();
+
+                await Assert.ThrowsAsync<FileNotFoundException>(
+                    () => stack.UpAsync(new UpOptions()
+                    {
+                        OnStandardOutput = msg => sb.AppendLine(msg),
+                    }));
+
+                var upOutput = sb.ToString();
+                Assert.DoesNotContain("test:res:b b deleted", upOutput);
```
Comment (t0yv0) [inline sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs:1610]: This is a little creative I like it :) Is there an API to do this more naturally like ResourceChanges or there is no such API?

File: sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs [hunk 3]
```diff
@@ -275,9 +275,25 @@ public Task RemoveAllConfigAsync(IEnumerable<string> keys, CancellationToken can
...
+                    upResult = await this.RunCommandAsync(
+                        args,
+                        options?.OnStandardOutput,
+                        options?.OnStandardError,
+                        options?.OnEvent,
+                        cancellationToken).ConfigureAwait(false);
+                }
+                catch
+                {
+                    if (inlineHost != null && inlineHost.TryGetExceptionInfo(out var exceptionInfo))
```
Comment (t0yv0) [inline sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs:290]: This is a little interesting here could you help me understand what is going on exactly? Presumably RunCommandAsync fails with an exception (catch), but we prefer to throw an exception captured by `inlineHost` if any. What is the original exception? It's not linked to or contain the inline host exception in any way?

**Comment by t0yv0** [comment]
Sorry for late review again, I'm finally catching up. This looks reasonable I'd like to understand the fix a little better though, left some questions! Thanks for the work!

File: sdk/dotnet/Pulumi.Automation/Runtime/LanguageRuntimeService.cs (hunk 1 above)
Comment (t0yv0) [reply sdk/dotnet/Pulumi.Automation/Runtime/LanguageRuntimeService.cs:63]: Let's leave it as is then! ty.

File: sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs (hunk 2 above)
Comment (orionstudt) [reply sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs:1610]: This test was borrowed from @vipentti's PR! I agree that it was creative. It works for our purpose here so I didn't look into improving on it. I guess we could subscribe to engine events and verify that no destroy events were published for the relevant resources?

Comment (t0yv0) [reply sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs:1610]: I'm not worried the test is fragile, I'd be worried if the API is lacking to get this info in a typed fashion if you want to. I guess there's an API so we're good.

File: sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs (hunk 3 above)
Comment (orionstudt) [reply sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs:290]: So now that the `LanguageRuntimeService` is returning a failure response correctly, that means that `RunCommandAsync` will throw `CommandException` if the caller's provided inline program throws an exception. But that's not the exception we want to throw to the caller - we want the actual inline exception to bubble to the caller, but since that is thrown on a different thread from the inline host inside the gRPC service we need to capture it separately so we can throw it here.

Comment (orionstudt) [reply sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs:290]: This is to support the scenario described in the test `InlineProgramExceptionPropagatesToCaller`

Comment (orionstudt) [reply sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs:290]: To clarify - this should not be a change in behavior for current consumers of inline programs because `InlineProgramExceptionPropagatesToCaller` was passing before this changeset. We just had to change the way we handle it internally because we were erroneously relying on the gRPC service always returning gracefully for inline programs

Comment (t0yv0) [reply sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs:290]: Ah thanks for those pointers! Aha it makes a little more sense now.

Another curious thing here is this. Before the change, inlineHost.TryGetExceptionInfo check ran only if this.RunCommandAsync did not throw. After the change, it runs only if this.RunCommandAsync throws. 

Are we sure this is what we want? Should we maybe always run it?

```
try {

   try {
      upResult = await this.runCommandAsync()
   } catch (Exception e) {
      upExc = e;
   }
} finally {
  if (inlineHost != null &amp;&amp; inlineHost.TryGetExceptionInfo(out var exceptionInfo))                    
     exceptionInfo.Throw();
   }
}

if upExc != null {
   throw upExc;
}
```

Comment (orionstudt) [reply sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs:290]: Technically every inline host exception should have caused `RunCommandAsync` to throw, but not every `RunCommandAsync` exception has an inline exception

Comment (orionstudt) [reply sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs:290]: [This line here](https://github.com/pulumi/pulumi/pull/7299/commits/4c4beb84064d5f4f0d22f3e786c5b97332915046#diff-16d113734488cfbc4117f2542e438ae49970eb3b9ffcce5864e5fa96a1043638R64) is checking the same `ExceptionDispatchInfo` instance that `TryGetExceptionInfo` returns when true. So if it was not null, than we bailed in gRPC and should have a `CommandException` and `TryGetExceptionInfo` should be true

**Comment by t0yv0** [comment]
Confirming macos test failure unrelated, fix coming to master separately.

**Review by t0yv0 — APPROVED** [review]
Let's ship it. Thanks again for the work!

**Comment by orionstudt** [comment]
Thanks @t0yv0!

**Comment by gitfool** [comment]
Thanks @orionstudt!
