### PR TITLE
Fix overlap when "this" keyword used in ts generation.

### LINKED ISSUE #18348: Don't use reserved keywords when generating programs
Depending on the language, we need to ensure that reserved identifiers (such as `this` in NodeJS, for instance) do not make it into programs generated by e.g. `pulumi convert`. In the best case, these programs won't compile; in the worst case, they'll run but produce broken results.

### PR DESCRIPTION
**Pull request by brandonpollack23**
As other keyword overlaps come up we can add them to this switch
statement.

This change also includes fixes to the go generation to make these tests pass. Previously we were chekcing the wrong identifiers against the roots in the pcl program.  Now we use the original names as intended and keywords work correctly now.

Fixes #18348

### CODE REVIEW

File: pkg/codegen/nodejs/gen_program.go [hunk 1]
```diff
@@ -1327,3 +1328,46 @@ func (g *generator) genNYI(w io.Writer, reason string, vs ...interface{}) {
...
+	newName := n.Name()
+	switch n.Name() {
+	case "this":
+		message := "Renaming reserved keyword this to thiz"
+		diags = append(diags, &hcl.Diagnostic{
+			Severity: hcl.DiagWarning,
+			Summary:  message,
+			Detail:   message,
+		})
+		newName = "thiz"
```
Comment (tgummerer) [inline pkg/codegen/nodejs/gen_program.go:1352]: What happens if a variable `thiz` already exists?  That might be more unlikely, but would we'd still override the local variable in that case, or not?

Comment (brandonpollack23) [reply pkg/codegen/nodejs/gen_program.go:1352]: I'm going to replace this implementation prototype since it is incomplete, i think I found another solution

**Comment by brandonpollack23** [comment]
Added both integration test to test the naming conversion in ts and also a conformance test to be sure it at least converts in all languages

File: pkg/codegen/nodejs/gen_program.go (hunk 1 above)
Comment (brandonpollack23) [reply pkg/codegen/nodejs/gen_program.go]: this actually is removed now, the underlying issue was renames were not done in all places they should have been

File: pkg/codegen/nodejs/gen_program.go [hunk 2]
```diff
@@ -567,34 +567,34 @@ func (g *generator) genComponentResourceDefinition(w io.Writer, componentName st
 				switch configVarType := configVar.Type().(type) {
 				case *model.ObjectType:
 					// generate {...}
-					g.Fgenf(w, "%s%s: ", configVar.Name(), optional)
+					g.Fgenf(w, "%s%s: ", makeValidIdentifier(configVar.Name()), optional)
```
Comment (lunaris) [inline pkg/codegen/nodejs/gen_program.go:570]: Worth just hoisting this out of the switch so that we only make the identifier once? Feels like this should also help prevent missing cases if we later add them? Also would save the duplicate applications later on in this function I think.

File: pkg/codegen/nodejs/gen_program.go [hunk 3]
```diff
@@ -699,7 +699,7 @@ func (g *generator) genComponentResourceDefinition(w io.Writer, componentName st
 			registeredOutputs := &model.ObjectConsExpression{}
 			for _, output := range outputs {
 				// assign the output fields
-				outputProperty := output.Name()
+				outputProperty := makeValidIdentifier(output.Name())
```
Comment (lunaris) [inline pkg/codegen/nodejs/gen_program.go:702]: TBH it looks like we could hoist the application to `output.Name()` too.

File: pkg/codegen/nodejs/gen_program.go [hunk 4]
```diff
@@ -1303,7 +1303,12 @@ func (g *generator) genConfigVariable(w io.Writer, v *pcl.ConfigVariable) {
 
 func (g *generator) genLocalVariable(w io.Writer, v *pcl.LocalVariable) {
 	g.genTrivia(w, v.Definition.Tokens.Name)
-	g.Fgenf(w, "%sconst %s = %.3v;\n", g.Indent, v.Name(), g.lowerExpression(v.Definition.Value, v.Type()))
+	g.Fgenf(
+		w,
+		"%sconst %s = %.3v;\n",
+		g.Indent,
+		makeValidIdentifier(v.Name()), g.lowerExpression(v.Definition.Value, v.Type()),
```
Comment (lunaris) [inline pkg/codegen/nodejs/gen_program.go:1310]: Feels like `g.lower` should be on its own line. Alternatively, make `vName := makeValidIdent(v.Name())` and have the gen stay on one line?

File: tests/examples/examples/dynamic-provider/class-with-comments/index.ts [hunk 5]
```diff
@@ -0,0 +1,32 @@
+// Copyright 2016-2018, Pulumi Corporation.  All rights reserved.
```
Comment (lunaris) [inline tests/examples/examples/dynamic-provider/class-with-comments/index.ts:1]: I assume these files aren't supposed to be here?

File: tests/integration/integration_nodejs_test.go [hunk 6]
```diff
@@ -2222,6 +2222,30 @@ func TestPackageAddNode(t *testing.T) {
...
+	goldTSFile := filepath.Join(e.CWD, "index.golden.ts")
+	goldTSBytes, err := os.ReadFile(goldTSFile)
+	assert.NoError(t, err)
+
+	indexTSFile := filepath.Join(e.CWD, "tsdir", "index.ts")
+	indexTSBytes, err := os.ReadFile(indexTSFile)
+	assert.NoError(t, err)
+
+	assert.Equal(t, string(goldTSBytes), string(indexTSBytes))
+}
```
Comment (lunaris) [inline tests/integration/integration_nodejs_test.go:2247]: I'm not sure you need the integration tests if you have the conformance tests, personally.

File: cmd/pulumi-test-language/tests/testdata/l1-resource-keyword-overlap/main.pp [hunk 7]
```diff
@@ -0,0 +1,7 @@
+# Since the name is "this" it will fail in typescript and other languages with
+# this reservered keyword if it is not renamed.
+this = "somestring"
+
+output "output" {
+  value = this
+}
```
Comment (lunaris) [inline cmd/pulumi-test-language/tests/testdata/l1-resource-keyword-overlap/main.pp:7]: _LOVE_ the idea of conformance testing this. I think we should get bang for our buck and add a load of "suspected reserved words" to this test. So e.g.:

```hcl
class = "class"
export = "export"
import = "import"
object = { object = "object" }
module = "module"
self = "self"
this = "this"

output "this_output" {
  value = this
}

...

output "all" {
  value = {
    ...
    this = this
  }
}
```

We could (should) also an an `l2-` test that does the same for some test `resource`s e.g. `resource "class" "..." { ... }`

File: pkg/codegen/nodejs/gen_program.go (hunk 2 above)
Comment (brandonpollack23) [reply pkg/codegen/nodejs/gen_program.go:570]: agreed, I just did this for consistency and sprinkled the call like elsewhere but hoisting would be better

File: pkg/codegen/nodejs/gen_program.go (hunk 3 above)
Comment (brandonpollack23) [reply pkg/codegen/nodejs/gen_program.go:702]: Sorry i dont quite understand your meaning

File: pkg/codegen/nodejs/gen_program.go (hunk 4 above)
Comment (brandonpollack23) [reply pkg/codegen/nodejs/gen_program.go:1310]: Good idea, ill extract both to make it a bit easier still

File: cmd/pulumi-test-language/tests/testdata/testdata/internal-bad-schema/main.pp [hunk 8]
```diff
@@ -0,0 +1,3 @@
+resource "res" "bad:index:Resource" {
```
Comment (julienp) [inline cmd/pulumi-test-language/tests/testdata/testdata/internal-bad-schema/main.pp:1]: Looks like a copy of testdata got accidentally added inside testdata.

File: sdk/go/pulumi-language-go/testdata/projects/l2-resource-keyword-overlap/main.go [hunk 9]
```diff
@@ -0,0 +1,54 @@
...
+		if err != nil {
+			return err
+		}
+		_, err = simple.NewResource(ctx, "export", &simple.ResourceArgs{
+			Value: pulumi.Bool(true),
+		})
+		if err != nil {
+			return err
+		}
+		_, err = simple.NewResource(ctx, "mod", &simple.ResourceArgs{
```
Comment (julienp) [inline sdk/go/pulumi-language-go/testdata/projects/l2-resource-keyword-overlap/main.go:22]: Unfortunately this doesn't capture the renaming because we'r not using the resource.

Maybe we can add a stack output for each resource.value, to force Go to generate a variable name.

File: cmd/pulumi-test-language/tests/testdata/l2-resource-keyword-overlap/main.pp [hunk 10]
```diff
@@ -0,0 +1,56 @@
...
+  value = mod
+}
+
+resource "import" "simple:index:Resource" {
+  value = true
+}
+
+# TODO(pulumi/pulumi#18246): Pcl should support scoping based on resource type just like HCL does in TF so we can uncomment this.
+# output "import" {
+#   value = Resource["import"]
```
Comment (julienp) [inline cmd/pulumi-test-language/tests/testdata/l2-resource-keyword-overlap/main.pp:31]: I don't follow, why do we want to use this instead of `value = import` here?

I was somehow thinking that `mod` was a keyword in Go, but that's only the case in `go.mod`, not in `*.go` files it seems. Unless we have the `import` case working, we have nothing that ensures we "escape" invalid identifiers in Go.

Maybe we could add a test case that uses `if` as a name? That should hit all languages 🤔

File: tests/integration/integration_nodejs_test.go (hunk 6 above)
Comment (julienp) [reply tests/integration/integration_nodejs_test.go:2247]: Agreed, I would prefer to remove this integration test.

File: cmd/pulumi-test-language/tests/testdata/l2-resource-keyword-overlap/main.pp (hunk 10 above)
Comment (julienp) [reply cmd/pulumi-test-language/tests/testdata/l2-resource-keyword-overlap/main.pp:31]: Sorry to be nitpicking here, but could we add a case here using `if`, or another Go keyword that does not clash with HCL/PCL, so that we can validate the renaming code works in Go?

File: pkg/codegen/nodejs/gen_program.go (hunk 3 above)
Comment (julienp) [reply pkg/codegen/nodejs/gen_program.go:703]: I think @lunaris meant that `makeValidIdentifier` could take an output instead of a string, but that was probably said under the assumption that   `makeValidIdentifier` was a new function. It's not, it already exists with the string argument, so I wouldn't change it.

Comment (lunaris) [reply pkg/codegen/nodejs/gen_program.go:703]: I meant that I think that in several places we do `makeValidIdentifier(output.Name())` -- wondering if we could just hoist that definition out and reuse the variable rather than have all those applications everywhere. Just a nit though.

**Comment by brandonpollack23** [comment]
Removed integration test and added "if"

File: cmd/pulumi-test-language/tests/l1_resource_keyword_overlap.go [hunk 11]
```diff
@@ -0,0 +1,53 @@
...
+
+import (
+	"github.com/pulumi/pulumi/pkg/v3/display"
+	"github.com/pulumi/pulumi/pkg/v3/resource/deploy"
+	"github.com/pulumi/pulumi/sdk/v3/go/common/resource"
+	"github.com/stretchr/testify/require"
+)
+
+func init() {
+	LanguageTests["l1-resource-keyword-overlap"] = LanguageTest{
```
Comment (lunaris) [inline cmd/pulumi-test-language/tests/l1_resource_keyword_overlap.go:25]: Nit: probably want this to just be `l1-keyword-overlap` or something because there are no resources (L1 means no providers, which means no resources)

File: sdk/go/pulumi-language-go/language_test.go [hunk 12]
```diff
@@ -172,6 +172,7 @@ func runTestingHost(t *testing.T) (string, testingrpc.LanguageTestClient) {
 
 // Add test names here that are expected to fail and the reason why they are failing
 var expectedFailures = map[string]string{
+	"l1-resource-keyword-overlap":         "outputs are not cast correctly from pcl to their pulumi types",                                           //nolint:lll
```
Comment (lunaris) [inline sdk/go/pulumi-language-go/language_test.go:175]: Probably want a tracking issue for this if we don't want to fix as part of this PR

File: cmd/pulumi-test-language/tests/testdata/l1-resource-keyword-overlap/main.pp [hunk 13]
```diff
@@ -0,0 +1,41 @@
...
+class = "class_output_string"
+export = "export_output_string"
+import = "import_output_string"
+mod = "mod_output_string"
+object = { object = "object_output_string" }
+self = "self_output_string"
+this = "this_output_string"
+if = "if_output_string"
+
+output "output_class" {
```
Comment (lunaris) [inline cmd/pulumi-test-language/tests/testdata/l1-resource-keyword-overlap/main.pp:11]: What if we name these outputs without the `output_` prefix, as in the L2 test? Does that work?

File: pkg/codegen/go/gen_program.go [hunk 14]
```diff
@@ -1166,8 +1166,8 @@ func (g *generator) genResource(w io.Writer, r *pcl.Resource) {
 
 	modOrAlias := g.getModOrAlias(pkg, mod, originalMod)
 
-	instantiate := func(varName, resourceName string, w io.Writer) {
-		if g.scopeTraversalRoots.Has(varName) || strings.HasPrefix(varName, "__") {
+	instantiate := func(varName, blockName, resourceName string, w io.Writer) {
+		if g.scopeTraversalRoots.Has(blockName) || strings.HasPrefix(varName, "__") {
```
Comment (lunaris) [inline pkg/codegen/go/gen_program.go:1170]: Maybe a comment worthwhile here -- when is the block name not the resource name/what does this let us achieve to avoid name clashes?

File: cmd/pulumi-test-language/tests/l2_resource_keyword_overlap.go [hunk 15]
```diff
@@ -0,0 +1,70 @@
...
+
+					provider := snap.Resources[1]
+					assert.Equal(l, "pulumi:providers:simple", provider.Type.String(), "expected simple provider")
+
+					resourceNames := []string{}
+					for _, res := range snap.Resources {
+						resourceNames = append(resourceNames, res.URN.Name())
+					}
+
+					assert.Equal(l, "simple:index:Resource", snap.Resources[2].Type.String())
```
Comment (lunaris) [inline cmd/pulumi-test-language/tests/l2_resource_keyword_overlap.go:46]: There's a helper, `RequireSingleNamedResource`, that might help here; it'd let you avoid the loop above and just do:

```go
classRes := RequireSingleNamedResource(l, snap.Resources, "class")
assert.Equal(l, "simple:index:Resource", classRes.Type.String())
```

etc. Also a bit more robust in the event that something triggers a reordering of resources or the like.

File: cmd/pulumi-test-language/tests/testdata/l1-resource-keyword-overlap/main.pp [hunk 16]
```diff
@@ -0,0 +1,41 @@
...
+  value = class
+}
+
+output "output_export" {
+  value = export
+}
+
+output "output_import" {
+  value = import
```
Comment (lunaris) [inline cmd/pulumi-test-language/tests/testdata/l1-resource-keyword-overlap/main.pp:20]: Interesting that we allow this but not the resource later on </pointless-note>

**Review by lunaris — APPROVED** [review]
