### PR TITLE
Indent stack outputs by 1.

### LINKED ISSUE #1821: An assertion has failed: Expected indention for a prefixed line
```
workspace/pulumi/hackathon2                                                                                                                                                                                  
▶ pulumi update -p 20
Previewing update of stack 'mastodon-dev'
Previewing changes:

     Type                 Name                   Plan          Info
 *   pulumi:pulumi:Stack  mastodon-mastodon-dev  no change

info: no changes required:
      55 resources unchanged

Do you want to perform this update? yes
Updating stack 'mastodon-dev'
Performing changes:

     Type                 Name                   Status     Info
 *   pulumi:pulumi:Stack  mastodon-mastodon-dev  done
panic: fatal: An assertion has failed: Expected indention for a prefixed line

goroutine 544 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(0xc42136c040, 0x3f)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xe9
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc4202f4200, 0x1a9b517, 0x26, 0x0, 0x0, 0x0)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x126
github.com/pulumi/pulumi/pkg/engine.getIndentationString(0x0, 0x1a799a3, 0x6, 0x1, 0x3, 0xc4219217e8)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/engine/diff.go:72 +0x198
github.com/pulumi/pulumi/pkg/engine.writeWithIndent(0xc4202f42a0, 0x0, 0x1a799a3, 0x6, 0x1, 0xc4219217e8, 0x7, 0xc421921820, 0x1, 0x1)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/engine/diff.go:94 +0x86
github.com/pulumi/pulumi/pkg/engine.printPropertyTitle(0xc4202f42a0, 0xc421457510, 0xa, 0xa, 0x0, 0x1a799a3, 0x6, 0x1)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/engine/diff.go:319 +0x179
github.com/pulumi/pulumi/pkg/engine.printObjectPropertyDiff.func1(0x1a799a3, 0x6, 0x1)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/engine/diff.go:451 +0x6b
github.com/pulumi/pulumi/pkg/engine.printAdd(0xc4202f42a0, 0x1a09400, 0xc42100e8a0, 0xc421921968, 0xc4209e3100, 0x0, 0x0)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/engine/diff.go:583 +0x44
github.com/pulumi/pulumi/pkg/engine.printObjectPropertyDiff(0xc4202f42a0, 0xc421457510, 0xa, 0xa, 0xc421377e60, 0xc421377e90, 0xc421377ec0, 0xc421377ef0, 0x0, 0x0, ...)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/engine/diff.go:454 +0x132
github.com/pulumi/pulumi/pkg/engine.GetResourceOutputsPropertiesString(0x1a77ea3, 0x4, 0xc42137d180, 0x4d, 0xc42124fac0, 0x13, 0xc42178cee0, 0xc42178d030, 0xc42178d1f0, 0x0, ...)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/engine/diff.go:275 +0x2bd
github.com/pulumi/pulumi/pkg/backend/local.(*ProgressDisplay).processEndSteps(0xc42181df00)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/backend/local/progress.go:709 +0x962
github.com/pulumi/pulumi/pkg/backend/local.(*ProgressDisplay).processEvents(0xc42181df00, 0xc4209da780, 0xc4212994a0)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/backend/local/progress.go:961 +0x173
github.com/pulumi/pulumi/pkg/backend/local.DisplayProgressEvents.func1(0xc42181df00, 0xc4209da780, 0xc4212994a0, 0xc421299500)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/backend/local/progress.go:264 +0x3f
created by github.com/pulumi/pulumi/pkg/backend/local.DisplayProgressEvents
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/backend/local/progress.go:263 +0x3ee
```

### PR DESCRIPTION
**Pull request by pgavlin**
Also:
- Show stack output diffs during preview
- Fix a bug where deletes in stack outputs were not displayed

Fixes #1821.

### CODE REVIEW

File: pkg/engine/diff.go [hunk 1]
```diff
@@ -69,7 +69,6 @@ func getIndentationString(indent int, op deploy.StepOp, prefix bool) string {
 	}
 
 	if result == "" {
-		contract.Assertf(!prefix, "Expected indention for a prefixed line")
 		return result
 	}
```
Comment (CyrusNajmabadi) [inline pkg/engine/diff.go]: i looked at this method, and while this assert seems like it can eb removed, things still feel a bit weird.  The caller is specifically asking for a prefix to be printed.  However, because they are at indent 0 they won't see any prefix at all.

It seems like a potentially better fix would be to update hte code that prints out outputs at the end to ask for things at indent '1' so taht at least the prefix can be supplied.

**Comment by CyrusNajmabadi** [comment]
>  I'm not too worried about omitting prefixes if we requested an indent of 0. (What does that even mean?)

I read through it, and i think i have a good sense of what it's trying to do.

When we emit text, we can emit it at some 'indent' level.  This indent level ends up being a multiple of 4 columns. 

We also support the idea of having hte line be 'prefixed' with the Op symbol (i.e. `+` or `-` or `+-`).  Importantly, this has no effect on indentation.  So the way the code works is by indenting first, then knowing that the Op symbol can overwrite any of the first indentation spaces. 

So, having someone say: i don't want any indent... but i also want the op-prefix ends up being something unsupported since there's no actual place to put that op symbol.

--

Now, the reason i preferred my suggestion was that what we are printing are the stack outputs (including showing how they changed).  In that case, having the op-symbol is useful and consistent with the rest of our presentation.  So, in order to support that, we should just indent in all the outputs by at least '1' so that we can print that out.  It feels like the right fix.  Though i'm totally with anyone who thinks all this code is confusing and error prone and could use some significant love to improve it and to help avoid these traps.

**Comment by pgavlin** [comment]
I'm with @CyrusNajmabadi on this, I think. I'll go ahead and make the necessary changes.

**Comment by pgavlin** [comment]
@CyrusNajmabadi PTAL

**Comment by pgavlin** [comment]
Here's the experience we get:
<a href="https://asciinema.org/a/TtwTBuLbsEE9jl3JhGpbrF4gQ" target="_blank"></a>
