### PR TITLE
[go/program-gen] Fixes int constant range expressions for go

### LINKED ISSUE #10853: `count` in TF is incorrectly translated into `range` in Go
In https://www.pulumi.com/registry/packages/aws/api-docs/rds/clusterinstance/ we have example code that's invalid, specifically:

```go
for key0, val0 := range 2 {
```

I believe it should be:

```go
for x := 0; x < 2;x++ {
```

[The upstream source example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance#example-usage) uses `count`, so I believe this is the source of the issue.

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

Fixes #10853

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/codegen/pcl/binder_test.go [hunk 1]
```diff
@@ -62,8 +63,22 @@ func TestBindProgram(t *testing.T) {
 					t.Fatalf("failed to parse files: %v", parser.Diagnostics)
 				}
 
-				_, diags, err := BindProgram(parser.Files, PluginHost(utils.NewHost(testdataPath, fileToMockPlugins[fileName])))
-				assert.NoError(t, err)
+				var bindError error
+				var diags hcl.Diagnostics
+				if fileName == "simple-range.pp" {
+					// simple-range.pp requires AllowMissingVariables
```
Comment (Frassle) [inline pkg/codegen/pcl/binder_test.go:69]: Why? I don't see a missing var?

Comment (Zaid-Ajaj) [reply pkg/codegen/pcl/binder_test.go:69]: It fails when the `range` expression is constant and we then use it in `range.value`. This is the error:
> === FAIL: codegen/pcl TestBindProgram/simple-range.pp (0.85s)
    binder_test.go:68: failed to bind program: simple-range.pp:5,28-33: undefined variable range; 
    --- FAIL: TestBindProgram/simple-range.pp (0.85s)

I need to look into this at some point because this is what tf2pulumi generates from terraform example:
Given
```terraform
resource "aws_rds_cluster" "default" {
  cluster_identifier = "aurora-cluster-demo"
  availability_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]
  database_name      = "mydb"
  master_username    = "foo"
  master_password    = "barbut8chars"
}

resource "aws_rds_cluster_instance" "cluster_instances" {
  count              = 2
  identifier         = "aurora-cluster-demo-${count.index}"
  cluster_identifier = aws_rds_cluster.default.id
  instance_class     = "db.r4.large"
  engine             = aws_rds_cluster.default.engine
  engine_version     = aws_rds_cluster.default.engine_version
}
```
tf2pulumi generates PCL
```
resource default "aws:rds/cluster:Cluster" {
  clusterIdentifier = "aurora-cluster-demo"
  availabilityZones = ["us-west-2a", "us-west-2b", "us-west-2c"]
  databaseName      = "mydb"
  masterUsername    = "foo"
  masterPassword    = "barbut8chars"
}
resource clusterInstances "aws:rds/clusterInstance:ClusterInstance" {
options {
  range              = 2

}
  identifier         = "aurora-cluster-demo-${range.value}"
  clusterIdentifier = default.id
  instanceClass     = "db.r4.large"
  engine             = default.engine
  engineVersion     = default.engineVersion
}
```

Comment (Frassle) [reply pkg/codegen/pcl/binder_test.go:69]: That looks like the binder doesn't understand options.range correctly, can you open an issue for that and put a "TODO issue/XXX" on this bit of binder_test.go

Comment (Zaid-Ajaj) [reply pkg/codegen/pcl/binder_test.go:70]: Made an issue and added a TODO comment ✅

**Review by Frassle — APPROVED** [review]

**Comment by Zaid-Ajaj** [comment]
bors merge
