### PR TITLE
Don't fail on configuration keys like `a:config:b:c`

### LINKED ISSUE #2171: "pulumi config set" allow invalid config key
I played a little with pulumi config and found, that there's some backward compatible logic when fetching config values(removing of the ":config" part from the key).  
I was able to set an invalid key, without any error, which caused an error during get.  

```
  ➜ ✗ pulumi config set a:b:c 3                                
error: invalid configuration key: a:b:c is not in config module
  ➜ ✗ pulumi config set a:config:b:c 3                         
  ➜ ✗ pulumi config                                            
error: could not unmarshal map: a:b:c is not in config module
```

Pulumi version: v0.16.2.

### PR DESCRIPTION
**Pull request by ellismg**
Configuration keys are simple namespace/name pairs, delimited by
":". For compatability, we also allow
"<namespace>:config:<name>", but we always record the "nice" name in
`Pulumi.<stack-name>.yaml`.

While `pulumi config` and friends would block setting a key like
`a:b:c` (where the "name" has a colon in it), it would allow
`a:config:b:c`. However, this would be recorded as `a:b:c` in
`Pulumi.<stack-name>.yaml`, which meant we'd error when parsing the
configuration file later.

To work around this, disallow ":" in the "name" part of a
configuration key.  With this change the following all work:

```
keyName
my-project:keyName
my-project:config:keyName
```

However, both

`my-project:keyName:subKey`
`my-project:config:keyName:subKey`

are now disallowed.

I considered allowing colons in subkeys, but I think it adds more
confusion (due to the interaction with how we allow you elide the
project name in the default case) than is worthwhile at this point.

Fixes #2171

### CODE REVIEW

File: pkg/resource/config/key.go [hunk 1]
```diff
@@ -36,28 +36,31 @@ func MustMakeKey(namespace string, name string) Key {
...
+			if mm.Module().Name() == tokens.ModuleName("config") {
+				return Key{
+					namespace: mm.Module().Package().String(),
+					name:      mm.Name().String(),
+				}, nil
+			}
+		}
 	}
 
 	return Key{}, errors.Errorf("could not parse %s as a configuration key", s)
```
Comment (pgavlin) [inline pkg/resource/config/key.go]: Should we return a richer error here that includes the key format?

Comment (ellismg) [reply pkg/resource/config/key.go]: Good idea.  Added a note to the error about the format.
