### PR TITLE
pulumi state unprotect command now uses OS specific quoting

### LINKED ISSUE #13045: Command hints in errors suggest using strings with single quotes in Windows
### What happened?

I.e. the following message proposes running a command that would be wrong in Windows, because strings must use double quotes in this OS:

```
error: Preview failed: resource "urn:pulumi:dev::ium::aws:s3/bucketV2:BucketV2::site-logs" cannot be deleted
    because it is protected. To unprotect the resource, either remove the `protect` flag from the resource in your Pulumi program and run `pulumi up`, or use the command:
    `pulumi state unprotect 'urn:pulumi:dev::ium::aws:s3/bucketV2:BucketV2::site-logs'`
```

### Expected Behavior

The message would look like this in Windows:

```
error: Preview failed: resource "urn:pulumi:dev::ium::aws:s3/bucketV2:BucketV2::site-logs" cannot be deleted
    because it is protected. To unprotect the resource, either remove the `protect` flag from the resource in your Pulumi program and run `pulumi up`, or use the command:
    pulumi state unprotect "urn:pulumi:dev::ium::aws:s3/bucketV2:BucketV2::site-logs"
```

### Steps to reproduce

Not needed.

### Output of `pulumi about`

Not needed.

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description
Error messages would suggest the command `pulumi state unprotect 'urn'` on Windows which was not a valid quoting and now windows displays: `pulumi state unprotect "urn"`.

Fixes #13045 

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/resource/deploy/step.go [hunk 1]
```diff
@@ -385,11 +386,20 @@ type deleteProtectedError struct {
...
+
+func (d deleteProtectedError) err(os string) string {
+	msg := fmt.Sprintf("resource %[1]q cannot be deleted\n"+
 		"because it is protected. To unprotect the resource, "+
 		"either remove the `protect` flag from the resource in your Pulumi "+
 		"program and run `pulumi up`, or use the command:\n"+
 		"`pulumi state unprotect '%[1]s'`", d.urn)
+	if os == "windows" {
+		// Windows uses double-quotes instead of single-quotes.
+		msg = strings.ReplaceAll(msg, `'`, `"`)
```
Comment (dixler) [inline pkg/resource/deploy/step.go:400]: If urns can include `single-quotes`, [surprised-pikachu.jpg](https://example.com)

**Review by abhinav — APPROVED** [review]
We could also just use double quotes here unconditionally. URNs don't contain `$`, so there's no risk of `"someurn"` being interpreted as a Bash variable.
I prefer the suggested solution, but I don't feel strongly about it.
I'll make it your call.

File: pkg/resource/deploy/step.go [hunk 2]
```diff
@@ -385,11 +386,20 @@ type deleteProtectedError struct {
...
-	return fmt.Sprintf("resource %[1]q cannot be deleted\n"+
+	return d.err(runtime.GOOS)
+}
+
+func (d deleteProtectedError) err(os string) string {
+	msg := fmt.Sprintf("resource %[1]q cannot be deleted\n"+
 		"because it is protected. To unprotect the resource, "+
 		"either remove the `protect` flag from the resource in your Pulumi "+
 		"program and run `pulumi up`, or use the command:\n"+
 		"`pulumi state unprotect '%[1]s'`", d.urn)
```
Comment (Frassle) [inline pkg/resource/deploy/step.go:397]: There's also a load of quotes like this in the config commands that we show in help, one in preview that we show for --plan. We should probably build this solution such that it can apply to those texts as well. Maybe a global var for the shell quote char, or a `Quote(string) string` method.

File: pkg/resource/deploy/step.go (hunk 1 above)
Comment (Frassle) [reply pkg/resource/deploy/step.go:400]: They're not supposed to, but I wouldn't be surprised if the the system allowed it.

**Comment by abhinav** [comment]
> URNs don't contain $, so there's no risk of "someurn" being interpreted as a Bash variable.

I stand corrected. If there is a parent resource, URNs do contain `$`s. (Thanks, @dixler.)

**Comment by dixler** [comment]
> We could also just use double quotes here unconditionally. URNs don't contain `$`, so there's no risk of `"someurn"` being interpreted as a Bash variable. I prefer the suggested solution, but I don't feel strongly about it. I'll make it your call.

fun fact URNs can include $ if it's using parenting
https://github.com/pulumi/pulumi-java/blob/fb164a6c7a26b439f89dc12e0c87abf852bd41d2/sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java#L62

https://github.com/pulumi/pulumi-java/pull/1056/files#diff-af267e3d5d88fd81e797a29b3321e17f3850ca97ae85f988b6227b76550c8b73

File: changelog/pending/20230621--cli-display--on-windows-make-pulumi-state-unprotect-command-suggestion-use-double-quotes-instead-of-single-quotes.yaml [hunk 3]
```diff
@@ -0,0 +1,4 @@
+changes:
+- type: fix
+  scope: cli/display
+  description: On windows, make `pulumi state unprotect` command suggestion use double-quotes instead of single-quotes.
```
Comment (abhinav) [inline changelog/pending/20230621--cli-display--on-windows-make-pulumi-state-unprotect-command-suggestion-use-double-quotes-instead-of-single-quotes.yaml:4]: Windows
```suggestion
  description: On Windows, make `pulumi state unprotect` command suggestion use double-quotes instead of single-quotes.
```

File: sdk/go/common/resource/urn.go [hunk 4]
```diff
@@ -68,6 +69,15 @@ func NewURN(stack tokens.QName, proj tokens.PackageName, parentType, baseType to
 	)
 }
 
+func (urn URN) Quote() string {
```
Comment (abhinav) [inline sdk/go/common/resource/urn.go:72]: Let's add a docstring to this:

```go
// Quote returns the quoted form of the URN
// appropriate for use in the command line for the current OS.
```

**Review by abhinav — APPROVED** [review]

**Comment by dixler** [comment]
bors merge
