### PR TITLE
`pulumi new` with existing project now can be bypassed

### LINKED ISSUE #13832: Do not block project creation if the project's name already exists, ask for confirmation instead
### What happened?

Previously, it was possible to create a Pulumi project, even if a project with the same name exists in the user's org or personal account. However, it appears this is no longer possible (not sure since when).

At least for me this is a problem because I sometimes group my stacks under the same project name.
For example, I have stacks like:
* zendesk/case123
* zendesk/case432
* and so on

It's also a breaking change from previous CLI versions imho.

Furthermore, the imposed restriction can be circumvented easily by editing `Pulumi.yaml` and creating a new stack. However, this unnecessarily degrades the user experience by adding extra manual steps.

### Expected Behavior

The CLI should warn a project with the same already exists and prompt the user to confirm or change their input.

### Steps to reproduce

* run `pulumi new aws-typescript --name zendesk --stack 1234`
* run `pulumi new aws-typescript --name zendesk --stack abc`

The 2nd command will return the error.
```
error: a project with this name already exists: zendesk
```

### Output of `pulumi about`

```
CLI          
Version      3.79.0
Go Version   go1.21.0
Go Compiler  gc

Host     
OS       debian
Version  12.1
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, menfin-team, demo, pulumi
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description

Fixes #13832

[asciinema recording](https://asciinema.org/a/zZvO66E31sMZ0t2DCAbnuMUMW)

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/cmd/pulumi/new_test.go [hunk 1]
```diff
@@ -1022,3 +1024,77 @@ func TestGenerateOnlyProjectCheck(t *testing.T) {
...
+		ctx context.Context, ref backend.StackReference,
+		stackName string, opts *backend.CreateStackOptions,
+	) (backend.Stack, error) {
+		return nil, &backend.StackAlreadyExistsError{StackName: stackName}
+	}
+	b.GetStackF = func(ctx context.Context, stackRef backend.StackReference) (backend.Stack, error) {
+		return s, nil
+	}
+
+	_, err := promptAndCreateStackInternal(context.Background(), b, func(
```
Comment (Frassle) [inline pkg/cmd/pulumi/new_test.go:1087]: The formatting here is pretty terrible to read, can this not be inline, probably be easier.

File: pkg/cmd/pulumi/new.go [hunk 2]
```diff
@@ -572,6 +576,49 @@ func errorIfNotEmptyDirectory(path string) error {
 
 func validateProjectName(ctx context.Context, b backend.Backend,
 	orgName string, projectName string, generateOnly bool, opts display.Options,
+) error {
+	handleExistingProjectName := func(projectName string) error {
+		surveycore.DisableColor = true
+		surveyIcons := survey.WithIcons(func(icons *survey.IconSet) {
```
Comment (Frassle) [inline pkg/cmd/pulumi/new.go:582]: Feels like we've probably got a few places making up an 'edit'/'continue' survey loop now? Worth finding them all and making a helper in cmdutils?

**Review by blampe — COMMENTED** [review]
What's the behavior if the user selects "continue" - do we just create a new stack inside the existing project?

**Comment by dixler** [comment]
> What's the behavior if the user selects "continue" - do we just create a new stack inside the existing project?

Yes and if they try creating a stack name that already exists, we emit a warning and allow them to confirm that they want to use it.

The update that is run will be on the existing stack.

File: pkg/cmd/pulumi/new.go [hunk 3]
```diff
@@ -658,6 +711,29 @@ func promptAndCreateStack(ctx context.Context, b backend.Backend, prompt promptF
...
+			}
+			stackRef, err := b.ParseStackReference(stackName)
+			if err != nil {
+				return nil, err
+			}
+			s, err = b.GetStack(ctx, stackRef)
+			if err != nil {
+				return nil, err
+			}
+			if err = state.SetCurrentStack(stackRef.String()); err != nil {
```
Comment (Frassle) [inline pkg/cmd/pulumi/new.go:732]: Shouldn't this still respect `setCurrent`?

File: pkg/cmd/pulumi/new.go [hunk 4]
```diff
@@ -658,6 +711,29 @@ func promptAndCreateStack(ctx context.Context, b backend.Backend, prompt promptF
...
+		var e *backend.StackAlreadyExistsError
+		if errors.As(err, &e) {
+			accept, err := acceptStackAlreadyExists(stackName, opts)
+			if err != nil {
+				return nil, err
+			}
+			if !accept {
+				continue
+			}
+			stackRef, err := b.ParseStackReference(stackName)
```
Comment (Frassle) [inline pkg/cmd/pulumi/new.go:724]: Should we print a warning or something here that we're ignoring the given `secretsProvider` option given to new because the stack already exists?

File: pkg/cmd/pulumi/util.go [hunk 5]
```diff
@@ -1115,3 +1115,22 @@ func missingNonInteractiveArg(args ...string) error {
 			strings.Join(args[:len(args)-1], ", "), args[len(args)-1])
 	}
 }
+
+func promptUser(msg string, options []string, defaultOption string, opts display.Options) string {
```
Comment (Frassle) [inline pkg/cmd/pulumi/util.go:1119]: The only thing this uses from display.Options is `Color`, feels like this should just take the Color option not the whole display opts.

Comment (Frassle) [reply pkg/cmd/pulumi/util.go:1119]: That also makes the edits to state_edit smaller.

File: pkg/cmd/pulumi/new_test.go [hunk 6]
```diff
@@ -1019,3 +1021,78 @@ func TestGenerateOnlyProjectCheck(t *testing.T) {
...
+	}
+
+	_, err := promptAndCreateStackInternal(context.Background(), b, prompt, "", "root", true, true, display.Options{
+		Color:         cmdutil.GetGlobalColorization(),
+		IsInteractive: true,
+	}, "", func(stackName string, opts display.Options) (bool, error) {
+		return true, nil
+	})
+
+	assert.NoError(t, err)
```
Comment (Frassle) [inline pkg/cmd/pulumi/new_test.go:1097]: Don't feel like this test is testing enough, should we not check that GetStack is called for the correct stack ref?

File: pkg/cmd/pulumi/new.go [hunk 7]
```diff
@@ -572,6 +582,30 @@ func errorIfNotEmptyDirectory(path string) error {
...
 	orgName string, projectName string, generateOnly bool, opts display.Options,
+) error {
+	handleExistingProjectName := func(projectName string) error {
+		prompt := "\b\n" + opts.Color.Colorize(colors.SpecWarning+"warning: "+colors.Reset) +
+			fmt.Sprintf("A project with the name `%s` already exists.\n", projectName) +
+			opts.Color.Colorize(colors.SpecPrompt+"Do you want to continue?"+colors.Reset)
+		response := promptUser(prompt, []string{_cont, _edit}, _cont, opts)
+
+		if response != _cont {
+			return fmt.Errorf("already in use")
```
Comment (Frassle) [inline pkg/cmd/pulumi/new.go:593]: Should this not be the same error as non-interactive? "a project with this name already exists"

**Comment by justinvp** [comment]
About:

```
warning: A project with the name `mytestproj` already exists.
Do you want to continue?  [Use arrows to move, type to filter]
> continue
  edit
```

I'm not really sure what it means to continue here. Wondering if something like the following would be more clear:

```
A project with the name `mytestproj` already exists.
Use 'mytestproj' anyway?  [Use arrows to move, type to filter]
> yes
  no
```

Even with this, it's still not entirely clear what the implications of proceeding with the existing name. Any ideas on how we could further clarify?

**Comment by justinvp** [comment]
I'm trying this out locally. If I run the following:

If I run the following:

```
$ mkdir mytestproj && cd mytestproj
$ pulumi new yaml
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name (mytestproj):
project description (A minimal Pulumi YAML program):
Created project 'mytestproj'

Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
stack name (dev):
Created stack 'dev'

Your new project is ready to go! ✨

To perform an initial deployment, run `pulumi up`
```

And then delete the one generated file and run it again, it prompts me for a project, but it doesn't specify a default value to use for the project name. It's just empty forcing me to enter something:

```
$ rm Pulumi.yaml
$ pulumi new yaml
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name:
```

If I hit enter, it rejects it and prompts again:

```
project name:
Sorry, '' is not a valid project name. project names may not be empty
project name:
```

I wonder if we should default it to what we'd originally use (the dir name), and go through the same "Use it anyway?" prompt, instead of asking for it without a default?

**Comment by dixler** [comment]
> I'm not really sure what it means to continue here. Wondering if something like the following would be more clear:
> 
> ```
> A project with the name `mytestproj` already exists.
> Use 'mytestproj' anyway?  [Use arrows to move, type to filter]
> > yes
>   no
> ```
> 
> Even with this, it's still not entirely clear what the implications of proceeding with the existing name. Any ideas on how we could further clarify?

I think your prompt makes sense. I'm not sure that there are *that* many consequences of using an existing project other than conflating 2+ source directories with the same project. The consequences seem to be more related to using an existing stack. Maybe we could just NOT allow `pulumi new` to use an existing stack name since it could go poorly very easily and to do this you would have to do `pulumi stack select` in a separate command.

> I'm trying this out locally. If I run the following:
> ...
> ...
> Enter a value or leave blank to accept the (default), and press <ENTER>.
> Press ^C at any time to quit.
> 
> project name:
> 
> If I hit enter, it rejects it and prompts again:
> 
> ```
> project name:
> Sorry, '' is not a valid project name. project names may not be empty
> project name:
> ```
> 
> I wonder if we should default it to what we'd originally use (the dir name), and go through the same "Use it anyway?" prompt, instead of asking for it without a default?

This behavior happens because an error occurs when validating the default project name and is silently ignored by not suggesting the provided project name. I'll change it so it suggests the default anyway.

File: pkg/cmd/pulumi/new.go (hunk 3 above)
Comment (dixler) [reply pkg/cmd/pulumi/new.go:732]: Can you elaborate?

File: pkg/cmd/pulumi/new_test.go (hunk 6 above)
Comment (dixler) [reply pkg/cmd/pulumi/new_test.go:1098]: Added

```go
assert.Equal(t, "stack", stackRef.FullyQualifiedName().String())
```

**Review by justinvp — COMMENTED** [review]
The interaction can still use some streamlining... Running `pulumi new yaml` in a directory named `mytest` with already existing project and stack names:

```
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name (mytest):
```

I hit enter:

```
warning: A project with the name `mytest` already exists.
Use 'mytest' anyway?  [Use arrows to move, type to filter]
> yes
  no
```

Select no:

```
Use 'mytest' anyway? no
Sorry, 'mytest' is not a valid project name. a project with this name already exists: mytest
project name (mytest):
```

Two things:

1. When selecting "no", why does it print out the "Sorry" message? It should go back to a prompt without that message.

2. Now that I'm trying it out, it seems like we could further improve the prompt. Rather than warning and then having a yes/no choice, I wonder if this could be combined into the prompt, something like:

```
A project with the name `mytest` already exists. Please choose:  [Use arrows to move, type to filter]
> Use 'mytest' anyway
  Specify a different project name
```

What do you think?

---

When hitting enter to use the default suggested value for the stack name (dev), which already exists, it gives the old "Do you want to continue?" prompt.


```
Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
stack name (dev):

warning: A stack with the name `dev` already exists.
Do you want to continue?  [Use arrows to move, type to filter]
> yes
  no
```

This prompt should match whatever we're doing for the project prompt, e.g.:

```
A stack with the name `dev` already exists. Please choose:  [Use arrows to move, type to filter]
> Use 'dev' anyway
  Specify a different stack name
```

File: pkg/cmd/pulumi/new.go (hunk 4 above)
Comment (dixler) [reply pkg/cmd/pulumi/new.go]: Not allowing `pulumi new` to use an existing stack anymore.

File: pkg/cmd/pulumi/new.go (hunk 3 above)
Comment (dixler) [reply pkg/cmd/pulumi/new.go]: Not allowing `pulumi new` to use an existing stack anymore.

File: pkg/cmd/pulumi/new.go [hunk 8]
```diff
@@ -572,6 +573,33 @@ func errorIfNotEmptyDirectory(path string) error {
 
 func validateProjectName(ctx context.Context, b backend.Backend,
 	orgName string, projectName string, generateOnly bool, opts display.Options,
+) error {
+	handleExistingProjectName := func(projectName string) error {
+		prompt := "\b\n" + opts.Color.Colorize(colors.SpecPrompt+
+			fmt.Sprintf("A project with the name `%s` already exists.\n", projectName)+
```
Comment (justinvp) [inline pkg/cmd/pulumi/new.go:579]: Elsewhere we don't have the newline before the prompt

```suggestion
			fmt.Sprintf("A project with the name `%s` already exists.", projectName)+
```

**Review by justinvp — APPROVED** [review]
LGTM otherwise

**Comment by dixler** [comment]
rebased.
