### PR TITLE
Fix plugin "exited prematurely" false positives

### LINKED ISSUE #18238: False positives: `Detected that <bin> exited prematurely`
### What happened?

Could it be possible that the code detecting provider failure sometimes blames a provider that did not fail, specifically:

https://github.com/pulumi/pulumi/blob/efb38baee4dbdd41748df877dfa2daf0dfc11846/sdk/go/common/resource/plugin/plugin.go#L587 

### Example

I'm observing the following operations in Metabase:

1. operation succeeded but it has Detected that <bin> exited prematurely messages
2. operation has 10-20 different Detected that <bin> exited prematurely messages, but unlikely that all providers failed simultaneously?

It appears that these logs do not contain any stdout/stderr in Metabase to truly understand what is going on.

Perhaps https://github.com/pulumi/pulumi/blob/efb38baee4dbdd41748df877dfa2daf0dfc11846/sdk/go/common/resource/plugin/plugin.go#L559 does not account fully for crash conditions?

I tried reproducing Ctrl+C and having 2 providers where one has a panic injected but failed to repro these strange scenarios. 

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
When closing a plugin, the plugin's connection state is used to determine whether the plugin had crashed, where a connection state other than `Ready` is presumed crashed. This can lead to false positives, as it's possible for the connection state to change from `Ready` to `Idle` after an idle timeout (e.g. 5 minutes) for plugins that have not crashed.

This leads to incorrect messages reported to users, such as:

```
   Detected that /Users/user/.pulumi/plugins/resource-random-v4.18.0/pulumi-resource-random exited prematurely.
             This is *always* a bug in the provider. Please report the issue to the provider author as appropriate.
```

This change avoids the false positives by making a request to a health check service on the plugin as a way of determining if the plugin is still alive. Most plugins don't and won't implement this service, but that's OK because we treat an unimplemented status as OK. If we get any other error (unavailable, deadline_exceeded, etc.) the plugin is presumed crashed.

Fixes #18238

### CODE REVIEW

File: sdk/go/common/resource/plugin/plugin_test.go [hunk 1]
```diff
@@ -89,3 +97,92 @@ func TestParsePort(t *testing.T) {
...
+			if tt.shutdownServer {
+				server.Stop()
+				// Give time for cleanup
+				time.Sleep(100 * time.Millisecond)
+			}
+
+			result := p.healthCheck()
+			assert.Equal(t, tt.expected, result)
+
+			if p.Conn != nil {
```
Comment (Frassle) [inline sdk/go/common/resource/plugin/plugin_test.go:182]: Isn't this always non-nil

File: sdk/go/common/resource/plugin/plugin_test.go [hunk 2]
```diff
@@ -89,3 +97,92 @@ func TestParsePort(t *testing.T) {
...
+		listener, _ := net.Listen("tcp", "127.0.0.1:0")
+		server := grpc.NewServer()
+
+		if healthService {
+			healthServer := health.NewServer()
+			grpc_health_v1.RegisterHealthServer(server, healthServer)
+		}
+
+		go func() {
+			err := server.Serve(listener)
```
Comment (Frassle) [inline sdk/go/common/resource/plugin/plugin_test.go:114]: Shouldn't we waitgroup that this serve has ran before returning from startServer otherwise the healthcheck might fail just because we haven't started up yet?

File: sdk/go/common/resource/plugin/plugin.go [hunk 3]
```diff
@@ -554,14 +555,33 @@ func buildPluginArguments(opts pluginArgumentOptions) []string {
...
+func (p *plugin) healthCheck() bool {
+	if p.Conn == nil {
+		return false
+	}
+
+	// Check that the plugin looks alive by calling gRPC's Health Check service.
+	// Most plugins don't actually implement this service, which is OK as we treat
+	// an unimplemented status as OK.
+	health := grpc_health_v1.NewHealthClient(p.Conn)
+	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
```
Comment (iwahbe) [inline sdk/go/common/resource/plugin/plugin.go:567]: Does this mean that a crashed plugin will wait 3 seconds for a response?

File: sdk/go/common/resource/plugin/plugin.go [hunk 4]
```diff
@@ -554,14 +555,33 @@ func buildPluginArguments(opts pluginArgumentOptions) []string {
...
 func (p *plugin) Close() error {
-	pluginCrashed := true
+	// Something has gone wrong with the plugin if it is not healthy and we have not yet
+	// shut it down.
+	pluginCrashed := !p.healthCheck()
 
 	if p.Conn != nil {
-		// Something has gone wrong with the plugin if it is not ready to handle requests and we have not yet
-		// shut it down.
-		pluginCrashed = p.Conn.GetState() != connectivity.Ready
```
Comment (iwahbe) [inline sdk/go/common/resource/plugin/plugin.go:563]: If we believe that valid options are `connectivity.Ready` and `connectivity.Idle`, why not just check for both?

File: sdk/go/common/resource/plugin/plugin_test.go [hunk 5]
```diff
@@ -89,3 +97,92 @@ func TestParsePort(t *testing.T) {
 		require.Error(t, err)
 	}
 }
+
+func TestHealthCheck(t *testing.T) {
```
Comment (iwahbe) [inline sdk/go/common/resource/plugin/plugin_test.go:101]: Does this check reproduce https://github.com/pulumi/pulumi/issues/18238?

Comment (t0yv0) [reply sdk/go/common/resource/plugin/plugin_test.go:101]: Last time I looked we didn't have a repro for 18238, it was based on log analysis. Unfortunately. I think absent a real repro this PR is a solution that's the best we can do.

File: sdk/go/common/resource/plugin/plugin_test.go (hunk 2 above)
Comment (t0yv0) [reply sdk/go/common/resource/plugin/plugin_test.go:114]: dialPlugin may be doing that on L125. If it responds it must've stared

```
			// The connection is supposedly ready; but we will make sure it is *actually* ready by sending a dummy
			// method invocation to the server.  Until it responds successfully, we can't safely proceed.
			for {
				handshakeRes, err = handshake(timeout, bin, prefix, conn)

```

https://github.com/pulumi/pulumi/blob/bd516f6535105497ee5596c6c2eeea871b1539f8/sdk/go/common/resource/plugin/plugin.go#L189

**Review by t0yv0 — APPROVED** [review]
I'd love to try this. If we exclude false positives this opens up alerting possibilities for providers to build alerts off logs that look like this.

File: sdk/go/common/resource/plugin/plugin.go (hunk 4 above)
Comment (justinvp) [reply sdk/go/common/resource/plugin/plugin.go:563]: I’ve observed a plugin that has crashed (panic in Configure) initially goes to Idle. I don’t think we can reliably tell from the connection state.

File: sdk/go/common/resource/plugin/plugin.go [hunk 6]
```diff
@@ -554,14 +555,33 @@ func buildPluginArguments(opts pluginArgumentOptions) []string {
...
+	req := &grpc_health_v1.HealthCheckRequest{}
+	_, err := health.Check(ctx, req)
+	if err != nil && status.Code(err) != codes.Unimplemented {
+		logging.V(9).Infof("healthCheck(): failed with: %v", err)
+		return false
+	}
+
+	return true
+}
+
```
Comment (cynicaljoy) [inline sdk/go/common/resource/plugin/plugin.go:578]:
```suggestion
func (p *plugin) healthCheck() bool {
	if p.Conn == nil {
		return false
	}

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	healthy := make(chan bool, 1)
	go func() {
		health := grpc_health_v1.NewHealthClient(p.Conn)
		req := &grpc_health_v1.HealthCheckRequest{}

		resp, err := health.Check(ctx, req)
		if err != nil {
			if status.Code(err) == codes.Unimplemented {
				healthy <- true 
				return
			}

			logging.V(9).Infof("healthCheck(): failed with: %v", err)
			healthy <- false
			return
		}

		healthy <- resp.Status == grpc_health_v1.HealthCheckResponse_SERVING
	}()

	select {
	case result := <-healthy:
		return result
	case <-ctx.Done(): // hit deadline
		return false
	}
}

```

- More explicit about handling timeouts through select pattern 
- validates the result from the health check
- early return inside of the error handling, easier to add more error cases later

File: sdk/go/common/resource/plugin/plugin.go (hunk 3 above)
Comment (justinvp) [reply sdk/go/common/resource/plugin/plugin.go:567]: Yes, it's possible to take that long for crashed plugins. We can probably get by with a shorter amount of time, but I wasn't sure how much grace to give Idle connections to reconnect for plugins that are still alive. These are local connections, so reconnects _should_ be much faster than seconds. On my machine local connections take anywhere from 216.917µs to 339.833µs. 500ms (half a second) should be plenty, I can try reducing it to that.

File: sdk/go/common/resource/plugin/plugin_test.go (hunk 2 above)
Comment (justinvp) [reply sdk/go/common/resource/plugin/plugin_test.go:116]: Went ahead and used a channel to make sure the server is ready.

File: sdk/go/common/resource/plugin/plugin.go (hunk 6 above)
Comment (justinvp) [reply sdk/go/common/resource/plugin/plugin.go]: Thanks for the feedback, @cynicaljoy!
