### PR TITLE
Fix AI prompt repetition on Windows

### LINKED ISSUE #14973: AI template prompt is repeated on Windows
When using `pulumi new` with AI generated templates, the question and response for the prompt is repeated back to the user on Windows:

```console
> pulumi.exe new
Would you like to create a project from a template or using a Pulumi AI prompt? ai
Please select a language for your project: JavaScript
? Please input your prompt here ("a static website on AWS behind a CDN"):
  an s3 bucket
? Please input your prompt here ("a static website on AWS behind a CDN"):
  an s3 bucket
```

The user is only asked the one time, the repetition appears to be a bug in Survey. Shortly after pressing enter the AI generated template is rendered to the user, with no impact on the functionality of the command.

### PR DESCRIPTION
**Pull request by AaronFriel**
# Description

Switches the prompt to use the `promptForValue` function, which now accepts an empty type descriptor. This renders to the user as:

```console
$ pulumi new
 Would you like to create a project from a template or using a Pulumi AI prompt? ai
 Please select a language for your project: TypeScript
What cloud infrastructure would you like to build?
(try something like "a static website on AWS behind a CDN")
> an eks cluster
Sending prompt to Pulumi AI...
Pulumi AI response:
\`\`\`typescript
...
\`\`\`
View this conversation at:  https://www.pulumi.com/ai/conversations/13a802da-50b6-46e8-bc82-fd2f7ac6e364
 Use this program as a template? refine
Tell Pulumi AI how to refine the previous program:
> add an awsx vpc
...
```

We're still a little inconsistent between the survey asked questions and those using `promptForValue`. An overhaul here would be a much larger change that's currently out of scope.

Removes a test that only tested the mocks, was not working on Windows due to OS-specific behavior in Survey.

Fixes #14973

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

### CODE REVIEW

File: pkg/cmd/pulumi/new_ai.go [hunk 1]
```diff
@@ -159,6 +159,40 @@ func sendPromptToPulumiAI(
...
+const initialPromptPrompt = `What cloud infrastructure would you like to build?
+(try something like "a static website on AWS behind a CDN")`
+
+const refinePromptPrompt = "Tell Pulumi AI how to refine the previous program:"
+
+var errEmptyPrompt = errors.New("prompt cannot be empty")
+
+func isValidAiPrompt(prompt string) error {
+	if prompt == "" {
+		return errors.New("prompt cannot be empty")
```
Comment (justinvp) [inline pkg/cmd/pulumi/new_ai.go:171]: Should this be returning `errEmptyPrompt`?

**Review by justinvp — APPROVED** [review]
LGTM otherwise

**Comment by justinvp** [comment]
Why aren't we including a changelog for the bug fix? Just curious.

File: pkg/cmd/pulumi/new_ai.go (hunk 1 above)
Comment (AaronFriel) [reply pkg/cmd/pulumi/new_ai.go:171]: Yeah.
