### PR TITLE
[sdk/nodejs] Fix provider for resource methods

### LINKED ISSUE #13777: Unexpected error "Call is not yet implemented"
Regression detected updating from 3.75 (July 12th release) to 3.78.1

Looks like the error comes from here:

https://github.com/pulumi/pulumi/blob/baf7dcc180b0240eee15bc14d74f59a4b5a7a665/pkg/resource/provider/component_provider.go#L131

Stack trace starts here: 

https://github.com/pulumi/pulumi/blob/9b39af3a4cf0508dc623b7ac9357beeacaddf90d/sdk/nodejs/runtime/invoke.ts#L301

### PR DESCRIPTION
**Pull request by justinvp**
The `Resource` class in the Node.js SDK has the following internal property:

```typescript
/** @internal */
readonly __prov?: ProviderResource;
```

When a resource is created, the provider specified for the resource is stored in this property. If it is set, it is passed along in the `Call` request when a method is called on the resource.

Prior to #13282, the property was only set for custom resources in `Resource`'s constructor:

```typescript
this.__prov = custom ? opts.provider : undefined;
```

With #13282, it was changed to also store the value for remote components:

```diff
- this.__prov = custom ? opts.provider : undefined;
+ this.__prov = custom || remote ? opts.provider : undefined;
```

This regressed the behavior when calling a method on a remote component that had an explicit provider that wasn't the component provider, but some other provider (e.g. AWS provider) specified as:

```typescript
const component = new MyRemoteComponent("comp", {
}, { provider: awsProvider });
```

The `awsProvider` was being stored in `Resource.__prov`, and when making the method call on the resource, it would try to invoke `Call` on the AWS provider, rather than calling the remote component provider's `Call`, which resulted in an error.

Note that specifying the AWS provider using the more verbose `providers: [awsProvider]` works around the issue.

The fix is to only set `__prov` if the provider's package is the same as the resource's package. Otherwise, don't set it, because the user is specifying a provider with the `provider: awsProvider` syntax as shorthand for `providers: [awsProvider]`.

Fixes #13777

### CODE REVIEW

File: sdk/nodejs/resource.ts [hunk 1]
```diff
@@ -454,8 +455,16 @@ export abstract class Resource {
             }
         }
 
+        // Store the provider in `__prov` if the provider's package is the same
+        // as the resource's package. Otherwise, don't, as the user specified
+        // `provider: someProvider` as shorthand for `providers: [someProvider]`.
```
Comment (dixler) [inline sdk/nodejs/resource.ts:460]: Can you make this comment be more high-level explaining the motivation behind this in comment form for future readers?

Comment (justinvp) [reply sdk/nodejs/resource.ts]: I've explained more in the comment.

**Review by dixler — APPROVED** [review]
LGTM
