### PR TITLE
[mlc] Propagate organization to component construct context

### LINKED ISSUE #21905: Calling `getOrganization` in TypeScript MLCs errors
### What happened?

I was trying to build a TypeScript component that included the following tag:

```typescript
const tags = { pulumi: `${pulumi.getOrganization()}/${pulumi.getProject()/${pulumi.getStack}` };
```

It failed with this incorrect error message:

```console
$ pulumi up
Previewing update (repro)

View in Browser (Ctrl+O): https://app.pulumi.com/iwahbe/repro-get-organization/repro/previews/ad0022e9-f66a-40a2-a5fb-625b1a39f9ae

     Type                 Name                          Plan       Info
 +   pulumi:pulumi:Stack  repro-get-organization-repro  create     1 error

Diagnostics:
  pulumi:pulumi:Stack (repro-get-organization-repro):
    error: component:index:Example resource 'example' has a problem: Missing organization name; for test mode, please call `pulumi.runtime.setMocks`

Resources:
    + 1 to create
    1 errored

```

### Example

```yaml
# Pulumi.yaml
name: repro-get-organization
runtime: yaml
packages:
  component: ./component
resources:
  example:
    type: component:Example
outputs:
  org: ${example.org}
```

```typescript
// component/index.ts
import * as pulumi from "@pulumi/pulumi";

export interface ExampleArgs {}

export class Example extends pulumi.ComponentResource {
    public readonly org: pulumi.Output<string>;

    constructor(name: string, args: ExampleArgs, opts?: pulumi.ComponentResourceOptions) {
        super("component:index:Example", name, args, opts);

        this.org = pulumi.output(pulumi.getOrganization());

        this.registerOutputs({ org: this.org });
    }
}
```

```json
// component/package.json
{
    "name": "component",
    "main": "index.ts",
    "dependencies": {
        "@pulumi/pulumi": "^3"
    }
}
```

```yaml
# component/PulumiPlugin.yaml
runtime: nodejs
```

```json
// component/tsconfig.json
{
    "compilerOptions": {
        "strict": true,
        "outDir": "bin",
        "target": "es2016",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true
    },
    "files": ["index.ts"]
}
```

### Output of `pulumi about`

```
CLI          
Version      3.223.0
Go Version   go1.26.0
Go Compiler  gc

Plugins
KIND      NAME       VERSION
resource  component  unknown
language  yaml       1.28.0

Host     
OS       darwin
Version  26.3
Arch     arm64

This project is written in yaml

Current Stack: iwahbe/repro-get-organization/repro

Found no resources associated with repro

Found no pending operations associated with repro

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/iwahbe
User           iwahbe
Organizations  iwahbe, moolumi, atestforme, pulumi-test
Token type     personal

Environment Variables:
Name                      Value
PULUMI_SUPPRESS_NEO_LINK  true

Dependencies:
NAME       VERSION
component  

Pulumi locates its logs in /var/folders/fg/_1q36r4j6yx0rwz2fbhjd5y40000gn/T/ by default
```

### Additional context

As part of this fix, we should confirm there is a test in all supported languages for this functionality. 

If this can be a `provider-` conformance test, even better.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by RohitYandigeri**
## Summary  
Fixes #21905. TypeScript multi-language components can currently call `pulumi.getProject()` and `pulumi.getStack()` during construct, but `pulumi.getOrganization()` fails because the organization is not propagated through the construct context path. This PR fixes that by passing `organization` through the same construct-info path already used for `project` and `stack` (engine → remote component construct info → provider plugin construct RPC request → provider server construct request reconstruction). This allows provider-backed multi-language components to read organization/project/stack together during construct. The regression coverage updates the existing provider component language test to expose a `context` output from the TypeScript component: ```${pulumi.getOrganization()}-${pulumi.getProject()}-${pulumi.getStack()}``` and asserts the expected value from the consumer side.

## Test plan  
- [x] Added appropriate unit tests - For all changes  
- [x] Added a test in `pkg/engine/lifecycletest` - For all engine/protocol changes  
- [x] Added a conformance test in `pkg/testing/pulumi-test-language` - For language protocol changes  
- [x] Added a golden test in `pkg/backend/display` - For changes to the output renderers  

## Validation  
- [x] `make lint` — clean  
- [x] `make test_fast` — all pass  
- [x] `make tidy_fix` — clean  
- [x] `make format_fix` — clean  
- [ ] Relevant SDK tests pass (if SDK changes)  
- [ ] `make check_proto` — clean (if proto changes)  

**Commands run:**  
`go test ./common/resource/plugin -run TestProvider_ConstructOptions -count=1`  
`go test ./resource/deploy -run TestResourceMonitor_remoteComponentIncludesOrganization -count=1`  

**Note:**  
The TypeScript MLC/provider language regression was also prepared, but the Node language-host test target is not runnable in this Windows environment because `sdk/nodejs/cmd/pulumi-language-nodejs` tests use `syscall.Mkfifo`.

## Changelog  
- [x] Changelog entry added.

## Risk  
Low. Blast radius is limited to construct-context propagation for multi-language components. This does not change provider diff/create semantics, resource state behavior, or engine planning behavior. The behavioral change is that organization is now available in the same construct context path that already carries project and stack, which makes `pulumi.getOrganization()` work correctly in provider-backed multi-language components.

### CODE REVIEW

File: pkg/resource/deploy/source_eval_test.go
Comment (Frassle) [inline pkg/resource/deploy/source_eval_test.go]: Pretty sure there will be tests in the engine/lifecycle folder for checkin stack and project. Organisation checks should be added there, not added as a new test here.

File: sdk/nodejs/cmd/pulumi-language-nodejs/testdata/providers/conformance-component/index.ts
Comment (Frassle) [inline sdk/nodejs/cmd/pulumi-language-nodejs/testdata/providers/conformance-component/index.ts]: This should probably be a new provider and conformance test. Simple needs to stay as simple as possible to check bootstrapping.

**Comment by RohitYandigeri** [comment]
Applied both review points and pushed ef65f98489.

I removed the new source_eval_test coverage and moved the organization assertion into pkg/engine/lifecycletest/components_test.go.

I also reverted the extra builtin-info behavior from conformance-component and added a separate provider + dedicated conformance test for this case instead.

File: pkg/engine/lifecycletest/components_test.go [hunk 1]
```diff
@@ -92,6 +92,54 @@ func TestSingleComponentDefaultProviderLifecycle(t *testing.T) {
...
+	loaders := []*deploytest.ProviderLoader{
+		deploytest.NewProviderLoader("pkgA", semver.MustParse("1.0.0"), func() (plugin.Provider, error) {
+			return &deploytest.Provider{
+				ConstructF: func(
+					_ context.Context,
+					req plugin.ConstructRequest,
+					monitor *deploytest.ResourceMonitor,
+				) (plugin.ConstructResponse, error) {
+					assert.Equal(t, "test", req.Info.Project)
+					assert.Equal(t, "test", req.Info.Stack)
```
Comment (Frassle) [inline pkg/engine/lifecycletest/components_test.go]: Use a different string here just to ensure there isn't stack/project mixups

File: pkg/engine/lifecycletest/components_test.go [hunk 2]
```diff
@@ -92,6 +92,54 @@ func TestSingleComponentDefaultProviderLifecycle(t *testing.T) {
...
+			Remote: true,
+		})
+		require.NoError(t, err)
+		return nil
+	})
+	hostF := deploytest.NewPluginHostF(nil, nil, programF, loaders...)
+
+	p := &lt.TestPlan{
+		Options: lt.TestUpdateOptions{T: t, HostF: hostF, SkipDisplayTests: true},
+		Steps:   lt.MakeBasicLifecycleSteps(t, 2),
```
Comment (Frassle) [inline pkg/engine/lifecycletest/components_test.go]: I don't think we need Steps set if we're running the testop directly below

File: pkg/testing/pulumi-test-language/providers/builtin_info_component_provider.go
Comment (Frassle) [inline pkg/testing/pulumi-test-language/providers/builtin_info_component_provider.go]: May as well return each field separately

**Comment by RohitYandigeri** [comment]
Applied all three review points and pushed 4ca0843c51.

I changed the lifecycle test to use distinct project/stack/organization values so mixups are visible, removed the unused Steps from that test plan, and updated the dedicated builtin-info provider/conformance test to return and assert organization, project, and stack as separate fields.

**Comment by Frassle** [comment]
/run-acceptance-tests
Please view the results of the acceptance tests [Here](https://github.com/pulumi/pulumi/actions/runs/23404486713)

**Comment by RohitYandigeri** [comment]
I fixed the two PR-caused CI failures and pushed e7d482c48d.

Specifically:

made builtin-info-component use a unique provider version (34.0.0) to satisfy TestUniqueProviderVersions
added the missing tests/testdata/provider-builtin-info-component/main.pp fixture for TestBindPrograms
aligned the published Node fixture package refs to the same provider version
I also verified locally with:
go test ./testing/pulumi-test-language -run "Test(UniqueProviderVersions|BindPrograms)" -count=1

The sdk/nodejs automation failure in the log appears to be an unrelated 502 Bad Gateway from pulumi config env add ....

**Comment by Frassle** [comment]
/run-acceptance-tests
Please view the results of the acceptance tests [Here](https://github.com/pulumi/pulumi/actions/runs/23412183205)

**Comment by RohitYandigeri** [comment]
@Frassle i'm stuck with the ci issues, could you please guide me with what actual fix need to be done?

**Comment by Frassle** [comment]
```
=== FAIL: . TestLanguageTSNode/local=false/provider-builtin-info-component (23.30s)
    language_test.go:236: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go:236
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = sdk snapshot validation for builtin-info-component: walk expected dir: lstat testdata/published/tsnode/sdks/builtin-info-component-0.0.0: no such file or directory
        	Test:       	TestLanguageTSNode/local=false/provider-builtin-info-component
```
Looks like some snapshots are missing? Although I don't think this should be version 0.0.0

**Comment by RohitYandigeri** [comment]
> ```
> === FAIL: . TestLanguageTSNode/local=false/provider-builtin-info-component (23.30s)
>     language_test.go:236: 
>         	Error Trace:	/home/runner/work/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go:236
>         	Error:      	Received unexpected error:
>         	            	rpc error: code = Unknown desc = sdk snapshot validation for builtin-info-component: walk expected dir: lstat testdata/published/tsnode/sdks/builtin-info-component-0.0.0: no such file or directory
>         	Test:       	TestLanguageTSNode/local=false/provider-builtin-info-component
> ```
> 
> Looks like some snapshots are missing? Although I don't think this should be version 0.0.0

Added the missing published SDK snapshots for builtin-info-component-34.0.0 and fixed the provider fixture metadata so it no longer falls back to 0.0.0. Pushed in d3d14a1820.

**Comment by RohitYandigeri** [comment]
@Frassle can we take this further ?

**Comment by RohitYandigeri** [comment]
@Frassle @julienp updates ?

**Comment by Frassle** [comment]
/run-acceptance-tests
Please view the results of the acceptance tests [Here](https://github.com/pulumi/pulumi/actions/runs/24330992320)

**Comment by Frassle** [comment]
> provider version 34.0.0 is used by both optionalprimitive and builtin-info-component, next provider version is 36.0.0

new provider version will need bumping up to 36.

**Comment by Frassle** [comment]
I've also got some work that we'll want to rebase this ontop of, we'll still be taking the tests and things from this PR but rather than doing another one-off fix to the ConstructInfo data I'm going to change programs and construct to get all the deployment info the same way.

**Review by Frassle — APPROVED** [review]

**Comment by Frassle** [comment]
Looks like the bun conformance tests hit an issue with data not being present

**Comment by iwahbe** [comment]
Now `TestUniqueProviderVersions` is failing. I'll fix that after https://github.com/pulumi/pulumi/pull/22696 merges.
