### PR TITLE
Resources now inherit the `DeletedWith` Resource Option across SDKs

### LINKED ISSUE #12158: `deletedWith` resource option is not inherited by child resources
### What happened?

The `deletedWith` resource option is not inherited by child resources when the option is set on the parent. This results in the physical child resources being deleted from the cloud provider, while the parent resource remains.

### Expected Behavior

child resource should only be deleted from Pulumi state; not the cloud provider 

### Steps to reproduce

Using the following program execute:
- `pulumi up -f`
- `pulumi destroy -f`

After destroy, parent-bucket and all child-buckets should physically remain in AWS, however, only the parent-bucket remains.

```typescript
import * as aws from "@pulumi/aws";

// all resources should below should only be deleted from stack state
const bucket = new aws.s3.Bucket("base-bucket");

// set deletedWith to stop provider from calling Delete
const parentBucket = new aws.s3.Bucket("parent-bucket", {}, { deletedWith: bucket });

// deletedWith should be inherited from parent and stop physical resource from being deleted
new aws.s3.Bucket("child-bucket-1", {}, { parent: parentBucket });
new aws.s3.Bucket("child-bucket-2", {}, { parent: parentBucket });
new aws.s3.Bucket("child-bucket-3", {}, { parent: parentBucket });
```

### Output of `pulumi about`

CLI          
Version      3.53.0
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.29.1
awsx    1.0.2
docker  3.6.1
nodejs  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/home/pedwards/.nvm/versions/node/v14.17.3/bin/node' version='v14.17.3'

Current Stack: team-ce/deleted-with-parent/phil

Found no resources associated with phil

Found no pending operations associated with phil

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/phillipedwards
User           phillipedwards

Dependencies:
NAME            VERSION
@pulumi/awsx    1.0.2
@pulumi/pulumi  3.54.0
@types/node     16.18.12
@pulumi/aws     5.29.1

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description
Tracking inheritance of resource options across SDKs is difficult to scale. This PR uses this information to set the `DeletedWith` when it is left unset by the user's program and there is a Parent resource to inherit the value from.

Alternate approach to https://github.com/pulumi/pulumi/pull/12420

Fixes #12158 

Needs follow up on: https://github.com/pulumi/pulumi-hugo/issues/2566

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/resource/deploy/step_generator.go [hunk 1]
```diff
@@ -421,22 +424,50 @@ func (sg *stepGenerator) inheritedChildAlias(
...
+	goal := event.Goal()
+
+	// Configure Goal's parent and inherited ResourceOptions.
+	sg.configureGoal(goal)
 
 	urn, res := sg.generateURN(goal.Parent, goal.Type, goal.Name)
 	if res != nil {
 		return nil, res
 	}
+	defer func() { sg.resourceGoals[urn] = goal }()
```
[the remark this answers is not in the document]
Comment (dixler) [reply pkg/resource/deploy/step_generator.go:470]: I was being defensive against future PRs. I was concerned about putting the Goal into the map before Goal leaves the function scope as a future PR may mutate the value somewhere else in this function before returning.

As it is a pointer, it's possible to change it after the fact via mutations in this function, but I didn't want another thread racing and potentially reading another URN's goal before it was fully configured and would prefer that it fail to find the Goal over have outdated data.

[the remark this answers is not in the document]
Comment (Frassle) [reply pkg/resource/deploy/step_generator.go:470]: Step gen is synchronous anyway, this doesn't need to defer

[the remark this answers is not in the document]
Comment (dixler) [reply pkg/resource/deploy/step_generator.go:470]: For now, but there are asks to make it async 😉 

https://github.com/pulumi/pulumi/issues/12351

File: pkg/resource/deploy/step_generator.go [hunk 2]
```diff
@@ -421,23 +424,57 @@ func (sg *stepGenerator) inheritedChildAlias(
...
+			parentGoal = sg.resourceGoals[parentURN]
+		}
+
+		// Make resource goal inherit parent's default resource options if left unset.
+		if goal.DeletedWith == "" {
+			goal.DeletedWith = parentGoal.DeletedWith
+		}
+	}
+
+	// Some goal settings are based on the parent settings so make sure our parent is correct.
```
Comment (Frassle) [inline pkg/resource/deploy/step_generator.go:448]: Probably want to do this _first_

File: pkg/resource/deploy/step_generator.go [hunk 3]
```diff
@@ -421,23 +424,57 @@ func (sg *stepGenerator) inheritedChildAlias(
...
 
+// configureGoal mutates the passed goal to inherit the correct ResourceOptions from its parent.
+func (sg *stepGenerator) configureGoal(goal *resource.Goal) result.Result {
+	originalParent := goal.Parent
+
+	if originalParent != "" {
+		parentGoal, ok := sg.resourceGoals[originalParent]
+		if !ok {
+			// Check if originalParent is an Alias
+			parentURN, ok := sg.aliases[originalParent]
```
Comment (Frassle) [inline pkg/resource/deploy/step_generator.go:435]: Parents won't ever be aliases, you can just take the result of checkParent to know the parent URN (or "")

Comment (abhinav) [inline pkg/resource/deploy/step_generator.go:435]: This won't handle multiple levels of aliasing (alias of alias of alias).
We need a loop here. Maybe this should be:

```go
if originalParent != "" {
  // Resolve alias until unaliased URN is found.
  parentURN := originalParent
  for {
    dest, ok := sg.aliases[parentURN]
    if !ok {  break } // parentURN is not an alias
    parentURN = dest
  }

  parentGoal, ok := sg.resourceGoals[parentURN]
  if !ok {
    return result.Errorf(...)
  }
}
```

(I wonder if StepGenerator already has a thing for resolving URNs to unaliased destinations.)

Comment (abhinav) [reply pkg/resource/deploy/step_generator.go:435]: Looking at @Frassle's other comment, this may be moot.

File: pkg/resource/deploy/step_generator_test.go [hunk 4]
```diff
@@ -360,3 +360,105 @@ func TestEngineDiff(t *testing.T) {
 		})
 	}
 }
+
+func TestResourceInheritsOptionsFromParent(t *testing.T) {
+	t.Parallel()
+
+	t.Run("children missing DeletedWith should inherit DeletedWith", func(t *testing.T) {
```
Comment (abhinav) [inline pkg/resource/deploy/step_generator_test.go:367]: minor: Test name is part of the subtest name so we can eliminate some redundancy in the name.
Longer explanations can be inside comments if needed.

For these tests, maybe: DeletedWith/inherit, DeletedWith/override, DeletedWith/empty?
(The "/" will group them all under an implicit "DeletedWith" test group.)

File: pkg/resource/deploy/step_generator_test.go [hunk 5]
```diff
@@ -360,3 +360,105 @@ func TestEngineDiff(t *testing.T) {
 		})
 	}
 }
+
+func TestResourceInheritsOptionsFromParent(t *testing.T) {
```
Comment (abhinav) [inline pkg/resource/deploy/step_generator_test.go:364]: The three subtests in this package might be easily combinable into a table test.

```go
tests := []struct{
    desc string

    parentDeletedWith string
    childDeletedWith  string
    wantDeletedWith   string
}{
    {
        desc: "...",
        parentDeletedWith: "parent-deleted-with",
        childDeletedWith: "",
        wantDeletedWith: "parent-deleted-with",
    },
    {
        desc: "...",
        parentDeletedWith: "parent-deleted-with",
        childDeletedWith: "this-value-should-not-change",
        wantDeletedWith: "this-value-should-not-change",
    },
    {
        desc: "...",
        parentDeletedWith: "",
        childDeletedWith: "this-value-should-not-change",
        wantDeletedWith: "this-value-should-not-change",
    },
}

for _, tt := range tests {
    tt := tt
    t.Run(tt.desc, func(t *testing.T) {
        t.Parallel()

        parentURN := // ...
        parentGoal := &resource.Goal{
            // ...
            DeletedWith: tt.parentDeletedWith,
        }

        childURN := // ...
        goal := &resource.Goal{
            // ...
            DeletedWith: tt.childDeletedWith,
        }

        sg := // ...
        // ...

        require.NoError(t, err)
        assert.Equal(t, tt.wantDeletedWith, goal.DeletedWith)
    })
}
```

You can keep the test general (as it is) to leave room for other options here,
or maybe rename it to TestInheritsDeletedWithFromParent to make it
DeletedWith-specific, which will also allow renaming the fields of the table
above to something shorter:

```go

func TestInheritsDeletedWithFromParent(t *testing.T) {
    t.Parallel()

    tests := []struct{
        desc   string
        parent string
        child  string
        want   string
    }{
        // ...
```

**Review by abhinav — COMMENTED** [review]
Logic LGTM, but I would also get @Frassle's approval on that.
Left a suggestion on the testing code.

**Review by abhinav — APPROVED** [review]
LGTM. Please get a @Frassle stamp before merging because I'm less familiar with the step generator.

File: pkg/resource/deploy/step_generator.go [hunk 6]
```diff
@@ -421,23 +424,52 @@ func (sg *stepGenerator) inheritedChildAlias(
...
+	// Some goal settings are based on the parent settings so make sure our parent is correct.
+	p, res := sg.checkParent(goal.Parent, goal.Type)
+	if res != nil {
+		return res
+	}
+
+	if p != "" {
+		parentGoal, ok := sg.resourceGoals[p]
+		if !ok {
+			return result.Errorf("could not find parent resource alias %v", originalParent)
```
Comment (Frassle) [inline pkg/resource/deploy/step_generator.go:440]:
```suggestion
			return result.Errorf("could not find parent goal %v (originally %v)", p, originalParent)
```

**Review by Frassle — APPROVED** [review]
Small error message change but otherwise I think this is fine.

**Comment by dixler** [comment]
bors merge
