### PR TITLE
fix panic when Pulumi.yaml has a provider with an empty/unspecified path key

### LINKED ISSUE #11864: Invalid plugin overrides panic on startup
### What happened?

Running `pulumi up` with an invalid `Pulumi.yaml["plugins"]["providers"]` causes a panic before main.

### Steps to reproduce

Run `pulumi up` with:

```yaml
name: csharp-artifactory
runtime: dotnet
description: A minimal C# Pulumi program
plugins:
  providers:
    - name: artifactory
      bin: ../../../bin # key should be 'path'
```

### Expected Behavior

A useful error message.

### Actual Behavior

```
X pulumi up
panic: fatal: could not find provider folder at path 

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.AssertNoError({0x102720ae0?, 0xc0004c3990?})
        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/assert.go:40 +0x88
github.com/pulumi/pulumi/pkg/v3/codegen/schema.newPulumiPackage()
        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/mock_pulumi_schema.go:41 +0x42d
github.com/pulumi/pulumi/pkg/v3/codegen/schema.init()
        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/mock_pulumi_schema.go:45 +0x11f
```

### Output of `pulumi about`

_No response_

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description

Fixes #11864 

This PR introduces a change such that Pulumi no longer panics before main when the Pulumi.yaml contains a provider plugin that has an empty/unspecified `path` key.

This PR removes the `contract.AssertNoError()` call and modifies the function to return the error. Instead of panicking, the error is now contained in the `DefaultPulumiPackageError` variable.

In terms of usage, it appears that [pulumi-lsp](https://github.com/pulumi/pulumi-lsp/blob/d5e1d1ef3750479a17e351675b0dfee654de61c0/sdk/yaml/completion.go#L353) uses this variable.

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/codegen/schema/mock_pulumi_schema.go [hunk 1]
```diff
@@ -38,8 +34,7 @@ func newPulumiPackage() *Package {
 	}
 
 	pkg, err := ImportSpec(spec, nil)
-	contract.AssertNoError(err)
```
Comment (Frassle) [inline pkg/codegen/schema/mock_pulumi_schema.go:41]: This really really shouldn't ever error, the assert is correct.

File: tests/integration/integration_test.go [hunk 2]
```diff
@@ -644,3 +644,31 @@ func TestExcludeProtected(t *testing.T) {
...
+	}()
+
+	pulumiProject := `
+name: invalid-plugin
+runtime: yaml
+description: A Pulumi program referencing an invalid plugin.
+plugins:
+  providers:
+    - name: fakeplugin
+      bin: ./does/not/exist/bin # key should be 'path'
```
Comment (Frassle) [inline tests/integration/integration_test.go:665]: Why isn't something like this getting picked up by the schema check?

File: pkg/codegen/schema/mock_pulumi_schema.go (hunk 1 above)
Comment (dixler) [reply pkg/codegen/schema/mock_pulumi_schema.go:41]: This checks the user's `Pulumi.yaml` which can be incorrect.

This is then run before main because of the top level `var DefaultPulumiPackage = newPulumiPackage()` on line 45

File: tests/integration/integration_test.go (hunk 2 above)
Comment (dixler) [reply tests/integration/integration_test.go:665]: Can you link where the schema check your referring to is?

File: pkg/codegen/schema/mock_pulumi_schema.go (hunk 1 above)
Comment (Frassle) [reply pkg/codegen/schema/mock_pulumi_schema.go:41]: This is the core pulumi schema, not the users Pulumi.yaml

Comment (Frassle) [reply pkg/codegen/schema/mock_pulumi_schema.go:41]: This is the core pulumi schema, not the users Pulumi.yaml

File: tests/integration/integration_test.go (hunk 2 above)
Comment (Frassle) [reply tests/integration/integration_test.go:665]: This file https://github.com/pulumi/pulumi/blob/master/sdk/go/common/workspace/project.json

I thought we validated against that when loading project files.
Looks like pluginOptions is missing a "additionalProperties: false" clause.

**Comment by iwahbe** [comment]
It looks like the error is originating in creating a `schema.Loader` and it's underlying `pulumi.Context`.

https://github.com/pulumi/pulumi/blob/b9ee42e32909ccd86672495abfa17d52ae891579/pkg/codegen/schema/bind.go#L250-L264

Since we know a priori that [`newPulumiPackage`](https://github.com/pulumi/pulumi/blob/b9ee42e32909ccd86672495abfa17d52ae891579/pkg/codegen/schema/mock_pulumi_schema.go#L5) will not need to load external packages, can we explore using in a dummy loader that panics when invoked. 

I'd like to avoid adding an error flag for an error that should never be set, and I'd like even more to avoid creating an error condition unrelated to the error we are reporting.

File: tests/integration/integration_test.go (hunk 2 above)
Comment (abhinav) [reply tests/integration/integration_test.go:665]: Looks like the validation does run. Those fields just weren't marked required.
If you revert the changes to pkg/ and make the following change to the schema,
it errors instead of panicking.

```diff
diff --git a/sdk/go/common/workspace/project.json b/sdk/go/common/workspace/project.json
index 822122748..ef0d1e23b 100644
--- a/sdk/go/common/workspace/project.json
+++ b/sdk/go/common/workspace/project.json
@@ -238,6 +238,7 @@
         "pluginOptions":{
             "title":"PluginOptions",
             "type":"object",
+            "required":["name","path"],
             "properties":{
                 "name":{
                     "type":"string",
```

New error:

```
% go test -v -run TestInvalidPluginError -tags all
=== RUN   TestInvalidPluginError
=== PAUSE TestInvalidPluginError
=== CONT  TestInvalidPluginError
    environment.go:96: Created new test environment:  /var/folders/12/gsh1s5sj4ds4mgmdyg4b5h400000gn/T/test-env1276381302
    pulumi.go:44: Running command git init
    integration_test.go:670: Running command pulumi stack init invalid-resources
    integration_test.go:670: Run Error: exit status 255
    integration_test.go:670: STDOUT:
    integration_test.go:670: STDERR: error: could not create stack: getting stack tags: error loading project "/private/var/folders/12/gsh1s5sj4ds4mgmdyg4b5h400000gn/T/test-env1276381302/Pulumi.yaml": could not validate '/private/var/folders/12/gsh1s5sj4ds4mgmdyg4b5h400000gn/T/test-env1276381302/Pulumi.yaml': 2 errors occurred:
                * #/plugins/providers/0: doesn't validate with '/$defs/pluginOptions'
                * #/plugins/providers/0: missing properties: 'path'


    integration_test.go:670: Ran command pulumi args [stack init invalid-resources] and expected success. Instead got failure.
--- FAIL: TestInvalidPluginError (0.15s)
FAIL
exit status 1
FAIL    github.com/pulumi/pulumi/tests/integration      0.558s
```

I don't know if that's better, though.

File: pkg/codegen/schema/mock_pulumi_schema.go [hunk 3]
```diff
@@ -38,8 +34,7 @@ func newPulumiPackage() *Package {
...
-	return pkg
+	return pkg, err
 }
 
-var DefaultPulumiPackage = newPulumiPackage()
+var DefaultPulumiPackage, DefaultPulumiPackageError = newPulumiPackage()
```
Comment (abhinav) [inline pkg/codegen/schema/mock_pulumi_schema.go:40]: I can see why we need to expose the error information (thanks for the reference to the lsp example), but I think this is a bit fragile. It's easy to forget to check the error here. It would be preferable if we could make this a function.

If it's possible to change this API, we can hide the variable and introduce a top-level function:

```go
func DefaultPulumiPackage() (*Package, error)
```

Implementation would internally use sync.Once to maintain the singleton:

```go
var defaultPulumiPackage struct {
  pkg *Package
  err error
  once sync.Once
}

func DefaultPulumiPackage() (*Package, error) {
  defaultPulumiPackage.once.Do(func() {
    defaultPulumiPackage.pkg, defaultPulumiPackage.err = newPulumiPackage()
  })
  return defaultPulumiPackage.pkg, defaultPulumiPackage.err
}
```

Comment (Frassle) [reply pkg/codegen/schema/mock_pulumi_schema.go:40]: newPulumiPackage _should not fail_, it's an engine bug if it errors.

File: tests/integration/integration_test.go (hunk 2 above)
Comment (Frassle) [reply tests/integration/integration_test.go:665]: Adding "required" is a good call, I'd _also_ add "additionalProperties: false". I think that error is fine, if your project is malformed pulumi should generally just error out that it doesn't understand the project file.

File: sdk/go/common/workspace/project.json [hunk 4]
```diff
@@ -317,4 +322,4 @@
             }
         }
     }
-}
\ No newline at end of file
+}
```
Comment (dixler) [inline sdk/go/common/workspace/project.json:325]: my editor has opinions about newlines at the end of files. idk if they're the right ones.

**Review by abhinav — APPROVED** [review]
🚢

**Review by Frassle — APPROVED** [review]

**Comment by iwahbe** [comment]
@dixler This is a positive change, but doesn't fix the problem. With your changes applied, I still get a panic with an invalid `providers` block:

```
panic: fatal: parsing plugin options for 'aws': no folder at path '../123'

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.AssertNoError({0x102720820?, 0xc0004b6c80?})
        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/assert.go:40 +0x88
github.com/pulumi/pulumi/pkg/v3/codegen/schema.newPulumiPackage()
        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/mock_pulumi_schema.go:41 +0x42d
github.com/pulumi/pulumi/pkg/v3/codegen/schema.init()
        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/mock_pulumi_schema.go:45 +0x11f
```

When I run `pulumi up` with this `Pulumi.yaml`:

```yaml
name: some-program
runtime: yaml
plugins:
  providers:
    - name: aws
      path: ../123
```

**Comment by Frassle** [comment]
> but doesn't fix the problem

Yup that will need the change of not using a full loader that tries to use project to set up the pulumi schema. I don't mind if that's in this or a separate PR though.
