### PR TITLE
Fix resource-ref-as-ID marshaling.

### LINKED ISSUE #5939: Preview fails when resource refs are enabled
From https://github.com/pulumi/pulumi/issues/5933:

Previews fail in very incorrect ways with CLI `2.15.5`.

```ts
import * as aws from "@pulumi/aws";
const bucket = new aws.s3.Bucket("mybucket");
bucket.onObjectCreated("foofunction", async (ev, ctx) => {
    console.log(JSON.stringify(ev));
});
```

```
$ pulumi preview
...
Diagnostics:
  aws:lambda:Permission (foofunction):
    error: aws:lambda/permission:Permission resource 'foofunction' has a problem: "function_name" doesn't comply with restrictions ("^(arn:[\\w-]+:lambda:)?([a-z]{2}-(?:[a-z]+-){1,2}\\d{1}:)?(\\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\\$LATEST|[a-zA-Z0-9-_]+))?$"): "urn:pulumi:dev::promisecapture::aws:s3/bucket:Bucket$aws:s3:BucketEventSubscription$aws:lambda/function:Function::foofunction"
```

This happens when resource refs are enabled.

### PR DESCRIPTION
**Pull request by pgavlin**
When marshaling a resource reference as its ID (i.e. when
opts.KeepResources is false, as it will be in the case of downlevel SDKs
and resource providers), we must take care to marshal/unmarshal an empty
ID as the unknown property value.

Fixes #5939.

### CODE REVIEW

File: sdk/go/common/resource/plugin/rpc.go [hunk 1]
```diff
@@ -168,6 +168,9 @@ func MarshalPropertyValue(v resource.PropertyValue, opts MarshalOptions) (*struc
 			val := string(ref.URN)
 			if ref.HasID {
 				val = string(ref.ID)
+				if val == "" {
```
Comment (lukehoban) [inline sdk/go/common/resource/plugin/rpc.go:171]: The semantics here are very subtle. Can we add comments somewhere appropriate that describe what these cases mean?

In particular - what ones hasid=true and id="" mean?

Comment (pgavlin) [reply sdk/go/common/resource/plugin/rpc.go:171]: Yeah, definitely.

The particular case that you've called out means "this reference has an ID, but that ID is unknown". In retrospect, it was probably a mistake to represent the ID as a simple string in the Go SDK rather than a `PropertyValue`, but I did want to be consistent with the semantics of resource IDs themselves (where an empty ID means that the ID is unknown). We need `HasID` to distinguish between refs that have an empty ID b/c the referenced resource is not a custom resource and refs that have an empty ID b/c the ID is unknown.

**Review by lblackstone — APPROVED** [review]

File: sdk/go/common/resource/plugin/rpc.go (hunk 1 above)
Comment (pgavlin) [reply sdk/go/common/resource/plugin/rpc.go]: Refactored for an approach that is hopefully clearer by construction.

File: sdk/go/common/resource/properties.go [hunk 2]
```diff
@@ -215,11 +230,25 @@ func MakeSecret(v PropertyValue) PropertyValue {
...
+		PackageVersion: packageVersion,
+	})
+}
+
+// MakeCustomResourceReference creates a reference to a custom resource. If the resource's ID is the empty string, it
+// will be treated as unknown.
+func MakeCustomResourceReference(urn URN, id ID, packageVersion string) PropertyValue {
+	idProp := NewStringProperty(string(id))
+	if id == "" {
+		idProp = MakeComputed(NewStringProperty(""))
```
Comment (lblackstone) [inline sdk/go/common/resource/properties.go:246]:
```suggestion
		idProp = MakeComputed(idProp)
```

**Review by lblackstone — APPROVED** [review]
I like the refactor; much easier to understand
