### PR TITLE
[policy/new] make `pulumi policy new <template-name>` runnable in non-interactive mode

### LINKED ISSUE #13901: [cli] `pulumi policy new` cannot be run non-interactively
### What happened?

`pulumi policy new` requires `--yes` when being run non-interactively. This makes it unusable for integration testing (currently).

```
% pulumi policy new kubernetes-premium-policies-typescript --force | cat
error: --yes must be passed in to proceed when running in non-interactive mode


% pulumi policy new kubernetes-premium-policies-typescript --force --yes | cat
Error: unknown flag: --yes
Usage:
  pulumi policy new [template|url] [flags]

Flags:
      --dir string      The location to place the generated Policy Pack; if not specified, the current directory is used
  -f, --force           Forces content to be generated even if it would change existing files
  -g, --generate-only   Generate the Policy Pack only; do not install dependencies
  -h, --help            help for new
  -o, --offline         Use locally cached templates without making any network requests

Global Flags:
      --color string                 Colorize output. Choices are: always, never, raw, auto (default "auto")
  -C, --cwd string                   Run pulumi as if it had been started in another directory
      --disable-integrity-checking   Disable integrity checking of checkpoint files
  -e, --emoji                        Enable emojis in the output
      --logflow                      Flow log settings to child processes (like plugins)
      --logtostderr                  Log to stderr instead of to files
      --memprofilerate int           Enable more precise (and expensive) memory allocation profiles by setting runtime.MemProfileRate
      --non-interactive              Disable interactive mode for all commands
      --profiling string             Emit CPU and memory profiles and an execution trace to '[filename].[pid].{cpu,mem,trace}', respectively
      --tracing file:                Emit tracing to the specified endpoint. Use the file: scheme to write tracing data to a local file
      --tracing-header string        Include the tracing header with the given contents.
  -v, --verbose int                  Enable verbose logging (e.g., v=3); anything >3 is very verbose

An error occurred: unknown flag: --yes
```

recording: https://asciinema.org/a/Cw5b5wy7F0DReFyky0phTet8q

### Expected Behavior

`--yes` should not be required since there's nothing left to confirm.

### Steps to reproduce

see above.

### Output of `pulumi about`

n/a

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description

Fixes #13901

`pulumi policy new <template-name>` would fail requiring a `--yes` argument that did not exist when being run non-interactively.

This changes `pulumi policy new <template-name>` to not require `--yes` when a template-name is provided.

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by Frassle — APPROVED** [review]

File: tests/remote_test.go [hunk 1]
```diff
@@ -154,3 +154,10 @@ func TestRemoteLifecycle(t *testing.T) {
 
 	e.RunCommand("pulumi", "stack", "rm", "--stack", fullyQualifiedStack, "--yes")
 }
+
+func TestPolicyNewNonInteractive(t *testing.T) {
```
Comment (justinvp) [inline tests/remote_test.go:158]: Nit: Seems a little odd to put this test in this file. Why not a new `policy_new_test.go` or `policy_test.go` file?

Comment (Frassle) [reply tests/remote_test.go:158]: Oh I didn't notice this was with the remote tests, that's a good point. Make a new file.

Comment (justinvp) [reply tests/remote_test.go]: I went ahead and pushed a commit that moves it to a new file.
