### PR TITLE
Fix `pulumi new` erroring when the project already exists.

### LINKED ISSUE #13774: `pulumi new -s` doesn't work for existing project
The "New Project" button in Pulumi Cloud creates a new project and stack and an empty update in that stack, then asks users to run these commands:

Screenshot 2023-08-24 at 9 15 55 PM

The `pulumi new -s` command fails with:

```
$ pulumi new https://github.com/lukehoban/pulumi-ai-starter/tree/main/next-openai -s luke-pulumi-corp/next-openai-luke/dev
error: a project with this name already exists: next-openai-luke
```

This happens for any template.

This appears to be a relatively recent regression.

### PR DESCRIPTION
**Pull request by dixler**
# Description

Fixes #13774

When `pulumi new -s org/project/stack` parses out the project name, it runs a validation of the project name which will throw an error if the project already exists and cause `pulumi new` to fail. This PR causes `pulumi new` to no longer fail. This also checks if the getStack value is nil and falls back on the projectName specified in the `-s` parameter.

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/cmd/pulumi/new.go [hunk 1]
```diff
@@ -132,6 +132,14 @@ func runNew(ctx context.Context, args newArgs) error {
...
 	}
 
+	// Ensure the project doesn't already exist.
+	if args.name != "" {
+		// There is no --org flag at the moment. The backend determines the orgName value if it is "".
+		if err := validateProjectName(ctx, b, "" /* orgName */, args.name, args.generateOnly, opts); err != nil {
+			return err
+		}
+	}
+
```
Comment (dixler) [inline pkg/cmd/pulumi/new.go:142]: Reverted moving this to the else block below.

File: pkg/cmd/pulumi/new.go [hunk 2]
```diff
@@ -183,26 +191,28 @@ func runNew(ctx context.Context, args newArgs) error {
 
 		// Set the org name for future use.
 		orgName = parts[0]
-
 		projectName := parts[1]
-		if err := validateProjectName(ctx, b, orgName, projectName, args.generateOnly, opts); err != nil {
-			return err
-		}
```
Comment (dixler) [inline pkg/cmd/pulumi/new.go:190]: "Validate project name errors if the project already exists."

Removing this check as we are checking the --stack argument so we don't care if the project already exists.

File: pkg/cmd/pulumi/new.go [hunk 3]
```diff
@@ -183,26 +191,28 @@ func runNew(ctx context.Context, args newArgs) error {
...
-			args.description = existingDesc
+		if existingStack != nil {
+			s = existingStack
+			if args.name == "" {
+				args.name = existingName
+			}
+			if args.description == "" {
+				args.description = existingDesc
+			}
+		} else {
```
Comment (dixler) [inline pkg/cmd/pulumi/new.go:213]: I made this change as we previously did not check if the stack was nil. We need to try to set `args.name` so that we don't prompt for the project name as we have it from the stack reference.

Comment (Frassle) [reply pkg/cmd/pulumi/new.go:213]: I think we could simplify getStack to not return the project at all and just unconditionally set args.name from the projectName pulled from parts above.

**Review by Frassle — APPROVED** [review]

File: pkg/cmd/pulumi/new.go (hunk 3 above)
Comment (dixler) [reply pkg/cmd/pulumi/new.go:213]: It'd be surprising if existingStack's project name != project (from `-s org/project/stack`) so I'll make the change.
