### PR TITLE
fix(testing): Adds cached python venvs for integration tests

### LINKED ISSUE #11485: [sdks/python] Cache virtual environments for integration tests
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, each integration test creates its own virtual environment, installs the released version of the pulumi python sdk and all its associated dependencies AND the local version and all its dependencies.  This can take between 2 to 6 minutes per test depending on how much dependencies differ between the two.  Instead of creating venvs based on the directory they're created in, we should create venvs based on the hashed contents of `requirements.txt` and reuse them on hash collision.

### Affected area/feature

Integration tests

### PR DESCRIPTION
**Pull request by kpitzen**
The cache key is based on hashing the contents of "requirements.txt" for each python test.  This should result in unchanged test results among tests sharing venvs, and maintains environment isolation across requirement sets

# Description

Fixes #11485 

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by kpitzen** [comment]
bors try

File: pkg/testing/integration/program.go [hunk 1]
```diff
@@ -292,6 +293,12 @@ type ProgramTestOptions struct {
 	UseAutomaticVirtualEnv bool
 	// Use the Pipenv tool to manage the virtual environment.
 	UsePipenv bool
+	// Use a shared virtual environment for tests based on the contents of the requirements file. Defaults to false.
+	UseSharedVirtualEnv *bool
```
Comment (kpitzen) [inline pkg/testing/integration/program.go:297]: I really don't love that I have to use a pointer here, but it _seems_ to be the only way to disambiguate between `false` and an unset value at initialization time.  I've used a convenience function to try to alleviate the ergonomics issue this introduces, but I'm open to other approaches if anyone has any.

**Comment by kpitzen** [comment]
bors try

**Review by AaronFriel — APPROVED** [review]
The improvement in test execution time speaks for itself.

File: pkg/testing/integration/program.go (hunk 1 above)
Comment (AaronFriel) [reply pkg/testing/integration/program.go:297]: I don't have a better answer here either, I expect we'll want to make this the default in the future because it'll speed up examples & templates tests, tests in providers. 

Using a pointer for Maybe[bool] and an env var to set the default is a good approach for a testing harness, and we can change the default in the future after validating.

**Comment by kpitzen** [comment]
bors merge

**Comment by kpitzen** [comment]
bors merge

**Comment by kpitzen** [comment]
bors merge

**Comment by kpitzen** [comment]
bors cancel

**Comment by kpitzen** [comment]
bors merge p=-1

**Comment by kpitzen** [comment]
bors retry p=-1

**Comment by kpitzen** [comment]
bors merge
