### PR TITLE
[go/sdkgen] Remove generic ToOutput methods from non-generic go SDKs

### LINKED ISSUE #14344: Existing go generics double memory consumption during SDK compilation
### What happened?

When go generics was initially rolled out, we needed to upgrade a bunch of our runners because the `build_sdk` failed with OOM.

Profiling the aws s3 package yielded the following result:

| pulumix | Max Memory |
|---|---|
| Current | 965.75MB |
| Removed | 475.26MB |

This shows that the existing `pulumix` code doubled the memory usage during compilation.

### Example

NA

### Output of `pulumi about`

NA

### Additional context

Profile code is https://github.com/pulumi/pulumi-aws/blob/iwahbe/profile-pulumix/profile.org.

This exacerbates https://github.com/pulumi/pulumi-gcp/issues/1283.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

Fixes #14344 by removing generic `ToOutput*` methods on types when generating providers in non-generic setting . This means that we will only generate these methods when `generics` setting is `side-by-side` since `generics-only` will not touch these anyways

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by tgummerer — APPROVED** [review]

File: pkg/codegen/go/gen.go [hunk 1]
```diff
@@ -4725,11 +4750,14 @@ func generateTypes(
 		hasOutputs = true
 	}
 
+	goInfo := goPackageInfo(pkg.pkg)
 	var goImports []string
 	if hasOutputs {
 		goImports = []string{"context", "reflect"}
 		importsAndAliases["github.com/pulumi/pulumi/sdk/v3/go/pulumi"] = ""
-		importsAndAliases["github.com/pulumi/pulumi/sdk/v3/go/pulumix"] = ""
+		if goInfo.Generics == GenericsSettingSideBySide {
```
Comment (Frassle) [inline pkg/codegen/go/gen.go:4758]: Isn't this also needed for GenericsOnly?

File: pkg/codegen/go/gen.go [hunk 2]
```diff
@@ -4513,7 +4535,10 @@ func GeneratePackage(tool string, pkg *schema.Package) (map[string][]byte, error
 			pkg.getImports(resource, importsAndAliases)
 			importsAndAliases["github.com/pulumi/pulumi/sdk/v3/go/pulumi"] = ""
 			importsAndAliases[path.Join(pkg.importBasePath, pkg.internalModuleName)] = ""
-			importsAndAliases["github.com/pulumi/pulumi/sdk/v3/go/pulumix"] = ""
+			if goPkgInfo.Generics == GenericsSettingSideBySide {
```
Comment (Frassle) [inline pkg/codegen/go/gen.go:4538]: Isn't this also needed for GenericsOnly?

**Review by iwahbe — APPROVED** [review]

File: pkg/codegen/go/gen.go (hunk 2 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/go/gen.go:4538]: No because this is `genResource` when `useGenericVariant` is set to false. The code underneath continues with adding the `pulumix` import when `useGenericVariant` is set to true

File: pkg/codegen/go/gen.go (hunk 1 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/go/gen.go:4758]: We do however need some test schemas for `generics-only` 🤔

**Review by Frassle — APPROVED** [review]
