### PR TITLE
Correctly flow secretness across POJO serialization for stack outputs

### LINKED ISSUE #2862: Stack outputs show secrets parameters when parent is exported
Pulumi Devs,

Thanks for taking a look at this. I've noticed that attributes of resources that contain a secret value are not encrypted in the stack when the parent resource is exported. However, individual references to that attribute as an export _are_ encrypted. In both examples, the output is correctly masked. My expectation is that the secret never shows up in plaintext in the stack export in either case. This is almost the inverse of this issue: https://github.com/pulumi/pulumi/issues/2756.

To reproduce, setup a new typescript project (using pulumi 0.17.18 and node 12.4.0):

    pulumi new typescript --secrets-provider passphrase
    npm install --save @pulumi/random

Create a secret:

    pulumi config set --secret petPrefix 'super-pet'

Edit index.ts:

    import * as pulumi from "@pulumi/pulumi";
    import * as random from "@pulumi/random";

    const config = new pulumi.Config("secrets-issue");
    const secretPetPrefix = config.requireSecret("petPrefix");

    // This exposes the `prefix` field in the stack.
    export const mypet = new random.RandomPet("mypet", {
        prefix: secretPetPrefix,
    });

    // This correctly masks/encrypts the secret.
    export const myPetPrefix = mypet.prefix;
   
Create the stack:

    pulumi up

    Previewing update (dev):

         Type                       Name               Plan
     +   pulumi:pulumi:Stack        secrets-issue-dev  create
     +   └─ random:index:RandomPet  mypet              create

    Resources:
        + 2 to create

    Do you want to perform this update? yes
    Updating (dev):

         Type                       Name               Status
     +   pulumi:pulumi:Stack        secrets-issue-dev  created
     +   └─ random:index:RandomPet  mypet              created

    Outputs:
        myPetPrefix: "[secret]"
        mypet      : {
            id       : "[secret]-fluent-seal"
            length   : 2
            prefix   : "[secret]"
            separator: "-"
            urn      : "urn:pulumi:dev::secrets-issue::random:index/randomPet:RandomPet::mypet"
        }

    Resources:
        + 2 created

    Duration: 1s

If you inspect the stack via `pulumi stack export` (or by looking at the local stack directly), the text "super-pet" exists in plaintext as an output of `mypet` but not of `myPetPrefix`. I would expect it to be ciphertext in all cases.

    [...]
        "resources": [
            {
                "urn": "urn:pulumi:dev::secrets-issue::pulumi:pulumi:Stack::secrets-issue-dev",
                "custom": false,
                "type": "pulumi:pulumi:Stack",
                "outputs": {
                    "myPetPrefix": {
                        "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                        "ciphertext": "v1:OT/3h49G1Ca046xD:ILG2P3u3pj52qXgRd4708qEMwWE8vgSV+EL5"
                    },
                    "mypet": {
                        "id": "super-pet-fluent-seal",
                        "length": 2,
                        "prefix": "super-pet",
                        "separator": "-",
                        "urn": "urn:pulumi:dev::secrets-issue::random:index/randomPet:RandomPet::mypet"
                    }
                }
            },
     [...]

Thanks for taking a look at this issue! Let me know if I can provide any other information to assist with debugging.

### PR DESCRIPTION
**Pull request by ellismg**
Our logic to export a resource as a stack output transforms the
resource into a plain old object by eliding internal fields and then
just serializing the resource as a POJO.

The custom serialization logic we used here unwrapped an Output
without care to see if it held a secret. Now, when it does, we
continue to return an Output as the thing to be serialized and that
output is marked as a secret.

Fixes #2862

### CODE REVIEW

**Comment by ellismg** [comment]
This was a problem where our code in the language host was dropping secretness while transforming objects to be passed along as stack outputs.

**Comment by ellismg** [comment]
Ping @CyrusNajmabadi @pgavlin

File: sdk/nodejs/runtime/stack.ts [hunk 1]
```diff
@@ -104,7 +104,17 @@ async function massage(prop: any, seenObjects: Set<any>): Promise<any> {
     }
 
     if (Output.isInstance(prop)) {
-        return await massage(await prop.promise(), seenObjects);
+        // If the output itself is a secret, we don't want to lose the secretness by returning the underlying
+        // value. So instead, we massage the underlying value and then wrap it back up in an Output which is
+        // marked as secret.
+        const isSecret = await (prop.isSecret || Promise.resolve(false));
```
Comment (CyrusNajmabadi) [inline sdk/nodejs/runtime/stack.ts]: when would isSecret be not there?

File: tests/integration/secret_outputs/package.json [hunk 2]
```diff
@@ -0,0 +1,10 @@
+{
+    "name": "typescript",
+    "devDependencies": {
+        "@types/node": "latest"
+    },
+    "dependencies": {
+        "@pulumi/pulumi": "latest",
+        "@pulumi/random": "^0.5.4"
```
Comment (CyrusNajmabadi) [inline tests/integration/secret_outputs/package.json]: ideally use "dev" for pulumi/random.

Comment (ellismg) [reply tests/integration/secret_outputs/package.json]: Will actually remove both of these.  The Random usage was from before I moved to use dynamic providers to remove a dependency.

File: sdk/nodejs/runtime/stack.ts (hunk 1 above)
Comment (ellismg) [reply sdk/nodejs/runtime/stack.ts]: If the `Output` instance that is getting exported was from an older SDK which did not contain the `isSecret` property, which could happen if we have multiple `@pulumi/pulumi`'s running around.
