### PR TITLE
[codegen] Fix bug in provider schema where default int properties could not be int

### LINKED ISSUE #6469: [codegen] Invalid default of type int for integer property
The following type definition

```json
"myprovider:index:ResourceSignal": {
            "properties": {
                "Count": {
                    "type": "integer",
                    "default": 1
                },
                "Timeout": {
                    "type": "string",
                    "default": "PT5M"
                }
            },
            "type": "object"
        }
```

causes an error during schema import

```
panic: error importing schema: binding types: failed to bind type myprovider:index:ResourceSignal:
error binding default value for property "Count": invalid default of type int for integer property
```

Apparently, we only allow floats as defaults here. Changing to `1.0` makes the error go away.

### PR DESCRIPTION
**Pull request by dixler**
# Description

Fixes #6469

From the issue:

The following type definition

```json
"myprovider:index:ResourceSignal": {
            "properties": {
                "Count": {
                    "type": "integer",
                    "default": 1
                },
                "Timeout": {
                    "type": "string",
                    "default": "PT5M"
                }
            },
            "type": "object"
        }
```

causes an error during schema import

```
panic: error importing schema: binding types: failed to bind type myprovider:index:ResourceSignal:
error binding default value for property "Count": invalid default of type int for integer property
```

Apparently, we only allow floats as defaults here. Changing to `1.0` makes the error go away.

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/codegen/schema/bind.go [hunk 1]
```diff
@@ -958,35 +958,46 @@ func bindConstValue(path, kind string, value interface{}, typ Type) (interface{}
...
+			if !ok {
+				return 0, typeError("integer")
+			}
+			if math.Trunc(v) != v || v < math.MinInt32 || v > math.MaxInt32 {
+				return 0, typeError("integer")
+			}
+			return int32(v), nil
 		}
-		if math.Trunc(v) != v || v < math.MinInt32 || v > math.MaxInt32 {
+		if v < math.MinInt32 || v > math.MaxInt32 {
```
Comment (Zaid-Ajaj) [inline pkg/codegen/schema/bind.go:978]: Is this check ever needed when `v` was correctly casted to `int` from `value`?

Comment (dixler) [reply pkg/codegen/schema/bind.go:978]: Good question. That check takes a float64.

Comment (dixler) [reply pkg/codegen/schema/bind.go:978]: Yeah. I've written a test case to catch overflows/underflows that failed without it.

**Review by Zaid-Ajaj — APPROVED** [review]
LGTM

**Comment by dixler** [comment]
bors merge
