### PR TITLE
[import] Parent and Provider improvements

### LINKED ISSUE #5958: Unable to import resource with a parent
I am trying to import a resource by specifying the `type`, `name`, `id`, `parent` and `provider` but it doesn't work.

## Expected Behavior

I should be able to import the resource (or it should do nothing if it already exists).

## Current Behavior

```
❯ pulumi import 'aws:iam/user:User' jason jason --parent 'jason=urn:pulumi:prod::root::foobar:auth:AdministratorUser::jason' --provider 'admin=urn:pulumi:prod::root::pulumi:providers:aws::admin::26c1d59e-b7f9-4542-99fe-2327ff869308'
Previewing import (prod)

View Live: https://app.pulumi.com/steinybot/root/prod/previews/abcdef

     Type                 Name       Plan
     pulumi:pulumi:Stack  root-prod

Resources:
    33 unchanged

Do you want to perform this import? yes
Importing (prod)

View Live: https://app.pulumi.com/steinybot/root/prod/updates/46

   Type  Name  Status

Outputs:
    ...

Resources:
    33 unchanged

Duration: 1s

error: no name for provider urn:pulumi:prod::root::foobar:auth:AdministratorUser::jason
```

I don't know what it means that there is "no name for provider".

I tried using a different name for the provider:
```
❯ pulumi import 'aws:iam/user:User' jason jason --parent 'jason=urn:pulumi:prod::root::foobar:auth:AdministratorUser::jason' --provider 'jason=urn:pulumi:prod::root::pulumi:providers:aws::admin::26c1d59e-b7f9-4542-99fe-2327ff869308'
Previewing import (prod)

View Live: https://app.pulumi.com/steinybot/root/prod/previews/abcdef

     Type                 Name       Plan       Info
     pulumi:pulumi:Stack  root-prod             1 error
 =   └─ aws:iam:User      jason      import     1 error

Diagnostics:
  pulumi:pulumi:Stack (root-prod):
    error: preview failed

  aws:iam:User (jason):
    error: Preview failed: unknown parent 'urn:pulumi:prod::root::pulumi:providers:aws::admin::26c1d59e-b7f9-4542-99fe-2327ff869308' for resource 'urn:pulumi:prod::root::pulumi:providers:aws$aws:iam/user:User::jason'
```

I don't know why it is now saying that the provider is an unknown parent. Seems like somehow the parent and provider are getting mixed up.

Just to see what would happen I tried reversing them:
```
❯ pulumi import 'aws:iam/user:User' jason jason --provider 'jason=urn:pulumi:prod::root::foobar:auth:AdministratorUser::jason' --parent 'admin=urn:pulumi:prod::root::pulumi:providers:aws::admin::26c1d59e-b7f9-4542-99fe-2327ff869308'
Previewing import (prod)

View Live: https://app.pulumi.com/steinybot/root/prod/previews/abcdef

     Type                 Name       Plan
     pulumi:pulumi:Stack  root-prod  running
panic: fatal: invalid module in type: expected 'pulumi:providers', got 'foobar:auth'

goroutine 79 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/private/tmp/pulumi-20201213-74568-1in5v9y/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.AssertNoError(0x5be05a0, 0xc000dabf00)
	/private/tmp/pulumi-20201213-74568-1in5v9y/sdk/go/common/util/contract/assert.go:40 +0xe5
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*importer).registerProviders(0xc0001e5b00, 0x5c14c20, 0xc00067b0c0, 0xc00167ae80, 0x35, 0x100, 0x0)
	/private/tmp/pulumi-20201213-74568-1in5v9y/pkg/resource/deploy/import.go:188 +0xe3f
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*importer).importResources(0xc0001e5b00, 0x5c14c20, 0xc00067b0c0, 0xc000fdf540, 0xfc65a58)
	/private/tmp/pulumi-20201213-74568-1in5v9y/pkg/resource/deploy/import.go:286 +0x105
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*deploymentExecutor).importResources(0xc00000ff00, 0x5c14ce0, 0xc0001f6690, 0xfc65a58, 0xc000fc7400, 0x7fffffff, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20201213-74568-1in5v9y/pkg/resource/deploy/deployment_executor.go:450 +0x167
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*deploymentExecutor).Execute(0xc00000ff00, 0x5c14ce0, 0xc0001f6690, 0xfc65a58, 0xc000fc7400, 0x7fffffff, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20201213-74568-1in5v9y/pkg/resource/deploy/deployment_executor.go:138 +0x1247
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*Deployment).Execute(...)
	/private/tmp/pulumi-20201213-74568-1in5v9y/pkg/resource/deploy/deployment.go:383
github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run.func1(0x5c1f880, 0xc000fc7400, 0xc000fc7a40, 0x5c14ce0, 0xc0001f6690, 0xc0001f6601, 0xc0001cf900, 0xc00010f7a0)
	/private/tmp/pulumi-20201213-74568-1in5v9y/pkg/engine/deployment.go:251 +0x267
created by github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run
	/private/tmp/pulumi-20201213-74568-1in5v9y/pkg/engine/deployment.go:237 +0x306
```

## Steps to Reproduce

```
import * as pulumi from "@pulumi/pulumi";
import {Input, Output} from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const config = new pulumi.Config();

const accountID = config.require("account-id");

const provider = new aws.Provider("admin", {
    allowedAccountIds: [accountID],
    region: aws.config.requireRegion(),
});

const opts = { provider: provider, protect: true };

interface Tagged {
    readonly tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

function tagged<A extends Tagged>(a: A): A {
    const oldTags = a.tags ?? {};
    const newTags = {
        ...oldTags,
        "pulumi:Project": pulumi.getProject(),
        "pulumi:Stack": pulumi.getStack(),
    };
    return { ...a, tags: newTags };
}

const administrators = new aws.iam.Group("Administrators", {
    name: "Administrators"
}, opts);

new aws.iam.GroupPolicyAttachment("IAMFullAccess", {
    group: administrators.name,
    policyArn: "arn:aws:iam::aws:policy/IAMFullAccess",
}, opts);

new aws.iam.GroupPolicyAttachment("AWSOrganizationsFullAccess", {
    group: administrators.name,
    policyArn: "arn:aws:iam::aws:policy/AWSOrganizationsFullAccess",
}, opts);

class AdministratorUser extends pulumi.ComponentResource {
    constructor(name: string, opts?: pulumi.InvokeOptions) {
        super("foobar:auth:AdministratorUser", name, {}, opts);

        const childOpts = { ...opts, parent: this };

        const user = new aws.iam.User(name, {
            name: name
        }, childOpts);

        new aws.iam.UserGroupMembership("Administrator", {
            user: user.name,
            groups: [
                administrators.name
            ],
        }, childOpts);

        this.registerOutputs();
    }
}

new AdministratorUser("jason", opts)
```

The resource already exists in the stack state. Not sure if that is relevant but I would still expect the import to succeed (or do nothing):
```
{
                "urn": "urn:pulumi:prod::root::foobar:auth:AdministratorUser$aws:iam/user:User::jason",
                "custom": true,
                "id": "jason",
                "type": "aws:iam/user:User",
                "inputs": {
                    "__defaults": [
                        "forceDestroy",
                        "path"
                    ],
                    "forceDestroy": false,
                    "name": "jason",
                    "path": "/",
                    "tags": {}
                },
                "outputs": {
                    "arn": "arn:aws:iam::12345:user/jason",
                    "forceDestroy": false,
                    "id": "jason",
                    "name": "jason",
                    "path": "/",
                    "tags": {},
                    "uniqueId": "AIDASFACSFJBHVIOLWK26"
                },
                "parent": "urn:pulumi:prod::root::foobar:auth:AdministratorUser::jason",
                "protect": true,
                "provider": "urn:pulumi:prod::root::pulumi:providers:aws::admin::26c1d59e-b7f9-4542-99fe-2327ff869308",
                "propertyDependencies": {
                    "name": null
                }
            }
```

### PR DESCRIPTION
**Pull request by lukehoban**
Allow passing raw URN instead of `name=URN` for parent and provider, defaulting name to `parent` and `provider` respectively.

Report an error if the names of the parent and provider are the same (instead of silently overwriting the parent with the provider).

Provide better error messages if the provided URN is not a URN - specifically if it is a provider reference.

Fix up an error message that included a parent instead of provider URN.

Also update the help text with some additional examples.

Fixes #5958.
Contributes to #10288.

### CODE REVIEW

**Review by iwahbe — APPROVED** [review]
Looks good. LGTM!

File: pkg/cmd/pulumi/import.go [hunk 1]
```diff
@@ -84,24 +92,29 @@ func makeImportFile(
 	if parentSpec != "" {
 		parentName, parentURN, err := parseResourceSpec(parentSpec)
 		if err != nil {
-			return importFile{}, fmt.Errorf("could not parse parent spec '%v': %w", parentSpec, err)
+			parentName = "parent"
+			parentURN = resource.URN(parentSpec)
```
Comment (Frassle) [inline pkg/cmd/pulumi/import.go:96]: Shouldn't this check parentSpec is actually a URN?

**Review by Frassle — APPROVED** [review]

**Comment by AaronFriel** [comment]
bors merge
