### PR TITLE
Special case the error specifing app.pulumi.com

### LINKED ISSUE #9410: poor error message when using pulumi login app.pulumi.com
_orginally reported through community slack_

## problem
a new user in community slack was using `pulumi login https://app.pulumi.com/<individual account-name>` instead of `pulumi login`
which first requests a token, and then results in the error `error: problem logging in: getting user info from https://app.pulumi.com/susanev: unmarshalling response object: invalid character '<' looking for beginning of value`

this error is unhelpful, and does not give information to the user that will help them fix the problem.

currently, folks need to only use `pulumi login` when using the service as their backend.

## thoughts & questions
- would it be possible to assume they mean pulumi login in this case? or support people using app.pulumi.com in this case?
    - possibly identify if they are using app.pulumi.com instead of api.pulumi.com
- if not, can we respond with a better error message letting them know to use `pulumi login`?

## ref
[internal slack convo](https://pulumi.slack.com/archives/C9SGX9QA1/p1650038927550389)
[community slack convo](https://pulumi-community.slack.com/archives/C01PF3E1B8V/p1650038002997409)

### PR DESCRIPTION
**Pull request by iwahbe**
# Description

Fixes #9410

I think we should just respond with an error message here. If you type `https://api.pulumi.com` then everything works as expected. We shouldn't perform the automatic conversion of `app` to `api`. 

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/cmd/pulumi/login.go [hunk 1]
```diff
@@ -120,6 +120,10 @@ func newLoginCmd() *cobra.Command {
 				if err != nil {
 					return fmt.Errorf("could not determine current cloud: %w", err)
 				}
+			} else if url := strings.TrimPrefix(strings.TrimPrefix(
+				cloudURL, "https://"), "http://"); strings.HasPrefix(url, "app.pulumi.com/") {
```
Comment (Frassle) [inline pkg/cmd/pulumi/login.go:124]: Wonder if we should just do contains check for pulumi.com? Would also catch if people tried to do like `pulumi login pulumi.com`

File: pkg/cmd/pulumi/login.go [hunk 2]
```diff
@@ -120,6 +120,10 @@ func newLoginCmd() *cobra.Command {
...
+				return fmt.Errorf("%s is not a valid self-hosted backend, "+
+					"use `pulumi login` without any arguments to log into the Pulumi service backend", cloudURL)
```
Comment (susanev) [inline pkg/cmd/pulumi/login.go:126]: this is kinda nity, so feel free to ignore if you feel strongly

```suggestion
					"use only `pulumi login` to log into the Pulumi service backend", cloudURL)
```

**Review by susanev — APPROVED** [review]
