### PR TITLE
retry pip install a few times

### LINKED ISSUE #22775: Flaky: Windows tests/integration fails with PyPI "Content-Type: Unknown"
## Symptom

Windows `tests/integration` shards intermittently fail when `pip install` requests against `https://pypi.org/simple/<pkg>/` are rejected with:

```
WARNING: Skipping page https://pypi.org/simple/<pkg>/ because the GET request got Content-Type: Unknown.
The only supported Content-Types are application/vnd.pypi.simple.v1+json,
application/vnd.pypi.simple.v1+html, and text/html
ERROR: Could not find a version that satisfies the requirement <pkg> (from versions: none)
ERROR: No matching distribution found for <pkg>
```

The test then fails at `integration_util_test.go:214` (or equivalent) with
`Received unexpected error: copying test to temp dir : Failed to prepare ... exit status 1`.

## Observed instances (2026-04-29)

| PR | Job | Failing test | Package pip couldn't fetch |
|---|---|---|---|
| #22725 (run 1) | [tests/integration 7/8 win/current](https://github.com/pulumi/pulumi/actions/runs/25122947022/job/73629681509) | `TestConstructMethodsResourcesPython` | `debugpy~=1.8.7` |
| #22725 (rerun)  | [tests/integration 7/8 win/current](https://github.com/pulumi/pulumi/actions/runs/25122947022/job/73638196009) | `TestPythonResourceArgs` | `setuptools` |
| #22766 | [tests/integration 3/8 win/current](https://github.com/pulumi/pulumi/actions/runs/25121308236/job/73624253378) | `TestPythonComponentProviderRun/nodejs` | `hatchling` |

The three runs hit three different packages, ruling out a single upstream package release as the cause.

## Environment

- Runner: `windows-latest`
- Python: 3.14.4 (`C:\hostedtoolcache\windows\Python\3.14.4\x64`)
- pip: 26.0.1

## Related

- #17638 — same outer symptom (`Failed to prepare temp dir`) but with venv-creation as the inner failure rather than pip install. This is a different inner cause under that umbrella.

Discovered while shepherding #22725.

### PR DESCRIPTION
**Pull request by tgummerer**
Lately we've been seeing a bit of flakyness from `pip install` in CI. See also https://github.com/pulumi/pulumi/issues/22775.

This seems like it's CDN issues, as we get the wrong header. Retry the command a few times hoping that the issues will go away in subsequent requests.  This will also affect the product, but I think retrying the install when it fails doesn't hurt, and might help in some cases, so it's probably a good thing for that as well.

Fixes https://github.com/pulumi/pulumi/issues/22775

### CODE REVIEW

File: sdk/python/toolchain/pip.go [hunk 1]
```diff
@@ -482,32 +482,44 @@ func InstallDependencies(ctx context.Context, cwd, venvDir string, useLanguageVe
...
-		pipCmd.Env = ActivateVirtualEnv(os.Environ(), venvDir)
-
-		if showOutput {
-			// Show stdout/stderr output.
-			pipCmd.Stdout = infoWriter
-			pipCmd.Stderr = errorWriter
-			if err := pipCmd.Run(); err != nil {
-				return fmt.Errorf("%s via '%s': %w", errorMsg, strings.Join(pipCmd.Args, " "), err)
+		// Retry up to 3 times to handle transient PyPI issues (e.g. CDN
+		// returning unexpected Content-Type responses).
```
Comment (Frassle) [inline sdk/python/toolchain/pip.go:485]: Bit worried about re-running an install 3 times because the user actually just has the wrong requirements.txt :frowning_face: is there any way we can filter this to errors that we recognise and know we should always retry regardless of if were running in CI or locally.

Comment (tgummerer) [reply sdk/python/toolchain/pip.go:485]: Yeah, I guess if they have a massive `requirements.txt` that is broken this might end up wasting a lot more time if we retry this.  Let me have a look how we can be more specific.

Comment (tgummerer) [reply sdk/python/toolchain/pip.go:485]: Made it so we only exclude the specific pattern we've been seeing, but we can easily add more as we see them.

**Review by Frassle — APPROVED** [review]
