### PR TITLE
Append debug flags after subcommand to account for non global flags like "debug"

### LINKED ISSUE #15305: Enabling the Debug option in the Go Automation API causes error
### What happened?

When using the Go Automation API the following configuration results in an error:

```
_, err := s.Refresh(context.TODO(), optrefresh.DebugLogging(debug.LoggingOptions{Debug: true}))
```

The error is `unknown flag: --debug`

This problem seems to be caused by this line https://github.com/pulumi/pulumi/blob/master/sdk/go/auto/debug/debuglogging.go#L40

```
if debugLogOpts.Debug {
    sharedArgs = append(sharedArgs, "--debug")
}
```

Here `--debug` is being added as a global flag, but it's actually not a global flag and is specific to the few commands that support `--debug`. Attempting to use it as a global flag causes the error.

### Example

main.go
```
package main

import (
	"context"
	"log"
	"os"

	"github.com/pulumi/pulumi/sdk/v3/go/auto"
	"github.com/pulumi/pulumi/sdk/v3/go/auto/debug"
	"github.com/pulumi/pulumi/sdk/v3/go/auto/optrefresh"
	"github.com/pulumi/pulumi/sdk/v3/go/auto/optup"
)

func main() {

	s, err := auto.UpsertStackLocalSource(context.TODO(), "test", "./testdata")
	if err != nil {
		log.Fatalf("unable to get stack: %v\n", err)
	}

	_, err = s.Refresh(context.TODO(), optrefresh.DebugLogging(debug.LoggingOptions{Debug: true}))
	if err != nil {
		log.Fatalf("unable to referesh: %v\n", err)
	}

	streamer := optup.ProgressStreams(os.Stdout)

	_, err = s.Up(context.TODO(), optup.Diff(), streamer, optup.DebugLogging(debug.LoggingOptions{Debug: true}))
	if err != nil {
		log.Fatalf("unable to update: %v\n", err)
	}

}
```

testdata/Pulumi.yaml
```
name: empty-stack
runtime: yaml
description: Stack for tests to reference
```

testdata/Pulumi.test.dev
```
config: {}
```

### Output of `pulumi about`

```
CLI          
Version      3.103.1
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME  VERSION
yaml  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in yaml

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/<REDACTED>
User           <REDACTED>
Organizations  <REDACTED>
Token type     personal

No dependencies found

Pulumi locates its logs in /tmp by default

```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by brandonpollack23**
Append debug flags after subcommand to account for non global flags like "debug"

Fixes #15305

### CODE REVIEW

**Review by tgummerer — APPROVED** [review]
Can we add a test for this?

File: sdk/go/auto/stack.go [hunk 1]
```diff
@@ -370,7 +370,6 @@ func (s *Stack) Up(ctx context.Context, opts ...optup.Option) (UpResult, error)
 	bufferSizeHint := len(upOpts.Replace) + len(upOpts.Target) + len(upOpts.PolicyPacks) + len(upOpts.PolicyPackConfigs)
 	sharedArgs := slice.Prealloc[string](bufferSizeHint)
 
-	sharedArgs = debug.AddArgs(&upOpts.DebugLogOpts, sharedArgs)
 	if upOpts.Message != "" {
 		sharedArgs = append(sharedArgs, fmt.Sprintf("--message=%q", upOpts.Message))
```
Comment (tgummerer) [inline sdk/go/auto/stack.go:374]: Hrm this and all the args below are also not global args.  Do they need a similar treatment?
