### PR TITLE
[PCL] annotate expressions under invoke calls with their associated schema types

### LINKED ISSUE #10914: pulumi convert to python doesn't populate argument in ec2.get_ami
### What happened?

I am converting a YAML program to Python using `pulumi convert`. The arguments in `Function: aws:ec2:getAmi` do not successfully populate in the python conversion. This is not a problem converting to TypeScript. 

### Steps to reproduce

Run `pulumi convert --out ../../test_vm_python --language python` against

```
name: vm-aws-yaml
description: A YAML program to create a virtual machine on AWS
runtime: yaml

template: 
    description: A YAML program to create a virtual machine on AWS
    config:
        aws:region:
            description: The AWS region to deploy into
            default: us-west-2
        instanceType:
            description: Instance type of EC2
            default: t2.micro

configuration:
    instanceType:
        type: String
        default: t2.micro

resources:  
    # Create EC2 Security Group
    secGroup:
        type: aws:ec2:SecurityGroup
        properties:
            description: Enable HTTP access
            ingress:
                - fromPort: 80
                  toPort: 80
                  protocol: tcp
                  cidrBlocks: 
                    - 0.0.0.0/0
            tags:
                Name: web-secgrp
    # Create EC2 server
    server:
        type: aws:ec2:Instance
        properties:
            instanceType: ${instanceType}
            vpcSecurityGroupIds: 
                - ${secGroup}
            userData: ${userData}
            ami: ${ami}
            tags:
                Name: web-server-www

variables:
    # Create EC2 AMI
    ami:
        Fn::Invoke:
            Function: aws:ec2:getAmi
            Arguments:
                filters:
                    - name: name
                      values: 
                        - "amzn-ami-hvm-*"
                owners: 
                    - "137112412989"
                mostRecent: true
            Return: id    
    # User data to start a HTTP server in the EC2 instance
    userData: "#!/bin/bash
            
            echo \"Hello, World from Pulumi!\" > index.html
            
            nohup python -m SimpleHTTPServer 80 &"
            

outputs:
    # Export the public IP and DNS
    publicIP: ${server.publicIp}
    publicDNS: ${server.publicDns}

```

### Expected Behavior

I expected this code to be generated

`ami = aws.ec2.get_ami(most_recent=True,
                  owners=["137112412989"],
                  filters=[aws.GetAmiFilterArgs(name="name", values=["amzn-ami-hvm-*"])])`

### Actual Behavior

This is generated instead with non of the arguments filled

`ami = aws.ec2.get_ami().id`

### Output of `pulumi about`

```
CLI          
Version      3.40.2
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME  VERSION
aws   unknown
yaml  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in yaml

Current Stack: dev

TYPE                                 URN
pulumi:pulumi:Stack                  urn:pulumi:dev::vm-aws-yaml::pulumi:pulumi:Stack::vm-aws-yaml-dev
pulumi:providers:aws                 urn:pulumi:dev::vm-aws-yaml::pulumi:providers:aws::default
aws:ec2/securityGroup:SecurityGroup  urn:pulumi:dev::vm-aws-yaml::aws:ec2/securityGroup:SecurityGroup::secGroup
aws:ec2/instance:Instance            urn:pulumi:dev::vm-aws-yaml::aws:ec2/instance:Instance::server


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aaronkao
User           aaronkao
Organizations  aaronkao, kao, upstarts, demo

No dependencies found

Pulumi locates its logs in /tmp by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

Fixes #10914 (issue)

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
This will potentially help clean up some of the hacks in dotnet program-gen that workaround non-annotated object expressions.

File: pkg/codegen/pcl/invoke.go [hunk 1]
```diff
@@ -44,6 +44,56 @@ func getInvokeToken(call *hclsyntax.FunctionCallExpr) (string, hcl.Range, bool)
...
+// for invoke calls that didn't have type annotations.
+//
+// this function will recursively annotate the properties of objects
+// that are nested within the object expression type.
+func annotateObjectProperties(modelType model.Type, schemaType schema.Type, topLevelAnnotate bool) {
+	if optionalType, ok := schemaType.(*schema.OptionalType); ok {
+		schemaType = optionalType.ElementType
+	}
+
+	if objectType, ok := modelType.(*model.ObjectType); ok {
```
Comment (iwahbe) [inline pkg/codegen/pcl/invoke.go:58]: Since we don't expect more than one of these `if _, ok := modelType.(_); ok` to trigger, a switch statement would be cleaner.
```suggestion
switch modelType := modelType.(type) {
case *model.ObjectType:
```

File: pkg/codegen/pcl/invoke.go [hunk 2]
```diff
@@ -44,6 +44,56 @@ func getInvokeToken(call *hclsyntax.FunctionCallExpr) (string, hcl.Range, bool)
...
+
+	if tupleType, ok := modelType.(*model.TupleType); ok {
+		if schemaArrayType, ok := schemaType.(*schema.ArrayType); ok {
+			underlyingSchemaArrayType := schemaArrayType.ElementType
+			elementTypes := tupleType.ElementTypes
+			for _, elemType := range elementTypes {
+				annotateObjectProperties(elemType, underlyingSchemaArrayType, true)
+			}
+		}
+	}
```
Comment (iwahbe) [inline pkg/codegen/pcl/invoke.go:94]: Shouldn't we handle `model.Union` types here?

File: pkg/codegen/python/gen_program_expressions.go [hunk 3]
```diff
@@ -318,31 +318,38 @@ func (g *generator) GenFunctionCallExpression(w io.Writer, expr *model.FunctionC
...
+
+		if funcCall, ok := expr.Args[1].(*model.FunctionCallExpression); ok {
+			if argsObject, ok := funcCall.Args[0].(*model.ObjectConsExpression); ok {
+				genFuncArgs(argsObject)
 			}
 		}
 
+		if argsObject, ok := expr.Args[1].(*model.ObjectConsExpression); ok {
+			genFuncArgs(argsObject)
+		}
```
Comment (iwahbe) [inline pkg/codegen/python/gen_program_expressions.go:351]: Switch statements make your intent much clearer when dealing with mutually exclusive if blocks.
```suggestion
                switch arg := expr.Args[1].(type) {
                case *model.FucntionCallExpression:
			if argsObject, ok := arg.Args[0].(*model.ObjectConsExpression); ok {
				genFuncArgs(argsObject)
			}
		case *model.ObjectConsExpression:
			genFuncArgs(arg)
		}
```

File: pkg/codegen/pcl/invoke.go [hunk 4]
```diff
@@ -44,6 +44,56 @@ func getInvokeToken(call *hclsyntax.FunctionCallExpr) (string, hcl.Range, bool)
 	return literal.Val.AsString(), call.Args[0].Range(), true
 }
 
+// annotateObjectProperties annotates the properties of an object expression with the types of the corresponding
+// properties in the schema. This is used to provide type information
+// for invoke calls that didn't have type annotations.
+//
+// this function will recursively annotate the properties of objects
+// that are nested within the object expression type.
+func annotateObjectProperties(modelType model.Type, schemaType schema.Type, topLevelAnnotate bool) {
```
Comment (iwahbe) [inline pkg/codegen/pcl/invoke.go:53]: I don't entirely understand what `topLevelAnnotate` does. It looks like it is possible for multiple objects in a tree to be annotated. Is it a way to skip annotating the first `model.Type` encountered iff that is an `model.ObjectType`?

Comment (Zaid-Ajaj) [reply pkg/codegen/pcl/invoke.go]: Indeed the idea was to skip the top-level object but now I've removed this `topLevelAnnotate` parameter entirely and refactored the code with switch statements ✅

File: pkg/codegen/python/gen_program_expressions.go (hunk 3 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/python/gen_program_expressions.go]: Done ✅

File: pkg/codegen/pcl/invoke.go (hunk 2 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/pcl/invoke.go:103]: I've added support to it like this: 
```go
	case *model.UnionType:
		if schemaUnionType, ok := schemaType.(*schema.UnionType); ok {
			modelElementTypes := arg.ElementTypes
			schemaElementTypes := schemaUnionType.ElementTypes
			if len(modelElementTypes) == len(schemaElementTypes) {
				// annotate each type inside the model union with its corresponding
				// schema type from the schema union.
				// Assuming here that they match based on the index (ordered), is this correct?
				for i := range modelElementTypes {
					annotateObjectProperties(modelElementTypes[i], schemaElementTypes[i])
				}
			}
		}
	}
```
but I am not sure my assumption is correct here that schema union element types and model union element types are ordered so that their indexes match. Thoughts?

Comment (iwahbe) [reply pkg/codegen/pcl/invoke.go:103]: I'm not aware of any guarantee of ordering between model union elements and schema union elements. Keep in mind that `*model.Union` is not isomorphic to `*schema.Union`. For example `schema.Option{Element: T}` is expressed as `model.Union{Elements: [None, T]}`. If nothing else, this needs to be handled during the optional check at the beginning of `annotateObjectProperties`. My understanding is that we are allowed to squash model unions, so that `Union[foo, Union[None, bar]]` should be equivalent to `Union[foo, None, bar]`. Schema unions are more limited, since they need to be translatable into `go`, which doesn't have union types.

Comment (Zaid-Ajaj) [reply pkg/codegen/pcl/invoke.go:103]: @iwahbe Alright, I'll make a TODO issue out of handling unions and tackle it later with a specific test schema for these cases because I really haven't seen any invokes that have unions as input but I would like to get this fix merged and use it in #10976

Comment (iwahbe) [reply pkg/codegen/pcl/invoke.go:93]: In that case I would change the union handling to collapse `Union[None, T]` to `T` and punt on the rest. If we aren't going to address unions here, we shouldn't annotate when we are unsure.

File: pkg/codegen/pcl/invoke.go [hunk 5]
```diff
@@ -44,6 +44,55 @@ func getInvokeToken(call *hclsyntax.FunctionCallExpr) (string, hcl.Range, bool)
 	return literal.Val.AsString(), call.Args[0].Range(), true
 }
 
+// annotateObjectProperties annotates the properties of an object expression with the types of the corresponding
+// properties in the schema. This is used to provide type information
+// for invoke calls that didn't have type annotations.
+//
+// this function will recursively annotate the properties of objects
```
Comment (iwahbe) [inline pkg/codegen/pcl/invoke.go:51]: Nit: capitalization consistency
```suggestion
// This function will recursively annotate the properties of objects
```

**Review by iwahbe — APPROVED** [review]
Except for [this comment](https://github.com/pulumi/pulumi/pull/10958/files#r992563680) on unions, it looks good.

File: pkg/codegen/pcl/invoke.go (hunk 2 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/pcl/invoke.go:101]: @iwahbe I've implemented it like this:
```go
case *model.UnionType:
	// sometimes optional schema types are represented as unions: None | T
	// in this case, we want to collapse the union and annotate the underlying type 
	if len(arg.ElementTypes) == 2 && arg.ElementTypes[0] == model.NoneType {
		annotateObjectProperties(arg.ElementTypes[1], schemaType)
	} else if len(arg.ElementTypes) == 2 && arg.ElementTypes[1] == model.NoneType {
		annotateObjectProperties(arg.ElementTypes[0], schemaType)
	} else {
		// TODO https://github.com/pulumi/pulumi/issues/10993
		// We need to handle the case where the schema type is a union type.
	}
}
```

**Comment by Zaid-Ajaj** [comment]
bors merge

**Comment by Zaid-Ajaj** [comment]
bors retry
