### PR TITLE
Look for language plugins next to `pulumi` when probing

### LINKED ISSUE #1956: error: failed to load language plugin nodejs
Trying the kubernetes "getting started" example. I did "pulumi new", then chose kubernetes-typescript. Didn't modify anything, getting this error whatever I do:
"error: failed to load language plugin nodejs: no language plugin 'nodejs' found in the workspace or on your $PATH"
Nothing else is printed even if setting verbose logging (v=3)

Nodejs: 8.10.0
typescript 3.0.3
pulumi: v0.15.2

### PR DESCRIPTION
**Pull request by ellismg**
When launching plugins today, `pulumi` looks in two places:

1. It looks to see if the plugin in on the $PATH and if so, uses
   it. This makes it easy to force a specific version of a resource
   provider to be used and is what happens at development time (since
   resource providers make their way onto $PATH via GOBIN).

2. If the above fails, it looks in the "plugin cache" in
   `~/.pulumi/plugins`. This is the location that `pulumi plugin
   install` places plugins.

Unlike resource provider plugins, we don't yet deliver language
plugins via `pulumi plugin install` so the language provider plugins
must be on the `$PATH` to be found. This is okay, because when we ship
the SDK, we include the executables next to `pulumi` itself.

However, if a user chooses to not put `pulumi` on their $PATH, or they
do but it is a symlink to the real `pulumi` binary installed
somewhere, we'd fail to find the language plugins, since they would
not be on the `$PATH`

To address this, when probing for language plugins, also consider
binaries next to the currently running `pulumi` process.

Fixes #1956

### CODE REVIEW

File: pkg/workspace/plugins.go [hunk 1]
```diff
@@ -330,6 +330,28 @@ func GetPluginPath(kind PluginKind, name string, version *semver.Version) (strin
...
+	// At some point in the future, language plugins will be located in the plugin cache, just like regular plugins
+	// (see pulumi/pulumi#956 for some of the reasons why this isn't the case today). For now, they ship next to the
+	// `pulumi` binary. While we encourage this folder to be on the $PATH (and so the check above would have found
+	// the language plugin) it's possible someone is running `pulumi` with an explicit path on the command line or
+	// has done symlink magic such that `pulumi` is on the path, but the language plugins are not. So, if possible,
+	// look next to the instance of `pulumi` that is running to find this language plugin.
+	if kind == LanguagePlugin {
+		exePath, exeErr := os.Executable()
+		if exeErr == nil {
+			fullPath, fullErr := filepath.EvalSymlinks(exePath)
```
Comment (swgillespie) [inline pkg/workspace/plugins.go]: Reading the docs:

> If a symlink was used to start the process, depending on the operating system, the result might be the symlink or the path it pointed to.

yikes...

File: pkg/workspace/plugins.go [hunk 2]
```diff
@@ -330,6 +330,28 @@ func GetPluginPath(kind PluginKind, name string, version *semver.Version) (strin
...
+			if fullErr == nil {
+				candidate := filepath.Join(filepath.Dir(fullPath), filename)
+				if _, err := os.Stat(candidate); err == nil {
```
Comment (swgillespie) [inline pkg/workspace/plugins.go]: `!os.IsNotExist(err)`?

Also should we try and verify that this thing is executable before we claim victory?

Comment (ellismg) [reply pkg/workspace/plugins.go]: > `!os.IsNotExist(err)`?

Not 100% sure here.  I'm checking to ensure that err was nil, so any error from stat would cause us to ignore this candidate.  I can't think of a way to slice the error space that makes it possible to do something reasonable for some class of errors but not others.

> Also should we try and verify that the candidate is executable before we claim victory?

Sure.

**Comment by ellismg** [comment]
@swgillespie force pushed a change to consider the mode of the file.  Will need to confirm this behave as expected on Windows, but if you don't see any more comments from me, assume that it did work.  Let me know if you have any other feedback.

**Comment by swgillespie** [comment]
> Let me know if you have any other feedback.

Nope, LGTM!
