### PR TITLE
Fix an issue where plugin install would fail on windows

### LINKED ISSUE #2217: Upgraded to pulumi v0.16.4 and node v11.2. Doing `pulumi new` failing on `npm install`
Here is a transcript.

[log.txt](https://github.com/pulumi/pulumi/files/2590469/log.txt)

### PR DESCRIPTION
**Pull request by ellismg**
The issue is related to this code:

https://github.com/pulumi/pulumi/blob/v0.16.4/pkg/workspace/plugins.go#L155-L195

Note that we use `defer` to ensure we close our handle to the file we
are unpacking when we encounter a file in the tarball.  However, the
defers don't run until the containing function ends, so when we go to
do the rename, or process still has a bunch of open file handles, which
prevents the directory from being renamed because it is "in use".

By doing all of the work in an anonymous function, we ensure that the
defer statements run before we go to rename the directory

Fixes #2217

### CODE REVIEW

File: tests/integration/integration_test.go [hunk 1]
```diff
@@ -214,13 +214,12 @@ func TestStackOutputsJSON(t *testing.T) {
 	e.RunCommand("pulumi", "login", "--cloud-url", e.LocalURL())
 	e.RunCommand("pulumi", "stack", "init", "stack-outs")
 	e.RunCommand("pulumi", "up", "--non-interactive", "--skip-preview")
-	stdout, stderr := e.RunCommand("pulumi", "stack", "output", "--json")
+	stdout, _ := e.RunCommand("pulumi", "stack", "output", "--json")
```
Comment (pgavlin) [inline tests/integration/integration_test.go]: Is this change necessary?

Comment (ellismg) [reply tests/integration/integration_test.go]: Unfortunately, for now, it is.  See: he commit message of ed804925fd2edb5cb11e53ac5a50848d07459c9f for the sad justification.

I should be able to undo this shortly, but for now it's the quickest way to unblock the release.
