### PR TITLE
[state] Fix pulumi state move snapshot integrity when copied providers depend on source-only resources

### LINKED ISSUE #22093: pulumi state move crashes
### What happened?

Tried to move resource from one project to another and got error:
```
error: The Pulumi CLI encountered a snapshot integrity error. This is a bug!
```

### Example

```
pulumi state move --source {source project} --dest {dest project} {resource_urn}
```

### Output of `pulumi about`

CLI
Version      3.224.0
Go Version   go1.26.0
Go Compiler  gc

Host
OS       darwin
Version  26.3
Arch     arm64

### Additional context

Pulumi Version:    v3.224.0
Command:           pulumi state move --source {source project} --dest {dest project} {resource_urn}
Env Vars:          (none)
Error:             failed to verify integrity of destination snapshot: resource urn:pulumi:main::{dest project}::pulumi:providers:aws::network_provider's dependency urn:pulumi:main::{dest project}::{resource} refers to missing resource

This is a bug! We would appreciate a report: https://github.com/pulumi/pulumi/issues/

Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.26.0/libexec/src/runtime/debug/stack.go:26 +0x64
github.com/pulumi/pulumi/sdk/v3/go/common/snapshot.SnapshotIntegrityErrorf({0x105fdd7a8, 0x36}, {0x3fa985b06e60?, 0x24?, 0x10800d600?})
        /private/tmp/pulumi-20260226-5643-nv6rx8/sdk/go/common/snapshot/integrity.go:205 +0x80
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0x3fa9831b8000)
        /private/tmp/pulumi-20260226-5643-nv6rx8/pkg/resource/deploy/snapshot.go:673 +0xfd4
github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/state.(*stateMoveCmd).Run(0x3fa981af4a50, {0x108375c60, 0x10881c4e0}, {0x136989640, 0x3fa981902480}, {0x136989640, 0x3fa9818bc630}, {0x3fa981af4f00, 0x1, 0x5}, ...)
        /private/tmp/pulumi-20260226-5643-nv6rx8/pkg/cmd/pulumi/state/state_move.go:462 +0x235c
github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/state.newStateMoveCommand.func1(0x3fa98163cf08?, {0x3fa981af4f00, 0x1, 0x5})
        /private/tmp/pulumi-20260226-5643-nv6rx8/pkg/cmd/pulumi/state/state_move.go:124 +0x2a0
github.com/spf13/cobra.(*Command).execute(0x3fa98163cf08, {0x3fa981af4eb0, 0x5, 0x5})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1015 +0x814
github.com/spf13/cobra.(*Command).ExecuteC(0x3fa981b27508)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1148 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1071
main.main()
        /private/tmp/pulumi-20260226-5643-nv6rx8/pkg/cmd/pulumi/main.go:64 +0x60

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by RohitYandigeri**
## Summary

Fixes #22093.

`pulumi state move` could fail with a destination snapshot integrity error when a copied provider resource still carried dependencies on resources that remained in the source stack.

Example failure:
`failed to verify integrity of destination snapshot: resource ... pulumi:providers:... dependency ... refers to missing resource`

## Root cause

During state move, providers are copied from source to destination when needed by moved resources.  
If a copied provider had `Dependencies` pointing to resources that were **not** moved, those dependencies were rewritten into destination URNs and became dangling references.

## What changed

- In `pkg/cmd/pulumi/state/state_move.go`:
  - When copying a provider (`r := res.Copy()`), call:
    - `breakDependencies(r, remainingResources)`
  - This removes provider dependencies that point to resources left in the source stack before destination integrity verification.

## Test-first workflow

1. **Test commit**: `ac668c490c`
   - Added regression test:
     - `TestMoveBreaksCopiedProviderDependenciesToRemainingSourceResources`
     - file: `pkg/cmd/pulumi/state/state_move_test.go`
   - Verified it fails before fix with the expected integrity error.

2. **Fix commit**: `4f043a6714`
   - Implemented dependency cleanup for copied providers.
   - Verified the regression test passes.

## Validation

Commands run:

- Failing before fix (at `ac668c490c`):
  - `go test ./cmd/pulumi/state -run "TestMoveBreaksCopiedProviderDependenciesToRemainingSourceResources"`
  - Fails with destination snapshot integrity error.

- Passing after fix (at `4f043a6714`):
  - `go test ./cmd/pulumi/state -run "TestMoveBreaksCopiedProviderDependenciesToRemainingSourceResources|TestMove"`
  - Passes.

## Notes

This is a targeted fix for provider dependency handling during state move and preserves existing behavior for other dependency rewriting paths.

### CODE REVIEW

File: pkg/cmd/pulumi/state/state_move.go [hunk 1]
```diff
@@ -347,6 +347,9 @@ func (cmd *stateMoveCmd) Run(
 		// rewrite the URNs of the resource.
 		originalProviderRef := fmt.Sprintf("%s::%s", res.URN, res.ID)
 		r := res.Copy()
+		// Copied providers must not depend on resources that remain in the source stack,
+		// otherwise destination snapshot integrity verification fails.
+		breakDependencies(r, remainingResources)
```
Comment (Frassle) [inline pkg/cmd/pulumi/state/state_move.go]: This should be appending to brokenSourceDependencies

File: pkg/cmd/pulumi/state/state_move_test.go [hunk 2]
```diff
@@ -1450,3 +1450,47 @@ func TestProviderParentsAreTreatedAsProviders(t *testing.T) {
...
+			Type: "pulumi:pulumi:Stack",
+		},
+		{
+			URN:    remainingURN,
+			Type:   "a:b:c",
+			Parent: resource.DefaultRootStackURN("sourceStack", "test"),
+		},
+		{
+			URN:          providerURN,
+			Type:         "pulumi:providers:a::default_1_0_0",
```
Comment (Frassle) [inline pkg/cmd/pulumi/state/state_move_test.go]: This isn't a valid type, it should just be `pulumi:providers:a`
```suggestion
			Type:         providerURN.Type(),
```

File: pkg/cmd/pulumi/state/state_move_test.go [hunk 3]
```diff
@@ -1450,3 +1450,47 @@ func TestProviderParentsAreTreatedAsProviders(t *testing.T) {
...
+			ID:           "provider_id",
+			Parent:       resource.DefaultRootStackURN("sourceStack", "test"),
+			Custom:       true,
+			Dependencies: []resource.URN{remainingURN},
+		},
+		{
+			URN:      moveURN,
+			Type:     "a:b:c",
```
Comment (Frassle) [inline pkg/cmd/pulumi/state/state_move_test.go]:
```suggestion
			Type:     moveURN.Type(),
```

File: pkg/cmd/pulumi/state/state_move_test.go [hunk 4]
```diff
@@ -1450,3 +1450,47 @@ func TestProviderParentsAreTreatedAsProviders(t *testing.T) {
...
+			Provider: string(providerURN) + "::provider_id",
+			Parent:   resource.DefaultRootStackURN("sourceStack", "test"),
+		},
+	}
+
+	sourceSnapshot, destSnapshot, _ := runMove(t, sourceResources, []string{string(moveURN)})
+
+	require.Len(t, sourceSnapshot.Resources, 3)
```
Comment (Frassle) [inline pkg/cmd/pulumi/state/state_move_test.go:1492]: There's 4 in the source snapshot.... this does not give confidence that you've actually run the tests

**Comment by Frassle** [comment]
@RohitYandigeri ensure you run the tests locally to see that things are actually fixed. Wasting maintainer time by submitting PRs that you have not tested and understood will get you banned under our AI usage policy.

**Comment by RohitYandigeri** [comment]
> @RohitYandigeri ensure you run the tests locally to see that things are actually fixed. Wasting maintainer time by submitting PRs that you have not tested and understood will get you banned under our AI usage policy.

Thanks for the review, and apologies for the earlier issues.

I’ve applied all requested changes:

In state_move.go, I now append the copied provider’s broken dependencies to brokenSourceDependencies:
brokenSourceDependencies = append(brokenSourceDependencies, breakDependencies(r, remainingResources)...)

In state_move_test.go, I updated fixture types to use URN-derived types instead of hardcoded strings:
Type: providerURN.Type()
Type: moveURN.Type()

I re-ran the relevant tests locally after these updates:
go test ./cmd/pulumi/state -run "TestMoveBreaksCopiedProviderDependenciesToRemainingSourceResources|TestMove"
Result: passing.

I’ve pushed the updates to the PR branch.

File: pkg/cmd/pulumi/state/state_move_test.go [hunk 5]
```diff
@@ -1450,3 +1450,47 @@ func TestProviderParentsAreTreatedAsProviders(t *testing.T) {
...
+		},
+		{
+			URN:      moveURN,
+			Type:     moveURN.Type(),
+			Provider: string(providerURN) + "::provider_id",
+			Parent:   resource.DefaultRootStackURN("sourceStack", "test"),
+		},
+	}
+
+	sourceSnapshot, destSnapshot, _ := runMove(t, sourceResources, []string{string(moveURN)})
```
Comment (Frassle) [inline pkg/cmd/pulumi/state/state_move_test.go]: Similar to the other tests this should assert stdout to ensure we're printing that the provider dependency is being dropped

Comment (RohitYandigeri) [reply pkg/cmd/pulumi/state/state_move_test.go]: I updated the test to assert stdout includes the dropped provider dependency warning (same style as related move tests), and pushed the change in 3a88e09d50.

I also re-ran locally:
go test ./cmd/pulumi/state -run "TestMoveBreaksCopiedProviderDependenciesToRemainingSourceResources|TestMove" (pass).

**Comment by Frassle** [comment]
/run-acceptance-tests
Please view the results of the acceptance tests [Here](https://github.com/pulumi/pulumi/actions/runs/22819382530)

**Comment by RohitYandigeri** [comment]
@Frassle please review

File: pkg/cmd/pulumi/state/state_move_test.go [hunk 6]
```diff
@@ -1450,3 +1450,50 @@ func TestProviderParentsAreTreatedAsProviders(t *testing.T) {
...
+	moveURN := resource.NewURN("sourceStack", "test", "", "a:b:c", "moveMe")
+
+	sourceResources := []*resource.State{
+		{
+			URN:  resource.DefaultRootStackURN("sourceStack", "test"),
+			Type: "pulumi:pulumi:Stack",
+		},
+		{
+			URN:    remainingURN,
+			Type:   "a:b:c",
```
Comment (Frassle) [inline pkg/cmd/pulumi/state/state_move_test.go]: This should use `remainingURN.Type()` like the other resource entries.

File: pkg/cmd/pulumi/state/state_move_test.go [hunk 7]
```diff
@@ -1450,3 +1450,50 @@ func TestProviderParentsAreTreatedAsProviders(t *testing.T) {
...
+			Parent: resource.DefaultRootStackURN("sourceStack", "test"),
+		},
+		{
+			URN:          providerURN,
+			Type:         providerURN.Type(),
+			ID:           "provider_id",
+			Parent:       resource.DefaultRootStackURN("sourceStack", "test"),
```
Comment (Frassle) [inline pkg/cmd/pulumi/state/state_move_test.go]: Worth pulling this to a variable, you're calling DefaultRootStackURN four times here. Also means you can use that urns `.Type()` to fill in the type for the stack entry.

File: pkg/cmd/pulumi/state/state_move_test.go [hunk 8]
```diff
@@ -1450,3 +1450,50 @@ func TestProviderParentsAreTreatedAsProviders(t *testing.T) {
...
+	}
+
+	sourceSnapshot, destSnapshot, stdout := runMove(t, sourceResources, []string{string(moveURN)})
+
+	require.Len(t, sourceSnapshot.Resources, 3)
+	require.Len(t, destSnapshot.Resources, 3)
+	assert.Equal(t, urn.URN("urn:pulumi:destStack::test::pulumi:providers:a::default_1_0_0"),
+		destSnapshot.Resources[1].URN)
+	assert.Empty(t, destSnapshot.Resources[1].Dependencies)
+	assert.Contains(t, stdout.String(),
```
Comment (Frassle) [inline pkg/cmd/pulumi/state/state_move_test.go:1497]: Ah this looks wrong, I think it should have been brokenDestDependencies not brokenSourceDependencies in the changed code.

**Comment by RohitYandigeri** [comment]
I'll check with changes and update

**Comment by RohitYandigeri** [comment]
@Frassle Applied all three points and pushed bc91878837: switched provider-copy breakage tracking to brokenDestDependencies, updated remaining type to remainingURN.Type(), and refactored repeated DefaultRootStackURN(...) into a sourceRootURN variable (also using sourceRootURN.Type() for the stack entry). Re-ran local tests: go test ./cmd/pulumi/state -run "TestMoveBreaksCopiedProviderDependenciesToRemainingSourceResources|TestMove" (pass).

**Comment by RohitYandigeri** [comment]
@Frassle waiting for a review

File: pkg/cmd/pulumi/state/state_move_test.go (hunk 8 above)
Comment (Frassle) [reply pkg/cmd/pulumi/state/state_move_test.go:1497]: Ah ok, I think this code correct now but we should make the test more clear. Check for the string:
```
The following resources being moved to organization/test/destStack have dependencies on resources in organization/test/sourceStack:

  - urn:pulumi:sourceStack::test::pulumi:providers:a::default_1_0_0 has a dependency on urn:pulumi:sourceStack::test::a:b:c::remaining
```
So we can clearly see this is a moved resource with a dep, not a left resource with a broken dep.

Comment (RohitYandigeri) [reply pkg/cmd/pulumi/state/state_move_test.go:1497]: Updated the test to assert the full output block you suggested so it’s clear this is a moved resource with a dependency on a source-stack resource, not a left-behind resource with a broken dep. Pushed in 13ea20085d and re-ran go test ./cmd/pulumi/state -run "TestMoveBreaksCopiedProviderDependenciesToRemainingSourceResources|TestMove" (pass).

**Review by Frassle — APPROVED** [review]
I think this looks right now

**Comment by Frassle** [comment]
/run-acceptance-tests
Please view the results of the acceptance tests [Here](https://github.com/pulumi/pulumi/actions/runs/22924539244)

**Comment by RohitYandigeri** [comment]
@Frassle Pushed b95bc953e8 to fix the lll lint failure in the new test assertion. I re-ran go test ./cmd/pulumi/state -run "TestMoveBreaksCopiedProviderDependenciesToRemainingSourceResources|TestMove" locally and it passes. The remaining acceptance failures are in unrelated lifecycletest / integration packages, outside the state move paths changed in this PR. Could those be retried?
