### PR TITLE
Fail refreshes with init errors.

### LINKED ISSUE #1881: `refresh` swallows initialization errors
In the process of investigating https://github.com/pulumi/pulumi/issues/1790, I discovered that `refresh` has regressed to swallowing initialization errors. This is easy to reproduce:

1. Create a `Pod` with a bad image name.
1. crtl-c after getting a warning about the bad image name.
1. `refresh`, the error disappears.

We'll want to fix this ASAP, before the release later today. cc @pgavlin @swgillespie

### PR DESCRIPTION
**Pull request by pgavlin**
And ensure that refreshes continue on errors.

Fixes #1881.

### CODE REVIEW

File: pkg/resource/deploy/step.go [hunk 1]
```diff
@@ -609,7 +609,7 @@ func (s *RefreshStep) Apply(preview bool) (resource.Status, StepCompleteFunc, er
 		if initErr, isInitErr := err.(*plugin.InitError); isInitErr {
 			// We clear error in this case because we do not want the refresh to fail in the face of initialization
```
Comment (hausdorff) [inline pkg/resource/deploy/step.go]: Seems like we should remove this comment now?

**Comment by pgavlin** [comment]
> There might be some subtlety with how this works with ctrl-c, but it seems like it should "just work."

Note that we do have tests for ctrl+c behavior to ensure that things cancel appropriately.
