### PR TITLE
fix `pulumi new` creates new project when stack reference project name and project name don't match

### LINKED ISSUE #13248: `pulumi new` `--stack` and `--name` may clash.
### What happened?

```bash
% pulumi new yaml --name fooo -s kyle-test1/foo/bar --yes
Created project 'fooo'

error: could not create stack: provided project name "foo" doesn't match Pulumi.yaml
```

### Expected Behavior

Project not created.

### Steps to reproduce

see what happened.

### Output of `pulumi about`

```
CLI          
Version      3.72.3-dev.0
Go Version   go1.20.4
Go Compiler  gc
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description

`pulumi new` `--stack` and `--name` check that the project name matches before creating a new project.

Fixes #13248 

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/cmd/pulumi/new.go [hunk 1]
```diff
@@ -82,6 +82,11 @@ func runNew(ctx context.Context, args newArgs) error {
 		IsInteractive: args.interactive,
 	}
 
+	// Check project name and stack reference project name are the same.
```
Comment (Frassle) [inline pkg/cmd/pulumi/new.go:85]: I wonder if we should just make --stack have to be a plain name. I.e. validate it's a `tokens.Name` not a `QName`. I realize the scuppers the idea of using a fully qualified ref here to set the org, but I think I'm coming around to preferring your idea of adding an "--org" flag to override that. Hell maybe we could even add a prompt as part of the new workflow to give users the choice for org if they haven't set that flag (The backend can suggest which orgs the user has access to, and if they only have one we can just default select it and not prompt so most users wouldn't see any difference here).

This might also interact with your other PR (https://github.com/pulumi/pulumi/pull/13234) so if we like this approach I'd put that PR on a short hold to make this change first.

Comment (dixler) [reply pkg/cmd/pulumi/new.go:85]: I think this is sensible.

Comment (justinvp) [reply pkg/cmd/pulumi/new.go:85]: This generally sounds reasonable to me, but we should discuss a concrete proposal in ideation.

Though, I don't think we can get away with forcing `--stack` to be only a plain name, because it can be a fully qualified name already today. As such, this change to do this validation looks reasonable to me.

Comment (Frassle) [reply pkg/cmd/pulumi/new.go:85]: >Though, I don't think we can get away with forcing --stack to be only a plain name, because it can be a fully qualified name already today.

I think we've only run into problems trying to pass a ref here internally, I haven't seen any users doing this? I suspect it would be OK to do this.

> As such, this change to do this validation looks reasonable to me.

If we are going to allow a ref here then yes we should validate the project matches but we should do that by calling the backends ParseStackReference method and checking the refs Project() property. Not by doing the string split currently proposed in this change.
That Parse will also cover a lot of other validation of the ref like checking its actually a valid name.

File: pkg/backend/mock.go [hunk 2]
```diff
@@ -139,7 +140,29 @@ func (be *MockBackend) ParseStackReference(s string) (StackReference, error) {
 	if be.ParseStackReferenceF != nil {
 		return be.ParseStackReferenceF(s)
 	}
-	panic("not implemented")
+
+	// default implementation
+	split := strings.Split(s, "/")
+	var name tokens.Name
+	var project tokens.Name
```
Comment (abhinav) [inline pkg/backend/mock.go:147]: optional:
```suggestion
	var name, project tokens.Name
```

File: pkg/cmd/pulumi/new.go [hunk 3]
```diff
@@ -1112,3 +1117,29 @@ func containsWhiteSpace(value string) bool {
...
+
+func validateStackProjectName(b backend.Backend, stackName, projectName string) error {
+	if stackName == "" {
+		return nil
+	}
+	if projectName == "" {
+		return nil
+	}
+
+	if strings.Count(stackName, "/") == 2 {
```
Comment (abhinav) [inline pkg/cmd/pulumi/new.go:1129]: A comment here adding context on exactly which case we're detecting here would be helpful.
e.g., if the user supplied `--stack organization/$project/$stack`, verify that the project name matches `--project $project`.

File: pkg/cmd/pulumi/new.go [hunk 4]
```diff
@@ -1112,3 +1117,29 @@ func containsWhiteSpace(value string) bool {
 	}
 	return false
 }
+
+func validateStackProjectName(b backend.Backend, stackName, projectName string) error {
```
Comment (abhinav) [inline pkg/cmd/pulumi/new.go:1121]: A comment explaining what the stackName and projectName arguments are would be helpful.
Specifically that they're the `--stack` and `--project` flag values,
and that stackName could be "$name" or "organization/$project/$name".

File: pkg/cmd/pulumi/new.go [hunk 5]
```diff
@@ -1112,3 +1117,29 @@ func containsWhiteSpace(value string) bool {
...
+	if stackName == "" {
+		return nil
+	}
+	if projectName == "" {
+		return nil
```
Comment (abhinav) [inline pkg/cmd/pulumi/new.go:1126]: optional nit: In this case, the two conditions are simple enough to combine, IMO.

```suggestion
	if stackName == "" || projectName == "" {
		return nil
```

File: pkg/cmd/pulumi/new.go [hunk 6]
```diff
@@ -1112,3 +1117,29 @@ func containsWhiteSpace(value string) bool {
...
+			return err
+		}
+		stackProjectName, hasProject := ref.Project()
+		if !hasProject {
+			return nil
+		}
+		if projectName == stackProjectName.String() {
+			return nil
+		}
+		return fmt.Errorf("project name (%s) and stack reference project name (%s) must be the same",
```
Comment (abhinav) [inline pkg/cmd/pulumi/new.go:1141]: Should we reference the flags here in the error message instead of the concept names?

e.g., something like:

    project name (--project %s) must match fully qualified stack reference (--stack %s)

File: pkg/cmd/pulumi/new_test.go [hunk 7]
```diff
@@ -818,3 +818,49 @@ func TestErrorIfNotEmptyDirectory(t *testing.T) {
...
+		{
+			projectName: "",
+			stackRef:    "org/foo/dev",
+			valid:       true,
+		},
+		{
+			projectName: "foo",
+			stackRef:    "",
+			valid:       true,
+		},
```
Comment (abhinav) [inline pkg/cmd/pulumi/new_test.go:848]: optional: can omit zero-value fields.
```suggestion
		},
		{
			stackRef:    "org/foo/dev",
			valid:       true,
		},
		{
			projectName: "foo",
			valid:       true,
		},
```

File: pkg/cmd/pulumi/new_test.go [hunk 8]
```diff
@@ -818,3 +818,49 @@ func TestErrorIfNotEmptyDirectory(t *testing.T) {
...
+	b, err := currentBackend(context.Background(), nil, display.Options{})
+	require.NoError(t, err)
+
+	for _, tt := range tests {
+		err := validateStackProjectName(b, tt.stackRef, tt.projectName)
+		if tt.valid {
+			assert.NoError(t, err, "projectName: %s, stackRef: %s", tt.projectName, tt.stackRef)
+		} else {
+			assert.Error(t, err, "projectName: %s, stackRef: %s", tt.projectName, tt.stackRef)
+		}
```
Comment (abhinav) [inline pkg/cmd/pulumi/new_test.go:864]: optional: Instead of adding context to the assertions, you can put context in the subtest names.

```go
for _, tt := range tests {
  tt := tt
  t.Run(fmt.Sprintf("project=%q/stackRef=%q", tt.projectName, tt.stackRef), func(t *testing.T) {
    t.Parallel()

    // ...
  })
```

**Review by abhinav — COMMENTED** [review]
Seems like a reasonable change.
Minus the minor comments, would appreciate comments on some of the key behavioral bits.
And we should maybe tweak the error message a bit, WDYT?

File: pkg/cmd/pulumi/new_test.go (hunk 7 above)
Comment (dixler) [reply pkg/cmd/pulumi/new_test.go:848]: We could, but I feel that it would be nicer to show this implicit detail.

**Review by justinvp — APPROVED** [review]

File: pkg/cmd/pulumi/new.go [hunk 9]
```diff
@@ -1112,3 +1117,34 @@ func containsWhiteSpace(value string) bool {
...
+//   - stackName comes from the --stack flag. stackName can be a stack name or a fully qualified stack reference
+//     i.e org/project/stack
+func validateStackProjectName(b backend.Backend, stackName, projectName string) error {
+	if stackName == "" || projectName == "" {
+		// No potential for conflicting project names.
+		return nil
+	}
+
+	// Catch the case where the user has specified a fully qualified stack reference.
+	if strings.Count(stackName, "/") == 2 {
```
Comment (Frassle) [inline pkg/cmd/pulumi/new.go:1132]: No need to check for if there's two "/" here, just let the backend do the parse.

File: pkg/cmd/pulumi/new_test.go [hunk 10]
```diff
@@ -818,3 +818,53 @@ func TestErrorIfNotEmptyDirectory(t *testing.T) {
...
+			stackRef:    "",
+			valid:       true,
+		},
+		{
+			projectName: "foo",
+			stackRef:    "org/foo/dev",
+			valid:       true,
+		},
+	}
+	b, err := currentBackend(context.Background(), nil, display.Options{})
```
Comment (Frassle) [inline pkg/cmd/pulumi/new_test.go:855]: This should _not_ be testing against the real backend.

**Review by Frassle — CHANGES_REQUESTED** [review]

**Review by justinvp — APPROVED** [review]

**Comment by dixler** [comment]
bors merge

**Comment by dixler** [comment]
bors merge

**Comment by dixler** [comment]
bors merge
