### PR TITLE
turn on the golangci-lint exhaustive linter

### LINKED ISSUE #14601: Turn on "exhaustive" golangci-lint linter
Having a non-exhaustive switch/case statement, and running into a `contract.Failf` has caused multiple issues over the last month.  Of the top of my head:
- https://github.com/pulumi/pulumi/issues/14598
- https://github.com/pulumi/pulumi/issues/14570
- https://github.com/pulumi/pulumi/issues/14325

and maybe more that I can't remember right now.  This seems to be the most common cause for panics/regressions, which are hard to catch in tests.

`golangci-lint` has a linter that can help in at least some of these cases: https://golangci-lint.run/usage/linters/#exhaustive, where the switch is over an enum.  We should experiment with this linter and try to turn it on if it makes sense to help prevent similar panics further down the line.

### PR DESCRIPTION
**Pull request by tgummerer**
Turn on the golangci-lint exhaustive linter.  This is the first step
towards catching more missing cases during development rather than
in tests, or in production.

This might be best reviewed commit-by-commit, as the first commit turns on the linter with the `default-signifies-exhaustive: true` option set, which requires a lot less changes in the current codebase.

I think it's probably worth doing the second commit as well, as that will get us the real benefits, even though we end up with a little bit more churn.  However it means all the `switch` statements are covered, which isn't the case after the first commit, since we do have a lot of `default` statements that just call `assert.Fail`.
 
Fixes #14601 

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: sdk/go/common/diag/colors/diag.go [hunk 1]
```diff
@@ -48,10 +46,11 @@ func (c Colorization) ColorizeWithMaxWidth(v string, maxWidth int) string {
 		return colorizeText(v, Always, maxWidth)
 	case Never:
 		return colorizeText(v, Never, maxWidth)
-	default:
-		contract.Failf("Unexpected colorization value: %v", c)
-		return ""
+	case Auto:
```
Comment (tgummerer) [inline sdk/go/common/diag/colors/diag.go:49]: Does anyone know if `Auto` is actually used?  I would have expected problems here earlier if it was.

Comment (Frassle) [reply sdk/go/common/diag/colors/diag.go:49]: No, there's some magic in `GetGlobalColorization` such that while Auto is the default value it's never actually used. I think I can tidy this up with an optional ptr rather than the Auto case.

Comment (Frassle) [reply sdk/go/common/diag/colors/diag.go:49]: https://github.com/pulumi/pulumi/pull/15030

File: sdk/go/common/util/cmdutil/console.go [hunk 2]
```diff
@@ -373,8 +373,7 @@ func (m readConsoleModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
 		// it's time to stop the bubbletea loop.
 		//
 		// Only Enter is considered a success.
-		switch msg.Type {
-		case tea.KeyEnter, tea.KeyCtrlC, tea.KeyEsc:
+		if msg.Type == tea.KeyEnter || msg.Type == tea.KeyCtrlC || msg.Type == tea.KeyEsc {
```
Comment (Frassle) [inline sdk/go/common/util/cmdutil/console.go:376]: This and sdk/go/common/resource/plugin/provider_plugin.go switches did look nicer as switches rather than == == ==. Wonder if we leave 'default' as allowed and then just have something like "default: // ignore other keys" instead?

File: pkg/backend/display/json.go [hunk 3]
```diff
@@ -206,6 +208,9 @@ func ShowPreviewDigest(events <-chan engine.Event, done chan<- bool, opts Option
 		case engine.PolicyLoadEvent:
 			// At this point in time, we don't handle policy events in JSON serialization
 			continue
+		case engine.PolicyRemediationEvent:
```
Comment (Frassle) [inline pkg/backend/display/json.go:211]: Combine with the case above?

File: sdk/go/common/util/cmdutil/console.go (hunk 2 above)
Comment (tgummerer) [reply sdk/go/common/util/cmdutil/console.go:376]: I think we could just annotate this with //nolint:exhaustive as well if we want to keep the switches.  

I shied away from having default as allowed, since it would be quite a bit of work to get rid of all the "default: contract.Fail(...)" situations we have, but it would definitely be doable.

**Review by Frassle — APPROVED** [review]
A bit sad at how many //nolint:exhastive bits we have, suggests the code could probably be cleaned up more. But this is a good first pass for better safety so ✅
