### PR TITLE
Fix panic when ranging over array of objects output

### LINKED ISSUE #21661: `pulumi convert` panics when converting tf snippet
## Steps to reproduce

**Step 1:** Create the following file and name it `foo.tf`:

```
resource "fastly_tls_subscription" "example" {
  domains               = []
  certificate_authority = "lets-encrypt"
}

resource "aws_route53_record" "domain_validation" {
  depends_on = [fastly_tls_subscription.example]

  for_each = {
    for domain in fastly_tls_subscription.example.domains :
    domain => element([
      for obj in fastly_tls_subscription.example.managed_dns_challenges :
      obj if obj.record_name == "_acme-challenge.${domain}"
    ], 0)
  }

  name            = each.value.record_name
}
```

**Step 2:** Run `pulumi convert --from terraform foo.tf --language python` with `pulumi` (reproduces even with pulumi downgraded to 3.200.0).

## What should happen?

Equivalent Python snippets should be produced.

## What happens instead?

The following panic:

<details>

```
Converting from terraform...
warning: using pulumi-converter-terraform from $PATH at /Users/apose/.local/share/mise/installs/vfox-pulumi-pulumi-pulumi-converter-terraform/1.2.4/bin/pulumi-converter-terraform
Downloading provider: fastly
warning: using pulumi-resource-aws from $PATH at /Users/apose/.local/share/mise/installs/vfox-pulumi-pulumi-pulumi-aws/7.12.0/bin/pulumi-resource-aws
Converting to python...
warning: using pulumi-resource-aws from $PATH at /Users/apose/.local/share/mise/installs/vfox-pulumi-pulumi-pulumi-aws/7.12.0/bin/pulumi-resource-aws
warning: using pulumi-resource-aws from $PATH at /Users/apose/.local/share/mise/installs/vfox-pulumi-pulumi-pulumi-aws/7.12.0/bin/pulumi-resource-aws
panic: runtime error: index out of range [-1]

goroutine 51 [running]:

github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.(*RelativeTraversalExpression).Type(0x1036f7900?)

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/hcl2/model/expression.go:1820 +0xf0

github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.typecheckArgs({{0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}}, {{0x1400c7ee560, 0x1, ...}, ...}, ...)

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/hcl2/model/binder_expression.go:219 +0x2d8

github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.(*FunctionCallExpression).Typecheck(0x14001922100, 0xf8?)

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/hcl2/model/expression.go:1050 +0x15c

github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*applyRewriter).preVisit(0x140004fd1c0, {0x1036f7b80, 0x14001922100})

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/pcl/rewrite_apply.go:262 +0x34

github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x1036f7b80?, 0x14001922100?}, 0x103555c40?, 0x1400203f318)

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/hcl2/model/visitor.go:307 +0x48

github.com/pulumi/pulumi/pkg/v3/codegen/pcl.RewriteAppliesWithSkipToJSON({0x1036f7b80, 0x14001922100}, {0x1036e2360, 0x1033dff68}, 0x0, 0x1)

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/pcl/rewrite_apply.go:703 +0xf8

github.com/pulumi/pulumi/pkg/v3/codegen/python.(*generator).lowerExpression(0x140005a6d20, {0x1036f7b80?, 0x14001922100?}, {0x1036f7900, 0x1400078fcc0})

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/python/gen_program_expressions.go:47 +0x58

github.com/pulumi/pulumi/pkg/v3/codegen/python.(*generator).genResourceDeclaration(0x140005a6d20, {0x1036dfa68, 0x14007e84360}, 0x1400031e8f0, 0x0)

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/python/gen_program.go:862 +0x1f34

github.com/pulumi/pulumi/pkg/v3/codegen/python.(*generator).genResourceDeclaration.func2(...)

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/python/gen_program.go:914

github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model/format.(*Formatter).Indented(...)

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/hcl2/model/format/gen.go:85

github.com/pulumi/pulumi/pkg/v3/codegen/python.(*generator).genResourceDeclaration(0x140005a6d20, {0x1036dfa68, 0x14007e84360}, 0x1400031e8f0, 0x1)

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/python/gen_program.go:909 +0x90c

github.com/pulumi/pulumi/pkg/v3/codegen/python.(*generator).genResource(...)

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/python/gen_program.go:1035

github.com/pulumi/pulumi/pkg/v3/codegen/python.(*generator).genNode(0x140005a6d20?, {0x1036dfa68?, 0x14007e84360?}, {0x1036f6630?, 0x1400031e8f0?})

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/python/gen_program.go:624 +0x64

github.com/pulumi/pulumi/pkg/v3/codegen/python.GenerateProgram(0x140007ffe80)

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/python/gen_program.go:75 +0xd0

github.com/pulumi/pulumi/pkg/v3/codegen/python.GenerateProject({0x140006b6410, 0x45}, {{0x140001a1a28, 0x8}, {{0x0, 0x0}, 0x0}, {0x0, 0x0}, 0x0, ...}, ...)

	github.com/pulumi/pulumi/pkg/v3@v3.156.0/codegen/python/gen_program.go:309 +0x48

main.(*pythonLanguageHost).GenerateProject(0x14000114c60, {0x10369e800?, 0x40?}, 0x140001c4280)

	github.com/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/v3/main.go:1612 +0x390

github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_GenerateProject_Handler.func1({0x1036ed6c0?, 0x1400045bb00?}, {0x103659920?, 0x140001c4280?})

	github.com/pulumi/pulumi/sdk/v3@v3.212.0/proto/go/language_grpc.pb.go:734 +0xcc

github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1036ed6c0, 0x1400045af30}, {0x103659920, 0x140001c4280}, 0x140006ac860, 0x1400069c840)

	github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2a4

github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_GenerateProject_Handler({0x10369e800, 0x14000114c60}, {0x1036ed6c0, 0x1400045af30}, 0x140001c4200, 0x140006ac3a0)

	github.com/pulumi/pulumi/sdk/v3@v3.212.0/proto/go/language_grpc.pb.go:736 +0x140

google.golang.org/grpc.(*Server).processUnaryRPC(0x140001c6000, {0x1036ed6c0, 0x1400045aea0}, 0x14000114d80, 0x1400045a4e0, 0x104016c50, 0x0)

	google.golang.org/grpc@v1.72.1/server.go:1405 +0xbd0

google.golang.org/grpc.(*Server).handleStream(0x140001c6000, {0x1036edff0, 0x1400040ab60}, 0x14000114d80)

	google.golang.org/grpc@v1.72.1/server.go:1815 +0x858

google.golang.org/grpc.(*Server).serveStreams.func2.1()

	google.golang.org/grpc@v1.72.1/server.go:1035 +0x74

created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 49

	google.golang.org/grpc@v1.72.1/server.go:1046 +0x120

error: could not generate output program: error reading from server: EOF
```
</details>

---

## Note

Also, please verify the command works with the snippets contained on the following files ([see](https://github.com/pulumi/pulumi-fastly/issues/944)) as part of the ticket resolution:

* [fastly/terraform-provider-fastly@8b9e78e/docs/resources/tls_subscription.md?plain=1#L33](https://github.com/fastly/terraform-provider-fastly/blob/8b9e78e8e4b6c4e2cc1c7860fb5edfdfa45aa4a3/docs/resources/tls_subscription.md?plain=1#L33)
* [fastly/terraform-provider-fastly@8b9e78e/docs/resources/tls_subscription.md?plain=1#L156](https://github.com/fastly/terraform-provider-fastly/blob/8b9e78e8e4b6c4e2cc1c7860fb5edfdfa45aa4a3/docs/resources/tls_subscription.md?plain=1#L156)
* [fastly/terraform-provider-fastly@8b9e78e/docs/resources/tls_subscription_validation.md?plain=1#L21](https://github.com/fastly/terraform-provider-fastly/blob/8b9e78e8e4b6c4e2cc1c7860fb5edfdfa45aa4a3/docs/resources/tls_subscription_validation.md?plain=1#L21)

## `pulumi about`

```
CLI
Version      3.213.0
Go Version   go1.25.5
Go Compiler  gc

Host
OS       darwin
Version  15.7.3
Arch     arm64
```

### PR DESCRIPTION
**Pull request by justinvp**
This change fixes a Python programgen panic when ranging over a resource output that is an array of objects, and traversing into the object.

The panic `index out of range [-1]` in `pulumi convert` occurs in [RelativeTraversalExpression.Type()](https://github.com/pulumi/pulumi/blob/aba11a7f6941592c383e17e8ea746e0da4a22258/pkg/codegen/hcl2/model/expression.go#L1820) when `Parts` is empty.

**Root Cause:** A `RelativeTraversalExpression` is being created with an empty/nil `Parts` slice. The `Type()` method assumes `Parts` has at least one element, so accessing `Parts[len(Parts)-1]` when `len(Parts) == 0` causes the panic.

The fix is in `gen_program_quotes.go`. The logic at [line 85-87](https://github.com/pulumi/pulumi/blob/aba11a7f6941592c383e17e8ea746e0da4a22258/pkg/codegen/python/gen_program_quotes.go#L85-L87) only appends to `currentParts` when not on the last element, which can leave `currentParts` empty:

```go
// Current buggy code:
if i < len(traversal)-1 {
    currentParts = append(currentParts, parts[i+1])
}
```

```go
// Fix: Always append when appending to currentTraversal
currentParts = append(currentParts, parts[i+1])
```

Fixes #21661

### CODE REVIEW

File: cmd/pulumi-test-language/providers/dns_provider.go [hunk 1]
```diff
@@ -0,0 +1,233 @@
...
+
+	"github.com/blang/semver"
+
+	"github.com/pulumi/pulumi/pkg/v3/codegen/schema"
+	"github.com/pulumi/pulumi/sdk/v3/go/common/resource"
+	"github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin"
+	"github.com/pulumi/pulumi/sdk/v3/go/common/tokens"
+)
+
+type DNSProvider struct {
```
Comment (Frassle) [inline cmd/pulumi-test-language/providers/dns_provider.go]: I've been trying to avoid making the conformance test providers match "real" things.
They should be designed to test a specific protocol feature, not copy what real world thing caused a reproable bug.

Comment (justinvp) [reply cmd/pulumi-test-language/providers/dns_provider.go]: Any suggestions on what to call it? It needs to have an output property that is an array of objects.

File: cmd/pulumi-test-language/tests/l3_range_resource_output_traversal.go [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+
+import (
+	"github.com/pulumi/pulumi/cmd/pulumi-test-language/providers"
+	"github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin"
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+)
+
+func init() {
+	LanguageTests["l3-range-resource-output-traversal"] = LanguageTest{
```
Comment (justinvp) [inline cmd/pulumi-test-language/tests/l3_range_resource_output_traversal.go:25]: @Frassle, I'm also curious if you have any thoughts on the test name. Seemed like it could be l3, but maybe it's l2 for PCL `range` option?

Comment (Frassle) [reply cmd/pulumi-test-language/tests/l3_range_resource_output_traversal.go:25]: Rules are if we can do it in YAML its L2, else L3

File: cmd/pulumi-test-language/providers/dns_provider.go (hunk 1 above)
Comment (Frassle) [reply cmd/pulumi-test-language/providers/dns_provider.go]: NestedObjectProvider? Then can use it to test objects nested in maps and arrays and other objects?

Comment (justinvp) [reply cmd/pulumi-test-language/providers/dns_provider.go]: Done

**Review by Frassle — APPROVED** [review]
