### PR TITLE
Fail read steps with missing resources.

### LINKED ISSUE #262: Lumi CLI should return failing error code on failure
Our nightly tests rely on `lumi` commands returning failing error codes when there are failures invoking the requested command.  

Currently, there are at least some conditions where failures will occur but succes is returned from the `lumi` process.  The one we have seen triggered a few times is on `catastraphic failures`, which are reported by do not appear to carry an error through to the process exit code.

```
[      scenarios/aws/serverless ] error LUMI2003: Plan apply failed: rpc error: code = Unknown desc = TooManyRequestsException: Too Many Requests
[      scenarios/aws/serverless ] 	status code: 429, request id: 78a14c45-56dc-11e7-9e69-61b9830708d2
[      scenarios/aws/serverless ] Step #4 failed [create]: this failure was catastrophic and the provider cannot guarantee recovery
[      scenarios/aws/serverless ] 3 total changes:
[      scenarios/aws/serverless ]     + 3 resources created
[      scenarios/aws/serverless ] Deployment duration: 34.952769412s
[      scenarios/aws/serverless ] A catastrophic error occurred; resources states may be unknown
[      scenarios/aws/serverless ]
```

(above from https://travis-ci.com/pulumi/lumi/builds/48645333)

### PR DESCRIPTION
**Pull request by pgavlin**
Just what it says on the tin.

Fixes #262.

### CODE REVIEW

File: pkg/resource/deploy/step.go [hunk 1]
```diff
@@ -600,7 +600,15 @@ func (s *ReadStep) Apply(preview bool) (resource.Status, StepCompleteFunc, error
 			}
 		}
 
+		// If there is no such resource, return an error indicating as such.
+		if result.Outputs == nil {
+			return resource.StatusOK, nil, errors.Errorf("resource '%s' does not exist", id)
```
Comment (stack72) [inline pkg/resource/deploy/step.go]: Even though we are failing, we are returning resource.StatusOK - is that Intended?

Comment (pgavlin) [reply pkg/resource/deploy/step.go]: Yes. I don't think we actually use these statuses anywhere, in fact.

**Comment by pgavlin** [comment]
As a note: one other option we could have taken here is to let these steps soft-fail, have the SDK throw an exception/return an error, and leave it up to the user whether or not to hard-fail.
