### PR TITLE
[codegen/nodejs] Fix missing args param

### LINKED ISSUE #7538: Method args parameter is missing in Node.js codegen
This schema:

```json
{
  "name": "xyz",
  "resources": {
    "xyz:index:First": {
      "isComponent": true,
      "properties": {
        "firstValue": {
          "type": "string"
        },
        "secondValue": {
          "type": "string"
        }
      },
      "required": [
        "secondValue"
      ],
      "methods": {
        "generateKubeconfig": "xyz:index:First/generateKubeconfig"
      }
    }
  },
  "functions": {
    "xyz:index:First/generateKubeconfig": {
      "description": "Do something with something else",
      "inputs": {
        "properties": {
          "__self__": {
            "$ref": "#/resources/xyz:index:First"
          },
          "boolValue": {
            "type": "boolean",
            "plain": true
          }
        },
        "required": [
          "__self__",
          "boolValue"
        ]
      },
      "outputs": {
        "properties": {
          "kubeconfig": {
            "type": "string"
          }
        },
        "required": [
          "kubeconfig"
        ]
      }
    }
  },
  "language": {
    "csharp": {
      "packageReferences": {
        "Pulumi": "3.*",
        "Pulumi.Aws": "4.*"
      }
    },
    "go": {
      "generateResourceContainerTypes": true,
      "importBasePath": "github.com/pulumi/pulumi-xyz/sdk/go/xyz"
    },
    "nodejs": {
      "dependencies": {
        "@pulumi/aws": "^4.0.0"
      },
      "devDependencies": {
        "typescript": "^3.7.0"
      }
    },
    "python": {
      "requires": {
        "pulumi": ">=3.0.0,<4.0.0",
        "pulumi-aws": ">=4.0.0,<5.0.0"
      }
    }
  }
}
```

Is producing:

image (5)

Note that `args` is not specified as a parameter of the generated method.

The problem is the `break` in:

https://github.com/pulumi/pulumi/blob/042e0061d4e32824c22c18b72e764a482ecfa3ac/pkg/codegen/nodejs/gen.go#L727-L730

🤦

### PR DESCRIPTION
**Pull request by justinvp**
This is the before/after:

```diff
-generateKubeconfig(): pulumi.Output<Foo.GenerateKubeconfigResult> {
+generateKubeconfig(args: Foo.GenerateKubeconfigArgs): pulumi.Output<Foo.GenerateKubeconfigResult> {
```

Fixes #7538

### CODE REVIEW

**Review by pgavlin — APPROVED** [review]

File: pkg/codegen/nodejs/gen.go [hunk 1]
```diff
@@ -726,7 +726,6 @@ func (mod *modContext) genResource(w io.Writer, r *schema.Resource) error {
 				}
 				if arg.IsRequired() {
 					argsOptional = false
-					break
```
Comment (t0yv0) [inline pkg/codegen/nodejs/gen.go:729]: 👿 

I've spent so many years in FP I literally fear these keywords `break` and `continue`. It looks like the fear is not entirely unjustified.
