### PR TITLE
[sdk/{go,nodejs,python}] Fix `DeletedWith` resource option

### LINKED ISSUE #11358: New resource option `DeletedWith` accepts a URN instead of a Resource
### What happened?

At least in the Go SDK, it's difficult to utilize the new `DeletedWith()` option.
It accept a `URN`, unlike `Parent()` which accepts a `Resource`, so it seems like the only way to use `DeletedWith` is inside an `.ApplyT(...)` block.

### Steps to reproduce

Try to invoke `pulumi.DeletedWith` in the Go SDK.

### Expected Behavior

I would like to be able to invoke `pulumi.DeletedWith` in the Go SDK without `.ApplyT()`.

### Actual Behavior

Seems like one must use `DeletedWith()` inside an `.ApplyT()` block.

### Output of `pulumi about`

_No response_

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #11622: "deletedWith" is ignored
### What happened?

I wanted to deploy a static website in Azure, with a CDN and a custom domain. This needs a DNS record to work, and the DNS record needs the CDN endpoint. The resulting dependencies are like so:
CDN Endpoint -> DNS Record Set -> CDN Custom domain.

This worked for deployment, but not for tear down since Azure needs the DNS Record to be deleted BEFORE the CDN Custom Endpoint.
> Cannot delete custom domain "<my domain>" because it is still directly or indirectly (using \"cdnverify\" prefix) CNAMEd to CDN endpoint "<my cdn endpoint name>.azureedge.net". Please remove the DNS CNAME record and try again.

Therefore I tried setting CDN Custom domain "deletedWith", to be deletedWith the CDN Endpoint. But when running pulumi down, pulumi still tries to delete the CDN Custom domain first.

### Steps to reproduce

Language: Typescript 
Package versions:
- @pulumi/azure-native: 1.88.1
- @pulumi/pulumi: 3.48.0

Pulumi CLI version: v3.49.0

**Gist:**
https://gist.github.com/oskar-martensson/9088ffbc788f15d8ce2351b062da8241

**What I've done:**
Using the example project: https://github.com/pulumi/examples/blob/master/azure-ts-static-website/index.ts
Add an azure-native RecordSet and azure-native CustomDomain.
Use the following dependency chain: CDN Endpoint -> DNS Record Set -> CDN Custom domain.
Set "deletedWith" to the Custom Domain, pointing at the CDN Endpoint.

### Expected Behavior

Pulumi does not attempt to destroy the Custom Domain

### Actual Behavior

Pulumi attempts to delete the Custom Domain

### Output of `pulumi about`

CLI
Version      3.49.0
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.25.0
azure-native  1.88.1
nodejs        unknown

Host
OS       darwin
Version  13.0
Arch     x86_64

This project is written in nodejs: executable='/Users/<xxx>/.nvm/versions/node/v16.14.2/bin/node' version='v16.14.2'

Current Stack: dev

TYPE                                              URN
pulumi:pulumi:Stack                               urn:pulumi:dev::<xxx>::pulumi:pulumi:Stack::<xxx>
pulumi:providers:azure-native                     urn:pulumi:dev::<xxx>::pulumi:providers:azure-native::default_1_88_1
azure-native:resources:ResourceGroup              urn:pulumi:dev::<xxx>::azure-native:resources:ResourceGroup::<xxx>
azure-native:cdn:Profile                          urn:pulumi:dev::<xxx>::azure-native:cdn:Profile::<xxx>
azure-native:storage:StorageAccount               urn:pulumi:dev::<xxx>::azure-native:storage:StorageAccount::<xxx>
azure-native:storage:StorageAccountStaticWebsite  urn:pulumi:dev::<xxx>::azure-native:storage:StorageAccountStaticWebsite::<xxx>
azure-native:storage:Blob                         urn:pulumi:dev::<xxx>::azure-native:storage:Blob::index.html
azure-native:cdn:Endpoint                         urn:pulumi:dev::<xxx>::azure-native:cdn:Endpoint::<xxx>
azure-native:network:RecordSet                    urn:pulumi:dev::<xxx>::azure-native:network:RecordSet::<xxx>
azure-native:cdn:CustomDomain                     urn:pulumi:dev::<xxx>::azure-native:cdn:CustomDomain::<xxx>

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
This change fixes the `DeletedWith` resource option in the Go, Node.js, and Python SDKs and adds tests.

This feature was a community contribution and while there were engine tests included with the [original PR](https://github.com/pulumi/pulumi/pull/11095), there weren't any tests confirming the functionality worked correctly from each SDK.

Here's a summary of the fixes:

* Go: The `DeletedWith` resource option was never usable as it accepted a URN instead of a Resource. We discussed this internally a while back and decided to go ahead and fix this. (Note: While changing the signature is technically a breaking change, the feature is currently unusable, so the change would not break anyone, so there's no need to wait for a major version bump.)

* Node.js: The `deletedWith` resource option did not work at all from the Node.js SDK because it was incorrectly passing the resource object itself in the RegisterResource request, rather than the resource's URN.

* Python: The `deleted_with` resource option did not work at all from the Python SDK because it was incorrectly passing the resource object itself in the RegisterResource request, rather than the resource's URN.

A `FailsOnDelete` resource has been added to the testprovider, which will fail when its `Delete` gRPC is called. The tests use this to ensure `Delete` is not called for resources of this type with the `DeletedWith` option specified.

Fixes #11358
Fixes #11622

### CODE REVIEW

File: tests/integration/deleted_with/go/fails_on_delete.go [hunk 1]
```diff
@@ -0,0 +1,24 @@
+// Copyright 2016-2023, Pulumi Corporation.  All rights reserved.
```
Comment (justinvp) [inline tests/integration/deleted_with/go/fails_on_delete.go:1]: It might be worth considering moving `testprovider` to its own repo and publishing it. Then we could use it from this repo and others (like `pulumi-dotnet`, `pulumi-java`, etc.), and we wouldn't need to have multiple copies of these hand-written files for calling the resources in the provider in each test that uses them.

Comment (Frassle) [reply tests/integration/deleted_with/go/fails_on_delete.go:1]: I think pretty much the entire integration test set should be callable from each language repo, not sure if that means testprovider needs to be moved out to it's own repo as well or not though. And as you'll have seen in dotnet I re-wrote the testprovider to C# in that repo, might make sense to do that for other languages as well.

File: tests/integration/deleted_with/nodejs/failsOnDelete.ts [hunk 2]
```diff
@@ -0,0 +1,9 @@
+// Copyright 2016-2023, Pulumi Corporation.  All rights reserved.
```
Comment (Frassle) [inline tests/integration/deleted_with/nodejs/failsOnDelete.ts:1]: It is very lame we have to write each of these integration test 6 times (python, nodejs, go, dotnet, java, yaml). Are we ever going to prioritize matrix testing to fix this?

**Review by Frassle — APPROVED** [review]

File: tests/integration/deleted_with/nodejs/failsOnDelete.ts (hunk 2 above)
Comment (justinvp) [reply tests/integration/deleted_with/nodejs/failsOnDelete.ts:1]: Yes, we should talk more about how/when we can get to it.

**Comment by justinvp** [comment]
bors merge

**Comment by same-id** [comment]
Thanks for taking this to the finish line
