### PR TITLE
Fix plugin resolution in convert.

### LINKED ISSUE #19039: #18951 breaks plugin resolution for conversions (and others?)
After this change conversion stop being able to find plugins with this error:

warning: /Users/brpol/src/pulumi-terraform-convert-investigation/examples/iam-user/main_example.tf:54,1-32: Failed to get provider info; Failed to get provider info for "aws_iam_policy": rpc error: code = Unknown desc = could not create provider for package aws: load plugin aws@6.68.0: no  plugin 'pulumi--aws' found in the workspace at version v6.68.0 or on your $PATH

and the like.

### PR DESCRIPTION
**Pull request by brandonpollack23**
Change #18951  introduced more robust plugin resolution, but convert has
some quirks that didn't set the "kind" field so resolution was not
working.  This fixes that, adds some testing, and some helpers to help
avoid this.

In the long run it'd be nice if mappers and plugin resolution used the
same functions, but this at least fixes it for now.

fixes #19039

### CODE REVIEW

File: pkg/codegen/convert/provider_factory.go [hunk 1]
```diff
@@ -31,6 +32,10 @@ type ProviderFactory func(descriptor workspace.PackageDescriptor) (plugin.Provid
 // lifecycles.
 func ProviderFactoryFromHost(ctx context.Context, host plugin.Host) ProviderFactory {
 	return func(descriptor workspace.PackageDescriptor) (plugin.Provider, error) {
+		if descriptor.Kind != apitype.ResourcePlugin {
```
Comment (Frassle) [inline pkg/codegen/convert/provider_factory.go:35]: Oh what? PackageDescriptor shouldn't even have a `Kind` field, it's _always_ a resource plugin. Looks like the fix is to unpick that field first.

Comment (brandonpollack23) [reply pkg/codegen/convert/provider_factory.go:35]: Well it should be set otherwise the underlying logic introduced [here](https://github.com/pulumi/pulumi/pull/18951/files#diff-196f5b7811e033d2523373f8138cca8c54eba850b419591283cd88a35828ac12R1104) wont work.  The localname depends on this being set

Comment (brandonpollack23) [reply pkg/codegen/convert/provider_factory.go:35]: alternatively I can just always et this right here to what it should be (but something tells me its better to crash and know what is misusing lest we overwrite something we thought was something else)

Comment (Frassle) [reply pkg/codegen/convert/provider_factory.go:35]: Oh yeh we changed it to just be a PluginSpec I forgot about that. In which case yeh just always making sure it's set to Resource is right.

**Review by Frassle — APPROVED** [review]

File: sdk/go/common/workspace/plugins.go [hunk 2]
```diff
@@ -909,6 +909,13 @@ type PackageDescriptor struct {
 	Parameterization *Parameterization
 }
 
+func NewPackageDescriptor(spec PluginSpec, parameterization *Parameterization) PackageDescriptor {
```
Comment (lunaris) [inline sdk/go/common/workspace/plugins.go:912]: Side note but I would question how much value there is in writing functions like this. Surely the struct with field names is more readable (now you have to unpick argument lists, which get longer if you add fields to a struct), and also in the case we use this, we pass `nil`, which with a struct wouldn't be necessary. If it did validation like `NewPluginSpec`, I could see an argument, but this feels a bit YAGNI right now (perhaps we have future plans though where this will be useful). Also we didn't add a doc comment (which TBH when writing might make us question how valuable the function is).

Comment (brandonpollack23) [reply sdk/go/common/workspace/plugins.go:912]: Your points are valid. I added this because if it existed before and was used it would prevent the bug this pr is fixing. 

You can still get it wrong by manually constructing the struct etc but I thought it's a bit more helpful

Comment (brandonpollack23) [reply sdk/go/common/workspace/plugins.go:912]: I thought about this more and I think it would have been better with the field that was missing as a parameter. Then it quickly gets out of hand. I guess just catching these as we did and having assertions more proactively is the best we can do actually and I regret adding it
