### PR TITLE
[go/codegen] Fix type collisions where InputType + "Map" clashes with resource type called "InputTypeMap"

### LINKED ISSUE #10527: Duplicate CertificateMap struct in certificatemanager
### What happened?

The `certmanager` package is unusable due to redefined structs `CertificateMap`.

Declaration [#1](https://github.com/pulumi/pulumi-gcp/blob/master/sdk/go/gcp/certificatemanager/certificate.go#L335) and [#2](https://github.com/pulumi/pulumi-gcp/blob/master/sdk/go/gcp/certificatemanager/certificateMap.go#L70).

### Steps to reproduce

snippet:

```
import (
	"github.com/pulumi/pulumi-gcp/sdk/v6/go/gcp/certificatemanager"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
    pulumi.Run(func(ctx *pulumi.Context) error {
	_, err := certificatemanager.NewCertificate(ctx, name, &certificatemanager.CertificateArgs{
		Project:     pulumi.String("my-project"),
		Managed: certificatemanager.CertificateManagedArgs{
			Domains: pulumi.ToStringArray([]string{"my-domain"},
		},
	})
	if err != nil {
		return nil, err
	}
    }
}
```

### Expected Behavior

To be able to import and use use `certificatemanager` and its methods.

### Actual Behavior

```
# github.com/pulumi/pulumi-gcp/sdk/v6/go/gcp/certificatemanager
    /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificateMap.go:70:6: CertificateMap redeclared in this block
        /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificate.go:335:6: other declaration of CertificateMap
    /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificateMap.go:101:98: cannot use &resource (value of type *CertificateMap) as type pulumi.Resource in argument to ctx.RegisterResource:
        *CertificateMap does not implement pulumi.Resource (missing URN method)
    /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificateMap.go:198:6: CertificateMapInput redeclared in this block
        /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificate.go:328:6: other declaration of CertificateMapInput
    /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificateMap.go:205:24: CertificateMap.ElementType redeclared in this block
        /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificate.go:337:23: other declaration of ElementType
    /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificateMap.go:209:26: CertificateMap.ToCertificateMapOutput redeclared in this block
        /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificate.go:341:25: other declaration of ToCertificateMapOutput
    /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificateMap.go:213:26: CertificateMap.ToCertificateMapOutputWithContext redeclared in this block
        /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificate.go:345:25: other declaration of ToCertificateMapOutputWithContext
    /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificateMap.go:267:6: CertificateMapOutput redeclared in this block
        /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificate.go:432:6: other declaration of CertificateMapOutput
    /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificateMap.go:269:29: CertificateMapOutput.ElementType redeclared in this block
        /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificate.go:434:29: other declaration of ElementType
    /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificateMap.go:273:31: CertificateMapOutput.ToCertificateMapOutput redeclared in this block
        /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificate.go:438:31: other declaration of ToCertificateMapOutput
    /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificateMap.go:277:31: CertificateMapOutput.ToCertificateMapOutputWithContext redeclared in this block
        /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificate.go:442:31: other declaration of ToCertificateMapOutputWithContext
    /Users/wolf/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v6@v6.35.0/go/gcp/certificatemanager/certificateMap.go:101:98: too many errors

    error: an unhandled error occurred: program exited with non-zero exit code: 2
```

### Output of `pulumi about`

pulumi about
CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME  VERSION
go    unknown

Host
OS       darwin
Version  12.5.1
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.19 darwin/arm64'

Current Stack: dev

TYPE                                         URN
*

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/joshrwolf
User           joshrwolf
Organizations  joshrwolf

No dependencies found

Pulumi locates its logs in /var/folders/5v/*/T/ by default

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Attempt to fix #10527

Here is a starting point with a minimal failing test and a schema that reproduces the issue 

I believe the idea is to skip generating the extra `InputType + "Map"` if the schema contains resources of that same type but we could also generate something else if a collision is found like `InputType + "Dictionary"` just in case but there will still be a chance of a type name collision.

This schema causes the same issue as with #10527 
```json
{
    "name": "world",
    "version": "0.0.1",
    "resources": {
        "world::WorldMap": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "world::Universe": {
            "type": "object",
            "inputProperties": {
                "worlds": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/types/world::World"
                    }
                }
            }
        }
    },
    "types": {
        "world::World": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        }
    }
}
```

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/codegen/go/gen.go [hunk 1]
```diff
@@ -1429,7 +1429,7 @@ func (pkg *pkgContext) genInputTypes(w io.Writer, t *schema.ObjectType, details
 	}
 
 	// Generate the array input.
-	if details.arrayInput {
+	if details.arrayInput && !pkg.names.Has(name+"Array") {
```
Comment (t0yv0) [inline pkg/codegen/go/gen.go:1432]: Reasoning out loud, so worst it can do here unintentionally is drop the helper arrayInput type that was relied on before, but it looks like it only does it if there's an actual conflict. This sounds reasonable! these arrayinput helper types are not quite used as much as normal resource types so this seems good.

**Review by t0yv0 — APPROVED** [review]
Encouraging that codegen tests pass without changes except for the new test case.
