### PR TITLE
Don't require ordered updates for `TestRefreshTargetChildren`

### LINKED ISSUE #18962: `TestRefreshTargetChildren` is flaky
```
=== FAIL: engine/lifecycletest TestRefreshTargetChildren (0.14s)
    target_test.go:118: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/pkg/engine/lifecycletest/target_test.go:118
        	Error:      	Not equal: 
        	            	expected: resource.PropertyValue***V:3***
        	            	actual  : resource.PropertyValue***V:2***
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,3 @@
        	            	 (resource.PropertyValue) ***
        	            	- V: (float64) 3
        	            	+ V: (float64) 2
        	            	 ***
        	Test:       	TestRefreshTargetChildren
    target_test.go:120: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/pkg/engine/lifecycletest/target_test.go:120
        	Error:      	Not equal: 
        	            	expected: resource.PropertyValue***V:2***
        	            	actual  : resource.PropertyValue***V:3***
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,3 @@
        	            	 (resource.PropertyValue) ***
        	            	- V: (float64) 2
        	            	+ V: (float64) 3
        	            	 ***
        	Test:       	TestRefreshTargetChildren
```

Seen this fail a couple of times now in a flaky manner. Example: https://github.com/pulumi/pulumi/actions/runs/13964609930/job/39092245402?pr=18951

### PR DESCRIPTION
**Pull request by i-am-tom**
Updates don't necessarily happen in a deterministic order _unless_ you run everything on one thread. Because CI doesn't, this test flakes every now and then depending on scheduling. This PR says that, instead of asserting specific values for each of the updated resources' properties, we just assert that they're no longer `null`.

Fixes #18962.

### CODE REVIEW

File: pkg/engine/lifecycletest/target_test.go [hunk 1]
```diff
@@ -112,12 +112,13 @@ func TestRefreshTargetChildren(t *testing.T) {
...
+
 	assert.Equal(t, snap.Resources[2].URN, b)
-	assert.Equal(t, snap.Resources[2].Outputs["count"], resource.NewPropertyValue(1.0))
+	assert.NotEqual(t, snap.Resources[2].Outputs["count"], null)
 	assert.Equal(t, snap.Resources[3].URN, c)
-	assert.Equal(t, snap.Resources[3].Outputs["count"], resource.NewPropertyValue(2.0))
+	assert.NotEqual(t, snap.Resources[3].Outputs["count"], null)
 	assert.Equal(t, snap.Resources[4].URN, d)
-	assert.Equal(t, snap.Resources[4].Outputs["count"], resource.NewPropertyValue(3.0))
+	assert.NotEqual(t, snap.Resources[4].Outputs["count"], null)
```
Comment (tgummerer) [inline pkg/engine/lifecycletest/target_test.go:121]: Instead of setting the `count` output property at all, should we assert that `callCount == 3` here?  The intention of the `count` output seems to have been to make sure that we call `ReadF` a certain number of times?

Comment (lunaris) [reply pkg/engine/lifecycletest/target_test.go:121]: Perhaps also have `ReadF` return a value that includes the URN with some deterministic thing? Then you can assert that each thing was read with a specific response?

Comment (i-am-tom) [reply pkg/engine/lifecycletest/target_test.go:121]: Ah, that's a neat idea! Updated the PR

Comment (i-am-tom) [reply pkg/engine/lifecycletest/target_test.go:121]: @lunaris Another neat idea, though I might leave that one for a follow-up in the interests of fixing the flake ASAP
