### PR TITLE
The `--expect-no-changes` flag checks for output diffs

### LINKED ISSUE #15564: --expect-no-changes doesn't fail on stack output changes
### What happened?

Ran `pulumi pre --expect-no-changes` on a stack that had changes in its outputs and the command ran without returning an error.

### Example

1. Deploy a stack that has `pulumi.export`s
2. Make a change to one of those exports
4. Run `pulumi pre --expect-no-changes`
5. Command doesn't fail

### Output of `pulumi about`

```
$ pulumi about

CLI
Version      3.108.0
Go Version   go1.22.0
Go Compiler  gc

Host
OS       darwin
Version  14.2.1
Arch     arm64
```

### Additional context

In our CI/CD runs we periodically check for unexpected changes. We use stack outputs heavily across stacks so unapplied changes in stack outputs can cause havoc in downstream dependant stacks.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by PollRobots**
# Description

This adds a pseudo op `OpOutputChange` to the set of changes that are recorded in `display.ResourceChanges` to count the number of output changes, this is then included in the check used to evaluate the `--expect-no-changes` flag

When resource outputs are registered, they are checked against their previous value using existing functionality, the total count of changes is then added

The internal capability is validated with an engine test, the cli is validated using an integration test

This will break user workflows that depend on the previous behavior

Fixes #15564

## Checklist

- [X] I have run `make tidy` to update any new dependencies
- [X] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [X] I have added tests that prove my fix is effective or that my feature works

- [X] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/cmd/pulumi/stack_history.go [hunk 1]
```diff
@@ -162,7 +163,9 @@ func displayUpdatesJSON(updates []backend.UpdateInfo, decrypter config.Decrypter
 			info.EndTime = makeStringRef(time.Unix(update.EndTime, 0).UTC().Format(timeFormat))
 			resourceChanges := make(map[string]int)
 			for k, v := range update.ResourceChanges {
-				resourceChanges[string(k)] = v
+				if k != deploy.OpOutputChange {
```
Comment (Frassle) [inline pkg/cmd/pulumi/stack_history.go:166]: Why do we filter out OpOutputChange here? That's not obvious from context, deserves an explanation comment.

File: pkg/engine/update.go [hunk 2]
```diff
@@ -657,9 +657,21 @@ func (acts *updateActions) OnResourceStepPost(
...
+		assertSeen(acts.Seen, step)
+
+		var oldOutputs resource.PropertyMap
+		if step.Old() != nil {
+			oldOutputs = step.Old().Outputs
+		}
+		newOutputs := step.New().Outputs
+		diff := oldOutputs.Diff(newOutputs)
+		if diff.AnyChanges() {
+			acts.Ops[deploy.OpOutputChange] += len(diff.Adds) + len(diff.Deletes) + len(diff.Updates)
```
Comment (Frassle) [inline pkg/engine/update.go:672]: Feels odd that this counts per-field changes rather than a count of how many resources made any change. Is there a reason to prefer this rather than just +1 here?

File: tests/integration/integration_nodejs_test.go [hunk 3]
```diff
@@ -823,7 +823,7 @@ func TestStackReferenceSecretsNodejs(t *testing.T) {
 			{
 				Dir:             filepath.Join(d, "nodejs", "step2"),
 				Additive:        true,
-				ExpectNoChanges: true,
+				ExpectNoChanges: false,
```
Comment (Frassle) [inline tests/integration/integration_nodejs_test.go:826]: Can just remove the field, it defaults to false.

File: pkg/engine/update.go (hunk 2 above)
Comment (PollRobots) [reply pkg/engine/update.go:672]: In the scenarios where this number is shown to the user, this then means that the number shown matches the listed output diffs

File: tests/integration/integration_nodejs_test.go (hunk 3 above)
Comment (PollRobots) [reply tests/integration/integration_nodejs_test.go]: Done

File: pkg/cmd/pulumi/stack_history.go (hunk 1 above)
Comment (PollRobots) [reply pkg/cmd/pulumi/stack_history.go:168]: Added a comment

**Review by Frassle — APPROVED** [review]

**Comment by PollRobots** [comment]
This is now safe with pulumi-service
