### PR TITLE
Fix rendering of output events in rendering update diffs

### LINKED ISSUE #17028: Diffs may render in an inconsistent order
### What happened?

This was first observed in the Pulumi Cloud console, and it's not obvious to this author what the code path is to reproduce locally. However, adding tests to `createDiff` highlights the inconsistent output.

### Example

This is an excerpt of the `up-truncate` test if run through the `createDiff` function:

```
    --outputs:--
    readme: "line 1\nline2\nline3\nline4"
        --outputs:--
        arn                : "arn:aws:iam::616138583583:role/eks-role-24b1266"
        assumeRolePolicy   : (json) {
            Statement: [
                [0]: {
                    Action   : "sts:AssumeRole"
                    Effect   : "Allow"
                    Principal: {
                        Service: "eks.amazonaws.com"
                    }
                    Sid      : ""
                }
            ]
            Version  : "2008-10-17"
        }

        createDate         : "2022-02-09T23:14:50Z"
        id                 : "eks-role-24b1266"
        inlinePolicies     : [
            [0]: {
                name  : ""
                policy: ""
            }
        ]
        managedPolicyArns  : [
            [0]: "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
            [1]: "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"
        ]
        uniqueId           : "AROAY65FYVYPWXZQUXMBX"
        --outputs:--
        id       : "eks-role-24b1266-20220209231452499500000001"
        --outputs:--
        id       : "eks-role-24b1266-20220209231452597100000002"
        --outputs:--
```

### Output of `pulumi about`

current

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by AaronFriel**
This fixes a bug found while working on another internal issue. This bug is reproduced in the first commit which adds tests, clearly showing the behavior of the incoherent rendering. The second commit makes the change and updates the tests.

Fixes #17028

Fixes all outputs being printed adjacent without context, as seen in the linked issue and the first commit:

```
    --outputs:--
    readme: "line 1\nline2\nline3\nline4"
        --outputs:--
        arn                : "arn:aws:iam::616138583583:role/eks-role-24b1266"
        assumeRolePolicy   : (json) {
            Statement: [
                [0]: {
                    Action   : "sts:AssumeRole"
                    Effect   : "Allow"
                    Principal: {
                        Service: "eks.amazonaws.com"
                    }
                    Sid      : ""
                }
            ]
            Version  : "2008-10-17"
        }

        createDate         : "2022-02-09T23:14:50Z"
        id                 : "eks-role-24b1266"
        inlinePolicies     : [
            [0]: {
                name  : ""
                policy: ""
            }
        ]
        managedPolicyArns  : [
            [0]: "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
            [1]: "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"
        ]
        uniqueId           : "AROAY65FYVYPWXZQUXMBX"
        --outputs:--
        id       : "eks-role-24b1266-20220209231452499500000001"
        --outputs:--
        id       : "eks-role-24b1266-20220209231452597100000002"
        --outputs:--
```

### CODE REVIEW

File: pkg/backend/display/diff.go [hunk 1]
```diff
@@ -483,3 +484,66 @@ func renderDiffResourceOutputsEvent(
 	}
 	return out.String()
 }
+
+// CreateDiff renders a view of the given events, enforcing an order of rendering that is consistent
+// with the diff view.
+func CreateDiff(events []engine.Event, displayOpts Options) (string, error) {
```
Comment (AaronFriel) [inline pkg/backend/display/diff.go:490]: This is exported so that it can be used in the service backend.

**Comment by pgavlin** [comment]
Can you add a description of the bug to the PR description? Not sure what to look for w.r.t. inconsistency in the output.

**Comment by AaronFriel** [comment]
@pgavlin done, and if you review the second commit you can see the before and after. The first commit adds tests that pass without any change in behavior.

**Comment by pgavlin** [comment]
> if you review the second commit you can see the before and after. The first commit adds tests that pass without any change in behavior.

Yeah, I took a look at the second commit prior to the description changes but it wasn't immediately clear what the actual issue was. This is what I was looking for:

> Fixes all outputs being printed adjacent without context

**Comment by pgavlin** [comment]
One q: how does this affect stack outputs (if it does at all)? I think from the code + tests that this should be strictly an improvement?

**Comment by AaronFriel** [comment]
@pgavlin ah, found the code path to produce this in the CLI. `pulumi up` with preview, then "details". 

With this, the stack outputs appear last, but at a lower indentation level than the resources - as everything parents from the stack. I don't think there's a clean way to fix that without implementing a sort on the events that could be out of scope for this PR.

```Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:redacted]
    ... [other resources]
        --aws:ecs/taskDefinition:TaskDefinition: (delete-replaced)
            [id=cloud-ai-2dec0ea]
            [...redacted...]
    --outputs:--
  + foo                         : "bar"
```

**Comment by pgavlin** [comment]
> With this, the stack outputs appear last, but at a lower indentation level than the resources - as everything parents from the stack. I don't think there's a clean way to fix that without implementing a sort on the events that could be out of scope for this PR.

Did they appear last prior to these changes as well?

File: pkg/backend/display/diff.go [hunk 2]
```diff
@@ -483,3 +484,52 @@ func renderDiffResourceOutputsEvent(
...
+	buff := &bytes.Buffer{}
+
+	seen := make(map[resource.URN]engine.StepEventMetadata)
+	displayOpts.SummaryDiff = true
+
+	if displayOpts.Color == "" {
+		// ColorizeWithMaxWidth panics if the colorization mode is not recognized, so we enforce it here.
+		return "", errors.New("color must be specified")
+	}
```
Comment (pgavlin) [inline pkg/backend/display/diff.go:499]: should we set a reasonable default instead of erroring?

**Comment by AaronFriel** [comment]
Yes, they do. The ordering of rendered `output` events is unchanged with respect to one another, before and after.

File: pkg/backend/display/diff.go (hunk 2 above)
Comment (arturl) [reply pkg/backend/display/diff.go:499]: +1. This is breaking change. The function did not return error before, why is this necessary now?

**Review by arturl — APPROVED** [review]
suggest to make the color error non-fatal.

File: pkg/backend/display/diff.go (hunk 2 above)
Comment (AaronFriel) [reply pkg/backend/display/diff.go:499]: It panicked before, actually. This protects against a panic in the server side code. I was unsure of choosing a default here where none existed before, but couldn't find any clear evidence either way.

Comment (AaronFriel) [reply pkg/backend/display/diff.go:499]: Panic on line 48, discovered while writing tests:

https://github.com/pulumi/pulumi/blob/e03d6f2c4cd1a282b6f6f2be18606c129ec02622/sdk/go/common/diag/colors/diag.go#L37-L48

Comment (arturl) [reply pkg/backend/display/diff.go:499]: Ah, I see. In that case, relaxing it is not needed, I withdraw my suggestion.

Comment (pgavlin) [reply pkg/backend/display/diff.go:499]: I think it's reasonable to treat `Never` as the default here. Though arguably a `panic` is the right thing inasmuch as some choice for colorization is a precondition?

Comment (pgavlin) [reply pkg/backend/display/diff.go:499]: (regardless, I don't think that this function should return an error--if a colorization is not specified, that's a programming error, not a runtime error)

Comment (AaronFriel) [reply pkg/backend/display/diff.go:499]: Aren't panics more expensive (and considered P0s/P1s?) - I would prefer to have a "safe but non-panicking" API that aborts early than one that conditionally panicks on a data-dependent path that could change in the future.

Comment (AaronFriel) [reply pkg/backend/display/diff.go:499]: @pgavlin if you're OK with it, maybe we default to colorization.Never (which produces "clean" text output).

I could go either way on keeping the return type `(string, error)`, in favor: forward API compatibility in case some other rendering option is fallible and bubbles up an error, against: it reinforces that this method _should_ be infallible.

Comment (pgavlin) [reply pkg/backend/display/diff.go:499]: > Aren't panics more expensive (and considered P0s/P1s?) - I would prefer to have a "safe but non-panicking" API that aborts early than one that conditionally panicks on a data-dependent path that could change in the future

FWIW if we were working in a language with enums, the colorization param would be of an enum type, which is what is is meant to be semantically. So I think panicking is in line with those semantics (and in general has been the philosophy throughout the product).

> if you're OK with it, maybe we default to colorization.Never (which produces "clean" text output).

Yeah I think that this is a fine approach. I think that removing the error parameter and using that default or removing the error and retaining the panic (or adding a `contract.Require` or something) would be great.
