### PR TITLE
Handle unconfigured plugins in Diff.

### LINKED ISSUE #2223: Step generator panics
This happens when I updated the username of a GKE cluster.

```
$ p up
warning: A new version of Pulumi is available. To upgrade from version '0.16.3-dev-1541007180-gb7489357-dirty' to '0.16.4', visit https://pulumi.io/install for manual instructions and release notes.
Previewing update (istio):

     Type                            Name         Plan       Info
     pulumi:pulumi:Stack             istio-istio
 ~   ├─ gcp:container:Cluster        gke-cluster  update     [diff: ~masterAuth]
 ~   └─ pulumi:providers:kubernetes  gkeK8s       update..   [diff: ~kubeconfig]
panic: fatal: An assertion has failed

goroutine 163 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(0x1abcd20, 0x17)
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xe9
github.com/pulumi/pulumi/pkg/util/contract.Assert(0xc00182d100)
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26 +0x49
github.com/pulumi/pulumi/pkg/resource/plugin.(*provider).Diff(0xc000b7da40, 0xc0018607e0, 0x6a, 0xc001081c40, 0x15, 0xc00137d6e0, 0xc0019a4d50, 0xc001238401, 0x0, 0x0, ...)
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/resource/plugin/provider_plugin.go:263 +0x3f2
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepGenerator).diff(0xc000174310, 0xc0018607e0, 0x6a, 0xc001081c40, 0x15, 0xc00137d530, 0xc00137d6e0, 0xc0019a4d50, 0x1bf2d00, 0xc000b7da40, ...)
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_generator.go:591 +0x121
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepGenerator).GenerateSteps(0xc000174310, 0x72c02a8, 0xc0019ba180, 0x0, 0x0, 0x0, 0xc0017a5c00)
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_generator.go:278 +0x1dbf
github.com/pulumi/pulumi/pkg/resource/deploy.(*planExecutor).handleSingleEvent(0xc0005e51c0, 0x1bdca40, 0xc0019ba180, 0xc0017a5cd8)
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_executor.go:211 +0x156
github.com/pulumi/pulumi/pkg/resource/deploy.(*planExecutor).Execute.func3(0xc0005e2720, 0xc0005e51c0, 0xc001613070, 0x1be9ba0, 0xc0005f4380, 0x1be9ba0, 0xc0005f4240, 0x10000, 0x1, 0xc0005d2280)
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_executor.go:171 +0x280
github.com/pulumi/pulumi/pkg/resource/deploy.(*planExecutor).Execute(0xc0005e51c0, 0x1be9ba0, 0xc0005f4240, 0x1be60e0, 0xc0005e6120, 0x7fffffff, 0x10000, 0x3030303030303001, 0x0, 0x0)
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_executor.go:187 +0x4c4
github.com/pulumi/pulumi/pkg/resource/deploy.(*Plan).Execute(0xc0005d8180, 0x1be9ba0, 0xc0005f4240, 0x1be60e0, 0xc0005e6120, 0x7fffffff, 0x10000, 0xc0003fea01, 0x1370000002f, 0x13700000000)
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan.go:286 +0x87
github.com/pulumi/pulumi/pkg/engine.(*planResult).Walk.func1(0x1be60e0, 0xc0005e6120, 0xc0005e6090, 0x1be9ba0, 0xc0005f4240, 0x1, 0xc001612fd0, 0xc0005e2240)
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/engine/plan.go:214 +0xc9
created by github.com/pulumi/pulumi/pkg/engine.(*planResult).Walk
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/engine/plan.go:206 +0x114

```

cc @swgillespie @pgavlin @lukehoban

### PR DESCRIPTION
**Pull request by pgavlin**
After #2088, we began calling `Diff` on providers that are not configured
due to unknown configuration values. This hit an assertion intended to
detect exactly this scenario, which was previously unexpected.

These changes adjust `Diff` to indicate that a Diff is unavailable and
return an error message that describes why. The step generator then
interprets the diff as indicating a normal update and issues the error
message to the diagnostic stream.

Fixes #2223.

### CODE REVIEW

**Comment by pgavlin** [comment]
Here's an example of the experience: https://asciinema.org/a/fUwanJGG2YcSbQ1PXUMDxopCx

**Comment by pgavlin** [comment]
I will add a test momentarily.

File: pkg/resource/plugin/provider_plugin.go [hunk 1]
```diff
@@ -257,10 +257,14 @@ func (p *provider) Diff(urn resource.URN, id resource.ID,
...
-	// If this function is called, we must have complete configuration for the underlying provider. Per DiffConfig,
-	// any unknown input will cause the provider to be replaced, which will cause all of its resources to be replaced,
-	// and we do not call `Diff` for resources that are being replaced due to a change to their provider reference.
-	contract.Assert(p.cfgknown)
+	// If the configuration for this provider was not fully known--e.g. if we are doing a preview and some input
+	// property was sourced from another resource's output properties--don't call into the underlying provider.
+	// Instead, indicate that the diff is unavailable and write a message
+	if !p.cfgknown {
+		logging.V(7).Infof("%s: cannot diff due to unknown config", label)
+		err := errors.New("cannot diff: this resource's provider has unknown configuration values")
```
Comment (swgillespie) [inline pkg/resource/plugin/provider_plugin.go]: "cannot diff" sounds like an error and not a warning and this warning isn't actionable for users. Could we do something like:

"This resource provider has inputs that are not known. Diffs of resources using this provider may be incorrect or unreliable."

File: pkg/engine/lifecycle_test.go [hunk 2]
```diff
@@ -911,6 +911,42 @@ func TestSingleResourceExplicitProviderDeleteBeforeReplace(t *testing.T) {
...
+		assert.NoError(t, err)
+		return nil
+	})
+	host := deploytest.NewPluginHost(nil, nil, program, loaders...)
+
+	p := &TestPlan{
+		Options: UpdateOptions{host: host},
+	}
+
+	// Run the initial update.
```
Comment (swgillespie) [inline pkg/engine/lifecycle_test.go]: not high-pri, so don't block on it, but it would be nice to assert that we actually emitted a warning as part of the test.

File: pkg/resource/deploy/step_generator.go [hunk 3]
```diff
@@ -275,7 +275,14 @@ func (sg *stepGenerator) GenerateSteps(event RegisterResourceEvent) ([]Step, *re
 			// Determine whether the change resulted in a diff.
 			d, diffErr := sg.diff(urn, old.ID, oldInputs, oldOutputs, inputs, prov, allowUnknowns)
 			if diffErr != nil {
-				return nil, result.FromError(diffErr)
+				// If the plugin indicated that the diff is unavailable, assume that the resource will be updated and
+				// report the message contained in the error.
+				if d.Changes == plugin.DiffUnavailable {
+					d.Changes = plugin.DiffSome
+					sg.plan.ctx.Diag.Warningf(diag.RawMessage(urn, diffErr.Error()))
```
Comment (swgillespie) [inline pkg/resource/deploy/step_generator.go]: We have the URN of the provider from the provider reference, right? can we issue the warning for that URN and not this resource? I think it would make more sense for this message to be attached to the provider since the message directly pertains to it.

File: pkg/resource/plugin/provider_plugin.go [hunk 4]
```diff
@@ -257,10 +257,14 @@ func (p *provider) Diff(urn resource.URN, id resource.ID,
...
+		return DiffResult{Changes: DiffUnavailable}, err
```
Comment (swgillespie) [inline pkg/resource/plugin/provider_plugin.go]: I don't think I like returning both an error and a non-empty `DiffResult` here - would it be sufficient to simply return `DiffUnavailable` here (or even something like `DiffUnavailableUnknownConfig`) and emit a warning in the step generator if you see it? It looks to me the error here is only for an error message and we might as well produce the warning text in the step generator.

File: pkg/resource/deploy/step_generator.go (hunk 3 above)
Comment (pgavlin) [reply pkg/resource/deploy/step_generator.go]: > I think it would make more sense for this message to be attached to the provider since the message directly pertains to it.

I think that this message needs to be associated with the resource: there is no visual indication that a resource and its provider are related, and it is the resource's diff that is affected.

File: pkg/resource/plugin/provider_plugin.go (hunk 4 above)
Comment (pgavlin) [reply pkg/resource/plugin/provider_plugin.go]: I do want the error text to be generated by the provider, as the provider has the best knowledge of why the diff cannot be computed. For example, we could go so far as to list the unknown config keys in the message.

I agree that what is in here isn't pretty. The other approach I considered was to use a distinguished error type for this, but this was expedient. If that approach sounds better, I can refactor.

File: pkg/resource/plugin/provider_plugin.go (hunk 1 above)
Comment (pgavlin) [reply pkg/resource/plugin/provider_plugin.go]: I originally had something like that, but I wanted to get the important bit--i.e. that the diff of the resource may not be accurate--at the front of the message.

File: pkg/resource/plugin/provider_plugin.go (hunk 4 above)
Comment (swgillespie) [reply pkg/resource/plugin/provider_plugin.go]: I'm fine with what you've got, I guess. I prefer distinguished error types in general because of Go's utter lack of any kind of sum type (which would be my favorite solution for `DiffUnavailable`)...

File: pkg/resource/plugin/provider_plugin.go (hunk 1 above)
Comment (swgillespie) [reply pkg/resource/plugin/provider_plugin.go]: I don't think `"cannot diff: this resource's provider has unknown configuration values"` accomplishes that, though - that message doesn't tell me that the diff won't be accurate. It just tell me that we couldn't diff it, which is a jargon-y way to say that it might not be accurate. I think it's better to explicitly say "might not be accurate" somewhere in the message.

Comment (pgavlin) [reply pkg/resource/plugin/provider_plugin.go]: Here are some other candidates:
`diff unavailable: ...`
`diff unknown: ...`
`unreliable diff: ...`
`diff may be unreliable: ...`

Comment (lukehoban) [reply pkg/resource/plugin/provider_plugin.go]: Yeah - I was about to suggest almost exactly what @swgillespie mentioned above after watching the screencast before seeing this thread.  I don't think "cannot diff" is clear at a level that users will understand.  I feel like this is an implementation details that is a layer or two beneath what the user can reason about.

As a slight play on @swgillespie's suggestion, what about:

"The provider for this resource has inputs that are not known during preview. Diffs of resources using this provider may not correctly capture the changes that will be applied during an update."

Comment (lukehoban) [reply pkg/resource/plugin/provider_plugin.go]: @pgavlin After seeing the implementation though - I'm not 100% sure that this error can only be reported under the conditions described in my proposed message above.  Is that your concern, that this error can happen in other cases?  If so, what are those other cases?

Comment (pgavlin) [reply pkg/resource/plugin/provider_plugin.go]: How about "The provider for this resource has inputs that are not known during preview. This preview may not correctly represent the changes that will be applied during an update."

Comment (pgavlin) [reply pkg/resource/plugin/provider_plugin.go]: > Is that your concern, that this error can happen in other cases?

Nope, the only time this should happen is during a preview. All values should be known at deploy time.

File: pkg/resource/plugin/provider_plugin.go (hunk 4 above)
Comment (pgavlin) [reply pkg/resource/plugin/provider_plugin.go]: Done.

File: pkg/engine/lifecycle_test.go (hunk 2 above)
Comment (pgavlin) [reply pkg/engine/lifecycle_test.go]: Done.

**Comment by pgavlin** [comment]
updated experience w/new error message: https://asciinema.org/a/UVzv5rtSy7Nllr7zaXj1LGhSl
