### PR TITLE
Propagate SIGINT to resource providers

### LINKED ISSUE #1613: ctrl-c should signal cancellation to resource provider
This work is semantically linked to https://github.com/pulumi/pulumi-kubernetes/issues/89. The goal is to allow users to press ctrl-c and for the provider to report an initialization failure (_i.e._, report that a resource was _created_ but failed to _initialize_).

The engine side of this issue consists of:

- [ ] Changing the gRPC interface for the provider to have a `Cancel` function, the semantics of which are to signal (using Go contexts) to all open requests that they should be cancelled.
- [ ] Have the ctrl-c signal handler call `Cancel`.

### PR DESCRIPTION
**Pull request by hausdorff**
Currently, the engine checks the cancellation context (which captures `SIGINT` from, _e.g._, a user pressing ctrl-c) only _between_ steps in the execution plan. In resource providers like Kubernetes, this has a large, negative impact on the experience, as many resources will loop continuously until timeout (_i.e._ 5 or 10 minutes), before the engine has the opportunity to cancel and exit.

This PR captures `SIGINT` and propagates it to the resource providers in the form of an RPC call on the resource provider, `Cancel`, so that they have a chance to cancel operations that are in flight. `Cancel` is _advisory_ and _non-blocking_; the intention is that the resource provider will cancel any in-flight operations, and subsequently return a relevant error. In the case of an `Update` or `Create` this should either be a creation error or an initialization error.

This PR will fix #1613.

This PR will also fix a pernicious (to me) issue of reproducible calls to build the `.proto` files.

### CODE REVIEW

File: pkg/engine/plan.go [hunk 1]
```diff
@@ -242,6 +242,14 @@ func (res *planResult) Walk(ctx *Context, events deploy.Events, preview bool) (d
 		rst, err = resource.StatusOK, nil
 	}()
 
+	// Asynchronously listen for cancellation, and deliver that signal to plan.
+	go func() {
+		select {
```
[the remark this answers is not in the document]
Comment (hausdorff) [reply pkg/engine/plan.go]: Unless I'm mistaken, that would cause this function to exit, which I think we _don't_ want, right? The semantics of this function are to exit on `Terminate`, no?

File: pkg/resource/plugin/provider_plugin.go [hunk 2]
```diff
@@ -520,6 +520,11 @@ func (p *provider) GetPluginInfo() (workspace.PluginInfo, error) {
 	}, nil
 }
 
+func (p *provider) SignalCancellation() error {
+	_, err := p.clientRaw.Cancel(p.ctx.Request(), &pbempty.Empty{})
```
[the remark this answers is not in the document]
Comment (hausdorff) [reply pkg/resource/plugin/provider_plugin.go]: For some reason I had thought in preliminary testing that this should "just work"... We can do this though.

**Comment by hausdorff** [comment]
Internet is pretty spotty and I only have time to work on this sporadically, so I'll fix the various issues as I have time...

File: pkg/engine/plan.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (swgillespie) [reply pkg/engine/plan.go]: This function will exit anyway the first time someone writes to `ctx.Cancel.Canceled()`, is that not what you want?

File: pkg/resource/plugin/host.go [hunk 3]
```diff
@@ -58,6 +60,13 @@ type Host interface {
 	// GetRequiredPlugins lists a full set of plugins that will be required by the given program.
 	GetRequiredPlugins(info ProgInfo, kinds Flags) ([]workspace.PluginInfo, error)
 
+	// SignalCancellation asks all resource providers to gragefully shut down and abort any ongoing
```
Comment (joeduffy) [inline pkg/resource/plugin/host.go]: Nit, gracefully

File: pkg/engine/plan.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (hausdorff) [reply pkg/engine/plan.go]: Oh, I see, sorry, I thought (on my phone) you were suggesting to move this to the select below. Yes, this makes sense. I don't have a good sense of idioms in Go yet...

File: pkg/resource/plugin/host.go [hunk 4]
```diff
@@ -387,6 +398,22 @@ func (host *defaultHost) GetRequiredPlugins(info ProgInfo, kinds Flags) ([]works
...
+	var buf bytes.Buffer
+	for _, plug := range host.resourcePlugins {
+		if err := plug.Plugin.SignalCancellation(); err != nil {
+			buf.WriteString(fmt.Sprintf("%s\n", err.Error()))
+			logging.Infof("Error cancelling '%s' resource plugin during shutdown; ignoring: %v", plug.Info.Name, err)
+		}
+	}
+
+	if err := buf.String(); err != "" {
+		return fmt.Errorf("Failed to delete resource plugin(s):\n%s", err)
```
Comment (joeduffy) [inline pkg/resource/plugin/host.go]: "Failed to cancel"?

File: pkg/resource/plugin/host.go [hunk 5]
```diff
@@ -387,6 +398,22 @@ func (host *defaultHost) GetRequiredPlugins(info ProgInfo, kinds Flags) ([]works
 	return plugins, nil
 }
 
+func (host *defaultHost) SignalCancellation() error {
+	var buf bytes.Buffer
+	for _, plug := range host.resourcePlugins {
+		if err := plug.Plugin.SignalCancellation(); err != nil {
+			buf.WriteString(fmt.Sprintf("%s\n", err.Error()))
```
Comment (joeduffy) [inline pkg/resource/plugin/host.go]: We usually use the go-multierror package for this sort of thing.

File: sdk/Dockerfile [hunk 6]
```diff
@@ -0,0 +1,46 @@
+# Copyright 2016-2018, Pulumi Corporation.
```
Comment (joeduffy) [inline sdk/Dockerfile]: Is this an intentional inclusion? Didn't immediately appear related...

Comment (joeduffy) [reply sdk/Dockerfile]: Ahhh I see, for the proto tools. Neat. Should it be in the proto subdir?

File: pkg/resource/plugin/host.go (hunk 5 above)
Comment (joeduffy) [reply pkg/resource/plugin/host.go]: I'd prefer if this function faithfully aggregated the errors and returned them. Then let the caller -- which for this particular case wants to ignore errors -- decide what to do.

File: pkg/engine/plan.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (hausdorff) [reply pkg/engine/plan.go]: Actually I think we want to do something like this, to avoid leaking the goroutine:

```
	// Asynchronously listen for cancellation, and deliver that signal to plan.
	go func() {
		select {
		case <-ctx.Cancel.Canceled():
			res.Plan.SignalCancellation()
		case <-done:
			return
		}
	}()
```

File: pkg/resource/plugin/host.go (hunk 5 above)
Comment (hausdorff) [reply pkg/resource/plugin/host.go]: Not sure I fully understand the second message, but I've wrapped this in `multierror`, which is what I think you want...

File: sdk/Dockerfile (hunk 6 above)
Comment (hausdorff) [reply sdk/Dockerfile]: I thought it should here because that directory only has proto files in it, but I don't feel strongly so lets do it your way.

File: pkg/engine/plan.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (swgillespie) [reply pkg/engine/plan.go]: Sounds good to me. I don't think we care much about leaking goroutines since we're generally exiting pretty quickly.
