### PR TITLE
Avoid backfilling property deps for Go

### LINKED ISSUE #10951: Presence of pulumi.DependsOn results in a runtime error
### What happened?

Presence of pulumi.DependsOn results in an error: resources.MyComponent.MyEnumProp is typed as *string but must be a type that implements pulumi.Input or pulumi.Output for input with dependencies

### Steps to reproduce

Using a go generated MLC, create a simple example that creates a resource and uses `pulumi.DependsOn` targeting a dependent resource.

### Expected Behavior

`pulumi up` succeeds

### Actual Behavior

Program fails with `resources.MyComponent.MyEnumProp is typed as *string but must be a type that implements pulumi.Input or pulumi.Output for input with dependencies`

### Additional context

Internal Slack Thread: https://pulumi.slack.com/archives/C01028X5X3K/p1665508743426729

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
Two changes:

## 1. Go SDK

Change the Go SDK to always send a filled-in property dependencies map, which is consistent with all of the other language SDKs. This prevents the engine from backfilling an empty map with explicit dependencies specified in the `pulumi.DependsOn` `ResourceOption`.

**Node.js:**

https://github.com/pulumi/pulumi/blob/a4dbd1da4fb0b5df716aeda56f9caf7d2d5175e4/sdk/nodejs/runtime/rpc.ts#L140-L143

**Python:**

https://github.com/pulumi/pulumi/blob/a4dbd1da4fb0b5df716aeda56f9caf7d2d5175e4/sdk/python/lib/pulumi/runtime/rpc.py#L211-L223

**.NET:**

https://github.com/pulumi/pulumi/blob/a4dbd1da4fb0b5df716aeda56f9caf7d2d5175e4/sdk/dotnet/Pulumi/Deployment/Deployment_Serialization.cs#L79-L83

**Java:**

https://github.com/pulumi/pulumi-java/blob/33e2d98ad96890937f5374e7b6699fc518edfc19/sdk/java/pulumi/src/main/java/com/pulumi/serialization/internal/PropertiesSerializer.java#L67-L72

## 2. Engine

Stop doing the backfilling in the engine when remote is true, because all clients that support remote already support passing property dependencies, so there's no need to backfill. The backfill behavior was meant for very old clients that didn't support sending property dependencies.

Fixes #10951

### CODE REVIEW

**Review by AaronFriel — APPROVED** [review]
Good change, lgtm.

File: pkg/resource/deploy/source_eval.go [hunk 1]
```diff
@@ -1054,9 +1054,10 @@ func (rm *resmon) RegisterResource(ctx context.Context,
 	}
 
 	propertyDependencies := make(map[resource.PropertyKey][]resource.URN)
-	if len(req.GetPropertyDependencies()) == 0 {
+	if len(req.GetPropertyDependencies()) == 0 && !remote {
 		// If this request did not specify property dependencies, treat each property as depending on every resource
-		// in the request's dependency list.
+		// in the request's dependency list. We don't need to do this when remote is true, because all clients that
+		// support remote already support passing property dependencies, so there's no need to backfill here.
```
Comment (iwahbe) [inline pkg/resource/deploy/source_eval.go:1060]: I'm assuming we are ok with telling people that they need to upgrade their 3.1.0 SDKs here.

**Review by iwahbe — APPROVED** [review]
Short and sweet. LGTM!

File: pkg/resource/deploy/source_eval.go (hunk 1 above)
Comment (justinvp) [reply pkg/resource/deploy/source_eval.go:1060]: What's special about 3.1.0 SDKs and why would we need to tell them to upgrade?

Backfilling the property dependencies like this is only an issue for remote components when you have a property that is plain and isn't supposed to be able to have any dependencies associated with it. For register resource calls where remote is false, it doesn't matter.

We added support for remote components in the Go SDK in v2.13.0. Any version of the Go SDK v2.13.0 or higher passing `remote == true` will get this fix when running against a CLI that has this engine change.

**Comment by justinvp** [comment]
bors merge

File: pkg/resource/deploy/source_eval.go (hunk 1 above)
Comment (iwahbe) [reply pkg/resource/deploy/source_eval.go:1060]: Sorry for the unclear comment. 3.1.0 is an arbitrary early version number I picked. What I meant was:

From the comment, it sounds like their used to be clients that supported remote but didn't support passing property dependencies. It seems like this will break them. I'm assuming that this break is acceptable because we can tell them to upgrade, and everything should start working again.

Comment (justinvp) [reply pkg/resource/deploy/source_eval.go:1060]: It won't break anyone. Users running Go SDK version < v2.13.0 aren't passing `remote`, so there's no behavior change.
