### PR TITLE
Ensure package generation for Go SDKs doesn't panic when encountering overly nested arrays or maps of primitive types

### LINKED ISSUE #15478: Go codegen panics for type `Map<Array<string>>`
Version: 3.105.0

## Stack trace

```
Generating go...
panic: fatal: An assertion has failed: tok: string

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.105.0/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0xd2?, {0x105973813?, 0x105f00b18?}, {0x14006c9f5a8?, 0x0?, 0x1?})
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.105.0/go/common/util/contract/assert.go:35 +0xe0
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*pkgContext).tokenToType(0x140020c4d80, {0x1059712d2, 0x6})
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.105.0/codegen/go/gen.go:213 +0x9c
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*pkgContext).nestedTypeToType(0x1401486ff10?, {0x1063871f8?, 0x106f45038?})
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.105.0/codegen/go/gen.go:3398 +0x168
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*pkgContext).nestedTypeToType(0x14006c9f6f8?, {0x106387108?, 0x1401484e0c0?})
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.105.0/codegen/go/gen.go:3390 +0x98
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*pkgContext).collectNestedCollectionTypes(0x140020c4d80, 0x14006c9f910, {0x1063870e0?, 0x140148f93e0?})
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.105.0/codegen/go/gen.go:3315 +0x13c
github.com/pulumi/pulumi/pkg/v3/codegen/go.generateTypes({0x106379c88, 0x1400b1b0060}, 0x140020c4d80, {0x1400c6740c0, 0x6, 0x8}, {0x1400689c000, 0x2d, 0x0?}, 0x0)
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.105.0/codegen/go/gen.go:4883 +0x1fc
github.com/pulumi/pulumi/pkg/v3/codegen/go.GeneratePackage({0x105994dd5, 0x18}, 0x1401398ad80)
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.105.0/codegen/go/gen.go:4797 +0x2388
main.generate(0x105978c81?, {0x16b5834d0, 0x2})
        /Users/dan/Dev/pulumi-aws-native/provider/cmd/pulumi-gen-aws-native/main.go:298 +0x94
main.emitPackage(0x140112077a0?, {0x16b5834d0, 0x2}, {0x14014607c38, 0x6})
        /Users/dan/Dev/pulumi-aws-native/provider/cmd/pulumi-gen-aws-native/main.go:313 +0x94
main.main()
        /Users/dan/Dev/pulumi-aws-native/provider/cmd/pulumi-gen-aws-native/main.go:93 +0x658
make: *** [local_generate] Error 2
```

## Type definition to repro:

```json
{
    "types": {
        "aws-native:inspectorv2:CisScanConfigurationCisTargets": {
            "properties": {
                "accountIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "targetResourceTags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "type": "object",
            "required": [
                "accountIds"
            ]
        }
    }
}
```

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

Fixes #15478 where sdk-gen should no longer panic when encountering overly nested arrays or maps of primitive types. The generated code still fails to compile but validation can be added later to cover cases where we are missing primitives in the core SDK to handle overly nested type definitions.

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/codegen/testing/test/sdk_driver.go [hunk 1]
```diff
@@ -266,6 +266,12 @@ var PulumiPulumiSDKTests = []*SDKTest{
 		Description: "Regress pulumi/pulumi#12971 affecting Go",
 		Skip:        allLanguages.Except("go/any"),
 	},
+	{
+		Directory:        "regress-go-15478",
+		Description:      "Regress pulumi/pulumi#15478 affecting Go ensuring SDK-gen doesn't panic",
+		Skip:             allLanguages.Except("go/any"),
+		SkipCompileCheck: codegen.NewStringSet(golang),
```
Comment (justinvp) [inline pkg/codegen/testing/test/sdk_driver.go:273]: Should we add a comment here? We're deliberately skipping right now because we don't expect it to be able to compile due to missing deeply nested container types in the core Go SDK.

**Review by justinvp — APPROVED** [review]
LGTM

File: tests/testdata/codegen/regress-go-15478/schema.json [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+            "type": "array",
+            "items": {
+              "type": "array",
+              "items": {
+                "type": "string"
+              }
+            }
+          }
+        }
+      },
```
Comment (Frassle) [inline tests/testdata/codegen/regress-go-15478/schema.json:19]: should probably add map/map/map as well

Comment (Zaid-Ajaj) [reply tests/testdata/codegen/regress-go-15478/schema.json:31]: Done ✅
