### PR TITLE
`--import-file` now omits empty resource lists.

### LINKED ISSUE #15041: `pulumi preview --import-file...` against a stack with resources produces a panic
### What happened?

A panic occurs when running `pulumi preview --import-file ...` against a stack that contains resources.

### Example

`pulumi up` the below program to ensure the stack has resources:
```
import * as awsx from "@pulumi/awsx";

new awsx.ec2.Vpc("vpc", {
    cidrBlock: "10.100.0.0/16"
});
```

next, execute `pulumi preview --import-file some-json.json`

panic:
```
panic: runtime error: index out of range [0] with length 0

goroutine 65 [running]:
main.newPreviewCmd.func1.buildImportFile.func1()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/preview.go:91 +0x140a
github.com/pulumi/pulumi/sdk/v3/go/common/promise.Run[...].func1()
	/home/runner/work/pulumi/pulumi/sdk/go/common/promise/promise.go:150 +0x2c
created by github.com/pulumi/pulumi/sdk/v3/go/common/promise.Run[...] in goroutine 1
	/home/runner/work/pulumi/pulumi/sdk/go/common/promise/promise.go:149 +0x90
```

### Output of `pulumi about`

pulumi/pulumi 3.99

### Additional context

cc @Frassle 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description

Fixes #15041

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by tgummerer — APPROVED** [review]

File: pkg/cmd/pulumi/import_test.go [hunk 1]
```diff
@@ -456,10 +459,23 @@ func TestImportFileMarshal(t *testing.T) {
...
-	enc.SetIndent("", "  ")
-	err := enc.Encode(importFile)
-	require.NoError(t, err)
-	assert.Equal(t, expected, buffer.String())
+		var buffer bytes.Buffer
+		enc := json.NewEncoder(&buffer)
+		enc.SetIndent("", "  ")
+		err := enc.Encode(importFile)
+		require.NoError(t, err)
+		assert.Equal(t, expected, buffer.String())
```
Comment (Frassle) [inline pkg/cmd/pulumi/import_test.go:467]: Minor and can clean this up later but given this encode/equals check is the same for both test cases this would be slightly nicer as a table driven test.

Comment (dixler) [reply pkg/cmd/pulumi/import_test.go:467]: Top one uses equals whereas the bottom is using contains. Could be reduced to table tests, but the amount of indirection added to support just these two seems not worth it at the moment.

Comment (Frassle) [reply pkg/cmd/pulumi/import_test.go:467]: Fair enough.
