### PR TITLE
[display] fix ComponentResource deletion not stopping time elapsed timer

### LINKED ISSUE #13357: Component deletion continues to show in-progress although all resources have been deleted
### What happened?

Pulumi continues to show a component resources as `deleting` even though all the resources within the component has been deleted (see screenshot).

### Expected Behavior

A component should be marked as `deleted` when all resources within a component are deleted.

### Steps to reproduce

I'm unclear on how to repro this, but it seems to occur when a component resource depends on another component resources. Eg- component A creates a kubernetes cluster and component B deploys kubernetes resources into the cluster created by component A.

image

### Output of `pulumi about`

▶ pulumi about
CLI
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.103.0
azuread       4.3.0
kubernetes    3.29.1
nodejs        unknown
random        4.13.2
tls           4.10.0

Host
OS       darwin
Version  13.2.1
Arch     x86_64

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description

Fixes #13357

ComponentResources now emit resourceOutputEvent on delete
steps. This fixes the time elapsed timer not stopping when the resource
is deleted.

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

**Review by Frassle — APPROVED** [review]
Looks alright

File: pkg/engine/update_test.go [hunk 1]
```diff
@@ -49,3 +54,42 @@ func TestAbbreviateFilePath(t *testing.T) {
 		assert.Equal(t, filepath.ToSlash(tt.expected), filepath.ToSlash(actual))
 	}
 }
+
+func TestDeletingCustomResourceProducesResourceOutputsEvent(t *testing.T) {
```
Comment (justinvp) [inline pkg/engine/update_test.go:58]: Are we testing custom resources or component (non-custom) resources? I _think_ the intention is to actually test component resources, but am I misunderstanding the test?

```suggestion
func TestDeletingComponentResourceProducesResourceOutputsEvent(t *testing.T) {
```

File: changelog/pending/20230927--engine--non-custom-componentresources-now-emit-resourceoutputevent-on-deletion-this-fixes-the-time-elapsed-timer-not-ending-when-the-resource-is-deleted.yaml [hunk 2]
```diff
@@ -0,0 +1,4 @@
+changes:
+- type: fix
+  scope: engine
+  description: non-custom ComponentResources now emit resourceOutputEvent on Deletion. This fixes the time elapsed timer not ending when the resource is deleted.
```
Comment (justinvp) [inline changelog/pending/20230927--engine--non-custom-componentresources-now-emit-resourceoutputevent-on-deletion-this-fixes-the-time-elapsed-timer-not-ending-when-the-resource-is-deleted.yaml:4]: Nit:

```suggestion
  description: ComponentResources now emit resourceOutputEvent on Deletion. This fixes the time elapsed timer not ending when the resource is deleted.
```

File: pkg/engine/update_test.go [hunk 3]
```diff
@@ -49,3 +54,42 @@ func TestAbbreviateFilePath(t *testing.T) {
...
+	acts := newUpdateActions(&Context{
+		Cancel: cancelCtx,
+	}, nil, deploymentOptions{})
+	eventsChan := make(chan Event, 10)
+	acts.Opts.Events.ch = eventsChan
+
+	step := deploy.NewDeleteStep(&deploy.Deployment{}, map[resource.URN]bool{}, &resource.State{
+		URN:      resource.URN("urn:pulumi:stack::project::my:example:Foo::foo"),
+		ID:       "foo",
+		Custom:   true,
```
Comment (justinvp) [inline pkg/engine/update_test.go:72]: Does this test pass without the product change? Shouldn't this be `false` to test component resources?

```suggestion
		Custom:   false,
```

**Review by justinvp — COMMENTED** [review]
Before, when I'd run the destroy, the final result would show the following. Notice how `pulumi:pulumi:Stack` and `my:example:Noop` don't have a time suffix:

```
     Type                                  Name              Status
 -   pulumi:pulumi:Stack                   sleepdisplay-dev  deleted
 -   ├─ my:example:Noop                    a                 deleted
 -   │  ├─ pulumi-nodejs:dynamic:Resource  a-c               deleted (5s)
 -   │  ├─ pulumi-nodejs:dynamic:Resource  a-b               deleted (5s)
 -   │  └─ pulumi-nodejs:dynamic:Resource  a-a               deleted (5s)
 -   └─ pulumi-nodejs:dynamic:Resource     b                 deleted (10s)
```

With this change, after the destroy is complete, the final result is as follows. Notice the stack and component now have the timings.

```
     Type                                  Name              Status
 -   pulumi:pulumi:Stack                   sleepdisplay-dev  deleted (0.23s)
 -   ├─ my:example:Noop                    a                 deleted (0.12s)
 -   │  ├─ pulumi-nodejs:dynamic:Resource  a-b               deleted (5s)
 -   │  ├─ pulumi-nodejs:dynamic:Resource  a-c               deleted (5s)
 -   │  └─ pulumi-nodejs:dynamic:Resource  a-a               deleted (5s)
 -   └─ pulumi-nodejs:dynamic:Resource     b                 deleted (10s)
```

Do we care? I think the new behavior is OK, but wanted to call out the difference. It does make `deleted` consistent with `updated` where on a `pulumi up` (even without the change in this PR) the stack and component do get timings for `updated`, e.g.:

```
     Type                                  Name              Status
 +   pulumi:pulumi:Stack                   sleepdisplay-dev  created (0.55s)
 +   ├─ pulumi-nodejs:dynamic:Resource     b                 created (0.09s)
 +   └─ my:example:Noop                    a                 created (0.36s)
 +      ├─ pulumi-nodejs:dynamic:Resource  a-a               created (0.11s)
 +      ├─ pulumi-nodejs:dynamic:Resource  a-c               created (0.21s)
 +      └─ pulumi-nodejs:dynamic:Resource  a-b               created (0.31s)
```

Note: I checked and the rendering in Pulumi Cloud is the same as all of the above.

**Comment by dixler** [comment]
> Do we care? I think the new behavior is OK, but wanted to call out the difference. It does make `deleted` consistent with `updated` where on a `pulumi up` (even without the change in this PR) the stack and component do get timings for `updated`, e.g.:
> 
> ```
>      Type                                  Name              Status
>  +   pulumi:pulumi:Stack                   sleepdisplay-dev  created (0.55s)
>  +   ├─ pulumi-nodejs:dynamic:Resource     b                 created (0.09s)
>  +   └─ my:example:Noop                    a                 created (0.36s)
>  +      ├─ pulumi-nodejs:dynamic:Resource  a-a               created (0.11s)
>  +      ├─ pulumi-nodejs:dynamic:Resource  a-c               created (0.21s)
>  +      └─ pulumi-nodejs:dynamic:Resource  a-b               created (0.31s)
> ```
> 
> Note: I checked and the rendering in Pulumi Cloud is the same as all of the above.

I think it makes sense since this is normal for normal pulumi up.

**Review by justinvp — APPROVED** [review]
