### PR TITLE
unflake TestNodejsComponentProviderRun

### LINKED ISSUE #22761: `TestNodejsComponentProviderRun/yaml` is flaky
```
=== FAIL: integration TestNodejsComponentProviderRun/yaml (57.96s)
    program.go:2046: sample: component_provider/nodejs/component-provider-host
    program.go:2051: pulumi: /home/runner/work/pulumi/pulumi/bin/pulumi
    integration_nodejs_test.go:3166: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/tests/integration/integration_nodejs_test.go:3166
        	            				/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:2220
        	            				/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:2161
        	            				/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:1293
        	            				/home/runner/work/pulumi/pulumi/tests/integration/integration_nodejs_test.go:3157
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestNodejsComponentProviderRun/yaml
        	Messages:   	/home/runner/work/pulumi/pulumi/bin/pulumi package add /tmp/p-it-runnervmeo-component--3b326b03-2419199425/provider failed with: Installing dependencies...
        	            	
        	            	yarn install v1.22.22
        	            	[1/4] Resolving packages...
        	            	success Already up-to-date.
        	            	Done in 0.54s.
        	            	Finished installing dependencies
        	            	
        	            	Downloading provider: tls
        	            	Downloading provider: terraform-provider
        	            	Downloading provider: random
        	            	error: failed to bind schema: error binding resource nodejs-component-provider:index:MyComponent: failed to bind properties for nodejs-component-provider:index:MyComponent: error binding type for property "aResourceOutput": resolving package /random/v4.18.0/schema.json#/resources/random:index%2FrandomPet:RandomPet: Error loading schema from plugin: failed to load plugin /home/runner/work/pulumi/pulumi/home/plugins/resource-random-v4.18.0/pulumi-resource-random: loading PulumiPlugin.yaml: open /home/runner/work/pulumi/pulumi/home/plugins/resource-random-v4.18.0/PulumiPlugin.yaml: no such file or directory
```

From https://github.com/pulumi/pulumi/actions/runs/25099755238/job/73560150270?pr=22750

### PR DESCRIPTION
**Pull request by tgummerer**
These subtests can run into a race condition, as seen in https://github.com/pulumi/pulumi/issues/22761.  Claude has tracked this down to the tests all using the same PULUMI_HOME which seems plausigle.  Use a tmpdir instead to try and avoid this test flaking.

Fixes https://github.com/pulumi/pulumi/issues/22761

### CODE REVIEW

File: tests/integration/integration_nodejs_test.go [hunk 1]
```diff
@@ -3154,20 +3154,31 @@ func TestNodejsComponentProviderRun(t *testing.T) {
 	//nolint:paralleltest // t.Parallel is called by integration.ProgramTest
 	for _, runtime := range []string{"yaml", "python", "nodejs-pnpm", "nodejs-npm"} {
 		t.Run(runtime, func(t *testing.T) {
+			// Each subtest needs its own PULUMI_HOME to avoid race conditions when
+			// multiple subtests concurrently download and install the same provider
+			// plugins.
```
Comment (Frassle) [inline tests/integration/integration_nodejs_test.go:3159]: oooh we should fix this properly. Can we issue and TODO this that these tests should be able to share a HOME.

**Review by Frassle — APPROVED** [review]

File: tests/integration/integration_nodejs_test.go (hunk 1 above)
Comment (tgummerer) [reply tests/integration/integration_nodejs_test.go:3159]: Done, opened #22784 and added a TODO here.
