### PR TITLE
Fix stack selection behavior

### LINKED ISSUE #11407: Pulumi delete not working as expected in version v3.47.0
### What happened?

I get an error message displayed, when trying to delete a Pulumi stack:

```bash
❯ pulumi destroy -y -f
Please choose a stack: 
error: parsing selected stack: stack names may only contain alphanumeric, hyphens, underscores, and periods
```

Looks related to https://github.com/pulumi/pulumi/issues/11334

### Steps to reproduce

Delete a Pulumi stack via `pulumi destroy -y -f`

### Expected Behavior

The Stack gets deleted

### Actual Behavior

Error message: 

```bash
error: parsing selected stack: stack names may only contain alphanumeric, hyphens, underscores, and periods
```

### Output of `pulumi about`

```bash
pulumi about 
CLI          
Version      3.47.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.21.0
docker  3.6.0
go      unknown

Host     
OS       darwin
Version  12.5
Arch     arm64

This project is written in go: executable='/opt/homebrew/Cellar/go/1.19.3/libexec/bin/go' version='go version go1.19.3 darwin/arm64'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/dirien
User           dirien
Organizations  dirien

Dependencies:
NAME                                    VERSION
github.com/pulumi/pulumi-aws/sdk/v5     5.21.0
github.com/pulumi/pulumi-docker/sdk/v3  3.6.0
github.com/pulumi/pulumi/sdk/v3         3.46.1
```

### Additional context

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by aq17**
# Description

Fixes #11407 
Follow on to PR [11354](https://github.com/pulumi/pulumi/pull/11354). When we don't prompt to `create a new stack`, we should default to an existing stack so the empty string isn't populated.

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/cmd/pulumi/util.go [hunk 1]
```diff
@@ -367,6 +369,10 @@ func chooseStack(ctx context.Context,
 	} else if len(options) == 0 {
 		// If no options are available, we can't offer a choice!
 		return nil, errors.New("this command requires a stack, but there are none")
+	} else {
+		if defaultOption == "" {
```
Comment (dixler) [inline pkg/cmd/pulumi/util.go:373]:
```suggestion
	} else if defaultOption == "" && len(options) > 0 {
```
Nit: line 374 implicitly depends on the check on line 369. Adding the explicit check to this `else` case allows us to more closely couple our assumptions.

**Review by dixler — APPROVED** [review]
Small nit, but other than that LGTM.

File: pkg/cmd/pulumi/util.go (hunk 1 above)
Comment (aq17) [reply pkg/cmd/pulumi/util.go]: Actually it can just be `else if defaultOption == ""` since we already checked that options is not empty
