### PR TITLE
Make the path to .pulumi folder configurable with an ENV variable

### LINKED ISSUE #2966: change or customize plugin install location
When using nodejs, pulumi plugins are automatically installed upon `npm install`.
However the plugins are not installed alongside the node_modules directory but in the global user home under `~/.pulumi/plugins`. This is kinda surprising for nodejs users which are used to have all their deps self-contained under node_modules. I suspect the same applies to advanced python users which expects all their deps to be contained in a workspace local virtualenv.
 
While this behavior is normally not a big deal on a local machine, it caused me multiple times some headache in CI environments. Particularly there are some CI systems, e.g. codefresh, which pass the working directory / volume from container to container (sometimes called "container chains") and other CI systems which have explicit caching support for certain working directories.
The fact that pulumi installs plugin outside the working directory, in a "somewhat" not fully stable location (i.e. the absolute path depends on OS and username of the container in which the install command was executed) oft led to situations in CI where the pulumi node_modules were present, but the plugins not and failed the pipeline with an error similar to this:
```
error: could not load plugin for kubernetes provider 'urn:pulumi:api-events-staging::api-events::pulumi:providers:kubernetes::api-cluster
-dev-a': no resource plugin 'kubernetes' found in the workspace or on your $PATH     
```

If this occurs, there is not even a way to "install the missing plugins", other than by nuking the entire node_modules directory and download all dependencies (not only pulumi plugins) from scratch.

Therefore I'd like to request a change in this behaviour, especially something that considers the needs of CI environments.

A few ideas I had:
1. Add an environment variable override like `PULUMI_PLUGIN_LOCATION` which can be used to override the default plugin (install and search) location.
2. Install pulumi plugins into node_modules instead of home directory. This could be optionally controlled via an environment variables as well.
3. Automatic lazy fetching of plugins by language SDKs, if a plugin is not present at runtime.

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Introduces `PULUMI_HOME` environment variable which points to a path to the path to `.pulumi` folder. Defaults to `<user's home dir> + ".pulumi"` if not specified.

Fixes #2966. In addition to plugins, it "moves" the credentials file, templates, workspaces.

`bin` folder is intact: to move it, we need to adjust all installation scripts to respect `PULUMI_HOME` and put executables in the proper `bin` folder.

### CODE REVIEW

File: pkg/workspace/paths.go [hunk 1]
```diff
@@ -61,6 +61,10 @@ const (
 	WorkspaceFile = "workspace.json"
 	// CachedVersionFile is the name of the file we use to store when we last checked if the CLI was out of date
 	CachedVersionFile = ".cachedVersionInfo"
+
+	// PulumiBookkeepingLocationEnvVar is a path to the folder where '.pulumi' folder is stored.
+	// The path should not include '.pulumi' itself. It defaults to the user's home dir if not specified.
+	PulumiBookkeepingLocationEnvVar = "PULUMI_BOOKKEEPING_LOCATION"
```
Comment (lukehoban) [inline pkg/workspace/paths.go]: The name "bookkeeping" feels a bit unusual here for a public facing thing.  Should it be `PULUMI_HOME_DIR`? or `PULUMI_HOME`?

**Comment by lukehoban** [comment]
> If this change is okay, we also need to adjust all installation scripts to respect the same variable and put executables in the proper bin folder.

I do think we should do this - but I *believe* this is technically orthogonal (the PR as is will work without this, and there is no reason the binaries need to be in the same `.pulumi` folder as the rest of these artifacts).

**Comment by lukehoban** [comment]
cc also @nesl247 and @geekflyer who had input on scenarios that would need this as part of https://github.com/pulumi/pulumi/issues/2966.

File: pkg/workspace/paths.go (hunk 1 above)
Comment (mikhailshilkov) [reply pkg/workspace/paths.go]: Yes, I copied it from an internal var, but I do realize it's ugly.
`PULUMI_HOME` would sound like `~/.pulumi` to me, so including `.pulumi`. Is there a name to indicate that it's one level above?

**Comment by mikhailshilkov** [comment]
> I do think we should do this - but I believe this is technically orthogonal (the PR as is will work without this, and there is no reason the binaries need to be in the same .pulumi folder as the rest of these artifacts).

There is just one spot - `getUpgradeCommand` - where this change affects the `bin` folder. Maybe I can adjust it to check both locations.

File: pkg/workspace/paths.go (hunk 1 above)
Comment (nesl247) [reply pkg/workspace/paths.go]: I feel like it shouldn't append `.pulumi`. If you set `PULUMI_HOME_DIR`, it would be the full path (e.g. `PULUMI_HOME=/workspace/pulumi pulumi up`).

See https://getcomposer.org/doc/03-cli.md#composer-home for an example.

Comment (olfway) [reply pkg/workspace/paths.go]: I also think it shouldn't add .plumi, just use PULUMI_HOME value as is

**Comment by mikhailshilkov** [comment]
> There is just one spot - getUpgradeCommand - where this change affects the bin folder. Maybe I can adjust it to check both locations.

I reverted this check until we change the installation scripts (if we want to).

Another point to discuss:

Local login files still default to `~/.pulumi`; this location is configurable via `pulumi login` itself. We could respect `PULUMI_HOME` as the default for the `--local` option. This might become a breaking change if we do it later, then folks introduce `PULUMI_HOME` while we still use `~/.pulumi` for local logins, and then we change the default.

File: pkg/workspace/paths.go (hunk 1 above)
Comment (mikhailshilkov) [reply pkg/workspace/paths.go]: I think this makes sense. I renamed to `PULUMI_HOME` and now it's assumed to be the full path, so no `.pulumi` is appended. The default is still `~/.pulumi`.

File: cmd/pulumi.go [hunk 2]
```diff
@@ -353,7 +353,7 @@ func getUpgradeCommand() string {
 		return "$ brew upgrade pulumi"
 	}
 
-	if filepath.Dir(exe) != filepath.Join(curUser.HomeDir, ".pulumi", "bin") {
+	if filepath.Dir(exe) != filepath.Join(curUser.HomeDir, workspace.BookkeepingDir, "bin") {
 		return ""
```
Comment (nesl247) [inline cmd/pulumi.go]: Why bookkeepingdir here but homedir elsewhere?

File: pkg/workspace/paths.go [hunk 3]
```diff
@@ -180,10 +185,33 @@ func isMarkupFile(path string, expect string) bool {
...
+		return "", errors.Wrapf(err, "getting current user")
+	}
+
+	return filepath.Join(user.HomeDir, BookkeepingDir), nil
+}
+
+// GetPulumiPath returns the path to a file or directory under the '.pulumi' folder. It joins the path of
+// the '.pulumi' folder with elements passed as arguments.
+func GetPulumiPath(elem ...string) (string, error) {
+	bookkeepingPath, err := GetPulumiHomeDir()
```
Comment (nesl247) [inline pkg/workspace/paths.go]: Again, why bookkeepingPath instead of homeDir?

Comment (mikhailshilkov) [reply pkg/workspace/paths.go]: Great catch!

File: cmd/pulumi.go (hunk 2 above)
Comment (mikhailshilkov) [reply cmd/pulumi.go]: We would need to adjust the installation scripts first. This PR assumes the `bin` is still in its old place.

**Comment by nesl247** [comment]
What's left to get this merged?
