### PR TITLE
Lock access when writing event timings in display

### LINKED ISSUE #16085: CLI concurrent map read and map write panic
### What happened?

I was just running a `pulumi up` when I hit a concurrent map read and map write panic. I believe that this could be related to https://github.com/pulumi/pulumi/pull/15112, but the issue is still occurring in v3.113.3.

### Example

I was just running a `pulumi up` command. Not sure how to reproduce this.

### Output of `pulumi about`

```
❯❯ pulumi about
CLI          
Version      3.113.3
Go Version   go1.22.2
Go Compiler  gc

Host     
OS       ubuntu
Version  23.10
Arch     x86_64

Backend        
Name           [redacted]
URL            file://~
User           [redacted]
Organizations  
Token type     personal

```

### Additional context

```
fatal error: concurrent map read and map write

goroutine 273 [running]:
github.com/pulumi/pulumi/pkg/v3/backend/display.(*ProgressDisplay).getStepDoneDescription.func2()
      /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/display/progress.go:1183 +0x665
                  github.com/pulumi/pulumi/pkg/v3/backend/display.(*ProgressDisplay).getStepDoneDescription(0xc0021168c0, {{0x2b25e80, 0x6}, {0xc00167cf80, 0x7d}, {0xc0023208a0, 0x1b}, 0x0, 0xc002de0900, 0xc002de0990, ...}, ...)
          /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/display/progress.go:1206 +0x25b
                github.com/pulumi/pulumi/pkg/v3/backend/display.(*ProgressDisplay).getStepStatus(0xb?, {{0x2b25e80, 0x6}, {0xc00167cf80, 0x7d}, {0xc0023208a0, 0x1b}, 0x0, 0xc002de0900, 0xc002de0990, ...}, ...)
            /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/display/progress.go:1097 +0x5a
 github.com/pulumi/pulumi/pkg/v3/backend/display.(*resourceRowData).ColorizedColumns(0xc002d118c0)
            /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/display/rows.go:325 +0x3c5
             github.com/pulumi/pulumi/pkg/v3/backend/display.(*ProgressDisplay).getOrCreateTreeNode(0xc0021168c0, 0xc002d1fb40, {0xc00167cf80, 0x7d}, {0x34ebed8, 0xc002d118c0}, 0xc002d1fc38)
              /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/display/progress.go:280 +0x83
github.com/pulumi/pulumi/pkg/v3/backend/display.(*ProgressDisplay).generateTreeNodes(0xc0021168c0)
            /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/display/progress.go:329 +0x299
 github.com/pulumi/pulumi/pkg/v3/backend/display.(*treeRenderer).render(0xc00258d1e)
                  /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/display/tree.go:149 +0x8f
                    github.com/pulumi/pulumi/pkg/v3/backend/display.(*treeRenderer).frame(0xc00258d1e0, 0x6c?, 0x0)
          /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/display/tree.go:217 +0xfd
          github.com/pulumi/pulumi/pkg/v3/backend/display.(*treeRenderer).handleEvents(0xc00258d1e0)
                /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/display/tree.go:399 +0xc9
                created by github.com/pulumi/pulumi/pkg/v3/backend/display.newInteractiveRenderer in goroutine 170
        /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/display/tree.go:78 +0x259

              goroutine 1 [select]:
           github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run(0xc001fb4680, 0xc001fdfb00, {0x34dbd20, 0xc001c3cbe0}, 0x0)
              /tmp/pulumi-20240419-3329-9yqnoy/pkg/engine/deployment.go:334 +0x352
                  github.com/pulumi/pulumi/pkg/v3/engine.update(0xc001fdfb00, 0xc002cdc6a0, 0xc0021fc7e0, 0x0)
                /tmp/pulumi-20240419-3329-9yqnoy/pkg/engine/update.go:506 +0x27d
                      github.com/pulumi/pulumi/pkg/v3/engine.Update({0x34cc2f0, 0xc002a41d10}, 0xc001fdfb00, {{0x4bd09c0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x20, ...}, ...)
/tmp/pulumi-20240419-3329-9yqnoy/pkg/engine/update.go:211 +0x4e9
      github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc001fe0160, {0xc001fe8410, 0x40}, ...}, ...)
        /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/diy/backend.go:1109 +0x99f
                     github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc001fe0160, {0xc001fe8410, 0x40}, {0x0, ...}, ...}, ...)
        /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/apply.go:272 +0x22d
              github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).Update(_, {_, _}, {_, _}, {0xc001fe0160, {0xc001fe8410, 0x40}, {0x0, 0x0, ...}, ...})
        /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/diy/backend.go:940 +0x205
      github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc001fe0160, {0xc001fe8410, 0x40}, {0x0, 0x0, 0x0}, ...})
        /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/stack.go:97 +0x9e
                      github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Update(_, {_, _}, {0xc001fe0160, {0xc001fe8410, 0x40}, {0x0, 0x0, 0x0}, 0xc001fe23d8, ...})
                /tmp/pulumi-20240419-3329-9yqnoy/pkg/backend/diy/stack.go:90 +0x6a
          main.newUpCmd.func1({_, _}, {{{0x4bd09c0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x20, 0x0, ...}, ...}, ...)
                /tmp/pulumi-20240419-3329-9yqnoy/pkg/cmd/pulumi/up.go:183 +0xe6d
                      main.newUpCmd.func3(0xc001f87208, {0x4bd09c0, 0x0, 0x0?})
        /tmp/pulumi-20240419-3329-9yqnoy/pkg/cmd/pulumi/up.go:515 +0xbce
main.newUpCmd.RunResultFunc.func4(0xc001f87208, {0x4bd09c0, 0x0, 0x0})
                /tmp/pulumi-20240419-3329-9yqnoy/sdk/go/common/util/cmdutil/exit.go:115 +0x38
                     github.com/spf13/cobra.(*Command).execute(0xc001f87208, {0x4bd09c0, 0x0, 0x0})
        /home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
      github.com/spf13/cobra.(*Command).ExecuteC(0xc00059c908)
                /home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
               github.com/spf13/cobra.(*Command).Execute(...)
                /home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
        main.main()
/tmp/pulumi-20240419-3329-9yqnoy/pkg/cmd/pulumi/main.go:56 +0x58

                goroutine 5 [select]:
             github.com/golang/glog.(*fileSink).flushDaemon(0x4b6a4f8)
/home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/golang/glog@v1.2.0/glog_file.go:351 +0xb9
                       created by github.com/golang/glog.init.1 in goroutine 1
        /home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/golang/glog@v1.2.0/glog_file.go:166 +0x126

        goroutine 6 [select]:
     go.opencensus.io/stats/view.(*worker).start(0xc00067bd80)
                /home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x9f
                  created by go.opencensus.io/stats/view.init.0 in goroutine 1
        /home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x8d

                   goroutine 7 [chan send]:
         main.NewPulumiCmd.func1.2()
                /tmp/pulumi-20240419-3329-9yqnoy/pkg/cmd/pulumi/pulumi.go:257 +0x39
           created by main.NewPulumiCmd.func1 in goroutine 1
                /tmp/pulumi-20240419-3329-9yqnoy/pkg/cmd/pulumi/pulumi.go:256 +0x3bb

  goroutine 283 [IO wait]:
  internal/poll.runtime_pollWait(0x791ffc6447a8, 0x72)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.22.2/libexec/src/runtime/netpoll.go:345 +0x85
                    internal/poll.(*pollDesc).wait(0x13?, 0x1?, 0x0)
                /home/linuxbrew/.linuxbrew/Cellar/go/1.22.2/libexec/src/internal/poll/fd_poll_ru:84 +0x27
         internal/poll.(*pollDesc).waitRead(...)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.22.2/libexec/src/internal/poll/fd_poll_runtime.go:89
                 internal/poll.(*FD).Accept(0xc002cde480)
                /home/linuxbrew/.linuxbrew/Cellar/go/1.22.2/libexec/src/internal/poll/fd_unix.go:611 +0x2ac
 net.(*netFD).accept(0xc002cde480)
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by lunaris**
This should fix #16085, in which we are getting concurrent reads and writes to the `opStopwatch` maps.

### CODE REVIEW

File: pkg/backend/display/progress.go [hunk 1]
```diff
@@ -964,10 +964,12 @@ func (display *ProgressDisplay) processNormalEvent(event engine.Event) {
 
 		// Register the resource update start time to calculate duration
 		// and time elapsed.
+		display.m.Lock()
```
Comment (tgummerer) [inline pkg/backend/display/progress.go:967]: Should we use a separate lock for this?  This lock seems to be used only for `eventUrnToResourceRow` according to the docs. I'm guessing this is convenient because it already does the read locking for `opStopwatch`, and that's why we don't need to add it in this PR?

It's probably okay to reuse the lock in that case, but we should update the comment.

Comment (lunaris) [reply pkg/backend/display/progress.go:967]: @PollRobots I _believe_ you have been working with display code recently and have a lot more experience than I do here -- any thoughts?

Comment (Frassle) [reply pkg/backend/display/progress.go:967]: I think just update the comment and it'll be fine.

**Review by tgummerer — APPROVED** [review]

**Review by Frassle — APPROVED** [review]
