### PR TITLE
[cli] make `pulumi new` properly check for project name existence at org level.

### LINKED ISSUE #7423: Can't create a project with a name that exists in a personal org
It doesn't appear to be possible to create a project in a particular organization using the name of a project that exists in one's personal org:

```
➜ pulumi whoami -v
User: cnunciato
Backend URL: https://app.pulumi.com/cnunciato

➜ mkdir someproj && cd someproj
➜ pulumi new typescript
...
Created project 'someproj'
...
Your new project is ready to go! ✨

➜ cd ..
➜ mkdir -p pulumibook/someproj && cd pulumibook/someproj
➜ pulumi new typescript -s pulumibook/someproj/dev
...
project name: someproj
Sorry, 'someproj' is not a valid project name. A project with this name already exists.
``` 

It _is_ possible, however, to create a same-named project in a non-personal org:

```
➜ mkdir -p pulumi/someproj && cd pulumi/someproj
➜ pulumi new typescript -s pulumi/someproj/dev
...
project name: (someproj)
...
Created project 'someproj'
Created stack 'pulumi/dev'
...
Your new project is ready to go! ✨

➜ cd ..
➜ mkdir -p pulumibook/someproj && cd pulumibook/someproj
➜ pulumi new typescript -s pulumibook/someproj/dev
...
project name: (someproj)
...
Created project 'someproj'
Created stack 'pulumibook/dev'
...
Your new project is ready to go! ✨
```

This seem to be happening because `DoesProjectExist` is always called with `currentUser` rather than respecting the org name passed in with `--stack`.

Expected:

I can create `pulumibook/someproj/dev` even when `cnunciato/someproj/dev` exists.

Actual:

I'm unable to create `pulumibook/someproj/dev` because the `HEAD` request that checks for the existence of `someproj` passes `cnunciato` where it should be passing `pulumibook`.

### LINKED ISSUE #10748: pulumi new project already exists error does not respect the default org
[internal slack convo](https://pulumi.slack.com/archives/C9SGX9QA1/p1663254061919969)

repro steps
- create a project in your individual account with name X
- set your default org to an org that does not have a project with the name X
- use pulumi new
- when it asks for a project name, set it to X
- receive an error saying that project already exists

### PR DESCRIPTION
**Pull request by dixler**
# Description

`pulumi new -s 'org/project/stack'` checks the proper organization for project existence rather than `backend.currentUser()`'s org.

Fixes #7423
Fixes #10748 

TODO
- [x] Integration Test with multiple orgs with 2 projects of the same name.

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/backend/httpstate/backend.go [hunk 1]
```diff
@@ -760,13 +760,16 @@ func (b *cloudBackend) LogoutAll() error {
...
+	if orgName == "" {
+		var err error
+		orgName, _, err = b.currentUser(ctx)
+		if err != nil {
+			return false, err
+		}
 	}
 
-	return b.client.DoesProjectExist(ctx, owner, projectName)
+	return b.client.DoesProjectExist(ctx, orgName, projectName)
```
Comment (dixler) [inline pkg/backend/httpstate/backend.go:772]: This is the meat of the change.

File: pkg/backend/backend.go [hunk 2]
```diff
@@ -155,7 +155,7 @@ type Backend interface {
 	ValidateStackName(s string) error
 
 	// DoesProjectExist returns true if a project with the given name exists in this backend, or false otherwise.
-	DoesProjectExist(ctx context.Context, projectName string) (bool, error)
+	DoesProjectExist(ctx context.Context, projectName string, orgName string) (bool, error)
```
Comment (abhinav) [inline pkg/backend/backend.go:158]: I would flip the argument order here. Other APIs do org, project, stack (decreasing order of scope). It'll be easy to make a mistake here and flip the order.

Also, perhaps add a comment on whether orgName is required or optional.

File: pkg/cmd/pulumi/new.go [hunk 3]
```diff
@@ -128,7 +128,9 @@ func runNew(ctx context.Context, args newArgs) error {
 
 	// Ensure the project doesn't already exist.
 	if args.name != "" {
-		if err := validateProjectName(ctx, b, args.name, args.generateOnly, opts); err != nil {
+		// No org name since
```
Comment (abhinav) [inline pkg/cmd/pulumi/new.go:131]: since what

File: pkg/cmd/pulumi/new.go [hunk 4]
```diff
@@ -128,7 +128,9 @@ func runNew(ctx context.Context, args newArgs) error {
...
+		noOrgName := ""
+		if err := validateProjectName(ctx, b, args.name, noOrgName, args.generateOnly, opts); err != nil {
```
Comment (abhinav) [inline pkg/cmd/pulumi/new.go:133]: optionally, you can use the pattern of inline `/* .. */` comments for documenting parameters here.

```suggestion
		noOrgName := ""
		if err := validateProjectName(ctx, b, args.name, "" /* org name */, args.generateOnly, opts); err != nil {
```

(e.g. https://github.com/uber-go/guide/blob/master/style.md#avoid-naked-parameters)

File: pkg/cmd/pulumi/new_test.go [hunk 5]
```diff
@@ -818,3 +818,68 @@ func TestErrorIfNotEmptyDirectory(t *testing.T) {
...
+			type Org string
+			type ProjectName string
+			projects := map[Org]map[ProjectName]struct{}{
+				"moolumi": {
+					"my-moolumi-project": {},
+				},
+				"pulumi": {
+					"my-pulumi-project": {},
+				},
+			}
```
Comment (abhinav) [inline pkg/cmd/pulumi/new_test.go:836]: Seeing that all this is constant, I would declare it above the MockBackend.

```
orgsAndProjects := map[Org]map[ProjectName]struct{}{
	"moolumi": {
		"my-moolumi-project": {},
	},
	"pulumi": {
		"my-pulumi-project": {},
	},
}
b := &backend.MockBackend{
	DoesProjectExistF: func(...) (bool, error) {
		projects, ok := orgsAndProjects[..]
		// ...
	},
}
```

File: pkg/cmd/pulumi/new_test.go [hunk 6]
```diff
@@ -818,3 +818,68 @@ func TestErrorIfNotEmptyDirectory(t *testing.T) {
...
+	}
+
+	// Table Test
+	type Project struct {
+		orgName     string
+		projectName string
+	}
+	tests := []struct {
+		name   string
+		give   Project
```
Comment (abhinav) [inline pkg/cmd/pulumi/new_test.go:853]: Any reason to declare the separate struct instead of:

```suggestion
	tests := []struct {
		desc   string
		orgName     string
		projectName string
```

File: pkg/cmd/pulumi/new.go (hunk 4 above)
Comment (dixler) [reply pkg/cmd/pulumi/new.go:133]: Yeah. that's technically better because it decreases the number of identifiers added in the scope.

File: changelog/pending/20230622--cli-new--pulumi-new-s-org-project-stack-checks-the-specified-organization-for-project-existence-rather-than-the-currentuser.yaml [hunk 7]
```diff
@@ -0,0 +1,4 @@
+changes:
+- type: fix
+  scope: cli/new
+  description: `pulumi new -s 'org/project/stack'` checks the specified organization for project existence rather than the currentUser.
```
Comment (justinvp) [inline changelog/pending/20230622--cli-new--pulumi-new-s-org-project-stack-checks-the-specified-organization-for-project-existence-rather-than-the-currentuser.yaml:4]: What about the default org? Will it use the default org, rather than the current user, if one is set?

https://www.pulumi.com/docs/cli/commands/pulumi_org_set-default/

Comment (Frassle) [reply changelog/pending/20230622--cli-new--pulumi-new-s-org-project-stack-checks-the-specified-organization-for-project-existence-rather-than-the-currentuser.yaml:4]: It won't we'd need a call to `workspace.GetBackendConfigDefaultOrg` to work out the default org.

Comment (dixler) [reply changelog/pending/20230622--cli-new--pulumi-new-s-org-project-stack-checks-the-specified-organization-for-project-existence-rather-than-the-currentuser.yaml:4]: To be clear, it should be to the effect:
```typescript
const org = explicitOrg || defaultOrg || currentUser;
```

Correct?

File: tests/stack_test.go [hunk 8]
```diff
@@ -811,3 +811,51 @@ func TestStackTags(t *testing.T) {
...
+
+	// This test requires the service, as only the service supports orgs.
+	if os.Getenv("PULUMI_ACCESS_TOKEN") == "" {
+		t.Skipf("Skipping: PULUMI_ACCESS_TOKEN is not set")
+	}
+
+	e := ptesting.NewEnvironment(t)
+	defer deleteIfNotFailed(e)
+
+	project := newUnixTimestampString("project")
```
Comment (Frassle) [inline tests/stack_test.go:838]: We use `resource.NewUniqueHex("test-name-", 8, -1)` in a few other places. We should probably just add a method to the environment object to do this and use that consistently everywhere.

File: tests/stack_test.go [hunk 9]
```diff
@@ -811,3 +811,41 @@ func TestStackTags(t *testing.T) {
 	tags = lsTags()
 	assert.Equal(t, "projectValue", tags["projectTag"], "projectTag should be set to projectValue")
 }
+
+//nolint:paralleltest // pulumi new is not parallel safe
+func TestNewStackConflictingOrg(t *testing.T) {
+	t.Parallel()
```
Comment (justinvp) [inline tests/stack_test.go:817]: Should it be parallel or not? Hard to tell with the nolint and t.Parallel() call

**Review by justinvp — APPROVED** [review]

**Comment by justinvp** [comment]
Please squash commits before merging.

**Comment by dixler** [comment]
bors merge

**Comment by dixler** [comment]
bors merge
