### PR TITLE
dotnet program-gen now targets .NET 6

### LINKED ISSUE #8069: Dotnet program codegen: We use the `?[]` on `ImmutableArray<T>`.
This was found compiling the our program codegen tests. It looks like `ImmutableArray<T>` is not nullable, so we can't apply the `?[]` operator to it. 
## Steps to reproduce

1. `cd pkg/codegen/internal/test/testdata/aws-s3-logging-pp`
2. `dotnet build`

Expected: A clean compile
Actual: 
```
  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/aws-s3-logging-pp/aws-s3-logging.cs(21,71): error CS0023: Operator '?' cannot be applied to operand of type 'ImmutableArray<BucketLogging>' [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/aws-s3-logging-pp/aws-s3-logging-pp.csproj]

Build FAILED.

/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/aws-s3-logging-pp/aws-s3-logging.cs(21,71): error CS0023: Operator '?' cannot be applied to operand of type 'ImmutableArray<BucketLogging>' [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/aws-s3-logging-pp/aws-s3-logging-pp.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.21
```

### LINKED ISSUE #8078: C# program codegen: invalid array literal
This was found compiling our program codegen tests. We generate invalid `dotnet` array literals. This is a syntax error. This is the example:
```c#
var joined = string.Join("-", 
        {
            "haha",
            "business",
        });
```
## Steps to reproduce

1. `cd pkg/codegen/internal/test/testdata/functions-pp`
2. `dotnet build --nologo`

Expected: A clean compile
Actual:
```
  Determining projects to restore...
  Restored /Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj (in 327 ms).
  1 of 2 projects are up-to-date for restore.
  Pulumi -> /Users/ianwahbe/Projects/pulumi/pulumi/sdk/dotnet/Pulumi/bin/Debug/netcoreapp3.1/Pulumi.dll
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(9,38): error CS1525: Invalid expression term '{' [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(9,38): error CS1026: ) expected [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(9,38): error CS1002: ; expected [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(11,19): error CS1002: ; expected [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(11,19): error CS1513: } expected [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(12,23): error CS1002: ; expected [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(12,23): error CS1513: } expected [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(13,10): error CS1513: } expected [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]

Build FAILED.

/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(9,38): error CS1525: Invalid expression term '{' [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(9,38): error CS1026: ) expected [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(9,38): error CS1002: ; expected [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(11,19): error CS1002: ; expected [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(11,19): error CS1513: } expected [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(12,23): error CS1002: ; expected [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(12,23): error CS1513: } expected [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions.cs(13,10): error CS1513: } expected [/Users/ianwahbe/Projects/pulumi/pulumi/pkg/codegen/internal/test/testdata/functions-pp/functions-pp.csproj]
    0 Warning(s)
    8 Error(s)

Time Elapsed 00:00:02.92
```

### LINKED ISSUE #9642: `pulumi convert` support for arbitrary output types in C#/dotnet
Converting a simple YAML program such as this produces invalid code in C#:

```yaml
name: random
runtime: yaml
outputs:
  arrVar:
  - fizz
  - buzz
```

The generated code incorrectly types `arrVar` as an `Output<string>`.

### LINKED ISSUE #10104: Dotnet program-gen should emit output-versioned function invokes
### What happened?

The current way dotnet programgen handles function invokes is faulty and can easily result in programs that don't compile. This is because we use the plain version of function invokes (i.e `InvokeAsync`) and then we wrap that inside `Output.Create`.

This easily breaks when you want to use a property  output of function invoke A as input for function invoke B

### Steps to reproduce

Run `pulumi convert` against the following YAML program:
```yaml
name: YamlTest
runtime: yaml
description: A static website hosted on AWS S3
variables:
  vpcId:
    Fn::Invoke:
      Function: aws:ec2:getVpc
      Arguments:
        default: true
      Return: id
  subnetIds:
    Fn::Invoke:
      Function: aws:ec2:getSubnetIds
      Arguments:
        vpcId: ${vpcId}
      Return: ids
outputs:
  subnets: ${subnetIds}
```

### Expected Behavior

It should generate
```cs
using System.Collections.Immutable;
using Pulumi;
using Aws = Pulumi.Aws;

class MyStack : Stack
{
    public MyStack()
    {
        var vpcId = Aws.Ec2.GetVpc.Invoke(new Aws.Ec2.GetVpcInvokeArgs
        {
            Default = true,
        }).Apply(invoke => invoke.Id);

        var subnetIds = Aws.Ec2.GetSubnetIds.Invoke(new Aws.Ec2.GetSubnetIdsInvokeArgs
        {
            VpcId = vpcId,
        }).Apply(invoke => invoke.Ids);

        this.Subnets = subnetIds;
    }

    [Output("subnets")]
    public Output<ImmutableArray<string>> Subnets { get; set; }
}
```

### Actual Behavior

It generates
```cs
using Pulumi;
using Aws = Pulumi.Aws;

class MyStack : Stack
{
    public MyStack()
    {
        var vpcId = Output.Create(Aws.Ec2.GetVpc.InvokeAsync(new Aws.Ec2.GetVpcArgs
        {
            Default = true,
        })).Apply(invoke => invoke.Id);
        var subnetIds = Output.Create(Aws.Ec2.GetSubnetIds.InvokeAsync(new Aws.Ec2.GetSubnetIdsArgs
        {
            VpcId = vpcId,
        })).Apply(invoke => invoke.Ids);
        this.Subnets = subnetIds;
    }

    [Output("subnets")]
    public Output<string> Subnets { get; set; }
}
```

### Versions used

Pulumi v3.53.3

### Additional context

The generated intermediate PCL 
```
vpcId = invoke("aws:ec2/getVpc:getVpc", {
        default = true
}).id

subnetIds = invoke("aws:ec2/getSubnetIds:getSubnetIds", {
        vpcId = vpcId
}).ids

output subnets {
        __logicalName = "subnets"
        value = subnetIds
}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #10113: Dotnet program-gen should output less noisy dictionaries using property initializers
### What happened?

The generated dictionaries by dotnet program-gen today are noisy: too many curly brackets and too much indentation

### Steps to reproduce

Run `pulumi convert --language csharp --out dist` against the following YAML program
```yaml
name: YamlTest
runtime: yaml
description: Dictionaries
resources:
  policyJson:
    type: aws:iam:Policy
    properties:
      policy:
        Fn::ToJSON:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 'lambda:*'
              Resource: 'arn:aws:lambda:*:*:function:*'

outputs:
  policy: ${policyJson.name}
```

### Expected Behavior

Should generate:
```csharp
using System.Collections.Generic;
using System.Text.Json;
using Pulumi;
using Aws = Pulumi.Aws;

class MyStack : Stack
{
    public MyStack()
    {
        var policyJson = new Aws.Iam.Policy("policyJson", new Aws.Iam.PolicyArgs
        {
            PolicyDocument = JsonSerializer.Serialize(new Dictionary<string, object?>
            {
                ["Version"] = "2012-10-17",
                ["Statement"] = new[]
                {
                    new Dictionary<string, object?>
                    {
                        ["Effect"] = "Allow",
                        ["Action"] = "lambda:*",
                        ["Resource"] = "arn:aws:lambda:*:*:function:*",
                    },
                },
            }),
        });
        this.Policy = policyJson.Name;
    }

    [Output("policy")]
    public Output<string> Policy { get; set; }
}

```

### Actual Behavior

It generates
```csharp
using System.Collections.Generic;
using System.Text.Json;
using Pulumi;
using Aws = Pulumi.Aws;

class MyStack : Stack
{
    public MyStack()
    {
        var policyJson = new Aws.Iam.Policy("policyJson", new Aws.Iam.PolicyArgs
        {
            PolicyDocument = JsonSerializer.Serialize(new Dictionary<string, object?>
            {
                { "Version", "2012-10-17" },
                { "Statement", new[]
                    {
                        new Dictionary<string, object?>
                        {
                            { "Effect", "Allow" },
                            { "Action", "lambda:*" },
                            { "Resource", "arn:aws:lambda:*:*:function:*" },
                        },
                    }
                 },
            }),
        });
        this.Policy = policyJson.Name;
    }

    [Output("policy")]
    public Output<string> Policy { get; set; }
}
```

### Versions used

_No response_

### Additional context

Intermediate PCL
```
resource policyJson "aws:iam/policy:Policy" {
        __logicalName = "policyJson"
        policy = toJSON({
                "Version" = "2012-10-17",
                "Statement" = [{
                        "Effect" = "Allow",
                        "Action" = "lambda:*",
                        "Resource" = "arn:aws:lambda:*:*:function:*"
                }]
        })
}

output policy {
        __logicalName = "policy"
        value = policyJson.name
}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #10114: Dotnet program-gen should simplify MyStack.cs into just Program.cs using .NET 6 top-level statements
### What happened?

Today, dotnet program-gen outputs a file called `MyStack.cs` which contains a class called `MyStack` that constructs resources and assigns outputs to properties of the class marked with `[Output]`

In .NET 6, we can greatly simplify this setup and get rid of `MyStack.cs` entirely where we instead generate a single entry point file `Program.cs` that defines stack resources and returns outputs from them. 

This results in
 - Simplified project structure that looks similar to all other languages
 - No longer we need to compute the types of the outputs up front, which today defaults to `Output<string>` for almost everything. 

This issue is also related to `GenerateProject` where the generated project should be targeting `net6.0` and only have `Program.cs` in the project

### Steps to reproduce

Run `pulumi convert --language csharp --out dist` against this YAML program
```yaml
name: YamlTest
runtime: yaml
resources:
  bucket:
    type: aws:s3:Bucket

outputs:
  bucketName: ${bucket.id}
```

### Expected Behavior

Should generate:
```cs
// Program.cs
using System.Collections.Generic;
using Pulumi;
using Aws = Pulumi.Aws;
using Deployment = Pulumi.Deployment;

await Deployment.RunAsync(() => 
{
  var bucket = new Aws.S3.Bucket("bucket")

  return new Dictionary<string, object?>
  {
      ["bucketName"] = bucket.Id
  };
});
```

### Actual Behavior

Generates:
```csharp
// MyStack.cs
using Pulumi;
using Aws = Pulumi.Aws;

class MyStack : Stack
{
    public MyStack()
    {
        var bucket = new Aws.S3.Bucket("bucket", new Aws.S3.BucketArgs
        {
        });
        this.BucketName = bucket.Id;
    }

    [Output("bucketName")]
    public Output<string> BucketName { get; set; }
}
```

### Versions used

Pulumi v3.53.3

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

Fixes #10114 
Fixes #10113
Fixes #10104
Fixes #8069
Fixes #8078
Fixes #9642

Summary:
 - No more `MyStack.cs`, only `Program.cs` with an entry point that defines resources and outputs
 - When async initialization is required, no longer the `Initialize()` function is created. Instead, we simply mark the deployment lambda as `async` and proceed to `await` any awaitable function invoke in the program
 - Using output-versioned function invokes now*
 - Simplifies dictionaries and makes them less noisy
 - Fixes array initializers (when to or not to use `new []`)
 - Fixes arbitrary outputs
 - Use implictly typed args type when defining resources: `new Bucket("name", new() {  ... })` instead of `new Bucket("name", new BucketArgs { ... })`. This is possible when targeting .NET 6 and only applies to top-level resource args.

> Using output-versioned function invokes now*

Works 99% of the time, will file more issues about this later

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/backend/watch_darwin_arm64.go [hunk 1]
```diff
@@ -21,6 +21,6 @@ import (
 	"github.com/pulumi/pulumi/sdk/v3/go/common/util/result"
 )
 
-func Watch(ctx context.Context, b Backend, stack Stack, op UpdateOperation, apply Applier, paths []string) result.Result {
+func Watch(ctx context.Context, b Backend, s Stack, op UpdateOperation, apply Applier, paths []string) result.Result {
```
Comment (Zaid-Ajaj) [inline pkg/backend/watch_darwin_arm64.go:24]: This change is to make my local linter happy because the line was 122 characters

**Comment by iwahbe** [comment]
Does this mean we are bumping the minimum version of `dotnet` that you can deploy with?

**Comment by Zaid-Ajaj** [comment]
> Does this mean we are bumping the minimum version of dotnet that you can deploy with?

@iwahbe For deploying .NET SDK, we could still use 3.1 but generated programs now require .NET 6

**Comment by iwahbe** [comment]
> > Does this mean we are bumping the minimum version of dotnet that you can deploy with?
> 
> @iwahbe For deploying .NET SDK, we could still use 3.1 but generated programs now require .NET 6

I think generated code should work for all supported versions of C#. If a user has a C# program, we shouldn't break `pulumi import` for them (which I think this does).

I would be ok with saying that running `pulumi convert` requires .NET 6, but we use program-gen for imports as well.

**Comment by AaronFriel** [comment]
> I would be ok with saying that running pulumi convert requires .NET 6, but we use program-gen for imports as well.

For `import` we only generate a single resource constructor and not a whole program, right? Does this break the syntax for that? Could we stick the old syntax generation behind a flag?

**Comment by Zaid-Ajaj** [comment]
> Could we stick the old syntax generation behind a flag?

@iwahbe @AaronFriel I've updated the PR and now we are able to provide different options to `GenerateProgram` with the default targeting .NET 6 but for `pulumi import`, we fallback to generating old, more verbose syntax. 

```go
// used now in pulumi import
func GenerateProgramForImport(program *pcl.Program) (map[string][]byte, hcl.Diagnostics, error) {
	importOptions := GenerateProgramOptions{
		// for import, we want to generate C# code that
		// is compatible with old versions of .NET
		implicitResourceArgsTypeName: false,
	}

	return GenerateProgramWithOptions(program, importOptions)
}

func GenerateProgram(program *pcl.Program) (map[string][]byte, hcl.Diagnostics, error) {
	defaultOptions := GenerateProgramOptions{
		// by default, we generate C# code that targets .NET 6
		implicitResourceArgsTypeName: true,
	}

	return GenerateProgramWithOptions(program, defaultOptions)
}
```
I can imagine these options being exposed to the CLI but that is not needed today

**Comment by mikhailshilkov** [comment]
It's impressive to fix six issues with one PR! My slight preference would be having many small PRs though, at least that would be much easier for me to review. Ignore me if the current format works for others.

**Comment by Zaid-Ajaj** [comment]
@mikhailshilkov It's tempting to mop up small issues I come across 😄 I will keep PRs small next time around 💯

File: pkg/codegen/dotnet/gen_program.go [hunk 2]
```diff
@@ -233,6 +258,44 @@ func (g *generator) genTrivia(w io.Writer, token syntax.Token) {
 	}
 }
 
+func (g *generator) findFunctionSchema(function string) (*schema.Function, bool) {
+	function = LowerCamelCase(function)
+	for _, pkg := range g.program.PackageReferences() {
+		for it := pkg.Functions().Range(); it.Next(); {
+			if strings.HasSuffix(it.Token(), function) {
```
Comment (iwahbe) [inline pkg/codegen/dotnet/gen_program.go:265]: Why is this checking via suffix? Can we not use `pkg.Functions().Get(function)`? I'm not a fan of swallowing all errors here. Can we return `(*schema.Function, boo, error)`.

File: pkg/codegen/dotnet/gen_program.go [hunk 3]
```diff
@@ -233,6 +258,44 @@ func (g *generator) genTrivia(w io.Writer, token syntax.Token) {
...
+	switch value.(type) {
+	case *model.FunctionCallExpression:
+		call := value.(*model.FunctionCallExpression)
+		switch call.Name {
+		case pcl.Invoke:
+			args := call.Args[0]
+			_, fullFunctionName := g.functionName(args)
+			functionNameParts := strings.Split(fullFunctionName, ".")
+			functionName := functionNameParts[len(functionNameParts)-1]
+			functionSchema, foundFunction := g.findFunctionSchema(functionName)
```
Comment (iwahbe) [inline pkg/codegen/dotnet/gen_program.go:289]: It looks like if this check fails, we will always return `nil, false`. We can just return here. 
```suggestion
			return g.findFunctionSchema(functionName)
```

File: pkg/codegen/dotnet/gen_program_expressions.go [hunk 4]
```diff
@@ -350,6 +344,12 @@ func (g *generator) genIntrensic(w io.Writer, from model.Expression, to model.Ty
 	}
 }
 
+func (g *generator) withinAwaitBlock(run func()) {
+	g.insideAwait = true
```
Comment (iwahbe) [inline pkg/codegen/dotnet/gen_program_expressions.go:348]: I would probably cache the old value, instead of assuming that it is `false`. See
```go
g.withAwaitBlock(func() {
  g.withAwaitBlock(func() {
    contract.Assert(g.insideAwait)
  }
  contract.Assert(g.insideAwait) // panics
}

File: pkg/codegen/dotnet/gen_program_expressions.go [hunk 5]
```diff
@@ -400,24 +447,45 @@ func (g *generator) GenFunctionCallExpression(w io.Writer, expr *model.FunctionC
...
-			if len(expr.Args) >= 2 {
-				g.Fgenf(w, "%.v", expr.Args[1])
-			}
+			g.Fprintf(w, "%s.Invoke(", fullFunctionName)
 		}
 
-		if len(expr.Args) == 3 {
-			g.Fgenf(w, ", %.v", expr.Args[2])
+		innerFunc, isFunc := expr.Args[1].(*model.FunctionCallExpression)
+		if isFunc && innerFunc.Name == pcl.IntrinsicConvert {
```
Comment (iwahbe) [inline pkg/codegen/dotnet/gen_program_expressions.go:460]: Is this the correct behavior for `isFunc && innerFunc.Name != pcl.IntrensicConcert`?

File: pkg/codegen/dotnet/gen_program_expressions.go [hunk 6]
```diff
@@ -650,6 +719,18 @@ func (g *generator) GenRelativeTraversalExpression(w io.Writer, expr *model.Rela
...
+func (g *generator) schemaTypeName(schemaType *schema.ObjectType) string {
+	fullyQualifiedTypeName := schemaType.Token
+	nameParts := strings.Split(fullyQualifiedTypeName, ":")
+	return names.Title(nameParts[len(nameParts)-1])
+}
+
+func (g *generator) withinFunctionInvoke(run func()) {
+	g.insideFunctionInvoke = true
+	run()
+	g.insideFunctionInvoke = false
```
Comment (iwahbe) [inline pkg/codegen/dotnet/gen_program_expressions.go:731]: As I mentioned for the `withingAsyncBlock`, this should cache the old value, not set to false on exit.

File: pkg/codegen/dotnet/gen_program_expressions.go [hunk 7]
```diff
@@ -20,6 +20,8 @@ import (
 	"math/big"
 	"strings"
 
+	"github.com/pulumi/pulumi-java/pkg/codegen/java/names"
```
Comment (iwahbe) [inline pkg/codegen/dotnet/gen_program_expressions.go:23]: I'd really rather not take a dependency on java from the dotnet codegen. Also, `dotnet` codegen already has this function:
https://github.com/pulumi/pulumi/blob/858f8b20a83eed48649fb833d3659a6873ba508d/pkg/codegen/dotnet/gen.go#L62-L70

**Review by iwahbe — COMMENTED** [review]
Deferring to @mikhailshilkov, if we can program-gen for only .NET 6, lets keep it simple. Sorry for the extra work.

It would be much easier to review if each PR was a small and targeted fix, though I appreciate the desire to snowball the PR.

File: pkg/codegen/dotnet/gen_program.go (hunk 3 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/dotnet/gen_program.go:289]: Yeah nice catch!

File: pkg/codegen/dotnet/gen_program_expressions.go (hunk 7 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/dotnet/gen_program_expressions.go:23]: Copy-paste issue and GoLand imported it automatically. Thanks for the heads-up 🙏

File: pkg/codegen/dotnet/gen_program.go (hunk 2 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/dotnet/gen_program.go:265]: Why would it error though? if it errors, that means it couldn't find the function, right? or are there errors that should be propagated back 🤔

File: pkg/codegen/dotnet/gen_program_expressions.go (hunk 6 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/dotnet/gen_program_expressions.go:731]: Maybe I am bit tired, not sure what you mean. I just did this instead:
```go
func (g *generator) withinAwaitBlock(run func()) {
	if g.insideAwait {
		// already inside await block?
		// only run the function
		run()
	} else {
		// not inside await? flag it as true, run the function,
		// then set it back to false
		g.insideAwait = true
		run()
		g.insideAwait = false
	}
}
```
Even though this doesn't really happen, don't think we double `await`, nor we call function invokes in succession

File: pkg/codegen/dotnet/gen_program.go (hunk 2 above)
Comment (iwahbe) [reply pkg/codegen/dotnet/gen_program.go:265]: I believe it will error if it can't acquire the schema, which could happen for many reasons we would want to propagate. If it can confirm that the function isn't there (can acquire the schema, no function there) then we can clearly indicate "The function doesn't exist".

File: pkg/codegen/dotnet/gen_program_expressions.go (hunk 6 above)
Comment (iwahbe) [reply pkg/codegen/dotnet/gen_program_expressions.go]: I meant something like:

```go
func (g *generator) withinAwaitBlock(run func()) {
        defer func(v bool) { g.insideAwait = v }(g.insideAwait)
        g.insideAwait = true
        run()
}
```

I think what you put has the same effect.

File: pkg/codegen/dotnet/gen_program_expressions.go (hunk 5 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/dotnet/gen_program_expressions.go:465]: I believe so, this logic only special-cases that specific pattern and the default case is what it was before

File: pkg/cmd/pulumi/import.go [hunk 8]
```diff
@@ -457,7 +457,7 @@ func newImportCmd() *cobra.Command {
 			var programGenerator programGeneratorFunc
 			switch proj.Runtime.Name() {
 			case "dotnet":
-				programGenerator = dotnet.GenerateProgram
+				programGenerator = dotnet.GenerateProgramForImport
```
Comment (iwahbe) [inline pkg/cmd/pulumi/import.go:460]: I know that I requested this, but after [the comment from @mikhailshilkov](https://github.com/pulumi/pulumi/pull/10143#issuecomment-1185314371), I think we can drop it back to `dotnet.GenerateProgram`, removing `dotnet.GenerateProgramForImport`.

File: pkg/codegen/dotnet/gen_program_expressions.go [hunk 9]
```diff
@@ -41,64 +40,78 @@ func (g *generator) lowerExpression(expr model.Expression, typ model.Type) model
...
 	return expr
 }
 
-// outputInvokes wraps each call to `invoke` with a call to the `output` intrinsic. This rewrite should only be used if
-// resources are instantiated within a stack constructor, where `await` operator is not available. We want to avoid the
-// nastiness of working with raw `Task` and wrap it into Pulumi's Output immediately to be able to `Apply` on it.
-// Note that this depends on the fact that invokes are the only way to introduce promises
+// lowerExpressionWithoutApplies is the same as lowerExpression
+// but without rewriting applies. Make especially for function invokes that are returning outputs
+func (g *generator) lowerExpressionWithoutApplies(expr model.Expression, typ model.Type) model.Expression {
```
[the remark this answers is not in the document]
Comment (Zaid-Ajaj) [reply pkg/codegen/dotnet/gen_program_expressions.go:55]: Done ✅

File: pkg/codegen/dotnet/gen_program_expressions.go [hunk 10]
```diff
@@ -41,64 +40,78 @@ func (g *generator) lowerExpression(expr model.Expression, typ model.Type) model
...
+	expr = pcl.RewritePropertyReferences(expr)
+	expr, diags := pcl.RewriteConversions(expr, typ)
+	if g.asyncInit {
+		expr = g.awaitInvokes(expr)
+	} else {
+		expr = g.outputInvokes(expr)
+	}
+	contract.Assertf(diags.HasErrors() == false, "expected no errors in conversion, got: %v", diags.Error())
```
[the remark this answers is not in the document]
Comment (Zaid-Ajaj) [reply pkg/codegen/dotnet/gen_program_expressions.go:63]: Done ✅

File: pkg/codegen/testing/test/program_driver.go [hunk 11]
```diff
@@ -194,12 +190,13 @@ type CheckProgramOutput = func(*testing.T, string, codegen.StringSet)
...
-	Check      CheckProgramOutput
-	GenProgram GenProgram
-	TestCases  []ProgramTest
+	Language             string
+	Extension            string
+	OutputFile           string
+	Check                CheckProgramOutput
+	GenProgram           GenProgram
+	TestCases            []ProgramTest
+	AcceptCodegenChanges bool
```
[the remark this answers is not in the document]
Comment (Zaid-Ajaj) [reply pkg/codegen/testing/test/program_driver.go:199]: It was nice to have as a dev-only thing because GoLand didn't pick up my environment variable `PULUMI_ACCEPT` so  this overrides it, personally I like having this in here instead of env vars. It is false everywhere by default unless you set it somewhere to be `true` while working with codegen tests

[the remark this answers is not in the document]
Comment (iwahbe) [reply pkg/codegen/testing/test/program_driver.go:199]: I'm concerned about having a variable that should only be set to `false`, I think it is confusing. I would at least like a comment explaining why it exists. It would be better if you could corral GoLand into picking up your environmental variable.

[the remark this answers is not in the document]
Comment (Zaid-Ajaj) [reply pkg/codegen/testing/test/program_driver.go]: I've removed `AcceptCodegenChanges` now and will look for a better way to improve the DX when testing
