### PR TITLE
Fix snapshot integrity on pending replacement

### LINKED ISSUE #16916: Pulumi Azure Pipelines Task" on Windows fail with an `ENOENT`?
### What happened?

Getting an intermittent error when running the [Pulumi@1 task](https://www.pulumi.com/docs/using-pulumi/continuous-delivery/azure-devops/) on Windows agents.

Log:

```
Starting: Update myEnv mystack
==============================================================================
Task         : Pulumi Azure Pipelines Task
Description  : Azure Pipelines task extension for running Pulumi apps.
Version      : 1.0.16
Author       : Pulumi
Help         : Join us on Slack at https://slack.pulumi.com.
==============================================================================
Downloading: https://get.pulumi.com/releases/sdk/pulumi-v3.127.0-windows-x64.zip
Extracting archive
C:\Windows\system32\chcp.com 65001
Active code page: 65001
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\a\_temp\a3329957-ee74-4ae7-ad34-e82c1e3c3c13', 'C:\a\_temp\4ca5e9f0-1491-46f0-aba3-c1f05943c6d6')"
Prepending PATH environment variable with directory: C:\a\_temp\4ca5e9f0-1491-46f0-aba3-c1f05943c6d6\pulumi\bin
Caching tool: pulumi 3.127.0 x64
C:\a\_temp\4ca5e9f0-1491-46f0-aba3-c1f05943c6d6\pulumi\bin\pulumi.exe version
v3.127.0
C:\a\_temp\4ca5e9f0-1491-46f0-aba3-c1f05943c6d6\pulumi\bin\pulumi.exe login
Logging in using access token from PULUMI_ACCESS_TOKEN
Logged in to pulumi.com as stoo (https://app.pulumi.com/stoo)
C:\a\_temp\4ca5e9f0-1491-46f0-aba3-c1f05943c6d6\pulumi\bin\pulumi.exe stack select stoo/mystack
##[error]Error: There was an error when attempting to execute the process 'C:\a\_temp\4ca5e9f0-1491-46f0-aba3-c1f05943c6d6\pulumi\bin\pulumi.exe'. This may indicate the process failed to start. Error: spawn C:\a\_temp\4ca5e9f0-1491-46f0-aba3-c1f05943c6d6\pulumi\bin\pulumi.exe ENOENT
Finishing: Update myEnv mystack
```

We are using the Pulumi@1 task to run our pulumi commands

```yaml
- task: Pulumi@1
    displayName: Update myEnv ${{ parameters.myEnv1 }}
    inputs:
      command: "up"
      cwd: $(build-dir)/src/PulumiStacks/Scloud.PulumiStack.MyEnv
      stack: "stoo/${{ parameters.myEnv1 }}"
      args: "--non-interactive --yes"
    env:
      PULUMI_ACCESS_TOKEN: $(pulumi-access-token)
      ARM_TENANT_ID: $(azure-tenant-id)
      ARM_USE_MSI: true
    continueOnError: true
```
Full error message from the pipeline job:

```
error: could not deserialize deployment: snapshot integrity failure; refusing to use it: resource urn:pulumi:mystack::myenv::stoo:myenv$azure-native:resources:ResourceGroup$azure-native:web:WebApp::mystack-avail-func's property dependency urn:pulumi:mystack::myenv::azure-native:storage:BlobContainer$azure-native:storage:Blob::avail-test-func-archive (from property siteConfig) refers to missing resource
##[error]Pulumi command exited with code '4294967295' while trying to run 'up --non-interactive --yes'.
o
```

Another interesting finding: we are actually updating 2 stacks sequentially in the same pipeline job. These 2 stacks are based on the same Pulumi project.
Only the first stack has the issue described above whereas the second one seems to be always fine

### Example

Here's the code for the stack:

```
var azureFunction = new AzureFunction();
Web.AppServicePlan consumptionPlan = azureFunction.CreateConsumptionPlan("plan",
                                                          resourceGroup.Name,
                                                          new CustomResourceOptions
                                                          {
                                                              Parent = resourceGroup,
                                                              DeleteBeforeReplace = true
                                                          });

string containerName = "container";
var container = new Storage.BlobContainer(containerName, new Storage.BlobContainerArgs
{
    AccountName = storageAccount.Name,
    PublicAccess = PublicAccess.None,
    ResourceGroupName = resourceGroup.Name,
});

string blobName = "func-archive";
var blob = new Storage.Blob(blobName, new Storage.BlobArgs
{
    AccountName = storageAccount.Name,
    ContainerName = container.Name,
    ResourceGroupName = resourceGroup.Name,
    Type = Storage.BlobType.Block,
    Source = new FileArchive("azure/function/source")
}, new CustomResourceOptions { Parent = container, DeleteBeforeReplace = true });

SiteConfigArgs siteConfig = azureFunction.CreateSiteConfig(storageAccount.Name, blob);

Web.WebApp function = azureFunction.CreateFunction("function",
                                            resourceGroup.Name,
                                            consumptionPlan.Id,
                                            siteConfig,
                                            new CustomResourceOptions
                                            {
                                                Parent = resourceGroup,
                                                DependsOn = { storageAccount, consumptionPlan },
                                                DeleteBeforeReplace = true
                                            });
```

### Output of `pulumi about`

Using the pulumi task, so n/a

### Additional context

Let me know if you need any more info.

Thanks

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #17069: Resource `x` dependency `y` refers to missing resource
### What happened?

```
================================================================================
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:    v3.130.0
Go Version:        go1.22.6
Go Compiler:       gc
Architecture:      arm64
Operating System:  darwin
Command:           pulumi state delete urn:pulumi:staging::k8s-clusters::example:k8s:Cluster-native:eks:Nodegroup::k8s-staging-node-group
Error:             resource urn:pulumi:staging::k8s-clusters::example:k8s:Cluster$pulumi:providers:kubernetes::k8s-staging-provider's dependency urn:pulumi:staging::k8s-clusters::example:k8s:Cluster$aws-native:eks:Nodegroup::k8s-staging-node-group refers to missing resourc
```

### Example

# First up
- Create eks cluster
- Create node pool (t3.medium)
- Depend on nodepool (kubeconfig)

# second up
- update node pool instance type to t4g.medium
```
error: post-step event returned an error: failed to verify snapshot: resource urn:pulumi:staging::k8s-clusters::example:k8s:Cluster$pulumi:providers:kubernetes::k8s-staging-provider's dependency urn:pulumi:staging::k8s-clusters::example:k8s:Cluster$aws-native:eks:Nodegroup::k8s-staging-node-group refers to missing resource
```

### Output of `pulumi about`

```
CLI          
Version      3.130.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown

Host     
OS       darwin
Version  13.0.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v22.6.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/***
User           ***
Organizations ***
Token type     personal
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #17070: The Pulumi CLI encountered a snapshot integrity error
### What happened?

================================================================================
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:    v3.130.0
Go Version:        go1.22.6
Go Compiler:       gc
Architecture:      arm64
Operating System:  darwin
Command:           pulumi state delete urn:pulumi:sandbox::infra::azure-native:network:RecordSet::frontend-cname --force
Error:             resource urn:pulumi:sandbox::infra::azure-native:web:StaticSiteCustomDomain::staticSiteCustomDomain's dependency urn:pulumi:sandbox::infra::azure-native:network:RecordSet::frontend-cname refers to missing resource

### Example

-

### Output of `pulumi about`

Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.22.6/x64/src/runtime/debug/stack.go:24 +0x64
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x102e6e376?, 0x49?}, {0x14002d1f678?, 0x49?, 0x40?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:313 +0x30
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0x14000f0e630)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:217 +0xd9c
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).getSnapshot(0x140005abef0, {0x1040698c8, 0x10576cd80}, {0x104041720, 0x10576cd80}, 0x14001f2c980)
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/state.go:180 +0xf4
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Snapshot(0x14000f824b0, {0x1040698c8, 0x10576cd80}, {0x104041720, 0x10576cd80})
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/stack.go:62 +0x84
main.totalStateEdit({0x1040698c8, 0x10576cd80}, {0x104084318, 0x14000f824b0}, 0x1, {{0x102d8988f, 0x6}, 0x0, 0x0, 0x0, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:153 +0x6c
main.runTotalStateEdit({0x1040698c8, 0x10576cd80}, {0x0, 0x0}, 0x1, 0x1400213fb60)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:147 +0xf4
main.runStateEdit(...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:124
main.newStateDeleteCommand.func1(0x0?, {0x14000c643a0?, 0x1?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_delete.go:75 +0x164
main.newStateDeleteCommand.runCmdFunc.func2(0x0?, {0x14000c643a0?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:31 +0x28
main.newStateDeleteCommand.runCmdFunc.RunFunc.func5(0x140005b0308, {0x14000c643a0, 0x1, 0x2})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x38
github.com/spf13/cobra.(*Command).execute(0x140005b0308, {0x14000c64380, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x14000a07508)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x54

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #17073: Resource refers to missing resource which is set to use `delete_before_replace=True`
### What happened?

```
Pulumi Version:    v3.130.0
Go Version:        go1.22.6
Go Compiler:       gc
Architecture:      arm64
Operating System:  darwin
Command:           pulumi state delete urn:pulumi:sandbox::infra::azure-native:containerinstance:ContainerGroup::openfgaseed-container-group --force
Error:             resource urn:pulumi:sandbox::infra::command:local:Command::initSqlCommand's dependency urn:pulumi:sandbox::infra::azure-native:containerinstance:ContainerGroup::openfgaseed-container-group refers to missing resource

We delete the Container group before creating new one using `delete_before_replace=True` parameter. Often the resource that is dependent on this resource goes into a state that this resource doesnt exist anymore(may be caught up between delete and create.
```

### Example

1. Create command local and azurenative container Group resource with a dependency. 

### Output of `pulumi about`

```
Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.22.6/x64/src/runtime/debug/stack.go:24 +0x64
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x10207a376?, 0x65?}, {0x14002c9f678?, 0x65?, 0x40?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:313 +0x30
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0x14001f34630)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:217 +0xd9c
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).getSnapshot(0x140022ca870, {0x1032758c8, 0x104978d80}, {0x10324d720, 0x104978d80}, 0x1400229bb80)
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/state.go:180 +0xf4
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Snapshot(0x14002296570, {0x1032758c8, 0x104978d80}, {0x10324d720, 0x104978d80})
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/stack.go:62 +0x84
main.totalStateEdit({0x1032758c8, 0x104978d80}, {0x103290318, 0x14002296570}, 0x1, {{0x101f9588f, 0x6}, 0x0, 0x0, 0x0, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:153 +0x6c
main.runTotalStateEdit({0x1032758c8, 0x104978d80}, {0x0, 0x0}, 0x1, 0x140023bfb60)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:147 +0xf4
main.runStateEdit(...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:124
main.newStateDeleteCommand.func1(0x0?, {0x140021411c0?, 0x1?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_delete.go:75 +0x164
main.newStateDeleteCommand.runCmdFunc.func2(0x0?, {0x140021411c0?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:31 +0x28
main.newStateDeleteCommand.runCmdFunc.RunFunc.func5(0x1400216e308, {0x140021411c0, 0x1, 0x2})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x38
github.com/spf13/cobra.(*Command).execute(0x1400216e308, {0x140021411a0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x14001ed6908)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x54
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #17111: snapshot integrity error with Pulumi CLI
### What happened?

I got the below error while trying to run `pulumi refresh --stack=main` and it stated:

> We would appreciate a report: https://github.com/pulumi/pulumi/issues/
> Please provide all of the below text in your report.

### Example

```
Pulumi Version:    v3.130.0
Go Version:        go1.22.6
Go Compiler:       gc
Architecture:      arm64
Operating System:  darwin
Command:           pulumi refresh --stack=main
Error:             resource urn:pulumi:main::plus::gcp:certificatemanager/certificate:Certificate::example-load-balancer-certificate's dependency urn:pulumi:main::plus::gcp:certificatemanager/dnsAuthorization:DnsAuthorization::example-load-balancer-cert-auth-instance refers to missing resource

Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.22.6/x64/src/runtime/debug/stack.go:24 +0x64
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x104ed6376?, 0x78?}, {0x14001dbed38?, 0x78?, 0x40?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:313 +0x30
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0x14002514a20)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:217 +0xd9c
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getSnapshot(0x0?, {0x1060d18c8, 0x1077d4d80}, {0x1060a9720, 0x1077d4d80}, {0x1060d1de0?, 0x14001dbee50?})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:229 +0x74
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Snapshot(0x14001fd2af0, {0x1060d18c8, 0x1077d4d80}, {0x1060a9720, 0x1077d4d80})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/stack.go:151 +0xb0
main.newRefreshCmd.func1(0x14001e3ef08, {0x14001e7e930, 0x0, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/refresh.go:235 +0xcd0
main.newRefreshCmd.runCmdFunc.func2(0x0?, {0x14001e7e930?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:31 +0x28
main.newRefreshCmd.runCmdFunc.RunFunc.func5(0x14001e3ef08, {0x14001e7e930, 0x0, 0x1})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x38
github.com/spf13/cobra.(*Command).execute(0x14001e3ef08, {0x14001e7e910, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x14001e2c008)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x54
```

### Output of `pulumi about`

CLI          
Version      3.130.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME           VERSION
resource  aws            6.37.0
resource  gcp            7.38.0
resource  pulumiservice  0.17.0
language  python         unknown
resource  random         4.15.0
resource  tailscale      0.16.2

Host     
OS       darwin
Version  14.6.1
Arch     arm64

This project is written in python: executable='<snipped>/.venv/bin/python' version='3.11.3'

Backend        
Name           pulumi.com
<snipped>

Dependencies:
NAME        VERSION
<snipped>

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: snapshot integrity failure; refusing to use it: resource urn:pulumi:main::plus::gcp:certificatemanager/certificate:Certificate::example-load-balancer-certificate's dependency urn:pulumi:main::plus::gcp:certificatemanager/dnsAuthorization:DnsAuthorization::example-load-balancer-cert-auth-instance refers to missing resource

### Additional context

The `DnsAuthorization` resource has `delete_before_replace=True` on it, this happened while trying to change them and they are re-created.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Frassle**
This fixes a snapshot integrity issue with delete before replace, failed creates, and multiple updates.

This was caused by https://github.com/pulumi/pulumi/pull/16510 where we started removing pending replace resources as part of their replacement steps. A well intentioned fix to stop trying to delete resources we'd already deleted in a previous update. 

The bug would manifest if the following happened:
1. An update goes to replace a resource with `deleteBeforeCreate` set. It deletes the old resource (and saves the state as pending replace) but then failed to create the new replacement resource.
2. A second update is run to try and create the replacement resource. At this point the bug manifest and we delete the pending replace resource from state, but then if the new resource fails to create again we end up with an invalid snapshot.

The fix is very simple. If a resource is already pending replacement we just don't issue a delete/remove step at all. The pending replace resource will get cleaned up at the end by the create step creating the new version.

Fixes #17111
Fixes #17073
Fixes #17070
Fixes #17069
Fixes #16916

### CODE REVIEW

File: pkg/resource/deploy/step_generator.go [hunk 1]
```diff
@@ -1355,15 +1355,11 @@ func (sg *stepGenerator) generateStepsFromDiff(
 					return nil, fmt.Errorf("could not load provider for resource %v: %w", old.URN, err)
 				}
 
-				var deleteStep Step
-				if old.PendingReplacement {
-					deleteStep = NewRemovePendingReplaceStep(sg.deployment, old)
-				} else {
-					deleteStep = NewDeleteReplacementStep(sg.deployment, sg.deletes, old, true)
+				if !old.PendingReplacement {
+					steps = append(steps, NewDeleteReplacementStep(sg.deployment, sg.deletes, old, true))
```
Comment (lunaris) [inline pkg/resource/deploy/step_generator.go:1359]: I'd be tempted to add a comment here explaining that the pending replacement flag will get cleaned up when the replacement completes/the create executes, and that doing nothing is deliberate in this case?

**Review by lunaris — APPROVED** [review]
