### PR TITLE
[program-gen/csharp] Fixes generated code for a list of resources used in resource option DependsOn

### LINKED ISSUE #14462: pulumi convert for csharp with a DependsOn array is wrong
### What happened?

I ran `pulumi convert --generate-only --language csharp --out result` with a working, simple yaml file (shown below) for which there's a resource with two DependsOn. However, the generated csharp code contained an error when attempting to run it.

### Example

Pulumi.yaml contents
```yaml
name: quickstart
runtime: yaml
description: A minimal AWS Pulumi YAML program

variables:
  homepage:
    fn::fileAsset: ./index.html

resources:
  my-bucket:
    type: aws:s3:Bucket
    properties:
      website:
        indexDocument: index.html

  ownership-controls:
    type: aws:s3:BucketOwnershipControls
    properties:
      bucket: ${my-bucket.id}
      rule:
        objectOwnership: ObjectWriter

  public-access-block:
    type: aws:s3:BucketPublicAccessBlock
    properties:
      bucket: ${my-bucket.id}
      blockPublicAcls: false

  index.html:
    type: aws:s3:BucketObject
    properties:
      bucket: ${my-bucket.id}
      source: ${homepage}
      contentType: text/html
      acl: public-read
    options:
      dependsOn:
        - ${public-access-block}
        - ${ownership-controls}

outputs:
  bucketName: ${my-bucket.id}
  bucketEndpoint: http://${my-bucket.websiteEndpoint}

```

Version of the same code after running it through `pulumi convert`
```csharp
using Pulumi;
using Pulumi.Aws.S3;
using Pulumi.Aws.S3.Inputs;
using System.Collections.Generic;

return await Deployment.RunAsync(() =>
{
    var bucket = new Bucket("my-bucket", new()
    {
        Website = new BucketWebsiteArgs
        {
            IndexDocument = "index.html",
        },
    });

    var ownershipControls = new BucketOwnershipControls("ownership-controls", new()
    {
        Bucket = bucket.Id,
        Rule = new BucketOwnershipControlsRuleArgs
        {
            ObjectOwnership = "ObjectWriter",
        },
    });

    var publicAccessBlock = new BucketPublicAccessBlock("public-access-block", new()
    {
        Bucket = bucket.Id,
        BlockPublicAcls = false,
    });

    var indexHtml = new BucketObject("index.html", new()
    {
        Bucket = bucket.Id,
        Source = new FileAsset("./index.html"),
        ContentType = "text/html",
        Acl = "public-read",
    }, new CustomResourceOptions
    {
        DependsOn = new []
        {
            publicAccessBlock,
            ownershipControls,
        },
    });

    return new Dictionary<string, object?>
    {
        ["bucketName"] = bucket.Id,
        ["bucketEndpoint"] = bucket.WebsiteEndpoint.Apply(websiteEndpoint => $"http://{websiteEndpoint}"),
    };
});
```

### Output of `pulumi about`

```bash
pulumi about
CLI          
Version      3.91.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME  VERSION
aws   unknown
yaml  unknown

Host     
OS       darwin
Version  14.0
Arch     arm64

This project is written in yaml```

### Additional context

A small fix to the csharp code worked by explicitly typing the array.

Working code snippet:

```csharp
    var indexHtml = new BucketObject("index.html", new()
    {
        Bucket = bucket.Id,
        Source = new FileAsset("./index.html"),
        ContentType = "text/html",
        Acl = "public-read",
    }, new CustomResourceOptions
    {
        DependsOn = new Resource[].  // <------------ FIX -------------
        {
            publicAccessBlock,
            ownershipControls,
        },
    });

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

Fixes #14462 by special casing how we handle `dependsOn` and generating `DependsOn = { ... }` instead of `DependsOn = new[] { ... }`

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/codegen/dotnet/gen_program.go [hunk 1]
```diff
@@ -1135,6 +1135,22 @@ func (g *generator) genResourceOptions(opts *pcl.ResourceOptions, resourceOption
 			} else {
 				g.Fgenf(&result, "\n%s%s = %v,", g.Indent, name, g.lowerExpression(value, value.Type()))
 			}
+		} else if name == "DependsOn" {
+			// depends on need to be special cased
+			// because new [] { resourceA, resourceB } cannot be implicitly casted to InputList<Resource>
```
Comment (Frassle) [inline pkg/codegen/dotnet/gen_program.go:1140]: Might be worth a comment here why we're preferring the initialiser expression to `new Resource[] { A, B }`.

**Review by Frassle — APPROVED** [review]

File: changelog/pending/20240324--programgen-dotnet--fixed-generated-code-for-a-list-of-resources-used-in-resource-option-dependson.yaml [hunk 2]
```diff
@@ -0,0 +1,4 @@
+changes:
+- type: fix
+  scope: programgen/dotnet
+  description: Fixes generated code for a list of resources used in resource option DependsOn
```
Comment (tgummerer) [inline changelog/pending/20240324--programgen-dotnet--fixed-generated-code-for-a-list-of-resources-used-in-resource-option-dependson.yaml:4]:
```suggestion
  description: Fix generated code for a list of resources used in resource option DependsOn
```

Comment (Frassle) [reply changelog/pending/20240324--programgen-dotnet--fixed-generated-code-for-a-list-of-resources-used-in-resource-option-dependson.yaml:4]: Your getting good at spotting these!

File: pkg/codegen/dotnet/gen_program.go (hunk 1 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/dotnet/gen_program.go:1140]: I don't think it matters which syntax we go with, both implicitly convert to `InputList<Resource>` which is the type of the `DependsOn` field

File: changelog/pending/20240324--programgen-dotnet--fixed-generated-code-for-a-list-of-resources-used-in-resource-option-dependson.yaml (hunk 2 above)
Comment (Zaid-Ajaj) [reply changelog/pending/20240324--programgen-dotnet--fixed-generated-code-for-a-list-of-resources-used-in-resource-option-dependson.yaml]: Thanks @tgummerer 🙏
