### PR TITLE
Fix `--glob` behaviour for `exclude`

### LINKED ISSUE #19084: `pulumi up --exclude` does not exclude deletions
### What happened?

I run `pulumi up -s dev --exclude "**pubsub**"`

All pubsub creations are excluded.
pubsub deletions are **not** excluded - but they probably should.

### Example

` -   ├─ gcp:pubsub:SubscriptionIAMMember`

### Output of `pulumi about`

```
warning: using pulumi-language-go from $PATH at /Users/REDACTED/go/bin/pulumi-language-go expected /Users/REDACTED/.pulumi/bin/pulumi-language-go
CLI
Version      3.159.0
Go Version   go1.24.1
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.65.0
resource  command     1.0.1
resource  datadog     4.12.0
resource  gcp         7.23.0
language  go          3.93.1-dev.0
resource  kubernetes  4.1.0
resource  random      4.8.2

Host
OS       darwin
Version  15.3.1
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.24.0 darwin/arm64'

Backend
Name           REDACTED
URL            REDACTED
User           REDACTED
Organizations
Token type     personal

Dependencies:
NAME                                              VERSION
cloud.google.com/go/cloudsqlconn                  v1.9.0
cloud.google.com/go/compute/metadata              v0.5.2
cloud.google.com/go/kms                           v1.18.1
cloud.google.com/go/pubsub                        v1.40.0
cloud.google.com/go/run                           v1.3.8
cloud.google.com/go/secretmanager                 v1.13.2
cosmossdk.io/api                                  v0.7.6
cosmossdk.io/errors                               v1.0.1
cosmossdk.io/math                                 v1.4.0
github.com/MicahParks/keyfunc                     v1.9.0
github.com/TwiN/gocache/v2                        v2.2.2
github.com/adshao/go-binance/v2                   v2.4.5
github.com/aptos-labs/aptos-go-sdk                v1.5.0
github.com/auth0/go-auth0                         v0.12.0
github.com/avast/retry-go/v4                      v4.6.0
github.com/aws/aws-sdk-go-v2/config               v1.29.2
github.com/aws/aws-sdk-go-v2/feature/ec2/imds     v1.16.25
github.com/aws/aws-sdk-go-v2/service/kms          v1.37.14
github.com/btcsuite/btcd                          v0.24.3-0.20241008130920-ee68dc66a835
github.com/btcsuite/btcd/btcutil                  v1.1.6
github.com/centrifuge/go-substrate-rpc-client/v4  v4.2.2-0.20240919131012-e3b938563803
github.com/cockroachdb/errors                     v1.11.3
github.com/coinbase/kryptology                    v0.0.0
github.com/cometbft/cometbft                      v0.38.17
github.com/coming-chat/go-sui/v2                  v2.0.1
github.com/cosmos/btcutil                         v1.0.5
github.com/cosmos/cosmos-proto                    v1.0.0-beta.5
github.com/cosmos/cosmos-sdk                      v0.50.13
github.com/cosmos/gogoproto                       v1.7.0
github.com/cosmos/ibc-go/v9                       v9.0.0
github.com/decred/base58                          v1.0.4
github.com/defiweb/go-eth                         v0.7.0
github.com/defiweb/go-rlp                         v0.3.0
github.com/docker/docker                          v26.1.5+incompatible
github.com/emicklei/proto                         v1.11.2
github.com/ethereum/go-ethereum                   v1.14.13
github.com/exgalibas/logrus-filename              v0.0.0-20230106110712-c320f793ed5a
github.com/fardream/go-bcs                        v0.8.7
github.com/fergusstrange/embedded-postgres        v1.28.0
github.com/fxamacker/cbor/v2                      v2.5.0
github.com/gagliardetto/binary                    v0.8.0
github.com/gagliardetto/metaplex-go               v0.2.1
github.com/gagliardetto/solana-go                 v1.12.0
github.com/gagliardetto/treeout                   v0.1.4
github.com/go-git/go-git/v5                       v5.13.2
github.com/go-webauthn/webauthn                   v0.8.4
github.com/golang-jwt/jwt                         v3.2.2+incompatible
github.com/golang-jwt/jwt/v4                      v4.5.2
github.com/golang-migrate/migrate/v4              v4.16.2
github.com/golang/protobuf                        v1.5.4
github.com/google/go-cmp                          v0.6.0
github.com/google/go-jsonnet                      v0.18.0
github.com/google/go-querystring                  v1.1.0
github.com/gorilla/mux                            v1.8.1
github.com/grpc-ecosystem/go-grpc-middleware      v1.4.0
github.com/grpc-ecosystem/grpc-gateway/v2         v2.20.0
github.com/hashicorp/go-retryablehttp             v0.7.7
github.com/hashicorp/golang-lru                   v1.0.2
github.com/hashicorp/golang-lru/v2                v2.0.7
github.com/hf/nsm                                 v0.0.0-20220930140112-cd181bd646b9
github.com/improbable-eng/grpc-web                v0.15.1-0.20230209220825-1d9bbb09a099
github.com/jackc/pgx/v5                           v5.6.1-0.20240715132227-ea9610f6722e
github.com/jarcoal/httpmock                       v1.3.1
github.com/jinzhu/copier                          v0.3.5
github.com/joefitzgerald/passwordcredentials      v0.0.0-20220127062845-f6408ea31f18
github.com/knocklabs/knock-go                     v0.1.13
github.com/launchdarkly/api-client-go             v5.3.0+incompatible
github.com/launchdarkly/go-sdk-common/v3          v3.0.0
github.com/launchdarkly/go-server-sdk/v6          v6.0.1
github.com/lbrlabs/pulumi-launchdarkly/sdk        v0.0.0-20221217202120-d871b936153a
github.com/lib/pq                                 v1.10.9
github.com/mdlayher/vsock                         v1.2.1
github.com/mr-tron/base58                         v1.2.0
github.com/otterize/lox                           v0.0.0-20220525164329-9ca2bf91c3dd
github.com/pkg/browser                            v0.0.0-20240102092130-5ac0b6a4141c
github.com/pulumi/pulumi-aws/sdk/v6               v6.65.0
github.com/pulumi/pulumi-command/sdk              v1.0.1
github.com/pulumi/pulumi-datadog/sdk/v4           v4.12.0
github.com/pulumi/pulumi-gcp/sdk/v7               v7.23.0
github.com/pulumi/pulumi-kubernetes/sdk/v4        v4.1.0
github.com/pulumi/pulumi-random/sdk/v4            v4.8.2
github.com/pulumi/pulumi/sdk/v3                   v3.142.0
github.com/robfig/cron/v3                         v3.0.1
github.com/rodaine/table                          v1.1.1
github.com/samber/lo                              v1.47.0
github.com/segmentio/ksuid                        v1.0.4
github.com/sendgrid/sendgrid-go                   v3.12.0+incompatible
github.com/sethvargo/go-password                  v0.2.0
github.com/shengdoushi/base58                     v1.0.0
github.com/shopspring/decimal                     v1.3.1
github.com/sirupsen/logrus                        v1.9.3
github.com/slack-go/slack                         v0.11.4
github.com/stretchr/testify                       v1.10.0
github.com/tonkeeper/tonapi-go                    v0.0.6
github.com/tonkeeper/tongo                        v1.9.0
github.com/urfave/cli/v2                          v2.25.7
github.com/vedhavyas/go-subkey/v2                 v2.0.0
github.com/veraison/go-cose                       v1.3.0
github.com/vishvananda/netlink                    v1.3.0
github.com/weft-finance/vayu-go                   v0.2.2
github.com/yeqown/go-qrcode/v2                    v2.2.4
github.com/yeqown/go-qrcode/writer/standard       v1.2.4
github.com/yeqown/go-qrcode/writer/terminal       v1.1.1
go.einride.tech/aip                               v0.67.1
go.uber.org/mock                                  v0.4.0
gocloud.dev                                       v0.34.0
golang.org/x/crypto                               v0.35.0
golang.org/x/exp                                  v0.0.0-20240719175910-8a7402abbf56
golang.org/x/net                                  v0.36.0
golang.org/x/oauth2                               v0.24.0
golang.org/x/text                                 v0.22.0
golang.org/x/tools                                v0.24.0
google.golang.org/genproto/googleapis/api         v0.0.0-20241202173237-19429a94021a
google.golang.org/genproto/googleapis/rpc         v0.0.0-20241202173237-19429a94021a
google.golang.org/grpc                            v1.70.0
google.golang.org/protobuf                        v1.36.4
gopkg.in/DataDog/dd-trace-go.v1                   v1.70.3
gopkg.in/dnaeon/go-vcr.v3                         v3.1.2
gorm.io/datatypes                                 v1.2.0
gorm.io/driver/postgres                           v1.5.9
gorm.io/gorm                                      v1.25.11
k8s.io/api                                        v0.28.12
k8s.io/apimachinery                               v0.28.12
k8s.io/client-go                                  v0.28.12
k8s.io/kubernetes                                 v1.29.14
cloud.google.com/go/storage                       v1.41.0
filippo.io/edwards25519                           v1.1.0
github.com/DataDog/datadog-go/v5                  v5.5.0
github.com/btcsuite/btcd/chaincfg/chainhash       v1.1.0
github.com/davecgh/go-spew                        v1.1.2-0.20180830191138-d8f796af33cc
github.com/deckarep/golang-set/v2                 v2.6.0
github.com/decred/dcrd/dcrec/secp256k1/v4         v4.3.0
github.com/google/uuid                            v1.6.0
github.com/gorilla/websocket                      v1.5.3
github.com/holiman/uint256                        v1.3.1
github.com/mitchellh/mapstructure                 v1.5.1-0.20231216201459-8508981c8b6c
github.com/patrickmn/go-cache                     v2.1.0+incompatible
golang.org/x/sync                                 v0.11.0
golang.org/x/sys                                  v0.30.0
google.golang.org/api                             v0.186.0
gopkg.in/yaml.v2                                  v2.4.0
gopkg.in/yaml.v3                                  v3.0.1
```

### Additional context

Original slack message:
https://pulumi-community.slack.com/archives/C84L4E3N1/p1743364818118099

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by i-am-tom**
The `--exclude` flag only considered literals as arguments, but ignored globs. This PR fixes that.

Fixes #19084.

### CODE REVIEW

File: pkg/resource/deploy/step_generator.go [hunk 1]
```diff
@@ -1949,6 +1949,11 @@ func (sg *stepGenerator) GenerateDeletes(targetsOpt UrnTargets, excludesOpt UrnT
 				continue
 			}
 
+			if forbiddenResourcesToDelete != nil && forbiddenResourcesToDelete[res.URN] {
```
Comment (Frassle) [inline pkg/resource/deploy/step_generator.go]: Isn't this just the same as what isTargeted is checking? And now your not adding a same step for it, like we should do at line ~2012

File: changelog/pending/20250728--cli-engine--exclude-now-also-excludes-unregistered-resources-from-operations-like-up-and-destroy.yaml [hunk 2]
```diff
@@ -0,0 +1,4 @@
+changes:
+- type: fix
+  scope: cli/engine
+  description: `--exclude` now also excludes unregistered resources from operations like `up` and `destroy`
```
Comment (tgummerer) [inline changelog/pending/20250728--cli-engine--exclude-now-also-excludes-unregistered-resources-from-operations-like-up-and-destroy.yaml]:
```suggestion
  description: Make `--exclude` also exclude unregistered resources from operations like `up` and `destroy`
```

File: pkg/resource/deploy/step_generator.go [hunk 3]
```diff
@@ -2135,6 +2135,38 @@ func (sg *stepGenerator) getTargetDependents(targetsOpt UrnTargets) map[resource
...
+	excludes := make(map[resource.URN]bool)
+	for len(frontier) > 0 {
+		next := frontier[0]
+		frontier = frontier[1:]
+		if _, has := excludes[next.URN]; has {
+			continue
+		}
+		excludes[next.URN] = true
+
+		deps := dg.DependenciesOf(next)
```
Comment (tgummerer) [inline pkg/resource/deploy/step_generator.go:2158]: We also have `dg.TransitiveDependenciesOf`.  I was wondering if we could rewrite the function to something like:
```
	var excluded []*resource.State
	for _, res := range sg.deployment.prev.Resources {
		if excludesOpt.Contains(res.URN) {
			excluded = append(excluded, res)
			transitiveDeps := dg.TransitiveDependenciesOf(res)
			for _, dep := range transitiveDeps {
				excluded = append(excluded, dep)
			}
		}
	}
```

(Potentially still checking for if we already included a dep in the list so we don't duplicate it).  

Although on second thought, I think that's more expensive than what you're proposing here, so I think it's better to keep it as is.
