### PR TITLE
Patch go plain input

### LINKED ISSUE #9486: [codegen] Updating to latest codegen causes broken DotNet SDK
### What happened?

When upgrading to https://github.com/pulumi/pulumi/commit/9a8d8d928f7a760bf61c40863e8cbbfacea082f7 we re-run our codegen and we get the following output:

```
  Determining projects to restore...
  Restored /Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj (in 1.84 sec).
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/Bucket.cs(54,42): error CS0234: The type or namespace name 'BucketCorsRule' does not exist in the namespace 'Pulumi.Aws.S3.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/Bucket.cs(72,42): error CS0234: The type or namespace name 'BucketGrant' does not exist in the namespace 'Pulumi.Aws.S3.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/Bucket.cs(90,42): error CS0234: The type or namespace name 'BucketLifecycleRule' does not exist in the namespace 'Pulumi.Aws.S3.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/Bucket.cs(102,42): error CS0234: The type or namespace name 'BucketLogging' does not exist in the namespace 'Pulumi.Aws.S3.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/Bucket.cs(112,37): error CS0234: The type or namespace name 'BucketObjectLockConfiguration' does not exist in the namespace 'Pulumi.Aws.S3.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/Bucket.cs(124,37): error CS0234: The type or namespace name 'BucketReplicationConfiguration' does not exist in the namespace 'Pulumi.Aws.S3.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/Bucket.cs(139,37): error CS0234: The type or namespace name 'BucketServerSideEncryptionConfiguration' does not exist in the namespace 'Pulumi.Aws.S3.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/Bucket.cs(157,37): error CS0234: The type or namespace name 'BucketVersioning' does not exist in the namespace 'Pulumi.Aws.S3.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/Bucket.cs(163,37): error CS0234: The type or namespace name 'BucketWebsite' does not exist in the namespace 'Pulumi.Aws.S3.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/Bucket.cs(49,43): error CS0234: The type or namespace name 'BucketCorsRule' does not exist in the namespace 'Pulumi.Aws.S3.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/Bucket.cs(67,43): error CS0234: The type or namespace name 'BucketGrant' does not exist in the namespace 'Pulumi.Aws.S3.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/Bucket.cs(85,43): error CS0234: The type or namespace name 'BucketLifecycleRule' does not exist in the namespace 'Pulumi.Aws.S3.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/Bucket.cs(97,43): error CS0234: The type or namespace name 'BucketLogging' does not exist in the namespace 'Pulumi.Aws.S3.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Lb/Inputs/Listener.cs(982,42): error CS0234: The type or namespace name 'ListenerDefaultAction' does not exist in the namespace 'Pulumi.Aws.LB.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Lb/Inputs/TargetGroup.cs(260,37): error CS0234: The type or namespace name 'TargetGroupHealthCheck' does not exist in the namespace 'Pulumi.Aws.LB.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Lb/Inputs/Listener.cs(977,43): error CS0234: The type or namespace name 'ListenerDefaultAction' does not exist in the namespace 'Pulumi.Aws.LB.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Lb/Inputs/TargetGroup.cs(326,37): error CS0234: The type or namespace name 'TargetGroupStickiness' does not exist in the namespace 'Pulumi.Aws.LB.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/RoleWithPolicy.cs(36,43): error CS0234: The type or namespace name 'RoleInlinePolicy' does not exist in the namespace 'Pulumi.Aws.Iam.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/RoleWithPolicy.cs(31,44): error CS0234: The type or namespace name 'RoleInlinePolicy' does not exist in the namespace 'Pulumi.Aws.Iam.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/SecurityGroup.cs(30,43): error CS0234: The type or namespace name 'SecurityGroupEgress' does not exist in the namespace 'Pulumi.Aws.Ec2.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/SecurityGroup.cs(42,43): error CS0234: The type or namespace name 'SecurityGroupIngress' does not exist in the namespace 'Pulumi.Aws.Ec2.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/SecurityGroup.cs(25,44): error CS0234: The type or namespace name 'SecurityGroupEgress' does not exist in the namespace 'Pulumi.Aws.Ec2.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Awsx/Inputs/SecurityGroup.cs(37,44): error CS0234: The type or namespace name 'SecurityGroupIngress' does not exist in the namespace 'Pulumi.Aws.Ec2.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Ecs/Inputs/EC2ServiceTaskDefinition.cs(54,38): error CS0234: The type or namespace name 'TaskDefinitionEphemeralStorage' does not exist in the namespace 'Pulumi.Aws.Ecs.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Ecs/Inputs/EC2ServiceTaskDefinition.cs(75,43): error CS0234: The type or namespace name 'TaskDefinitionInferenceAccelerator' does not exist in the namespace 'Pulumi.Aws.Ecs.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Ecs/Inputs/FargateServiceTaskDefinition.cs(54,38): error CS0234: The type or namespace name 'TaskDefinitionEphemeralStorage' does not exist in the namespace 'Pulumi.Aws.Ecs.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Ecs/Inputs/FargateServiceTaskDefinition.cs(75,43): error CS0234: The type or namespace name 'TaskDefinitionInferenceAccelerator' does not exist in the namespace 'Pulumi.Aws.Ecs.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Ecs/Inputs/EC2ServiceTaskDefinition.cs(118,43): error CS0234: The type or namespace name 'TaskDefinitionPlacementConstraint' does not exist in the namespace 'Pulumi.Aws.Ecs.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Ecs/Inputs/EC2ServiceTaskDefinition.cs(128,38): error CS0234: The type or namespace name 'TaskDefinitionProxyConfiguration' does not exist in the namespace 'Pulumi.Aws.Ecs.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Ecs/Inputs/EC2ServiceTaskDefinition.cs(134,38): error CS0234: The type or namespace name 'TaskDefinitionRuntimePlatform' does not exist in the namespace 'Pulumi.Aws.Ecs.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Ecs/Inputs/FargateServiceTaskDefinition.cs(112,43): error CS0234: The type or namespace name 'TaskDefinitionPlacementConstraint' does not exist in the namespace 'Pulumi.Aws.Ecs.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Ecs/Inputs/FargateServiceTaskDefinition.cs(122,38): error CS0234: The type or namespace name 'TaskDefinitionProxyConfiguration' does not exist in the namespace 'Pulumi.Aws.Ecs.Inputs' (are you missing an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-awsx/sdk/dotnet/Pulumi.Awsx.csproj]
```

### Steps to reproduce

Checkout awsx - change schemagen/go.mod to reference above commit

run make build and watch the failure

### Expected Behavior

The above commit should fix a Go codegen issue

### Actual Behavior

Codegen is now broken for at least DotNet

### Versions used

_No response_

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by iwahbe**
# Description

We need to revert #9430 because it will cause backwards incompatible changes. We still need the fix that it introduced though. 

Fixes #9486 

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by danielrbradley — APPROVED** [review]
Tested in awsx here: https://github.com/pulumi/pulumi-awsx/pull/800

File: pkg/codegen/testing/test/testdata/plain-object-defaults/dotnet/Inputs/LayeredTypeArgs.cs [hunk 1]
```diff
@@ -28,7 +28,7 @@ public sealed class LayeredTypeArgs : Pulumi.ResourceArgs
         /// Test how plain types interact
         /// </summary>
         [Input("plainOther")]
-        public Inputs.HelmReleaseSettings? PlainOther { get; set; }
+        public Inputs.HelmReleaseSettingsArgs? PlainOther { get; set; }
```
Comment (AaronFriel) [inline pkg/codegen/testing/test/testdata/plain-object-defaults/dotnet/Inputs/LayeredTypeArgs.cs:31]: I'm a little confused why this change to `go/gen.go` and `schema/schema.go` resulted in renaming a lot of other types. Is this going to require a major version bump for our other packages due to renames?

**Review by AaronFriel — CHANGES_REQUESTED** [review]
Blocking comment in here for now

File: pkg/codegen/testing/test/testdata/plain-object-defaults/dotnet/Inputs/LayeredTypeArgs.cs (hunk 1 above)
Comment (iwahbe) [reply pkg/codegen/testing/test/testdata/plain-object-defaults/dotnet/Inputs/LayeredTypeArgs.cs:31]: Because we change how `plain` types are generated back to the pre https://github.com/pulumi/pulumi/pull/9430 algorithm. As it stands, pulumi/pulumi currently exhibits a breaking change which this PR undoes. The result is no breaking change between our last release (pre https://github.com/pulumi/pulumi/pull/9430) and our next release (post #9488).

**Review by AaronFriel — APPROVED** [review]
