### PR TITLE
Fix wierd interactions due to Cobra and glog

### LINKED ISSUE #301: Remove glog usage; just do standard Go logging
At the moment, we use glog.  This is nice in that it gives us leveled logging.  It's not so nice in that it's really hard to configure (in part because of its global dependency on flag).  Related to this, with multiple processes, it's hard to redirect everything to where it ought to go.

Let's consider going back to the standard Go logging library, perhaps with minimal sugar on top.

### LINKED ISSUE #710: Nit: improve command line parse errors in CLI
`$ pulumi -version`

```
An error occurred: invalid argument "ersion" for "-v, --verbose" flag: strconv.ParseInt: parsing "ersion": invalid syntax
```

### LINKED ISSUE #968: Confusing help message when incorrectly using logging flags
When you put a logging flag between `pulumi` and the verb you're intending to log, you get a funny help message that doesn't line up with reality:

```
$ pulumi --logflow update
flag provided but not defined: -logflow
Usage of pulumi:
  -C string
    	Run pulumi as if it had been started in another directory
  -alsologtostderr
    	log to standard error as well as files
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory
  -logtostderr
    	log to standard error instead of files
  -stderrthreshold value
    	logs at or above this threshold go to stderr
  -v value
    	log level for V logs
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
```

`pulumi update --logflow` works since Cobra parses it correctly.

This is confusing and it seems to me like `google/glog` is hijacking flag parsing somewhere and Cobra doesn't know about it.

### PR DESCRIPTION
**Pull request by ellismg**
The glog package force the use of golang's underyling flag package,
which Cobra does not use. To work around this, we had a complicated
dance around defining flags in multiple places, calling flag.Parse
explicitly and then stomping values in the flag package with values we
got from Cobra.

Because we ended up parsing parts of the command line twice, each with
a different set of semantics, we ended up with bad UX in some
cases. For example:

`$ pulumi -v=10 --logflow update`

Would fail with an error message that looked nothing like normal CLI
errors, where as:

`$ pulumi -v=10 update --logflow`

Would behave as you expect. To address this, we now do two things:

- We never call flag.Parse() anymore. Wacking the flags with values we
  got from Cobra is sufficent for what we care about.

- We use a forked copy of glog which does not complain when
  flag.Parse() is not called before logging.

Fixes #301
Fixes #710
Fixes #968

### CODE REVIEW

File: pkg/resource/plugin/plugin.go [hunk 1]
```diff
@@ -229,7 +229,7 @@ func execPlugin(bin string, pluginArgs []string, pwd string) (*plugin, error) {
 	// Flow the logging information if set.
 	if logging.LogFlow {
 		if logging.LogToStderr {
-			args = append(args, "--logtostderr")
+			args = append(args, "-logtostderr")
```
Comment (ellismg) [inline pkg/resource/plugin/plugin.go]: All the plugins were using `flag` directly (and hence calling `flag.Parse()`), and this is the preferred form for options there.

Comment (pgavlin) [reply pkg/resource/plugin/plugin.go]: :+1:
