### PR TITLE
[sdk/nodejs] Fix serialized async generators

### LINKED ISSUE #21483: Serialized async generators missing `async` keyword from function declaration
We recently added support for serializing async generators in #21410.

However, there's still an issue: the serialized code can't actually be used because the serialized function declaration is missing the `async` keyword.

Consider:

```js
module.exports.func = async function* () {
    await new Promise((resolve) => setTimeout(resolve, 100));
    yield "Hello";
    console.log("World");
};
```

which is currently serialized as:

```js
exports.handler = __f0;

var __f0_prototype = Object.create(Object.getPrototypeOf((async function*(){}).prototype));
Object.defineProperty(__f0, "prototype", { writable: true, value: __f0_prototype });

function __f0() {
  return (function() {
    with({ this: undefined, arguments: undefined }) {

return function* () {
    await new Promise((resolve) => setTimeout(resolve, 100));
    yield "Hello";
    console.log("World");
};

    }
  }).apply(undefined, undefined).apply(this, arguments);
}
```

It should be this (diff):

```diff
exports.handler = __f0;

var __f0_prototype = Object.create(Object.getPrototypeOf((async function*(){}).prototype));
Object.defineProperty(__f0, "prototype", { writable: true, value: __f0_prototype });

function __f0() {
  return (function() {
    with({ this: undefined, arguments: undefined }) {

-return function* () {
+return async function* () {
    await new Promise((resolve) => setTimeout(resolve, 100));
    yield "Hello";
    console.log("World");
};

    }
  }).apply(undefined, undefined).apply(this, arguments);
}
```

### PR DESCRIPTION
**Pull request by justinvp**
We recently added support for serializing async generators in #21410. However, there's an issue: the serialized code couldn't actually be used because the serialized function declaration is missing the async keyword. This change fixes that.

Fixes #21483

### CODE REVIEW

File: sdk/nodejs/runtime/closure/parseFunction.ts [hunk 1]
```diff
@@ -314,7 +314,7 @@ function makeFunctionDeclaration(
 
     if (v.startsWith("*")) {
         v = v.slice(1).trimLeft();
-        prefix = "function* ";
+        prefix = isAsync ? "async function* " : "function* ";
```
Comment (Frassle) [inline sdk/nodejs/runtime/closure/parseFunction.ts]:
```suggestion
        prefix = (isAsync ? "async " : "") + "function* ";
```
Maybe?
