### PR TITLE
`pulumi new` now supports numeric stack names.

### LINKED ISSUE #12136: pulumi new fails when project name is numeric
### What happened?

`pulumi new` flow errors when a numeric name is provided probably because YAML numerics are assumed to be numbers.

[asciicast](https://asciinema.org/a/fmb4HTN6jZzNnjRXsLE4etIE9)

### Expected Behavior

Pulumi.yaml to be saved as

```yaml
name: "12345"
description: A minimal JavaScript Pulumi program
runtime:
  name: nodejs
  options:
    typescript: false
template:
  description: A minimal JavaScript Pulumi program
```

### Steps to reproduce

See asciinema recording.

`pulumi up` also fails with a poor error message

```
error: could not get cloud url: could not load current project: could not validate '/home/kdixler/foo/Pulumi.yaml': project is missing a non-empty string 'name' attribute
```

```yaml
name: 12345
description: A minimal JavaScript Pulumi program
runtime:
  name: nodejs
  options:
    typescript: false
template:
  description: A minimal JavaScript Pulumi program
```

### Output of `pulumi about`

```
CLI          
Version      3.54.1-dev.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       arch
Version  22.0.2
Arch     x86_64

This project is written in nodejs: executable='/home/kdixler/.nvm/versions/node/v14.19.1/bin/node' version='v14.19.1'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/dixler
User           dixler
Organizations  dixler, EpicGames, organization, pulumi

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either /home/kdixler/foo/yarn.lock or /home/kdixler/foo/package-lock.json
warning: Failed to get information about the current stack: No current stack
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description

`pulumi new` now correctly serializes a stack name of 123456 as a string in the `Pulumi.yaml` file.

Previously `123456` is interpreted as a number in YAML by default.

Fixes #12136 

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: sdk/go/common/workspace/templates.go [hunk 1]
```diff
@@ -502,13 +502,25 @@ func CopyTemplateFilesDryRun(sourceDir, destDir, projectName string) error {
 func CopyTemplateFiles(
 	sourceDir, destDir string, force bool, projectName string, projectDescription string,
 ) error {
+	// Needed for stringifying numeric user-provided project names.
+	yamlName := projectName
```
Comment (Frassle) [inline sdk/go/common/workspace/templates.go:506]: Why are we declaring this (and description below) to one value but unconditionally overwriting that with the YAML value. Looks like we can just drop these first declarations.

File: pkg/cmd/pulumi/new_acceptance_test.go [hunk 2]
```diff
@@ -64,6 +64,34 @@ func TestCreatingStackWithArgsSpecifiedName(t *testing.T) {
 	removeStack(t, tempdir, stackName)
 }
 
+//nolint:paralleltest // changes directory for process
+func TestCreatingStackWithNumericName(t *testing.T) {
+	tempdir, _ := os.MkdirTemp("", "test-env")
+	defer os.RemoveAll(tempdir)
```
Comment (abhinav) [inline pkg/cmd/pulumi/new_acceptance_test.go:70]: Use `t.TempDir()` here to have `testing.T` manage this for you.
```suggestion
	tempdir := t.TempDir()
```

**Review by abhinav — APPROVED** [review]

File: sdk/go/common/workspace/templates.go (hunk 1 above)
Comment (abhinav) [reply sdk/go/common/workspace/templates.go:506]: I'm guessing Kyle was trying to convert the `[]byte` to string early.

@dixler we can do either:

```go
yamlName, err := yaml.Marshal(projectName) 
// ...
name = string(yamlName)
```

or if you'd prefer for yamlName to be a string, a helper function `yamlName, err := yamlToString(projectName)`.

Comment (dixler) [reply sdk/go/common/workspace/templates.go:506]: was copying the existing code. can clean it up a bit more.

Comment (dixler) [reply sdk/go/common/workspace/templates.go]: We will error if the project name or description was unable to be serialized to YAML for some reason rather than only if we are serializing to YAML.

**Comment by dixler** [comment]
Addressed nits going to merge.

**Comment by dixler** [comment]
bors merge

**Comment by dixler** [comment]
bors merge

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
bors merge
