### PR TITLE
Fix panic in SDK generator for Go for map[string]map[string]union

### LINKED ISSUE #19730: Go gen fails for type `Map<string, Map<string, Union<string, Array<string>>>>`
### What happened?

I have a type with this definition

```go
TypeSpec: schema.TypeSpec{
    Type: "object",
    AdditionalProperties: &schema.TypeSpec{
      Type: "object",
      AdditionalProperties: &schema.TypeSpec{
        OneOf: []schema.TypeSpec{
          {Type: "string"},
          {Type: "array", Items: &schema.TypeSpec{Type: "string"}},
        },
      },
    },
  },
```

And running `make build_go` fails with

```console
Applied 316 replacementspanic: fatal: An assertion has failed: tok: Input<Union<Input<string>, Input<Array<Input<string>>>>>

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.166.0/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0xc0?, {0x11950b9db?, 0x11ba92d48?}, {0x1402ff27b88?, 0x0?, 0x1402ff27b88?})
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.166.0/go/common/util/contract/assert.go:35 +0xe0
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*pkgContext).tokenToType(0x14016674120, {0x1400e8f4ac0, 0x38})
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.166.0/codegen/go/gen.go:218 +0x9c
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*pkgContext).nestedTypeToType(0x14016674120, {0x11f61cbe0?, 0x1401a6b8600?})
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.166.0/codegen/go/gen.go:3516 +0x1dc
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*pkgContext).collectNestedCollectionTypes(0x14016674120, 0x1402ff27fd0, {0x11f61ca50, 0x1401a6b8900})
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.166.0/codegen/go/gen.go:3433 +0x1b0
github.com/pulumi/pulumi/pkg/v3/codegen/go.generateTypes({0x11f59d400, 0x14017d885d0}, 0x14016674120, {0x14008cc1080, 0x8, 0x8}, {0x14001893b08, 0x23, 0x1?}, 0x0)
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.166.0/codegen/go/gen.go:5116 +0x23c
github.com/pulumi/pulumi/pkg/v3/codegen/go.GeneratePackage({0x119766ebc, 0x28}, 0x14001182380, 0x0)
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.166.0/codegen/go/gen.go:4984 +0x2e60
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.Language.emitSDK({_, _}, _, {{0x11f9ed500, 0x1400186a800}, {0x1194fffaa, 0x3}, {0x0, 0x0}, {0x1195160e0, ...}, ...}, ...)
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.108.0/pkg/tfgen/generate.go:138 +0x3ec
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).UnstableGenerateFromSchema(0x140020e0f08, 0x11f8b2810?)
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.108.0/pkg/tfgen/generate.go:1052 +0xa40
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).Generate(0x140020e0f08)
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.108.0/pkg/tfgen/generate.go:941 +0x50
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/pf/tfgen.MainWithMuxer.func1({{0x1194fffaa, 0x3}, {0x11bacfbd0, 0x11}, {0x16bb4ea96, 0x2}, {{0x11f9ed500, 0x1400186a800}, {0x1194fffaa, 0x3}, ...}, ...})
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.108.0/pkg/pf/tfgen/main.go:113 +0x198
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.func1.1(0x0?, {0x14005bcb3b0, 0x1, 0x0?})
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.108.0/pkg/tfgen/main.go:165 +0x43c
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.func1(0x140020e0008?, {0x14005bcb3b0?, 0x4?, 0x119501609?})
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.108.0/pkg/tfgen/main.go:179 +0xc0
github.com/spf13/cobra.(*Command).execute(0x140020e0008, {0x140002340d0, 0x3, 0x3})
        /Users/chall/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1015 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x140020e0008)
        /Users/chall/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/chall/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1071
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.MainWithCustomGenerate({_, _}, {_, _}, {{0x11f9ed500, 0x1400186a800}, {0x1194fffaa, 0x3}, {0x0, 0x0}, ...}, ...)
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.108.0/pkg/tfgen/main.go:61 +0x54
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/pf/tfgen.MainWithMuxer({_, _}, {{0x11f9ed500, 0x1400186a800}, {0x1194fffaa, 0x3}, {0x0, 0x0}, {0x1195160e0, 0x9}, ...})
        /Users/chall/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.108.0/pkg/pf/tfgen/main.go:90 +0x1f8
main.main()
        /Users/chall/work/pulumi-aws/v7-policydoc-schema/provider/cmd/pulumi-tfgen-aws/main.go:44 +0x100
make: *** [.make/generate_go] Error 2
```

### Example

```go
map[string]schema.ComplexTypeSpec{
	"aws:iam/PolicyStatement:PolicyStatement": {
		ObjectTypeSpec: schema.ObjectTypeSpec{
			Type:        "object",
			Description: "The Statement element is the main element for a policy. This element is required. It can include multiple elements (see the subsequent sections in this page). The Statement element contains an array of individual statements.",
			Properties: map[string]schema.PropertySpec{
				"Condition": {
					TypeSpec: schema.TypeSpec{
						Type: "object",
						AdditionalProperties: &schema.TypeSpec{
							Type: "object",
							AdditionalProperties: &schema.TypeSpec{
								OneOf: []schema.TypeSpec{
									{Type: "string"},
									{Type: "array", Items: &schema.TypeSpec{Type: "string"}},
								},
							},
						},
					},
					Description: "Specify the circumstances under which the policy grants permission.",
				},
      },
    },
  },
}

```

### Output of `pulumi about`

NA

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by t0yv0**
Union types are not fully supported by the Go SDK generator, but with this PR map[string]map[string]union generates as map[string]map[string]any, while incomplete it is an improvement over panicking globally with this type.

Fixes #19730

### CODE REVIEW

File: pkg/codegen/testing/test/sdk_driver.go [hunk 1]
```diff
@@ -483,6 +483,11 @@ var PulumiPulumiSDKTests = []*SDKTest{
 		Description: "Regress pulumi/pulumi#17219 affecting Python",
 		Skip:        allLanguages.Except("python/any"),
 	},
+	{
```
Comment (Frassle) [inline pkg/codegen/testing/test/sdk_driver.go]: We're trying to move away from these codegen tests. I feel like it would make sense to write a conformance test for this?

Comment (t0yv0) [reply pkg/codegen/testing/test/sdk_driver.go]: Sorry for the late response here, sure I can move this to the new conformance test matrix.

File: cmd/pulumi-test-language/README.md [hunk 2]
```diff
@@ -119,7 +119,7 @@ programs generated from that PCL. Presently they are laid out as follows:
   below) and `name` is a descriptive name for the test. The `l1-output-string`
   test, for example, has a level of 1 and the name `output-string`.
 
-* PCL programs are defined in `cmd/pulumi-test-language/testdata`. Each test has
+* PCL programs are defined in `cmd/pulumi-test-language/tests/testdata`. Each test has
```
Comment (t0yv0) [inline cmd/pulumi-test-language/README.md:122]: Drive-by doc fix, this is the new location I think.

File: cmd/pulumi-test-language/tests/testdata/l2-union/main.pp [hunk 3]
```diff
@@ -0,0 +1,13 @@
+resource "mapMapUnionExample" "union:index:Example" {
+  mapMapUnionProperty = {
```
Comment (Frassle) [inline cmd/pulumi-test-language/tests/testdata/l2-union/main.pp:10]: Should we test some other union types with this as well? Like basic number/string unions.

Comment (t0yv0) [reply cmd/pulumi-test-language/tests/testdata/l2-union/main.pp:10]: I can add a number/string union sure.

**Review by Frassle — APPROVED** [review]
