### PR TITLE
[sdk/providers] Fix update previews

### LINKED ISSUE #7521: `.metadata.name` properties are known and undefined instead of autonamed or unknown when provider kubeconfig is unknown
During a preview, the program below fails in the `ApplyT` callback at the end with `*v` failing because `v` is nil.  This is unexpected because either one of the following should be true:
1. If the `.Metadata.Name()` is known, `v` should have that value.
2. If the `.Metadata.Name()` is not known, the `ApplyT` callback should not be invoked at all, and should just propagate the unknown.

```go
package main

import (
	corev1 "github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/core/v1"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/meta/v1"

	"github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes"
	"github.com/pulumi/pulumi-random/sdk/v4/go/random"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		pet, err := random.NewRandomPet(ctx, "random-pet", &random.RandomPetArgs{Length: pulumi.Int(4)})
		if err != nil {
			return err
		}
		prov, err := kubernetes.NewProvider(ctx, "k8s-provider", &kubernetes.ProviderArgs{
			// If this `KubeConfig` is a known value like `pulumi.String("/Users/lukehoban/.kube/config")`
			// then this will not repro
			Kubeconfig: pet.ID().ApplyT(func(_ pulumi.ID) string { return "/Users/lukehoban/.kube/config" }).(pulumi.StringOutput),
		})

		if err != nil {
			return err
		}

		namespaceA, err := corev1.NewNamespace(ctx, "a", &corev1.NamespaceArgs{
                         // If the Metadata is removed, this will not repror.
			Metadata: &metav1.ObjectMetaArgs{
				Labels: pulumi.StringMap{
					"app": pulumi.String("foo"),
				},
			},
		}, pulumi.Provider(prov))
		if err != nil {
			return err
		}
		namespaceB, err := corev1.NewNamespace(ctx, "b", &corev1.NamespaceArgs{
			Metadata: &metav1.ObjectMetaArgs{
				Labels: pulumi.StringMap{
					"namespaceA": StringOutputFromStringPtrOutput(namespaceA.Metadata.Name()),
				},
			},
		}, pulumi.Provider(prov))
		if err != nil {
			return err
		}

		ctx.Export("namespaceBName", namespaceB.Metadata.Name())
		return nil
	})
}

func StringOutputFromStringPtrOutput(ptr pulumi.StringPtrOutput) pulumi.StringOutput {
	return ptr.ApplyT(func(v *string) string {
		// // If this guard is added, this will not repro.
		// if v == nil {
		// 	return ""
		// }
		return *v
	}).(pulumi.StringOutput)
}
```

This is ultimately happening because:
1. The provider that is being used is unknown during the preview (the issue wouldn't repro if the provider was known)
2. When the provider is unknown, we pass all inputs through as (known) outputs
3. That makes `Metadata` known because it as provided as an input (the issue wouldn't repro if `Metadata` was not populated)
4. When the provider is unknown, we also don't/can't call `Check`, which means the autonaming isn't applied to the resource, which would add the `.Metadata.Name` property.
5. That means that `.Metadata.Name()` returns an Output that is known but missing a value for `Name` even though there should and will actually be one.

Two additional notes:
a. This only happens during the preview, because everything becomes known during the update.
b. This can be worked around by returning a dummy value on `nil` Name in the `StringOutputFromStringPtrOutput` helper.  That isn't ideal, and may degrade the correctness of preview, but does avoid the failure.

We believe that we can make a change to (2) above to not pass through inputs as outputs on resources that have unknown providers.  See https://github.com/pulumi/pulumi/blob/master/sdk/go/common/resource/plugin/provider_plugin.go#L705-L712.  Changing this would mean that all outputs of resource whose providers are unknown would be treated as unknown.  This is more conservatively correct, though it may mean that some "useful" previews are no longer presented on such resources.

### PR DESCRIPTION
**Pull request by pgavlin**
Do not return the inputs as the state for update previews that use an
unconfigured provider. Returning the inputs as the state allows the
language SDKs to incorrectly treat unknown properties as known (because
we can't call `Update` on an unconfigured provider, we can't know which
properties are unknown). Users can re-enable the existing behavior by
setting the `PULUMI_LEGACY_PROVIDER_PREVIEW` environment variable to a
truthy value (e.g. `1`, `true`, etc.).

Most users will be unaffected by these changes. The most common programs
that may be affected are those that combine the creation of a managed
Kubernetes cluster with the deployment of applications to that cluster. These
programs generally need to configure a k8s provider instance by constructing
a kubeconfig from the output of the managed k8s cluster. Any changes to the
cluster that cause the kubeconfig to be unknown then cause the provider to
go unconfigured at runtime. Prior to these changes, resources managed by the
k8s provider would have some known outputs in this scenario, as the engine
would treat the resource's input values as its output values. After these changes,
the resource's outputs will be treated as unknown. The most frequent affect
that this has is that applies/stack outputs that depend on the outputs of
a k8s resource managed by a provider with an unknown kubeconfig will not
run/be displayed as `output`s during previews, respectively.

We might be able to improve on this by taking advantage of schema
information and filling in unknown values for properties that do not
exist in the inputs.

Fixes #7521.

### CODE REVIEW

**Comment by pgavlin** [comment]
Note that this PR is essentially a work-in-progress: we'd like to take some additional time to trial the experience here and make sure that previews aren't too badly affected by this change.

File: sdk/go/common/resource/plugin/provider_plugin.go [hunk 1]
```diff
@@ -917,12 +917,23 @@ func (p *provider) Update(urn resource.URN, id resource.ID,
...
+	if preview {
+		// TODO: it would be great to swap the order of these if statements. This would prevent a behavioral change for
+		// providers that do not support provider previews, which will always return the inputs as state regardless of
+		// whether or not the config is known. Unfortunately, we can't, since the `supportsPreview` bit depends on the
+		// result of `Configure`, which we won't call if the `cfgknown` is false. It may be worth fixing this catch-22
+		// by extending the provider gRPC interface with a `SupportsFeature` API similar to the language monitor.
+		if !p.cfgknown {
+			return resource.PropertyMap{}, resource.StatusOK, nil
+		}
+		if !p.supportsPreview {
```
Comment (lblackstone) [inline sdk/go/common/resource/plugin/provider_plugin.go:934]: Should we also handle `disableProviderPreview`?

**Review by lblackstone — COMMENTED** [review]
I think the approach makes sense overall

File: sdk/go/common/resource/plugin/provider_plugin.go [hunk 2]
```diff
@@ -917,12 +917,23 @@ func (p *provider) Update(urn resource.URN, id resource.ID,
 	}
 
 	// If this is a preview and the plugin does not support provider previews, or if the configuration for the provider
-	// is not fully known, hand back the inputs as the state.
+	// is not fully known, hand back an empty property map. This will force the language SDK will to treat all properties
```
Comment (justinvp) [inline sdk/go/common/resource/plugin/provider_plugin.go:920]: Nit:

```suggestion
	// is not fully known, hand back an empty property map. This will force the language SDK to treat all properties
```

File: sdk/go/common/resource/plugin/provider_plugin.go (hunk 1 above)
Comment (pgavlin) [reply sdk/go/common/resource/plugin/provider_plugin.go:934]: Yes, we should--good catch.

**Comment by lukehoban** [comment]
A couple notes from an offline conversation on this:
1. Let's have an env var that allows opting into the previous experience, in case this has any unforeseen negative impact on outlier scenarios.
2. Let's validate the before/after experience for 2-3 common scenarios that are impacted by this, both positively and potentially negatively.  Would be great to have these real-world before/after examples in the PR description so we can review and agree that on balance this is something that is not going to cause problems for any common scenarios.

File: CHANGELOG_PENDING.md [hunk 3]
```diff
@@ -1,7 +1,26 @@
 ### Improvements
 
+- [cli] - Fix the preview experience for unconfigured providers. Rather than returning the
+  inputs of a resource as its outputs, the engine will treat all outputs as unknown. Most
```
Comment (lukehoban) [inline CHANGELOG_PENDING.md:4]: It feels like theres a qualifier missing on this sentence?  Something like this?

```suggestion
  inputs of a resource managed by an unconfigured provider as its outputs, the engine will treat all outputs as unknown. Most
```

File: sdk/go.sum [hunk 4]
```diff
@@ -343,6 +423,7 @@ gopkg.in/yaml.v2 v2.2.8/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
 gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c h1:dUUwHk2QECo/6vqA44rthZ8ie2QXMNeKRTHCNY2nXvo=
 gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c/go.mod h1:K4uyk7z7BCEPqu6E+C64Yfv1cQ7kz7rIZviUmN+EgEM=
 honnef.co/go/tools v0.0.0-20190102054323-c2f93a96b099/go.mod h1:rf3lG4BRIbNafJWhAfAdb/ePZxsR/4RtNHQocxwk9r4=
+honnef.co/go/tools v0.0.0-20190523083050-ea95bdfd59fc h1:/hemPrYIhOhy8zYrNj+069zDB68us2sMGsfkFJO0iZs=
```
Comment (lukehoban) [inline sdk/go.sum:426]: Out of curiosity - what caused all these go.sum changes?

**Review by lukehoban — APPROVED** [review]
LGTM

> Let's validate the before/after experience for 2-3 common scenarios that are impacted by this, both positively and potentially negatively. Would be great to have these real-world before/after examples in the PR description so we can review and agree that on balance this is something that is not going to cause problems for any common scenarios.

I'd still love to see this in the PR description - a before/after of the most common impacted scenario.

File: CHANGELOG_PENDING.md (hunk 3 above)
Comment (pgavlin) [reply CHANGELOG_PENDING.md:4]: Sure--I thought that the prior sentence would imply this.

File: sdk/go.sum (hunk 4 above)
Comment (pgavlin) [reply sdk/go.sum:426]: No clue, to be honest. These popped up after running `go mod tidy`.

**Comment by pgavlin** [comment]
> I'd still love to see this in the PR description - a before/after of the most common impacted scenario.

The general scenario is in the CHANGELOG. I'll add it to the description as well.
