### PR TITLE
fix(cli/stack output): Don't escape HTML characters

### LINKED ISSUE #10561: pulumi stack output mangles strings inside objects (chars are escaped)
### What happened?

A co-worker had issues fetching a string from `pulumi stack output` because pulumi mangles the string.
Pulumi prints '>' as "\u003e".

### Steps to reproduce

```bash
docker run --rm -it --entrypoint bash pulumi/pulumi:3.38.0

mkdir test && cd test
pulumi login -l
export PULUMI_CONFIG_PASSPHRASE=toto
pulumi new typescript -n test -d yolo -s test
printf 'import * as pulumi from "@pulumi/pulumi";const s="><";const o={s: s}; console.log(o); export const es=s; export const eo=o\n' > index.ts
pulumi up --yes && pulumi stack output
```

### Expected Behavior

```
Current stack outputs (2):
    OUTPUT  VALUE
    eo      {"s":"><"}
    es      ><
```

### Actual Behavior

```
Current stack outputs (2):
    OUTPUT  VALUE
    eo      {"s":"\u003e\u003c"}
    es      ><
```
Note: this doesn't seem to be a TypeScript issue as the `console.log` prints `{ s: '><' }`.

### Output of `pulumi about`

I'm using the container, but anyways:
```
root@e170252144d4:/test# pulumi about
CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       debian
Version  11.4
Arch     x86_64

This project is written in nodejs: executable='/usr/bin/node' version='v16.17.0'

Current Stack: test

TYPE                 URN
pulumi:pulumi:Stack  urn:pulumi:test::test::pulumi:pulumi:Stack::test-test


Found no pending operations associated with test

Backend
Name           e170252144d4
URL            file://~
User           root
Organizations

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.38.0
@types/node     14.18.26

Pulumi locates its logs in /tmp by default
```

### Additional context

This issue is circumvented by  using `pulumi stack output -j` (json output). The output becomes:
```json
{
  "eo": {
    "s": "><"
  },
  "es": "><"
}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by abhinav**
For the default `pulumi stack output` (writing to the console),
don't escape HTML characters inside JSON strings.

The only way to control this in Go is with `json.Encoder`.
However, that unconditionally places a newline at the end,
so we have to strip that for our use case.

Testing:
TestStringifyOutput was turned into a table test.
That's in an independent commit without any other changes.

Resolves #10561

### CODE REVIEW

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* master
  * **PR #13257** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/13257" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi/13257?utm_source=stack-comment).

File: pkg/cmd/pulumi/stack.go [hunk 1]
```diff
@@ -233,11 +234,21 @@ func stringifyOutput(v interface{}) string {
 		return s
 	}
 
-	b, err := json.Marshal(v)
-	if err != nil {
+	// json.Marshal escapes HTML characters, which we don't want,
```
Comment (Frassle) [inline pkg/cmd/pulumi/stack.go:237]: > The only way to control this in Go is with json.Encoder.
However, that unconditionally places a newline at the end,
so we have to strip that for our use case.

I really hate this, I've ran into this wall multiple times and it's just infuriating that they don't expose an option here 😭 

There's probably some other places in the codebase doing this trick (or a poor attempt at it). Probably worth scanning and seeing if it makes sense to make a util helper function to do this `json.MarshalUnescaped`?

Comment (abhinav) [reply pkg/cmd/pulumi/stack.go:237]: I considered that based on your comment in #10561, but the only place that this actually matters is at the presentation layers: where the JSON is surfaced to the user in a view somewhere.
For machines parsing the JSON, the escaped HTML is still a valid JSON string representing the same information, and the extraneous newline is not a problem.

Comment (Frassle) [reply pkg/cmd/pulumi/stack.go:237]: > but the only place that this actually matters is at the presentation layers

Mostly, but there's a few places where we need to do this in the presentation layers. 

There is in fact already a helper function `makeJSONString` (in pkg/cmd/pulumi/util.go) that's basically doing the same as here except without the newline handling. 

Should probably just change this to use that, and fix that to handle the newline.

Comment (abhinav) [reply pkg/cmd/pulumi/stack.go:237]: Alright, I'll try to merge this into makeJSONString.

Comment (abhinav) [reply pkg/cmd/pulumi/stack.go]: @Frassle I merged them, but makeJSONString was previously only for indented output. 
In indented output form, it should not strip the trailing newline—because the output is likely going to be printed on the console (e.g. it's used by `stack output --json`).

So I've added a multiline flag that decides whether to indent or not, and also whether to strip the trailing newline.
EscapeHTML is always disabled.

**Review by Frassle — APPROVED** [review]

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
bors retry
