### PR TITLE
Fix issues in the filestate backend

### LINKED ISSUE #2714: Intermittent "NoSuchKey: The specified key does not exist" errors when using S3 backend
I have been following the cloud backend change

https://github.com/pulumi/pulumi/pull/2455

When trying to run
`pulumi login s3://pulumi-state-files` and then `pulumi up`

I get the following error 
`error: failed to load checkpoint: blob (code=NotFound): NoSuchKey: The specified key does not exist.`
I can navigate and interrogate that specific S3 bucket via the AWS CLI and have setup the appropriate AWS_PROFILE environment.

Not quite sure what I am doing incorrectly, I have followed all the documentation and issue steps I have been able to find.

### PR DESCRIPTION
**Pull request by ellismg**
Two related commits, the first was an outcome of me looking into the intermittent issues we've seen with state storage on S3 and the following was from me following up based on a class of issues I discovered.

Here's the messages of each:

---

### Do not attempt to load checkpoint before saving a snapshot

For historical reasons, we used to need to require to load an existing
checkpoint to copy some data from it into the snapshot when saving a
new snapshot. The need for this was removed as part of the general
work in #2678, but we continued to load the checkpoint and then just
disregard the data that was returned (unless there was an error and
that error was not FileNotFound, in which case we would fail).

Our logic for checking if something was FileNotFound was correct when
we wrote it, but when we adopted go-cloud in order to have our
filestate backend also write to blob storage backends like S3, we
forgot that we had checks like `os.IsNotExists()` floating around
which were now incorrect. That meant if the file did not exist for
some reason, instead of going along as planned, we'd error out now
with an error saying something wasn't found.

When we write a checkpoint, we first "backed up" the initial version
by renaming it to include a `.bak` suffix, then we write the new file
in place. However, this can run afoul of eventual consistency models
like S3, since there will be a period of time in which a caller may
observe that the object is missing, even after a new version is
written (based on my understanding of [S3's consistency
model](https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel))

Since we no longer need to actually copy any information from the
previous checkpoint, we can simply remove the call entirely to load
it.

As a follow up, we need to audit places inside the filebased backend
that assume `os.*` functions are going to do what we want them to do,
since in general they will not.

Fixes #2714

---

### Do not use `os` package in filestate backend

Since the filestate backend is now written using the go-cloud blob
abstraction, places where we were using functions from the `os`
package were very unlikely to be correct.

This change removes their uses in favor of APIs provided by
go-cloud (which sometimes requires more work than before).

### CODE REVIEW

File: pkg/backend/filestate/state.go [hunk 1]
```diff
@@ -302,6 +303,44 @@ func (b *localBackend) getHistory(name tokens.QName) ([]backend.UpdateInfo, erro
...
+	for _, file := range allFiles {
+		fileName := objectName(file)
+		oldBlob := path.Join(oldHistory, fileName)
+
+		// The filename format is <stack-name>-<timestamp>.[checkpoint|history].json, we need to change
+		// the stack name part but retain the other parts.
+		newFileName := string(newName) + fileName[strings.LastIndex(fileName, "-"):]
+		newBlob := path.Join(newHistory, newFileName)
+
+		fmt.Printf("copy:%s -> %s\n", oldBlob, newBlob)
```
Comment (pgavlin) [inline pkg/backend/filestate/state.go]: Probably want to remove this, yes?

Comment (ellismg) [reply pkg/backend/filestate/state.go]: Indeed!

**Comment by ellismg** [comment]
> Not to block landing this - but possibly as a follow-up - is there any increased testing we can add to "stress-test" this a bit more to ensure that this remains stable?

I think we can use the dynamic provider to generate an update that will create a lot of resources (and hence have a large number of checkpoint writes) we could just run that update against the s3 backend and have better confidence here.

**Comment by Saingsophea** [comment]
> Two related commits, the first was an outcome of me looking into the intermittent issues we've seen with state storage on S3 and the following was from me following up based on a class of issues I discovered.
> 
> Here's the messages of each:
> 
> ---
> 
> ### Do not attempt to load checkpoint before saving a snapshot
> 
> For historical reasons, we used to need to require to load an existing
> checkpoint to copy some data from it into the snapshot when saving a
> new snapshot. The need for this was removed as part of the general
> work in #2678, but we continued to load the checkpoint and then just
> disregard the data that was returned (unless there was an error and
> that error was not FileNotFound, in which case we would fail).
> 
> Our logic for checking if something was FileNotFound was correct when
> we wrote it, but when we adopted go-cloud in order to have our
> filestate backend also write to blob storage backends like S3, we
> forgot that we had checks like `os.IsNotExists()` floating around
> which were now incorrect. That meant if the file did not exist for
> some reason, instead of going along as planned, we'd error out now
> with an error saying something wasn't found.
> 
> When we write a checkpoint, we first "backed up" the initial version
> by renaming it to include a `.bak` suffix, then we write the new file
> in place. However, this can run afoul of eventual consistency models
> like S3, since there will be a period of time in which a caller may
> observe that the object is missing, even after a new version is
> written (based on my understanding of [S3's consistency
> model](https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel))
> 
> Since we no longer need to actually copy any information from the
> previous checkpoint, we can simply remove the call entirely to load
> it.
> 
> As a follow up, we need to audit places inside the filebased backend
> that assume `os.*` functions are going to do what we want them to do,
> since in general they will not.
> 
> Fixes #2714
> 
> ---
> 
> ### Do not use `os` package in filestate backend
> 
> Since the filestate backend is now written using the go-cloud blob
> abstraction, places where we were using functions from the `os`
> package were very unlikely to be correct.
> 
> This change removes their uses in favor of APIs provided by
> go-cloud (which sometimes requires more work than before).

File: pkg/backend/filestate/state.go (hunk 1 above)
Comment (Saingsophea) [reply pkg/backend/filestate/state.go]: - [ ]
