### PR TITLE
sdk/go: Don't use Provider for type if package doesn't match

### LINKED ISSUE #12430: Passing a provider for an MLC's children via `pulumi.Provider` results in error
The following Go program previews as expected using v3.56.0 of the Go SDK:

main.go:

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws"
	"github.com/pulumi/pulumi-awsx/sdk/go/awsx/ec2"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		provider, err := aws.NewProvider(ctx, "myprovider", nil)
		if err != nil {
			return err
		}

		_, err = ec2.NewVpc(ctx, "myvpc", nil, pulumi.Provider(provider))
		if err != nil {
			return err
		}

		return nil
	})
}
```

go.mod:

```
module myproject

go 1.18

require (
	github.com/pulumi/pulumi-aws/sdk/v5 v5.31.0
	github.com/pulumi/pulumi-awsx/sdk v1.0.2
	github.com/pulumi/pulumi/sdk/v3 v3.56.0
)
```

Output:

```
$ pulumi preview
Previewing update (dev)

     Type                                          Name             Plan
 +   pulumi:pulumi:Stack                           goproviderr-dev  create
 +   ├─ pulumi:providers:aws                       myprovider       create
 +   └─ awsx:ec2:Vpc                               myvpc            create
 +      └─ aws:ec2:Vpc                             myvpc            create
 +         ├─ aws:ec2:InternetGateway              myvpc            create
 +         ├─ aws:ec2:Subnet                       myvpc-public-2   create
 +         │  ├─ aws:ec2:RouteTable                myvpc-public-2   create
 +         │  │  ├─ aws:ec2:Route                  myvpc-public-2   create
 +         │  │  └─ aws:ec2:RouteTableAssociation  myvpc-public-2   create
 +         │  ├─ aws:ec2:Eip                       myvpc-2          create
 +         │  └─ aws:ec2:NatGateway                myvpc-2          create
 +         ├─ aws:ec2:Subnet                       myvpc-public-1   create
 +         │  ├─ aws:ec2:RouteTable                myvpc-public-1   create
 +         │  │  ├─ aws:ec2:RouteTableAssociation  myvpc-public-1   create
 +         │  │  └─ aws:ec2:Route                  myvpc-public-1   create
 +         │  ├─ aws:ec2:Eip                       myvpc-1          create
 +         │  └─ aws:ec2:NatGateway                myvpc-1          create
 +         ├─ aws:ec2:Subnet                       myvpc-private-1  create
 +         │  └─ aws:ec2:RouteTable                myvpc-private-1  create
 +         │     ├─ aws:ec2:RouteTableAssociation  myvpc-private-1  create
 +         │     └─ aws:ec2:Route                  myvpc-private-1  create
 +         ├─ aws:ec2:Subnet                       myvpc-public-3   create
 +         │  ├─ aws:ec2:RouteTable                myvpc-public-3   create
 +         │  │  ├─ aws:ec2:RouteTableAssociation  myvpc-public-3   create
 +         │  │  └─ aws:ec2:Route                  myvpc-public-3   create
 +         │  ├─ aws:ec2:Eip                       myvpc-3          create
 +         │  └─ aws:ec2:NatGateway                myvpc-3          create
 +         ├─ aws:ec2:Subnet                       myvpc-private-3  create
 +         │  └─ aws:ec2:RouteTable                myvpc-private-3  create
 +         │     ├─ aws:ec2:RouteTableAssociation  myvpc-private-3  create
 +         │     └─ aws:ec2:Route                  myvpc-private-3  create
 +         └─ aws:ec2:Subnet                       myvpc-private-2  create
 +            └─ aws:ec2:RouteTable                myvpc-private-2  create
 +               ├─ aws:ec2:RouteTableAssociation  myvpc-private-2  create
 +               └─ aws:ec2:Route                  myvpc-private-2  create


Resources:
    + 35 to create
```

However, upgrading the pulumi SDK to v3.57.1 (`github.com/pulumi/pulumi/sdk/v3 v3.57.1`) results in the following error during preview:

```
$ pulumi preview
Previewing update (dev)

     Type                     Name             Plan       Info
 +   pulumi:pulumi:Stack      goproviderr-dev  create     1 error
 +   └─ pulumi:providers:aws  myprovider       create


Diagnostics:
  pulumi:pulumi:Stack (goproviderr-dev):
    error: an unhandled error occurred: program failed:
    waiting for RPCs: rpc error: code = Unknown desc = plugins that can construct components must support secrets
```

The error message is deceiving... it's coming from:

https://github.com/pulumi/pulumi/blob/477e0c97660bdbeb28a142057899792d52e63a0b/sdk/go/common/resource/plugin/provider_plugin.go#L1250

We've seen this before in https://github.com/pulumi/pulumi/issues/11316. When passing an AWS provider to an MLC, the engine is trying to use that provider to construct the MLC. But the AWS provider doesn't have an implementation of Construct for the MLC, and it's failing earlier when trying to call Construct on the AWS provider because the AWS provider currently says it doesn't support secrets.

## Workaround

A workaround is to pass the provider via `pulumi.Providers` (plural) rather than `pulumi.Provider` (singular). The plural variant is intended for passing providers for a component's children.

### PR DESCRIPTION
**Pull request by abhinav**
In #12296, we started correctly interpreting the Provider argument
per other SDKs. but this introduced a regression:
the Provider field is now set for resources with mismatched types.

This results in a scenario where a provider foo for package X
is passed to a resource bar with package Y,
with the intent of plumbing it to bar's descendants,
but bar attempts to incorrectly use the provider directly.

    foo := NewXProvider()
    bar := NewYThing("bar", Provider(foo))
    // ...
    baz := NewXThing("baz", Parent(bar)) // should use foo

This worked previously, but with #12296, this fails
because NewYThing attempts to use Provider foo directly.

To fix this, we need to prevent NewYThing from using a provider
that does not match the package that it belongs to.
We had to make a similar change to the Python SDK in #12292.

https://github.com/pulumi/pulumi/blob/477e0c97660bdbeb28a142057899792d52e63a0b/sdk/python/lib/pulumi/resource.py#L925-L927

The regression test is specific to remote component resources
per #12430, but the issue would be caused even for normal component
resources before this.

Resolves #12430

### CODE REVIEW

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12433** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/12433" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi/12433?utm_source=stack-comment).

File: sdk/go/pulumi/resource_test.go [hunk 1]
```diff
@@ -784,6 +784,63 @@ func TestComponentResourcePropagatesProvider(t *testing.T) {
...
+				//
+				// However, only the custom resource should have the provider set.
+				switch args.RegisterRPC.Type {
+				case "awsx:ec2:Vpc":
+					assert.Empty(t, args.Provider,
+						"provider should not be set on remote component resource")
+
+				case "aws:ec2/vpc:Vpc":
+					assert.NotEmpty(t, args.Provider,
+						"provider should not be set on remote component resource")
```
Comment (justinvp) [inline sdk/go/pulumi/resource_test.go:831]: Nit: Should it be:

```suggestion
						"provider should be set on custom resource")
```

?

**Review by justinvp — APPROVED** [review]
LGTM

File: sdk/go/pulumi/resource_test.go (hunk 1 above)
Comment (abhinav) [reply sdk/go/pulumi/resource_test.go:831]: Derp, yes. Bad copypasta.

**Comment by abhinav** [comment]
NodeJS failures above fixed in #12435

**Comment by abhinav** [comment]
bors merge

**Comment by Frassle** [comment]
bors cancel

**Comment by Frassle** [comment]
bors merge

**Comment by justinvp** [comment]
bors retry

**Comment by justinvp** [comment]
bors retry

**Comment by Frassle** [comment]
bors merge
