### PR TITLE
[dotnet/program-gen] Fixes code generation of ForExpressions

### LINKED ISSUE #13613: [pcl/dotnet] Support generating ForExpressions in program-gen
### What happened?

dotnet/csharp does not support generatingForExpressions, right now it emits "Not yet implemented" but they are required when converting a dynamic list of elements which is very common when converting from terraform

### Expected Behavior

The following PCL code to convert to csharp
```tf
data = [for entry in entries([1,2,3]) : {
    usingKey: entry.key
    usingValue: entry.value
}]
```

### Steps to reproduce

Use `pulumi convert --from pcl --language csharp --out cs` against the program above

### Output of `pulumi about`

CLI
Version 3.60.1
Go Version go1.20.2
Go Compiler gc

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

When using ForExpressions from PCL, the resulting expression is either a list or a dictionary. Right now the generate code only emits `IEnumerable` and only works for input lists. This PR updates dotnet program-gen to fully support `ForExpressions` when creating a list, in which case the previous expression would use a suffix `.ToList()`. When creating maps/dictionaries, the generated code will use `ToDictionary(item => <keyExpr>, item => <valueExpr>)` 

<details>
<summary>Example PCL</summary>

```
config egress "list(object({FromPort=int, ToPort=int}))" {

}

config tags "map(string)" {
    default = {}
}

defaultVpc = invoke("aws:ec2:getVpc", {
	default = true
})

// Create a security group that permits HTTP ingress and unrestricted egress.
resource webSecurityGroup "aws:ec2:SecurityGroup" {
	vpcId = defaultVpc.id
	egress = [for entry in entries(egress): {
		protocol = "-1"
		fromPort = entry.value.FromPort
		toPort = entry.value.ToPort
		cidrBlocks = ["0.0.0.0/0"]
	}]

	tags = { for k, v in tags: k => v }
}
```

</details>

<details>
<summary>Generated C# which compiles</summary>

```csharp
using System.Collections.Generic;
using System.Linq;
using Pulumi;
using Aws = Pulumi.Aws;

return await Deployment.RunAsync(() => 
{
    var config = new Config();
    var egress = config.RequireObject<Egress[]>("egress");
    var tags = config.GetObject<Dictionary<string, string>>("tags") ?? null;
    var defaultVpc = Aws.Ec2.GetVpc.Invoke(new()
    {
        Default = true,
    });

    // Create a security group that permits HTTP ingress and unrestricted egress.
    var webSecurityGroup = new Aws.Ec2.SecurityGroup("webSecurityGroup", new()
    {
        VpcId = defaultVpc.Apply(getVpcResult => getVpcResult.Id),
        Egress = egress.Select((v, k) => new { Key = k, Value = v }).Select(entry => 
        {
            return new Aws.Ec2.Inputs.SecurityGroupEgressArgs
            {
                Protocol = "-1",
                FromPort = entry.Value.FromPort,
                ToPort = entry.Value.ToPort,
                CidrBlocks = new[]
                {
                    "0.0.0.0/0",
                },
            };
        }).ToList(),
        Tags = tags.Select(pair => new { pair.Key, pair.Value }).ToDictionary(item => {
            var k = item.Key;
            return k;
        }, item => {
            var v = item.Value;
            return v;
        }),
    });

});

public class Egress
{
    public int FromPort { get; set; }
    public int ToPort { get; set; }
}


```

</details>

Fixes #13613

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/codegen/testing/test/testdata/entries-function-pp/dotnet/entries-function.cs [hunk 1]
```diff
@@ -11,12 +11,12 @@
         3,
     }.Select((v, k) => new { Key = k, Value = v }).Select(entry => 
     {
-        return new Dictionary<string, object?>
```
Comment (Zaid-Ajaj) [inline pkg/codegen/testing/test/testdata/entries-function-pp/dotnet/entries-function.cs:14]: The code which resolves this type name was broken. Need to revisit the creation of untyped maps in dotnet

Comment (Zaid-Ajaj) [reply pkg/codegen/testing/test/testdata/entries-function-pp/dotnet/entries-function.cs:14]: Related https://github.com/pulumi/pulumi/issues/13623

**Review by Frassle — APPROVED** [review]
