### PR TITLE
sdk/go: Fix panic from uninitialized parent resources

### LINKED ISSUE #12138: [sdk/go] Panic when uninitialized parent is used along with aliases
This code panics:

```go
package main

import (
	"fmt"

	"github.com/pulumi/pulumi-random/sdk/v4/go/random"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SQL struct {
	pulumi.ResourceState

	AdminPwd    pulumi.StringInput
	NewAdminPwd pulumi.StringInput
}

func NewSQL(ctx *pulumi.Context, name string, opts ...pulumi.ResourceOption) (*SQL, error) {
	myComponent := &SQL{}
//	err := ctx.RegisterComponentResource("pkg:index:MyComponent", name, myComponent, opts...)
//	if err != nil {
//		return nil, err
//	}

	return myComponent, nil
}

func GetPostgresAlias(createAlias bool, oldAlias string) []pulumi.Alias {
	if !createAlias {
		return []pulumi.Alias{}
	}
	return []pulumi.Alias{{URN: nil}}
}

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		db, err := NewSQL(ctx, "db")
		if err != nil {
			return err
		}

		adminPassword, err := random.NewRandomPassword(
			ctx,
			fmt.Sprintf("db-admin-password-%s-%s", "test", "test"),
			&random.RandomPasswordArgs{
				Length:  pulumi.Int(64),
				Lower:   pulumi.Bool(true),
				Number:  pulumi.Bool(true),
				Upper:   pulumi.Bool(true),
				Special: pulumi.Bool(true),
			},
			pulumi.Parent(db),
			pulumi.Aliases(append(
				GetPostgresAlias(true, "db-admin-password12"),
				GetPostgresAlias(true, "db-admin-password")...,
			)),
		)
		if err != nil {
			return err
		}
		ctx.Export("adminPassword", adminPassword.Result)
		return nil
	})

}
```

with:

```
  pulumi:pulumi:Stack (awssftest-dev):
    panic: applier's second input parameter must be assignable from interface {}, got pulumi.URN
    applier defined at /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/go/pulumi/types_builtins.go:4818
    goroutine 1 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*OutputState).ApplyTWithContext(0x0, {0x1abe678, 0xc00012c008}, {0x182a0a0?, 0x19d0958?})
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/go/pulumi/types.go:560 +0xa5
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.URNOutput.ToStringOutputWithContext({0x198cbef?}, {0x1abe678?, 0xc00012c008?})
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/go/pulumi/types_builtins.go:4818 +0x31
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.URNOutput.ToStringOutput(...)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/go/pulumi/types_builtins.go:4814
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.Alias.collapseToURN({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/go/pulumi/alias.go:80 +0x191
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).collapseAliases(0x4?, {0xc000170100, 0x2, 0xc0001480c0?}, {0x198cbef, 0x2a}, {0xc0001480c0, 0x1b}, {0x1ac5a68, 0xc00016c000})
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/go/pulumi/context.go:1028 +0x1a5
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).registerResource(0xc0000a4160, {0x198cbef, 0x2a}, {0xc0001480c0, 0x1b}, {0x1ab5ba0?, 0xc000164580}, {0x1ac55a0, 0xc0003fc120}, 0x0, ...)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/go/pulumi/context.go:805 +0x505
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).RegisterResource(...)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/go/pulumi/context.go:714
    github.com/pulumi/pulumi-random/sdk/v4/go/random.NewRandomPassword(0x191d280?, {0xc0001480c0?, 0x1b?}, 0xc000164580?, {0xc000266080?, 0x2?, 0x2?})
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi-random/sdk/v4@v4.10.0/go/random/randomPassword.go:122 +0x20b
    main.main.func1(0xc0000a4160)
        /Users/lukehoban/dd/pulumidemos/awssftest/main.go:41 +0x2dd
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunWithContext(0xc0000a4160, 0x19d1f90)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/go/pulumi/run.go:121 +0x1aa
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.runErrInner(0xc0000061a0?, 0x19d08e0, {0x0, 0x0, 0x1007c19?})
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/go/pulumi/run.go:97 +0x317
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.Run(0x0?, {0x0?, 0x17f5620?, 0xc0000061a0?})
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/go/pulumi/run.go:49 +0x2e
    main.main()
        /Users/lukehoban/dd/pulumidemos/awssftest/main.go:35 +0x27
```

Uncommenting the following causes it to work:

```go
// err := ctx.RegisterComponentResource("pkg:index:MyComponent", name, myComponent, opts...)
// if err != nil {
//	return nil, err
// }
```
 
This appears to be because the parent's embedded ResourceState has not been initialized, and therefore has an invalid value for its internal `URN`.  

This was always invalid state for a parent resource, but it appears it didn't trigger this panic until the changes in https://github.com/pulumi/pulumi/commit/e38876f7affe053815e691ab52e76be415b254cf.  The upgrade that the user is doing in https://github.com/pulumi/pulumi-random/issues/219 was from a version of pulumi before this change to after it, which caused the panic to surface.

Ultimately there are two problems:
1. The user code needs to use a valid parent resource (or no parent) - we validated that the user who hit this appears to be able to fix this by not parenting the resource (due to the existing aliases).
2. The Pulumi Go SDK should "fail better" here - either fail early if a non-initialized resorucestate is used as a parent, or ensure that things that read URN don't fail if it is uninitialized (and return a useful default result).

This issue is tracking (2).

### PR DESCRIPTION
**Pull request by abhinav**
# Description

The Go SDK panics if RegisterResource is called with a parent resource
that is uninitialized
(hasn't had its RegisterResource or RegisterComponentResource call yet).

The panic is during alias collapsing:
the system fails to read the unintialized parent resource's URN
from a zero-valued URNOutput.

Guard against this panic by verifying that the value passed to `Parent`
has been initialized.
We do this by checking the name of the resource--names are not allowed
to be empty when a resource is registered.

Resolves #12138

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

### CODE REVIEW

**Comment by abhinav** [comment]
MLC's might not have a name yet.
Uninitialized detection should use URNs instead.
Fixing.

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12303** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/12303" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi/12303?utm_source=stack-comment).

File: sdk/go/pulumi/context.go [hunk 1]
```diff
@@ -806,6 +806,20 @@ func (ctx *Context) registerResource(
...
 		options.Parent = ctx.stack
+	} else {
+		// Guard against uninitialized parent resources to prevent
+		// panics from invalid state further down the line.
+		// Uninitialized parent resources won't have a URN.
+		if parent.URN().getState() == nil {
+			var msg string
+			if _, parentIsCustom := parent.(CustomResource); !parentIsCustom {
+				msg = "parent component resource %T has not been registered: " +
+					"did you mean to call RegisterComponentResource?"
```
Comment (Frassle) [inline sdk/go/pulumi/context.go:817]: "did you mean to call" sounds odd, they _must_ have meant to do that, there's nothing else sensible to do with a component resource.

File: sdk/go/pulumi/context.go [hunk 2]
```diff
@@ -806,6 +806,20 @@ func (ctx *Context) registerResource(
...
+			} else {
+				msg = "parent resource %T has not been registered"
```
Comment (Frassle) [inline sdk/go/pulumi/context.go:819]: This should probably match the phrasing above, and say that RegisterResource should have been called on the parent.

Comment (abhinav) [reply sdk/go/pulumi/context.go:819]: I considered that, and I'm down to add that.
The reason I didn't at the time was that custom resources typically have a NewMyResource constructor in our generated SDKs, so end users won't _normally_ call RegisterResource directly.
If it's fine to leak that little detail, I can fix that.

File: sdk/go/pulumi/context.go (hunk 1 above)
Comment (abhinav) [reply sdk/go/pulumi/context.go:817]: Fair. How about "did you forget to call"?

File: sdk/go/pulumi/context.go (hunk 2 above)
Comment (Frassle) [reply sdk/go/pulumi/context.go:819]: hmm maybe that they didn't call the "NewX" constructor method then?

File: sdk/go/pulumi/context.go (hunk 1 above)
Comment (Frassle) [reply sdk/go/pulumi/context.go:817]: Again I don't think there's any "did" about it, @susanev probably has words to say on phrasing error messages but I think this should probably be something like "parent component resource %T has not been registered: RegisterComponentResource should have been called"

**Comment by lukehoban** [comment]
This is technically a breaking change - right?

It’s very possible there are lots of cases where parents are being passed today that are not initialized. Doing so was not previously something that would trigger an error (until recently, and only if aliases were used, where it started panicking). 

Are we worried that this will break users whose code is (inadvertently) working “correctly” today?

Should we ship this as a warning before making it an error?

**Comment by abhinav** [comment]
I'm unsure whether we should consider this a breaking change.
Yes, technically there could be code that was passing invalid parent resources as arguments, that was passing before and will fail with this change.
However, that was also technically a bug in user code that could explode elsewhere besides aliases, or worse, persist invalid state down into the system.

That said, I agree that we can err on the side of extreme caution here.
I'll make this log a message and nil out the invalid parent resource instead.
That way, aliases and possibly other options won't accidentally attempt to use the bad parent.

File: sdk/go/pulumi/context.go (hunk 1 above)
Comment (abhinav) [reply sdk/go/pulumi/context.go:817]: I think we can drop the two sentence problem completely with:

    parent component resource %T has not been registered via RegisterComponentResource

Thanks to @ericrudder for the suggestion

File: sdk/go/pulumi/context.go (hunk 2 above)
Comment (abhinav) [reply sdk/go/pulumi/context.go:819]: AFAIK, the SDK doesn't know that NewX exists. I'm going to stick with RegisterResource for now, since this variant of the error is less likely to happen (passing in a zero value `s3.Bucket` instead of one returned by `s3.NewBucket`), so the little leak that all resource instantiations go through RegisterResource isn't too bad.
(If there's a type-constructor mapping, though, we can definitely tell users that they forgot to call NewFoo.)

**Review by Frassle — APPROVED** [review]

**Comment by abhinav** [comment]
bors merge
