### PR TITLE
[`pulumi state edit`] handle multi-part EDITOR variables (i.e. `emacs -nw`)

### LINKED ISSUE #13850: `pulumi state edit` doesn't work with multi-part
### What happened?

`pulumi state edit` attempts to run `$EDITOR` directly instead of running it through the shell.

### Expected Behavior

`$EDITOR` works correctly, just like other commands. For example `git commit --allow-empty
` works correctly for me, opening emacs.

### Steps to reproduce

Have `$EDITOR` set to a multi-part command:

```sh
𝛌 pulumi state edit
Failed to exec EDITOR: exec: "emacs -nw": executable file not found in $PATH
error: exec: "emacs -nw": executable file not found in $PATH
```

### Output of `pulumi about`

```
CLI          
Version      3.80.0-dev.0
Go Version   go1.21.0
Go Compiler  gc

Plugins
NAME  VERSION
rke   unknown
yaml  unknown

Host     
OS       darwin
Version  13.4
Arch     arm64

This project is written in yaml

Current Stack: pulumi/secret-random-yaml/dev

TYPE                  URN
pulumi:pulumi:Stack   urn:pulumi:dev::secret-random-yaml::pulumi:pulumi:Stack::secret-random-yaml-dev
pulumi:providers:aws  urn:pulumi:dev::secret-random-yaml::pulumi:providers:aws::default
aws:s3/bucket:Bucket  urn:pulumi:dev::secret-random-yaml::aws:s3/bucket:Bucket::res


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ian-pulumi-corp
User           ian-pulumi-corp
Organizations  ian-pulumi-corp, pulumi

No dependencies found

Pulumi locates its logs in /var/folders/fg/_1q36r4j6yx0rwz2fbhjd5y40000gn/T/ by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description

`pulumi state edit` now properly handles multi-part EDITOR variables (i.e. `emacs -nw`).

Fixes #13850

## Checklist

- [x] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [x] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/cmd/pulumi/state_edit.go [hunk 1]
```diff
@@ -248,12 +249,25 @@ func (cmd *stateEditCmd) validateAndPrintState(f *snapshotBuffer) (*deploy.Snaps
...
-	if editor == "" {
+	editorEnv := os.Getenv("EDITOR")
+	if editorEnv == "" {
 		return fmt.Errorf("no EDITOR environment variable set")
 	}
+	return openInEditorInternal(editorEnv, filename)
+}
+
+func openInEditorInternal(editorEnv, filename string) error {
+	if editorEnv == "" {
```
Comment (Frassle) [inline pkg/cmd/pulumi/state_edit.go:260]: This should probably be `contract.Requiresf(editor != "", "editor", "must not be empty")`

File: pkg/cmd/pulumi/state_edit.go [hunk 2]
```diff
@@ -248,12 +249,25 @@ func (cmd *stateEditCmd) validateAndPrintState(f *snapshotBuffer) (*deploy.Snaps
...
-	editor := os.Getenv("EDITOR")
-	if editor == "" {
+	editorEnv := os.Getenv("EDITOR")
+	if editorEnv == "" {
 		return fmt.Errorf("no EDITOR environment variable set")
 	}
+	return openInEditorInternal(editorEnv, filename)
+}
+
+func openInEditorInternal(editorEnv, filename string) error {
```
Comment (Frassle) [inline pkg/cmd/pulumi/state_edit.go:259]:
```suggestion
func openInEditorInternal(editor, filename string) error {
```

Just call it editor, it's not important that it came from the envvar

File: pkg/cmd/pulumi/state_edit_test.go [hunk 3]
```diff
@@ -86,3 +86,48 @@ func TestSnapshotFrontendRoundTrip(t *testing.T) {
...
+		},
+	}
+
+	for _, tt := range tests {
+		tt := tt
+		t.Run(tt.name, func(t *testing.T) {
+			t.Parallel()
+			err := openInEditorInternal(tt.command, tt.filename)
+			if tt.wantError {
+				assert.Error(t, err)
```
Comment (Frassle) [inline pkg/cmd/pulumi/state_edit_test.go:127]: If checking for errors you really ought to use ErrorContains, it's far to easy to write a test that errors but isn't actually checking the code path for the error you want.

Comment (dixler) [reply pkg/cmd/pulumi/state_edit_test.go:127]: kk. changing the `""` check to panic means that they should not error and should simplify this.

**Review by Frassle — APPROVED** [review]
