### PR TITLE
programgen(go): Handle conflicting names in imported packages

### LINKED ISSUE #11176: [codegen/go] Conflicting imports are generated
### What happened?

Given a YAML program such as https://github.com/pulumi/pulumi-yaml/blob/main/examples/awsx-fargate/Pulumi.yaml where two different packages have a module with the same name (`aws` and `awsx` both having `ecs` here), codegen does not alias the imports, causing an invalid program  

### Steps to reproduce

Run `pulumi convert --language go` on this example https://github.com/pulumi/pulumi-yaml/blob/main/examples/awsx-fargate/Pulumi.yaml

### Expected Behavior

Import naming conflicts are handled properly

### Actual Behavior

Invalid program generated

### Output of `pulumi about`

_No response_

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by abhinav**
This fixes how programgen generates import statements
to handle conflicting imports when two imported packages
have the same name, e.g.

    github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ecs
    github.com/pulumi/pulumi-awsx/sdk/go/awsx/ecs

To do this, we add a fileImporter type that tracks these imports.
It prefers unnamed imports for packages unless one of the following is
true:

- the name of the package has already been used by another import
- the name of the package does not match the last component
  of the import path (e.g., `example.com/foo-go` with `package foo`).

If the name has already been used by another import,
it attempts the following in-order:

- Combine the last two path components of the import path
  into an identifier and use that if available.
  e.g., `awsxs3` from `sdk/go/awsx/s3`.
- Append a number to the package name and increment it
  until an unused name is found.
  e.g. `ecs2`, `ecs3`, and so on.

There's a change in how this information is tracked as well.
Previously, this was a pull approach: various calls returned
programImports objects which all got merged together.

This change switches to a push approach:
as code is generated and imports are requested,
they're submitted to the fileImporter which keeps track of them
until the next `Reset()` call.
The above also has a nice side effect of dropping a parameter.

Another change worth explicitly calling out:
Previously, getModOrAlias partially duplicated some of the logic
implemented in getPulumiImport, and used `mod`, `originalMod`
in a non-obvious way.
This generated incorrect imports like the following
(note the two `/aws` at the end):

    github.com/pulumi/pulumi-aws/sdk/v5/go/aws/aws

This change replicates more of the logic of getPulumiImport
(now called addPulumiImport) into this function,
and addresses the discrepancy in codegen caused by `mod`/`originalMod`.
The result leaves most existing code unchanged,
except in a couple existing cases where the resulting changes make sense
given the logic for named imports outlined above.

Resolves #11176

### CODE REVIEW

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* master
  * **PR #13289** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi/13289" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi/13289?utm_source=stack-comment).

File: pkg/codegen/testing/test/testdata/modpath-pp/go/modpath.go [hunk 1]
```diff
@@ -1,13 +1,13 @@
 package main
 
 import (
-	"git.example.org/thirdparty/sdk/go/pkg"
+	other "git.example.org/thirdparty/sdk/go/pkg"
```
Comment (abhinav) [inline pkg/codegen/testing/test/testdata/modpath-pp/go/modpath.go:4]: note: basename of import path doesn't match package name, so this makes sense

File: pkg/codegen/testing/test/testdata/synthetic-resource-properties-pp/go/synthetic-resource-properties.go [hunk 2]
```diff
@@ -1,7 +1,7 @@
 package main
 
 import (
-	resourceProperties "git.example.org/pulumi-synthetic/resourceProperties"
+	"git.example.org/pulumi-synthetic/resourceProperties"
```
Comment (abhinav) [inline pkg/codegen/testing/test/testdata/synthetic-resource-properties-pp/go/synthetic-resource-properties.go:4]: base name matches package name so named import not necessary

**Comment by abhinav** [comment]
bors try

**Comment by abhinav** [comment]
> ## try
> Build failed:
> 
> * [bors-ok](https://github.com/pulumi/pulumi/actions/runs/5383254282/jobs/9770460903)

Build is green. Only the merge failed (for obvious reasons).

File: pkg/codegen/go/gen_program.go [hunk 3]
```diff
@@ -1546,3 +1556,162 @@ func programPackageDefs(program *pcl.Program) ([]*schema.Package, error) {
...
+		fi.used[name] = importPath
+		return name
+	}
+
+	// Already imported with an alias. Use that alias.
+	if other, ok := fi.aliases[importPath]; ok {
+		return other
+	}
+
+	// Find a unique name to use as an alias.
```
Comment (Frassle) [inline pkg/codegen/go/gen_program.go:1635]: Can we try using some of the importPath for this first? So like in the regress example added in this PR we'd get "awsxEcs" rather than "ecs2"? e.g. ("example.com/bar/aws", "aws") -> "barAws".

Comment (abhinav) [reply pkg/codegen/go/gen_program.go:1635]: Alright, maybe a "join last two components, and if that's unique, use that, otherwise numbered"? Yeah, I can see that being more readable, though it would be "awsx_ecs" or "awsxecs"; package names aren't camelCase (and even `_` is suspect, but I could bend on that for this).

Comment (abhinav) [reply pkg/codegen/go/gen_program.go]: Done! We now try to build a unique `foo_bar` from the last two components of the import path before falling back to the numerical suffix.

File: pkg/codegen/go/gen_program.go [hunk 4]
```diff
@@ -1552,3 +1562,180 @@ func programPackageDefs(program *pcl.Program) ([]*schema.Package, error) {
...
+		return name
+	}
+
+	// Already imported with an alias. Use that alias.
+	if other, ok := fi.aliases[importPath]; ok {
+		return other
+	}
+
+	// The name is taken. We need a unique unused alias.
+	// We prefer a simple "$mod_$name" (e.g. "aws_s3", "awsx_s3") for
```
Comment (Frassle) [inline pkg/codegen/go/gen_program.go:1642]: _I_ think the underscore is probably better here, but I'm cognisant that Go recommends no underscores in package names and I wonder if we should be trying to maintain that here? "awss3"

Comment (abhinav) [reply pkg/codegen/go/gen_program.go:1642]: Yeah, that sounds better, especially because this generated code is intended to be read and modified by users.

File: pkg/codegen/go/gen_program.go [hunk 5]
```diff
@@ -1552,3 +1562,180 @@ func programPackageDefs(program *pcl.Program) ([]*schema.Package, error) {
...
+	// readability.
+	if parts := strings.Split(importPath, "/"); len(parts) > 2 {
+		// "example.com/foo/bar" -> "foo_bar"
+		candidate := strings.Join(parts[len(parts)-2:], "_")
+
+		// Just in case, drop common non-identifier characters.
+		// e.g., "foo-go" -> "foogo"
```
[the remark this answers is not in the document]
Comment (abhinav) [reply pkg/codegen/go/gen_program.go:1649]: Yeah, I think this logic is more fragile than I intended. I'll have it drop any non-identifier symbols and add some more unit tests.

**Comment by abhinav** [comment]
Updated:
- Prefer "$mod$name" over "$name$num"
- Guarantee that the preferred name is a valid Go package name

**Review by justinvp — APPROVED** [review]
LGTM

**Comment by abhinav** [comment]
bors merge
