### PR TITLE
Generate three-level nested builtin output types for Go SDK

### LINKED ISSUE #21238: Generated Go SDK from `pulumi package add terraform-provider kong/konnect` does not compile (invalid output types)
### What happened?

When generating a Go SDK using `pulumi package add` for the Terraform provider `kong/konnect`, the resulting SDK does not compile due to references to invalid or non-existent Pulumi output types.

This occurs when building a Pulumi project in Go and regenerating the SDK via pulumi install / pulumi package add. The generated code contains Go compilation errors that require manual intervention (patching or deleting files) before the SDK can be used.

### Example

```sh
mkdir provider-debug-dir && cd provider-debug-dir
pulumi new go -y
pulumi package add terraform-provider kong/konnect
cd sdks/konnect
go mod tidy
go test ./... # fails with compilation error
```

### Output of `pulumi about`

```
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):  
Enter your passphrase to unlock config/secrets
CLI          
Version      3.212.0
Go Version   go1.25.5
Go Compiler  gc

Plugins
KIND      NAME  VERSION
language  go    3.212.0

Host     
OS       darwin
Version  26.2
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.24.0 darwin/arm64'

Current Stack: organization/provider-debug-dir/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           Tyler-Gabbs-MacBook-Pro.local
URL            gs://infra-state-abba
User           tyler
Organizations  
Token type     personal

Dependencies:
NAME                             VERSION
github.com/pulumi/pulumi/sdk/v3  v3.212.0

Pulumi locates its logs in /var/folders/_c/7bz0bqp96j9cr09ddpt305rh0000gp/T/ by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by TylerJGabb**
# Generate three-level nested builtin output types for Go SDK

## Why

The Go SDK code generator creates deeply nested output types when providers have schemas with 3+ levels of nesting, but these types were not systematically generated. Previous fixes added specific ad-hoc cases (`StringMapMapMap` for #17415), but the codegen can produce references to any combination of three-level Array/Map nesting, causing compilation failures.

### How the issue was discovered

When running `pulumi package add terraform-provider kong/konnect`, the generated Go SDK included code like:

```go
func (o GetPlatformIpAddressesResultOutput) Regions() pulumi.StringArrayMapMapOutput {
	return o.ApplyT(func(v GetPlatformIpAddressesResult) map[string]map[string][]string { return v.Regions }).(pulumi.StringArrayMapMapOutput)
}
```

However, `pulumi.StringArrayMapMapOutput` did not exist in the SDK, causing this compilation error:

```
undefined: pulumi.StringArrayMapMapOutput
```

## What

Systematically generate all eight three-level nesting patterns for all nine primitive types (Bool, Int, Float64, String, Archive, Asset, AssetOrArchive, ID, URN):

- `ArrayMapMap` → `map[string]map[string][]T`
- `MapArrayMap` → `map[string][]map[string]T`
- `MapMapArray` → `[]map[string]map[string]T`
- `ArrayMapArray` → `[]map[string][]T`
- `ArrayArrayMap` → `map[string][][]T`
- `ArrayArrayArray` → `[][][]T`
- `MapMapMap` → `map[string]map[string]map[string]T`

This adds 72 new output types (8 patterns × 9 primitives), expanding types_builtins.go from ~2,000 to ~14,000 lines. This comprehensive approach replaces ad-hoc special cases with a systematic solution that ensures the codegen can reference any three-level combination without compilation errors.

## How

Modified `sdk/go/pulumi/generate/main.go` to:
1. Extract `arrayMapType` and `mapArrayType` to variables (so they can be referenced by three-level types)
2. Add generation logic for all eight three-level type combinations
3. Regenerate `types_builtins.go` and `types_builtins_test.go`

## Testing

Verified the fix by:
1. Building Pulumi CLI with the changes
2. Running `pulumi package add terraform-provider kong/konnect` to generate the SDK
3. Confirming the generated code compiles successfully
4. Verifying that `StringArrayMapMapOutput` and other new types are properly generated and used
5. Running `go test ./...` in sdk/go/pulumi to confirm all tests pass

Fixes #21238

### CODE REVIEW

File: sdk/go/pulumi/generate/main.go [hunk 1]
```diff
@@ -294,31 +296,88 @@ func makeBuiltins(primitives []*builtin) []*builtin {
...
-				ItemType:      "ArrayArrayInput",
-				elementType:   "map[string][][]" + p.Type,
-				item:          arrayArrayType,
-				Example:       fmt.Sprintf("%sArrayArrayMap{\"baz\": %sArrayArray{Array{%s}}}", name, name, p.Example),
-				RegisterInput: true,
-			})
-		}
+		// Three-level nesting types for all primitives
+		// These handle cases like map[string]map[string][]T or map[string][][]T
+		// See: https://github.com/pulumi/pulumi/issues/XXXXX (kong/konnect provider issue)
```
Comment (Frassle) [inline sdk/go/pulumi/generate/main.go]:
```suggestion
		// See: https://github.com/pulumi/pulumi/issues/21238 (kong/konnect provider issue)
```

File: sdk/go/pulumi/generate/main.go [hunk 2]
```diff
@@ -294,31 +296,88 @@ func makeBuiltins(primitives []*builtin) []*builtin {
...
+			ItemType:      name + "ArrayArrayInput",
+			elementType:   "[][][]" + p.Type,
+			item:          arrayArrayType,
+			Example:       fmt.Sprintf("%sArrayArrayArray{%sArrayArray{%sArray{%s}}}", name, name, name, p.Example),
+			RegisterInput: true,
 		}
+		builtins = append(builtins, arrayArrayArrayType)
+
+		// MapMapMap: map[string]map[string]map[string]T
+		// (Already exists for String, now adding for all primitives)
```
Comment (Frassle) [inline sdk/go/pulumi/generate/main.go]:
```suggestion
```

**Comment by TylerJGabb** [comment]
@Frassle I have addressed your concerns and added a changelog.

**Comment by Frassle** [comment]
Just checking internally if anyone knows why we didn't do this before, but worried about the proliferation of types might be an issue for the compiler or usability.

**Comment by TylerJGabb** [comment]
Yeah perhaps I could modify my solution to only support the type that was missing `StringArrayMapMapOutput` and not necessarily every possible permutation of nesting 3 levels deep.

**Comment by TylerJGabb** [comment]
Okay @Frassle I went ahead and reduced the total changes I've made - and scoped it specifically to the type I was missing for the terraform-provider kong/konnect.

**Comment by Frassle** [comment]
OK checking in with the rest of the team, no one knows of any reason we didn't have these before, so probably ok to just add all the combinations as you originally did. At least that's then consistent.

**Comment by TylerJGabb** [comment]
@Frassle 😆 full circle! Done.

**Comment by Frassle** [comment]
/run-acceptance-tests 
Please view the results of the acceptance tests [Here](https://github.com/pulumi/pulumi/actions/runs/20293872550)

**Comment by Frassle** [comment]
Thanks, hopefully we'll get generics one day and not need "fun" like this.

**Review by Frassle — APPROVED** [review]
