### PR TITLE
[sdkgen/python] Use `importlib.metadata` instead of `pkg_resources`

### LINKED ISSUE #12414: pulumi_aws python package doesn't specify requirement on setuptools / pkg_resources
### What happened?

When pulumi project is installed in an environment without setuptools, running program fails with:
```
Diagnostics:
  pulumi:pulumi:Stack (dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "__main__.py", line 8, in <module>
        from pulumi_aws import ec2
      File ".venv\Lib\site-packages\pulumi_aws\__init__.py", line 5, in <module>
        from . import _utilities
      File ".venv\Lib\site-packages\pulumi_aws\_utilities.py", line 10, in <module>
        import pkg_resources
    ModuleNotFoundError: No module named 'pkg_resources'
```

### Expected Behavior

pulumi_aws should either explicitly specify its requirement on setuptools or (better) switch away from deprecated technology
> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.

(https://setuptools.pypa.io/en/latest/pkg_resources.html)

### Steps to reproduce

Steps are basically the same as in https://github.com/pulumi/pulumi/issues/12390, just pick aws template and add pip (the workaround)

### Output of `pulumi about`

CLI
Version      3.56.0
Go Version   go1.20.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.30.1
gcp     6.51.0
github  5.5.0
python  unknown

Host
OS       Microsoft Windows 11 Home
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in python: executable='C:\Users\Yuri\AppData\Local\Programs\Python\Python311\python.exe' version='3.11.2
'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           NOID-00646
URL            s3://***
User           NOID-00646\Yuri Timenkov
Organizations

Dependencies:
NAME             VERSION
infra-ci-runner  1.0.0

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by justinvp**
This addresses two issues:

1. `pkg_resource` is deprecated in favor of `importlib.resources` and `importlib.metadata` (https://setuptools.pypa.io/en/latest/pkg_resources.html)

2. Generated provider SDKs don't indicate that they have a dependency on `setuptools` (which includes `pkg_resources`), which can cause problems when installing the package in environments that don't have `setuptools` installed. That's not often common in Pulumi projects, as the virtual environment created by the CLI will include `setuptools`, however, if creating the virtual environment manually with `python -m venv`, `setuptools` is no longer included in the created virtual environment as of Python 3.12.

Fixes #12414

Based on #14002, thanks @edgarrmondragon!

### CODE REVIEW

File: pkg/codegen/python/gen_test.go [hunk 1]
```diff
@@ -292,6 +292,7 @@ func TestCalculateDeps(t *testing.T) {
 			// We expect three alphabetized deps,
```
Comment (Frassle) [inline pkg/codegen/python/gen_test.go:292]:
```suggestion
			// We expect four alphabetized deps,
```

**Review by Frassle — APPROVED** [review]
