### PR TITLE
[sdk/go] Don't panic on Elem and Index operations

### LINKED ISSUE #6154: [sdk/go] Consider safer Elem/Index/MapIndex functions instead of allowing these to panic
I need to extract an AWS EKS cluster security group ID to provide security group information for a launch template. Tried to do it like this:

```
eksCluster := eks.NewCluster(...)
securityGroup := eksCluster.VpcConfig.ClusterSecurityGroupId().Elem()
launchTemplateArgs := ec2.LaunchTemplateArgs{
    (...),
    NetworkInterfaces: ec2.LaunchTemplateNetworkInterfaceArray{
        ec2.LaunchTemplateNetworkInterfaceArgs{
	    DeviceIndex: pulumi.IntPtr(0),
	    SecurityGroups: pulumi.StringArray{
                eksCluster.VpcConfig.ToClusterVpcConfigOutput().ClusterSecurityGroupId().Elem(),
	    },
	},
    },
}
launchTemplate, err := ec2.NewLaunchTemplate(ctx, (...), &launchTemplateArgs)
```
When I run `pulumi up` it ends up with:

```
Diagnostics:
  pulumi:pulumi:Stack (create-cluster-jakubz-test):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbb7925]
    goroutine 203 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.StringPtrOutput.Elem.func1(0x0, 0x0, 0x0)
        /home/jzaron/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.17.2/go/pulumi/types_builtins.go:6623 +0x5
    reflect.Value.call(0xa25b620, 0xc11f8b0, 0x13, 0xc04dd80, 0x4, 0xc000252cd8, 0x1, 0x1, 0x10, 0xc0004dd370, ...)
        /usr/lib/go-1.14/src/reflect/value.go:460 +0x8ab
    reflect.Value.Call(0xa25b620, 0xc11f8b0, 0x13, 0xc000252cd8, 0x1, 0x1, 0xa3be1a0, 0xc0004dd370, 0xc0008d0bd8)
        /usr/lib/go-1.14/src/reflect/value.go:321 +0xb4
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.makeContextful.func1(0xc000252cc0, 0x2, 0x2, 0xc000252cc0, 0x3, 0xc0004aa9f0)
        /home/jzaron/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.17.2/go/pulumi/types.go:286 +0x7c
    reflect.callReflect(0xc000145650, 0xc0008d0bd8, 0xc0008d0bc0)
        /usr/lib/go-1.14/src/reflect/value.go:549 +0x322
    reflect.makeFuncStub(0xc32c7c0, 0xc000052098, 0x0, 0x0, 0x0, 0xa16fec0, 0x0, 0xc000252c90, 0xc0008d0e30, 0x4b33fb, ...)
        /usr/lib/go-1.14/src/reflect/asm_amd64.s:20 +0x42
    reflect.Value.call(0xc00040e660, 0xc000145650, 0x13, 0xc04dd80, 0x4, 0xc0008d0f60, 0x2, 0x2, 0xa475160, 0xa16fec0, ...)
        /usr/lib/go-1.14/src/reflect/value.go:460 +0x8ab
    reflect.Value.Call(0xc00040e660, 0xc000145650, 0x13, 0xc000123f60, 0x2, 0x2, 0xc000676040, 0x1, 0x1)
        /usr/lib/go-1.14/src/reflect/value.go:321 +0xb4
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.(*OutputState).ApplyTWithContext.func1(0xc000192e00, 0xc32c7c0, 0xc000052098, 0xc3ad040, 0xc000192e70, 0xc00040e660, 0xc000145650, 0x13)
        /home/jzaron/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.17.2/go/pulumi/types.go:410 +0x28b
    created by github.com/pulumi/pulumi/sdk/v2/go/pulumi.(*OutputState).ApplyTWithContext
        /home/jzaron/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.17.2/go/pulumi/types.go:398 +0x1e0
    exit status 2

    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

The problem seems to be that the Elem() function causes too early pointer dereference. I can't just use value returned by `ClusterSecurityGroupId()` because it returns `StringPtrOutput` . This is incompatible with the type I need to create a launch template, as `LaunchTemplateArgs -> NetworkInterfaces -> SecurityGroups` is of `StringArray` type, so with `StringPtrOutput` code won't compile at all.

The problem pops out if the cluster does not exist at the time of running `pulumi up`. If the cluster already exists, all works fine, but it's worth nothing.

I tried to find some help on Pulumi Slack, but after some discussion was told to report a bug.

## Expected Behavior
`pulumi up` causes normal execution with no runtiime error, first it creates AWS EKS cluster, then creates launch template using cluster security group ID.

## Current Behavior
`pulumi up` ends up with runtime error.

## Steps to Reproduce
Take Pulumi Golang SDK. Try to create an EKS cluster, and then to create a launch template with interface binded to cluster's default security group. Code stub is above (if needed, I can provide full code, just don't want to make this post too heavy).

## Context (Environment)
I need to extract an AWS EKS cluster security group ID to provide security group information for a launch template. I use a custom AMI for worker nodes, so AWS forces me to define a launch template.

### PR DESCRIPTION
**Pull request by lukehoban**
Fixes #6154.

### CODE REVIEW

File: sdk/go/pulumi/templates/types_builtins.go.template [hunk 1]
```diff
@@ -134,20 +134,34 @@ func (o {{.Name}}Output) To{{.Name}}PtrOutputWithContext(ctx context.Context) {{
...
 {{if .DefineIndex}}
+// Index looks up the i'th element of the array if it is in bounds or returns the zero value of the appropriate
+// type if the index is out of bounds.
 func (o {{.Name}}Output) Index(i IntInput) {{.IndexReturnType}}Output {
 	return All(o, i).ApplyT(func(vs []interface{}) {{.IndexElementType}} {
-		return vs[0].({{.ElementType}})[vs[1].(int)]
+		arr := vs[0].({{.ElementType}})
+		idx := vs[1].(int)
+		var ret {{.IndexElementType}}
+		if idx >= 0 && idx < len(arr) {
```
Comment (pgavlin) [inline sdk/go/pulumi/templates/types_builtins.go.template:156]:
```suggestion
		var ret {{.IndexElementType}}
		if idx := vs[1].(int); idx >= 0 && idx < len(arr) {
```

**Review by pgavlin — APPROVED** [review]
One nit; LGTM otherwise.

File: sdk/go/pulumi/templates/types_builtins.go.template (hunk 1 above)
Comment (lukehoban) [reply sdk/go/pulumi/templates/types_builtins.go.template:156]: I honestly slightly prefer the original - so will keep it as is for now.
