### PR TITLE
Do not pass arguments as secrets to CheckConfig/Configure

### LINKED ISSUE #2741: k8s.Provider({kubeconfig}) fails when referencing a secret or a stack ref
When either a `pulumi.secret` or a `StackReference` prop is made part of the graph that results in a kubeconfig, the below error occurs.

image

Example:

```ts
const k8sProvider = new k8s.Provider(name, {
  kubeconfig: pulumi.secret("dont tell anybody")
});
```

```ts
const k8sProvider = new k8s.Provider(name, {
  kubeconfig: new pulumi.StackReference('pancake').getOutput('syrup')
});
```

### PR DESCRIPTION
**Pull request by ellismg**
Providers from plugins require that configuration value be
strings. This means if we are passing a secret string to a
provider (for example, trying to configure a kubernetes provider based
on some secret kubeconfig) we need to be careful to remove the
"secretness" before actually making the calls into the provider.

Failure to do this resulted in errors saying that the provider
configuration values had to be strings, and of course, the values
logically where, they were just marked as secret strings

Fixes #2741

### CODE REVIEW

**Comment by jeffijoe** [comment]
I suppose using pulumi.all([pulumi.secret()]) maps the resulting Output as secret as well because it “contains” a secret?

Are stack ref outputs also considered secrets?

**Comment by ellismg** [comment]
> I suppose using pulumi.all([pulumi.secret()]) maps the resulting Output as secret as well because it “contains” a secret?

Correct.

> Are stack ref outputs also considered secrets?

If a stack has *any* secret outputs, and you take a reference to that stack, then *all* values you pull from that stack reference will be considered secrets.  This is not ideal, but happens because of how the StackReference type was designed.  It has a single output property which aggregates all the stack outputs from the stack you are referencing.  Because this output contains a secret, it means the entire output needs to be treated as a secret today, meaning that when you interact with it either directly (or indirectly, via calling `.getOutput`) we consider that value to be secret, even if it was for a different output. 

We may be able to relax this in the future.  I opened https://github.com/pulumi/pulumi/issues/2744 to track it.

File: pkg/resource/plugin/provider_plugin.go [hunk 1]
```diff
@@ -172,13 +178,18 @@ func (p *provider) Configure(inputs resource.PropertyMap) error {
...
 
-	// Convert the inputs to a config map. If any are unknown, do not configure the underlying plugin: instead, leavce
+	// Convert the inputs to a config map. If any are unknown, do not configure the underlying plugin: instead, leave
 	// the cfgknown bit unset and carry on.
 	config := make(map[string]string)
 	for k, v := range inputs {
 		if k == "version" {
 			continue
 		}
+		// The configure method has to accept strings, so we go through anf strip off all the secret markers before
```
Comment (swgillespie) [inline pkg/resource/plugin/provider_plugin.go]:
```suggestion
		// The configure method has to accept strings, so we go through and strip off all the secret markers before
```

**Comment by ellismg** [comment]
> LGTM. Is it possible to easily test this code path?

I am not sure.  It's not easy to do so with the lifecycle test framework, because the code does not go through `provider_plugin.go`.  It's possible we could test this using the dynamic provider, let me see if that's possible.  Otherwise, it would be easier to test "upstack" in one of the provider repositories.

**Comment by jeffijoe** [comment]
That makes sense, the example didnt use secrets at all and I guess I now know why 😅

I think its possible that secrets are also the root cause of #2739

**Comment by ellismg** [comment]
Added a simple test using the dynamic provider.
