### PR TITLE
[display] Fix detailed diff indentation when hidden parents are unchanged

### LINKED ISSUE #22056: detailed diff showing confusing indentation when a nested resource is changed but the parent is not
### What happened?

Consider the following:

Image

We have a top level `ServiceIdentity` being added, and an unrelated resource `InstanceTemplate` which is nested under `OtelResource` being updated (create-replace in this case).

If we look at the diff view `OtelResource` is not shown (as it is not itself changing), but we still indent `InstanceTempate` because its a child.  This makes it appear that `InstanceTemplate` is a child of the new resource `ServiceIdentity`, even though it is not.

Image

### Example

n/a

### Output of `pulumi about`

n/a

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by RohitYandigeri**
## Summary
Fixes #22056.

Detailed diff rendering currently computes indentation from the full parent chain recorded in the
event metadata, even when some ancestors are not shown in the diff output.

That leads to confusing output when:
- a nested resource changes,
- its parent is unchanged and therefore hidden,
- and another unrelated top-level resource is shown nearby.

In that case, the changed child is still indented as if its hidden parent were visible, which makes
it look like the child belongs under the wrong displayed resource.

This PR fixes that by computing indentation from the visible ancestor chain rather than the full
resource parent chain. Hidden unchanged parents no longer contribute indentation, so displayed child
resources align under the nearest displayed ancestor.

It also makes parent lookup in indentation logic robust by reading the parent from `Res`, `New`, or
`Old`, whichever is available.

## Test plan
- [x] Added appropriate unit tests - For all changes
- [ ] Added a test in `pkg/engine/lifecycletest` - For all engine/protocol changes
- [ ] Added a conformance test in `pkg/testing/pulumi-test-language` - For language protocol changes
- [ ] Added a golden test in `pkg/backend/display` - For changes to the output renderers

## Validation
- [ ] `make lint` — clean
- [ ] `make test_fast` — all pass
- [ ] `make tidy_fix` — clean
- [ ] `make format_fix` — clean
- [ ] Relevant SDK tests pass (if SDK changes)
- [ ] `make check_proto` — clean (if proto changes)

Commands run:
- `go test ./backend/display -run TestCreateDiffDoesNotIndentBeneathHiddenParent -count=1`
  - verified failing on the test-only commit
- `go test ./backend/display -run "Test(CreateDiffDoesNotIndentBeneathHiddenParent|DiffEventsCreateDiff|CreateDiffRequiresColor)" -count=1`
  - verified passing after the fix

## Changelog
- [x] Changelog entry added.

## Risk
Low.

Blast radius is limited to detailed diff rendering in the CLI display layer. This does not change
engine behavior, resource planning, provider behavior, or state handling.

The behavior change is that indentation for detailed diffs now reflects only ancestors that are
actually shown in the rendered diff output, which makes nested changes display consistently and avoids
misleading visual grouping.

### CODE REVIEW

File: pkg/backend/display/object_diff.go [hunk 1]
```diff
@@ -44,19 +44,34 @@ import (
...
+		return step.Res.Parent
+	}
+	if step.New != nil {
+		return step.New.Parent
+	}
+	if step.Old != nil {
+		return step.Old.Parent
+	}
+	return ""
+}
```
Comment (Frassle) [inline pkg/backend/display/object_diff.go]: Why this change? Shouldn't Res always be set?

Comment (RohitYandigeri) [reply pkg/backend/display/object_diff.go]: I added that defensively while tracing parent lookup across the different step shapes in the detailed diff renderer, but you’re right that for the display path here Res should be populated.

I can simplify this back to using step.Res.Parent directly and keep the actual fix scoped just to counting visible parents for indentation.

Comment (Frassle) [reply pkg/backend/display/object_diff.go]: I think given Res.Parent seemed fine before it should just stay as that

Comment (RohitYandigeri) [reply pkg/backend/display/object_diff.go]: Reverted that helper and restored the original Res.Parent lookup in b6e99d6194.

The PR is now scoped just to the visible-parent indentation change.

File: pkg/backend/display/diff_test.go [hunk 2]
```diff
@@ -267,3 +269,75 @@ func TestCreateDiffRequiresColor(t *testing.T) {
...
+	diff, err := CreateDiff(events, Options{
+		Color:                colors.Never,
+		ShowSameResources:    false,
+		ShowReplacementSteps: true,
+	})
+	require.NoError(t, err)
+
+	assert.Contains(t, diff, "\n    + pkg:index:Sibling: (create)\n")
+	assert.Contains(t, diff, "\n    ~ pkg:index:Child: (update)\n")
+	assert.NotContains(t, diff, "\n        ~ pkg:index:Child: (update)\n")
```
Comment (Frassle) [inline pkg/backend/display/diff_test.go]: Wonder if it makes more sense to just do an equals check here fro the whole diff string? Is that too much

Comment (RohitYandigeri) [reply pkg/backend/display/diff_test.go]: Tightened the regression test to assert the full rendered diff string and pushed that in 8be72d9220.

File: pkg/backend/display/diff_test.go [hunk 3]
```diff
@@ -267,3 +270,80 @@ func TestCreateDiffRequiresColor(t *testing.T) {
 	require.Error(t, err)
 	assert.Contains(t, err.Error(), "color must be specified")
 }
+
+func TestCreateDiffDoesNotIndentBeneathHiddenParent(t *testing.T) {
+	t.Parallel()
+
+	stackURN := resource.URN("urn:pulumi:dev::project::pulumi:pulumi:Stack::project-dev")
+	parentURN := resource.URN("urn:pulumi:dev::project::pkg:index:Parent::otel-collector")
+	childURN := resource.URN("urn:pulumi:dev::project::pkg:index:Child::template")
```
Comment (Frassle) [inline pkg/backend/display/diff_test.go]: As a point of snapshot correctness this type should have the parent type as well
```suggestion
	childURN := resource.URN("urn:pulumi:dev::project::pkg:index:Parent$pkg:index:Child::template")
```

File: pkg/backend/display/diff_test.go [hunk 4]
```diff
@@ -267,3 +270,80 @@ func TestCreateDiffRequiresColor(t *testing.T) {
 	require.Error(t, err)
 	assert.Contains(t, err.Error(), "color must be specified")
 }
+
+func TestCreateDiffDoesNotIndentBeneathHiddenParent(t *testing.T) {
+	t.Parallel()
+
+	stackURN := resource.URN("urn:pulumi:dev::project::pulumi:pulumi:Stack::project-dev")
+	parentURN := resource.URN("urn:pulumi:dev::project::pkg:index:Parent::otel-collector")
```
Comment (Frassle) [inline pkg/backend/display/diff_test.go]: Use more generic names
```suggestion
	parentURN := resource.URN("urn:pulumi:dev::project::pkg:index:Parent::parentRes")
```
For the other resources as well

Comment (RohitYandigeri) [reply pkg/backend/display/diff_test.go]: Applied those test fixups and pushed e8c9bf7807.

I updated the child URN to include the parent type for snapshot correctness, and changed the synthetic resource names to generic values throughout the test.

**Comment by Frassle** [comment]
/run-acceptance-tests
Please view the results of the acceptance tests [Here](https://github.com/pulumi/pulumi/actions/runs/23412186846)

**Comment by RohitYandigeri** [comment]
> `getIndent` now only counts visible/stack parents (`shouldShow`), which fixes the extra indent when same parents are hidden; `TestCreateDiffDoesNotIndentBeneathHiddenParent` pins the layout. Nit: if any future caller passes a different `Options` than the renderer, indentation could disagree with filtering—worth keeping call sites paired.

Thanks, agreed. The fix relies on getIndent and the filtering logic using the same Options, so I’ve kept it scoped to the current renderer path where those call sites stay paired. The regression test is intended to pin that layout and catch drift if those paths diverge later.

**Comment by RohitYandigeri** [comment]
> This looks correct to me.
> 
> @Frassle I think this is OK to take, but I think it would be better UX if we instead rendered the parent & then correctly indented the child. We can do that in a follow-up if we care to.

Thanks for the review. Agreed on the UX point as well. This PR keeps the narrower fix of correcting indentation when hidden same-parents are omitted, and rendering the hidden parent explicitly would make sense as a follow-up improvement if we want to take the display further.
