### PR TITLE
Fix 8110

### LINKED ISSUE #8110: Node codegen emits incorrectly nested enum-array type literals
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

In certain circumstances of nested arrays/unions nodejs codegen emits the wrong type. 

### Steps to reproduce

Consider:

```
    "deploymentTypes": {
      "type": "array",
      "items": {
       "oneOf": [
        {
         "type": "string"
        },
        {
         "$ref": "#/types/azure-native:network:ConfigurationType"
        }
       ]
     },
```

The intent is `Array<Union<string,ConfigurationType>>`.

But the generated code is:

https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/nodejs/network/listNetworkManagerDeploymentStatus.ts#L33

```typescript
string | enums.network.v20210201preview.ConfigurationType[]
```

Which gets interpreted as `Union<string,Array<ConfigurationType>>`.

Expected: `(string | enums.network.v20210201preview.ConfigurationType)[]`
Actual: `string | enums.network.v20210201preview.ConfigurationType[]`

### PR DESCRIPTION
**Pull request by t0yv0**
# Description

Fix Node codegen to not create incorrectly parsed type references for unions and optionals.

Fixes #8110

Based on discussion, some effort was put into minimally inserting parens, rather than inserting them everywhere. 

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by pgavlin — COMMENTED** [review]
This feels like an annoying question, but how hard would it be to only generate the parens when they're necessary? It'd minimize the diffs and would keep the types a little less noisy.

**Comment by t0yv0** [comment]
Not annoying at all I was asking the same thing.

It would also make diff checking easier.

It's some work mostly to find TypeScript grammar precedence rules. If someone remembers how those work that could be a great help.

**Comment by t0yv0** [comment]
Not seeing BNF in https://www.typescriptlang.org/docs/handbook/2/everyday-types.html

But at first glance, `[]` has higher precedence than `|` and we don't have other "operators" at play so I can just try to handle those.

File: pkg/codegen/internal/tstypes/tstypes_test.go [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+	"fmt"
+	"testing"
+
+	"github.com/davecgh/go-spew/spew"
+
+	"github.com/stretchr/testify/assert"
+	"pgregory.net/rapid"
+)
+
+func TestParenInsert(t *testing.T) {
```
Comment (t0yv0) [inline pkg/codegen/internal/tstypes/tstypes_test.go:27]: Admittedly verbose but foolproof. Works on a simplified grammar but can be easily extended if we run into more grammar peculiarities. This checks that unparsing and auto-parenthesizing the AST into tokens gets parsed back into the same ast.

File: pkg/codegen/internal/tstypes/tstypes_test.go [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+		if err != nil {
+			t.Error(err)
+			return
+		}
+		t.Logf("parsed: %s", spew.Sdump(parsed))
+		assert.Equal(t, example, parsed)
+	})
+}
+
+func astGenerator() *rapid.Generator {
```
Comment (t0yv0) [inline pkg/codegen/internal/tstypes/tstypes_test.go:48]: Lib remark: shrinking trees seems not entirely satisfactory, I'd like to compare to what Haskell has and if necessary send a patch upstream. Once a bad tree T has been found, I'd like it to be minimized heavily by pruning branches that do not matter for the test before presenting to the user.

File: pkg/codegen/internal/test/testdata/regress-node-8110/go/my8110/pulumiTypes.go [hunk 3]
```diff
@@ -0,0 +1,64 @@
+// *** WARNING: this file was generated by test. ***
+// *** Do not edit by hand unless you're certain you know what you are doing! ***
```
Comment (t0yv0) [inline pkg/codegen/internal/test/testdata/regress-node-8110/go/my8110/pulumiTypes.go:2]: Non-node code noisy, relatively low value, we should probably support skipping codegen by lang.

File: pkg/codegen/internal/tstypes/tstypes.go [hunk 4]
```diff
@@ -0,0 +1,222 @@
...
+)
+
+type typeToken struct {
+	kind  typeTokenKind
+	value string
+}
+
+type typeScriptTypeUnparser struct{}
+
+func (u *typeScriptTypeUnparser) unparse(ast TypeAst) []typeToken {
```
Comment (pgavlin) [inline pkg/codegen/internal/tstypes/tstypes.go:173]: are these methods just for scoping? if so, these can take a value receiver:

```suggestion
func (u typeScriptTypeUnparser) unparse(ast TypeAst) []typeToken {
```

**Review by pgavlin — APPROVED** [review]
