### PR TITLE
[cli] make `pulumi stack rm` more usable

### LINKED ISSUE #9663: pulumi stack rm prompt is confusing
when deleting a stack we ask the person to type the stack name, for example if the stack name is dev we ask them to type "dev", but if you type "dev" with the quotes it does not work.

suggest dropping both the quotes and the parens from that prompt

```
This will permanently remove the 'dev' stack!
Please confirm that this is what you'd like to do by typing ("dev"): 
```

this came up in a usability study today

### PR DESCRIPTION
**Pull request by dixler**
# Description
This PR clarifies highlighting of confirmation text in `confirmPrompt`.

Fixes #9663

New:
[asciicast](https://asciinema.org/a/m8E9OK7TVtSWRvIJAWtHEivlv)

Old:
[asciicast](https://asciinema.org/a/G0ScAU2SYLnx1WYGwnBMT6dpK)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/cmd/pulumi/pulumi.go [hunk 1]
```diff
@@ -649,5 +649,6 @@ func confirmPrompt(prompt string, name string, opts display.Options) bool {
 
 	reader := bufio.NewReader(os.Stdin)
 	line, _ := reader.ReadString('\n')
-	return strings.TrimSpace(line) == name
+	input := strings.TrimSpace(line)
+	return strings.Trim(input, "\"") == name
```
Comment (Frassle) [inline pkg/cmd/pulumi/pulumi.go:653]: I worry about putting this so deep in input parsing, there _may_ be cases where '"' is a valid char to input and this will confuse the hell out of us if we forget about it.
Also are they're really enough people adding quotes to their prompt answers that this is needed?

Comment (Frassle) [reply pkg/cmd/pulumi/pulumi.go:653]: OK I re-read the issue, this is _very_ specific to "pulumi stack rm" so I'd be ok with the trim('"') there.

Comment (dixler) [reply pkg/cmd/pulumi/pulumi.go:653]: I'll recheck usage and name this explicitly for stackRm if it's the only user.

**Review by Frassle — APPROVED** [review]
