### PR TITLE
Do not prompt for passphrase multiple times

### LINKED ISSUE #2729: passphrase provider prompts twice on pulumi up
I just created a new stack with `--secrets-provider passphrase`, and when I run `pulumi up`, it prompts me twice, back to back, to enter my passphrase:

```
$ pulumi up
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE to remember):
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE to remember):
```

This seems like unexpected behavior to me.

### PR DESCRIPTION
**Pull request by ellismg**
The change does two things:

- Reorders some calls in the CLI to prevent trying to create a secrets
  manager twice (which would end up prompting twice).

- Adds a cache inside the passphrase secrets manager such that when
  decrypting a deployment, we can re-use the one created earlier in
  the update. This is sort of a hack, but is needed because otherwise
  we would fail to decrypt the deployment, meaning that if you had a
  secret value in your deployment *and* you were using local
  passphrase encryption *and* you had not set PULUMI_CONFIG_PASSPHRASE
  you would get an error asking you to do so.

Fixes #2729

### CODE REVIEW

**Comment by ellismg** [comment]
Ideally we can move some of this caching into the `backend.Stack` object, but to do so we need to start tracking the configuration file that was passed to the CLI (if it was overwritten) inside the backend and that's a slightly more invasive change.  I want to get this core case smooth ASAP as we plan to blog about this on Thursday.

**Comment by ellismg** [comment]
I pushed a fix for another issue here @justinvp.  It is in a different commit with a good message, but the same PR to cut down on the CHANGELOG.md merge conflicts.

File: cmd/new.go [hunk 1]
```diff
@@ -343,8 +349,8 @@ func newNewCmd() *cobra.Command {
 		&yes, "yes", "y", false,
 		"Skip prompts and proceed with default values")
 	cmd.PersistentFlags().StringVar(
-		&secretsProvider, "secrets-provider", "", "The name of the provider that should be used to encrypt and "+
-			"decrypt secrets.")
+		&secretsProvider, "secrets-provider", "default", "The type of the provider that should be used to encrypt and "+
+			"decrypt secrets (possible choices: default, passpharse)")
```
Comment (justinvp) [inline cmd/new.go]: passpharse => passphrase (throughout)

File: pkg/secrets/passphrase/manager.go [hunk 2]
```diff
@@ -103,18 +104,38 @@ func (sm *localSecretsManager) Encrypter() (config.Encrypter, error) {
 	return sm.crypter, nil
 }
 
+var lock sync.Mutex
+var cache map[string]secrets.Manager
+
 func NewPassphaseSecretsManager(phrase string, state string) (secrets.Manager, error) {
+	// check the cache first, if we have an already seen this state before, return a cached value
```
Comment (justinvp) [inline pkg/secrets/passphrase/manager.go]: Nit: End the comment with a period.

Comment (justinvp) [reply pkg/secrets/passphrase/manager.go]: Also: "an already" => "already"
