### PR TITLE
Install policy packs in parallel with plugins

### LINKED ISSUE #21442: Install required policy packs in parallel with plugins
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Right now, required policies are installed sequentially _after_ plugins are installed. This is problematic for two primary reasons:

1. If plugin installation takes a long time, the policy pack URLs may expire
2. General slowness waiting for policies to be installed sequentially, when they could be downloaded in parallel

### Affected area/feature

Policy as Code

### LINKED ISSUE #21443: Installation of required policy packs disrupts the interactive pulumi update TUI
This is a UX regression that appears to have regressed with https://github.com/pulumi/pulumi/pull/17019 which shipped in [v3.131.0](https://github.com/pulumi/pulumi/releases/tag/v3.131.0).

Previously, when running a Pulumi operation such as `pulumi up` interactively, if any required plugins needed to be installed, they'd be installed and then any required policy packs would be installed, _before_ the TUI for the update is shown.

With https://github.com/pulumi/pulumi/pull/17019, plugin installation progress is now shown as part of the update TUI, which renders plugin installation progress events.

If any required policy packs need to be installed, they are, but this results in output emitted to stdout (npm install output, pip output, etc.), which gets interleaved with the update's TUI and messes it up.

Instead, policy installation progress should be reported in the same way as plugins, via progress events that are rendered in the update TUI.

### PR DESCRIPTION
**Pull request by justinvp**
Download/install missing required policy packs in parallel with downloading/installing missing plugins during Pulumi operations.

As part of this, we show the same progress bars in system messages we do for plugins. Additionally, we elide policy pack dependency installation output (e.g. `npm install` / `pip install` output), which previously was written to stdout/stderr, as this messes up the interactive update display.

Additionally, the "Loading policy packs..." message, has been updated to display as a system message like the rest of the "downloading" and "installing" messages, otherwise, the interactive table gets messed up.

Fixes #21442
Fixes #21443

## Before

https://github.com/user-attachments/assets/fd81d473-3ff6-4162-9878-556e15c66f2d

## After

https://github.com/user-attachments/assets/91859160-e7c2-47d3-8799-6df04750fcbc

---

I'm planning two follow-up changes after this (will open issues to track):

1. Add an integration test. Will likely require some manual calls the Pulumi Cloud API to create a temp policy group and add the test policy pack and test stack to it.
2. When installing plugins that have dependencies, we have the same problem as #21443, where the output of installing dependencies for the plugin (e.g. `npm install`) gets written out to stdout/stderr and messes-up the interactive display.

### CODE REVIEW

**Comment by justinvp** [comment]
This change is part of the following stack:

- #21651 ◀
    - #21652

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>

File: pkg/backend/httpstate/client/client.go [hunk 1]
```diff
@@ -1175,23 +1175,24 @@ func (pc *Client) RemovePolicyPackByVersion(ctx context.Context, orgName string,
 	return nil
 }
 
-// DownloadPolicyPack applies a `PolicyPack` to the Pulumi organization.
-func (pc *Client) DownloadPolicyPack(ctx context.Context, url string) (io.ReadCloser, error) {
+// DownloadPolicyPack downloads a `PolicyPack` fro the given URL. It returns a ReadCloser to read
```
Comment (Frassle) [inline pkg/backend/httpstate/client/client.go]:
```suggestion
// DownloadPolicyPack downloads a `PolicyPack` from the given URL. It returns a ReadCloser to read
```

**Review by Frassle — APPROVED** [review]
