### PR TITLE
[docs] Fix generating constructor examples for resources that have numeric enums as input

### LINKED ISSUE #16191: Missing constructor syntax examples for the Pulumi service provider
https://www.pulumi.com/registry/packages/pulumiservice/api-docs/teamstackpermission/

image

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

Fixes #16191 

The original issue is that the intermediate PCL we generate used enum names instead of enum values for numeric enum inputs. This PR changes it so that the PCL program now uses the first numeric value for the first enum case then subsequently fixing downstream program-gen bugs that didn't know how to handle numeric values as inputs for enums. 

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [x] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

### CODE REVIEW

File: pkg/codegen/docs/constructor_syntax_generator_test.go [hunk 1]
```diff
@@ -51,6 +62,11 @@ func TestConstructorSyntaxGeneratorForSchema(t *testing.T) {
 							Type: "boolean",
 						},
 					},
+					"fooNumericEnum": {
+						TypeSpec: schema.TypeSpec{
+							Ref: "#/types/test:index:ExampleEnum",
+						},
+					},
```
Comment (justinvp) [inline pkg/codegen/docs/constructor_syntax_generator_test.go:69]: Should we also add a test case for non-numeric enum?

File: pkg/codegen/dotnet/gen_program_expressions.go [hunk 2]
```diff
@@ -407,14 +412,13 @@ func (g *generator) genIntrensic(w io.Writer, from model.Expression, to model.Ty
...
-		case to.Type.Equals(model.StringType):
+		if to.Type.Equals(model.StringType) {
 			convertFn = fmt.Sprintf("System.Enum.Parse<%s.%s>", pkg, name)
-		default:
-			panic(fmt.Sprintf(
-				"Unsafe enum conversions from type %s not implemented yet: %s => %s",
-				from.Type(), from, to))
+		} else {
+			// for numeric enums, we new up the type that is generated for that enum
+			convertFn = fmt.Sprintf("new %s.%s", pkg, name)
```
Comment (justinvp) [inline pkg/codegen/dotnet/gen_program_expressions.go:419]: Is there a test that demonstrates this? Do we really use `new`?

Comment (Zaid-Ajaj) [reply pkg/codegen/dotnet/gen_program_expressions.go:419]: I looked at the generated and their was a constructor that accepts `double` but now I checked again and that constructor is `private` 😅 
```cs
private TeamStackPermissionScope(double value)
```
there is actually no way to construct the enum from a number (it's generated as a struct). I changed the previous behaviour because it was panicking _too_ early and unnecessarily so I though I would just fix it but this won't do. Will bring back the previous behaviour without redundantly panicking. Also we could change sdk-gen in dotnet to make the constructor public or add an implicit cast operator but that is for another PR.

File: pkg/codegen/docs/constructor_syntax_generator_test.go (hunk 1 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/docs/constructor_syntax_generator_test.go]: Done ✅

File: pkg/codegen/dotnet/gen_program_expressions.go (hunk 2 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/dotnet/gen_program_expressions.go]: Old behaviour is back without panicking too early ✅ constructing a numeric enum from a number value will be handled in a separate PR

**Review by Frassle — APPROVED** [review]
Mostly looks ok, odd that java and yaml are using the numeric values rather than enums though? Is that because they need fixes in their code generators?

**Comment by Zaid-Ajaj** [comment]
> Is that because they need fixes in their code generators?

@Frassle that's right
